In [3]:
import sqlalchemy
from sqlalchemy import create_engine, Table, Column, Integer, String, ForeignKey, MetaData, DateTime, Float
from sqlalchemy.orm.session import Session, sessionmaker, query
from sqlalchemy.ext.declarative import declarative_base
base = declarative_base()

In [4]:
engine = create_engine('sqlite:///child_abuse_detection_database.db',echo=True)

In [5]:
class Location(base):
    __tablename__ = 'location'
    id = Column(Integer, primary_key=True)
    name = Column(Integer, nullable=False)

In [6]:
class User(base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String, nullable=False)
    pw = Column(String, nullable=False)
    office_num = Column(Integer, nullable=False)
    department = Column(String, nullable=False)
    name = Column(String, nullable=False)
    ph_num1 = Column(String, nullable=False)
    ph_num2 = Column(String, nullable=False)
    ph_num3 = Column(String, nullable=False)
    loc_id = Column(ForeignKey(Location.id))

In [7]:
class DaycareCenter(base):
    __tablename__ = 'daycare_center'
    
    id = Column(Integer, primary_key=True)
    name = Column(Integer, nullable=False)
    chief_staff_name = Column(String, nullable=False)
    address = Column(String, nullable=False)
    ph_num1 = Column(String, nullable=False)
    ph_num2 = Column(String, nullable=False)
    ph_num3 = Column(String, nullable=False)
    loc_id = Column(ForeignKey(Location.id))

In [8]:
class Video(base):
    __tablename__ = 'video'
    
    id = Column(Integer, primary_key=True)
    detection_time = Column(Integer, nullable=False)
    name = Column(String, nullable=False)
    accuracy = Column(Float, nullable=False)
    status = Column(String, nullable=False)
    loc_id = Column(ForeignKey(Location.id))
    dc_id = Column(ForeignKey(DaycareCenter.id))

In [9]:
class ReportList(base):
    __tablename__ = 'report_list'
    
    id = Column(Integer, primary_key=True)
    time = Column(Integer, nullable=False) 
    police_name = Column(String, nullable=False) 
    status = Column(String, nullable=False) 

    loc_id = Column(ForeignKey(Location.id))
    dc_id = Column(ForeignKey(DaycareCenter.id))
    vid_id = Column(ForeignKey(Video.id))

In [10]:
base.metadata.create_all(engine)

2021-08-18 17:40:38,853 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-08-18 17:40:38,856 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,858 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-08-18 17:40:38,859 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,860 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("location")
2021-08-18 17:40:38,861 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,864 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("location")
2021-08-18 17:40:38,864 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,866 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("user")
2021-08-18 17:40:38,866 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,868 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("user")
2021-08-18 17:40:38,869 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,869 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("daycare_center")
2021-08-18 17:40:38,870 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,871 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("daycare_center")
2021-08-18 17:40:38,873 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,874 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("video")
2021-08-18 17:40:38,875 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,876 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("video")
2021-08-18 17:40:38,877 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,878 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("report_list")
2021-08-18 17:40:38,878 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,880 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("report_list")
2021-08-18 17:40:38,881 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,883 INFO sqlalchemy.engine.base.Engine
CREATE TABLE location (
	id INTEGER NOT NULL,
	name INTEGER NOT NULL,
	PRIMARY KEY (id)
)


2021-08-18 17:40:38,883 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,903 INFO sqlalchemy.engine.base.Engine COMMIT
2021-08-18 17:40:38,905 INFO sqlalchemy.engine.base.Engine
CREATE TABLE user (
	id INTEGER NOT NULL,
	email VARCHAR NOT NULL,
	pw VARCHAR NOT NULL,
	office_num INTEGER NOT NULL,
	department VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	ph_num1 VARCHAR NOT NULL,
	ph_num2 VARCHAR NOT NULL,
	ph_num3 VARCHAR NOT NULL,
	loc_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(loc_id) REFERENCES location (id)
)


2021-08-18 17:40:38,905 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,924 INFO sqlalchemy.engine.base.Engine COMMIT
2021-08-18 17:40:38,926 INFO sqlalchemy.engine.base.Engine
CREATE TABLE daycare_center (
	id INTEGER NOT NULL,
	name INTEGER NOT NULL,
	chief_staff_name VARCHAR NOT NULL,
	address VARCHAR NOT NULL,
	ph_num1 VARCHAR NOT NULL,
	ph_num2 VARCHAR NOT NULL,
	ph_num3 VARCHAR NOT NULL,
	loc_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(loc_id) REFERENCES location (id)
)


2021-08-18 17:40:38,927 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,944 INFO sqlalchemy.engine.base.Engine COMMIT
2021-08-18 17:40:38,945 INFO sqlalchemy.engine.base.Engine
CREATE TABLE video (
	id INTEGER NOT NULL,
	detection_time INTEGER NOT NULL,
	name VARCHAR NOT NULL,
	accuracy FLOAT NOT NULL,
	status VARCHAR NOT NULL,
	loc_id INTEGER,
	dc_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(loc_id) REFERENCES location (id),
	FOREIGN KEY(dc_id) REFERENCES daycare_center (id)
)


2021-08-18 17:40:38,947 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,968 INFO sqlalchemy.engine.base.Engine COMMIT
2021-08-18 17:40:38,969 INFO sqlalchemy.engine.base.Engine
CREATE TABLE report_list (
	id INTEGER NOT NULL,
	time INTEGER NOT NULL,
	police_name VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	loc_id INTEGER,
	dc_id INTEGER,
	vid_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY(loc_id) REFERENCES location (id),
	FOREIGN KEY(dc_id) REFERENCES daycare_center (id),
	FOREIGN KEY(vid_id) REFERENCES video (id)
)


2021-08-18 17:40:38,972 INFO sqlalchemy.engine.base.Engine ()
2021-08-18 17:40:38,989 INFO sqlalchemy.engine.base.Engine COMMIT

# Creating Dummy Data

In [84]:
import numpy as np
import datetime
import time
import string
import re

In [85]:
sess = sessionmaker()
session = sess(bind=engine)

In [86]:
def create_random_phone_num():
    num1 = 10
    num2 = np.random.randint(0,10000)
    num3 = np.random.randint(0,10000)
    return num1, num2, num3

In [87]:
def create_random_name():
    lastname = list('김이박최정강조윤장임한오서신권황안송류전')
    firstname = ['정웅','영철','영식','영철','성진','정운','준혁','준서',
                 '영길','정수','성수','정호','지훈','동현','준호','민재',
                 '영일','종수','성호','영진','상훈','성호','준영','민석',
                 '도현','건우','예준','정수','정식','상철','병철','성민',
                 '민수','지훈','예준','건우','정남','정호','종수','진호',
                 '영진','준호','준호','준혁','준영','현준','광수','영환',
                 '영자','순자','미경','미영','지영','지혜','유진','서연',
                 '정자','미숙','은정','지은','민지','민서','정순','경회',
                 '수빈','서현','영숙','경숙','은영','현정','혜진','지원',
                 '경자','은경','은영','지영','지은','민지','예은','지민']
    last = np.random.choice(lastname, 1)
    first = np.random.choice(firstname,1)
    return last[0] + first[0]

In [88]:
def create_random_time():
    return np.random.randint(0,164000000,10) * 10

In [89]:
def create_random_email():
    alpha = list(string.ascii_lowercase)
    number = list('0123456789')
    domain = ['gmail.com','naver.com','google.com','daum.net','aspo.dor','foke.ok','github.io','please.work','korea.ac.kr','kakao.com']
    n = np.random.randint(1,7)
    k = 10-n
    return ''.join(np.random.choice(alpha,n)) + ''.join(np.random.choice(number,k)) + '@'+''.join(np.random.choice(domain,1))

In [90]:
def create_random_password():
    alpha = list(string.ascii_lowercase)
    number = list('0123456789')
    data = alpha + number
    return ''.join(np.random.choice(data,10))

In [91]:
def create_random_office_num():
    number = list('123456789')
    return ''.join(np.random.choice(number,8))

In [92]:
def create_random_department():
    dep = '''균형발전본부, 균형발전기획관, 균형발전정책과, 도시활성화과, 주거재생과, 주거환경과, 도심권사업과, 한옥정책과, 안전총괄실, 안전총괄관, 안전총괄과, 상황대응과, 시설안전과, 도로계획과, 광화문광장추진단, 감염병연구센터, 여성가족정책실, 여성권익담당관, 여성정책담당관, 보육담당관, 외국인다문화담당관, 가족담당관, 아이돌봄담당관, 온마을돌봄추진단, 공공개발기획단, 동물보호과, 미래청년기획단, 청년정책반, 청년사업반, 국제교류담당관, 인생이모작담당관, 행정국, 총무과, 인사과, 자치행정과, 인력개발과, 정보공개정책과, 법률자문검사, 국회협력관, 시장단, 코로나19대응지원과, 1인가구특별대책추진단, 기획조정실, 정책기획관, 기획담당관, 조직담당관, 평가협업담당관, 법무담당관, 대외협력담당관, 재정기획관, 예산담당관, 재정담당관, 공기업담당관, 법률지원담당관, 식품정책과, 복지정책실, 복지기획관, 복지정책과, 지역돌봄복지과, 어르신복지과, 자활지원과, 시민건강국, 보건의료정책과, 건강증진과, 감염병관리과, 비상기획관, 민방위담당관, 도로관리과, 도로시설과, 건설혁신과, 동남권사업과, 동북권사업과, 서부권사업과, 교량안전과, 대변인, 언론담당관, 인권담당관, 시민소통기획관, 시민소통담당관, 시민봉사담당관, 뉴미디어담당관, 도시브랜드담당관, 장애인자립지원과, 장애인복지정책과, 시민봉사담당관(열린민원실)'''
    department = re.sub(' ','',dep).split(',')
    return np.random.choice(department,1)[0]

In [93]:
def convert_datetime(unixtime):
    """Convert unixtime to datetime"""
    date = datetime.datetime.fromtimestamp(unixtime).strftime('%Y-%m-%d %H:%M:%S')
    return date # format : str

def convert_unixtime(date_time):
    """Convert datetime to unixtime"""
    unixtime = datetime.datetime.strptime(date_time,'%Y-%m-%d %H:%M:%S').timestamp()
    return unixtime

In [94]:
for i in range(10,24):
    p_num1,p_num2, p_num3 = create_random_phone_num()
    user_1 = User(email=create_random_email(), 
                  pw=create_random_password(), 
                  office_num=create_random_office_num(),
                  department=create_random_department(),
                  name=create_random_name(),
                  ph_num1=p_num1,
                  ph_num2=p_num2,
                  ph_num3=p_num3, 
                  loc_id=i+2)
    session.add(user_1)

In [95]:
session.commit()

2021-08-18 18:34:19,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 18:34:19,856 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,857 INFO sqlalchemy.engine.base.Engine ('ltp7162483@korea.ac.kr', 'x7w63fszs2', '85667212', '시민봉사담당관(열린민원실)', '한은정', 10, 179, 653, 12)
2021-08-18 18:34:19,861 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,862 INFO sqlalchemy.engine.base.Engine ('ywhrw32383@naver.com', '219ple5zlw', '24476128', '공기업담당관', '서영숙', 10, 1255, 137, 13)
2021-08-18 18:34:19,863 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,864 INFO sqlalchemy.engine.base.Engine ('hmgpsa5623@github.io', 'e6ipo143f6', '97515527', '도로관리과', '박준영', 10, 5661, 8152, 14)
2021-08-18 18:34:19,865 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,866 INFO sqlalchemy.engine.base.Engine ('qvuaw15948@please.work', 'bow4fx5iks', '93353842', '도로관리과', '박혜진', 10, 7746, 7589, 15)
2021-08-18 18:34:19,867 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,867 INFO sqlalchemy.engine.base.Engine ('h123415666@daum.net', 'or23l2ban7', '98259858', '예산담당관', '류성호', 10, 311, 4181, 16)
2021-08-18 18:34:19,868 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,869 INFO sqlalchemy.engine.base.Engine ('iyzt822642@aspo.dor', '2rhoinszfb', '37186497', '대외협력담당관', '윤준호', 10, 7113, 3824, 17)
2021-08-18 18:34:19,870 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,871 INFO sqlalchemy.engine.base.Engine ('aox5142093@google.com', 'oaghbo7az2', '43384749', '대변인', '전현준', 10, 5836, 2753, 18)
2021-08-18 18:34:19,872 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,873 INFO sqlalchemy.engine.base.Engine ('s166813538@google.com', 'k28hzho4oi', '81719572', '코로나19대응지원과', '서미숙', 10, 4011, 2597, 19)
2021-08-18 18:34:19,874 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,875 INFO sqlalchemy.engine.base.Engine ('uyn1705398@please.work', '3n99zew7bx', '18148459', '도시활성화과', '장지훈', 10, 7544, 1515, 20)
2021-08-18 18:34:19,876 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,876 INFO sqlalchemy.engine.base.Engine ('ridz830812@foke.ok', 'ww4fjbil87', '97353281', '동북권사업과', '임유진', 10, 1621, 801, 21)
2021-08-18 18:34:19,877 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,878 INFO sqlalchemy.engine.base.Engine ('jh61841047@google.com', 'fv94yngnev', '79933464', '법률자문검사', '장영식', 10, 5733, 1331, 22)
2021-08-18 18:34:19,881 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,882 INFO sqlalchemy.engine.base.Engine ('umho931468@foke.ok', 'zfxxfdwnoh', '72476987', '여성가족정책실', '신준서', 10, 610, 755, 23)
2021-08-18 18:34:19,883 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,884 INFO sqlalchemy.engine.base.Engine ('srn7166798@daum.net', 'nqw62bvtq0', '46811237', '균형발전정책과', '송준호', 10, 6412, 8381, 24)
2021-08-18 18:34:19,886 INFO sqlalchemy.engine.base.Engine INSERT INTO user (email, pw, office_num, department, name, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-08-18 18:34:19,887 INFO sqlalchemy.engine.base.Engine ('i263735542@aspo.dor', '84njveoy0c', '23573891', '1인가구특별대책추진단', '정준호', 10, 2385, 7328, 25)
2021-08-18 18:34:19,889 INFO sqlalchemy.engine.base.Engine COMMIT

In [23]:
location_list = '''강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,동대문구,동작구,마포구,서대문구,서초구,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구'''.split(',')

In [24]:
for idx, loc in enumerate(location_list):
    location = Location(id=idx+1, name='서울특별시 '+loc)
    session.add(location)
session.commit()

2021-08-18 17:40:47,143 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 17:40:47,146 INFO sqlalchemy.engine.base.Engine INSERT INTO location (id, name) VALUES (?, ?)
2021-08-18 17:40:47,147 INFO sqlalchemy.engine.base.Engine ((1, '서울특별시 강남구'), (2, '서울특별시 강동구'), (3, '서울특별시 강북구'), (4, '서울특별시 강서구'), (5, '서울특별시 관악구'), (6, '서울특별시 광진구'), (7, '서울특별시 구로구'), (8, '서울특별시 금천구')  ... displaying 10 of 25 total bound parameter sets ...  (24, '서울특별시 중구'), (25, '서울특별시 중랑구'))
2021-08-18 17:40:47,153 INFO sqlalchemy.engine.base.Engine COMMIT

In [25]:
for idx, loc in enumerate(location_list):
    print(idx+1, loc )

1 강남구
2 강동구
3 강북구
4 강서구
5 관악구
6 광진구
7 구로구
8 금천구
9 노원구
10 도봉구
11 동대문구
12 동작구
13 마포구
14 서대문구
15 서초구
16 성동구
17 성북구
18 송파구
19 양천구
20 영등포구
21 용산구
22 은평구
23 종로구
24 중구
25 중랑구

In [26]:
import pandas as pd

In [27]:
daycare_center = pd.read_csv('C:/Users/Seogki/GoogleDrive/데이터청년캠퍼스_고려대과정/child-abuse-detection/data/daycare_center.csv')

In [28]:
daycare_center.drop(columns=['Unnamed: 0'], axis=1, inplace=True)

In [29]:
daycare_center.head()

            name   phone number                                        address
0         예솔어린이집    02-857-1113           서울특별시 금천구 벚꽃로 100 ,105동 102호 (독산제1동)
1       반포예원어린이집    02-537-3921           서울특별시 서초구 사평대로 240 ,502동 107호 (반포4동)
2       구립푸른어린이집  010-2249-9250  서울특별시 동작구 동작대로35길 46 ,이수푸르지오더프레티움 관리동 (사당제2동)
3  서초구립 라클라스어린이집    02-534-2122                     서울특별시 서초구 서초중앙로 206 (반포1동)
4      위례바른숲어린이집    02-401-7001                     서울특별시 송파구 위례송파로5길 16 (위례동)

In [30]:
def find_locid(address):
    location_list = '''강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,동대문구,동작구,마포구,서대문구,서초구,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구'''.split(',')
    gu = address.split(' ')[1]
    return location_list.index(gu) + 1

In [31]:
for center in daycare_center.iterrows():
    p_num1,p_num2, p_num3 = center[1]['phone number'].split('-')
    dcc = DaycareCenter(
        name= center[1]['name'],
        chief_staff_name=create_random_name(),
        address=center[1]['address'],
        ph_num1=p_num1,
        ph_num2=p_num2,
        ph_num3=p_num3, 
        loc_id = find_locid(center[1]['address'])
    )
    #print(center[1]['name'],create_random_name(),center[1]['address'],p_num1,p_num2,p_num3,find_locid(center[1]['address']))
    session.add(dcc)

In [32]:
session.commit()

2021-08-18 17:40:57,750 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 17:40:57,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,791 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '안영숙', '서울특별시 금천구 벚꽃로 100 ,105동 102호 (독산제1동)', '02', '857', '1113', 8)
2021-08-18 17:40:57,798 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,801 INFO sqlalchemy.engine.base.Engine ('반포예원어린이집', '오성호', '서울특별시 서초구 사평대로 240 ,502동 107호 (반포4동)', '02', '537', '3921', 15)
2021-08-18 17:40:57,803 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,804 INFO sqlalchemy.engine.base.Engine ('구립푸른어린이집', '박미영', '서울특별시 동작구 동작대로35길 46 ,이수푸르지오더프레티움 관리동 (사당제2동)', '010', '2249', '9250', 12)
2021-08-18 17:40:57,805 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,806 INFO sqlalchemy.engine.base.Engine ('서초구립 라클라스어린이집', '최경회', '서울특별시 서초구 서초중앙로 206 (반포1동)', '02', '534', '2122', 15)
2021-08-18 17:40:57,807 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,808 INFO sqlalchemy.engine.base.Engine ('위례바른숲어린이집', '임동현', '서울특별시 송파구 위례송파로5길 16 (위례동)', '02', '401', '7001', 18)
2021-08-18 17:40:57,810 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,810 INFO sqlalchemy.engine.base.Engine ('봄빛어린이집', '임성수', '서울특별시 금천구 벚꽃로 100 ,독산역롯데캐슬아파트 106동 103호 (독산제1동)', '02', '892', '2006', 8)
2021-08-18 17:40:57,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,813 INFO sqlalchemy.engine.base.Engine ('구립 푸른들어린이집', '권경숙', '서울특별시 은평구 은평로 240 (응암제1동)', '02', '6748', '0202', 22)
2021-08-18 17:40:57,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,815 INFO sqlalchemy.engine.base.Engine ('구립독산롯데캐슬어린이집', '임성호', '서울특별시 금천구 벚꽃로 100 ,독산역 롯데캐슬아파트 단지내 (독산제1동)', '02', '805', '7605', 8)
2021-08-18 17:40:57,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,817 INFO sqlalchemy.engine.base.Engine ('근로복지공단 마포어린이집', '서경회', '서울특별시 마포구 연남로 49-1 (연남동)', '02', '322', '7333', 13)
2021-08-18 17:40:57,819 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,820 INFO sqlalchemy.engine.base.Engine ('위례아이숲어린이집', '장준영', '서울특별시 송파구 위례북로 30 ,(거여동, 위례포레샤인 17단지) (위례동)', '02', '448', '1718', 18)
2021-08-18 17:40:57,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,823 INFO sqlalchemy.engine.base.Engine ('구립 꿈여울어린이집', '조종수', '서울특별시 은평구 통일로89길 5-6 (갈현제1동)', '02', '358', '2525', 22)
2021-08-18 17:40:57,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,827 INFO sqlalchemy.engine.base.Engine ('구립 자양도담어린이집', '조영철', '서울특별시 광진구 아차산로44가길 5 ,(자양동 231-51) (자양제1동)', '02', '455', '7000', 6)
2021-08-18 17:40:57,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,829 INFO sqlalchemy.engine.base.Engine ('구립 중곡하나어린이집', '김영일', '서울특별시 광진구 동일로76길 59 (중곡제3동)', '02', '465', '1004', 6)
2021-08-18 17:40:57,831 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,831 INFO sqlalchemy.engine.base.Engine ('근로복지공단 곰달래어린이집', '서정호', '서울특별시 강서구 곰달래로53길 30-20 (화곡제4동)', '02', '2646', '7142', 4)
2021-08-18 17:40:57,833 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,835 INFO sqlalchemy.engine.base.Engine ('원진어린이집', '이정수', '서울특별시 구로구 고척로55길 21 ,(고척동, 원진어린이집) (고척제2동)', '02', '2684', '7444', 7)
2021-08-18 17:40:57,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,838 INFO sqlalchemy.engine.base.Engine ('성민가정어린이집', '서경회', '서울특별시 강서구 화곡로68길 115 ,101동 111호 (등촌제1동)', '02', '6093', '8643', 4)
2021-08-18 17:40:57,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,842 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '한준서', '서울특별시 마포구 대흥로24길 24 ,마포프레스티지자이 1단지 내 104동 앞 (염리동)', '02', '2088', '7212', 13)
2021-08-18 17:40:57,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,844 INFO sqlalchemy.engine.base.Engine ('해들어린이집', '신영식', '서울특별시 마포구 숭문16다길 10-5 ,마포프레스티지자이 2단지 내 203동 옆 (염리동)', '02', '716', '2007', 13)
2021-08-18 17:40:57,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,847 INFO sqlalchemy.engine.base.Engine ('강남구육아종합지원센터(분원점)', '정순자', '서울특별시 강남구 봉은사로114길 43 (삼성1동)', '02', '568', '1792', 1)
2021-08-18 17:40:57,849 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,850 INFO sqlalchemy.engine.base.Engine ('구립 아이샘어린이집', '한정자', '서울특별시 양천구 중앙로43길 14 ,래미안목동아델리체 (신정3동)', '02', '6953', '2911', 19)
2021-08-18 17:40:57,852 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,853 INFO sqlalchemy.engine.base.Engine ('구립 아이숲어린이집', '조정웅', '서울특별시 양천구 중앙로43길 14 ,래미안목동아델리체 (신정3동)', '02', '2605', '0061', 19)
2021-08-18 17:40:57,855 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,855 INFO sqlalchemy.engine.base.Engine ('로카키즈어린이집', '박준서', '서울특별시 종로구 새문안로2길 10 ,1층 (사직동)', '02', '739', '8042', 23)
2021-08-18 17:40:57,857 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,858 INFO sqlalchemy.engine.base.Engine ('숲속별어린이집', '정영철', '서울특별시 서대문구 홍은중앙로3길 9 ,북한산두산위브아파트 (홍은제1동)', '02', '395', '9565', 14)
2021-08-18 17:40:57,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,860 INFO sqlalchemy.engine.base.Engine ('위례봄어린이집', '최지은', '서울특별시 송파구 위례광장로 121 ,2414동 101호 (위례동)', '02', '400', '8544', 18)
2021-08-18 17:40:57,861 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,864 INFO sqlalchemy.engine.base.Engine ('도토리소풍넥슨 대치어린이집', '정영식', '서울특별시 강남구 역삼로90길 25 (대치2동)', '02', '565', '7900', 1)

2021-08-18 17:40:57,865 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,866 INFO sqlalchemy.engine.base.Engine ('쿠키즈(coukids) 어린이집', '이건우', '서울특별시 강남구 테헤란로 332 ,HJ타워 3층 (역삼2동)', '02', '6204', '2114', 1)
2021-08-18 17:40:57,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,868 INFO sqlalchemy.engine.base.Engine ('라온어린이집', '박성민', '서울특별시 영등포구 신길로 29 (대림제1동)', '02', '842', '9376', 20)
2021-08-18 17:40:57,870 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,871 INFO sqlalchemy.engine.base.Engine ('삼각지어린이집', '정미영', '서울특별시 용산구 백범로99길 40 ,1,2층 (한강로동)', '02', '6273', '4200', 21)
2021-08-18 17:40:57,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,874 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '정현정', '서울특별시 서대문구 홍은중앙로1길 100 (홍은제1동)', '02', '6956', '1530', 14)
2021-08-18 17:40:57,876 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,876 INFO sqlalchemy.engine.base.Engine ('근로복지공단 등촌어린이집', '오영길', '서울특별시 강서구 강서로56나길 128 (등촌제3동)', '02', '2659', '3370', 4)
2021-08-18 17:40:57,878 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,879 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '강수빈', '서울특별시 동작구 상도로 421 ,현대아파트 108-103 (상도제1동)', '02', '888', '8646', 12)
2021-08-18 17:40:57,880 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,881 INFO sqlalchemy.engine.base.Engine ('구립 라온어린이집', '김민재', '서울특별시 강서구 곰달래로53길 112 (화곡제4동)', '02', '2655', '0644', 4)
2021-08-18 17:40:57,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,883 INFO sqlalchemy.engine.base.Engine ('구립 목3동공원어린이집', '류준혁', '서울특별시 양천구 목동중앙남로16나길 46 (목3동)', '02', '2645', '3220', 19)
2021-08-18 17:40:57,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,886 INFO sqlalchemy.engine.base.Engine ('구립 아인어린이집', '최지훈', '서울특별시 양천구 목동중앙남로3길 23-1 (목4동)', '02', '2647', '8798', 19)
2021-08-18 17:40:57,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,889 INFO sqlalchemy.engine.base.Engine ('구립 해든어린이집', '박민수', '서울특별시 양천구 목동남로4길 100 (신정7동)', '02', '6956', '2454', 19)
2021-08-18 17:40:57,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,892 INFO sqlalchemy.engine.base.Engine ('구립아름어린이집', '장정수', '서울특별시 동작구 양녕로 220 ,상도역롯데캐슬아파트 관리동 (상도제2동)', '02', '821', '2021', 12)
2021-08-18 17:40:57,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,894 INFO sqlalchemy.engine.base.Engine ('구립지혜어린이집', '임준서', '서울특별시 금천구 시흥대로76길 19 ,골드빌 101호 (시흥제1동)', '02', '891', '7942', 8)
2021-08-18 17:40:57,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,896 INFO sqlalchemy.engine.base.Engine ('구립트윈파크어린이집', '신정운', '서울특별시 동작구 노량진로23가길 23 ,래미안트윈파크아파트 관리동 (노량진제1동)', '02', '3280', '2320', 12)
2021-08-18 17:40:57,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,898 INFO sqlalchemy.engine.base.Engine ('꿈동산어린이집', '황민지', '서울특별시 구로구 남부순환로95길 16 ,101동 101호(개봉동, 삼호아파트) (개봉제2동)', '02', '2618', '9382', 7)
2021-08-18 17:40:57,901 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,902 INFO sqlalchemy.engine.base.Engine ('느티나무어린이집', '송혜진', '서울특별시 도봉구 도당로13바길 19 (방학제2동)', '02', '3493', '0228', 10)
2021-08-18 17:40:57,904 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,905 INFO sqlalchemy.engine.base.Engine ('늘봄어린이집', '송건우', '서울특별시 도봉구 우이천로 487-1 (쌍문제1동)', '02', '996', '5311', 10)
2021-08-18 17:40:57,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,908 INFO sqlalchemy.engine.base.Engine ('도봉숲어린이집', '안서연', '서울특별시 도봉구 마들로 684-10 (도봉제2동)', '02', '956', '7474', 10)
2021-08-18 17:40:57,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,910 INFO sqlalchemy.engine.base.Engine ('봄날어린이집', '정준호', '서울특별시 도봉구 덕릉로53길 55 (창제2동)', '02', '6368', '0825', 10)
2021-08-18 17:40:57,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,912 INFO sqlalchemy.engine.base.Engine ('새빛어린이집', '최성민', '서울특별시 마포구 백범로31길 8 ,202동 1층 (아현동)', '02', '6951', '1317', 13)
2021-08-18 17:40:57,913 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,914 INFO sqlalchemy.engine.base.Engine ('서초구립 서초3동하나어린이집', '이정수', '서울특별시 서초구 명달로11길 16 (서초3동)', '02', '523', '6777', 15)
2021-08-18 17:40:57,916 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,917 INFO sqlalchemy.engine.base.Engine ('서초구립 한신서래어린이집', '안지민', '서울특별시 서초구 사평대로28길 31 ,101동 108호 (반포4동)', '02', '533', '9631', 15)
2021-08-18 17:40:57,918 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,921 INFO sqlalchemy.engine.base.Engine ('서초구립 허니비어린이집', '윤경자', '서울특별시 서초구 서초대로1길 30 ,105동 101호(방배동, 현대아파트) (방배4동)', '02', '535', '7957', 15)
2021-08-18 17:40:57,922 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,923 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '조정순', '서울특별시 중랑구 봉우재로2길 22 (면목제2동)', '02', '432', '5799', 25)
2021-08-18 17:40:57,924 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,925 INFO sqlalchemy.engine.base.Engine ('온유한어린이집', '강혜진', '서울특별시 도봉구 덕릉로60자길 22 (창제3동)', '02', '906', '1842', 10)
2021-08-18 17:40:57,926 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,927 INFO sqlalchemy.engine.base.Engine ('태양하나어린이집', '최민서', '서울특별시 동대문구 황물로 32 (답십리제1동)', '02', '2245', '9544', 11)
2021-08-18 17:40:57,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:57,929 INFO sqlalchemy.engine.base.Engine ('포레나아이어린이집', '이상훈', '서울특별시 노원구 노원로38길 76 (상계10동)', '02', '937', '3263', 9)
2021-08-18 17:40:57,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,931 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '서민지', '서울특별시 마포구 서강로 75-16 ,창전동 청년주택 1층 (서강동)', '02', '6956', '0015', 13)
2021-08-18 17:40:57,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,934 INFO sqlalchemy.engine.base.Engine ('현대열린어린이집', '신은경', '서울특별시 구로구 개봉로20길 6 ,현대아파트 1단지내(개봉역입구쪽) (개봉제2동)', '02', '6091', '1004', 7)
2021-08-18 17:40:57,936 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,937 INFO sqlalchemy.engine.base.Engine ('자이숲어린이집', '신준호', '서울특별시 강동구 상일로 55 ,119동 103호(상일동, 고덕자이) (상일제1동)', '02', '441', '9002', 2)
2021-08-18 17:40:57,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,940 INFO sqlalchemy.engine.base.Engine ('삼성서울병원2 어린이집', '권예은', '서울특별시 강남구 양재대로55길 12 (일원1동)', '02', '3411', '3140', 1)
2021-08-18 17:40:57,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,943 INFO sqlalchemy.engine.base.Engine ('KB여의도어린이집', '신성호', '서울특별시 영등포구 국제금융로8길 26 ,1층 (여의동)', '02', '6332', '5051', 20)
2021-08-18 17:40:57,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,945 INFO sqlalchemy.engine.base.Engine ('서울아산병원제2어린이집', '한지원', '서울특별시 송파구 강동대로 13 (풍납2동)', '02', '2045', '3935', 18)
2021-08-18 17:40:57,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,947 INFO sqlalchemy.engine.base.Engine ('구립 은빛나래어린이집', '권미경', '서울특별시 은평구 서오릉로9길 18 (역촌동)', '02', '3157', '2777', 22)
2021-08-18 17:40:57,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,949 INFO sqlalchemy.engine.base.Engine ('구립가래여울어린이집', '윤정호', '서울특별시 강동구 아리수로93나길 88 ,강동리버스트8단지아파트관리동 (강일동)', '02', '441', '3690', 2)
2021-08-18 17:40:57,950 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,951 INFO sqlalchemy.engine.base.Engine ('구립도로롱어린이집', '윤수빈', '서울특별시 강동구 고덕로98길 160 ,강동리엔파크14단지아파트 관리동 (상일제2동)', '02', '441', '0103', 2)
2021-08-18 17:40:57,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,952 INFO sqlalchemy.engine.base.Engine ('삼전하늘어린이집', '박준서', '서울특별시 송파구 삼전로10길 21 (삼전동)', '02', '418', '3721', 18)
2021-08-18 17:40:57,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,954 INFO sqlalchemy.engine.base.Engine ('석촌새싹어린이집', '권현정', '서울특별시 송파구 가락로11길 9-18 (석촌동)', '02', '423', '1860', 18)
2021-08-18 17:40:57,955 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,956 INFO sqlalchemy.engine.base.Engine ('구립해뜨는어린이집', '김종수', '서울특별시 강동구 고덕로98길 101 ,강동리엔파크11단지아파트 관리동 (상일제2동)', '02', '3426', '7775', 2)
2021-08-18 17:40:57,957 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,958 INFO sqlalchemy.engine.base.Engine ('꿈빛어린이집', '정정식', '서울특별시 마포구 백범로31길 7 ,공덕SK리더스뷰 103동 1층 (아현동)', '02', '6953', '3800', 13)
2021-08-18 17:40:57,960 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,960 INFO sqlalchemy.engine.base.Engine ('구립 우장숲어린이집', '임미숙', '서울특별시 강서구 화곡로41길 19 (우장산동)', '02', '2691', '3690', 4)
2021-08-18 17:40:57,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,962 INFO sqlalchemy.engine.base.Engine ('구립새봄어린이집', '윤민석', '서울특별시 동작구 사당로9길 11-13 (사당제3동)', '02', '532', '3330', 12)
2021-08-18 17:40:57,964 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,964 INFO sqlalchemy.engine.base.Engine ('구립은솔어린이집', '서영환', '서울특별시 동작구 상도로 346-1 ,힐스테이트상도 111동 101호 (상도제1동)', '02', '824', '2021', 12)
2021-08-18 17:40:57,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,966 INFO sqlalchemy.engine.base.Engine ('동심어린이집', '안순자', '서울특별시 중랑구 용마공원로3길 40 (망우본동)', '02', '432', '6461', 25)
2021-08-18 17:40:57,968 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,969 INFO sqlalchemy.engine.base.Engine ('푸르니어린이집', '김현준', '서울특별시 구로구 신도림로 16 ,302동 104호 (신도림동)', '02', '2633', '3389', 7)
2021-08-18 17:40:57,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,970 INFO sqlalchemy.engine.base.Engine ('하영어린이집', '황은정', '서울특별시 구로구 신도림로 16 ,406동102호 (신도림동)', '02', '2672', '3331', 7)
2021-08-18 17:40:57,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,972 INFO sqlalchemy.engine.base.Engine ('한나어린이집', '장수빈', '서울특별시 서대문구 가재울로 45 ,103동 105호 (남가좌제2동)', '02', '374', '1005', 14)
2021-08-18 17:40:57,974 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,975 INFO sqlalchemy.engine.base.Engine ('마곡9 나인어린이집', '전상철', '서울특별시 강서구 공항대로 103 ,엠밸리9단지 관리동 (공항동)', '02', '6956', '5573', 4)
2021-08-18 17:40:57,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,979 INFO sqlalchemy.engine.base.Engine ('도토리집공동육아어린이집', '박순자', '서울특별시 강북구 삼각산로4길 36 ,나호 (인수동)', '02', '907', '1300', 3)
2021-08-18 17:40:57,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,981 INFO sqlalchemy.engine.base.Engine ('송파든든어린이집', '권현준', '서울특별시 송파구 위례서이로 25 (위례동)', '02', '407', '0301', 18)
2021-08-18 17:40:57,982 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,983 INFO sqlalchemy.engine.base.Engine ('구립또바기어린이집', '신은영', '서울특별시 강동구 상일로 55 ,고덕자이아파트 관리동 (상일제1동)', '02', '441', '3215', 2)
2021-08-18 17:40:57,984 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,985 INFO sqlalchemy.engine.base.Engine ('서초구립 래미안리더스원어린이집', '김지원', '서울특별시 서초구 서운로 62 (서초2동)', '02', '522', '6260', 15)

2021-08-18 17:40:57,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,988 INFO sqlalchemy.engine.base.Engine ('자연아이어린이집', '정병철', '서울특별시 성북구 돌곶이로40길 46 (장위제1동)', '02', '909', '3567', 17)
2021-08-18 17:40:57,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,990 INFO sqlalchemy.engine.base.Engine ('구립가람슬기어린이집', '임은경', '서울특별시 강동구 올림픽로98가길 12-16 (암사제1동)', '02', '6012', '8957', 2)
2021-08-18 17:40:57,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,992 INFO sqlalchemy.engine.base.Engine ('신길파크자이솔숲어린이집', '한정호', '서울특별시 영등포구 신길로28길 25 (신길제6동)', '02', '6269', '1900', 20)
2021-08-18 17:40:57,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,994 INFO sqlalchemy.engine.base.Engine ('구립 염창별하어린이집', '최지은', '서울특별시 강서구 공항대로 543 (염창동)', '02', '3662', '7942', 4)
2021-08-18 17:40:57,995 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,995 INFO sqlalchemy.engine.base.Engine ('보배사랑어린이집', '임동현', '서울특별시 구로구 중앙로12길 7 ,101동 101호 (고척제2동)', '02', '2619', '3377', 7)
2021-08-18 17:40:57,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,997 INFO sqlalchemy.engine.base.Engine ('삼성어린이집', '박예은', '서울특별시 동대문구 한천로26길 43 (장안제1동)', '02', '2243', '5033', 11)
2021-08-18 17:40:57,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:57,999 INFO sqlalchemy.engine.base.Engine ('거여하나어린이집', '최성진', '서울특별시 송파구 오금로 475 (거여1동)', '02', '402', '2010', 18)
2021-08-18 17:40:58,001 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,002 INFO sqlalchemy.engine.base.Engine ('구립 이든아이어린이집', '이상철', '서울특별시 강서구 까치산로18나길 22-1 (화곡본동)', '02', '2605', '0241', 4)
2021-08-18 17:40:58,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,005 INFO sqlalchemy.engine.base.Engine ('구립사랑그린어린이집', '서진호', '서울특별시 강동구 고덕로98길 29 ,강동리엔파크9단지 관리동 (상일제2동)', '02', '441', '9829', 2)
2021-08-18 17:40:58,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,008 INFO sqlalchemy.engine.base.Engine ('한별어린이집', '류영철', '서울특별시 서대문구 이화여대8길 123 ,힐스테이트신촌아파트 단지 내 (북아현동)', '02', '392', '6001', 14)
2021-08-18 17:40:58,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,010 INFO sqlalchemy.engine.base.Engine ('구립강동해밀어린이집', '조민수', '서울특별시 강동구 아리수로93가길 77 ,강동리버스트6단지아파트 관리동 (강일동)', '02', '426', '8861', 2)
2021-08-18 17:40:58,011 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,012 INFO sqlalchemy.engine.base.Engine ('구립해봄어린이집', '김준호', '서울특별시 강동구 아리수로93가길 70 ,강동리버스트7단지아파트 관리동 (강일동)', '02', '426', '9370', 2)
2021-08-18 17:40:58,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,014 INFO sqlalchemy.engine.base.Engine ('구립대우주어린이집', '전상훈', '서울특별시 강서구 화곡로13길 107 ,135동 101호 (화곡제3동)', '02', '2605', '7313', 4)
2021-08-18 17:40:58,015 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,017 INFO sqlalchemy.engine.base.Engine ('서초구립 센트럴아이파크어린이집', '황영일', '서울특별시 서초구 반포대로18길 36 (서초3동)', '02', '2088', '7137', 15)
2021-08-18 17:40:58,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,018 INFO sqlalchemy.engine.base.Engine ('도토리소풍넥슨 강남어린이집', '전은영', '서울특별시 강남구 강남대로110길 36 ,(역삼동) (역삼1동)', '02', '538', '1026', 1)
2021-08-18 17:40:58,019 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,020 INFO sqlalchemy.engine.base.Engine ('신길힐스테이트나래어린이집', '정건우', '서울특별시 영등포구 신길로28길 9 (신길제4동)', '02', '6672', '8330', 20)
2021-08-18 17:40:58,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,022 INFO sqlalchemy.engine.base.Engine ('위례푸른숲어린이집', '이은영', '서울특별시 송파구 위례북로4길 12 (위례동)', '02', '409', '7942', 18)
2021-08-18 17:40:58,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,027 INFO sqlalchemy.engine.base.Engine ('현대오토에버 늘해랑어린이집', '윤지영', '서울특별시 강남구 삼성로84길 13 (대치2동)', '02', '3453', '0053', 1)
2021-08-18 17:40:58,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,030 INFO sqlalchemy.engine.base.Engine ('쿠팡(위례)어린이집', '황은영', '서울특별시 송파구 위례광장로 188 ,아이온스퀘어 2F (위례동)', '02', '400', '7790', 18)
2021-08-18 17:40:58,031 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,032 INFO sqlalchemy.engine.base.Engine ('구립 샘물어린이집', '김서연', '서울특별시 광진구 뚝섬로58길 56 ,101호 (자양제2동)', '02', '3437', '7737', 6)
2021-08-18 17:40:58,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,034 INFO sqlalchemy.engine.base.Engine ('포레스트어린이집', '장준혁', '서울특별시 강남구 개포로 264 (개포제4동)', '02', '2058', '3788', 1)
2021-08-18 17:40:58,035 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,036 INFO sqlalchemy.engine.base.Engine ('거여사과나무어린이집', '윤준영', '서울특별시 송파구 거마로 41 ,302동 101호(거여동, 현대3차아파트) (거여1동)', '02', '3402', '3425', 18)
2021-08-18 17:40:58,038 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,039 INFO sqlalchemy.engine.base.Engine ('빛의숲어린이집', '윤병철', '서울특별시 강남구 논현로158길 19 ,1층 (압구정동)', '02', '542', '5857', 1)
2021-08-18 17:40:58,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,041 INFO sqlalchemy.engine.base.Engine ('송파아이숲어린이집', '신종수', '서울특별시 송파구 오금로 551 ,205동 104호 (거여2동)', '02', '400', '6079', 18)
2021-08-18 17:40:58,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,043 INFO sqlalchemy.engine.base.Engine ('큰나래어린이집', '이성진', '서울특별시 용산구 서빙고로 17 ,102동 1,2,3층 (한강로동)', '02', '797', '7703', 21)
2021-08-18 17:40:58,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,046 INFO sqlalchemy.engine.base.Engine ('구립늘해랑어린이집', '류성수', '서울특별시 강동구 고덕로 399 ,고덕센트럴푸르지오아파트 관리동 (고덕제2동)', '02', '429', '7942', 2)
2021-08-18 17:40:58,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,048 INFO sqlalchemy.engine.base.Engine ('꿈빛 어린이집', '서은영', '서울특별시 성북구 종암로21길 127 ,101동 101호 (종암동)', '02', '6227', '4960', 17)
2021-08-18 17:40:58,050 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,051 INFO sqlalchemy.engine.base.Engine ('라온어린이집', '신혜진', '서울특별시 중랑구 동일로91길 23 (면목제5동)', '02', '432', '5592', 25)
2021-08-18 17:40:58,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,055 INFO sqlalchemy.engine.base.Engine ('사가정 아이파크어린이집', '김영숙', '서울특별시 중랑구 동일로92길 40 (면목제5동)', '02', '496', '8077', 25)
2021-08-18 17:40:58,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,057 INFO sqlalchemy.engine.base.Engine ('새솔아델포레어린이집', '조영식', '서울특별시 영등포구 신길로 29 (대림제1동)', '02', '6334', '0202', 20)
2021-08-18 17:40:58,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,059 INFO sqlalchemy.engine.base.Engine ('신아푸르지오 어린이집', '서현정', '서울특별시 은평구 연서로 455 ,제각말 5단지 푸르지오 관리동(진관동) (진관동)', '02', '358', '0404', 22)
2021-08-18 17:40:58,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,060 INFO sqlalchemy.engine.base.Engine ('서울도봉경찰서어린이집', '장서현', '서울특별시 도봉구 노해로 403 ,서울도봉경찰서어린이집 (창제4동)', '02', '906', '8190', 10)
2021-08-18 17:40:58,061 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,062 INFO sqlalchemy.engine.base.Engine ('중앙그룹직장어린이집', '안성민', '서울특별시 마포구 월드컵북로 375 ,1,2층 (상암동)', '070', '8672', '9249', 13)
2021-08-18 17:40:58,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,064 INFO sqlalchemy.engine.base.Engine ('카페24직장어린이집', '오유진', '서울특별시 관악구 보라매로3길 23 ,2층(카페24직장어린이집) (보라매동)', '02', '6279', '2411', 5)
2021-08-18 17:40:58,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,066 INFO sqlalchemy.engine.base.Engine ('별하어린이집', '최상철', '서울특별시 구로구 항동로 68 ,하버라인9단지 관리동 내 (항동)', '02', '2682', '0996', 7)
2021-08-18 17:40:58,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,067 INFO sqlalchemy.engine.base.Engine ('당산2동센트럴아이파크별하어린이집', '한민재', '서울특별시 영등포구 영신로 247 ,107동 관리동 (당산제2동)', '02', '2135', '2653', 20)
2021-08-18 17:40:58,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,069 INFO sqlalchemy.engine.base.Engine ('방이즐거운어린이집', '장성호', '서울특별시 송파구 가락로39길 6 ,(방이동) (방이2동)', '02', '413', '5277', 18)
2021-08-18 17:40:58,069 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,070 INFO sqlalchemy.engine.base.Engine ('송파파크센트럴어린이집', '박서연', '서울특별시 송파구 오금로 551 (거여2동)', '02', '403', '7700', 18)
2021-08-18 17:40:58,070 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,071 INFO sqlalchemy.engine.base.Engine ('구립키즈맘어린이집', '장민재', '서울특별시 관악구 봉천로23나길 35 ,101호 (보라매동)', '02', '874', '0761', 5)
2021-08-18 17:40:58,072 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,073 INFO sqlalchemy.engine.base.Engine ('해바라기어린이집', '송예은', '서울특별시 구로구 항동로 8 ,관리동 (항동)', '02', '2060', '5887', 7)
2021-08-18 17:40:58,074 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,075 INFO sqlalchemy.engine.base.Engine ('현대모비스모아어린이집', '오성호', '서울특별시 강남구 테헤란로13길 34 (역삼1동)', '02', '3454', '0062', 1)
2021-08-18 17:40:58,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,077 INFO sqlalchemy.engine.base.Engine ('참누리어린이집', '신상철', '서울특별시 구로구 경인로 302 ,관리동 (개봉동,개봉역센트레빌레우스 임대아파트) (개봉제1동)', '02', '2612', '2021', 7)
2021-08-18 17:40:58,078 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,079 INFO sqlalchemy.engine.base.Engine ('구립강동든든어린이집', '전경회', '서울특별시 강동구 아리수로93가길 110 ,관리동 (강일동)', '02', '442', '2807', 2)
2021-08-18 17:40:58,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,080 INFO sqlalchemy.engine.base.Engine ('당산2동은솔어린이집', '송예준', '서울특별시 영등포구 당산로42길 23 (당산제2동)', '02', '2636', '5630', 20)
2021-08-18 17:40:58,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,082 INFO sqlalchemy.engine.base.Engine ('새우개 하나어린이집', '최수빈', '서울특별시 중랑구 용마산로139다길 17 (신내1동)', '02', '438', '1318', 25)
2021-08-18 17:40:58,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,084 INFO sqlalchemy.engine.base.Engine ('서울지방국세청 우리누리어린이집', '황건우', '서울특별시 종로구 종로5길 86 (종로1.2.3.4가동)', '02', '739', '5100', 23)
2021-08-18 17:40:58,085 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,090 INFO sqlalchemy.engine.base.Engine ('서초구립 반포센트럴자이어린이집', '안미숙', '서울특별시 서초구 반포대로 310-6 ,(반포센트럴자이어린이집) (반포3동)', '02', '533', '8801', 15)
2021-08-18 17:40:58,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,092 INFO sqlalchemy.engine.base.Engine ('아이누리어린이집', '황지훈', '서울특별시 성북구 숭인로 16 ,103동 101호 (길음제2동)', '02', '982', '3949', 17)
2021-08-18 17:40:58,093 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,094 INFO sqlalchemy.engine.base.Engine ('두빛나래터발도르프어린이집', '전정호', '서울특별시 강서구 등촌로39마길 52 (등촌제2동)', '02', '2653', '6986', 4)
2021-08-18 17:40:58,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,095 INFO sqlalchemy.engine.base.Engine ('서울남부지방법원 직장어린이집', '전영일', '서울특별시 양천구 신월로 386 ,별관 5층 (신정1동)', '02', '2192', '1930', 19)
2021-08-18 17:40:58,096 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,097 INFO sqlalchemy.engine.base.Engine ('아이키움문래어린이집', '최성진', '서울특별시 영등포구 선유로9길 30 ,102동 1층(문래동6가) (문래동)', '02', '6397', '7955', 20)
2021-08-18 17:40:58,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,098 INFO sqlalchemy.engine.base.Engine ('구립 물빛캐슬어린이집', '임순자', '서울특별시 은평구 수색로 300 (수색동)', '02', '6951', '2081', 22)
2021-08-18 17:40:58,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,105 INFO sqlalchemy.engine.base.Engine ('다올어린이집', '황정수', '서울특별시 마포구 양화로 72 ,1층 (서교동)', '02', '332', '2322', 13)
2021-08-18 17:40:58,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,107 INFO sqlalchemy.engine.base.Engine ('늘봄어린이집', '오혜진', '서울특별시 동대문구 외대역동로1길 60-3 ,휘경해모로 관리동 (휘경제1동)', '02', '3390', '3094', 11)
2021-08-18 17:40:58,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,109 INFO sqlalchemy.engine.base.Engine ('구립 가온어린이집', '황건우', '서울특별시 양천구 남부순환로83길 17 ,목동센트럴아이파크위브아파트 1단지 (신월6동)', '02', '2602', '2484', 19)
2021-08-18 17:40:58,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,111 INFO sqlalchemy.engine.base.Engine ('구립 나래어린이집', '신종수', '서울특별시 양천구 남부순환로83길 18 ,목동센트럴아이파크위브아파트 2단지 (신월6동)', '02', '2603', '4110', 19)
2021-08-18 17:40:58,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,113 INFO sqlalchemy.engine.base.Engine ('구립 마루어린이집', '류민지', '서울특별시 양천구 남부순환로83길 47 ,목동센트럴아이파크위브아파트 4단지 (신월6동)', '02', '2604', '4301', 19)
2021-08-18 17:40:58,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,115 INFO sqlalchemy.engine.base.Engine ('구립에코포레어린이집', '임미숙', '서울특별시 강동구 천중로 253 ,이편한세상강동에코포레아파트 관리동 1층 (길동)', '02', '470', '0633', 2)
2021-08-18 17:40:58,117 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,118 INFO sqlalchemy.engine.base.Engine ('날아라어린이집', '정준영', '서울특별시 구로구 부광로 96-16 (항동)', '02', '2066', '7114', 7)
2021-08-18 17:40:58,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,120 INFO sqlalchemy.engine.base.Engine ('한나무어린이집', '김정웅', '서울특별시 도봉구 노해로66길 21 ,103동 105호(창동, 삼성래미안아파트) (창제1동)', '02', '995', '2447', 10)
2021-08-18 17:40:58,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,123 INFO sqlalchemy.engine.base.Engine ('거여키즈어린이집', '윤광수', '서울특별시 송파구 거마로 41 ,303동 102호(거여동, 현대3차아파트) (거여1동)', '02', '408', '6198', 18)
2021-08-18 17:40:58,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,127 INFO sqlalchemy.engine.base.Engine ('구립다움어린이집', '임영진', '서울특별시 동작구 사당로 90 ,사당롯데캐슬골든포레 관리동 1층 (사당제5동)', '02', '582', '2990', 12)
2021-08-18 17:40:58,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,131 INFO sqlalchemy.engine.base.Engine ('영등포든든어린이집', '권은영', '서울특별시 영등포구 대림로35가길 9 (대림제3동)', '02', '842', '2021', 20)
2021-08-18 17:40:58,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,134 INFO sqlalchemy.engine.base.Engine ('구립 응암샛별어린이집', '전서연', '서울특별시 은평구 은평로 220 (응암제1동)', '02', '354', '5208', 22)
2021-08-18 17:40:58,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,136 INFO sqlalchemy.engine.base.Engine ('구립 응암행복어린이집', '권정남', '서울특별시 은평구 은평로 220 (응암제1동)', '02', '353', '0701', 22)
2021-08-18 17:40:58,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,138 INFO sqlalchemy.engine.base.Engine ('신촌그랑어린이집', '장지은', '서울특별시 마포구 대흥로 175 ,관리동 (대흥동)', '02', '6949', '0277', 13)
2021-08-18 17:40:58,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,141 INFO sqlalchemy.engine.base.Engine ('이삭숲어린이집', '정지은', '서울특별시 강동구 동남로82길 29-8 ,이삭숲어린이집 (고덕제2동)', '02', '441', '2914', 2)
2021-08-18 17:40:58,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,143 INFO sqlalchemy.engine.base.Engine ('서대문든든어린이집', '안정수', '서울특별시 서대문구 거북골로 100 ,래미안루센티아아파트 (남가좌제2동)', '02', '306', '2020', 14)
2021-08-18 17:40:58,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,144 INFO sqlalchemy.engine.base.Engine ('한샘어린이집', '권영철', '서울특별시 서초구 방배로 285 ,한샘빌딩 (방배본동)', '02', '6908', '4051', 15)
2021-08-18 17:40:58,145 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,146 INFO sqlalchemy.engine.base.Engine ('행복타운어린이집', '전민수', '서울특별시 마포구 마포대로 144 ,마포T타운 2층 (공덕동)', '070', '7470', '3598', 13)
2021-08-18 17:40:58,147 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,148 INFO sqlalchemy.engine.base.Engine ('모두의 숲 어린이집', '최종수', '서울특별시 성동구 상원6나길 22-7 (성수1가제2동)', '02', '463', '0312', 16)
2021-08-18 17:40:58,150 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,152 INFO sqlalchemy.engine.base.Engine ('신길센트럴자이 솔빛 어린이집', '서지민', '서울특별시 영등포구 신길로29길 17 (신길제5동)', '02', '848', '1531', 20)
2021-08-18 17:40:58,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,154 INFO sqlalchemy.engine.base.Engine ('구립 신태양어린이집', '최예은', '서울특별시 강서구 곰달래로31다길 25 (화곡제2동)', '02', '2699', '1921', 4)
2021-08-18 17:40:58,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,157 INFO sqlalchemy.engine.base.Engine ('구립아이와나무어린이집', '전미숙', '서울특별시 광진구 천호대로123길 4-4 (중곡제2동)', '02', '452', '5579', 6)
2021-08-18 17:40:58,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,161 INFO sqlalchemy.engine.base.Engine ('꼬마사랑어린이집', '오준호', '서울특별시 중랑구 봉우재로6길 9 (면목제2동)', '02', '432', '0097', 25)
2021-08-18 17:40:58,163 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,164 INFO sqlalchemy.engine.base.Engine ('서초구(내곡)육아종합지원센터', '윤영진', '서울특별시 서초구 청계산로15길 77 ,1층 (내곡동)', '02', '578', '9340', 15)
2021-08-18 17:40:58,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,168 INFO sqlalchemy.engine.base.Engine ('서초구(서리풀)육아종합지원센터', '안예준', '서울특별시 서초구 명달로 148 (서초3동)', '02', '597', '9340', 15)
2021-08-18 17:40:58,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,170 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '정준영', '서울특별시 구로구 디지털로31길 90 ,108동 103호 (구로제3동)', '02', '838', '6157', 7)
2021-08-18 17:40:58,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,173 INFO sqlalchemy.engine.base.Engine ('한국환경산업기술원 초록꿈나무 직장어린이집', '이준호', '서울특별시 은평구 진흥로 215 ,A동 (불광제1동)', '02', '356', '7071', 22)
2021-08-18 17:40:58,174 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,175 INFO sqlalchemy.engine.base.Engine ('구립인헌어린이집', '오영환', '서울특별시 관악구 낙성대역14길 6 (인헌동)', '02', '889', '8586', 5)
2021-08-18 17:40:58,177 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,179 INFO sqlalchemy.engine.base.Engine ('구립 이든어린이집', '임상철', '서울특별시 은평구 응암로30길 15 (응암제2동)', '02', '356', '9616', 22)
2021-08-18 17:40:58,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,181 INFO sqlalchemy.engine.base.Engine ('서비스에이스 하람어린이집', '오수빈', '서울특별시 영등포구 문래로28길 25 ,에스타워 3층(문래동3가) (문래동)', '02', '6256', '0190', 20)
2021-08-18 17:40:58,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,183 INFO sqlalchemy.engine.base.Engine ('국립중앙박물관 해누림 어린이집', '신정호', '서울특별시 용산구 서빙고로 137 ,국립중앙박물관 (서빙고동)', '02', '2077', '9048', 21)
2021-08-18 17:40:58,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,184 INFO sqlalchemy.engine.base.Engine ('우아한어린이집', '강영자', '서울특별시 송파구 올림픽로32길 37-22 (방이2동)', '02', '422', '9941', 18)
2021-08-18 17:40:58,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,186 INFO sqlalchemy.engine.base.Engine ('목멱어린이집', '정예준', '서울특별시 용산구 회나무로12나길 10 (이태원제2동)', '02', '6954', '2057', 21)
2021-08-18 17:40:58,188 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,188 INFO sqlalchemy.engine.base.Engine ('CJ키즈빌어린이집', '오준영', '서울특별시 서초구 전원말4길 7 (방배2동)', '02', '586', '2022', 15)
2021-08-18 17:40:58,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,190 INFO sqlalchemy.engine.base.Engine ('GS예원어린이집', '안민석', '서울특별시 마포구 창전로 26 ,관리동 1층 (신수동)', '02', '712', '7974', 13)
2021-08-18 17:40:58,192 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,192 INFO sqlalchemy.engine.base.Engine ('구립 내일어린이집', '김종수', '서울특별시 은평구 응암로16길 20-9 ,구립 내일어린이집 (응암제2동)', '02', '306', '3850', 22)
2021-08-18 17:40:58,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,194 INFO sqlalchemy.engine.base.Engine ('구립 새하늘어린이집', '최영일', '서울특별시 강서구 강서로17다길 15-14 (화곡제1동)', '02', '2603', '2225', 4)
2021-08-18 17:40:58,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,195 INFO sqlalchemy.engine.base.Engine ('구립 성수아이파크어린이집', '신은영', '서울특별시 성동구 성수이로 137 ,관리동 1층 (성수동2가, 성수동아이파크) (성수2가제3동)', '02', '469', '5575', 16)
2021-08-18 17:40:58,196 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,196 INFO sqlalchemy.engine.base.Engine ('구립 왕십리하나어린이집', '황건우', '서울특별시 성동구 무학봉16길 9-3 (왕십리제2동)', '02', '2296', '3990', 16)
2021-08-18 17:40:58,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,198 INFO sqlalchemy.engine.base.Engine ('구립 해담어린이집', '김상훈', '서울특별시 강서구 금낭화로11길 36 (방화제2동)', '02', '2662', '3265', 4)
2021-08-18 17:40:58,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,201 INFO sqlalchemy.engine.base.Engine ('구립삼성어린이집', '장지혜', '서울특별시 강북구 한천로159길 8 ,삼성아파트 관리동 (수유2동)', '02', '996', '3737', 3)
2021-08-18 17:40:58,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,204 INFO sqlalchemy.engine.base.Engine ('구립우리아이어린이집', '신정식', '서울특별시 광진구 구의로4길 21 ,구의동 (구의제3동)', '010', '4697', '9933', 6)
2021-08-18 17:40:58,205 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,207 INFO sqlalchemy.engine.base.Engine ('나무어린이집', '강도현', '서울특별시 도봉구 노해로66길 21 ,103동 106호(창동, 삼성래미안아파트) (창제1동)', '02', '900', '8520', 10)
2021-08-18 17:40:58,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,210 INFO sqlalchemy.engine.base.Engine ('노원든든어린이집', '류준혁', '서울특별시 노원구 초안산로2라길 26 ,월계센트럴아이파크A, 월계동 (월계2동)', '02', '998', '0632', 9)
2021-08-18 17:40:58,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,211 INFO sqlalchemy.engine.base.Engine ('늘품자연어린이집', '황준서', '서울특별시 서대문구 거북골로 84 ,DMC에코자이아파트 단지 내 (남가좌제2동)', '02', '306', '0972', 14)
2021-08-18 17:40:58,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,213 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '조미숙', '서울특별시 도봉구 마들로 859-19 ,110동 106호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '3494', '0541', 10)
2021-08-18 17:40:58,214 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,215 INFO sqlalchemy.engine.base.Engine ('라이나생명 키즈나루 어린이집', '송영철', '서울특별시 종로구 삼봉로 48 ,시그나 빌딩 2층 (종로1.2.3.4가동)', '02', '3779', '8170', 23)
2021-08-18 17:40:58,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,217 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '안성진', '서울특별시 도봉구 덕릉로60길 121-20 (창제3동)', '02', '999', '8096', 10)
2021-08-18 17:40:58,218 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,219 INFO sqlalchemy.engine.base.Engine ('보림어린이집', '정영환', '서울특별시 중랑구 중랑천로 286 ,101동 101호(묵동, 현대아이파크) (묵제2동)', '02', '948', '0533', 25)
2021-08-18 17:40:58,221 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,223 INFO sqlalchemy.engine.base.Engine ('삼성영재어린이집', '서영자', '서울특별시 서대문구 증가로 191 ,DMC래미안클라시스 108동 104호 (남가좌제2동)', '02', '374', '6703', 14)
2021-08-18 17:40:58,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,226 INFO sqlalchemy.engine.base.Engine ('상계해솔어린이집', '정영숙', '서울특별시 노원구 수락산로 12 ,(상계역센트럴푸르지오A, 상계동) (상계3.4동)', '02', '931', '0219', 9)
2021-08-18 17:40:58,227 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,228 INFO sqlalchemy.engine.base.Engine ('서초구립 대우효령어린이집', '오건우', '서울특별시 서초구 효령로 84 (방배3동)', '02', '525', '1116', 15)
2021-08-18 17:40:58,229 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,230 INFO sqlalchemy.engine.base.Engine ('서초구립 롯데캐슬킨더어린이집', '류은영', '서울특별시 서초구 서운로 197 ,1층 (서초4동)', '02', '591', '3009', 15)
2021-08-18 17:40:58,231 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,232 INFO sqlalchemy.engine.base.Engine ('수자인어린이집', '권민수', '서울특별시 중랑구 사가정로72길 26 ,한양수자인사가정파크 단지내 (면목제7동)', '02', '432', '8366', 25)
2021-08-18 17:40:58,233 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,234 INFO sqlalchemy.engine.base.Engine ('신동아어린이집', '김은정', '서울특별시 강남구 헌릉로590길 10 ,관리동 (세곡동)', '02', '451', '1828', 1)
2021-08-18 17:40:58,235 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,236 INFO sqlalchemy.engine.base.Engine ('신촌숲어린이집', '김은영', '서울특별시 마포구 광성로 17 ,관리동 1층 (신수동)', '02', '717', '1357', 13)
2021-08-18 17:40:58,237 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,238 INFO sqlalchemy.engine.base.Engine ('아름드리어린이집', '강지혜', '서울특별시 마포구 월드컵로 338 ,관리동 1층 (상암동)', '02', '322', '0714', 13)
2021-08-18 17:40:58,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,239 INFO sqlalchemy.engine.base.Engine ('웃음가득어린이집', '강민재', '서울특별시 도봉구 마들로 859-19 ,106동 104호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '955', '1255', 10)
2021-08-18 17:40:58,240 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,241 INFO sqlalchemy.engine.base.Engine ('월드컵어린이집', '정건우', '서울특별시 마포구 월드컵북로 501 ,관리동 1층 (상암동)', '02', '383', '3201', 13)
2021-08-18 17:40:58,242 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,243 INFO sqlalchemy.engine.base.Engine ('진주어린이집', '윤정운', '서울특별시 노원구 동일로227길 86 ,1614동 103호 (상계8동)', '02', '930', '0240', 9)
2021-08-18 17:40:58,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,245 INFO sqlalchemy.engine.base.Engine ('포스코 제2 어린이집', '강영철', '서울특별시 강남구 테헤란로 440 ,포스코센터 4층 (대치4동)', '02', '3457', '6591', 1)
2021-08-18 17:40:58,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,247 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '송종수', '서울특별시 중랑구 용마산로94길 94 (면목제3.8동)', '02', '2208', '3004', 25)
2021-08-18 17:40:58,247 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,248 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '한준호', '서울특별시 동대문구 이문로9길 93 ,101호 (이문동, 반도하이츠빌라) (이문제1동)', '02', '2135', '5861', 11)
2021-08-18 17:40:58,249 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,250 INFO sqlalchemy.engine.base.Engine ('호호어린이집', '권영환', '서울특별시 노원구 석계로 49 ,현대아파트 단지내 (월계1동)', '02', '943', '8133', 9)
2021-08-18 17:40:58,251 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,252 INFO sqlalchemy.engine.base.Engine ('다람패스트파이브공동직장어린이집', '황미경', '서울특별시 강남구 봉은사로18길 45-1 (역삼1동)', '02', '3453', '7734', 1)
2021-08-18 17:40:58,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,253 INFO sqlalchemy.engine.base.Engine ('서울소방학교 직장어린이집', '송예준', '서울특별시 은평구 통일로 1031-21 (진관동)', '02', '354', '3601', 22)
2021-08-18 17:40:58,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,254 INFO sqlalchemy.engine.base.Engine ('SK스토아 행복어린이집', '장영철', '서울특별시 마포구 월드컵북로 402 ,2층(상암동,KGIT센터) (상암동)', '02', '6393', '5320', 13)
2021-08-18 17:40:58,255 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,256 INFO sqlalchemy.engine.base.Engine ('블랭크어린이집', '조성호', '서울특별시 강남구 선릉로93길 40 ,1층 (역삼1동)', '02', '6230', '0100', 1)
2021-08-18 17:40:58,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,259 INFO sqlalchemy.engine.base.Engine ('용산소방서직장어린이집', '정상철', '서울특별시 용산구 한강대로 167 ,용산소방서 (한강로동)', '02', '749', '6034', 21)
2021-08-18 17:40:58,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,261 INFO sqlalchemy.engine.base.Engine ('LG이노텍 서울어린이집', '강미숙', '서울특별시 강서구 마곡중앙10로 30 ,E3 (가양제1동)', '02', '2135', '1236', 4)
2021-08-18 17:40:58,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,266 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '장경숙', '서울특별시 강동구 고덕로80길 99 ,517동 103호(상일동, 고덕센트럴아이파크아파트) (상일제1동)', '02', '427', '0511', 2)
2021-08-18 17:40:58,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,268 INFO sqlalchemy.engine.base.Engine ('키즈일레븐어린이집', '오서연', '서울특별시 중구 한강대로 416 ,2층 (회현동)', '02', '6456', '8560', 24)
2021-08-18 17:40:58,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,269 INFO sqlalchemy.engine.base.Engine ('KB구의 어린이집', '윤민지', '서울특별시 광진구 광나루로 525 ,3층 (구의제2동)', '02', '6235', '7977', 6)
2021-08-18 17:40:58,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,272 INFO sqlalchemy.engine.base.Engine ('구립 엠밸리큰나무어린이집', '송성민', '서울특별시 강서구 마곡중앙8로1길 10 (가양제1동)', '02', '3663', '9599', 4)
2021-08-18 17:40:58,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,275 INFO sqlalchemy.engine.base.Engine ('구립아르테온보나어린이집', '전지영', '서울특별시 강동구 고덕로 360 ,고덕아르테온 339동 인근 관리동 (상일제1동)', '02', '442', '2022', 2)
2021-08-18 17:40:58,276 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,277 INFO sqlalchemy.engine.base.Engine ('구립아르테온보예어린이집', '서예은', '서울특별시 강동구 고덕로 360 ,고덕아르테온아파트 319동 1층(상일동) (상일제1동)', '02', '6925', '5642', 2)
2021-08-18 17:40:58,278 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,279 INFO sqlalchemy.engine.base.Engine ('유한버들새싹어린이집', '임성수', '서울특별시 동작구 노량진로 74 ,유한양행 (대방동)', '02', '828', '2506', 12)
2021-08-18 17:40:58,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,283 INFO sqlalchemy.engine.base.Engine ('구립가온어린이집', '송영진', '서울특별시 동작구 성대로16길 21 (상도제4동)', '02', '3280', '0217', 12)
2021-08-18 17:40:58,284 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,285 INFO sqlalchemy.engine.base.Engine ('늘봄보라매SK뷰어린이집', '황서현', '서울특별시 영등포구 여의대방로35가길 19 (신길제7동)', '02', '2135', '7941', 20)
2021-08-18 17:40:58,286 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,286 INFO sqlalchemy.engine.base.Engine ('동고어린이집', '안준호', '서울특별시 서초구 바우뫼로7길 29 ,105동 102호 (양재1동)', '02', '6241', '1852', 15)
2021-08-18 17:40:58,287 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,288 INFO sqlalchemy.engine.base.Engine ('용산캐슬어린이집', '안서연', '서울특별시 용산구 백범로 313 ,키즈클럽(효창동,롯데캐슬센터포레) (효창동)', '02', '712', '7942', 21)
2021-08-18 17:40:58,290 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,291 INFO sqlalchemy.engine.base.Engine ('가락아이들어린이집', '최상훈', '서울특별시 송파구 중대로12길 34 ,(가락동) (가락본동)', '02', '400', '3188', 18)
2021-08-18 17:40:58,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,293 INFO sqlalchemy.engine.base.Engine ('구립꿈담어린이집', '류정운', '서울특별시 동작구 상도로47아길 44-1 ,2층 (상도제1동)', '02', '813', '4246', 12)
2021-08-18 17:40:58,297 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,298 INFO sqlalchemy.engine.base.Engine ('구립독산e편한어린이집', '오종수', '서울특별시 금천구 범안로 1212 (독산제1동)', '02', '892', '0700', 8)
2021-08-18 17:40:58,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,301 INFO sqlalchemy.engine.base.Engine ('구립 행당한신어린이집', '최성호', '서울특별시 성동구 고산자로 164 ,관리동 2층(행당동, 행당한신) (행당제1동)', '02', '2291', '0079', 16)
2021-08-18 17:40:58,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,304 INFO sqlalchemy.engine.base.Engine ('새빛어린이집', '박정운', '서울특별시 구로구 연동로 233 (항동)', '02', '2688', '3688', 7)
2021-08-18 17:40:58,306 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,306 INFO sqlalchemy.engine.base.Engine ('항동하랑어린이집', '류정수', '서울특별시 구로구 항동로 42 (항동)', '02', '2612', '0081', 7)
2021-08-18 17:40:58,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,308 INFO sqlalchemy.engine.base.Engine ('삼성아트어린이집', '황미경', '서울특별시 송파구 문정로 83 (문정1동)', '02', '401', '7245', 18)
2021-08-18 17:40:58,309 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,310 INFO sqlalchemy.engine.base.Engine ('파인13어린이집', '황서현', '서울특별시 송파구 송파대로8길 10 ,(장지동, 송파파인타운13단지) (장지동)', '02', '400', '0609', 18)
2021-08-18 17:40:58,311 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,311 INFO sqlalchemy.engine.base.Engine ('아이다움어린이집', '한성호', '서울특별시 중구 난계로 130 ,102동 102호 (신당제5동)', '02', '2233', '7942', 24)
2021-08-18 17:40:58,312 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,313 INFO sqlalchemy.engine.base.Engine ('잠실올림픽아이파크어린이집', '송종수', '서울특별시 송파구 올림픽로43길 34 ,관리동 1층(풍납동, 잠실올림픽공원아이파크) (풍납2동)', '02', '473', '8613', 18)
2021-08-18 17:40:58,314 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,314 INFO sqlalchemy.engine.base.Engine ('구립 아이나무어린이집', '황혜진', '서울특별시 강서구 화곡로13가길 5 (화곡제3동)', '02', '6949', '1305', 4)
2021-08-18 17:40:58,315 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,316 INFO sqlalchemy.engine.base.Engine ('구립 하늘마음어린이집', '박준호', '서울특별시 강서구 초록마을로 106 (화곡본동)', '02', '6959', '7736', 4)
2021-08-18 17:40:58,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,317 INFO sqlalchemy.engine.base.Engine ('구립 가람슬기어린이집', '윤영식', '서울특별시 은평구 연서로19길 28-1 (갈현제2동)', '02', '353', '2235', 22)
2021-08-18 17:40:58,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,321 INFO sqlalchemy.engine.base.Engine ('구립도레미어린이집', '장민서', '서울특별시 동작구 흑석로13길 25 (흑석동)', '02', '813', '2031', 12)
2021-08-18 17:40:58,325 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,326 INFO sqlalchemy.engine.base.Engine ('바람아래발도르프어린이집', '최지영', '서울특별시 성북구 길음로9길 40 ,108동 101호 (길음제1동)', '02', '942', '5090', 17)
2021-08-18 17:40:58,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,327 INFO sqlalchemy.engine.base.Engine ('키움누리어린이집', '박준혁', '서울특별시 성북구 서경로 60 ,길음뉴타운 11단지 롯데캐슬골든힐스 단지 내 (정릉제1동)', '02', '943', '1525', 17)
2021-08-18 17:40:58,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,329 INFO sqlalchemy.engine.base.Engine ('구립롯데캐슬베네루체어린이집', '안지훈', '서울특별시 강동구 구천면로 630 ,고덕롯데캐슬베네루체 관리동(구립롯데캐슬베네루체어린이집) (상일제1동)', '02', '442', '7675', 2)
2021-08-18 17:40:58,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,330 INFO sqlalchemy.engine.base.Engine ('구립센트럴아이파크어린이집', '신은영', '서울특별시 강동구 고덕로80길 99 ,관리동(구립센트럴아이파크어린이집) (상일제1동)', '02', '6013', '0320', 2)
2021-08-18 17:40:58,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,332 INFO sqlalchemy.engine.base.Engine ('구립힐스아이어린이집', '서영진', '서울특별시 강동구 올림픽로91길 30 ,관리동(구립힐스아이어린이집) (암사제2동)', '02', '429', '6351', 2)
2021-08-18 17:40:58,333 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,334 INFO sqlalchemy.engine.base.Engine ('구립소나무어린이집', '안정수', '서울특별시 금천구 독산로58나길 81 (독산제2동)', '02', '802', '7902', 8)
2021-08-18 17:40:58,335 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,336 INFO sqlalchemy.engine.base.Engine ('데시앙어린이집', '이종수', '서울특별시 동대문구 장한로27길 37 ,관리동(장안동, 더퍼스트데시앙아파트) (장안제2동)', '02', '6053', '6601', 11)
2021-08-18 17:40:58,337 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,338 INFO sqlalchemy.engine.base.Engine ('우리들어린이집', '장순자', '서울특별시 중랑구 공릉로4길 18-13 (묵제1동)', '02', '973', '0577', 25)
2021-08-18 17:40:58,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,340 INFO sqlalchemy.engine.base.Engine ('구립꿈의숲해링턴어린이집', '신성진', '서울특별시 강북구 오현로 45 ,꿈의숲해링턴플레이스아파트 114동 (지하1층) (송중동)', '02', '989', '1467', 3)
2021-08-18 17:40:58,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,342 INFO sqlalchemy.engine.base.Engine ('구립 숲속향기어린이집', '이성진', '서울특별시 은평구 연서로48길 12 ,510동 1층 (진관동)', '02', '384', '4466', 22)
2021-08-18 17:40:58,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,344 INFO sqlalchemy.engine.base.Engine ('자람어린이집', '강정순', '서울특별시 서대문구 가재울미래로 2 ,DMC파크뷰자이 4단지 내 402동 1층 (남가좌제1동)', '02', '6954', '1909', 14)
2021-08-18 17:40:58,345 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,346 INFO sqlalchemy.engine.base.Engine ('베베키즈어린이집', '강경회', '서울특별시 강동구 고덕로 333 ,112동 105호(고덕동, 고덕그라시움아파트) (고덕제2동)', '02', '428', '1566', 2)
2021-08-18 17:40:58,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,348 INFO sqlalchemy.engine.base.Engine ('두산로다어린이집', '신종수', '서울특별시 양천구 신월로20길 7 ,신정뉴타운 두산위브 관리동 (신월2동)', '02', '6408', '0705', 19)
2021-08-18 17:40:58,349 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,350 INFO sqlalchemy.engine.base.Engine ('구립 가온누리어린이집', '서서현', '서울특별시 은평구 갈현로31길 14-9 (갈현제2동)', '02', '356', '7713', 22)
2021-08-18 17:40:58,351 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,352 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '최유진', '서울특별시 성북구 한천로90길 49 ,1층 (장위제3동)', '02', '942', '0130', 17)
2021-08-18 17:40:58,353 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,354 INFO sqlalchemy.engine.base.Engine ('하이키즈어린이집', '이영환', '서울특별시 성북구 한천로 713 ,513동 102호 (래미안장위퍼스트하이) (장위제3동)', '02', '942', '1101', 17)
2021-08-18 17:40:58,355 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,356 INFO sqlalchemy.engine.base.Engine ('구립 움찬어린이집', '서준서', '서울특별시 은평구 불광로 64 ,불광 롯데캐슬 (불광제1동)', '02', '6959', '9950', 22)
2021-08-18 17:40:58,357 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,358 INFO sqlalchemy.engine.base.Engine ('구립 한빛어린이집', '송정운', '서울특별시 은평구 백련산로 67 ,(백련산파크자이) (응암제2동)', '02', '2135', '4662', 22)
2021-08-18 17:40:58,360 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,361 INFO sqlalchemy.engine.base.Engine ('어울림어린이집', '조성호', '서울특별시 강동구 고덕로 333 ,127동 104호(고덕그라시움) (고덕제2동)', '02', '481', '0045', 2)
2021-08-18 17:40:58,367 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,368 INFO sqlalchemy.engine.base.Engine ('더나은어린이집', '최경자', '서울특별시 송파구 충민로 152 ,306동 104호(송파파인타운3단지) (장지동)', '02', '3012', '2334', 18)
2021-08-18 17:40:58,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,369 INFO sqlalchemy.engine.base.Engine ('LG전자 서초어린이집', '서경회', '서울특별시 서초구 양재대로11길 19 ,고객센터3층 (양재2동)', '02', '503', '4013', 15)
2021-08-18 17:40:58,370 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,372 INFO sqlalchemy.engine.base.Engine ('구립초록빛어린이집', '오서현', '서울특별시 금천구 시흥대로68길 89 (시흥제1동)', '02', '891', '1381', 8)
2021-08-18 17:40:58,373 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,374 INFO sqlalchemy.engine.base.Engine ('꿈터어린이집', '최영진', '서울특별시 중랑구 사가정로42길 90 ,두산아파트 관리동(면목동) (면목제7동)', '02', '435', '3382', 25)
2021-08-18 17:40:58,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,376 INFO sqlalchemy.engine.base.Engine ('서일대학교부설어린이집', '신예준', '서울특별시 중랑구 용마산로90길 28-5 (면목제3.8동)', '02', '492', '3993', 25)
2021-08-18 17:40:58,377 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,377 INFO sqlalchemy.engine.base.Engine ('서초구립 나래어린이집', '조영철', '서울특별시 서초구 양재대로2길 33 ,지상1층 (양재1동)', '02', '529', '2019', 15)
2021-08-18 17:40:58,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,379 INFO sqlalchemy.engine.base.Engine ('서초구립 신반포리오센트어린이집', '조은경', '서울특별시 서초구 잠원로14길 32 (잠원동)', '02', '595', '5532', 15)
2021-08-18 17:40:58,381 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,382 INFO sqlalchemy.engine.base.Engine ('마포자이3차어린이집', '이지은', '서울특별시 마포구 숭문길 98 ,관리동 1층 (염리동)', '02', '714', '0005', 13)
2021-08-18 17:40:58,383 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,384 INFO sqlalchemy.engine.base.Engine ('마포한강아이파크어린이집', '전준서', '서울특별시 마포구 희우정로 77 ,102동 1층 (망원제1동)', '02', '334', '0000', 13)
2021-08-18 17:40:58,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,385 INFO sqlalchemy.engine.base.Engine ('구립 매바위어린이집', '오성민', '서울특별시 은평구 응암로30길 16 ,백련산SK뷰아이파크 (응암제2동)', '02', '6959', '0097', 22)
2021-08-18 17:40:58,386 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,387 INFO sqlalchemy.engine.base.Engine ('이화의료원어린이집', '황정수', '서울특별시 강서구 공항대로 260 ,B관 4층 (발산제1동)', '02', '6986', '5950', 4)
2021-08-18 17:40:58,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,388 INFO sqlalchemy.engine.base.Engine ('그린나래어린이집', '류준혁', '서울특별시 성북구 한천로 713 ,506동 1층 (장위제3동)', '02', '6949', '1609', 17)
2021-08-18 17:40:58,389 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,390 INFO sqlalchemy.engine.base.Engine ('구립 꿈터어린이집', '최진호', '서울특별시 은평구 갈현로33길 24 ,갈현동현대아파트 (갈현제1동)', '02', '2135', '5448', 22)
2021-08-18 17:40:58,392 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,393 INFO sqlalchemy.engine.base.Engine ('아름다운어린이집', '송병철', '서울특별시 동대문구 황물로7길 21 (답십리제1동)', '02', '2215', '6363', 11)
2021-08-18 17:40:58,394 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,395 INFO sqlalchemy.engine.base.Engine ('신사임당어린이집', '최은경', '서울특별시 중랑구 신내로 51 ,104동 103호(신내동, 성원아파트) (신내2동)', '02', '494', '2179', 25)
2021-08-18 17:40:58,396 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,396 INFO sqlalchemy.engine.base.Engine ('지혜어린이집', '박영일', '서울특별시 강남구 삼성로 11 (개포2동)', '02', '576', '0060', 1)
2021-08-18 17:40:58,398 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,398 INFO sqlalchemy.engine.base.Engine ('구립그라시움물빛어린이집', '강지영', '서울특별시 강동구 고덕로 333 ,119동 1층(고덕동, 고덕그라시움아파트) (고덕제2동)', '02', '3427', '0257', 2)
2021-08-18 17:40:58,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,400 INFO sqlalchemy.engine.base.Engine ('구립그라시움별빛어린이집', '권정웅', '서울특별시 강동구 고덕로 333 ,140동 1층(고덕동, 고덕그라시움아파트) (고덕제2동)', '02', '3013', '3375', 2)
2021-08-18 17:40:58,401 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,402 INFO sqlalchemy.engine.base.Engine ('구립그라시움은빛어린이집', '황영일', '서울특별시 강동구 고덕로 333 ,113동 1층(고덕동, 고덕그라시움아파트) (고덕제2동)', '02', '2135', '7268', 2)
2021-08-18 17:40:58,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,403 INFO sqlalchemy.engine.base.Engine ('N젤어린이집', '전준서', '서울특별시 강서구 마곡중앙로 177 (가양제1동)', '02', '6340', '8131', 4)
2021-08-18 17:40:58,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,404 INFO sqlalchemy.engine.base.Engine ('대상어린이집', '송진호', '서울특별시 중랑구 면목로 470 ,대상빌딩 내 1층 (상봉제2동)', '02', '6406', '9911', 25)
2021-08-18 17:40:58,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,408 INFO sqlalchemy.engine.base.Engine ('구립 아이편한어린이집', '서정운', '서울특별시 강서구 공항대로 583 ,염창동, e편한세상 염창아파트 관리동 (염창동)', '02', '2662', '3401', 4)
2021-08-18 17:40:58,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,410 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '황순자', '서울특별시 구로구 경인로47다길 34-7 ,우성꿈동산 아파트 우성상가(고척동) (고척제1동)', '02', '2611', '7618', 7)
2021-08-18 17:40:58,411 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,411 INFO sqlalchemy.engine.base.Engine ('늘사랑어린이집', '류미경', '서울특별시 구로구 구로중앙로40길 24 (신도림동)', '02', '3667', '1235', 7)
2021-08-18 17:40:58,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,413 INFO sqlalchemy.engine.base.Engine ('꽃망울어린이집', '박준호', '서울특별시 구로구 항동로 72 ,관리동(항동, 하버라인 4단지) (항동)', '02', '2618', '1007', 7)
2021-08-18 17:40:58,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,414 INFO sqlalchemy.engine.base.Engine ('자연숲어린이집', '한준혁', '서울특별시 구로구 연동로 234 ,관리동(항동, 하버라인 2단지) (항동)', '02', '2688', '2611', 7)
2021-08-18 17:40:58,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,416 INFO sqlalchemy.engine.base.Engine ('꾸미어린이집', '류성수', '서울특별시 금천구 시흥대로77길 23 ,시흥베르빌 아파트 101동 104호 (시흥제1동)', '02', '6348', '1108', 8)
2021-08-18 17:40:58,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,417 INFO sqlalchemy.engine.base.Engine ('선재어린이집', '김정웅', '서울특별시 종로구 우정국로 51-4 (종로1.2.3.4가동)', '02', '720', '9770', 23)
2021-08-18 17:40:58,418 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,419 INFO sqlalchemy.engine.base.Engine ('구립 솔찬어린이집', '권준호', '서울특별시 은평구 가좌로 334 (신사제1동)', '02', '2135', '7477', 22)
2021-08-18 17:40:58,420 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,421 INFO sqlalchemy.engine.base.Engine ('구립e편한2단지어린이집', '박민지', '서울특별시 관악구 청룡16길 43 ,서울대입구e편한세상2단지 206동 앞 (청룡동)', '02', '883', '0903', 5)
2021-08-18 17:40:58,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,422 INFO sqlalchemy.engine.base.Engine ('구립e편한1단지어린이집', '김민재', '서울특별시 관악구 청룡10길 45 ,서울대입구e편한세상1단지 105동 앞 (청룡동)', '02', '883', '8083', 5)
2021-08-18 17:40:58,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,425 INFO sqlalchemy.engine.base.Engine ('구립신사어린이집', '최정순', '서울특별시 관악구 관천로21길 16 (신사동)', '02', '857', '7490', 5)
2021-08-18 17:40:58,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,427 INFO sqlalchemy.engine.base.Engine ('서초구립 누리아미어린이집', '박성진', '서울특별시 서초구 서운로26길 3 ,서초4동 열린문화센터 내 (서초4동)', '02', '3477', '1232', 15)
2021-08-18 17:40:58,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,428 INFO sqlalchemy.engine.base.Engine ('구립래미안솔베뉴어린이집', '한지영', '서울특별시 강동구 양재대로 1650 ,구립래미안솔베뉴어린이집 (명일제1동)', '02', '6925', '0850', 2)
2021-08-18 17:40:58,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,429 INFO sqlalchemy.engine.base.Engine ('휘경SK뷰어린이집', '장준혁', '서울특별시 동대문구 휘경로 60 ,휘경SK뷰아파트, 관리동 (휘경제1동)', '02', '6949', '3393', 11)
2021-08-18 17:40:58,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,431 INFO sqlalchemy.engine.base.Engine ('신당하나어린이집', '강은정', '서울특별시 중구 왕십리로 407 ,신당파인힐하나유보라 103동 1층 (신당제5동)', '02', '2256', '7646', 24)
2021-08-18 17:40:58,439 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,440 INFO sqlalchemy.engine.base.Engine ('예크어린이집', '전광수', '서울특별시 구로구 개봉로20길 158 ,현대홈타운 2단지아파트 관리동 1층 (개봉제2동)', '070', '4200', '0713', 7)
2021-08-18 17:40:58,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,443 INFO sqlalchemy.engine.base.Engine ('푸르지오비씨 어린이집', '서준호', '서울특별시 중구 을지로4가 을지로 170 (을지로동)', '02', '2288', '2761', 24)
2021-08-18 17:40:58,444 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,444 INFO sqlalchemy.engine.base.Engine ('아름드리어린이집', '안진호', '서울특별시 성북구 장월로 160 ,래미안장위포레카운티 104동 1층 (장위제3동)', '02', '943', '9933', 17)
2021-08-18 17:40:58,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,445 INFO sqlalchemy.engine.base.Engine ('교원&하나투어 공동직장어린이집', '전영길', '서울특별시 중구 을지로2가 을지로 55 ,교원명동빌딩 3층 (명동)', '02', '779', '6118', 24)
2021-08-18 17:40:58,446 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,447 INFO sqlalchemy.engine.base.Engine ('구립 늘봄어린이집', '장준영', '서울특별시 은평구 통일로 610 ,힐스테이트녹번 106동 1층 (녹번동)', '02', '353', '7554', 22)
2021-08-18 17:40:58,448 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,449 INFO sqlalchemy.engine.base.Engine ('구립 향림어린이집', '강건우', '서울특별시 은평구 연서로41가길 24-1 (불광제2동)', '02', '353', '1966', 22)
2021-08-18 17:40:58,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,450 INFO sqlalchemy.engine.base.Engine ('사랑해어린이집', '정건우', '서울특별시 송파구 동남로24길 37 ,1층 (오금동)', '02', '2135', '4591', 18)
2021-08-18 17:40:58,451 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,451 INFO sqlalchemy.engine.base.Engine ('KCC직장어린이집', '임정자', '서울특별시 서초구 사평대로 334-2 ,1층 (서초4동)', '02', '3447', '9280', 15)
2021-08-18 17:40:58,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,453 INFO sqlalchemy.engine.base.Engine ('구립 내숲어린이집', '서정자', '서울특별시 은평구 은평터널로 121-6 ,이랜드타운아파트 101-102 (신사제2동)', '02', '302', '1630', 22)
2021-08-18 17:40:58,454 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,454 INFO sqlalchemy.engine.base.Engine ('구립 맑은별어린이집', '조성호', '서울특별시 은평구 서오릉로21길 47 ,갈현이편한세상 103-104 (구산동)', '02', '357', '7942', 22)
2021-08-18 17:40:58,455 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,457 INFO sqlalchemy.engine.base.Engine ('구립 봄샘어린이집', '최혜진', '서울특별시 양천구 목동남로4길 80 ,목동파크자이아파트 (신정7동)', '02', '2651', '1905', 19)
2021-08-18 17:40:58,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,459 INFO sqlalchemy.engine.base.Engine ('구립 이든샘어린이집', '이미숙', '서울특별시 양천구 신정로7길 75 ,이든채아파트 (신정3동)', '02', '6347', '1817', 19)
2021-08-18 17:40:58,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,461 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '윤상철', '서울특별시 서대문구 증가로 150 ,DMC2차아이파크 아파트 (남가좌제2동)', '02', '3152', '6579', 14)
2021-08-18 17:40:58,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,463 INFO sqlalchemy.engine.base.Engine ('헬리오마음어린이집', '임영진', '서울특별시 송파구 송파대로 345 ,, 510동 앞(가락동, 헬리오시티) (가락1동)', '02', '400', '7751', 18)
2021-08-18 17:40:58,464 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,465 INFO sqlalchemy.engine.base.Engine ('사랑별어린이집', '임예은', '서울특별시 송파구 송파대로 345 ,201동 102호(가락동, 헬리오시티) (가락1동)', '070', '8160', '0000', 18)
2021-08-18 17:40:58,466 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,467 INFO sqlalchemy.engine.base.Engine ('느티나무어린이집', '서지원', '서울특별시 구로구 항동로 43 ,1층 관리동 (항동)', '02', '2060', '2010', 7)
2021-08-18 17:40:58,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,469 INFO sqlalchemy.engine.base.Engine ('어린왕자어린이집', '박예준', '서울특별시 강남구 자곡로7길 8-16 (세곡동)', '02', '3412', '0612', 1)
2021-08-18 17:40:58,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,471 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '권준호', '서울특별시 강남구 삼성로 212 ,17동 115호 (대치2동)', '02', '576', '4938', 1)
2021-08-18 17:40:58,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,473 INFO sqlalchemy.engine.base.Engine ('자이안어린이집', '최정식', '서울특별시 은평구 통일로 1034 (진관동)', '02', '6402', '7007', 22)
2021-08-18 17:40:58,473 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,474 INFO sqlalchemy.engine.base.Engine ('여의도 하나금융그룹 직장어린이집', '황은경', '서울특별시 영등포구 여의나루로 53-1 ,3층 (여의도동)', '02', '780', '3220', 20)
2021-08-18 17:40:58,476 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,477 INFO sqlalchemy.engine.base.Engine ('신길햇살아이파크어린이집', '송준호', '서울특별시 영등포구 가마산로 426 (신길제3동)', '02', '849', '9501', 20)
2021-08-18 17:40:58,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,479 INFO sqlalchemy.engine.base.Engine ('오금물빛어린이집', '송성호', '서울특별시 송파구 성내천로 103 (오금동)', '02', '406', '4001', 18)
2021-08-18 17:40:58,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,481 INFO sqlalchemy.engine.base.Engine ('구립 기자촌어린이집', '류정웅', '서울특별시 은평구 연서로46길 7 ,1105동 1층 (진관동)', '02', '389', '6878', 22)
2021-08-18 17:40:58,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,483 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '최미경', '서울특별시 구로구 구일로4길 46 ,204동 105호(구로동,현대연예인아파트) (구로제1동)', '02', '838', '3934', 7)
2021-08-18 17:40:58,484 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,485 INFO sqlalchemy.engine.base.Engine ('은평성모병원어린이집', '안준서', '서울특별시 은평구 통일로 1021 ,별관2층 (진관동)', '02', '2030', '4988', 22)
2021-08-18 17:40:58,486 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,487 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '이현준', '서울특별시 서대문구 홍제천로 136 ,103동 1층(연희동, 연희파크푸르지오) (연희동)', '02', '336', '2146', 14)
2021-08-18 17:40:58,488 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,489 INFO sqlalchemy.engine.base.Engine ('푸르지오아이숲어린이집', '강영숙', '서울특별시 구로구 중앙로 121 ,고척파크푸르지오 관리동 (고척제2동)', '02', '2613', '9280', 7)
2021-08-18 17:40:58,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,492 INFO sqlalchemy.engine.base.Engine ('가온누리어린이집', '신혜진', '서울특별시 성북구 숭인로 50 ,122동 1층 (길음제2동)', '02', '988', '5100', 17)
2021-08-18 17:40:58,505 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,506 INFO sqlalchemy.engine.base.Engine ('구립 해온어린이집', '서서연', '서울특별시 성동구 성수동1가 왕십리로5길 3 (성수1가제2동)', '02', '462', '6738', 16)
2021-08-18 17:40:58,506 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,507 INFO sqlalchemy.engine.base.Engine ('헬리오바른어린이집', '박영숙', '서울특별시 송파구 송파대로 345 ,, 515동 앞(가락동, 헬리오시티) (가락1동)', '02', '401', '7715', 18)
2021-08-18 17:40:58,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,509 INFO sqlalchemy.engine.base.Engine ('헬리오사랑어린이집', '강민서', '서울특별시 송파구 송파대로 345 ,, 201동 앞(가락동, 헬리오시티) (가락1동)', '02', '400', '2021', 18)
2021-08-18 17:40:58,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,512 INFO sqlalchemy.engine.base.Engine ('가재울어린이집', '송정운', '서울특별시 서대문구 모래내로15길 31 (남가좌제1동)', '02', '304', '7002', 14)
2021-08-18 17:40:58,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,514 INFO sqlalchemy.engine.base.Engine ('구립 은뜨락어린이집', '윤서연', '서울특별시 은평구 통일로 972 (진관동)', '02', '388', '7676', 22)
2021-08-18 17:40:58,515 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,517 INFO sqlalchemy.engine.base.Engine ('거여리본타운어린이집', '강미경', '서울특별시 송파구 오금로53길 14 (거여1동)', '02', '402', '1900', 18)
2021-08-18 17:40:58,518 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,518 INFO sqlalchemy.engine.base.Engine ('동화숲어린이집', '박은경', '서울특별시 송파구 송파대로 345 ,406동 104호(가락동, 헬리오시티) (가락1동)', '02', '3402', '2010', 18)
2021-08-18 17:40:58,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,520 INFO sqlalchemy.engine.base.Engine ('헬리오어린이집', '최지민', '서울특별시 송파구 송파대로 345 ,206동 103호(가락동, 헬리오시티) (가락1동)', '02', '409', '0320', 18)
2021-08-18 17:40:58,521 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,522 INFO sqlalchemy.engine.base.Engine ('아장닷컴어린이집', '정수빈', '서울특별시 강서구 화곡로42나길 30-17 (화곡본동)', '02', '2602', '8554', 4)
2021-08-18 17:40:58,523 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,524 INFO sqlalchemy.engine.base.Engine ('공릉한보어린이집', '오예준', '서울특별시 노원구 공릉로46길 19 ,102동 102호(공릉동, 한보에센시티A) (공릉2동)', '02', '977', '4659', 9)
2021-08-18 17:40:58,527 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,528 INFO sqlalchemy.engine.base.Engine ('구립 가온어린이집', '송영숙', '서울특별시 강서구 양천로 590 ,102동 102호 (등촌제1동)', '02', '2658', '0179', 4)
2021-08-18 17:40:58,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,533 INFO sqlalchemy.engine.base.Engine ('구립 강변어린이집', '박정수', '서울특별시 강서구 허준로 139 (가양제2동)', '02', '2659', '9046', 4)
2021-08-18 17:40:58,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,535 INFO sqlalchemy.engine.base.Engine ('구립 다원어린이집', '정미영', '서울특별시 은평구 갈현로19길 16 ,다원어린이집 (갈현제2동)', '02', '353', '4477', 22)
2021-08-18 17:40:58,536 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,537 INFO sqlalchemy.engine.base.Engine ('구립 뜰아래어린이집', '전성호', '서울특별시 강서구 양천로67가길 49 ,201동 105호 (염창동)', '02', '3664', '5637', 4)
2021-08-18 17:40:58,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,539 INFO sqlalchemy.engine.base.Engine ('구립 물고기어린이집', '장영진', '서울특별시 광진구 뚝섬로34길 25-19 ,1006동 102호 (자양제3동)', '070', '8278', '4030', 6)
2021-08-18 17:40:58,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,541 INFO sqlalchemy.engine.base.Engine ('구립 베라힐즈어린이집', '류영길', '서울특별시 은평구 통일로 630 ,녹번래미안베라힐즈 단지내 어린이집 (녹번동)', '02', '356', '9987', 22)
2021-08-18 17:40:58,542 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,543 INFO sqlalchemy.engine.base.Engine ('구립 베베아이어린이집', '한동현', '서울특별시 광진구 아차산로 549 ,1008동 101호(광장동,현대파크빌) (광장동)', '02', '455', '1279', 6)
2021-08-18 17:40:58,544 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,545 INFO sqlalchemy.engine.base.Engine ('구립 벽산한마음어린이집', '오광수', '서울특별시 양천구 월정로9길 20 ,양천벽산블루밍2단지 203동 106호 (신월4동)', '02', '6347', '3434', 19)
2021-08-18 17:40:58,546 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,547 INFO sqlalchemy.engine.base.Engine ('구립 봄빛어린이집', '전민석', '서울특별시 광진구 능동로 19 ,101동 103호(자양동,한강현대아파트) (자양제4동)', '02', '467', '4720', 6)
2021-08-18 17:40:58,548 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,549 INFO sqlalchemy.engine.base.Engine ('구립 사랑모아어린이집', '정민지', '서울특별시 광진구 광나루로56길 32 ,구의현대아파트 202동 103호 (구의제3동)', '02', '457', '0348', 6)
2021-08-18 17:40:58,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,550 INFO sqlalchemy.engine.base.Engine ('구립 산새소리어린이집', '류상훈', '서울특별시 은평구 서오릉로17길 10-5 ,(구립 산새소리어린이집, 구산동) (구산동)', '02', '356', '9501', 22)
2021-08-18 17:40:58,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,552 INFO sqlalchemy.engine.base.Engine ('구립 샛별어린이집', '송도현', '서울특별시 강서구 초록마을로 166 (화곡제8동)', '02', '2606', '5070', 4)
2021-08-18 17:40:58,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,554 INFO sqlalchemy.engine.base.Engine ('구립 엄마품어린이집', '전지영', '서울특별시 양천구 오목로35길 5 ,보람쉬움아파트 1동 105호 (신정4동)', '02', '2690', '7223', 19)
2021-08-18 17:40:58,555 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,556 INFO sqlalchemy.engine.base.Engine ('구립 엔젤아이어린이집', '이정호', '서울특별시 강서구 양천로 507 ,106동 104호 (가양제3동)', '02', '6341', '7373', 4)
2021-08-18 17:40:58,557 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,559 INFO sqlalchemy.engine.base.Engine ('구립 진로어린이집', '서지영', '서울특별시 강서구 공항대로 351-21 ,102동 102호 (등촌제3동)', '02', '2658', '4979', 4)
2021-08-18 17:40:58,560 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,561 INFO sqlalchemy.engine.base.Engine ('구립 청마루어린이집', '윤영자', '서울특별시 양천구 목동남로2길 60-30 ,세양청마루아파트 106동 103호 (신정7동)', '02', '2061', '6540', 19)
2021-08-18 17:40:58,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,563 INFO sqlalchemy.engine.base.Engine ('구립 청솔어린이집', '윤미영', '서울특별시 강서구 강서로47마길 71 ,107호 (발산제1동)', '02', '2606', '7045', 4)
2021-08-18 17:40:58,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,565 INFO sqlalchemy.engine.base.Engine ('구립 푸른솔어린이집', '박상철', '서울특별시 강서구 화곡로13길 107 ,104동 104호(화곡동,화곡푸르지오) (화곡제3동)', '02', '6342', '0042', 4)
2021-08-18 17:40:58,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,568 INFO sqlalchemy.engine.base.Engine ('구립 푸름어린이집', '임정식', '서울특별시 은평구 진흥로1길 35-1 (역촌동)', '02', '355', '5008', 22)
2021-08-18 17:40:58,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,571 INFO sqlalchemy.engine.base.Engine ('구립 피노키오어린이집', '전성수', '서울특별시 강서구 강서로12길 73 (화곡제8동)', '02', '2605', '7829', 4)
2021-08-18 17:40:58,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,573 INFO sqlalchemy.engine.base.Engine ('구립 하늘땅별땅어린이집', '박영길', '서울특별시 광진구 동일로56길 15 ,(군자동) (군자동)', '02', '498', '3062', 6)
2021-08-18 17:40:58,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,574 INFO sqlalchemy.engine.base.Engine ('구립 한빛어린이집', '강영철', '서울특별시 강서구 강서로8길 134 (화곡제2동)', '02', '2697', '6711', 4)
2021-08-18 17:40:58,575 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,576 INFO sqlalchemy.engine.base.Engine ('구립 해뜰어린이집', '서영철', '서울특별시 강서구 강서로68길 36 ,등촌주공2단지아파트 근로복지관2층 (등촌제3동)', '02', '3663', '0218', 4)
2021-08-18 17:40:58,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,578 INFO sqlalchemy.engine.base.Engine ('구립 행복마루어린이집', '신서연', '서울특별시 광진구 뚝섬로56가길 10 ,(자양2동 현대3차 301-105) (자양제2동)', '02', '455', '0516', 6)
2021-08-18 17:40:58,579 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,580 INFO sqlalchemy.engine.base.Engine ('구립건강한어린이집', '박민서', '서울특별시 관악구 관악로 285 ,성현동아아파트 107-103 (성현동)', '02', '6080', '8058', 5)
2021-08-18 17:40:58,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,583 INFO sqlalchemy.engine.base.Engine ('구립꼬꼬마어린이집', '강진호', '서울특별시 관악구 호암로 399 ,삼성산주공아파트 306-101 (삼성동)', '02', '6335', '2677', 5)
2021-08-18 17:40:58,584 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,585 INFO sqlalchemy.engine.base.Engine ('구립꿈의숲어린이집', '조지영', '서울특별시 강북구 오현로 180 ,101동 102호(번동, 한솔솔파크아파트) (번3동)', '02', '981', '2265', 3)
2021-08-18 17:40:58,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,586 INFO sqlalchemy.engine.base.Engine ('구립두산위브어린이집', '서민지', '서울특별시 강북구 삼양로27길 95 ,214동 103호(미아동, 두산위브아파트) (삼각산동)', '02', '982', '6804', 3)
2021-08-18 17:40:58,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,589 INFO sqlalchemy.engine.base.Engine ('구립드림타운어린이집', '전정자', '서울특별시 관악구 난곡로 55 ,관악산휴먼시아아파트 224-103 (난향동)', '02', '838', '7974', 5)
2021-08-18 17:40:58,590 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,590 INFO sqlalchemy.engine.base.Engine ('구립롯데키즈어린이집', '윤상훈', '서울특별시 동작구 여의대방로10길 38 ,보라매롯데낙천대아파트 관리동 1층 (신대방제1동)', '02', '847', '5333', 12)
2021-08-18 17:40:58,591 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,592 INFO sqlalchemy.engine.base.Engine ('구립무지개어린이집', '권영환', '서울특별시 강북구 삼양로19길 113 ,101동 101호(미아동, 삼각산아이원아파트) (삼각산동)', '02', '6228', '7326', 3)
2021-08-18 17:40:58,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,594 INFO sqlalchemy.engine.base.Engine ('구립바르니어린이집', '장영숙', '서울특별시 동작구 사당로17길 52 ,대림아파트 3-106 (사당제3동)', '02', '582', '4701', 12)
2021-08-18 17:40:58,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,595 INFO sqlalchemy.engine.base.Engine ('구립반짝반짝어린이집', '장영진', '서울특별시 강북구 삼양로27길 95 ,301동 103호(미아동,두산위브아파트) (삼각산동)', '02', '6338', '4003', 3)
2021-08-18 17:40:58,596 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,597 INFO sqlalchemy.engine.base.Engine ('구립번동어린이집', '안은영', '서울특별시 강북구 한천로124나길 34 (번1동)', '02', '902', '1889', 3)
2021-08-18 17:40:58,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,600 INFO sqlalchemy.engine.base.Engine ('구립별마루어린이집', '장민지', '서울특별시 금천구 독산로94길 17 (독산제3동)', '02', '830', '8992', 8)
2021-08-18 17:40:58,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,602 INFO sqlalchemy.engine.base.Engine ('구립별이랑어린이집', '류지영', '서울특별시 관악구 낙성대역길 19 ,동원낙성대아파트 101-106 (인헌동)', '02', '888', '2829', 5)
2021-08-18 17:40:58,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,604 INFO sqlalchemy.engine.base.Engine ('구립숲사랑어린이집', '이서연', '서울특별시 강북구 도봉로22길 7 (송중동)', '02', '985', '3465', 3)
2021-08-18 17:40:58,605 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,606 INFO sqlalchemy.engine.base.Engine ('구립아이땅어린이집', '이성민', '서울특별시 강북구 솔샘로 174 ,140동 101호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '984', '0339', 3)
2021-08-18 17:40:58,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,608 INFO sqlalchemy.engine.base.Engine ('구립아이봄어린이집', '신정수', '서울특별시 관악구 은천로 86 ,두산아파트 208-101 (은천동)', '02', '883', '2081', 5)
2021-08-18 17:40:58,609 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,610 INFO sqlalchemy.engine.base.Engine ('구립어린왕자어린이집', '안정남', '서울특별시 강북구 한천로124나길 10 ,101동 108호(번동,번동쌍용아파트) (번1동)', '02', '906', '1123', 3)
2021-08-18 17:40:58,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,613 INFO sqlalchemy.engine.base.Engine ('구립캐슬아이어린이집', '오순자', '서울특별시 금천구 벚꽃로 30 ,금천 롯데캐슬 골드파크 2차 관리동어린이집 (독산제1동)', '02', '804', '7999', 8)
2021-08-18 17:40:58,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,616 INFO sqlalchemy.engine.base.Engine ('구립킨더어린이집', '임혜진', '서울특별시 강북구 숭인로 39 ,관리동 1층(미아동,송천센트레빌아파트) (송천동)', '02', '6015', '2345', 3)
2021-08-18 17:40:58,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,618 INFO sqlalchemy.engine.base.Engine ('구립튼튼어린이집', '윤민지', '서울특별시 강북구 솔샘로 174 ,116동 101호(미아동, SK북한산시티아파트) (삼각산동)', '02', '945', '9127', 3)
2021-08-18 17:40:58,620 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,621 INFO sqlalchemy.engine.base.Engine ('구립해맑은어린이집', '송경회', '서울특별시 금천구 독산로35길 15-6 ,한백아트 101호 (시흥제1동)', '02', '803', '1227', 8)
2021-08-18 17:40:58,622 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,623 INFO sqlalchemy.engine.base.Engine ('구립햇님몬테소리어린이집', '정정호', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트 120-103 (청림동)', '02', '883', '9277', 5)
2021-08-18 17:40:58,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,625 INFO sqlalchemy.engine.base.Engine ('구립희아어린이집', '박지은', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트 122-101 (청림동)', '02', '886', '0801', 5)
2021-08-18 17:40:58,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,627 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '서도현', '서울특별시 노원구 공릉로46길 32 ,107동 111호(공릉동, 삼익A) (공릉2동)', '02', '6229', '3165', 9)
2021-08-18 17:40:58,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,630 INFO sqlalchemy.engine.base.Engine ('꼬마박사어린이집', '오정자', '서울특별시 서대문구 거북골로 120 ,203동 103호 (남가좌제2동)', '02', '309', '8557', 14)
2021-08-18 17:40:58,631 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,632 INFO sqlalchemy.engine.base.Engine ('꿈의숲어린이집', '권은영', '서울특별시 노원구 섬밭로 139 ,105동 103호(공릉동, 풍림A) (공릉1동)', '02', '978', '1189', 9)
2021-08-18 17:40:58,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,634 INFO sqlalchemy.engine.base.Engine ('다울어린이집', '윤지민', '서울특별시 도봉구 마들로 672-26 (도봉제2동)', '02', '3493', '9674', 10)
2021-08-18 17:40:58,636 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,637 INFO sqlalchemy.engine.base.Engine ('도봉2동다솜어린이집', '이병철', '서울특별시 도봉구 마들로 859-19 ,124동 101호 (도봉제2동)', '02', '955', '0207', 10)
2021-08-18 17:40:58,638 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,638 INFO sqlalchemy.engine.base.Engine ('도봉2동리틀포도나무어린이집', '오민서', '서울특별시 도봉구 마들로 835 ,202동 102호 (도봉제2동)', '02', '955', '0040', 10)
2021-08-18 17:40:58,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,640 INFO sqlalchemy.engine.base.Engine ('동원어린이집', '조성수', '서울특별시 노원구 월계로53길 21 ,101동 101호(월계동, 동원베네스트A) (월계2동)', '02', '902', '1222', 9)
2021-08-18 17:40:58,641 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,642 INFO sqlalchemy.engine.base.Engine ('방학1동고은뜰어린이집', '강준호', '서울특별시 도봉구 마들로 616 ,203동 102호 (방학제1동)', '02', '954', '3138', 10)
2021-08-18 17:40:58,643 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,644 INFO sqlalchemy.engine.base.Engine ('방학1동행복한천사어린이집', '안건우', '서울특별시 도봉구 도당로 116 ,101동 102호 (방학제1동)', '02', '955', '1951', 10)
2021-08-18 17:40:58,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,646 INFO sqlalchemy.engine.base.Engine ('방학3동맑은샘어린이집', '서광수', '서울특별시 도봉구 해등로 312-10 (방학제3동)', '02', '955', '5528', 10)
2021-08-18 17:40:58,648 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,649 INFO sqlalchemy.engine.base.Engine ('방학3동해니크레오어린이집', '전준혁', '서울특별시 도봉구 시루봉로 166 ,102동 104호 (방학제3동)', '02', '3493', '1192', 10)
2021-08-18 17:40:58,650 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,651 INFO sqlalchemy.engine.base.Engine ('벧엘어린이집', '류건우', '서울특별시 노원구 동일로207길 18 ,119동 102호(중계동, 중계그린A) (중계2.3동)', '02', '971', '5768', 9)
2021-08-18 17:40:58,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,661 INFO sqlalchemy.engine.base.Engine ('보람자연어린이집', '서병철', '서울특별시 노원구 한글비석로 479 ,102동 109호(상계동, 보람A) (상계9동)', '02', '933', '7070', 9)
2021-08-18 17:40:58,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,665 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '신성호', '서울특별시 도봉구 덕릉로62길 30 (창제3동)', '02', '903', '2978', 10)
2021-08-18 17:40:58,668 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:58,672 INFO sqlalchemy.engine.base.Engine ('새나어린이집', '박정운', '서울특별시 도봉구 도봉로110바길 38 (창제1동)', '02', '906', '3334', 10)
2021-08-18 17:40:58,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,677 INFO sqlalchemy.engine.base.Engine ('색종이어린이집', '정수빈', '서울특별시 노원구 동일로227길 86 ,1603동 103호(상계동, 주공16단지A) (상계8동)', '02', '937', '7949', 9)
2021-08-18 17:40:58,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,680 INFO sqlalchemy.engine.base.Engine ('서초구립 방배아트자이어린이집', '강정웅', '서울특별시 서초구 명달로9길 57 ,관리동 (방배3동)', '02', '522', '7600', 15)
2021-08-18 17:40:58,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,683 INFO sqlalchemy.engine.base.Engine ('서초구립 삼호3차가온어린이집', '장영철', '서울특별시 서초구 방배로45길 2 ,13동 104호 (방배본동)', '070', '7576', '2425', 15)
2021-08-18 17:40:58,685 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,686 INFO sqlalchemy.engine.base.Engine ('솔바람어린이집', '최민서', '서울특별시 노원구 노원로 428 ,209동 104호(상계동, 상계2차중앙하이츠A) (상계2동)', '02', '933', '3601', 9)
2021-08-18 17:40:58,687 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,688 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '류서현', '서울특별시 동대문구 사가정로 190 ,13동 101호(전농동,전농우성아파트) (전농제2동)', '02', '2215', '6395', 11)
2021-08-18 17:40:58,692 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,694 INFO sqlalchemy.engine.base.Engine ('아이랑어린이집', '정순자', '서울특별시 동대문구 한천로55길 9 ,102동 109호(이문동,이문동삼익아파트) (이문제1동)', '02', '960', '0057', 11)
2021-08-18 17:40:58,695 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,695 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '박준영', '서울특별시 중랑구 봉화산로48길 62 ,104동 105호(상봉동,건영아파트) (상봉제1동)', '02', '432', '2890', 25)
2021-08-18 17:40:58,697 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,698 INFO sqlalchemy.engine.base.Engine ('엄마사랑i어린이집', '조종수', '서울특별시 노원구 마들로 31 ,103동 102호(월계동, 그랑빌A) (월계3동)', '02', '949', '9077', 9)
2021-08-18 17:40:58,701 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,702 INFO sqlalchemy.engine.base.Engine ('예닮어린이집', '이민지', '서울특별시 동대문구 무학로26길 30 ,1동 103호(용두동,신동아아파트) (용신동)', '02', '6462', '2842', 11)
2021-08-18 17:40:58,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,704 INFO sqlalchemy.engine.base.Engine ('우남어린이집', '한상훈', '서울특별시 중랑구 봉화산로56길 51 ,101동 101호(신내동,우남푸르미아아파트) (신내1동)', '02', '3422', '5790', 25)
2021-08-18 17:40:58,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,706 INFO sqlalchemy.engine.base.Engine ('우리들어린이집', '최정운', '서울특별시 서대문구 세검정로1길 95 ,벽산아파트 107동 106호 (홍은제1동)', '02', '379', '7955', 14)
2021-08-18 17:40:58,708 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,708 INFO sqlalchemy.engine.base.Engine ('우림해피어린이집', '오은경', '서울특별시 노원구 동일로230가길 71 ,102동 103호(상계동, 우림루미아트A) (상계1동)', '02', '938', '9706', 9)
2021-08-18 17:40:58,710 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,711 INFO sqlalchemy.engine.base.Engine ('우방어린이집', '전민지', '서울특별시 구로구 구일로 154-17 ,101동 101호 (구로제1동)', '02', '858', '0506', 7)
2021-08-18 17:40:58,712 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,713 INFO sqlalchemy.engine.base.Engine ('은행나무어린이집', '강영식', '서울특별시 도봉구 방학로 187 ,관리동 1층 (방학제3동)', '02', '956', '9568', 10)
2021-08-18 17:40:58,715 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,716 INFO sqlalchemy.engine.base.Engine ('이레뜰어린이집', '임도현', '서울특별시 노원구 동일로192나길 26 ,101동 105호(공릉동, 신원A) (공릉1동)', '02', '973', '3533', 9)
2021-08-18 17:40:58,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,718 INFO sqlalchemy.engine.base.Engine ('이수어린이집', '권은영', '서울특별시 중랑구 공릉로18길 59 ,105동107호(묵동,브라운스톤태릉아파트) (묵제1동)', '02', '949', '8915', 25)
2021-08-18 17:40:58,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,720 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '윤민재', '서울특별시 동대문구 장한로26다길 38 (장안제2동)', '02', '2212', '6717', 11)
2021-08-18 17:40:58,721 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,722 INFO sqlalchemy.engine.base.Engine ('자람어린이집', '송유진', '서울특별시 노원구 누원로 18 ,402동 103호(상계동, 수락리버시티4단지A) (상계1동)', '02', '930', '3441', 9)
2021-08-18 17:40:58,724 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,725 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '이민지', '서울특별시 동대문구 한천로37길 33 ,104동 104호(답십리동,래미안엘파인아파트) (답십리제2동)', '02', '2213', '1566', 11)
2021-08-18 17:40:58,726 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,727 INFO sqlalchemy.engine.base.Engine ('작은별어린이집', '류준호', '서울특별시 노원구 덕릉로60길 252 ,101동 106호(월계동, 유원A) (월계2동)', '02', '995', '5622', 9)
2021-08-18 17:40:58,727 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,728 INFO sqlalchemy.engine.base.Engine ('창3동신도아이숲어린이집', '전민재', '서울특별시 도봉구 우이천로4라길 11-14 ,102동 107호 (창제3동)', '02', '998', '9598', 10)
2021-08-18 17:40:58,729 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,730 INFO sqlalchemy.engine.base.Engine ('창5동아이조아어린이집', '정정웅', '서울특별시 도봉구 해등로 118 ,2동 110호 (창제5동)', '02', '906', '1732', 10)
2021-08-18 17:40:58,732 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,733 INFO sqlalchemy.engine.base.Engine ('청구몬테소리어린이집', '장정수', '서울특별시 노원구 동일로207길 186 ,110동 103호(하계동, 학여울청구A) (하계2동)', '02', '949', '2961', 9)
2021-08-18 17:40:58,735 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,735 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '장지혜', '서울특별시 노원구 동일로 1456 ,710동 102호(상계동, 주공7단지A) (상계10동)', '02', '932', '0333', 9)

2021-08-18 17:40:58,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,737 INFO sqlalchemy.engine.base.Engine ('파크자이어린이집', '장건우', '서울특별시 동대문구 답십리로56길 105 ,관리동(답십리동,파크자이아파트) (답십리제2동)', '02', '3394', '7987', 11)
2021-08-18 17:40:58,738 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,739 INFO sqlalchemy.engine.base.Engine ('하늘샘어린이집', '안준호', '서울특별시 구로구 개봉로18길 17 (개봉제2동)', '02', '2615', '8825', 7)
2021-08-18 17:40:58,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,741 INFO sqlalchemy.engine.base.Engine ('학마을어린이집', '안병철', '서울특별시 도봉구 도봉로145길 95 (방학제1동)', '02', '954', '3700', 10)
2021-08-18 17:40:58,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,744 INFO sqlalchemy.engine.base.Engine ('한진예닮어린이집', '이영자', '서울특별시 구로구 개봉로3길 87 ,101동 101호(개봉동,한진타운아파트) (개봉제3동)', '02', '2613', '3990', 7)
2021-08-18 17:40:58,746 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,747 INFO sqlalchemy.engine.base.Engine ('해가람어린이집', '송현정', '서울특별시 구로구 신도림로21길 25 ,301동 106호 (신도림동)', '02', '2675', '8330', 7)
2021-08-18 17:40:58,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,749 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '임광수', '서울특별시 구로구 공원로6가길 67 ,3동 102호(구로동,구로우성아파트) (구로제5동)', '02', '857', '5110', 7)
2021-08-18 17:40:58,750 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,751 INFO sqlalchemy.engine.base.Engine ('해피키즈어린이집', '조민재', '서울특별시 서대문구 문화촌길 6-24 ,101동 112호(홍제동, 문화촌현대아파트) (홍제제3동)', '02', '6371', '1005', 14)
2021-08-18 17:40:58,753 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,754 INFO sqlalchemy.engine.base.Engine ('햇살나무어린이집', '조준영', '서울특별시 서대문구 연희로 377 ,202동 104호 (홍은제2동)', '02', '396', '0397', 14)
2021-08-18 17:40:58,755 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,756 INFO sqlalchemy.engine.base.Engine ('행복이가득한어린이집', '안민지', '서울특별시 노원구 한글비석로24바길 17 ,(상계동) (상계3.4동)', '02', '951', '7775', 9)
2021-08-18 17:40:58,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,762 INFO sqlalchemy.engine.base.Engine ('현대아이들세상어린이집', '류정웅', '서울특별시 노원구 석계로 49 ,105동 102호(월계동, 현대A) (월계1동)', '02', '943', '1565', 9)
2021-08-18 17:40:58,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,765 INFO sqlalchemy.engine.base.Engine ('나이스 가온 어린이집', '최상철', '서울특별시 영등포구 국회대로74길 19 ,1~2층 (여의동)', '02', '780', '9370', 20)
2021-08-18 17:40:58,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,767 INFO sqlalchemy.engine.base.Engine ('너나들이어린이집', '권준호', '서울특별시 중랑구 신내역로1길 145 ,102호(신내동,신내소행주) (신내1동)', '070', '7743', '7772', 25)
2021-08-18 17:40:58,768 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,769 INFO sqlalchemy.engine.base.Engine ('명동하나금융그룹직장어린이집', '신영철', '서울특별시 중구 을지로2가 을지로 66 ,하나금융그룹 명동사옥 2층 (명동)', '02', '319', '9606', 24)
2021-08-18 17:40:58,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,772 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '윤영자', '서울특별시 강남구 광평로34길 35 ,강남더샵포레스트 관리동 (수서동)', '02', '3411', '0972', 1)
2021-08-18 17:40:58,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,775 INFO sqlalchemy.engine.base.Engine ('선혜어린이집', '권예은', '서울특별시 강남구 선릉로 8 ,레미안블레스티지 관리동 (개포제2동)', '02', '2057', '7004', 1)
2021-08-18 17:40:58,776 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,777 INFO sqlalchemy.engine.base.Engine ('거여초원어린이집', '정민서', '서울특별시 송파구 양산로4길 16 ,관리동 1층(거여동, 거여5단지) (거여2동)', '02', '402', '2190', 18)
2021-08-18 17:40:58,779 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,779 INFO sqlalchemy.engine.base.Engine ('쌍용아이사랑어린이집', '윤정자', '서울특별시 송파구 송이로15길 31 ,(가락동, 가락2차쌍용아파트) (가락본동)', '02', '430', '8387', 18)
2021-08-18 17:40:58,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,783 INFO sqlalchemy.engine.base.Engine ('우리에프아이에스어린이집', '최영식', '서울특별시 마포구 월드컵북로60길 17 ,3층 (상암동)', '02', '302', '6393', 13)
2021-08-18 17:40:58,784 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,785 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '황예준', '서울특별시 강서구 마곡서1로 100 ,607-104(마곡동,마곡엠벨리6단지) (방화제1동)', '070', '4233', '1225', 4)
2021-08-18 17:40:58,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,788 INFO sqlalchemy.engine.base.Engine ('서울서부지방법원 어린이집', '정현준', '서울특별시 마포구 마포대로 199 ,4층 (아현동)', '02', '3271', '9270', 13)
2021-08-18 17:40:58,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,791 INFO sqlalchemy.engine.base.Engine ('루나밸리어린이집', '장건우', '서울특별시 성북구 월곡로14길 26 ,관리동 (월곡제2동)', '02', '913', '7475', 17)
2021-08-18 17:40:58,794 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,795 INFO sqlalchemy.engine.base.Engine ('구립 성수롯데캐슬어린이집', '최예준', '서울특별시 성동구 성수동2가 성수일로8길 47 ,관리동 (성수동2가, 성수동 롯데캐슬파크) (성수2가제3동)', '02', '499', '1177', 16)
2021-08-18 17:40:58,796 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,797 INFO sqlalchemy.engine.base.Engine ('구립꽃다비어린이집', '정정운', '서울특별시 강동구 성안로31마길 9 ,(천호동) (천호제3동)', '02', '473', '0513', 2)
2021-08-18 17:40:58,800 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,804 INFO sqlalchemy.engine.base.Engine ('꿈의숲코오롱하늘채어린이집', '안영진', '서울특별시 성북구 돌곶이로 220 (장위제3동)', '02', '909', '2700', 17)
2021-08-18 17:40:58,806 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,808 INFO sqlalchemy.engine.base.Engine ('별이달이어린이집', '신지훈', '서울특별시 영등포구 대림로22길 29 ,102동 103호(갑을명가아파트) (대림제1동)', '02', '846', '6549', 20)

2021-08-18 17:40:58,809 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,811 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '송준혁', '서울특별시 영등포구 문래동3가 문래로 94-7 ,101동 107호(문래건영아파트) (문래동)', '02', '6104', '7912', 20)
2021-08-18 17:40:58,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,814 INFO sqlalchemy.engine.base.Engine ('아이존어린이집', '황정순', '서울특별시 영등포구 당산동2가 당산로 95 ,105동 103호(현대아파트) (당산제1동)', '02', '833', '1446', 20)
2021-08-18 17:40:58,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,817 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '오종수', '서울특별시 영등포구 문래동6가 문래로4길 14 ,101동 104호(현대아파트) (문래동)', '02', '2679', '0671', 20)
2021-08-18 17:40:58,819 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,821 INFO sqlalchemy.engine.base.Engine ('큰나무어린이집', '이예준', '서울특별시 영등포구 문래동3가 문래로20길 14 ,2동 103호(문래공원한신아파트) (문래동)', '02', '6335', '2903', 20)
2021-08-18 17:40:58,823 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,825 INFO sqlalchemy.engine.base.Engine ('BSP어린이집', '서미숙', '서울특별시 서초구 고무래로 89 ,반포써밋푸르지오 아파트 단지 내 (반포1동)', '02', '532', '0800', 15)
2021-08-18 17:40:58,827 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,828 INFO sqlalchemy.engine.base.Engine ('오금숲어린이집', '임은정', '서울특별시 송파구 중대로27길 2 (오금동)', '02', '430', '4399', 18)
2021-08-18 17:40:58,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,832 INFO sqlalchemy.engine.base.Engine ('롯데가온어린이집', '안경숙', '서울특별시 금천구 시흥대로 291 (독산제1동)', '02', '805', '2176', 8)
2021-08-18 17:40:58,835 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,836 INFO sqlalchemy.engine.base.Engine ('파인3어린이집', '김경자', '서울특별시 송파구 충민로 152 ,관리동 1층(장지동, 송파파인타운3단지) (장지동)', '02', '403', '1218', 18)
2021-08-18 17:40:58,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,838 INFO sqlalchemy.engine.base.Engine ('항동라온어린이집', '황병철', '서울특별시 구로구 서해안로 2036 ,803동 1층 (항동)', '02', '2066', '5700', 7)
2021-08-18 17:40:58,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,841 INFO sqlalchemy.engine.base.Engine ('베르디움어린이집', '권준호', '서울특별시 송파구 동남로 342 ,101동 1층 (오금동)', '02', '408', '2280', 18)
2021-08-18 17:40:58,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,844 INFO sqlalchemy.engine.base.Engine ('헬리오가람어린이집', '오은영', '서울특별시 송파구 송파대로 345 ,, 103동 앞(가락동,헬리오시티) (가락1동)', '02', '402', '5005', 18)
2021-08-18 17:40:58,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,846 INFO sqlalchemy.engine.base.Engine ('헬리오나래어린이집', '안지은', '서울특별시 송파구 송파대로 345 ,, 209동 뒤(가락동,헬리오시티) (가락1동)', '02', '403', '6909', 18)
2021-08-18 17:40:58,847 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,849 INFO sqlalchemy.engine.base.Engine ('헬리오다올어린이집', '전지훈', '서울특별시 송파구 송파대로 345 ,306동 앞(가락동,헬리오시티) (가락1동)', '02', '400', '2120', 18)
2021-08-18 17:40:58,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,852 INFO sqlalchemy.engine.base.Engine ('헬리오라온어린이집', '강지은', '서울특별시 송파구 송파대로 345 ,,414동 앞(가락동,헬리오시티) (가락1동)', '02', '430', '4030', 18)
2021-08-18 17:40:58,853 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,854 INFO sqlalchemy.engine.base.Engine ('문래동제2어린이집', '강영환', '서울특별시 영등포구 문래동5가 선유로5길 8 (문래동)', '02', '2069', '4911', 20)
2021-08-18 17:40:58,855 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,857 INFO sqlalchemy.engine.base.Engine ('새봄빛어린이집', '한건우', '서울특별시 성북구 숭인로 50 ,112동 1층 (길음제2동)', '02', '945', '2800', 17)
2021-08-18 17:40:58,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,860 INFO sqlalchemy.engine.base.Engine ('아트리치어린이집', '임영환', '서울특별시 성북구 돌곶이로8길 22 ,1층 2층 (석관동)', '02', '964', '1964', 17)
2021-08-18 17:40:58,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,863 INFO sqlalchemy.engine.base.Engine ('방이어린이집', '김민재', '서울특별시 송파구 오금로23길 27 (방이2동)', '02', '412', '0008', 18)
2021-08-18 17:40:58,865 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,866 INFO sqlalchemy.engine.base.Engine ('구립 목2동어린이집', '강준영', '서울특별시 양천구 목동중앙본로 104-1 (목2동)', '02', '6741', '1002', 19)
2021-08-18 17:40:58,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,869 INFO sqlalchemy.engine.base.Engine ('구립강마루어린이집', '윤종수', '서울특별시 동작구 현충로 52 ,흑석아크로리버하임 아파트 (흑석동)', '02', '814', '3200', 12)
2021-08-18 17:40:58,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,873 INFO sqlalchemy.engine.base.Engine ('구립꿈마루어린이집', '김민지', '서울특별시 동작구 현충로 52 ,흑석아크로리버하임 아파트 관리동 (흑석동)', '02', '6277', '6990', 12)
2021-08-18 17:40:58,874 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,875 INFO sqlalchemy.engine.base.Engine ('구립노블어린이집', '안은정', '서울특별시 동작구 만양로 6 ,e편한세상상도노빌리티 관리동 (상도제2동)', '02', '812', '0668', 12)
2021-08-18 17:40:58,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,878 INFO sqlalchemy.engine.base.Engine ('구립이솔어린이집', '신정운', '서울특별시 동작구 서달로 123 (흑석동)', '02', '815', '0492', 12)
2021-08-18 17:40:58,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,880 INFO sqlalchemy.engine.base.Engine ('소담어린이집', '오상철', '서울특별시 강남구 개포로110길 50 (일원제2동)', '02', '445', '1601', 1)
2021-08-18 17:40:58,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,884 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '임민석', '서울특별시 강남구 삼성로 629 (삼성제2동)', '02', '517', '7550', 1)

2021-08-18 17:40:58,886 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,888 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '임성진', '서울특별시 강남구 헌릉로590길 88 (세곡동)', '02', '3411', '6227', 1)
2021-08-18 17:40:58,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,894 INFO sqlalchemy.engine.base.Engine ('현대오토에버 어린이집', '송예은', '서울특별시 강남구 테헤란로113길 12 (삼성1동)', '02', '6200', '4055', 1)
2021-08-18 17:40:58,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,897 INFO sqlalchemy.engine.base.Engine ('늘해랑어린이집', '김미숙', '서울특별시 영등포구 양평동4가 선유로47길 30 ,(양평동) (양평제2동)', '02', '2069', '2780', 20)
2021-08-18 17:40:58,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,901 INFO sqlalchemy.engine.base.Engine ('리버빌꿈마을어린이집', '황영철', '서울특별시 송파구 토성로 37 (풍납2동)', '02', '474', '1411', 18)
2021-08-18 17:40:58,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,903 INFO sqlalchemy.engine.base.Engine ('강서구공공직장어린이집', '한준서', '서울특별시 강서구 강서로33가길 42 (화곡제3동)', '02', '2690', '2600', 4)
2021-08-18 17:40:58,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,906 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '정서현', '서울특별시 구로구 고척로52나길 25 ,1층 어린이집 (고척제2동)', '02', '2685', '1324', 7)
2021-08-18 17:40:58,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,908 INFO sqlalchemy.engine.base.Engine ('문래힐스테이트어린이집', '류지민', '서울특별시 영등포구 문래동3가 문래로 82 ,문래동 힐스테이트 관리동 (문래동)', '02', '2633', '2233', 20)
2021-08-18 17:40:58,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,911 INFO sqlalchemy.engine.base.Engine ('해봄어린이집', '권지원', '서울특별시 구로구 금오로 882 ,어린이집 (오류제2동)', '02', '2689', '7879', 7)
2021-08-18 17:40:58,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,913 INFO sqlalchemy.engine.base.Engine ('구립난곡어린이집', '한성호', '서울특별시 관악구 난곡로31길 14 (난곡동)', '02', '838', '3766', 5)
2021-08-18 17:40:58,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,917 INFO sqlalchemy.engine.base.Engine ('구립 그린나래어린이집', '오종수', '서울특별시 양천구 신정로 170 ,신정현대아파트 관리동 (신정3동)', '02', '2060', '5783', 19)
2021-08-18 17:40:58,918 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,918 INFO sqlalchemy.engine.base.Engine ('구립 꿈동산어린이집', '황민지', '서울특별시 양천구 신정로14길 6 ,학마을1단지아파트 관리동 (신정3동)', '02', '2060', '6637', 19)
2021-08-18 17:40:58,920 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,921 INFO sqlalchemy.engine.base.Engine ('구립 미래어린이집', '권민석', '서울특별시 광진구 아차산로 503-23 ,104동 113호(광장동, 청구아파트) (광장동)', '02', '447', '4191', 6)
2021-08-18 17:40:58,922 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,923 INFO sqlalchemy.engine.base.Engine ('구립 보금자리어린이집', '권종수', '서울특별시 양천구 오목로29길 25 ,101-102 (신정4동)', '02', '2608', '3614', 19)
2021-08-18 17:40:58,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,926 INFO sqlalchemy.engine.base.Engine ('구립 신트리어린이집', '조정식', '서울특별시 양천구 신정로 293 ,신트리1단지아파트 관리동 (신정3동)', '02', '2065', '1400', 19)
2021-08-18 17:40:58,927 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,928 INFO sqlalchemy.engine.base.Engine ('구립슬기어린이집', '송지영', '서울특별시 금천구 한내로 69-54 ,1402동 101호(독산동, 주공14단지아파트) (독산제1동)', '02', '805', '2004', 8)
2021-08-18 17:40:58,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,931 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '권정순', '서울특별시 중랑구 봉화산로56길 145-1 ,5동 103호(신내동, 중앙하이츠아파트) (신내1동)', '02', '6212', '0330', 25)
2021-08-18 17:40:58,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,934 INFO sqlalchemy.engine.base.Engine ('예슬어린이집', '윤영철', '서울특별시 중랑구 신내로7나길 24 ,212동 102호(상봉동, 건영2차아파트) (상봉제1동)', '02', '434', '6563', 25)
2021-08-18 17:40:58,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,936 INFO sqlalchemy.engine.base.Engine ('가락1동어린이집', '신준영', '서울특별시 송파구 양재대로 921 ,구립가락1동어린이집 (가락1동)', '02', '400', '9210', 18)
2021-08-18 17:40:58,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,938 INFO sqlalchemy.engine.base.Engine ('강서햇빛발도르프어린이집', '서성호', '서울특별시 강서구 까치산로18길 35 ,강서햇빛발도르프어린이집 (화곡제6동)', '02', '2653', '2462', 4)
2021-08-18 17:40:58,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,940 INFO sqlalchemy.engine.base.Engine ('금빛어린이집', '서정남', '서울특별시 강동구 고덕로27길 36 ,107동 101호(암사동, 현대홈타운) (암사제3동)', '02', '477', '6775', 2)
2021-08-18 17:40:58,941 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,942 INFO sqlalchemy.engine.base.Engine ('노블레스어린이집', '조지훈', '서울특별시 동대문구 답십리로23길 30 ,관리동(전농동,롯데캐슬노블레스아파트) (전농제1동)', '02', '6933', '7336', 11)
2021-08-18 17:40:58,943 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,944 INFO sqlalchemy.engine.base.Engine ('미드카운티어린이집', '오지원', '서울특별시 동대문구 답십리로 141 ,(답십리동,래미안미드카운티아파트) (답십리제1동)', '02', '6713', '1410', 11)
2021-08-18 17:40:58,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,946 INFO sqlalchemy.engine.base.Engine ('벽산에덴어린이집', '안영일', '서울특별시 금천구 금하로 816 ,512동 103호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '809', '1556', 8)
2021-08-18 17:40:58,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,949 INFO sqlalchemy.engine.base.Engine ('서초구립 반포래미안아이파크어린이집', '서정식', '서울특별시 서초구 서초중앙로 220 ,112동(반포래미안아이파크) (반포1동)', '02', '595', '3366', 15)
2021-08-18 17:40:58,951 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,952 INFO sqlalchemy.engine.base.Engine ('구립 스위첸숲속어린이집', '최은정', '서울특별시 성동구 무학봉길 35 (왕십리제2동)', '02', '2282', '2847', 16)

2021-08-18 17:40:58,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,954 INFO sqlalchemy.engine.base.Engine ('구립꿈이찬어린이집', '권준영', '서울특별시 강동구 천중로27길 70 (천호제1동)', '02', '478', '2220', 2)
2021-08-18 17:40:58,955 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,956 INFO sqlalchemy.engine.base.Engine ('구립별가득어린이집', '안준혁', '서울특별시 강동구 양재대로97길 17 (성내제3동)', '02', '473', '1903', 2)
2021-08-18 17:40:58,957 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,958 INFO sqlalchemy.engine.base.Engine ('가람어린이집', '오성수', '서울특별시 동대문구 왕산로23길 89 ,101동 101호(제기동,이수브라운스톤아파트) (제기동)', '02', '922', '2018', 11)
2021-08-18 17:40:58,959 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,960 INFO sqlalchemy.engine.base.Engine ('거여새싹어린이집', '서상철', '서울특별시 송파구 양산로8길 8 ,관리동 1층(거여동, 거여1단지아파트) (거여2동)', '02', '3401', '5427', 18)
2021-08-18 17:40:58,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,963 INFO sqlalchemy.engine.base.Engine ('구립 아이누리어린이집', '송영자', '서울특별시 양천구 목동중앙북로8길 71 ,목동롯데캐슬마에스트로 (목3동)', '02', '2654', '7780', 19)
2021-08-18 17:40:58,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,966 INFO sqlalchemy.engine.base.Engine ('구립 파크스위트어린이집', '송건우', '서울특별시 광진구 광나루로 545 ,110동 1층(구의동, 래미안파크스위트) (구의제2동)', '02', '456', '8546', 6)
2021-08-18 17:40:58,967 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,968 INFO sqlalchemy.engine.base.Engine ('파인12어린이집', '신성호', '서울특별시 송파구 송파대로8길 42 ,구립파인12어린이집(장지동, 송파파인타운12단지) (장지동)', '02', '402', '7942', 18)
2021-08-18 17:40:58,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,969 INFO sqlalchemy.engine.base.Engine ('가람슬기어린이집', '오민지', '서울특별시 마포구 마포대로11길 44-81 ,아현문화건강센터 1층 (아현동)', '02', '312', '3001', 13)
2021-08-18 17:40:58,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,971 INFO sqlalchemy.engine.base.Engine ('경선어린이집', '권정식', '서울특별시 구로구 개봉로20길 6 ,118동 102호 (개봉제2동)', '02', '6095', '5915', 7)
2021-08-18 17:40:58,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,974 INFO sqlalchemy.engine.base.Engine ('구립 군자동 꿈모음어린이집', '최영숙', '서울특별시 광진구 군자로12길 6-4 ,(군자동 363-28) (군자동)', '02', '499', '0011', 6)
2021-08-18 17:40:58,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,977 INFO sqlalchemy.engine.base.Engine ('구립 아띠어린이집', '안지영', '서울특별시 광진구 광나루로56길 32 ,(구의동, 구의현대2단지아파트 213동 102호) (구의제3동)', '02', '454', '7911', 6)
2021-08-18 17:40:58,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,979 INFO sqlalchemy.engine.base.Engine ('구립 양천SOS어린이집', '오은정', '서울특별시 양천구 가로공원로58길 32 ,1층 (신월3동)', '02', '2699', '9014', 19)
2021-08-18 17:40:58,981 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,982 INFO sqlalchemy.engine.base.Engine ('구립 자양1동 봄뜰어린이집', '오영식', '서울특별시 광진구 자양로9길 30 ,(자양동 629-40) (자양제1동)', '02', '453', '2260', 6)
2021-08-18 17:40:58,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,983 INFO sqlalchemy.engine.base.Engine ('구립 초록나무어린이집', '김예준', '서울특별시 양천구 오목로35길 22 ,101호 (신정4동)', '02', '2608', '3654', 19)
2021-08-18 17:40:58,984 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,986 INFO sqlalchemy.engine.base.Engine ('구립솔샘어린이집', '안정호', '서울특별시 강북구 삼양로74길 8 ,102동 102호(미아동, 경남아너스빌) (삼양동)', '02', '989', '5321', 3)
2021-08-18 17:40:58,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,988 INFO sqlalchemy.engine.base.Engine ('동부이촌어린이집', '서영철', '서울특별시 용산구 이촌로 193 ,관리동 1층 (이촌제1동)', '02', '797', '7857', 21)
2021-08-18 17:40:58,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,990 INFO sqlalchemy.engine.base.Engine ('또래어린이집', '전성수', '서울특별시 노원구 동일로245가길 41 ,202동 106호 (상계동, 은빛아파트) (상계1동)', '02', '952', '5880', 9)
2021-08-18 17:40:58,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,992 INFO sqlalchemy.engine.base.Engine ('미키미니어린이집', '류준혁', '서울특별시 노원구 초안산로1길 18 ,2단지 내 관리동 (월계동, 월계주공2단지) (월계2동)', '02', '906', '8886', 9)
2021-08-18 17:40:58,994 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,995 INFO sqlalchemy.engine.base.Engine ('비선어린이집', '류은영', '서울특별시 노원구 화랑로51길 78 ,관리동 (공릉동, 비선아파트) (공릉2동)', '02', '948', '2166', 9)
2021-08-18 17:40:58,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,996 INFO sqlalchemy.engine.base.Engine ('서초구립 신반포아크로빛어린이집', '강동현', '서울특별시 서초구 잠원로 117 ,신반포아크로리버뷰아파트 104동 (반포3동)', '02', '532', '2001', 15)
2021-08-18 17:40:58,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:58,998 INFO sqlalchemy.engine.base.Engine ('서초구립 신반포자이어린이집', '송정호', '서울특별시 서초구 잠원로 60 (반포3동)', '02', '535', '5128', 15)
2021-08-18 17:40:58,999 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,000 INFO sqlalchemy.engine.base.Engine ('수락예지어린이집', '안민서', '서울특별시 노원구 누원로 28 ,304동 1층(상계동, 수락리버시티3단지) (상계1동)', '02', '936', '3050', 9)
2021-08-18 17:40:59,001 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,001 INFO sqlalchemy.engine.base.Engine ('아현아이파크어린이집', '최종수', '서울특별시 마포구 마포대로 246 ,아현아이파크아파트 103동 1층 (공덕동)', '02', '365', '2003', 13)
2021-08-18 17:40:59,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,003 INFO sqlalchemy.engine.base.Engine ('유린어린이집', '장현준', '서울특별시 중랑구 신내로 56 (신내1동)', '02', '438', '4014', 25)
2021-08-18 17:40:59,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,005 INFO sqlalchemy.engine.base.Engine ('점프어린이집', '오영식', '서울특별시 노원구 동일로241길 53 ,109동 104호 (상계동, 두산아파트) (상계1동)', '02', '6221', '4570', 9)
2021-08-18 17:40:59,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,007 INFO sqlalchemy.engine.base.Engine ('청솔어린이집', '이준영', '서울특별시 동대문구 전농로10길 20 ,(답십리동) (답십리제2동)', '02', '3394', '5026', 11)
2021-08-18 17:40:59,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,010 INFO sqlalchemy.engine.base.Engine ('청아어린이집', '신광수', '서울특별시 동대문구 천호대로55길 11 ,(답십리동,힐스테이트청계아파트 내) (답십리제1동)', '02', '3394', '9025', 11)
2021-08-18 17:40:59,011 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,012 INFO sqlalchemy.engine.base.Engine ('청암아이들세상어린이집', '신지혜', '서울특별시 노원구 덕릉로112길 24 ,관리동 1층 (상계동, 청암1단지아파트) (상계3.4동)', '02', '2091', '0336', 9)
2021-08-18 17:40:59,013 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,015 INFO sqlalchemy.engine.base.Engine ('푸른샘어린이집', '임유진', '서울특별시 성북구 장위로19길 35 (장위제1동)', '02', '909', '8558', 17)
2021-08-18 17:40:59,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,017 INFO sqlalchemy.engine.base.Engine ('하늘채어린이집', '오성수', '서울특별시 중랑구 용마산로 210 ,102동(면목동,용마산하늘채) (면목제4동)', '02', '491', '0901', 25)
2021-08-18 17:40:59,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,019 INFO sqlalchemy.engine.base.Engine ('해늘어린이집', '김상훈', '서울특별시 용산구 이촌로34길 29 ,이촌동, 현대한강아파트 관리동 (이촌제2동)', '02', '711', '7847', 21)
2021-08-18 17:40:59,020 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,021 INFO sqlalchemy.engine.base.Engine ('화랑어린이집', '이예준', '서울특별시 노원구 화랑로51길 17 ,관리동 1층 (공릉동, 화랑타운아파트) (공릉2동)', '02', '949', '1939', 9)
2021-08-18 17:40:59,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,024 INFO sqlalchemy.engine.base.Engine ('신한꿈나무어린이집', '조성진', '서울특별시 중구 을지로2가 삼일대로 358 ,신한L타워 3층 (명동)', '02', '6250', '8091', 24)
2021-08-18 17:40:59,025 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,026 INFO sqlalchemy.engine.base.Engine ('롯데중앙연구소 mom편한 어린이집', '장준호', '서울특별시 강서구 마곡중앙로 201 (가양제1동)', '02', '6309', '3148', 4)
2021-08-18 17:40:59,027 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,027 INFO sqlalchemy.engine.base.Engine ('구립 해맞이어린이집', '서영진', '서울특별시 은평구 갈현로15길 11-4 (구산동)', '02', '356', '6800', 22)
2021-08-18 17:40:59,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,031 INFO sqlalchemy.engine.base.Engine ('송파꿈꾸는어린이집', '임서현', '서울특별시 송파구 동남로 341 ,(오금동, 송파레미니스2단지) (오금동)', '02', '6953', '6366', 18)
2021-08-18 17:40:59,032 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,033 INFO sqlalchemy.engine.base.Engine ('구립 다래어린이집', '강민지', '서울특별시 은평구 응암로4길 5 (응암제3동)', '02', '302', '5800', 22)
2021-08-18 17:40:59,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,034 INFO sqlalchemy.engine.base.Engine ('참좋은어린이집', '장미영', '서울특별시 송파구 동남로 341 ,206동 103호(오금동, 송파레미니스2단지) (오금동)', '02', '402', '5955', 18)
2021-08-18 17:40:59,035 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,036 INFO sqlalchemy.engine.base.Engine ('구립로이어린이집', '장경자', '서울특별시 동작구 사당로23길 112 (사당제3동)', '02', '535', '5277', 12)
2021-08-18 17:40:59,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,040 INFO sqlalchemy.engine.base.Engine ('구립리가어린이집', '안정수', '서울특별시 동작구 사당로27길 130 ,105동 키즈클럽(사당동,이수역 리가아파트) (사당제3동)', '02', '536', '1292', 12)
2021-08-18 17:40:59,042 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,043 INFO sqlalchemy.engine.base.Engine ('구립아리아어린이집', '이정호', '서울특별시 동작구 보라매로5길 51 ,102호 (신대방제2동)', '02', '836', '9300', 12)
2021-08-18 17:40:59,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,046 INFO sqlalchemy.engine.base.Engine ('구립성내2동어린이집', '강준서', '서울특별시 강동구 성안로13길 21-14 ,(성내동) (성내제2동)', '02', '476', '0510', 2)
2021-08-18 17:40:59,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,048 INFO sqlalchemy.engine.base.Engine ('래미안어린이집', '한정운', '서울특별시 양천구 신목로 7 ,104동 106호(신정동, 목동삼성아파트) (신정2동)', '02', '6092', '8870', 19)
2021-08-18 17:40:59,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,050 INFO sqlalchemy.engine.base.Engine ('가락라온어린이집', '장성호', '서울특별시 송파구 송이로15길 31 ,가락2차쌍용아파트 102동 102호 (가락본동)', '02', '401', '6805', 18)
2021-08-18 17:40:59,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,052 INFO sqlalchemy.engine.base.Engine ('거여다온어린이집', '윤준서', '서울특별시 송파구 오금로56길 16 ,우방1차아파트 102동 101호 (거여1동)', '02', '415', '7036', 18)
2021-08-18 17:40:59,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,054 INFO sqlalchemy.engine.base.Engine ('구립열린어린이집', '오상훈', '서울특별시 동작구 동작대로29길 91 (사당제2동)', '02', '594', '8153', 12)
2021-08-18 17:40:59,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,057 INFO sqlalchemy.engine.base.Engine ('송이어린이집', '황예준', '서울특별시 송파구 송파대로36길 5-8 ,송파아파트 106호 (송파2동)', '02', '2202', '6113', 18)
2021-08-18 17:40:59,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,059 INFO sqlalchemy.engine.base.Engine ('이글아이영아어린이집', '박정식', '서울특별시 양천구 화곡로3길 27-8 ,101동 103호(신월동, 제일아파트) (신월5동)', '02', '2602', '2902', 19)
2021-08-18 17:40:59,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,061 INFO sqlalchemy.engine.base.Engine ('혜림어린이집', '오민석', '서울특별시 양천구 목동중앙북로7가길 24-6 (목3동)', '02', '2642', '8023', 19)
2021-08-18 17:40:59,062 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,062 INFO sqlalchemy.engine.base.Engine ('자연과아이어린이집', '오민서', '서울특별시 영등포구 당산동3가 양산로25길 12 (당산제1동)', '02', '2068', '2914', 20)
2021-08-18 17:40:59,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,064 INFO sqlalchemy.engine.base.Engine ('구립 백련산힐4차어린이집', '조영식', '서울특별시 은평구 백련산로 37 ,백련산힐스테이트4차아파트 407동 1층 (응암제2동)', '02', '307', '9622', 22)
2021-08-18 17:40:59,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,076 INFO sqlalchemy.engine.base.Engine ('구립참행복한어린이집', '강준호', '서울특별시 금천구 시흥대로 165 ,남서울힐스테이트아파트 212동 102호 (시흥제1동)', '02', '895', '2737', 8)
2021-08-18 17:40:59,077 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,078 INFO sqlalchemy.engine.base.Engine ('다해어린이집', '류은영', '서울특별시 마포구 상암산로1길 24 (상암동)', '02', '305', '6555', 13)
2021-08-18 17:40:59,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,080 INFO sqlalchemy.engine.base.Engine ('동아라온어린이집', '박지은', '서울특별시 성북구 장월로1길 28 ,단지내 1층 (월곡제2동)', '02', '6224', '7942', 17)
2021-08-18 17:40:59,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,082 INFO sqlalchemy.engine.base.Engine ('솔향기어린이집', '전성수', '서울특별시 동대문구 장한로26다길 77 (장안2동)', '02', '2213', '1095', 11)
2021-08-18 17:40:59,083 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,084 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '조준혁', '서울특별시 성북구 보국문로 116 ,, 단지내 1층(정릉동) (정릉제4동)', '02', '918', '4477', 17)
2021-08-18 17:40:59,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,087 INFO sqlalchemy.engine.base.Engine ('통통어린이집', '류지혜', '서울특별시 성북구 화랑로48길 16 (석관동)', '02', '965', '6619', 17)
2021-08-18 17:40:59,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,091 INFO sqlalchemy.engine.base.Engine ('파아란어린이집', '신정남', '서울특별시 성북구 솔샘로24길 15 ,, 단지내 1층(정릉동) (정릉제4동)', '02', '916', '7942', 17)
2021-08-18 17:40:59,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,093 INFO sqlalchemy.engine.base.Engine ('어울림어린이집', '최준서', '서울특별시 은평구 진관3로 15-45 ,1015동 1층 (진관동, 은평뉴타운 구파발) (진관동)', '02', '355', '9009', 22)
2021-08-18 17:40:59,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,095 INFO sqlalchemy.engine.base.Engine ('구립 거북마을어린이집', '박병철', '서울특별시 은평구 서오릉로15길 7-1 (구산동)', '02', '352', '1170', 22)
2021-08-18 17:40:59,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,096 INFO sqlalchemy.engine.base.Engine ('구립 꽃가람어린이집', '황지민', '서울특별시 은평구 은평로21길 36-3 ,102-101 (녹번동)', '02', '382', '6130', 22)
2021-08-18 17:40:59,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,098 INFO sqlalchemy.engine.base.Engine ('구립 아롱별어린이집', '이영길', '서울특별시 은평구 통일로69길 12-10 (대조동)', '02', '383', '2220', 22)
2021-08-18 17:40:59,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,100 INFO sqlalchemy.engine.base.Engine ('거성어린이집', '안정순', '서울특별시 영등포구 양평동3가 선유로43가길 24 ,관리동 1층 (양평제2동)', '02', '2672', '9681', 20)
2021-08-18 17:40:59,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,101 INFO sqlalchemy.engine.base.Engine ('구립 키즈빌리지어린이집', '강종수', '서울특별시 은평구 진관4로 17 ,상림마을 812동 1층 (진관동)', '02', '355', '0608', 22)
2021-08-18 17:40:59,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,104 INFO sqlalchemy.engine.base.Engine ('모아미래도어린이집', '박민수', '서울특별시 영등포구 문래동5가 선유로9나길 5 ,관리동 1층 (문래동)', '02', '2637', '2335', 20)
2021-08-18 17:40:59,105 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,106 INFO sqlalchemy.engine.base.Engine ('현대홈키즈어린이집', '송지민', '서울특별시 강동구 올림픽로70길 34 ,현대홈쇼핑 1층, 현대홈키즈어린이집 (천호제2동)', '02', '484', '0508', 2)
2021-08-18 17:40:59,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,115 INFO sqlalchemy.engine.base.Engine ('작은별어린이집', '장준호', '서울특별시 용산구 효창원로93길 12 ,1층 (효창동)', '02', '6367', '0707', 21)
2021-08-18 17:40:59,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,120 INFO sqlalchemy.engine.base.Engine ('삼일어린이집', '송영환', '서울특별시 용산구 한강로2가 한강대로 95 ,래미안용산더센트럴 410호 (한강로동)', '02', '794', '8831', 21)
2021-08-18 17:40:59,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,122 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '강지훈', '서울특별시 중구 만리동2가 만리재로21길 9 (중림동)', '02', '2088', '1318', 24)
2021-08-18 17:40:59,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,124 INFO sqlalchemy.engine.base.Engine ('마곡어린이집', '서성호', '서울특별시 강서구 마곡중앙1로 71 ,1308동 102호(마곡동,마곡13단지힐스테이트마스터) (공항동)', '02', '2665', '6777', 4)
2021-08-18 17:40:59,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,126 INFO sqlalchemy.engine.base.Engine ('가락예은어린이집', '윤정호', '서울특별시 송파구 송파대로32길 8 ,6동 101호(가락동, 우성아파트) (가락본동)', '02', '6479', '1273', 18)
2021-08-18 17:40:59,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,129 INFO sqlalchemy.engine.base.Engine ('방이두리어린이집', '장정자', '서울특별시 송파구 오금로23길 9-17 ,1층 2호(방이동) (방이2동)', '02', '422', '1363', 18)
2021-08-18 17:40:59,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,131 INFO sqlalchemy.engine.base.Engine ('석촌사랑어린이집', '안민서', '서울특별시 송파구 백제고분로33길 32-14 ,102호(석촌동, 호수맨션) (석촌동)', '02', '419', '9134', 18)
2021-08-18 17:40:59,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,133 INFO sqlalchemy.engine.base.Engine ('가온어린이집', '오서연', '서울특별시 동대문구 천호대로89길 30 ,101동 109호(장안동,은하수드림필아파트) (장안제1동)', '02', '2215', '3342', 11)
2021-08-18 17:40:59,134 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,134 INFO sqlalchemy.engine.base.Engine ('솔솔어린이집', '장민재', '서울특별시 동대문구 장안벚꽃로5길 19 ,2층(휘경동) (휘경제2동)', '02', '2249', '4924', 11)
2021-08-18 17:40:59,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,136 INFO sqlalchemy.engine.base.Engine ('한국교직원공제회어린이집', '송정순', '서울특별시 영등포구 여의나루로 50 ,한국교직원공제회관 2층 (여의동)', '02', '786', '1508', 20)
2021-08-18 17:40:59,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,138 INFO sqlalchemy.engine.base.Engine ('삼성물산강동어린이집', '오성진', '서울특별시 강동구 상일로6길 26 ,글로벌엔지니어링센터 B동 2층 (상일제2동)', '02', '481', '9961', 2)
2021-08-18 17:40:59,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,140 INFO sqlalchemy.engine.base.Engine ('KB합정어린이집', '전정남', '서울특별시 마포구 포은로2가길 59 (합정동)', '02', '337', '8102', 13)
2021-08-18 17:40:59,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,143 INFO sqlalchemy.engine.base.Engine ('사랑꿈어린이집', '장정식', '서울특별시 용산구 원효로 216 ,관리동 1층 (원효로제1동)', '070', '7767', '6300', 21)
2021-08-18 17:40:59,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,145 INFO sqlalchemy.engine.base.Engine ('구립우솔어린이집', '임정웅', '서울특별시 금천구 금하로 816 ,벽산아파트 518-101 (시흥제2동)', '02', '805', '9707', 8)
2021-08-18 17:40:59,146 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,147 INFO sqlalchemy.engine.base.Engine ('구립다온어린이집', '최영숙', '서울특별시 강북구 삼양로19길 25 ,103동 104호(미아동, 래미안트라베라1단지아파트) (삼각산동)', '02', '988', '1717', 3)
2021-08-18 17:40:59,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,150 INFO sqlalchemy.engine.base.Engine ('오뚜기 어린이집', '안동현', '서울특별시 강남구 영동대로 308 ,2층 (대치2동)', '02', '2010', '0200', 1)
2021-08-18 17:40:59,152 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,155 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '박지훈', '서울특별시 용산구 후암로 4-8 ,후암동 (후암동)', '02', '2213', '2929', 21)
2021-08-18 17:40:59,157 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,160 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '황민지', '서울특별시 서대문구 통일로 510 ,106-101 (홍은제1동)', '02', '395', '3232', 14)
2021-08-18 17:40:59,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,162 INFO sqlalchemy.engine.base.Engine ('다사랑어린이집', '정현준', '서울특별시 송파구 양산로8길 24 ,211동 102호(거여동,거여2단지) (거여2동)', '02', '431', '6667', 18)
2021-08-18 17:40:59,163 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,164 INFO sqlalchemy.engine.base.Engine ('큰솔어린이집', '권준혁', '서울특별시 송파구 송이로 88 ,5동 107호(가락동,대림아파트) (가락본동)', '02', '430', '7942', 18)
2021-08-18 17:40:59,166 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,166 INFO sqlalchemy.engine.base.Engine ('SK키즈몬테소리어린이집', '정지혜', '서울특별시 성북구 삼선동3가 삼선교로16길 35 ,, 관리동 1층 (삼선동)', '02', '461', '3510', 17)
2021-08-18 17:40:59,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,168 INFO sqlalchemy.engine.base.Engine ('구립 건대티움아이어린이집', '황현정', '서울특별시 광진구 능동로4길 41 ,701동 101호(자양동, 자양7차현대홈타운) (자양제3동)', '02', '499', '1279', 6)
2021-08-18 17:40:59,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,169 INFO sqlalchemy.engine.base.Engine ('구립 모아어린이집', '강정웅', '서울특별시 강서구 방화대로45길 78 ,101동 103호(방화동, 보람쉬움아파트) (방화제1동)', '02', '2661', '8767', 4)
2021-08-18 17:40:59,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,171 INFO sqlalchemy.engine.base.Engine ('구립 파란나라어린이집', '안지영', '서울특별시 양천구 신정로 290 (신정3동)', '02', '2065', '8727', 19)
2021-08-18 17:40:59,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,173 INFO sqlalchemy.engine.base.Engine ('구립 하나로어린이집', '김준호', '서울특별시 강서구 양천로73길 5 ,101동 105호 (염창동)', '02', '2652', '5946', 4)
2021-08-18 17:40:59,174 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,175 INFO sqlalchemy.engine.base.Engine ('구립 한숲어린이집', '서수빈', '서울특별시 강서구 방화대로50길 7 ,101동 102호(방화동 한숲마을대림아파트) (방화제3동)', '02', '6348', '7942', 4)
2021-08-18 17:40:59,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,177 INFO sqlalchemy.engine.base.Engine ('구립꿈의숲캐슬어린이집', '신준호', '서울특별시 강북구 오현로 56 ,관리동 1층(미아동, 꿈의숲롯데캐슬아파트) (송중동)', '02', '980', '7750', 3)
2021-08-18 17:40:59,177 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,178 INFO sqlalchemy.engine.base.Engine ('구립롯데금빛어린이집', '전준혁', '서울특별시 금천구 벚꽃로 40 ,롯데캐슬골드파크1차아파트 내 (독산제1동)', '02', '809', '7942', 8)
2021-08-18 17:40:59,179 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,179 INFO sqlalchemy.engine.base.Engine ('구립예능어린이집', '이은정', '서울특별시 강북구 솔샘로 159 ,벽산라이브파크아파트 관리동 1층 (삼양동)', '02', '982', '8733', 3)
2021-08-18 17:40:59,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,182 INFO sqlalchemy.engine.base.Engine ('구립우리어린이집', '신정운', '서울특별시 금천구 범안로 1136 ,구립우리어린이집 (독산제1동)', '02', '869', '7273', 8)
2021-08-18 17:40:59,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,184 INFO sqlalchemy.engine.base.Engine ('구립유쉘어린이집', '김준서', '서울특별시 금천구 금하로 750 ,우방아파트 단지내 구립유쉘어린이집 (시흥제2동)', '02', '804', '2007', 8)
2021-08-18 17:40:59,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,186 INFO sqlalchemy.engine.base.Engine ('구립키즈사랑어린이집', '권유진', '서울특별시 동작구 알마타길 37 ,관리동 1층 (대방동)', '02', '3280', '0377', 12)
2021-08-18 17:40:59,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,188 INFO sqlalchemy.engine.base.Engine ('꿈의숲어린이집', '장준서', '서울특별시 성북구 오패산로16가길 40 ,, 관리동 1층 (월곡제1동)', '02', '942', '9155', 17)
2021-08-18 17:40:59,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,191 INFO sqlalchemy.engine.base.Engine ('능동주민센터어린이집', '한서연', '서울특별시 광진구 천호대로112길 55 ,능동주민센터 1층(능동 232-4) (능동)', '02', '452', '1006', 6)
2021-08-18 17:40:59,192 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,194 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '조정호', '서울특별시 서대문구 문화촌길 6-24 ,102동 107호(홍제동, 문화촌현대아파트) (홍제제3동)', '02', '6082', '9972', 14)
2021-08-18 17:40:59,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,196 INFO sqlalchemy.engine.base.Engine ('다함어린이집', '조준혁', '서울특별시 동대문구 사가정로 65 ,(전농동, 래미안크레시티아파트) (전농제1동)', '02', '2249', '9636', 11)
2021-08-18 17:40:59,198 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,199 INFO sqlalchemy.engine.base.Engine ('도담도담어린이집', '권예준', '서울특별시 종로구 숭인동길 47 (숭인제2동)', '02', '921', '4500', 23)
2021-08-18 17:40:59,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,201 INFO sqlalchemy.engine.base.Engine ('돈암하늘채어린이집', '한준호', '서울특별시 성북구 아리랑로 75 ,관리동 1층 (돈암제2동)', '02', '924', '7007', 17)
2021-08-18 17:40:59,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,204 INFO sqlalchemy.engine.base.Engine ('동화속아이들어린이집', '박경자', '서울특별시 종로구 통일로 246-11 ,무악현대아파트 단지내 (무악동)', '02', '733', '2440', 23)
2021-08-18 17:40:59,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,207 INFO sqlalchemy.engine.base.Engine ('두산어린이집', '한경회', '서울특별시 구로구 도림로 59 ,105동 102호(구로동,구로두산아파트) (구로제4동)', '02', '6735', '9267', 7)
2021-08-18 17:40:59,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,209 INFO sqlalchemy.engine.base.Engine ('두산영재어린이집', '임서현', '서울특별시 노원구 공릉로 126 ,두산힐스빌아파트 관리동 (공릉2동)', '02', '948', '6816', 9)
2021-08-18 17:40:59,210 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,210 INFO sqlalchemy.engine.base.Engine ('래미안숲어린이집', '강영일', '서울특별시 성북구 화랑로 214 ,, 관리동 1층(석관동) (석관동)', '02', '966', '1466', 17)
2021-08-18 17:40:59,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,212 INFO sqlalchemy.engine.base.Engine ('롯데캐슬어린이집', '안민지', '서울특별시 중구 청계천로 400 ,롯데캐슬베네치아아파트 103동7층관리동 (황학동) (황학동)', '02', '2048', '5757', 24)
2021-08-18 17:40:59,213 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,215 INFO sqlalchemy.engine.base.Engine ('마곡1 고운비어린이집', '김정순', '서울특별시 강서구 마곡서1로 131 ,101동 115호(마곡동, 엠벨리1단지아파트) (방화제1동)', '02', '2666', '2004', 4)
2021-08-18 17:40:59,215 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,216 INFO sqlalchemy.engine.base.Engine ('방학3동꿈송이어린이집', '황수빈', '서울특별시 도봉구 방학로 200 ,115동110호(방학동,신동아아파트) (방학제3동)', '02', '955', '1209', 10)
2021-08-18 17:40:59,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,218 INFO sqlalchemy.engine.base.Engine ('블루밍서연어린이집', '강예은', '서울특별시 구로구 고척로60길 30 ,고척벽산베스트블루밍 아파트 관리동 1층 (고척제2동)', '02', '2686', '4333', 7)
2021-08-18 17:40:59,219 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,222 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '김성진', '서울특별시 구로구 개봉로20길 158 ,204동 102호 (개봉제2동)', '02', '2066', '2564', 7)
2021-08-18 17:40:59,223 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,224 INFO sqlalchemy.engine.base.Engine ('사랑별어린이집', '권준영', '서울특별시 구로구 구로동로8길 30-1 (구로제4동)', '02', '858', '8010', 7)
2021-08-18 17:40:59,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,225 INFO sqlalchemy.engine.base.Engine ('사슴어린이집', '한민석', '서울특별시 노원구 월계로55길 15 ,사슴3단지아파트 관리동 (월계3동)', '02', '979', '1262', 9)
2021-08-18 17:40:59,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,227 INFO sqlalchemy.engine.base.Engine ('삼선예일어린이집', '권정호', '서울특별시 성북구 보문로29다길 31 ,, 관리동 1층 (삼선동)', '02', '742', '6371', 17)
2021-08-18 17:40:59,227 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,228 INFO sqlalchemy.engine.base.Engine ('새한어린이집', '조미영', '서울특별시 중랑구 용마산로 616 ,관리동 1층 (신내1동)', '02', '3421', '7900', 25)
2021-08-18 17:40:59,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,231 INFO sqlalchemy.engine.base.Engine ('서봄어린이집', '안영진', '서울특별시 관악구 신림로44나길 18 ,1층 (서원동)', '02', '882', '3351', 5)
2021-08-18 17:40:59,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,232 INFO sqlalchemy.engine.base.Engine ('서울시립대학교직장어린이집', '권정남', '서울특별시 동대문구 서울시립대로 163 ,서울시립대학교직장어린이집 (전농제2동)', '02', '2213', '9566', 11)
2021-08-18 17:40:59,233 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,238 INFO sqlalchemy.engine.base.Engine ('쌍문4동리틀모아어린이집', '오서현', '서울특별시 도봉구 해등로 242-12 ,103동 102호(쌍문동) (쌍문제4동)', '02', '991', '6174', 10)
2021-08-18 17:40:59,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,240 INFO sqlalchemy.engine.base.Engine ('쌍문4동아이천국어린이집', '황영진', '서울특별시 도봉구 해등로 229 ,3동 109호(쌍문동, 한양아파트) (쌍문제4동)', '02', '900', '4245', 10)
2021-08-18 17:40:59,242 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,243 INFO sqlalchemy.engine.base.Engine ('쌍문4동파란꿈나라어린이집', '황정자', '서울특별시 도봉구 해등로 242-11 ,101동 103호(쌍문동,성원아파트) (쌍문제4동)', '02', '6225', '6919', 10)
2021-08-18 17:40:59,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,245 INFO sqlalchemy.engine.base.Engine ('아미어린이집', '전은경', '서울특별시 중랑구 봉화산로56길 112 ,101동 102호 (신내1동)', '02', '436', '3859', 25)
2021-08-18 17:40:59,247 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,248 INFO sqlalchemy.engine.base.Engine ('아이누리어린이집', '한영환', '서울특별시 중랑구 동일로 752 ,107-102 (중화제1동)', '02', '433', '1642', 25)
2021-08-18 17:40:59,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,252 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '신예은', '서울특별시 노원구 동일로231길 86 ,204동 108호(상계동, 현대2차아파트) (상계1동)', '02', '3391', '5927', 9)
2021-08-18 17:40:59,253 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,253 INFO sqlalchemy.engine.base.Engine ('아이조아어린이집', '박종수', '서울특별시 송파구 백제고분로46길 8-23 ,101호(송파동, 온누리아파트) (송파1동)', '02', '415', '5672', 18)
2021-08-18 17:40:59,255 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,255 INFO sqlalchemy.engine.base.Engine ('알콩달콩어린이집', '강준혁', '서울특별시 중랑구 신내로 155 ,808동 109호 (신내2동)', '02', '3423', '3577', 25)
2021-08-18 17:40:59,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,257 INFO sqlalchemy.engine.base.Engine ('엘프어린이집', '서현준', '서울특별시 마포구 상암산로1길 52 ,상암월드컵파크5단지 505동 1층 (상암동)', '02', '373', '3654', 13)
2021-08-18 17:40:59,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,259 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '조은경', '서울특별시 마포구 월드컵북로47길 46 ,상암월드컵파크2단지 202동 1층 (상암동)', '02', '306', '1600', 13)
2021-08-18 17:40:59,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,261 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '임건우', '서울특별시 노원구 동일로198가길 149 ,공릉2단지아파트 관리동 (공릉1동)', '02', '972', '9207', 9)
2021-08-18 17:40:59,263 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,265 INFO sqlalchemy.engine.base.Engine ('우애들어린이집', '한동현', '서울특별시 마포구 독막로20나길 22 ,래미안밤섬리베뉴1 관리동 (서강동)', '02', '333', '1003', 13)
2021-08-18 17:40:59,266 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,267 INFO sqlalchemy.engine.base.Engine ('우주별어린이집', '이영자', '서울특별시 노원구 공릉로46길 19 ,관리동 1층 (공릉2동)', '02', '948', '2074', 9)
2021-08-18 17:40:59,267 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,268 INFO sqlalchemy.engine.base.Engine ('위브어린이집', '서민지', '서울특별시 동대문구 황물로15길 25 ,(답십리동,두산위브아파트) (답십리제2동)', '02', '2212', '9919', 11)
2021-08-18 17:40:59,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,271 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '강성호', '서울특별시 노원구 동일로245가길 41 ,은빛2단지아파트 관리동 (상계1동)', '02', '934', '3006', 9)
2021-08-18 17:40:59,272 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,272 INFO sqlalchemy.engine.base.Engine ('이노키즈어린이집', '신영길', '서울특별시 서초구 서초중앙로8길 47 (서초1동)', '02', '581', '5345', 15)
2021-08-18 17:40:59,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,273 INFO sqlalchemy.engine.base.Engine ('이문현대어린이집', '서예은', '서울특별시 동대문구 한천로58길 107 ,(이문동, 현대아파트) (이문제2동)', '02', '959', '1153', 11)
2021-08-18 17:40:59,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,276 INFO sqlalchemy.engine.base.Engine ('이편한오렌지어린이집', '이광수', '서울특별시 동대문구 한천로63길 10 (이문제2동)', '02', '966', '0906', 11)
2021-08-18 17:40:59,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,278 INFO sqlalchemy.engine.base.Engine ('이화우성어린이집', '장성민', '서울특별시 구로구 도림로22길 8 ,101동 110호 (구로제3동)', '02', '859', '5152', 7)
2021-08-18 17:40:59,279 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,279 INFO sqlalchemy.engine.base.Engine ('인왕어린이집', '강성진', '서울특별시 서대문구 문화촌길 34 ,홍제동 (홍제제3동)', '02', '394', '6753', 14)
2021-08-18 17:40:59,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,281 INFO sqlalchemy.engine.base.Engine ('인정어린이집', '강영길', '서울특별시 광진구 동일로 242 ,(군자동) (군자동)', '02', '462', '2758', 6)
2021-08-18 17:40:59,282 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,283 INFO sqlalchemy.engine.base.Engine ('작은숲어린이집', '박정자', '서울특별시 서대문구 포방터10길 33 ,극동아파트 106동 103호 (홍은제1동)', '02', '6378', '7780', 14)
2021-08-18 17:40:59,284 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,284 INFO sqlalchemy.engine.base.Engine ('주영어린이집', '김미숙', '서울특별시 노원구 한글비석로5길 62 ,중계8단지주공아파트 관리동 (중계1동)', '02', '930', '8787', 9)
2021-08-18 17:40:59,286 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,286 INFO sqlalchemy.engine.base.Engine ('창1동뽀뽀뽀24시어린이집', '권성호', '서울특별시 도봉구 해등로 50 ,323동 104호 (창동, 주공3단지아파트) (창제1동)', '02', '998', '6033', 10)
2021-08-18 17:40:59,287 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,288 INFO sqlalchemy.engine.base.Engine ('창1동즐거운어린이집', '장현정', '서울특별시 도봉구 덕릉로 371 ,(창동,대우그린아파트) (창제1동)', '02', '998', '2689', 10)
2021-08-18 17:40:59,290 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,290 INFO sqlalchemy.engine.base.Engine ('창4동별초롱어린이집', '송유진', '서울특별시 도봉구 노해로70길 12 ,6동 106호(창동) (창제4동)', '02', '6316', '5050', 10)
2021-08-18 17:40:59,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,292 INFO sqlalchemy.engine.base.Engine ('창4동예나동산어린이집', '서정남', '서울특별시 도봉구 노해로69길 103 ,109동101호(창동,동아청솔아파트) (창제4동)', '02', '6231', '2555', 10)
2021-08-18 17:40:59,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,294 INFO sqlalchemy.engine.base.Engine ('파란나라어린이집', '서진호', '서울특별시 노원구 덕릉로94가길 20 ,청암2단지아파트 (상계3.4동)', '02', '951', '5854', 9)
2021-08-18 17:40:59,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,296 INFO sqlalchemy.engine.base.Engine ('파란나라어린이집', '권은경', '서울특별시 구로구 중앙로1길 18-19 ,103동 105호 (고척제1동)', '02', '2619', '4501', 7)
2021-08-18 17:40:59,297 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,298 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '정서연', '서울특별시 동대문구 장안벚꽃로 107 ,108동 102호(장안동, 현대홈타운아파트) (장안제1동)', '02', '2243', '3935', 11)
2021-08-18 17:40:59,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,299 INFO sqlalchemy.engine.base.Engine ('하계현대어린이집', '오준혁', '서울특별시 노원구 노원로18길 19 ,하계2차현대아파트 (하계1동)', '02', '948', '7386', 9)
2021-08-18 17:40:59,300 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,301 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '장지은', '서울특별시 구로구 개봉로20길 6 ,124동 104호 (개봉제2동)', '02', '2066', '7749', 7)
2021-08-18 17:40:59,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,302 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '장영진', '서울특별시 동대문구 한천로 248 ,(휘경동, 휘경주공아파트) (휘경제2동)', '02', '6452', '7942', 11)
2021-08-18 17:40:59,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,304 INFO sqlalchemy.engine.base.Engine ('해피래미안어린이집', '임정운', '서울특별시 성북구 길음로 74 ,, 관리동 1층 (길음제1동)', '02', '914', '7979', 17)
2021-08-18 17:40:59,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,307 INFO sqlalchemy.engine.base.Engine ('허브리츠어린이집', '조지은', '서울특별시 동대문구 정릉천동로 36 ,(용두동,허브리츠) 관리동 (용신동)', '02', '965', '0121', 11)
2021-08-18 17:40:59,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,309 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '류서연', '서울특별시 성북구 종암로21길 127 ,, 관리동 1층 (종암동)', '02', '925', '9777', 17)
2021-08-18 17:40:59,310 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,312 INFO sqlalchemy.engine.base.Engine ('휴먼빌어린이집', '김정식', '서울특별시 성북구 아리랑로 89 ,, 관리동 1층 (돈암동) (돈암제2동)', '02', '928', '5240', 17)
2021-08-18 17:40:59,313 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,314 INFO sqlalchemy.engine.base.Engine ('사이언스파크어린이집', '최준호', '서울특별시 강서구 마곡중앙10로 30 (가양제1동)', '02', '6941', '0302', 4)
2021-08-18 17:40:59,315 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,316 INFO sqlalchemy.engine.base.Engine ('삼양어린이집', '오준혁', '서울특별시 종로구 종로33길 31 (종로5·6가동)', '02', '760', '5081', 23)
2021-08-18 17:40:59,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,318 INFO sqlalchemy.engine.base.Engine ('에스앤아이 강서어린이집', '한정순', '서울특별시 강서구 마곡중앙로 150 ,2층 (가양제1동)', '02', '2088', '2021', 4)
2021-08-18 17:40:59,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,320 INFO sqlalchemy.engine.base.Engine ('GKL행복(강남 코엑스2호점)어린이집', '전미경', '서울특별시 강남구 봉은사로68길 27 (삼성2동)', '02', '501', '3385', 1)
2021-08-18 17:40:59,322 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,322 INFO sqlalchemy.engine.base.Engine ('LG마포어린이집', '장지훈', '서울특별시 마포구 마포대로 155 ,마포빌딩 3층 (아현동)', '02', '2039', '7716', 13)
2021-08-18 17:40:59,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,325 INFO sqlalchemy.engine.base.Engine ('구립 아이클어린이집', '박성수', '서울특별시 은평구 진관1로 21-10 ,(진관동, 박석고개 1단지아파트) 주민공동시설 중 어린이집 (진관동)', '02', '355', '3558', 22)
2021-08-18 17:40:59,325 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,326 INFO sqlalchemy.engine.base.Engine ('마곡코오롱어린이집', '서정식', '서울특별시 강서구 마곡동로 110 ,1층 (마곡동, 코오롱미래기술원) (가양제1동)', '02', '2199', '1990', 4)
2021-08-18 17:40:59,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,327 INFO sqlalchemy.engine.base.Engine ('잘자람어린이집', '장영식', '서울특별시 강서구 방화대로37길 26 ,방화현대아파트101-102 (방화제1동)', '02', '2662', '6660', 4)
2021-08-18 17:40:59,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,329 INFO sqlalchemy.engine.base.Engine ('구립성내푸른어린이집', '류준호', '서울특별시 강동구 성내로3길 49 ,(성내동) (성내제1동)', '02', '470', '1113', 2)
2021-08-18 17:40:59,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,331 INFO sqlalchemy.engine.base.Engine ('구립조앤아이어린이집', '이지원', '서울특별시 관악구 관악로30길 12 ,봉천우성아파트 103-101 (행운동)', '02', '883', '0312', 5)
2021-08-18 17:40:59,332 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,332 INFO sqlalchemy.engine.base.Engine ('구립즐거운어린이집', '강준호', '서울특별시 관악구 양녕로 31 ,두산아파트 3단지 관리동 (은천동)', '02', '3285', '1998', 5)
2021-08-18 17:40:59,334 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,334 INFO sqlalchemy.engine.base.Engine ('구립찬솔어린이집', '신영숙', '서울특별시 관악구 법원단지12길 24 (난곡동)', '02', '853', '0330', 5)
2021-08-18 17:40:59,337 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,339 INFO sqlalchemy.engine.base.Engine ('서초구립 아르떼어린이집', '안준호', '서울특별시 서초구 방배천로18길 11 ,관리동(방배동, 방배롯데캐슬아르떼) (방배2동)', '02', '521', '5689', 15)
2021-08-18 17:40:59,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,341 INFO sqlalchemy.engine.base.Engine ('사이좋은 어린이집', '박미경', '서울특별시 중랑구 숙선옹주로 45 ,112동 102호(묵동,e-편한세상화랑대) (묵제1동)', '02', '3421', '1007', 25)
2021-08-18 17:40:59,342 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,343 INFO sqlalchemy.engine.base.Engine ('경희궁솔빛어린이집', '안유진', '서울특별시 종로구 송월길 99 ,210동 1층 (교남동)', '02', '732', '8003', 23)
2021-08-18 17:40:59,344 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,345 INFO sqlalchemy.engine.base.Engine ('구립 응암봄샘어린이집', '신지영', '서울특별시 은평구 백련산로 160 ,(응암동, 녹번역센트레빌아파트) 주민공동시설 중 어린이집 (응암제1동)', '02', '387', '2977', 22)
2021-08-18 17:40:59,346 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,347 INFO sqlalchemy.engine.base.Engine ('구립 맑은샘어린이집', '강상철', '서울특별시 성동구 매봉길 51 ,(옥수동 528-2) (옥수동)', '02', '2293', '0509', 16)
2021-08-18 17:40:59,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,350 INFO sqlalchemy.engine.base.Engine ('경희궁자이어린이집', '조영자', '서울특별시 종로구 경교장길 35 ,306동 데크층 (교남동)', '02', '720', '1633', 23)
2021-08-18 17:40:59,351 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,353 INFO sqlalchemy.engine.base.Engine ('경희궁초록어린이집', '서준서', '서울특별시 종로구 송월길 130 ,102동 1층 (교남동)', '070', '4024', '1499', 23)
2021-08-18 17:40:59,353 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,354 INFO sqlalchemy.engine.base.Engine ('구립천호1동어린이집', '서종수', '서울특별시 강동구 상암로27길 18 (천호제1동)', '02', '429', '3337', 2)
2021-08-18 17:40:59,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,357 INFO sqlalchemy.engine.base.Engine ('아너스빌어린이집', '전준호', '서울특별시 영등포구 여의대방로 25 ,경남아너스빌아파트 관리동 (신길제6동)', '02', '849', '4279', 20)
2021-08-18 17:40:59,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,359 INFO sqlalchemy.engine.base.Engine ('헤아림어린이집', '강혜진', '서울특별시 서대문구 북아현로1길 50 (북아현동)', '02', '313', '6702', 14)
2021-08-18 17:40:59,360 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,361 INFO sqlalchemy.engine.base.Engine ('구립 해솔어린이집', '권정수', '서울특별시 은평구 진관4로 87 ,(진관동, 은평뉴타운 상림마을 5단지 아파트) 주민공동시설 중 어린이집 (진관동)', '02', '352', '1331', 22)
2021-08-18 17:40:59,362 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,364 INFO sqlalchemy.engine.base.Engine ('구립 서울숲리버뷰자이어린이집', '강상훈', '서울특별시 성동구 고산자로2길 65 ,행당동 100번지일대(행당6구역) (행당제1동)', '02', '2293', '7770', 16)
2021-08-18 17:40:59,365 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,365 INFO sqlalchemy.engine.base.Engine ('구립 예가어린이집', '전혜진', '서울특별시 은평구 진관4로 37 ,은평뉴타운 상림마을2단지아파트 관리동 (진관동)', '02', '387', '2656', 22)
2021-08-18 17:40:59,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,367 INFO sqlalchemy.engine.base.Engine ('구립리틀버드어린이집', '신혜진', '서울특별시 강북구 삼양로93길 11-4 (인수동)', '02', '900', '9284', 3)
2021-08-18 17:40:59,368 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,368 INFO sqlalchemy.engine.base.Engine ('구립 행복한우리어린이집', '서정자', '서울특별시 은평구 응암로22길 18-1 (응암제2동)', '02', '352', '1566', 22)
2021-08-18 17:40:59,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,370 INFO sqlalchemy.engine.base.Engine ('서초구립 양재목련어린이집', '송정순', '서울특별시 서초구 언남16길 37 (양재2동)', '02', '529', '3579', 15)
2021-08-18 17:40:59,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,373 INFO sqlalchemy.engine.base.Engine ('프라임어린이집', '이준혁', '서울특별시 은평구 진관4로 100 ,609동 1층 (진관동, 은평뉴타운 상림마을) (진관동)', '02', '351', '4263', 22)
2021-08-18 17:40:59,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,376 INFO sqlalchemy.engine.base.Engine ('서초구립 방배1동초록꿈어린이집', '정영숙', '서울특별시 서초구 효령로23길 16 (방배1동)', '02', '3486', '2019', 15)
2021-08-18 17:40:59,378 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,379 INFO sqlalchemy.engine.base.Engine ('서초구립 양재별하어린이집', '신성호', '서울특별시 서초구 논현로5길 15-5 (양재2동)', '02', '533', '4503', 15)
2021-08-18 17:40:59,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,383 INFO sqlalchemy.engine.base.Engine ('창의나라어린이집', '류광수', '서울특별시 영등포구 여의대방로47길 24-2 (신길제1동)', '02', '844', '3234', 20)
2021-08-18 17:40:59,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,385 INFO sqlalchemy.engine.base.Engine ('서초구립 서울교육대학교사향어린이집', '장준호', '서울특별시 서초구 서초중앙로 96 ,서울교육대학교 평생교육원 1층 (서초1동)', '02', '583', '6688', 15)
2021-08-18 17:40:59,387 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,388 INFO sqlalchemy.engine.base.Engine ('서초구립 래미안서초에스티지S어린이집', '서은영', '서울특별시 서초구 서운로 104 (서초2동)', '02', '525', '2018', 15)
2021-08-18 17:40:59,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,391 INFO sqlalchemy.engine.base.Engine ('드림타운어린이집', '조성호', '서울특별시 영등포구 도신로29길 28 ,대우푸르지오 1단지 (영등포본동)', '02', '6746', '1004', 20)
2021-08-18 17:40:59,392 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,396 INFO sqlalchemy.engine.base.Engine ('선유어린이집', '류민재', '서울특별시 영등포구 양평동3가 선유로 207 (양평제2동)', '02', '2676', '7111', 20)
2021-08-18 17:40:59,400 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,401 INFO sqlalchemy.engine.base.Engine ('신길삼성어린이집', '권준호', '서울특별시 영등포구 가마산로79길 7 ,삼성래미안아파트 관리동 (신길제4동)', '02', '841', '8386', 20)
2021-08-18 17:40:59,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,403 INFO sqlalchemy.engine.base.Engine ('아르미어린이집', '조영일', '서울특별시 영등포구 당산동5가 당산로 214 (당산제2동)', '02', '2068', '5515', 20)
2021-08-18 17:40:59,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,404 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '전종수', '서울특별시 영등포구 도신로29길 28 ,대우푸르지오 2단지내 (영등포본동)', '02', '847', '2243', 20)
2021-08-18 17:40:59,405 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,406 INFO sqlalchemy.engine.base.Engine ('푸르지오어린이집', '안지영', '서울특별시 영등포구 영등포동8가 영중로 154 ,당산푸르지오아파트 관리동 (영등포동)', '02', '2677', '3927', 20)
2021-08-18 17:40:59,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,408 INFO sqlalchemy.engine.base.Engine ('구립슬비어린이집', '권성진', '서울특별시 강북구 오패산로38길 6-15 (송중동)', '02', '980', '1248', 3)
2021-08-18 17:40:59,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,410 INFO sqlalchemy.engine.base.Engine ('구립아이원어린이집', '조정운', '서울특별시 강북구 삼양로19길 113 ,102동 102호(미아동1357, 삼각산아이원아파트) (삼각산동)', '02', '6086', '7700', 3)
2021-08-18 17:40:59,411 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,412 INFO sqlalchemy.engine.base.Engine ('삼전초록어린이집', '류정운', '서울특별시 송파구 백제고분로32길 6-76 ,(삼전동) (삼전동)', '02', '422', '8931', 18)
2021-08-18 17:40:59,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,414 INFO sqlalchemy.engine.base.Engine ('송파레미니스어린이집', '임정수', '서울특별시 송파구 성내천로 6 ,1단지(오금동, 송파레미니스) (오금동)', '02', '6713', '6714', 18)
2021-08-18 17:40:59,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,416 INFO sqlalchemy.engine.base.Engine ('구립성내1동어린이집', '조민수', '서울특별시 강동구 풍성로 127 ,관리동(성내동, 성내삼성아파트) (성내제1동)', '02', '478', '0010', 2)
2021-08-18 17:40:59,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,418 INFO sqlalchemy.engine.base.Engine ('구립 트리마제어린이집', '장미경', '서울특별시 성동구 성수동1가 왕십리로 16 ,관리동 (성수동1가, 트리마제) (성수1가제1동)', '02', '465', '7717', 16)
2021-08-18 17:40:59,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,420 INFO sqlalchemy.engine.base.Engine ('구립고덕숲어린이집', '오성호', '서울특별시 강동구 고덕로80길 134 ,107동 1층(상일동, 고덕숲아이파크아파트) (상일제1동)', '02', '442', '2323', 2)
2021-08-18 17:40:59,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,422 INFO sqlalchemy.engine.base.Engine ('구립도토리어린이집', '강상훈', '서울특별시 강동구 고덕로97길 20 ,강일동, 강일리버파크10단지아파트 (강일동)', '02', '428', '3944', 2)
2021-08-18 17:40:59,423 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,423 INFO sqlalchemy.engine.base.Engine ('구립봄빛어린이집', '김지영', '서울특별시 강동구 아리수로97길 19 ,(강일동, 강일리버파크4단지아파트) (강일동)', '02', '3426', '7714', 2)
2021-08-18 17:40:59,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,425 INFO sqlalchemy.engine.base.Engine ('구립유진어린이집', '박영길', '서울특별시 강동구 아리수로94길 19 ,강일동,강일리버파크6단지아파트 (강일동)', '02', '442', '7942', 2)
2021-08-18 17:40:59,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,426 INFO sqlalchemy.engine.base.Engine ('구립태영어린이집', '안병철', '서울특별시 강동구 천호대로163길 21-10 ,관리동(천호동, 천호태영아파트) (천호제3동)', '02', '470', '2122', 2)
2021-08-18 17:40:59,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,429 INFO sqlalchemy.engine.base.Engine ('오류동행복주택어린이집', '이상철', '서울특별시 구로구 경인로20가길 38 ,1층 (오류제1동)', '02', '2088', '5752', 7)
2021-08-18 17:40:59,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,431 INFO sqlalchemy.engine.base.Engine ('예담어린이집', '이영진', '서울특별시 광진구 아차산로 537-17 ,광장힐스테이트 관리동 (광장동)', '02', '444', '2008', 6)
2021-08-18 17:40:59,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,433 INFO sqlalchemy.engine.base.Engine ('LG CNS어린이집', '한영진', '서울특별시 강서구 마곡중앙10로 70 (가양제1동)', '02', '2088', '4065', 4)
2021-08-18 17:40:59,434 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,435 INFO sqlalchemy.engine.base.Engine ('맑은숲어린이집', '안경회', '서울특별시 용산구 한남대로40길 76 ,맑은숲어린이집 (한남동)', '02', '798', '3500', 21)
2021-08-18 17:40:59,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,437 INFO sqlalchemy.engine.base.Engine ('별찌어린이집', '임종수', '서울특별시 금천구 벚꽃로6길 3 ,102동 102호 (독산제1동)', '070', '8159', '4578', 8)
2021-08-18 17:40:59,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,438 INFO sqlalchemy.engine.base.Engine ('송파위례23어린이집', '황민서', '서울특별시 송파구 위례순환로 477 ,2323동 1층(장지동, 위례포레샤인) (위례동)', '02', '448', '0048', 18)
2021-08-18 17:40:59,439 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,440 INFO sqlalchemy.engine.base.Engine ('송파위례햇살어린이집', '김준혁', '서울특별시 송파구 위례순환로 477 (위례동)', '02', '402', '0056', 18)
2021-08-18 17:40:59,441 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,441 INFO sqlalchemy.engine.base.Engine ('서초구립 내곡연두어린이집', '김은정', '서울특별시 서초구 헌릉로 226 ,1층 (내곡동)', '02', '529', '0081', 15)
2021-08-18 17:40:59,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,443 INFO sqlalchemy.engine.base.Engine ('서초구립 도구머리어린이집', '한지민', '서울특별시 서초구 청두곶2길 33 (방배2동)', '02', '588', '5952', 15)
2021-08-18 17:40:59,444 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,445 INFO sqlalchemy.engine.base.Engine ('서초구립 반포단비어린이집', '조민서', '서울특별시 서초구 주흥13길 12 (반포1동)', '02', '585', '3927', 15)
2021-08-18 17:40:59,446 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,447 INFO sqlalchemy.engine.base.Engine ('서초구립 방배4동어린이집', '서현정', '서울특별시 서초구 서초대로19길 16 (방배4동)', '02', '523', '6545', 15)
2021-08-18 17:40:59,449 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,450 INFO sqlalchemy.engine.base.Engine ('서초구립 잠원동어린이집', '김은경', '서울특별시 서초구 강남대로95길 75 ,. (잠원동)', '02', '523', '3615', 15)
2021-08-18 17:40:59,451 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,452 INFO sqlalchemy.engine.base.Engine ('안암래미안어린이집', '이민재', '서울특별시 성북구 안암동1가 인촌로17가길 64 ,안암래미안아파트 관리동 1층 (안암동)', '02', '927', '8179', 17)
2021-08-18 17:40:59,455 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,456 INFO sqlalchemy.engine.base.Engine ('구립 이편한세상금호어린이집', '신정식', '서울특별시 성동구 금호동1가 금호로 118 ,e편한세상 금호파크힐스아파트 관리동 (금호1가동)', '02', '2282', '2018', 16)
2021-08-18 17:40:59,457 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,458 INFO sqlalchemy.engine.base.Engine ('구립 힐스테이트서울숲리버어린이집', '박영환', '서울특별시 성동구 금호동4가 금호로 40 ,힐스테이트서울숲리버아파트 관리동 (금호4가동)', '02', '2295', '7100', 16)
2021-08-18 17:40:59,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,460 INFO sqlalchemy.engine.base.Engine ('구립 폭포동어린이집', '최종수', '서울특별시 은평구 진관1로 77-8 ,폭포동4-1단지아파트내 관리동1층 부대복리시설 (진관동)', '02', '352', '5233', 22)
2021-08-18 17:40:59,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,461 INFO sqlalchemy.engine.base.Engine ('금나래어린이집', '강지혜', '서울특별시 영등포구 도신로60길 17-12 (신길제1동)', '02', '844', '2018', 20)
2021-08-18 17:40:59,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,464 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '류수빈', '서울특별시 영등포구 도림로39길 11-13 (대림제3동)', '02', '831', '0462', 20)
2021-08-18 17:40:59,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,466 INFO sqlalchemy.engine.base.Engine ('한샘어린이집', '한경자', '서울특별시 마포구 성암로 179 (상암동)', '02', '6470', '6300', 13)
2021-08-18 17:40:59,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,469 INFO sqlalchemy.engine.base.Engine ('구립 해누리어린이집', '김정운', '서울특별시 양천구 목동동로 81 (신정6동)', '02', '2062', '0102', 19)
2021-08-18 17:40:59,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,471 INFO sqlalchemy.engine.base.Engine ('구립 북한산어린이집', '정예은', '서울특별시 은평구 진흥로 265 ,주민공동시설 중 어린이집(불광동, 북한산래미안아파트) (불광제1동)', '02', '353', '8860', 22)
2021-08-18 17:40:59,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,473 INFO sqlalchemy.engine.base.Engine ('구립 비단산어린이집', '전민석', '서울특별시 은평구 은평터널로7가길 6 (신사제2동)', '02', '376', '9993', 22)
2021-08-18 17:40:59,474 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,476 INFO sqlalchemy.engine.base.Engine ('구립 텐즈아이어린이집', '강영철', '서울특별시 성동구 무학로 33 ,114동 1층 (하왕십리동, 텐즈힐1단지) (왕십리도선동)', '02', '2282', '2114', 16)
2021-08-18 17:40:59,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,478 INFO sqlalchemy.engine.base.Engine ('아모레퍼시픽 서울어린이집', '권영길', '서울특별시 용산구 한강로2가 한강대로 100 ,(주)아모레퍼시픽 2층 (한강로동)', '02', '709', '5193', 21)
2021-08-18 17:40:59,479 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,480 INFO sqlalchemy.engine.base.Engine ('구립 다음어린이집', '오상훈', '서울특별시 은평구 진흥로 267 ,(불광1동, 북한산래미안 1단지아파트) 주민공동시설 중 어린이집 (불광제1동)', '02', '388', '2277', 22)
2021-08-18 17:40:59,481 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,482 INFO sqlalchemy.engine.base.Engine ('구립다온어린이집', '조준혁', '서울특별시 강동구 올림픽로79길 46 (천호제2동)', '02', '489', '1712', 2)
2021-08-18 17:40:59,483 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,484 INFO sqlalchemy.engine.base.Engine ('구립 굿모닝어린이집', '임정수', '서울특별시 광진구 아차산로 552 ,2동105호(광장동, 광장극동아파트) (광장동)', '02', '458', '6169', 6)
2021-08-18 17:40:59,485 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,487 INFO sqlalchemy.engine.base.Engine ('구립 꿈초롱어린이집', '황은정', '서울특별시 양천구 신정로11길 20 ,202동 104호 (신정3동)', '02', '6091', '0102', 19)
2021-08-18 17:40:59,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,490 INFO sqlalchemy.engine.base.Engine ('구립샘터어린이집', '임민지', '서울특별시 광진구 아차산로 503-23 ,102동 102호(광장동,청구아파트) (광장동)', '02', '456', '4566', 6)
2021-08-18 17:40:59,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,492 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '윤지은', '서울특별시 용산구 원효로1가 백범로 329 ,꿈나무어린이집 (원효로제1동)', '02', '706', '2468', 21)
2021-08-18 17:40:59,493 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,493 INFO sqlalchemy.engine.base.Engine ('초안숲속어린이집', '안건우', '서울특별시 노원구 마들로5길 25 ,(월계동, 두산위브아파트) (월계2동)', '02', '990', '0502', 9)
2021-08-18 17:40:59,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,495 INFO sqlalchemy.engine.base.Engine ('파크리오어린이집', '신지민', '서울특별시 송파구 올림픽로 435 ,112동 102호(신천동, 파크리오아파트) (잠실4동)', '02', '418', '7710', 18)
2021-08-18 17:40:59,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,498 INFO sqlalchemy.engine.base.Engine ('NH투자증권어린이집', '권예은', '서울특별시 영등포구 여의대로 66 ,2층 (여의동)', '02', '761', '9433', 20)
2021-08-18 17:40:59,499 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,499 INFO sqlalchemy.engine.base.Engine ('풍납또래어린이집', '한광수', '서울특별시 송파구 한가람로 478 ,101동 109호(풍납동, 씨티극동아파트) (풍납1동)', '02', '485', '9540', 18)
2021-08-18 17:40:59,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,501 INFO sqlalchemy.engine.base.Engine ('구립조은어린이집', '정예준', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트 1단지 관리동(122동 123동 사이) (청림동)', '02', '875', '9199', 5)
2021-08-18 17:40:59,501 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,503 INFO sqlalchemy.engine.base.Engine ('마곡13 하나어린이집', '전성민', '서울특별시 강서구 마곡중앙1로 71 ,(마곡동, 마곡13단지힐스테이트마스터) (공항동)', '02', '2666', '4521', 4)
2021-08-18 17:40:59,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,508 INFO sqlalchemy.engine.base.Engine ('서초구립 방배본동신나는어린이집', '정준호', '서울특별시 서초구 동광로11길 23 ,. (방배본동)', '02', '534', '8450', 15)
2021-08-18 17:40:59,509 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,510 INFO sqlalchemy.engine.base.Engine ('용문어린이집', '김동현', '서울특별시 용산구 효창원로 88 ,브라운스톤용산 104-103 (용문동)', '02', '711', '3136', 21)
2021-08-18 17:40:59,511 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,512 INFO sqlalchemy.engine.base.Engine ('놀이존어린이집', '오유진', '서울특별시 강남구 영동대로141길 5 (청담동)', '070', '4837', '0620', 1)
2021-08-18 17:40:59,514 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,515 INFO sqlalchemy.engine.base.Engine ('LG서울역어린이집', '서순자', '서울특별시 중구 남대문로5가 후암로 98 ,2층 (회현동)', '02', '3789', '1002', 24)
2021-08-18 17:40:59,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,517 INFO sqlalchemy.engine.base.Engine ('공룡 어린이집', '박영일', '서울특별시 성동구 독서당로 218 ,107동 104호(옥수동, 삼성아파트) (옥수동)', '02', '2298', '8212', 16)
2021-08-18 17:40:59,518 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,518 INFO sqlalchemy.engine.base.Engine ('동화속어린이집', '강영숙', '서울특별시 강남구 역삼로 456-2 ,1층 (대치제4동)', '02', '2247', '0008', 1)
2021-08-18 17:40:59,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,520 INFO sqlalchemy.engine.base.Engine ('구립백합어린이집', '황건우', '서울특별시 동작구 동작대로29길 119 ,110동 105호 (사당동, 극동아파트) (사당제2동)', '02', '596', '9117', 12)
2021-08-18 17:40:59,521 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,522 INFO sqlalchemy.engine.base.Engine ('구립장미어린이집', '정미영', '서울특별시 동작구 동작대로29길 115 (사당제2동)', '02', '596', '1116', 12)
2021-08-18 17:40:59,523 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,524 INFO sqlalchemy.engine.base.Engine ('서울교통공사 어린이집', '오성호', '서울특별시 성동구 자동차시장길 22 ,인재개발원 1층 (용답동)', '02', '6110', '8093', 16)
2021-08-18 17:40:59,525 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,526 INFO sqlalchemy.engine.base.Engine ('구립강감찬어린이집', '윤정수', '서울특별시 관악구 관악로8길 45 (낙성대동)', '02', '873', '6677', 5)
2021-08-18 17:40:59,527 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,528 INFO sqlalchemy.engine.base.Engine ('구립장군봉어린이집', '오은영', '서울특별시 관악구 장군봉길 100 (서원동)', '02', '875', '0960', 5)
2021-08-18 17:40:59,529 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,529 INFO sqlalchemy.engine.base.Engine ('서울테크노파크친친어린이집', '황지훈', '서울특별시 노원구 공릉로 232 ,(공릉동, 서울과기대 내 서울테크노파크친친 어린이집) (공릉2동)', '02', '944', '6100', 9)
2021-08-18 17:40:59,531 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,531 INFO sqlalchemy.engine.base.Engine ('해피랜드어린이집', '윤경숙', '서울특별시 강서구 마곡중앙1로 71 ,1312동 106호(마곡동,마곡13단지힐스테이트마스터) (공항동)', '02', '2667', '0008', 4)
2021-08-18 17:40:59,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,532 INFO sqlalchemy.engine.base.Engine ('우성어린이집', '최성진', '서울특별시 서초구 방배선행길 1 ,102동 103호(방배동,우성아파트) (방배2동)', '02', '588', '8979', 15)
2021-08-18 17:40:59,533 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,534 INFO sqlalchemy.engine.base.Engine ('아크로타워어린이집', '전영식', '서울특별시 영등포구 영등포동7가 국회대로54길 11 ,아크로타워스퀘어아파트 관리동어린이집 (영등포동)', '02', '2677', '9207', 20)
2021-08-18 17:40:59,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,535 INFO sqlalchemy.engine.base.Engine ('송파더샵어린이집', '최지혜', '서울특별시 송파구 위례광장로 270 ,103동 1층 (위례동)', '02', '3012', '7776', 18)
2021-08-18 17:40:59,536 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,536 INFO sqlalchemy.engine.base.Engine ('송파아이별어린이집', '윤은영', '서울특별시 송파구 위례광장로 230 ,204동 1층 (위례동)', '02', '404', '5556', 18)
2021-08-18 17:40:59,537 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,537 INFO sqlalchemy.engine.base.Engine ('구립 구의1동 아이터어린이집', '정정남', '서울특별시 광진구 자양로23길 79 (구의제1동)', '02', '2201', '8684', 6)
2021-08-18 17:40:59,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,539 INFO sqlalchemy.engine.base.Engine ('구립 꽃별어린이집', '최미숙', '서울특별시 양천구 화곡로3길 43 ,103동 103호 (신월5동)', '02', '2603', '9933', 19)
2021-08-18 17:40:59,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,541 INFO sqlalchemy.engine.base.Engine ('구립 별하어린이집', '류영진', '서울특별시 양천구 목동동로 50 ,1220동 107호 (신정7동)', '02', '2647', '8900', 19)
2021-08-18 17:40:59,542 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,543 INFO sqlalchemy.engine.base.Engine ('구립해와별어린이집', '이미영', '서울특별시 동작구 만양로8길 50 (노량진제1동)', '02', '817', '4972', 12)
2021-08-18 17:40:59,544 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,545 INFO sqlalchemy.engine.base.Engine ('누리보듬어린이집', '박건우', '서울특별시 동대문구 장안벚꽃로1길 7 ,1003동 104호(장안동, 힐스테이트아파트) (장안제2동)', '02', '2212', '1256', 11)
2021-08-18 17:40:59,547 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,548 INFO sqlalchemy.engine.base.Engine ('도토리어린이집', '이민재', '서울특별시 마포구 희우정로 53-6 (합정동)', '02', '322', '0556', 13)
2021-08-18 17:40:59,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,550 INFO sqlalchemy.engine.base.Engine ('리버웰어린이집', '조성호', '서울특별시 마포구 토정로31길 23 ,래미안마포리버웰 관리동어린이집 (용강동)', '02', '711', '6161', 13)
2021-08-18 17:40:59,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,552 INFO sqlalchemy.engine.base.Engine ('삼성어린이집', '신예준', '서울특별시 마포구 상암산로1길 57 ,상암월드컵6단지 610동 1층 (상암동)', '02', '307', '7101', 13)
2021-08-18 17:40:59,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,554 INFO sqlalchemy.engine.base.Engine ('서초구립 느티나무어린이집', '장지은', '서울특별시 서초구 사임당로19길 126 (서초1동)', '02', '523', '0100', 15)
2021-08-18 17:40:59,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,557 INFO sqlalchemy.engine.base.Engine ('서초구립 반포1동주민센터어린이집', '권진호', '서울특별시 서초구 사평대로 273 (반포1동)', '02', '534', '8895', 15)
2021-08-18 17:40:59,558 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,559 INFO sqlalchemy.engine.base.Engine ('서초구립 반포미도어린이집', '오지혜', '서울특별시 서초구 서초중앙로29길 28 ,303동 108호(반포동, 반포미도아파트) (반포4동)', '02', '595', '2237', 15)
2021-08-18 17:40:59,560 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,561 INFO sqlalchemy.engine.base.Engine ('서초구립 서초1동하은어린이집', '서성호', '서울특별시 서초구 서초대로58길 35-6 ,. (서초1동)', '02', '3473', '1757', 15)
2021-08-18 17:40:59,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,565 INFO sqlalchemy.engine.base.Engine ('서초구립 서초3동어린이집', '송준영', '서울특별시 서초구 반포대로13길 64 ,서초구립 서초3동어린이집 (서초3동)', '02', '522', '5665', 15)
2021-08-18 17:40:59,566 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,567 INFO sqlalchemy.engine.base.Engine ('서초구립 서초4동써밋1어린이집', '송종수', '서울특별시 서초구 서운로 201 ,(서초4동, 푸르지오써밋아파트) (서초4동)', '02', '6933', '6447', 15)
2021-08-18 17:40:59,568 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,569 INFO sqlalchemy.engine.base.Engine ('서초구립 서초4동써밋2어린이집', '류민지', '서울특별시 서초구 서운로 212 ,(서초4동, 서초푸르지오써밋아파트) (서초4동)', '02', '6930', '5651', 15)
2021-08-18 17:40:59,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,573 INFO sqlalchemy.engine.base.Engine ('서초구립 서초4동행복어린이집', '오민재', '서울특별시 서초구 서초중앙로 200 ,3동 106호(서초동, 삼풍아파트) (서초4동)', '02', '537', '1240', 15)
2021-08-18 17:40:59,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,575 INFO sqlalchemy.engine.base.Engine ('신나는어린이집', '윤지훈', '서울특별시 동대문구 외대역동로 101 ,102동 102호(이문동, 중앙하이츠아파트) (이문제1동)', '02', '969', '5906', 11)
2021-08-18 17:40:59,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,580 INFO sqlalchemy.engine.base.Engine ('아이미소어린이집', '송정자', '서울특별시 동대문구 전농로16길 51 ,107동 104호(전농동,래미안아름숲) (전농제2동)', '02', '2212', '2293', 11)
2021-08-18 17:40:59,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,583 INFO sqlalchemy.engine.base.Engine ('영은어린이집', '장정식', '서울특별시 영등포구 양평동3가 양산로 61 (양평제1동)', '02', '2633', '6966', 20)
2021-08-18 17:40:59,585 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,585 INFO sqlalchemy.engine.base.Engine ('키즈극동어린이집', '장상훈', '서울특별시 구로구 구로중앙로7길 28 ,1동 101호(구로동, 극동아파트) (구로제4동)', '02', '6347', '5001', 7)
2021-08-18 17:40:59,587 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,590 INFO sqlalchemy.engine.base.Engine ('한그루어린이집', '강준영', '서울특별시 도봉구 도봉로131길 86 (쌍문제2동)', '02', '907', '2720', 10)
2021-08-18 17:40:59,591 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,592 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '장지영', '서울특별시 동대문구 장안벚꽃로 107 ,102동 101호(장안동,현대홈타운) (장안제1동)', '02', '6457', '0087', 11)
2021-08-18 17:40:59,594 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,596 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '서민수', '서울특별시 강남구 삼성로51길 25 ,대치SK-VIEW아파트 관리동 (대치제1동)', '02', '565', '0302', 1)
2021-08-18 17:40:59,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,598 INFO sqlalchemy.engine.base.Engine ('햇빛어린이집', '강정식', '서울특별시 동대문구 사가정로 190 ,16동 108호(전농동, 우성아파트) (전농제2동)', '02', '2242', '0089', 11)
2021-08-18 17:40:59,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,600 INFO sqlalchemy.engine.base.Engine ('홍익어린이집', '오지훈', '서울특별시 마포구 서강로9길 45 ,태영아파트 내 보육시설 (서강동)', '02', '3141', '7770', 13)
2021-08-18 17:40:59,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,602 INFO sqlalchemy.engine.base.Engine ('SC으뜸별 어린이집', '장정수', '서울특별시 종로구 종로 47 (종로1·2·3·4가동)', '02', '3210', '0904', 23)
2021-08-18 17:40:59,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,603 INFO sqlalchemy.engine.base.Engine ('문정훼밀리타운어린이집', '오민지', '서울특별시 송파구 중대로 24 ,228동 102호 (문정2동)', '02', '404', '5600', 18)
2021-08-18 17:40:59,605 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,605 INFO sqlalchemy.engine.base.Engine ('햇살가득어린이집', '안정자', '서울특별시 마포구 새창로6길 16 ,새창로6길 15(추후수정-도로명연동불가) (도화동)', '02', '719', '9995', 13)
2021-08-18 17:40:59,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,608 INFO sqlalchemy.engine.base.Engine ('경남큰사랑어린이집', '윤상훈', '서울특별시 구로구 오류로 65 ,105동 101호(오류동, 경남아너스빌) (오류제2동)', '02', '2066', '2081', 7)
2021-08-18 17:40:59,610 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,611 INFO sqlalchemy.engine.base.Engine ('꿈사랑어린이집', '류준호', '서울특별시 구로구 경인로40길 11 ,101동 104호 (개봉제1동)', '02', '6734', '4757', 7)
2021-08-18 17:40:59,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,613 INFO sqlalchemy.engine.base.Engine ('래미안어린이집', '임지혜', '서울특별시 영등포구 신풍로 77 ,래미안에스티움 110동 101호 (신길제7동)', '02', '6449', '2345', 20)
2021-08-18 17:40:59,614 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,615 INFO sqlalchemy.engine.base.Engine ('아름뜰어린이집', '오영일', '서울특별시 중랑구 상봉중앙로8길 76 ,1509동 101호 (상봉제1동)', '02', '6231', '2848', 25)
2021-08-18 17:40:59,616 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,617 INFO sqlalchemy.engine.base.Engine ('예쁜별어린이집', '임광수', '서울특별시 중랑구 신내로 110 ,13동 106호(신내동, 동성아파트) (신내1동)', '02', '438', '5751', 25)
2021-08-18 17:40:59,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,619 INFO sqlalchemy.engine.base.Engine ('푸르름어린이집', '임미경', '서울특별시 영등포구 도림로81길 12-1 (신길제5동)', '02', '833', '2446', 20)
2021-08-18 17:40:59,621 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,622 INFO sqlalchemy.engine.base.Engine ('하람어린이집', '최영일', '서울특별시 영등포구 신풍로 77 ,114동 106호 (신길제7동)', '02', '835', '9922', 20)
2021-08-18 17:40:59,623 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,624 INFO sqlalchemy.engine.base.Engine ('구립 왕십리자이어린이집', '한은영', '서울특별시 성동구 난계로 100 (왕십리제2동)', '02', '2296', '0901', 16)
2021-08-18 17:40:59,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,626 INFO sqlalchemy.engine.base.Engine ('구립꿈마루어린이집', '오민수', '서울특별시 강동구 천호대로 1077 ,101동 1층(천호동, 래미안강동팰리스) (천호제3동)', '02', '477', '0713', 2)
2021-08-18 17:40:59,627 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,628 INFO sqlalchemy.engine.base.Engine ('화랑어린이집', '김지훈', '서울특별시 중랑구 숙선옹주로 45 ,108동(묵동, e편한세상 화랑대) (묵제1동)', '02', '979', '7802', 25)
2021-08-18 17:40:59,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,631 INFO sqlalchemy.engine.base.Engine ('구립강남어린이집', '최동현', '서울특별시 동작구 만양로12길 5-12 (노량진제1동)', '02', '814', '7615', 12)
2021-08-18 17:40:59,632 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,633 INFO sqlalchemy.engine.base.Engine ('구립새빛어린이집', '황지민', '서울특별시 동작구 장승배기로11가길 11 (상도제2동)', '02', '827', '0791', 12)
2021-08-18 17:40:59,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,635 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '정준호', '서울특별시 서대문구 신촌로35길 10 (북아현동)', '02', '364', '1231', 14)
2021-08-18 17:40:59,637 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,637 INFO sqlalchemy.engine.base.Engine ('새순어린이집', '강민지', '서울특별시 용산구 원효로35길 37-7 ,1,2층 (원효로제2동)', '02', '716', '7930', 21)
2021-08-18 17:40:59,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,640 INFO sqlalchemy.engine.base.Engine ('솔빛어린이집', '임유진', '서울특별시 서대문구 북아현로 29 ,e편한세상신촌3단지 302동 (북아현동)', '02', '313', '4800', 14)
2021-08-18 17:40:59,641 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,642 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '장서현', '서울특별시 서대문구 통일로 348 ,청구아파트 (홍제제2동)', '02', '396', '9333', 14)
2021-08-18 17:40:59,643 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,644 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '최준영', '서울특별시 서대문구 북아현로1길 17 (북아현동)', '02', '313', '7500', 14)
2021-08-18 17:40:59,645 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,646 INFO sqlalchemy.engine.base.Engine ('푸른빛어린이집', '류은경', '서울특별시 서대문구 북아현로1가길 20 ,e편한세상신촌 102동 (북아현동)', '02', '313', '9200', 14)
2021-08-18 17:40:59,647 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,648 INFO sqlalchemy.engine.base.Engine ('구립 역마을어린이집', '전유진', '서울특별시 은평구 갈현로7길 20 (역촌동)', '02', '356', '8083', 22)
2021-08-18 17:40:59,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,650 INFO sqlalchemy.engine.base.Engine ('서울세관 직장어린이집', '한종수', '서울특별시 강남구 언주로 721 ,서울세관 별관동 1층 (논현2동)', '02', '510', '1993', 1)
2021-08-18 17:40:59,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,652 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '송현준', '서울특별시 강서구 마곡중앙1로 71 ,1314동 102호(마곡동,마곡13단지힐스테이트마스터) (공항동)', '02', '2666', '3330', 4)
2021-08-18 17:40:59,654 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,654 INFO sqlalchemy.engine.base.Engine ('한국외국어대학교어린이집', '임정순', '서울특별시 동대문구 천장산로9길 11 (이문제1동)', '02', '2173', '2518', 11)
2021-08-18 17:40:59,656 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,657 INFO sqlalchemy.engine.base.Engine ('고운아이어린이집', '신준호', '서울특별시 강서구 마곡중앙1로 71 ,1307동 101호(공항동,마곡13단지힐스테이트마스터) (공항동)', '02', '2665', '5757', 4)
2021-08-18 17:40:59,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,659 INFO sqlalchemy.engine.base.Engine ('구립 광현어린이집', '권건우', '서울특별시 은평구 연서로27길 31-7 (갈현제2동)', '02', '356', '8522', 22)
2021-08-18 17:40:59,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,661 INFO sqlalchemy.engine.base.Engine ('구립 소담어린이집', '신정남', '서울특별시 양천구 신정로 290 ,306동 104호(신정동, 신트리아파트) (신정3동)', '02', '2061', '2282', 19)
2021-08-18 17:40:59,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,663 INFO sqlalchemy.engine.base.Engine ('구립 아가사랑어린이집', '최순자', '서울특별시 양천구 목동동로 350 ,510동 106호(목동, 목동5단지아파트) (목5동)', '02', '6342', '7756', 19)
2021-08-18 17:40:59,664 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,665 INFO sqlalchemy.engine.base.Engine ('구립 채송화어린이집', '한정호', '서울특별시 양천구 화곡로 85 ,상진지오벨리 아파트 103호 (신월5동)', '02', '2692', '6670', 19)
2021-08-18 17:40:59,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,668 INFO sqlalchemy.engine.base.Engine ('자곡단비어린이집', '최영철', '서울특별시 강남구 자곡로 260 ,417동 104호(자곡동, 강남한양수자인아파트) (세곡동)', '02', '6326', '7879', 1)
2021-08-18 17:40:59,670 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,671 INFO sqlalchemy.engine.base.Engine ('청명어린이집', '이준서', '서울특별시 성북구 화랑로32라길 21 (석관동)', '02', '959', '7890', 17)
2021-08-18 17:40:59,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,674 INFO sqlalchemy.engine.base.Engine ('구립올림픽파크꿈별어린이집', '안지민', '서울특별시 강동구 성내로 80 (성내제1동)', '02', '487', '0708', 2)
2021-08-18 17:40:59,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,677 INFO sqlalchemy.engine.base.Engine ('노아어린이집', '신성수', '서울특별시 영등포구 신풍로 77 ,래미안에스티움 103동103호 (신길제7동)', '02', '832', '5527', 20)
2021-08-18 17:40:59,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,680 INFO sqlalchemy.engine.base.Engine ('송파푸르지오어린이집', '오지은', '서울특별시 송파구 송파대로 111 ,103동 1층 (문정2동)', '02', '406', '3040', 18)
2021-08-18 17:40:59,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,683 INFO sqlalchemy.engine.base.Engine ('중계해봄어린이집', '조정운', '서울특별시 노원구 중계로19길 44 (중계1동)', '02', '966', '5300', 9)
2021-08-18 17:40:59,684 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,685 INFO sqlalchemy.engine.base.Engine ('마곡아이솔어린이집', '전정남', '서울특별시 강서구 마곡중앙1로 71 ,1301동 101호(마곡동,마곡13단지힐스테이트마스터) (공항동)', '02', '6080', '7839', 4)
2021-08-18 17:40:59,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,687 INFO sqlalchemy.engine.base.Engine ('보라어린이집', '김예은', '서울특별시 강서구 공항대로39길 100 ,103동 105호(등촌동,등촌대림아파트) (등촌제3동)', '02', '3661', '7715', 4)
2021-08-18 17:40:59,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,689 INFO sqlalchemy.engine.base.Engine ('마곡두린아이어린이집', '이지민', '서울특별시 강서구 마곡중앙1로 71 ,1305동 102호(마곡동, 마곡13단지힐스테이트마스터) (공항동)', '02', '2663', '0207', 4)
2021-08-18 17:40:59,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,691 INFO sqlalchemy.engine.base.Engine ('래미안에스티움어린이집', '신서현', '서울특별시 영등포구 신풍로 77 ,래미안에스티움아파트 관리동 (신길제7동)', '02', '842', '4111', 20)
2021-08-18 17:40:59,692 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,693 INFO sqlalchemy.engine.base.Engine ('꿈땅어린이집', '한영자', '서울특별시 영등포구 당산동4가 당산로41길 23 ,106동 105호 (당산제2동)', '02', '2633', '3998', 20)
2021-08-18 17:40:59,695 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,696 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '임경회', '서울특별시 동대문구 사가정로 65 ,212동 105호(전농동,래미안크레시티) (전농제1동)', '02', '2214', '3155', 11)
2021-08-18 17:40:59,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,700 INFO sqlalchemy.engine.base.Engine ('미담어린이집', '신지훈', '서울특별시 중구 퇴계로 447 (황학동)', '02', '2231', '7227', 24)
2021-08-18 17:40:59,702 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,703 INFO sqlalchemy.engine.base.Engine ('착한나라어린이집', '임정순', '서울특별시 마포구 망원로4길 16-8 (망원제1동)', '02', '324', '0965', 13)
2021-08-18 17:40:59,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,705 INFO sqlalchemy.engine.base.Engine ('구립 꼬마대통령어린이집', '서광수', '서울특별시 은평구 진관3로 15-35 ,구파발10단지 1009동 1층 (진관동)', '02', '357', '1008', 22)
2021-08-18 17:40:59,708 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,709 INFO sqlalchemy.engine.base.Engine ('서울시설공단 누비어린이집', '이영자', '서울특별시 성동구 왕십리로26길 29 (왕십리도선동)', '02', '2298', '2800', 16)
2021-08-18 17:40:59,711 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,712 INFO sqlalchemy.engine.base.Engine ('늘봄어린이집', '윤민지', '서울특별시 용산구 이촌로2가길 122 ,대림아파트 (이촌제2동)', '02', '702', '2522', 21)
2021-08-18 17:40:59,714 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,716 INFO sqlalchemy.engine.base.Engine ('사랑가득어린이집', '전준서', '서울특별시 송파구 위례광장로 121 ,2418동 101호 (위례동)', '02', '6082', '1357', 18)
2021-08-18 17:40:59,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,719 INFO sqlalchemy.engine.base.Engine ('아뜰리에어린이집', '송유진', '서울특별시 성북구 보문동6가 보문사길 111 (보문동)', '02', '929', '5556', 17)
2021-08-18 17:40:59,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,721 INFO sqlalchemy.engine.base.Engine ('구립예람어린이집', '임광수', '서울특별시 금천구 독산로72길 11-16 (독산제4동)', '02', '830', '5855', 8)
2021-08-18 17:40:59,722 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,723 INFO sqlalchemy.engine.base.Engine ('구립하늘아이어린이집', '강정남', '서울특별시 강북구 삼양로19길 25 ,103동 102호(미아동, 래미안트라베라1단지아파트) (삼각산동)', '02', '983', '2323', 3)
2021-08-18 17:40:59,724 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,725 INFO sqlalchemy.engine.base.Engine ('구립해맑은어린이집', '이영철', '서울특별시 강북구 솔샘로 174 ,117동 102호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '6229', '2225', 3)
2021-08-18 17:40:59,727 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,727 INFO sqlalchemy.engine.base.Engine ('키즈어린이집', '류영진', '서울특별시 영등포구 도림천로11길 3 (대림제2동)', '02', '846', '2131', 20)
2021-08-18 17:40:59,729 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,730 INFO sqlalchemy.engine.base.Engine ('위례별마루어린이집', '김지원', '서울특별시 송파구 위례광장로 215 ,(장지동, 위례스타힐스) (위례동)', '02', '403', '3334', 18)
2021-08-18 17:40:59,732 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,734 INFO sqlalchemy.engine.base.Engine ('새둥지어린이집', '정경회', '서울특별시 용산구 이촌로65가길 3 ,110동 101호 (이촌제1동)', '02', '796', '5025', 21)
2021-08-18 17:40:59,735 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,736 INFO sqlalchemy.engine.base.Engine ('애플어린이집', '한수빈', '서울특별시 강동구 아리수로50길 50 ,124동 204호 (고덕제1동)', '02', '441', '6310', 2)
2021-08-18 17:40:59,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,738 INFO sqlalchemy.engine.base.Engine ('지밸리경협어린이집', '류경자', '서울특별시 금천구 가산디지털1로 1 ,더루벤스밸리 305,306,307호 (가산동)', '02', '830', '1501', 8)
2021-08-18 17:40:59,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,741 INFO sqlalchemy.engine.base.Engine ('IBK 참! 좋은 어린이집', '윤동현', '서울특별시 중구 을지로2가 을지로 82 (명동)', '02', '2031', '3394', 24)
2021-08-18 17:40:59,742 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,743 INFO sqlalchemy.engine.base.Engine ('푸른꿈어린이집', '김경자', '서울특별시 용산구 백범로 260 ,효창파크푸르지오아파트 104동, 1층 (효창동)', '02', '719', '9989', 21)
2021-08-18 17:40:59,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,744 INFO sqlalchemy.engine.base.Engine ('서밋RUTC어린이집', '박정웅', '서울특별시 송파구 오금로20길 3 (송파1동)', '02', '417', '1363', 18)
2021-08-18 17:40:59,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,745 INFO sqlalchemy.engine.base.Engine ('위례꿈별어린이집', '장도현', '서울특별시 송파구 위례광장로 215 ,(장지동, 위례스타힐스) (위례동)', '02', '3402', '2300', 18)
2021-08-18 17:40:59,747 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,748 INFO sqlalchemy.engine.base.Engine ('파크하비오어린이집', '장성호', '서울특별시 송파구 송파대로 111 ,107동 1층 (문정2동)', '02', '431', '6757', 18)
2021-08-18 17:40:59,749 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,750 INFO sqlalchemy.engine.base.Engine ('힐스송파어린이집', '이영환', '서울특별시 송파구 위례광장로 170 ,102동 1층(장지동, 힐스테이트송파위례) (위례동)', '02', '430', '6594', 18)
2021-08-18 17:40:59,751 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,752 INFO sqlalchemy.engine.base.Engine ('구립 백련산힐1차어린이집', '류예준', '서울특별시 은평구 백련산로2길 19 ,관리동(응암2동, 백련산힐스테이트1차) (응암제2동)', '02', '303', '9276', 22)
2021-08-18 17:40:59,753 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,753 INFO sqlalchemy.engine.base.Engine ('구립 파란하늘어린이집', '전혜진', '서울특별시 은평구 통일로72길 16 ,관리동(불광1동, 북한산힐스테이트7차아파트) (불광제1동)', '02', '389', '0025', 22)
2021-08-18 17:40:59,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,755 INFO sqlalchemy.engine.base.Engine ('구로구청 사랑채움 어린이집', '조민지', '서울특별시 구로구 가마산로 245 (구로제2동)', '02', '858', '2046', 7)
2021-08-18 17:40:59,756 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,757 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '권서현', '서울특별시 송파구 정의로 30 (문정2동)', '02', '430', '5599', 18)
2021-08-18 17:40:59,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,759 INFO sqlalchemy.engine.base.Engine ('강동경희대병원어린이집', '강준호', '서울특별시 강동구 동남로 881 ,5층 서희스타힐스(명일동) (명일제2동)', '02', '440', '6710', 2)
2021-08-18 17:40:59,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,761 INFO sqlalchemy.engine.base.Engine ('오케이최고어린이집', '송예준', '서울특별시 용산구 두텁바위로31길 28 (후암동)', '02', '775', '2560', 21)
2021-08-18 17:40:59,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,764 INFO sqlalchemy.engine.base.Engine ('SKY어린이집', '박민지', '서울특별시 마포구 매봉산로 75 ,DDMC 3층 (상암동)', '02', '2146', '0980', 13)
2021-08-18 17:40:59,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,767 INFO sqlalchemy.engine.base.Engine ('가람어린이집', '전영진', '서울특별시 영등포구 도림로 365 ,101동 101호(도림동, 동아에코빌) (도림동)', '02', '6203', '2335', 20)
2021-08-18 17:40:59,768 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,769 INFO sqlalchemy.engine.base.Engine ('공룡어린이집', '황민석', '서울특별시 노원구 동일로227길 86 ,1612동 105호(상계도, 주공아파트) (상계8동)', '02', '939', '4730', 9)
2021-08-18 17:40:59,770 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,771 INFO sqlalchemy.engine.base.Engine ('구립 꼬꼬마라인어린이집', '신정자', '서울특별시 강서구 화곡로68길 33 ,102동 101호(등촌동, 라인아파트) (등촌제1동)', '02', '6736', '2352', 4)
2021-08-18 17:40:59,772 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,773 INFO sqlalchemy.engine.base.Engine ('구립 밤비어린이집', '조은경', '서울특별시 강서구 공항대로45길 68-6 ,106동 104호(등촌동, 등촌서광마을아파트) (등촌제1동)', '02', '3662', '8003', 4)
2021-08-18 17:40:59,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,775 INFO sqlalchemy.engine.base.Engine ('구립 아기별어린이집', '조민수', '서울특별시 강서구 강서로 348 ,108동 101호(내발산동, 우장산힐스테이트) (우장산동)', '02', '3661', '8846', 4)
2021-08-18 17:40:59,776 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,777 INFO sqlalchemy.engine.base.Engine ('구립 코알라아가마을어린이집', '윤광수', '서울특별시 강서구 허준로 175 ,608동 101호(가양동, 가양6단지아파트) (가양제3동)', '02', '2668', '3955', 4)
2021-08-18 17:40:59,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,779 INFO sqlalchemy.engine.base.Engine ('구립 큰별어린이집', '강영일', '서울특별시 강서구 화곡로63가길 71 ,1005동 106호(등촌동, 등촌주공10단지아파트) (등촌제3동)', '02', '3664', '4775', 4)
2021-08-18 17:40:59,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,781 INFO sqlalchemy.engine.base.Engine ('구립 해그림어린이집', '오정운', '서울특별시 양천구 목동로 224 ,101동 110호 (목1동)', '02', '2652', '6363', 19)
2021-08-18 17:40:59,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,783 INFO sqlalchemy.engine.base.Engine ('구립꿀송이어린이집', '최민수', '서울특별시 관악구 성현로 80 ,관악드림타운아파트 106-104 (성현동)', '02', '874', '2425', 5)
2021-08-18 17:40:59,784 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,785 INFO sqlalchemy.engine.base.Engine ('구립꿈동산어린이집', '전경회', '서울특별시 강북구 덕릉로30길 10 ,(미아동) (미아동)', '02', '981', '3773', 3)
2021-08-18 17:40:59,786 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,787 INFO sqlalchemy.engine.base.Engine ('구립나래어린이집', '송준혁', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트 112-102 (청림동)', '070', '7583', '7581', 5)
2021-08-18 17:40:59,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,789 INFO sqlalchemy.engine.base.Engine ('구립다솜어린이집', '이유진', '서울특별시 강북구 인수봉로72길 15-20 ,(수유동) (인수동)', '02', '997', '9644', 3)
2021-08-18 17:40:59,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,790 INFO sqlalchemy.engine.base.Engine ('구립다온어린이집', '신영식', '서울특별시 관악구 남부순환로198길 10 ,효림다온아파트 101호 (서원동)', '02', '886', '0225', 5)
2021-08-18 17:40:59,791 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,792 INFO sqlalchemy.engine.base.Engine ('구립도로시몬테소리어린이집', '황지혜', '서울특별시 금천구 벚꽃로 73 ,108동 106호(독산동, 금천현대아파트) (독산제1동)', '02', '805', '8025', 8)
2021-08-18 17:40:59,793 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,794 INFO sqlalchemy.engine.base.Engine ('구립동그라미어린이집', '조건우', '서울특별시 강북구 솔샘로 159 ,104동 102호(미아동, 벽산라이브파크) (삼양동)', '02', '982', '7582', 3)
2021-08-18 17:40:59,796 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,797 INFO sqlalchemy.engine.base.Engine ('구립보람어린이집', '임영일', '서울특별시 관악구 관악로 304 ,현대아파트 118-101 (청림동)', '02', '6275', '7942', 5)
2021-08-18 17:40:59,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,799 INFO sqlalchemy.engine.base.Engine ('구립보물단지어린이집', '윤유진', '서울특별시 관악구 남부순환로230길 94 ,푸르빌3차아파트 101호 (낙성대동)', '02', '888', '3677', 5)
2021-08-18 17:40:59,800 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,801 INFO sqlalchemy.engine.base.Engine ('구립소하어린이집', '정현정', '서울특별시 관악구 관천로15길 116 (신사동)', '02', '854', '4786', 5)
2021-08-18 17:40:59,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,815 INFO sqlalchemy.engine.base.Engine ('구립아기구름어린이집', '송영진', '서울특별시 관악구 남부순환로237길 22 ,1층 (행운동) (행운동)', '02', '872', '2627', 5)
2021-08-18 17:40:59,817 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,818 INFO sqlalchemy.engine.base.Engine ('구립아기둥지어린이집', '전지은', '서울특별시 동작구 상도로 421 ,108동 108호 (관악현대아파트) (상도제1동)', '02', '887', '7796', 12)
2021-08-18 17:40:59,820 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,821 INFO sqlalchemy.engine.base.Engine ('구립오렌지어린이집', '오지은', '서울특별시 강북구 삼양로123길 10-21 (우이동)', '02', '994', '2770', 3)
2021-08-18 17:40:59,822 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,823 INFO sqlalchemy.engine.base.Engine ('구립이루미어린이집', '오은정', '서울특별시 강북구 삼양로27길 80 ,303동 104호(미아동, 두산위브아파트) (삼각산동)', '02', '6397', '0660', 3)
2021-08-18 17:40:59,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,826 INFO sqlalchemy.engine.base.Engine ('구립즐거운어린이집', '조상훈', '서울특별시 강북구 솔샘로 174 ,111동 101호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '982', '0282', 3)
2021-08-18 17:40:59,827 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,828 INFO sqlalchemy.engine.base.Engine ('구립초록나라어린이집', '권서연', '서울특별시 강북구 인수봉로14길 8 ,(미아동) (삼양동)', '02', '986', '6148', 3)
2021-08-18 17:40:59,829 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,831 INFO sqlalchemy.engine.base.Engine ('구립큰마을어린이집', '박정순', '서울특별시 강북구 도봉로31길 28 (송천동)', '02', '2138', '7781', 3)
2021-08-18 17:40:59,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,832 INFO sqlalchemy.engine.base.Engine ('구립토마토어린이집', '권준혁', '서울특별시 관악구 남부순환로248길 78 ,아이펠리스 101호 (인헌동)', '02', '886', '2696', 5)
2021-08-18 17:40:59,833 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,834 INFO sqlalchemy.engine.base.Engine ('구립해아래어린이집', '조현정', '서울특별시 강북구 오패산로30길 30 ,101동 108호 (송중동)', '02', '6061', '1003', 3)
2021-08-18 17:40:59,835 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,835 INFO sqlalchemy.engine.base.Engine ('구립현대가정어린이집', '안미숙', '서울특별시 관악구 관악로 304 ,현대아파트 118-102 (청림동)', '02', '6275', '3003', 5)
2021-08-18 17:40:59,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,838 INFO sqlalchemy.engine.base.Engine ('꼬마어린이집', '정지은', '서울특별시 노원구 동일로213길 21 ,107동 104호(상계동, 주공아파트) (상계6.7동)', '02', '935', '5942', 9)
2021-08-18 17:40:59,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,841 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '정정호', '서울특별시 성북구 북악산로 813 ,105-108 (정릉제1동)', '02', '943', '7386', 17)
2021-08-18 17:40:59,842 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,842 INFO sqlalchemy.engine.base.Engine ('꿈꾸리아이뜰어린이집', '서정순', '서울특별시 노원구 중계로 230 ,517동 103호(중계동, 주공아파트) (중계1동)', '02', '937', '7566', 9)
2021-08-18 17:40:59,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,844 INFO sqlalchemy.engine.base.Engine ('꿈동이어린이집', '최상훈', '서울특별시 동대문구 답십리로 130 ,108동 106호(답십리동,래미안위브) (답십리제1동)', '02', '2249', '9520', 11)
2021-08-18 17:40:59,844 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,845 INFO sqlalchemy.engine.base.Engine ('꿈사랑어린이집', '임민서', '서울특별시 성북구 종암로23길 35 ,202-102 (종암동)', '02', '6408', '3331', 17)
2021-08-18 17:40:59,846 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,847 INFO sqlalchemy.engine.base.Engine ('꿈이크는어린이집', '권성진', '서울특별시 마포구 망원로2길 14 ,102호 (망원제1동)', '02', '373', '3141', 13)
2021-08-18 17:40:59,848 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,853 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '서지훈', '서울특별시 성북구 서경로 31 ,104-103 (정릉제2동)', '02', '971', '3248', 17)
2021-08-18 17:40:59,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,855 INFO sqlalchemy.engine.base.Engine ('느티나무어린이집', '최지영', '서울특별시 동대문구 사가정로 65 ,201동 101호(전농동,래미안크레시티) (전농제1동)', '02', '2212', '3373', 11)
2021-08-18 17:40:59,856 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,857 INFO sqlalchemy.engine.base.Engine ('능동 꿈맞이어린이집', '임진호', '서울특별시 광진구 천호대로120길 32 (능동)', '02', '457', '7532', 6)
2021-08-18 17:40:59,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,858 INFO sqlalchemy.engine.base.Engine ('대림 어린이집', '강지영', '서울특별시 동대문구 한천로63길 10 ,115동 103호 (이문동, 이편한세상아파트) (이문제2동)', '02', '6212', '5414', 11)
2021-08-18 17:40:59,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,860 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '서준영', '서울특별시 마포구 상암산로1길 92 ,709동 1층 상암월드컵파크7단지 (상암동)', '02', '302', '5400', 13)
2021-08-18 17:40:59,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,863 INFO sqlalchemy.engine.base.Engine ('도봉1동새꿈 어린이집', '이수빈', '서울특별시 도봉구 도봉로169길 31 ,104동 104호(도봉동, 럭키아파트) (도봉제1동)', '02', '954', '0802', 10)
2021-08-18 17:40:59,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,865 INFO sqlalchemy.engine.base.Engine ('도봉1동엄마무릎어린이집', '이정호', '서울특별시 도봉구 시루봉로23나길 17 ,(도봉동) (도봉제1동)', '02', '3494', '4001', 10)
2021-08-18 17:40:59,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,867 INFO sqlalchemy.engine.base.Engine ('도봉2동도토리어린이집', '임미경', '서울특별시 도봉구 도봉로170길 40 ,103동 101호(도봉동, 래미안도봉아파트) (도봉제2동)', '02', '3494', '2234', 10)
2021-08-18 17:40:59,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,868 INFO sqlalchemy.engine.base.Engine ('도봉2동재롱이어린이집', '안성민', '서울특별시 도봉구 마들로 859-19 ,121동 101호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '954', '8237', 10)
2021-08-18 17:40:59,869 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,870 INFO sqlalchemy.engine.base.Engine ('도봉2동해솔어린이집', '윤혜진', '서울특별시 도봉구 마들로 859-19 ,103동 109호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '954', '2666', 10)

2021-08-18 17:40:59,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,872 INFO sqlalchemy.engine.base.Engine ('돈의문어린이집', '신은영', '서울특별시 서대문구 독립문로14길 33 ,돈의문 센트레빌 아파트 (천연동)', '02', '6396', '0112', 14)
2021-08-18 17:40:59,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,874 INFO sqlalchemy.engine.base.Engine ('라파엘엔젤어린이집', '신지민', '서울특별시 성북구 솔샘로24길 15 ,105동 102호(정릉동, 정릉E-편한세상아파트) (정릉제4동)', '02', '916', '9878', 17)
2021-08-18 17:40:59,875 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,876 INFO sqlalchemy.engine.base.Engine ('리틀삼성어린이집', '서정운', '서울특별시 마포구 서강로 95 ,104-102 (서강동)', '02', '3143', '1900', 13)
2021-08-18 17:40:59,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,878 INFO sqlalchemy.engine.base.Engine ('바다어린이집', '김지원', '서울특별시 성북구 북악산로 828 ,101-106 (정릉제1동)', '02', '942', '0279', 17)
2021-08-18 17:40:59,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,880 INFO sqlalchemy.engine.base.Engine ('반딧불어린이집', '전지은', '서울특별시 도봉구 덕릉로63가길 43 ,(창동, 대우아파트 내) (창제2동)', '02', '992', '5959', 10)
2021-08-18 17:40:59,883 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,886 INFO sqlalchemy.engine.base.Engine ('사랑가득어린이집', '강민석', '서울특별시 구로구 신도림로 87 ,103동 101호 (신도림동)', '02', '2689', '1342', 7)
2021-08-18 17:40:59,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,888 INFO sqlalchemy.engine.base.Engine ('사랑샘몬테소리어린이집', '전영식', '서울특별시 성북구 오패산로 46 ,106-108(하월곡동,두산위브아파트) (월곡제1동)', '02', '911', '8899', 17)
2021-08-18 17:40:59,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,889 INFO sqlalchemy.engine.base.Engine ('삼성키즈어린이집', '조영철', '서울특별시 마포구 만리재로 60 ,305동 104호(신공덕동 삼성래미안) (공덕동)', '02', '704', '2428', 13)
2021-08-18 17:40:59,890 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,891 INFO sqlalchemy.engine.base.Engine ('상암나래어린이집', '전상훈', '서울특별시 마포구 월드컵북로44길 40 (상암동)', '02', '374', '0402', 13)
2021-08-18 17:40:59,894 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,895 INFO sqlalchemy.engine.base.Engine ('샛별몬테소리어린이집', '강지민', '서울특별시 노원구 광운로 46 ,102동 104호(월계동, 대동아파트) (월계1동)', '02', '6221', '5243', 9)
2021-08-18 17:40:59,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,897 INFO sqlalchemy.engine.base.Engine ('서초구립 반포본동푸른어린이집', '최상훈', '서울특별시 서초구 신반포로 45 ,66동 102호(반포동, 주공아파트) (반포본동)', '02', '535', '9191', 15)
2021-08-18 17:40:59,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,898 INFO sqlalchemy.engine.base.Engine ('서초구립 서초4동삼풍어린이집', '강성수', '서울특별시 서초구 서초중앙로 200 ,5동, 103호(서초동, 삼풍아파트) (서초4동)', '02', '535', '0222', 15)
2021-08-18 17:40:59,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,904 INFO sqlalchemy.engine.base.Engine ('서초구립 에스티지하늘어린이집', '오준혁', '서울특별시 서초구 서운로 107 ,1층(서초2동, 래미안서초에스티지 아파트) (서초2동)', '02', '523', '0478', 15)
2021-08-18 17:40:59,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,906 INFO sqlalchemy.engine.base.Engine ('선경어린이집', '강준서', '서울특별시 성북구 종암로24가길 53 ,101-101 (종암동)', '02', '941', '4685', 17)
2021-08-18 17:40:59,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,908 INFO sqlalchemy.engine.base.Engine ('숲속푸른아이어린이집', '조지훈', '서울특별시 노원구 동일로215길 48 ,312동 103호(상계동, 주공아파트) (상계6.7동)', '02', '6316', '8084', 9)
2021-08-18 17:40:59,910 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,911 INFO sqlalchemy.engine.base.Engine ('쌍문4동사랑모아어린이집', '조정호', '서울특별시 도봉구 해등로 231 ,7동 101호(쌍문동, 한양2차아파트) (쌍문제4동)', '02', '908', '9642', 10)
2021-08-18 17:40:59,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,913 INFO sqlalchemy.engine.base.Engine ('쌍문4동푸른숲속어린이집', '장성수', '서울특별시 도봉구 해등로25길 41 ,701동 101호(쌍문동, 한양7차아파트) (쌍문제4동)', '02', '6227', '1453', 10)
2021-08-18 17:40:59,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,915 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '박정수', '서울특별시 영등포구 당산동4가 당산로41길 23 ,당산현대아파트 103동 105호 (당산제2동)', '02', '2068', '0011', 20)
2021-08-18 17:40:59,916 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,917 INFO sqlalchemy.engine.base.Engine ('예지슬어린이집', '이상철', '서울특별시 동대문구 사가정로 65 ,109동 101호(전농동, 래미안크레시티아파트) (전농제1동)', '02', '2246', '2226', 11)
2021-08-18 17:40:59,918 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,919 INFO sqlalchemy.engine.base.Engine ('우주어린이집', '한도현', '서울특별시 노원구 동일로227길 85 ,1115동101호(상계동,주공아파트) (상계8동)', '02', '935', '0108', 9)
2021-08-18 17:40:59,921 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,922 INFO sqlalchemy.engine.base.Engine ('원스쿨어린이집', '장정호', '서울특별시 광진구 아차산로69길 19 ,현대아파트 902동 104호 (광장동)', '02', '6451', '8801', 6)
2021-08-18 17:40:59,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,924 INFO sqlalchemy.engine.base.Engine ('은성어린이집', '서영철', '서울특별시 성북구 종암로24가길 80 ,106-104 (종암동)', '02', '909', '8514', 17)
2021-08-18 17:40:59,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,926 INFO sqlalchemy.engine.base.Engine ('자연샘어린이집', '한영진', '서울특별시 성북구 한천로101길 18 ,206-102 (장위제3동)', '02', '6404', '9145', 17)
2021-08-18 17:40:59,927 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,927 INFO sqlalchemy.engine.base.Engine ('작은꼬마어린이집', '김유진', '서울특별시 영등포구 여의대방로5길 6 ,우창아파트 1동 108호 (신길제6동)', '02', '833', '3044', 20)
2021-08-18 17:40:59,929 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,930 INFO sqlalchemy.engine.base.Engine ('재미나어린이집', '신정운', '서울특별시 노원구 동일로227길 25 ,1109동 101호(상계동, 주공아파트) (상계8동)', '02', '6232', '4656', 9)
2021-08-18 17:40:59,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,931 INFO sqlalchemy.engine.base.Engine ('좋은나무어린이집', '서준호', '서울특별시 마포구 월드컵북로47길 46 ,201동 105호 (상암동)', '02', '305', '1240', 13)
2021-08-18 17:40:59,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,934 INFO sqlalchemy.engine.base.Engine ('중곡1동 자람터어린이집', '전지훈', '서울특별시 광진구 긴고랑로8길 76 (중곡제1동)', '02', '469', '7942', 6)
2021-08-18 17:40:59,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,936 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '강은정', '서울특별시 영등포구 당산동4가 당산로41길 23 ,101동 102호 (당산제2동)', '02', '6269', '3939', 20)
2021-08-18 17:40:59,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,937 INFO sqlalchemy.engine.base.Engine ('참사랑어린이집', '송현정', '서울특별시 서대문구 이화여대8길 62 ,두산아파트 102동 106호 (북아현동)', '02', '6356', '6767', 14)
2021-08-18 17:40:59,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,939 INFO sqlalchemy.engine.base.Engine ('창4동디즈니어린이집', '전지훈', '서울특별시 도봉구 노해로70길 54 ,1907동 102호(창동, 상계주공19차아파트) (창제4동)', '02', '6228', '4991', 10)
2021-08-18 17:40:59,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,941 INFO sqlalchemy.engine.base.Engine ('창4동아이꿈터어린이집', '윤광수', '서울특별시 도봉구 마들로 551 ,113동 101호(창동, 쌍용아파트) (창제4동)', '02', '6223', '9600', 10)
2021-08-18 17:40:59,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,943 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '오유진', '서울특별시 구로구 개봉로20길 6 ,116동 101호 (개봉제2동)', '02', '2066', '2753', 7)
2021-08-18 17:40:59,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,945 INFO sqlalchemy.engine.base.Engine ('키즈맘어린이집', '장민수', '서울특별시 성북구 북악산로 844 ,101-105 (돈암제2동)', '02', '953', '6369', 17)
2021-08-18 17:40:59,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,947 INFO sqlalchemy.engine.base.Engine ('하늘채어린이집', '장영철', '서울특별시 성북구 한천로 509 ,104-101 (석관동)', '02', '969', '8586', 17)
2021-08-18 17:40:59,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,948 INFO sqlalchemy.engine.base.Engine ('학여울어린이집', '김민지', '서울특별시 노원구 동일로207길 186 ,107동101호(하계동, 학여울청구아파트) (하계2동)', '02', '971', '2224', 9)
2021-08-18 17:40:59,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,955 INFO sqlalchemy.engine.base.Engine ('한사랑어린이집', '류준호', '서울특별시 구로구 개봉로3길 87 ,110동 103호 (개봉제3동)', '02', '6741', '2270', 7)
2021-08-18 17:40:59,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,956 INFO sqlalchemy.engine.base.Engine ('햇님달님어린이집', '전준호', '서울특별시 노원구 덕릉로118길 29 ,104동 108호(상계동, 불암현대아파트) (상계3.4동)', '02', '937', '0862', 9)
2021-08-18 17:40:59,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,958 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '류은경', '서울특별시 마포구 망원로11길 35 ,101호 (망원제2동)', '02', '322', '9590', 13)
2021-08-18 17:40:59,959 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,960 INFO sqlalchemy.engine.base.Engine ('행복어린이집', '송영철', '서울특별시 마포구 성암로 28 (성산제2동)', '02', '3152', '9349', 13)
2021-08-18 17:40:59,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,961 INFO sqlalchemy.engine.base.Engine ('행복열매어린이집', '서준혁', '서울특별시 서대문구 증가로 191 ,101동 101호 (남가좌제2동)', '02', '6010', '7258', 14)
2021-08-18 17:40:59,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,963 INFO sqlalchemy.engine.base.Engine ('행복한아이어린이집', '권정식', '서울특별시 구로구 개봉로20길 6 ,105동 103호(개봉동, 현대아파트) (개봉제2동)', '02', '2616', '2473', 7)
2021-08-18 17:40:59,964 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,965 INFO sqlalchemy.engine.base.Engine ('현대아이사랑어린이집', '오경자', '서울특별시 서대문구 통일로39가길 57 ,107동 108호 (홍제제1동)', '02', '394', '7701', 14)
2021-08-18 17:40:59,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,967 INFO sqlalchemy.engine.base.Engine ('혜연어린이집', '임상훈', '서울특별시 성북구 종암로24가길 53 ,104-107 (종암동)', '02', '941', '4006', 17)
2021-08-18 17:40:59,968 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,971 INFO sqlalchemy.engine.base.Engine ('호수어린이집', '박정식', '서울특별시 동대문구 답십리로 130 ,403동 106호(답십리동, 래미안위브) (답십리제1동)', '02', '2214', '2230', 11)
2021-08-18 17:40:59,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,974 INFO sqlalchemy.engine.base.Engine ('휴먼시아어린이집', '정정자', '서울특별시 광진구 천호대로 716 ,102동 102호(구의동, 휴먼시아아파트) (구의제2동)', '02', '456', '9709', 6)
2021-08-18 17:40:59,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,976 INFO sqlalchemy.engine.base.Engine ('사랑가득어린이집', '전민석', '서울특별시 강동구 아리수로50길 50 ,122동 203호(래미안힐스테이트 고덕) (고덕제1동)', '02', '442', '2112', 2)
2021-08-18 17:40:59,977 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,980 INFO sqlalchemy.engine.base.Engine ('신한 신이한이양천 어린이집', '박영길', '서울특별시 양천구 목동동로 10 ,상가A동 126호 (신정7동)', '02', '2648', '7060', 19)
2021-08-18 17:40:59,986 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,987 INFO sqlalchemy.engine.base.Engine ('해군바다마을어린이집', '이영환', '서울특별시 영등포구 가마산로 540 (신길제7동)', '02', '834', '7004', 20)
2021-08-18 17:40:59,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,995 INFO sqlalchemy.engine.base.Engine ('신도어린이집', '안서연', '서울특별시 성동구 성수동2가 성수이로24길 3 (성수2가3동)', '02', '462', '2468', 16)
2021-08-18 17:40:59,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:40:59,997 INFO sqlalchemy.engine.base.Engine ('구립별하어린이집', '김준호', '서울특별시 강동구 상암로 11 ,110동 105호(암사동, 선사현대아파트) (암사제2동)', '02', '429', '5558', 2)
2021-08-18 17:40:59,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:40:59,998 INFO sqlalchemy.engine.base.Engine ('동부법원어린이집', '안정웅', '서울특별시 송파구 법원로 101 ,서울동부지방법원 2층 (문정2동)', '02', '2204', '2911', 18)
2021-08-18 17:40:59,999 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,000 INFO sqlalchemy.engine.base.Engine ('구립색종이어린이집', '황상훈', '서울특별시 강동구 강동대로53길 66 ,102호(성내동, 한솔애리즈5차) (성내제3동)', '02', '479', '0003', 2)
2021-08-18 17:41:00,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,004 INFO sqlalchemy.engine.base.Engine ('새아어린이집', '권영숙', '서울특별시 강동구 아리수로50길 50 ,123동 212호(래미안힐스테이트아파트 고덕) (고덕제1동)', '02', '442', '3321', 2)
2021-08-18 17:41:00,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,007 INFO sqlalchemy.engine.base.Engine ('신한신이한이송파어린이집', '신준서', '서울특별시 송파구 중대로 68 ,2층 (문정2동)', '02', '404', '7060', 18)
2021-08-18 17:41:00,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,011 INFO sqlalchemy.engine.base.Engine ('구립남서울힐스테이트어린이집', '장준호', '서울특별시 금천구 시흥대로 165 ,남서울힐스테이트아파트 커뮤니티센터 (시흥제1동)', '02', '852', '2345', 8)
2021-08-18 17:41:00,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,015 INFO sqlalchemy.engine.base.Engine ('구립토리어린이집', '안준호', '서울특별시 강동구 상일로 74 ,323-102(상일동, 고덕리엔파크아파트 3단지) (상일제2동)', '02', '427', '7079', 2)
2021-08-18 17:41:00,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,017 INFO sqlalchemy.engine.base.Engine ('구립 누리봄어린이집', '정지은', '서울특별시 양천구 중앙로29길 61 ,신정뉴타운 롯데캐슬 관리동 1층 (신월2동)', '02', '2065', '9411', 19)
2021-08-18 17:41:00,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,019 INFO sqlalchemy.engine.base.Engine ('구립 연두어린이집', '송영일', '서울특별시 양천구 중앙로36길 15 (신정1동)', '070', '4961', '5695', 19)
2021-08-18 17:41:00,020 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,021 INFO sqlalchemy.engine.base.Engine ('구립키움어린이집', '류영철', '서울특별시 동작구 매봉로 123 ,104동 101호 (노량진제1동)', '02', '2135', '6663', 12)
2021-08-18 17:41:00,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,023 INFO sqlalchemy.engine.base.Engine ('이든어린이집', '최민수', '서울특별시 영등포구 양평동4가 양평로17길 36 ,1동 110호 (양평제2동)', '02', '2676', '5422', 20)
2021-08-18 17:41:00,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,026 INFO sqlalchemy.engine.base.Engine ('한국쓰리엠어린이집', '황병철', '서울특별시 영등포구 의사당대로 82 ,하나금융투자빌딩 2층 (여의동)', '02', '761', '6981', 20)
2021-08-18 17:41:00,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,029 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '정유진', '서울특별시 금천구 벚꽃로 40 ,111동 105호 (독산제1동)', '02', '804', '7979', 8)
2021-08-18 17:41:00,030 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,031 INFO sqlalchemy.engine.base.Engine ('구립 극동미라주어린이집', '서지은', '서울특별시 성동구 난계로 73 ,101동 110호(하왕십리동, 극동미라주 아파트) (왕십리제2동)', '02', '2295', '4002', 16)
2021-08-18 17:41:00,032 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,032 INFO sqlalchemy.engine.base.Engine ('구립 센트라스나래어린이집', '안정순', '서울특별시 성동구 왕십리로 410 ,하왕십리동, 123동 (왕십리도선동)', '02', '2291', '2017', 16)
2021-08-18 17:41:00,034 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,034 INFO sqlalchemy.engine.base.Engine ('구립 센트라스라온어린이집', '윤정호', '서울특별시 성동구 왕십리로 410 ,129동(하왕십리동, 센트라스) (왕십리도선동)', '02', '2296', '3002', 16)
2021-08-18 17:41:00,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,037 INFO sqlalchemy.engine.base.Engine ('구립 센트라스아띠어린이집', '정영진', '서울특별시 성동구 왕십리로 410 ,하왕십리동, 센트라스 101동 (왕십리도선동)', '02', '2292', '2295', 16)
2021-08-18 17:41:00,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,040 INFO sqlalchemy.engine.base.Engine ('구립 센트라스으뜸어린이집', '임민석', '서울특별시 성동구 왕십리로 410 ,하왕십리동, 센트라스 128동 (왕십리도선동)', '02', '2282', '4650', 16)
2021-08-18 17:41:00,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,042 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '이민서', '서울특별시 서대문구 북아현로1길 50 ,103동 1층 (북아현동)', '02', '312', '1255', 14)
2021-08-18 17:41:00,044 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,045 INFO sqlalchemy.engine.base.Engine ('구립길동어린이집', '김정수', '서울특별시 강동구 명일로 238 (길동)', '02', '489', '5434', 2)
2021-08-18 17:41:00,046 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,047 INFO sqlalchemy.engine.base.Engine ('햇살아래 보듬이나눔이 어린이집', '신정남', '서울특별시 중랑구 신내역로 131 ,신내동 170-3(신내3지구) (신내1동)', '02', '3423', '0150', 25)
2021-08-18 17:41:00,048 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,048 INFO sqlalchemy.engine.base.Engine ('구립보라매어린이집', '류종수', '서울특별시 관악구 당곡6길 63 (보라매동)', '02', '889', '6004', 5)
2021-08-18 17:41:00,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,050 INFO sqlalchemy.engine.base.Engine ('구립사당빛나어린이집', '황영길', '서울특별시 동작구 동작대로29길 118 (사당제2동)', '02', '845', '6545', 12)
2021-08-18 17:41:00,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,051 INFO sqlalchemy.engine.base.Engine ('구립아람어린이집', '황은영', '서울특별시 금천구 벚꽃로 40 ,롯데캐슬골드파크1차아파트 내 (독산제1동)', '02', '894', '8009', 8)
2021-08-18 17:41:00,052 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,053 INFO sqlalchemy.engine.base.Engine ('구립아람어린이집', '김영진', '서울특별시 동작구 상도로30길 40 ,두산위브트레지움아파트 203동 204호 (상도제2동)', '02', '822', '8620', 12)
2021-08-18 17:41:00,054 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,054 INFO sqlalchemy.engine.base.Engine ('구립아람어린이집', '임은영', '서울특별시 관악구 관악로 229-12 (중앙동)', '02', '877', '8112', 5)
2021-08-18 17:41:00,057 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,058 INFO sqlalchemy.engine.base.Engine ('구립용꿈어린이집', '강유진', '서울특별시 관악구 신림로58길 68 (서원동)', '02', '877', '4587', 5)
2021-08-18 17:41:00,059 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,060 INFO sqlalchemy.engine.base.Engine ('구립초롱별어린이집', '이성호', '서울특별시 관악구 난곡로45길 5 (미성동)', '02', '855', '0771', 5)
2021-08-18 17:41:00,062 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,063 INFO sqlalchemy.engine.base.Engine ('구립행운어린이집', '신예은', '서울특별시 관악구 행운1라길 9 (행운동)', '02', '877', '4234', 5)
2021-08-18 17:41:00,064 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,065 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '정병철', '서울특별시 중구 동호로10길 30 ,103동 101호(신당동, 약수하이츠) (청구동)', '02', '2236', '9121', 24)
2021-08-18 17:41:00,066 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,067 INFO sqlalchemy.engine.base.Engine ('서초구립 아크로달어린이집', '정정웅', '서울특별시 서초구 신반포로15길 19 ,104동 (아크로리버파크아파트, 반포동) (반포2동)', '02', '537', '3940', 15)
2021-08-18 17:41:00,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,069 INFO sqlalchemy.engine.base.Engine ('어울림어린이집', '한정자', '서울특별시 중랑구 망우로73길 47 (망우본동)', '02', '496', '9497', 25)
2021-08-18 17:41:00,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,072 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '김영철', '서울특별시 구로구 천왕로 56 ,313동 104호(천왕동,천왕이펜하우스3단지) (오류제2동)', '02', '6448', '5700', 7)
2021-08-18 17:41:00,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,074 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '안민재', '서울특별시 종로구 낙산길 198 ,205-101 (창신제3동)', '02', '3674', '1004', 23)
2021-08-18 17:41:00,075 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,076 INFO sqlalchemy.engine.base.Engine ('푸르뫼어린이집', '임도현', '서울특별시 구로구 고척로 82 ,201동 103호(개봉동, 거성푸르뫼2차아파트) (개봉제1동)', '02', '2618', '8736', 7)
2021-08-18 17:41:00,077 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,078 INFO sqlalchemy.engine.base.Engine ('해피벨어린이집', '박종수', '서울특별시 구로구 신도림로 32 ,702동 101호 (신도림동)', '02', '2678', '1614', 7)
2021-08-18 17:41:00,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,079 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '서상훈', '서울특별시 영등포구 당산동6가 당산로50길 29 (당산제2동)', '02', '2675', '5657', 20)
2021-08-18 17:41:00,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,081 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '서건우', '서울특별시 송파구 송파대로 567 ,522동 106호 (잠실3동)', '02', '6140', '1166', 18)
2021-08-18 17:41:00,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,082 INFO sqlalchemy.engine.base.Engine ('위례아이파크어린이집', '임성호', '서울특별시 송파구 위례광장로 136 ,103동 1층(장지동, 위례아이파크) (위례동)', '02', '406', '6545', 18)
2021-08-18 17:41:00,083 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,084 INFO sqlalchemy.engine.base.Engine ('롯데mom편한어린이집', '김예은', '서울특별시 구로구 구일로8길 31 ,102동 105호(구로동,구로우성아파트) (구로제1동)', '02', '6737', '1722', 7)
2021-08-18 17:41:00,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,085 INFO sqlalchemy.engine.base.Engine ('구립 꽃빛나라어린이집', '권지혜', '서울특별시 은평구 진관3로 67 ,구파발래미안 9-1단지 908동 (진관동)', '02', '357', '3004', 22)
2021-08-18 17:41:00,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,087 INFO sqlalchemy.engine.base.Engine ('구립 백련산힐2차어린이집', '권영철', '서울특별시 은평구 백련산로 38 ,관리동(백련산힐스테이트2차아파트) (응암제2동)', '02', '305', '8558', 22)
2021-08-18 17:41:00,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,089 INFO sqlalchemy.engine.base.Engine ('리센츠어린이집', '이민석', '서울특별시 송파구 올림픽로 135 ,215동 101호(잠실동, 리센츠) (잠실2동)', '02', '417', '3033', 18)
2021-08-18 17:41:00,090 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,091 INFO sqlalchemy.engine.base.Engine ('문정2동어린이집', '김정수', '서울특별시 송파구 중대로 24 ,307동 104호(문정동, 올림픽훼밀리타운) (문정2동)', '02', '430', '2211', 18)
2021-08-18 17:41:00,093 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,094 INFO sqlalchemy.engine.base.Engine ('잠실엘스어린이집', '조은경', '서울특별시 송파구 올림픽로 99 ,101동 104호 (잠실2동)', '02', '423', '0547', 18)
2021-08-18 17:41:00,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,096 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '김수빈', '서울특별시 성동구 왕십리로 410 ,118동 102호(하왕십리동, 센트라스) (왕십리도선동)', '02', '6015', '1166', 16)
2021-08-18 17:41:00,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,098 INFO sqlalchemy.engine.base.Engine ('구립해나어린이집', '오준호', '서울특별시 강동구 아리수로 46-14 (암사제3동)', '02', '441', '3340', 2)
2021-08-18 17:41:00,100 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,101 INFO sqlalchemy.engine.base.Engine ('구립 사랑가득어린이집', '임도현', '서울특별시 은평구 진흥로 267 ,102-103 (불광제1동)', '02', '352', '7088', 22)
2021-08-18 17:41:00,102 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,104 INFO sqlalchemy.engine.base.Engine ('구립 사랑샘어린이집', '류광수', '서울특별시 은평구 갈현로29길 62 ,102-104 (갈현제1동)', '02', '358', '5720', 22)
2021-08-18 17:41:00,105 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,106 INFO sqlalchemy.engine.base.Engine ('구립 으뜸어린이집', '류종수', '서울특별시 은평구 서오릉로 94 ,102-101 (대조동)', '02', '386', '8152', 22)
2021-08-18 17:41:00,107 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,108 INFO sqlalchemy.engine.base.Engine ('구립마루어린이집', '강지훈', '서울특별시 관악구 은천로 93 ,벽산블루밍아파트 202동 203동 사이 (은천동)', '02', '883', '9900', 5)
2021-08-18 17:41:00,109 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,110 INFO sqlalchemy.engine.base.Engine ('노원연두어린이집', '한민서', '서울특별시 노원구 덕릉로70가길 21 ,중계센트럴파크아파트 내 보육시설 (상계6.7동)', '02', '930', '7877', 9)
2021-08-18 17:41:00,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,112 INFO sqlalchemy.engine.base.Engine ('구립 조은어린이집', '권준혁', '서울특별시 양천구 신정로14길 6 ,,103동102호(신정동,학마을어린이집) (신정3동)', '02', '6734', '1970', 19)
2021-08-18 17:41:00,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,114 INFO sqlalchemy.engine.base.Engine ('구립 해맞이어린이집', '신영진', '서울특별시 양천구 지양로5길 15 (신월7동)', '02', '2699', '7194', 19)
2021-08-18 17:41:00,116 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,117 INFO sqlalchemy.engine.base.Engine ('구립 해와별어린이집', '한민지', '서울특별시 양천구 신정로7길 60-7 ,,406동101호(신정동,푸른마을아파트) (신정3동)', '02', '2060', '3452', 19)
2021-08-18 17:41:00,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,119 INFO sqlalchemy.engine.base.Engine ('구립꼬꼬어린이집', '전병철', '서울특별시 금천구 가산로 99 ,107동 102호(가산동, 두산아파트) (가산동)', '02', '864', '5563', 8)
2021-08-18 17:41:00,120 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,121 INFO sqlalchemy.engine.base.Engine ('구립늘채움어린이집', '임혜진', '서울특별시 금천구 금하로 750 ,106동 102호(시흥동, 관악우방아파트) (시흥제2동)', '02', '896', '3004', 8)
2021-08-18 17:41:00,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,124 INFO sqlalchemy.engine.base.Engine ('구립별솔어린이집', '권준혁', '서울특별시 금천구 한내로 62 ,4동 104호(독산한신아파트,독산제1동) (독산제1동)', '02', '6672', '8810', 8)
2021-08-18 17:41:00,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,125 INFO sqlalchemy.engine.base.Engine ('구립싱글벙글어린이집', '송영진', '서울특별시 금천구 독산로64나길 1 ,행복타운102호 (독산동) (독산제2동)', '02', '807', '8905', 8)
2021-08-18 17:41:00,126 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,127 INFO sqlalchemy.engine.base.Engine ('구립예담어린이집', '장수빈', '서울특별시 금천구 범안로 1136 ,103동 104호(독산동, 중앙하이츠아파트) (독산제1동)', '02', '857', '5012', 8)
2021-08-18 17:41:00,129 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,130 INFO sqlalchemy.engine.base.Engine ('구립화목한어린이집', '최영철', '서울특별시 금천구 독산로10길 96 ,1동 110호(시흥동, 남서울건영2차아파트) (시흥제5동)', '070', '7524', '6391', 8)
2021-08-18 17:41:00,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,133 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '최진호', '서울특별시 구로구 구일로8길 143 (구로제1동)', '02', '830', '0161', 7)
2021-08-18 17:41:00,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,136 INFO sqlalchemy.engine.base.Engine ('아라어린이집', '윤지혜', '서울특별시 동대문구 장한로14길 81 ,106동 104호 (장안동, 삼성래미안1차아파트) (장안제1동)', '02', '6071', '0012', 11)
2021-08-18 17:41:00,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,138 INFO sqlalchemy.engine.base.Engine ('KIST숲속 어린이집', '한경회', '서울특별시 성북구 화랑로14길 5 ,. (월곡제2동)', '02', '958', '7051', 17)
2021-08-18 17:41:00,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,140 INFO sqlalchemy.engine.base.Engine ('신한신이한이강북어린이집', '오준호', '서울특별시 강북구 도봉로 364 ,강북금융센터 3층 (번1동)', '02', '900', '7060', 3)
2021-08-18 17:41:00,141 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,142 INFO sqlalchemy.engine.base.Engine ('구립래미안힐스테이트어린이집', '신정호', '서울특별시 강동구 아리수로50길 50 ,관리동 (고덕제1동)', '02', '427', '3166', 2)
2021-08-18 17:41:00,143 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,145 INFO sqlalchemy.engine.base.Engine ('구립 신정숲속마을어린이집', '윤지은', '서울특별시 양천구 신정로 110 (신정3동)', '02', '2613', '2233', 19)
2021-08-18 17:41:00,147 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,148 INFO sqlalchemy.engine.base.Engine ('구립해솔어린이집', '오정호', '서울특별시 강북구 한천로105길 23 ,108동 103호(번동, 주공1단지아파트) (번3동)', '02', '981', '5498', 3)
2021-08-18 17:41:00,149 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,151 INFO sqlalchemy.engine.base.Engine ('마곡10 별솔어린이집', '송미숙', '서울특별시 강서구 마곡중앙1로 72 ,1012동 1층(마곡동, 마곡엠밸리10단지) (공항동)', '02', '6964', '6630', 4)
2021-08-18 17:41:00,152 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,153 INFO sqlalchemy.engine.base.Engine ('마곡11 나무햇살어린이집', '전영철', '서울특별시 강서구 공항대로 124 ,1103동 1층(마곡동,마곡엠밸리11단지) (공항동)', '02', '6958', '7701', 4)
2021-08-18 17:41:00,154 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,155 INFO sqlalchemy.engine.base.Engine ('마곡12 온새미어린이집', '장성수', '서울특별시 강서구 공항대로 140 ,1205동 1층(마곡동, 마곡엠밸리 12단지) (공항동)', '02', '2088', '1722', 4)
2021-08-18 17:41:00,156 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,157 INFO sqlalchemy.engine.base.Engine ('마곡8 열린숲어린이집', '윤예준', '서울특별시 강서구 마곡서1로 81 ,807동 1층(마곡동, 마곡엠밸리8단지) (방화제1동)', '02', '2039', '8301', 4)
2021-08-18 17:41:00,158 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,159 INFO sqlalchemy.engine.base.Engine ('서초구립 아크로별어린이집', '한정수', '서울특별시 서초구 신반포로15길 19 ,100동(반포동, 아크로리버파크) (반포2동)', '02', '3478', '1442', 15)
2021-08-18 17:41:00,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,161 INFO sqlalchemy.engine.base.Engine ('서초구립 아크로해어린이집', '안정운', '서울특별시 서초구 신반포로15길 19 ,106동 1층(반포동, 아크로리버파크) (반포2동)', '02', '3478', '0542', 15)
2021-08-18 17:41:00,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,163 INFO sqlalchemy.engine.base.Engine ('서초구립 잠원햇살어린이집', '이현정', '서울특별시 서초구 잠원로8길 25 ,1층 (잠원동, 래미안신반포팰리스) (잠원동)', '02', '536', '8725', 15)

2021-08-18 17:41:00,164 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,165 INFO sqlalchemy.engine.base.Engine ('동원어린이집', '권민서', '서울특별시 강남구 개포로15길 29 (개포4동)', '02', '2058', '2190', 1)
2021-08-18 17:41:00,166 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,167 INFO sqlalchemy.engine.base.Engine ('주빌리어린이집', '정영진', '서울특별시 송파구 올림픽로 417 ,1층 (잠실4동)', '02', '417', '6004', 18)
2021-08-18 17:41:00,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,170 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '임영철', '서울특별시 강서구 마곡중앙1로 72 ,1018동 101호(마곡동, 마곡엠밸리10단지) (공항동)', '02', '6398', '7839', 4)
2021-08-18 17:41:00,171 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,172 INFO sqlalchemy.engine.base.Engine ('꿈보어린이집', '임상철', '서울특별시 중랑구 신내로 110 ,12동102호(신내동,동성아파트) (신내1동)', '070', '4062', '7600', 25)
2021-08-18 17:41:00,173 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,174 INFO sqlalchemy.engine.base.Engine ('SeoulTech어린이집', '류예은', '서울특별시 노원구 공릉로 232 ,서울과학기술대학교 내 (공릉2동)', '02', '972', '1156', 9)
2021-08-18 17:41:00,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,176 INFO sqlalchemy.engine.base.Engine ('다림 어린이집', '오정호', '서울특별시 도봉구 덕릉로60길 164-13 ,101동 101호(창동, 한승 미메이드 아파트) (창제3동)', '02', '905', '9429', 10)
2021-08-18 17:41:00,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,179 INFO sqlalchemy.engine.base.Engine ('구립엄마품어린이집', '황은정', '서울특별시 강동구 진황도로 212 ,둔촌신성미소지움 202동 103호 (둔촌제2동)', '02', '812', '6551', 2)
2021-08-18 17:41:00,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,181 INFO sqlalchemy.engine.base.Engine ('샘물어린이집', '오민석', '서울특별시 용산구 원효로4가 원효로19길 49 (원효로제2동)', '02', '701', '0505', 21)
2021-08-18 17:41:00,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,183 INFO sqlalchemy.engine.base.Engine ('유진어린이집', '최수빈', '서울특별시 중랑구 중랑천로 332 ,102동 106호(묵동, 한국아파트) (묵제2동)', '02', '976', '9066', 25)
2021-08-18 17:41:00,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,185 INFO sqlalchemy.engine.base.Engine ('미소어린이집', '서성진', '서울특별시 강서구 마곡서1로 81 ,804동 103호(마곡동, 마곡엠벨리 8단지) (방화제1동)', '02', '6448', '9984', 4)
2021-08-18 17:41:00,186 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,187 INFO sqlalchemy.engine.base.Engine ('한섬아이어린이집', '류병철', '서울특별시 강남구 언주로 808 ,2,3층(신사동, 유성빌딩) (압구정동)', '02', '540', '1114', 1)
2021-08-18 17:41:00,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,189 INFO sqlalchemy.engine.base.Engine ('문래자이어린이집', '김정운', '서울특별시 영등포구 문래동3가 당산로4길 12 ,관리동 (문래동)', '02', '2069', '4512', 20)
2021-08-18 17:41:00,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,191 INFO sqlalchemy.engine.base.Engine ('양평 병아리 어린이집', '신정수', '서울특별시 영등포구 양평동1가 영등포로11길 18 (양평제1동)', '02', '6015', '0579', 20)
2021-08-18 17:41:00,192 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,193 INFO sqlalchemy.engine.base.Engine ('중앙대학교어린이집', '신영진', '서울특별시 동작구 흑석로 84 ,중앙대학교 307관 1층 (흑석동)', '02', '881', '7395', 12)
2021-08-18 17:41:00,194 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,195 INFO sqlalchemy.engine.base.Engine ('구립 옥수파크어린이집', '윤성호', '서울특별시 성동구 매봉길 50 ,110동 (옥수동, 옥수파크힐스 1단지) (옥수동)', '02', '2282', '3241', 16)
2021-08-18 17:41:00,196 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,198 INFO sqlalchemy.engine.base.Engine ('구립 옥수힐스어린이집', '장서연', '서울특별시 성동구 매봉길 50 ,(옥수동, 옥수파크힐스 2단지) (옥수동)', '02', '2281', '7979', 16)
2021-08-18 17:41:00,199 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,199 INFO sqlalchemy.engine.base.Engine ('대치팰리스어린이집', '황지영', '서울특별시 강남구 삼성로51길 37 ,래미안대치팰리스 1단지 관리동 (대치제1동)', '02', '3482', '4361', 1)
2021-08-18 17:41:00,201 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,201 INFO sqlalchemy.engine.base.Engine ('아이앤어린이집', '오은영', '서울특별시 강남구 봉은사로68길 35-2 (삼성2동)', '02', '6203', '5425', 1)
2021-08-18 17:41:00,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,203 INFO sqlalchemy.engine.base.Engine ('한숲어린이집', '박도현', '서울특별시 종로구 통일로 134 ,디타워 돈의문 2층 (교남동)', '02', '735', '1712', 23)
2021-08-18 17:41:00,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,205 INFO sqlalchemy.engine.base.Engine ('고려대학교 서울캠퍼스 어린이집', '이정자', '서울특별시 성북구 안암동5가 안암로 145 ,안암동 5가 산 1-92번지 (안암동)', '02', '3290', '1793', 17)
2021-08-18 17:41:00,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,207 INFO sqlalchemy.engine.base.Engine ('구립 늘사랑어린이집', '오준혁', '서울특별시 강서구 등촌로 163 ,102동 102호(등촌동, 등촌아이파크) (등촌제2동)', '02', '2658', '1342', 4)
2021-08-18 17:41:00,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,209 INFO sqlalchemy.engine.base.Engine ('구립 드보라어린이집', '서도현', '서울특별시 강서구 강서로47길 63 ,103호(내발산동, 예스빌) (발산제1동)', '02', '2666', '5300', 4)
2021-08-18 17:41:00,210 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,211 INFO sqlalchemy.engine.base.Engine ('구립 보솜어린이집', '황동현', '서울특별시 강서구 공항대로43길 39 ,1106동 1층 6호 (등촌제3동)', '02', '2658', '0223', 4)
2021-08-18 17:41:00,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,213 INFO sqlalchemy.engine.base.Engine ('구립 뽄다어린이집', '김정웅', '서울특별시 강서구 강서로17라길 7-8 ,(화곡동) (화곡제1동)', '02', '2648', '0148', 4)
2021-08-18 17:41:00,214 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,215 INFO sqlalchemy.engine.base.Engine ('구립 사랑의몬테소리어린이집', '윤예준', '서울특별시 양천구 목동중앙남로 10 ,신목아파트 101동 108호 (목4동)', '02', '2647', '9853', 19)
2021-08-18 17:41:00,216 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,217 INFO sqlalchemy.engine.base.Engine ('구립 새싹어린이집', '신정호', '서울특별시 양천구 목동동로 130 ,1423동 101호(신정6동, 목동아파트) (신정6동)', '02', '2647', '2056', 19)
2021-08-18 17:41:00,218 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,219 INFO sqlalchemy.engine.base.Engine ('구립 소은어린이집', '서서연', '서울특별시 강서구 양천로67길 77 ,104동 101호(염창동, 우성1차아파트) (염창동)', '02', '3661', '6494', 4)
2021-08-18 17:41:00,220 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,221 INFO sqlalchemy.engine.base.Engine ('구립 코아루어린이집', '송영철', '서울특별시 양천구 남부순환로56길 9 ,코아루아파트 103동 104호(신월3동) (신월3동)', '02', '2601', '2783', 19)
2021-08-18 17:41:00,222 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,223 INFO sqlalchemy.engine.base.Engine ('구립 태진한솔어린이집', '윤진호', '서울특별시 강서구 공항대로71길 54 ,103동 101호(염창동, 태진한솔아파트) (염창동)', '02', '6091', '2279', 4)
2021-08-18 17:41:00,224 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,225 INFO sqlalchemy.engine.base.Engine ('꿈드림 어린이집', '전정남', '서울특별시 강남구 선릉로 221 ,402동 103호 (도곡동, 도곡렉슬아파트) (도곡제2동)', '02', '576', '9645', 1)
2021-08-18 17:41:00,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,227 INFO sqlalchemy.engine.base.Engine ('남서울어린이집', '최병철', '서울특별시 영등포구 버드나루로14가길 35 (당산제2동)', '02', '2068', '3466', 20)
2021-08-18 17:41:00,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,229 INFO sqlalchemy.engine.base.Engine ('서초구립 아람어린이집', '조정웅', '서울특별시 서초구 태봉로2길 5 ,505동 1층(우면동, 서초네이처힐5단지) (양재1동)', '02', '3461', '7942', 15)
2021-08-18 17:41:00,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,235 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '신은경', '서울특별시 구로구 경인로 382 ,102동 101호(개봉동, 한마을아파트) (개봉제1동)', '02', '2060', '8733', 7)
2021-08-18 17:41:00,236 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,237 INFO sqlalchemy.engine.base.Engine ('자람어린이집', '윤준호', '서울특별시 중랑구 사가정로71길 11 ,101동 101호(면목동, 용마2차한신아파트) (면목제3.8동)', '02', '435', '6806', 25)
2021-08-18 17:41:00,238 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,243 INFO sqlalchemy.engine.base.Engine ('키즈윌어린이집', '오종수', '서울특별시 동대문구 답십리로23나길 9 ,(전농동) (전농제1동)', '02', '2215', '7942', 11)
2021-08-18 17:41:00,245 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,246 INFO sqlalchemy.engine.base.Engine ('영등포경찰서어린이집', '장현정', '서울특별시 영등포구 양평동6가 양평로28라길 9 (양평제2동)', '02', '3667', '0209', 20)
2021-08-18 17:41:00,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,248 INFO sqlalchemy.engine.base.Engine ('서울경찰청어린이집', '안영자', '서울특별시 종로구 사직로8길 31 (사직동)', '02', '720', '8502', 23)
2021-08-18 17:41:00,249 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,250 INFO sqlalchemy.engine.base.Engine ('우리은행어린이집', '안은정', '서울특별시 중구 회현동1가 소공로 51 (회현동)', '02', '2002', '3095', 24)
2021-08-18 17:41:00,251 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,251 INFO sqlalchemy.engine.base.Engine ('홈플러스어린이집', '권은영', '서울특별시 강서구 화곡로 398 ,1층(등촌동, 홈플러스 강서점 앤 본사사옥) (등촌제1동)', '070', '4727', '8805', 4)
2021-08-18 17:41:00,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,253 INFO sqlalchemy.engine.base.Engine ('건이강이어린이집', '오정호', '서울특별시 영등포구 당산동6가 당산로 238 (당산제2동)', '02', '2632', '4100', 20)
2021-08-18 17:41:00,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,255 INFO sqlalchemy.engine.base.Engine ('구립 목3동어린이집', '임영일', '서울특별시 양천구 목동중앙남로3가길 92 (목3동)', '02', '2646', '5755', 19)
2021-08-18 17:41:00,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,257 INFO sqlalchemy.engine.base.Engine ('아이온어린이집', '송상훈', '서울특별시 영등포구 가마산로 442 ,104동 104호(신길동, 래미안영등포 프레비뉴아파트) (신길제3동)', '02', '846', '7771', 20)
2021-08-18 17:41:00,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,259 INFO sqlalchemy.engine.base.Engine ('롯데mom편한월드점어린이집', '권준호', '서울특별시 송파구 올림픽로 240 ,롯데월드 240 WB(3호) (잠실3동)', '02', '2143', '1460', 18)
2021-08-18 17:41:00,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,261 INFO sqlalchemy.engine.base.Engine ('아이행복어린이집', '한준혁', '서울특별시 영등포구 양평동2가 선유서로 67 (양평제1동)', '02', '2678', '1900', 20)
2021-08-18 17:41:00,263 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,264 INFO sqlalchemy.engine.base.Engine ('마곡 이화어린이집', '정정웅', '서울특별시 강서구 마곡중앙3로 74 ,관리동 1층(마곡동,마곡힐스테이트) (방화제1동)', '02', '2663', '7171', 4)
2021-08-18 17:41:00,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,266 INFO sqlalchemy.engine.base.Engine ('미즈메디어린이집', '김종수', '서울특별시 강서구 우장산로4길 25 ,1004동 1층 101호 (우장산동)', '02', '2659', '1419', 4)
2021-08-18 17:41:00,267 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,268 INFO sqlalchemy.engine.base.Engine ('구립무지개어린이집', '정지훈', '서울특별시 관악구 조원로11길 24 ,우민조원아파트 101-101 (조원동)', '02', '868', '1373', 5)
2021-08-18 17:41:00,270 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,271 INFO sqlalchemy.engine.base.Engine ('구립반디어린이집', '윤민지', '서울특별시 관악구 관악로 133 ,건영아파트 102-103 (청룡동)', '02', '889', '7237', 5)
2021-08-18 17:41:00,272 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,272 INFO sqlalchemy.engine.base.Engine ('서초구립 아이숲어린이집', '권은영', '서울특별시 서초구 청계산로9길 1-12 ,602동 1층내 (내곡동)', '02', '577', '9509', 15)

2021-08-18 17:41:00,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,274 INFO sqlalchemy.engine.base.Engine ('구립 노블키즈어린이집', '장민수', '서울특별시 강서구 강서로47길 108 ,109동 102호 (발산제1동)', '02', '6012', '2430', 4)
2021-08-18 17:41:00,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,276 INFO sqlalchemy.engine.base.Engine ('구립 스마일어린이집', '전미영', '서울특별시 강서구 강서로 266 ,114동 103호(화곡동, 우장산아이파크 이편한세상) (우장산동)', '02', '6278', '7737', 4)
2021-08-18 17:41:00,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,278 INFO sqlalchemy.engine.base.Engine ('구립 푸른별어린이집', '한종수', '서울특별시 강서구 강서로47길 158 ,201동 104호 (발산제1동)', '02', '2667', '2288', 4)
2021-08-18 17:41:00,279 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,280 INFO sqlalchemy.engine.base.Engine ('강남세브란스어린이집', '안준서', '서울특별시 강남구 언주로63길 29 ,명지빌딩 1층 (역삼2동)', '02', '2019', '4300', 1)
2021-08-18 17:41:00,281 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,282 INFO sqlalchemy.engine.base.Engine ('꿈둥이어린이집', '황수빈', '서울특별시 동대문구 장안벚꽃로 107 ,105동 104호 (장안동, 현대홈타운아파트) (장안제1동)', '02', '3394', '8300', 11)
2021-08-18 17:41:00,283 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,283 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '이지영', '서울특별시 구로구 디지털로 319 ,302동 101호(구로동, 현대아파트) (구로제3동)', '02', '837', '6232', 7)
2021-08-18 17:41:00,284 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,285 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '안정남', '서울특별시 구로구 개봉로17아길 44 ,멤버스빌 101호 (개봉동) (개봉제2동)', '02', '2685', '0692', 7)
2021-08-18 17:41:00,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,288 INFO sqlalchemy.engine.base.Engine ('은해어린이집', '임지은', '서울특별시 영등포구 국제금융로 110 ,여의도동 (여의동)', '02', '783', '5512', 20)
2021-08-18 17:41:00,289 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,290 INFO sqlalchemy.engine.base.Engine ('잠실국민연금어린이집', '신지영', '서울특별시 송파구 올림픽로35다길 13 (잠실6동)', '02', '2202', '7470', 18)
2021-08-18 17:41:00,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,292 INFO sqlalchemy.engine.base.Engine ('풍납토성어린이집', '권수빈', '서울특별시 송파구 토성로 34 (풍납2동)', '02', '472', '5155', 18)
2021-08-18 17:41:00,294 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,294 INFO sqlalchemy.engine.base.Engine ('순천향대학교서울병원어린이집', '서정수', '서울특별시 용산구 대사관로34가길 2-18 (한남동)', '02', '795', '1007', 21)
2021-08-18 17:41:00,296 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,297 INFO sqlalchemy.engine.base.Engine ('구립 이솝어린이집', '안지훈', '서울특별시 양천구 신정중앙로12길 17 ,(신정동) (신정4동)', '02', '2695', '1145', 19)
2021-08-18 17:41:00,298 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,299 INFO sqlalchemy.engine.base.Engine ('구립레미안어린이집', '한종수', '서울특별시 관악구 성현로 80 ,관악드림타운아파트 144-101 (성현동)', '02', '872', '5034', 5)
2021-08-18 17:41:00,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,300 INFO sqlalchemy.engine.base.Engine ('구립운서어린이집', '전지민', '서울특별시 관악구 미성길 60 ,두영아파트 103호 (미성동)', '02', '858', '6999', 5)
2021-08-18 17:41:00,301 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,301 INFO sqlalchemy.engine.base.Engine ('동그라미리틀어린이집', '박혜진', '서울특별시 마포구 독막로5길 16-2 (서교동)', '02', '6404', '6573', 13)
2021-08-18 17:41:00,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,304 INFO sqlalchemy.engine.base.Engine ('방배본동 행복한 어린이집', '송정호', '서울특별시 서초구 동광로11길 86 (방배본동)', '02', '3482', '0103', 15)
2021-08-18 17:41:00,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,306 INFO sqlalchemy.engine.base.Engine ('아이플러스어린이집', '장정자', '서울특별시 강남구 밤고개로26길 50 ,강남한신휴플러스 아파트 6단지 내 관리동 (세곡동)', '02', '2226', '8835', 1)
2021-08-18 17:41:00,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,308 INFO sqlalchemy.engine.base.Engine ('열린꿈어린이집', '윤예준', '서울특별시 중랑구 신내로19길 42 ,612동 101호(신내동, 신내대주아파트) (신내2동)', '02', '3423', '0079', 25)
2021-08-18 17:41:00,309 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,310 INFO sqlalchemy.engine.base.Engine ('금천G밸리어린이집', '한영철', '서울특별시 금천구 두산로 70 ,현대지식산업센터 티-115,116,117-01 (독산제1동)', '02', '2169', '2280', 8)
2021-08-18 17:41:00,311 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,312 INFO sqlalchemy.engine.base.Engine ('롯데mom편한어린이집', '안민지', '서울특별시 송파구 올림픽로35길 137 ,한국광고문화회관 5층 3호 (잠실6동)', '02', '420', '1338', 18)
2021-08-18 17:41:00,313 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,314 INFO sqlalchemy.engine.base.Engine ('서울북부지방법원어린이집', '임준호', '서울특별시 도봉구 마들로 749 ,서울북부지방법원 (도봉제2동)', '02', '910', '3950', 10)
2021-08-18 17:41:00,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,316 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '황미경', '서울특별시 구로구 고척로21다길 28-1 ,1층(개봉1동) (개봉제1동)', '02', '2612', '3359', 7)
2021-08-18 17:41:00,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,318 INFO sqlalchemy.engine.base.Engine ('꿈에그린어린이집', '조영자', '서울특별시 성북구 아리랑로19가길 21 ,,관리동(정릉동,꿈에그린아파트) (정릉제2동)', '02', '915', '0565', 17)
2021-08-18 17:41:00,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,321 INFO sqlalchemy.engine.base.Engine ('솔빛어린이집', '신정순', '서울특별시 강남구 압구정로80길 17 ,2층 (청담동)', '02', '6979', '1060', 1)
2021-08-18 17:41:00,322 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,323 INFO sqlalchemy.engine.base.Engine ('은평한옥마을성균관어린이집', '서성호', '서울특별시 은평구 연서로48길 54 (진관동)', '02', '356', '5375', 22)

2021-08-18 17:41:00,323 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,324 INFO sqlalchemy.engine.base.Engine ('푸른아이어린이집', '전민서', '서울특별시 은평구 통일로 660 ,북한산푸르지오아파트관리동어린이집 (녹번동)', '02', '355', '7956', 22)
2021-08-18 17:41:00,325 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,325 INFO sqlalchemy.engine.base.Engine ('롯데mom편한어린이집', '류서현', '서울특별시 중구 회현동1가 소공로 35 ,남산롯데캐슬아이리스 210호, 211호 (회현동)', '02', '774', '4498', 24)
2021-08-18 17:41:00,326 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,326 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '서성진', '서울특별시 서초구 태봉로2길 10 ,네이처힐 7단지 관리동 (양재1동)', '02', '529', '8855', 15)
2021-08-18 17:41:00,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,328 INFO sqlalchemy.engine.base.Engine ('광남어린이집', '전준서', '서울특별시 광진구 아차산로70길 62 ,305동 102호(광장현대3단지아파트, 광장동) (광장동)', '02', '455', '7430', 6)
2021-08-18 17:41:00,329 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,329 INFO sqlalchemy.engine.base.Engine ('구립 경남어린이집', '전수빈', '서울특별시 은평구 갈현로11길 46 ,106동 101호(구산동, 경남아너스빌) (구산동)', '02', '3157', '1231', 22)
2021-08-18 17:41:00,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,331 INFO sqlalchemy.engine.base.Engine ('구립 꿈동산어린이집', '신민서', '서울특별시 은평구 서오릉로22길 16-1 ,101호 (갈현제2동)', '02', '355', '1081', 22)
2021-08-18 17:41:00,333 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,334 INFO sqlalchemy.engine.base.Engine ('구립 대영어린이집', '오지영', '서울특별시 은평구 응암로 376 (녹번동)', '02', '358', '8541', 22)
2021-08-18 17:41:00,336 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,337 INFO sqlalchemy.engine.base.Engine ('구립 이솝어린이집', '류동현', '서울특별시 은평구 증산서길 79 ,102동 101호(증산동, 두산위브아파트) (증산동)', '02', '374', '7219', 22)
2021-08-18 17:41:00,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,339 INFO sqlalchemy.engine.base.Engine ('구립 좋은씨앗어린이집', '조서현', '서울특별시 은평구 연서로3가길 13-11 ,한국리치빌 아파트 1층 106호 (역촌동) (역촌동)', '02', '386', '9777', 22)
2021-08-18 17:41:00,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,341 INFO sqlalchemy.engine.base.Engine ('구립늘사랑어린이집', '최민석', '서울특별시 강북구 솔샘로 174 ,115동 103호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '983', '5531', 3)
2021-08-18 17:41:00,342 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,343 INFO sqlalchemy.engine.base.Engine ('구립독산2동어린이집', '장민수', '서울특별시 금천구 시흥대로98길 45 (독산제2동)', '02', '804', '9237', 8)
2021-08-18 17:41:00,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,344 INFO sqlalchemy.engine.base.Engine ('구립독산한신사임당어린이집', '송예은', '서울특별시 금천구 한내로 62 ,12동 103호(독산동, 한신) (독산제1동)', '02', '899', '8993', 8)
2021-08-18 17:41:00,345 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,346 INFO sqlalchemy.engine.base.Engine ('구립또래어린이집', '박종수', '서울특별시 금천구 금하로 793 ,115동 103호(시흥동, 벽산아파트) (시흥제2동)', '02', '805', '0397', 8)
2021-08-18 17:41:00,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,347 INFO sqlalchemy.engine.base.Engine ('구립벽산꿈어린이집', '류준혁', '서울특별시 금천구 금하로 816 ,511동 102호(시흥동, 벽산5단지아파트) (시흥제2동)', '02', '3286', '7942', 8)
2021-08-18 17:41:00,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,348 INFO sqlalchemy.engine.base.Engine ('구립삼각산꾸러기어린이집', '박영식', '서울특별시 강북구 삼양로19길 113 ,101동 104호(미아동, 삼각산아이원아파트) (삼각산동)', '02', '982', '0132', 3)
2021-08-18 17:41:00,349 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,350 INFO sqlalchemy.engine.base.Engine ('구립새싹어린이집', '조영식', '서울특별시 강북구 솔샘로 174 ,138동 104호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '983', '0056', 3)
2021-08-18 17:41:00,351 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,352 INFO sqlalchemy.engine.base.Engine ('구립스마일어린이집', '서정호', '서울특별시 동작구 성대로11길 42 (상도제4동)', '02', '813', '2602', 12)
2021-08-18 17:41:00,353 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,354 INFO sqlalchemy.engine.base.Engine ('구립유나어린이집', '윤종수', '서울특별시 금천구 금하로 816 ,516동 102호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '808', '7369', 8)
2021-08-18 17:41:00,357 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,359 INFO sqlalchemy.engine.base.Engine ('구립은하수어린이집', '황유진', '서울특별시 금천구 금하로 793 ,103동 101호(시흥동, 벽산아파트) (시흥제2동)', '02', '891', '6663', 8)
2021-08-18 17:41:00,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,362 INFO sqlalchemy.engine.base.Engine ('구립짐토피아어린이집', '한정순', '서울특별시 강북구 삼각산로 143-1 ,9동 107호(수유동, 수유벽산) (수유2동)', '02', '992', '7179', 3)
2021-08-18 17:41:00,364 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,365 INFO sqlalchemy.engine.base.Engine ('구립참행복한어린이집', '한영철', '서울특별시 강북구 인수봉로84길 34-14 (우이동)', '02', '902', '8881', 3)
2021-08-18 17:41:00,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,367 INFO sqlalchemy.engine.base.Engine ('구립하늘빛어린이집', '황순자', '서울특별시 금천구 금하로 816 ,510동 103호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '807', '6162', 8)
2021-08-18 17:41:00,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,370 INFO sqlalchemy.engine.base.Engine ('구립햇님어린이집', '박준혁', '서울특별시 강북구 솔샘로 174 ,116동 104호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '984', '8874', 3)
2021-08-18 17:41:00,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,373 INFO sqlalchemy.engine.base.Engine ('도봉2동예광어린이집', '황준혁', '서울특별시 도봉구 마들로 859-19 ,117동 105호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '955', '9502', 10)
2021-08-18 17:41:00,374 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,375 INFO sqlalchemy.engine.base.Engine ('도봉2동오감발달베이비마을어린이집', '안수빈', '서울특별시 도봉구 도봉로180길 6-23 ,103동 106호(도봉동, 동아에코빌아파트) (도봉제2동)', '02', '6463', '3030', 10)
2021-08-18 17:41:00,376 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,376 INFO sqlalchemy.engine.base.Engine ('동심삐아제어린이집', '안지혜', '서울특별시 성북구 숭인로2길 61 ,101동 103호(길음동, 동부센트레빌아파트) (길음제2동)', '02', '983', '7330', 17)
2021-08-18 17:41:00,377 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,378 INFO sqlalchemy.engine.base.Engine ('바니스쿨어린이집', '윤민지', '서울특별시 광진구 광나루로56길 32 ,구의현대2단지아파트 215동 104호(구의3동) (구의제3동)', '02', '446', '1347', 6)
2021-08-18 17:41:00,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,380 INFO sqlalchemy.engine.base.Engine ('방학1동한슬어린이집', '장성호', '서울특별시 도봉구 마들로 616 ,107동 101호(방학동, 대상타운현대아파트) (방학제1동)', '02', '955', '0694', 10)
2021-08-18 17:41:00,381 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,382 INFO sqlalchemy.engine.base.Engine ('서울발트킨더어린이집', '권준호', '서울특별시 서초구 헌릉로8길 10-12 ,107동 1층 (내곡동)', '02', '572', '7942', 15)
2021-08-18 17:41:00,383 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,384 INFO sqlalchemy.engine.base.Engine ('서초구립예아어린이집', '최영길', '서울특별시 서초구 방배천로18길 36-8 (방배2동)', '02', '522', '2879', 15)
2021-08-18 17:41:00,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,386 INFO sqlalchemy.engine.base.Engine ('서현어린이집', '조정호', '서울특별시 마포구 잔다리로7길 31 (서교동)', '02', '326', '5004', 13)
2021-08-18 17:41:00,387 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,388 INFO sqlalchemy.engine.base.Engine ('쌍문2동소라어린이집', '권미숙', '서울특별시 도봉구 도봉로 603-1 ,창동중앙교회 1층 (쌍문제2동)', '02', '904', '6100', 10)
2021-08-18 17:41:00,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,390 INFO sqlalchemy.engine.base.Engine ('언덕위에 하얀 어린이집', '임상훈', '서울특별시 동대문구 약령시로3길 38 ,(제기동) (제기동)', '02', '925', '3150', 11)
2021-08-18 17:41:00,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,392 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '장경회', '서울특별시 동대문구 한천로63길 10 ,106동 104호(이문동, 이문e편한세상아파트) (이문제2동)', '02', '965', '3007', 11)
2021-08-18 17:41:00,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,393 INFO sqlalchemy.engine.base.Engine ('이솝어린이집', '권민수', '서울특별시 동대문구 고산자로 534 ,107동 101호(제기동, 한신아파트) (제기동)', '02', '959', '3434', 11)
2021-08-18 17:41:00,394 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,395 INFO sqlalchemy.engine.base.Engine ('중곡햇님어린이집', '정은경', '서울특별시 광진구 능동로48길 49 ,101호(중곡동, 웰빙아파트) (중곡제2동)', '02', '453', '6132', 6)
2021-08-18 17:41:00,396 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,397 INFO sqlalchemy.engine.base.Engine ('창2동새샘어린이집', '황영진', '서울특별시 도봉구 도봉로106길 36 ,(창동) (창제2동)', '02', '998', '7796', 10)
2021-08-18 17:41:00,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,398 INFO sqlalchemy.engine.base.Engine ('창2동엘리트어린이집', '윤정수', '서울특별시 도봉구 도봉로110다길 51 ,108동 102호(창동, 태영데시앙) (창제2동)', '02', '6316', '2987', 10)
2021-08-18 17:41:00,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,400 INFO sqlalchemy.engine.base.Engine ('창4동사랑어린이집', '오미경', '서울특별시 도봉구 노해로70길 54 ,1909동 108호(창동, 상계주공19차아파트) (창제4동)', '02', '905', '2551', 10)
2021-08-18 17:41:00,401 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,401 INFO sqlalchemy.engine.base.Engine ('키노어린이집', '서병철', '서울특별시 성북구 정릉로26길 8 ,205동 102호(정릉동, 중앙하이츠빌아파트) (정릉제2동)', '02', '943', '9353', 17)
2021-08-18 17:41:00,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,403 INFO sqlalchemy.engine.base.Engine ('한국공항공사어린이집', '신지은', '서울특별시 강서구 하늘길 78 ,. (공항동)', '02', '2660', '2630', 4)
2021-08-18 17:41:00,403 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,404 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '신지훈', '서울특별시 영등포구 가마산로45길 13-1 (대림제3동)', '02', '832', '4539', 20)
2021-08-18 17:41:00,405 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,406 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '송경숙', '서울특별시 성북구 오패산로 46 ,123동 108호(하월곡동, 월곡두산위브아파트) (월곡제1동)', '02', '918', '3308', 17)
2021-08-18 17:41:00,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,407 INFO sqlalchemy.engine.base.Engine ('휴먼빌키즈어린이집', '조건우', '서울특별시 성북구 아리랑로 89 ,104동 101호(돈암동, 일신휴먼빌아파트) (돈암제2동)', '02', '6231', '7942', 17)
2021-08-18 17:41:00,408 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,409 INFO sqlalchemy.engine.base.Engine ('서울시농수산식품공사올본어린이집', '류지훈', '서울특별시 송파구 양재대로 932 ,서울시농수산식품공사 3층 (가락1동)', '02', '3435', '1212', 18)
2021-08-18 17:41:00,410 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,411 INFO sqlalchemy.engine.base.Engine ('이글아이어린이집', '오은경', '서울특별시 양천구 화곡로 25 (신월3동)', '070', '7379', '5603', 19)
2021-08-18 17:41:00,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,413 INFO sqlalchemy.engine.base.Engine ('한국국방연구원 직장어린이집', '박준서', '서울특별시 동대문구 회기로 85 ,800동 (회기동) (회기동)', '02', '959', '2169', 11)
2021-08-18 17:41:00,414 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,414 INFO sqlalchemy.engine.base.Engine ('KSD푸르니어린이집', '이지혜', '서울특별시 영등포구 여의나루로4길 23 ,2층 (여의동)', '02', '785', '7011', 20)
2021-08-18 17:41:00,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,416 INFO sqlalchemy.engine.base.Engine ('구립 신금호자이어린이집', '장민지', '서울특별시 성동구 금호동2가 금호로 173 ,신금호파크자이 관리동 (금호2.3가동)', '02', '2234', '1700', 16)

2021-08-18 17:41:00,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,418 INFO sqlalchemy.engine.base.Engine ('미성어린이집', '황미경', '서울특별시 은평구 백련산로4길 17-7 (응암제2동)', '02', '357', '3562', 22)
2021-08-18 17:41:00,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,419 INFO sqlalchemy.engine.base.Engine ('효성ITX어린이집', '장진호', '서울특별시 영등포구 양평동4가 선유동2로 57 (양평제2동)', '02', '2068', '1920', 20)
2021-08-18 17:41:00,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,421 INFO sqlalchemy.engine.base.Engine ('푸르지오그린어린이집', '황수빈', '서울특별시 송파구 위례광장로 185 ,관리동 (위례동)', '02', '2138', '6493', 18)
2021-08-18 17:41:00,422 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,423 INFO sqlalchemy.engine.base.Engine ('SGI서울보증 어린이집', '강수빈', '서울특별시 종로구 김상옥로 29 ,2층 (종로5·6가동)', '02', '3671', '7051', 23)
2021-08-18 17:41:00,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,427 INFO sqlalchemy.engine.base.Engine ('무궁화어린이집', '최은정', '서울특별시 종로구 자하문로28길 8 ,외 1 (궁정동) (청운효자동)', '02', '730', '2486', 23)
2021-08-18 17:41:00,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,429 INFO sqlalchemy.engine.base.Engine ('삼성전자서울R&D;캠퍼스어린이집', '서정식', '서울특별시 서초구 성촌길 67 ,삼성전자서울알앤디캠퍼스어린이집 (양재1동)', '02', '6147', '9801', 15)
2021-08-18 17:41:00,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,430 INFO sqlalchemy.engine.base.Engine ('상명행복어린이집', '신광수', '서울특별시 종로구 홍지문2길 37 (부암동)', '02', '2287', '5223', 23)
2021-08-18 17:41:00,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,432 INFO sqlalchemy.engine.base.Engine ('아름어린이집', '박미경', '서울특별시 강서구 등촌로5길 18-22 ,은성하이츠 101호 (화곡제4동)', '02', '6494', '0079', 4)
2021-08-18 17:41:00,433 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,434 INFO sqlalchemy.engine.base.Engine ('순수 빅스맘 어린이집', '류준영', '서울특별시 영등포구 당산동3가 국회대로 612 (당산제1동)', '02', '2068', '7975', 20)
2021-08-18 17:41:00,435 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,435 INFO sqlalchemy.engine.base.Engine ('국립중앙도서관책사랑어린이집', '임준호', '서울특별시 서초구 반포대로 201 ,국립중앙도서관 내 어린이집 (반포4동)', '02', '590', '6309', 15)
2021-08-18 17:41:00,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,437 INFO sqlalchemy.engine.base.Engine ('월계꿈의숲어린이집', '한정수', '서울특별시 노원구 월계로42길 97 ,꿈의숲SK VIEW아파트 102동 1층 (월계1동)', '02', '942', '3399', 9)
2021-08-18 17:41:00,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,439 INFO sqlalchemy.engine.base.Engine ('구립명일사랑어린이집', '신민수', '서울특별시 강동구 상암로 224 ,9-106 (명일제1동)', '02', '442', '1449', 2)
2021-08-18 17:41:00,440 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,441 INFO sqlalchemy.engine.base.Engine ('구립연두어린이집', '전민석', '서울특별시 강동구 천중로44길 40 ,101동109호(길동, 희훈리치파크A) (길동)', '02', '486', '0268', 2)
2021-08-18 17:41:00,443 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,443 INFO sqlalchemy.engine.base.Engine ('구립초롱별어린이집', '송수빈', '서울특별시 강동구 양재대로134길 41 (명일제1동)', '02', '428', '7977', 2)
2021-08-18 17:41:00,447 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,448 INFO sqlalchemy.engine.base.Engine ('AJ어린이집', '류민지', '서울특별시 송파구 정의로8길 9 ,문정동 640-5 (문정2동)', '02', '6240', '1490', 18)
2021-08-18 17:41:00,449 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,450 INFO sqlalchemy.engine.base.Engine ('금호힐어린이집', '윤병철', '서울특별시 성북구 동소문로34길 73 (돈암제1동)', '02', '929', '3412', 17)
2021-08-18 17:41:00,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,452 INFO sqlalchemy.engine.base.Engine ('구립한빛어린이집', '강동현', '서울특별시 동작구 상도로30길 40 ,두산위브트레지움아파트 202동 1층 (상도제2동)', '02', '826', '8080', 12)
2021-08-18 17:41:00,453 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,454 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '권영길', '서울특별시 영등포구 당산동4가 당산로41가길 7 ,1층 (당산제2동)', '02', '2636', '3412', 20)
2021-08-18 17:41:00,455 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,456 INFO sqlalchemy.engine.base.Engine ('둥근마음어린이집', '정성호', '서울특별시 영등포구 여의대방로 372 (여의동)', '02', '2070', '7500', 20)
2021-08-18 17:41:00,457 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,457 INFO sqlalchemy.engine.base.Engine ('반디어린이집', '장서연', '서울특별시 영등포구 양평동6가 양평로30가길 15 ,동양아파트 101동 106호 (양평제2동)', '02', '2676', '0677', 20)
2021-08-18 17:41:00,458 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,459 INFO sqlalchemy.engine.base.Engine ('선재어린이집', '서은영', '서울특별시 영등포구 당산동3가 선유동1로 80 (당산제1동)', '02', '2069', '3018', 20)
2021-08-18 17:41:00,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,460 INFO sqlalchemy.engine.base.Engine ('아기사랑어린이집', '서준혁', '서울특별시 중구 다산로32길 25 ,(신당동) (동화동)', '02', '2253', '1467', 24)
2021-08-18 17:41:00,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,462 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '박영철', '서울특별시 노원구 동일로227길 26 ,1611동 101호(상계동, 상계주공16차) (상계8동)', '02', '930', '6021', 9)
2021-08-18 17:41:00,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,464 INFO sqlalchemy.engine.base.Engine ('청솔창의어린이집', '최도현', '서울특별시 노원구 공릉로59가길 13 ,청솔창의어린이집 (하계1동)', '02', '977', '3593', 9)
2021-08-18 17:41:00,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,466 INFO sqlalchemy.engine.base.Engine ('프레비뉴어린이집', '장병철', '서울특별시 영등포구 가마산로 442 (신길제3동)', '02', '832', '9919', 20)

2021-08-18 17:41:00,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,467 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '권지훈', '서울특별시 영등포구 여의대방로 25 ,104동 101호(신길동, 경남보라매아너스빌) (신길제6동)', '02', '831', '8255', 20)
2021-08-18 17:41:00,469 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,470 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '정지은', '서울특별시 영등포구 선유서로 43 ,1동 105호(문래동6가, 한신아파트) (문래동)', '02', '2068', '5664', 20)
2021-08-18 17:41:00,471 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,472 INFO sqlalchemy.engine.base.Engine ('엘림어린이집', '조광수', '서울특별시 강남구 광평로34길 55 ,강남데시앙포레아파트 관리동 (수서동)', '02', '459', '2525', 1)
2021-08-18 17:41:00,473 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,474 INFO sqlalchemy.engine.base.Engine ('수락한옥어린이집', '최예은', '서울특별시 노원구 수락산로 131 ,수락한옥어린이집 (상계9동)', '02', '935', '2600', 9)
2021-08-18 17:41:00,475 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,475 INFO sqlalchemy.engine.base.Engine ('나빛어린이집', '서정순', '서울특별시 서대문구 가재울미래로 2 ,217동101호(남가좌1동,DMC파크뷰자이) (남가좌제1동)', '02', '307', '8781', 14)
2021-08-18 17:41:00,476 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,477 INFO sqlalchemy.engine.base.Engine ('중계행복어린이집', '류지영', '서울특별시 노원구 중계로8길 17 ,중계행복어린이집 (중계본동)', '02', '931', '5566', 9)
2021-08-18 17:41:00,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,479 INFO sqlalchemy.engine.base.Engine ('경동어린이집', '신건우', '서울특별시 성북구 안암동3가 고려대로14길 42 ,경동어린이집 (안암동)', '02', '921', '9739', 17)
2021-08-18 17:41:00,483 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,484 INFO sqlalchemy.engine.base.Engine ('구립 신정4동어린이집', '류현정', '서울특별시 양천구 오목로34길 5 (신정4동)', '02', '2601', '7856', 19)
2021-08-18 17:41:00,485 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,486 INFO sqlalchemy.engine.base.Engine ('소리어린이집', '김정자', '서울특별시 성북구 오패산로 98-12 (월곡제1동)', '02', '910', '8990', 17)
2021-08-18 17:41:00,488 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,488 INFO sqlalchemy.engine.base.Engine ('고운햇살어린이집', '송민석', '서울특별시 서대문구 가재울미래로 2 ,303동102호(남가좌1동,DMC파크뷰자이) (남가좌제1동)', '02', '303', '8352', 14)
2021-08-18 17:41:00,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,493 INFO sqlalchemy.engine.base.Engine ('도토리어린이집', '오동현', '서울특별시 강서구 곰달래로51길 46 (화곡제4동)', '02', '2649', '4912', 4)
2021-08-18 17:41:00,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,496 INFO sqlalchemy.engine.base.Engine ('구립 꽃초롱어린이집', '장종수', '서울특별시 성동구 마장로 164 (왕십리도선동)', '02', '2291', '3260', 16)
2021-08-18 17:41:00,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,498 INFO sqlalchemy.engine.base.Engine ('구립 새솔어린이집', '안정수', '서울특별시 성동구 금호동2가 금호로 107 ,105동 102호 (금호2.3가동)', '070', '8111', '3067', 16)
2021-08-18 17:41:00,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,501 INFO sqlalchemy.engine.base.Engine ('구립 송정햇살어린이집', '박민재', '서울특별시 성동구 송정12길 1 (송정동)', '02', '467', '5002', 16)
2021-08-18 17:41:00,502 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,503 INFO sqlalchemy.engine.base.Engine ('구립명일2동어린이집', '서준혁', '서울특별시 강동구 동남로65길 46-12 ,(명일2동 237) (명일제2동)', '02', '3013', '5679', 2)
2021-08-18 17:41:00,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,505 INFO sqlalchemy.engine.base.Engine ('구립은강어린이집', '김서현', '서울특별시 강동구 양재대로103길 28 ,(성내3동 378-9) (성내제3동)', '02', '486', '7979', 2)
2021-08-18 17:41:00,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,508 INFO sqlalchemy.engine.base.Engine ('구립천호2어린이집', '오영자', '서울특별시 강동구 구천면로41길 84 ,(천호2동 289-76) (천호제2동)', '02', '470', '0336', 2)
2021-08-18 17:41:00,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,518 INFO sqlalchemy.engine.base.Engine ('구립한마을어린이집', '김예준', '서울특별시 강동구 상암로81길 14 ,(상일동337-2) (상일제1동)', '02', '426', '1603', 2)
2021-08-18 17:41:00,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,520 INFO sqlalchemy.engine.base.Engine ('구립한빛어린이집', '박정웅', '서울특별시 강동구 구천면로55길 35-1 (암사제1동)', '02', '428', '2055', 2)
2021-08-18 17:41:00,528 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,529 INFO sqlalchemy.engine.base.Engine ('구립해든어린이집', '전지영', '서울특별시 강동구 상암로21길 26 (암사제1동)', '02', '428', '7942', 2)
2021-08-18 17:41:00,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,530 INFO sqlalchemy.engine.base.Engine ('구립행복이든어린이집', '이영길', '서울특별시 강동구 고덕로97길 100 ,강일리버파크11단지 관리동 (강일동)', '02', '426', '8684', 2)
2021-08-18 17:41:00,535 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,536 INFO sqlalchemy.engine.base.Engine ('구립현대어린이집', '전정수', '서울특별시 강동구 고덕로27길 36 ,관리동(암사동, 강동 현대홈타운) (암사제3동)', '02', '441', '8333', 2)
2021-08-18 17:41:00,537 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,538 INFO sqlalchemy.engine.base.Engine ('예뜰어린이집', '장은경', '서울특별시 서대문구 거북골로23길 15 ,(북가좌1동) (북가좌제1동)', '02', '308', '0137', 14)
2021-08-18 17:41:00,539 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,539 INFO sqlalchemy.engine.base.Engine ('칼비테영재어린이집', '최미영', '서울특별시 동대문구 장안벚꽃로 167 ,214동 102호(장안동, 장안아파트2단지) (장안제2동)', '02', '2215', '0010', 11)
2021-08-18 17:41:00,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,541 INFO sqlalchemy.engine.base.Engine ('아장아장어린이집', '김상훈', '서울특별시 서대문구 가재울미래로 2 ,129동103호(남가좌1동,DMC파크뷰자이) (남가좌제1동)', '02', '373', '0727', 14)

2021-08-18 17:41:00,544 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,548 INFO sqlalchemy.engine.base.Engine ('해뜰어린이집', '안정호', '서울특별시 구로구 구로동로21길 38 (구로제2동)', '02', '852', '5110', 7)
2021-08-18 17:41:00,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,553 INFO sqlalchemy.engine.base.Engine ('기쁨새생명어린이집', '권지은', '서울특별시 송파구 성내천로23가길 7 (마천2동)', '02', '430', '2210', 18)
2021-08-18 17:41:00,554 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,555 INFO sqlalchemy.engine.base.Engine ('하늘숲 어린이집', '권경자', '서울특별시 서초구 본마을길 37 ,하늘숲 어린이집 (내곡동)', '02', '578', '5999', 15)
2021-08-18 17:41:00,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,557 INFO sqlalchemy.engine.base.Engine ('가람어린이집', '윤준호', '서울특별시 서대문구 가재울미래로 2 ,dmc 파크뷰자이 1단지 내, 관리사무소 빌딩 1층 (남가좌제1동)', '02', '307', '1900', 14)
2021-08-18 17:41:00,558 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,559 INFO sqlalchemy.engine.base.Engine ('경남삐아제어린이집', '황영길', '서울특별시 노원구 섬밭로 263 ,5동 106호(중계동, 경남아파트) (중계2.3동)', '02', '978', '0447', 9)
2021-08-18 17:41:00,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,562 INFO sqlalchemy.engine.base.Engine ('구립 별하어린이집', '신수빈', '서울특별시 성동구 마장로39길 31 (마장동)', '02', '2291', '4191', 16)
2021-08-18 17:41:00,563 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,564 INFO sqlalchemy.engine.base.Engine ('구립마엘향어린이집', '임지훈', '서울특별시 관악구 난곡로35길 60 ,구립마엘향어린이집 (난곡동)', '02', '857', '3553', 5)
2021-08-18 17:41:00,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,567 INFO sqlalchemy.engine.base.Engine ('아람어린이집', '황정순', '서울특별시 서대문구 가재울미래로 2 ,가재울미래로 2, DMC파크뷰자이 2단지 내 커뮤니티 센터 1층 (남가좌제1동)', '02', '307', '2600', 14)
2021-08-18 17:41:00,568 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,569 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '최지민', '서울특별시 중랑구 봉화산로21길 14 ,(중화동) (중화제1동)', '02', '434', '7117', 25)
2021-08-18 17:41:00,571 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,572 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '송지영', '서울특별시 서대문구 거북골로 154 ,101동 108호(북가좌동, 삼호) (북가좌제2동)', '02', '308', '7812', 14)
2021-08-18 17:41:00,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,575 INFO sqlalchemy.engine.base.Engine ('예그린어린이집', '권정순', '서울특별시 서대문구 증가로30길 8 ,서부아파트 103호 (북가좌동) (북가좌제2동)', '02', '305', '0522', 14)
2021-08-18 17:41:00,576 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,577 INFO sqlalchemy.engine.base.Engine ('he KIDS 여의도2 어린이집', '권상훈', '서울특별시 영등포구 여의대로 24 ,전경련회관 4층 (여의동)', '02', '3775', '4760', 20)
2021-08-18 17:41:00,578 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,579 INFO sqlalchemy.engine.base.Engine ('베베오르다어린이집', '류정수', '서울특별시 강남구 개포로 516 ,605동 105호 (개포2동)', '070', '8973', '1004', 1)
2021-08-18 17:41:00,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,581 INFO sqlalchemy.engine.base.Engine ('청계산반디빅스맘어린이집', '신정수', '서울특별시 서초구 청계산로11길 10 ,(내곡동) (내곡동)', '02', '576', '4121', 15)
2021-08-18 17:41:00,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,583 INFO sqlalchemy.engine.base.Engine ('키즈크레용어린이집', '장은정', '서울특별시 송파구 중대로 24 ,230동 103호(문정동, 올림픽훼밀리타운) (문정2동)', '02', '443', '8844', 18)
2021-08-18 17:41:00,584 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,585 INFO sqlalchemy.engine.base.Engine ('구립도담어린이집', '류은영', '서울특별시 동작구 여의대방로10길 59 ,보라매파크빌아파트 104동 102호 (신대방제2동)', '02', '831', '5041', 12)
2021-08-18 17:41:00,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,587 INFO sqlalchemy.engine.base.Engine ('구립 가람어린이집', '류지영', '서울특별시 성동구 독서당로62길 43 ,6동 105호 (응봉동)', '02', '2297', '3462', 16)
2021-08-18 17:41:00,589 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,590 INFO sqlalchemy.engine.base.Engine ('구립 금호키움어린이집', '윤지원', '서울특별시 성동구 난계로 114-31 ,104-102(하왕십리동) (왕십리제2동)', '02', '2292', '2240', 16)
2021-08-18 17:41:00,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,595 INFO sqlalchemy.engine.base.Engine ('꿈모아어린이집', '이건우', '서울특별시 노원구 동일로227길 25 ,1109동 105호(상계동, 상계주공11차) (상계8동)', '02', '936', '2722', 9)
2021-08-18 17:41:00,596 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,597 INFO sqlalchemy.engine.base.Engine ('아기사랑어린이집', '최정수', '서울특별시 노원구 동일로228길 23 ,1412동 105호(상계동, 상계주공14차) (상계9동)', '02', '932', '0339', 9)
2021-08-18 17:41:00,598 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,599 INFO sqlalchemy.engine.base.Engine ('윤정어린이집', '송유진', '서울특별시 노원구 동일로215길 23 ,215동 102호(상계동, 상계주공2차) (상계6.7동)', '02', '6437', '9938', 9)
2021-08-18 17:41:00,600 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,600 INFO sqlalchemy.engine.base.Engine ('키노어린이집', '김준영', '서울특별시 노원구 섬밭로 139 ,106동 104호(공릉동, 픙림아파트) (공릉1동)', '02', '6221', '4991', 9)
2021-08-18 17:41:00,604 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,605 INFO sqlalchemy.engine.base.Engine ('하계햇빛어린이집', '임은경', '서울특별시 노원구 섬밭로 229 ,12동 105호(하계동, 벽산아파트) (하계2동)', '02', '977', '5513', 9)
2021-08-18 17:41:00,606 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,607 INFO sqlalchemy.engine.base.Engine ('해담어린이집', '박경숙', '서울특별시 구로구 천왕로 21 ,705동(천왕동, 천왕1지구, 7단지) (오류제2동)', '02', '2688', '8863', 7)
2021-08-18 17:41:00,608 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,609 INFO sqlalchemy.engine.base.Engine ('베리젬어린이집', '강준혁', '서울특별시 송파구 올림픽로 99 ,127동101호 (잠실동,엘스아파트) (잠실2동)', '02', '6407', '1233', 18)
2021-08-18 17:41:00,610 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,611 INFO sqlalchemy.engine.base.Engine ('he KIDS 대방 어린이집', '강수빈', '서울특별시 동작구 보라매로5가길 24 ,사옥2층 (신대방제2동)', '02', '849', '8555', 12)
2021-08-18 17:41:00,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,613 INFO sqlalchemy.engine.base.Engine ('구립 동화어린이집', '최성호', '서울특별시 양천구 목동중앙본로3길 7 ,101동 201호목동, 동화옥시죤-7아파트 (목4동)', '02', '2644', '9605', 19)
2021-08-18 17:41:00,614 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,615 INFO sqlalchemy.engine.base.Engine ('구립 목5동어린이집', '류정순', '서울특별시 양천구 목동서로 41 (목5동)', '02', '2652', '7979', 19)
2021-08-18 17:41:00,616 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,616 INFO sqlalchemy.engine.base.Engine ('구립 아이사랑어린이집', '박영진', '서울특별시 양천구 목동서로2길 22 ,101동 106호(목동, 한신청구아파트) (목5동)', '02', '2644', '9230', 19)
2021-08-18 17:41:00,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,619 INFO sqlalchemy.engine.base.Engine ('구립 올리브어린이집', '조지영', '서울특별시 양천구 신정로13길 50 ,102동 106호(신월동, 벽산아파트) (신월6동)', '02', '2692', '2279', 19)
2021-08-18 17:41:00,620 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,621 INFO sqlalchemy.engine.base.Engine ('구립 한마음어린이집', '서정순', '서울특별시 양천구 목동중앙남로 12-3 ,목동 노블레스아파트 102동 101호 (목4동)', '02', '6408', '2399', 19)
2021-08-18 17:41:00,622 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,622 INFO sqlalchemy.engine.base.Engine ('구립명지어린이집', '황현준', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트 121-104 (청림동)', '02', '6332', '3688', 5)
2021-08-18 17:41:00,623 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,624 INFO sqlalchemy.engine.base.Engine ('구립해뜨는어린이집', '윤경자', '서울특별시 관악구 관천로27길 2 ,우방아파트 103-103 (신사동)', '02', '859', '7906', 5)
2021-08-18 17:41:00,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,625 INFO sqlalchemy.engine.base.Engine ('대림어린이집', '권지은', '서울특별시 성북구 길음로 118 ,길음뉴타운대림아파트 관리동 1층(길음동) (길음제1동)', '02', '913', '6058', 17)
2021-08-18 17:41:00,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,629 INFO sqlalchemy.engine.base.Engine ('별초롱어린이집', '류종수', '서울특별시 동대문구 장안벚꽃로 107 ,104동 102호(장안동, 현대홈타운아파트) (장안제1동)', '02', '2217', '8880', 11)
2021-08-18 17:41:00,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,630 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '김정수', '서울특별시 동대문구 한천로 248 ,101동 102호(휘경동, 주공아파트) (휘경제2동)', '02', '2248', '2467', 11)
2021-08-18 17:41:00,632 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,634 INFO sqlalchemy.engine.base.Engine ('서초구립 포레스타2단지어린이집', '정미경', '서울특별시 서초구 헌릉로8길 45 (내곡동)', '02', '576', '7979', 15)
2021-08-18 17:41:00,635 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,636 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '강민수', '서울특별시 성북구 정릉로 305 ,107동 105호(정릉동,경남아파트) (정릉제1동)', '02', '914', '9858', 17)
2021-08-18 17:41:00,637 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,638 INFO sqlalchemy.engine.base.Engine ('한사랑어린이집', '조경회', '서울특별시 성북구 솔샘로25길 28 ,112동 101호(정릉동, 풍림아이원) (정릉제4동)', '02', '910', '7150', 17)
2021-08-18 17:41:00,640 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,640 INFO sqlalchemy.engine.base.Engine ('한세예스24 어린이집', '김예준', '서울특별시 영등포구 은행로 25 ,안원빌딩 2층 (여의동)', '02', '780', '6889', 20)
2021-08-18 17:41:00,641 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,642 INFO sqlalchemy.engine.base.Engine ('he KIDS 여의도1 어린이집', '정미경', '서울특별시 영등포구 의사당대로 18 ,현대카드/캐피탈 본사 3관 1층 (여의동)', '02', '3775', '2527', 20)
2021-08-18 17:41:00,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,643 INFO sqlalchemy.engine.base.Engine ('구립까치산어린이집', '서병철', '서울특별시 관악구 행운10길 21 ,관악파크푸르지오아파트 102동 1층 (행운동)', '02', '871', '1376', 5)
2021-08-18 17:41:00,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,644 INFO sqlalchemy.engine.base.Engine ('KB강서어린이집', '박종수', '서울특별시 강서구 양천로 643 ,2층 (염창동)', '02', '3665', '8101', 4)
2021-08-18 17:41:00,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,647 INFO sqlalchemy.engine.base.Engine ('강서힐스테이트어린이집', '장예준', '서울특별시 강서구 우현로 67 (우장산동)', '02', '2607', '7893', 4)
2021-08-18 17:41:00,648 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,648 INFO sqlalchemy.engine.base.Engine ('도담도담어린이집', '김성진', '서울특별시 마포구 독막로20나길 21 ,(상수동, 래미안밤섬리베뉴 2) (서강동)', '02', '336', '0606', 13)
2021-08-18 17:41:00,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,650 INFO sqlalchemy.engine.base.Engine ('하나린어린이집', '황정웅', '서울특별시 강서구 수명로1길 133 (발산제1동)', '02', '2665', '6300', 4)
2021-08-18 17:41:00,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,652 INFO sqlalchemy.engine.base.Engine ('GS리테일 푸르니 어린이집', '신현정', '서울특별시 강남구 테헤란로27길 34-3 ,. (역삼1동)', '02', '6925', '5012', 1)
2021-08-18 17:41:00,654 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,654 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '황정순', '서울특별시 동대문구 한천로46길 70-9 ,(장안동) (장안제2동)', '02', '2243', '0088', 11)
2021-08-18 17:41:00,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,656 INFO sqlalchemy.engine.base.Engine ('참포도나무어린이집', '신정남', '서울특별시 영등포구 대방천로 180 ,204동 112호(신길동, 우성2차아파트) (신길제6동)', '02', '831', '1068', 20)
2021-08-18 17:41:00,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,657 INFO sqlalchemy.engine.base.Engine ('구립대방보듬이나눔이어린이집', '장경숙', '서울특별시 동작구 대방동15길 10 (대방동)', '02', '822', '1257', 12)
2021-08-18 17:41:00,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,658 INFO sqlalchemy.engine.base.Engine ('이화초록별어린이집', '오서현', '서울특별시 마포구 마포대로24길 16 ,관리동 어린이집(아현동, 공덕자이아파트) (공덕동)', '02', '313', '0070', 13)
2021-08-18 17:41:00,659 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,660 INFO sqlalchemy.engine.base.Engine ('삼성SDS 꿈토란어린이집', '안영길', '서울특별시 마포구 월드컵북로60길 24 ,삼성SDS 상암IT센터 1층 (상암동)', '02', '6440', '7170', 13)
2021-08-18 17:41:00,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,661 INFO sqlalchemy.engine.base.Engine ('구립태성어린이집', '황정웅', '서울특별시 동작구 여의대방로16길 1 (신대방제2동)', '02', '832', '7799', 12)
2021-08-18 17:41:00,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,662 INFO sqlalchemy.engine.base.Engine ('구립색동어린이집', '한성호', '서울특별시 관악구 봉천로17길 5-16 (보라매동)', '02', '876', '8506', 5)
2021-08-18 17:41:00,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,664 INFO sqlalchemy.engine.base.Engine ('서초구립 서초자연이랑 어린이집', '송민서', '서울특별시 서초구 양재대로2길 109 (양재1동)', '02', '576', '0927', 15)
2021-08-18 17:41:00,664 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,665 INFO sqlalchemy.engine.base.Engine ('서초구립 포레스타6단지어린이집', '권준호', '서울특별시 서초구 청계산로9길 1-12 (내곡동)', '02', '575', '0546', 15)
2021-08-18 17:41:00,666 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,666 INFO sqlalchemy.engine.base.Engine ('힐스어린이집', '임은경', '서울특별시 강남구 자곡로3길 21 ,LHA5블럭 강남LH힐스테이트(관리동) (세곡동)', '02', '445', '3218', 1)
2021-08-18 17:41:00,668 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,669 INFO sqlalchemy.engine.base.Engine ('마노아구로어린이집', '임지훈', '서울특별시 구로구 디지털로27길 36 ,이스페이스108호 (구로제3동)', '02', '6210', '3100', 7)
2021-08-18 17:41:00,670 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,670 INFO sqlalchemy.engine.base.Engine ('아트자이어린이집', '조영길', '서울특별시 영등포구 도영로 66 ,아트자이아파트 단지내 복리시설 (도림동)', '02', '835', '9751', 20)
2021-08-18 17:41:00,672 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,672 INFO sqlalchemy.engine.base.Engine ('지니어스어린이집', '황성호', '서울특별시 강서구 화곡로68길 102 ,서울 시니어스 가양타워 1층 (등촌제1동)', '02', '3663', '1004', 4)
2021-08-18 17:41:00,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,674 INFO sqlalchemy.engine.base.Engine ('구립하늘빛어린이집', '임성호', '서울특별시 관악구 청림5길 28 ,관악푸르지오아파트 2단지 관리동 (청림동)', '02', '885', '1174', 5)
2021-08-18 17:41:00,675 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,675 INFO sqlalchemy.engine.base.Engine ('한가람꼬마숲어린이집', '조진호', '서울특별시 용산구 이촌로71길 10 ,213-101(이촌동,한가람아파트) (이촌제1동)', '070', '8888', '9655', 21)
2021-08-18 17:41:00,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,677 INFO sqlalchemy.engine.base.Engine ('라온어린이집', '조영철', '서울특별시 동대문구 정릉천동로 16 ,106동 102호 (용두두산위브아파트) (용신동)', '010', '7723', '7257', 11)
2021-08-18 17:41:00,678 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,679 INFO sqlalchemy.engine.base.Engine ('크니크니어린이집', '장지훈', '서울특별시 마포구 월드컵로1길 14 ,1층 크니크니어린이집 (합정동)', '02', '336', '6836', 13)
2021-08-18 17:41:00,680 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,681 INFO sqlalchemy.engine.base.Engine ('가온어린이집', '임정식', '서울특별시 구로구 서해안로34가길 33 (개봉제2동)', '02', '2681', '0090', 7)
2021-08-18 17:41:00,681 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,682 INFO sqlalchemy.engine.base.Engine ('구립아름꿈노아어린이집', '임지혜', '서울특별시 관악구 남부순환로145길 6 ,(조원동) (조원동)', '02', '852', '3338', 5)
2021-08-18 17:41:00,683 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,683 INFO sqlalchemy.engine.base.Engine ('창의나무아이파크어린이집', '조은정', '서울특별시 강남구 테헤란로52길 16 ,테헤란아이파크아파트 관리동 (역삼제2동)', '02', '558', '1841', 1)
2021-08-18 17:41:00,685 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,685 INFO sqlalchemy.engine.base.Engine ('리치빅스맘어린이집', '임정순', '서울특별시 동대문구 한빛로 73 ,103동 101 (용두동, 롯데캐슬리치아파트) (용신동)', '02', '6406', '2722', 11)
2021-08-18 17:41:00,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,687 INFO sqlalchemy.engine.base.Engine ('마포리버파크지향 어린이집', '조정수', '서울특별시 마포구 토정로31길 24 ,(용강동, e편한세상마포3차) (용강동)', '02', '719', '6369', 13)
2021-08-18 17:41:00,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,689 INFO sqlalchemy.engine.base.Engine ('예쁜꿈어린이집', '류영철', '서울특별시 강남구 개포로110길 15 ,우성7차아파트 107동 104호 (일원2동)', '02', '6160', '5950', 1)
2021-08-18 17:41:00,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,690 INFO sqlalchemy.engine.base.Engine ('해피어린이집', '박지은', '서울특별시 송파구 올림픽로35길 104 ,30동108(신천동,장미아파트) (잠실6동)', '02', '3402', '0605', 18)
2021-08-18 17:41:00,691 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,692 INFO sqlalchemy.engine.base.Engine ('세아별어린이집', '황정호', '서울특별시 강남구 영동대로 325 ,S TOWER 2층 (대치2동)', '02', '553', '7212', 1)
2021-08-18 17:41:00,694 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,695 INFO sqlalchemy.engine.base.Engine ('GKL행복어린이집', '한준혁', '서울특별시 강남구 삼성로122길 7 ,GKL 행복 어린이집 (삼성1동)', '02', '3448', '4571', 1)
2021-08-18 17:41:00,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,697 INFO sqlalchemy.engine.base.Engine ('구립 우리어린이집', '오미숙', '서울특별시 성동구 왕십리로21길 26-1 (행당제1동)', '02', '2295', '7940', 16)
2021-08-18 17:41:00,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:00,698 INFO sqlalchemy.engine.base.Engine ('구립상도4동어린이집', '김은영', '서울특별시 동작구 상도로22길 45 ,구립상도4동어린이집 (상도제4동)', '02', '3280', '1145', 12)
2021-08-18 17:41:00,700 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,701 INFO sqlalchemy.engine.base.Engine ('GS SHOP 도담도담 어린이집', '신준영', '서울특별시 영등포구 문래동6가 선유로 75 (문래동)', '02', '3667', '8935', 20)
2021-08-18 17:41:00,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,704 INFO sqlalchemy.engine.base.Engine ('구립 목3동보듬이어린이집', '윤정운', '서울특별시 양천구 목동중앙남로16마길 35-10 (목3동)', '02', '2647', '7942', 19)
2021-08-18 17:41:00,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,706 INFO sqlalchemy.engine.base.Engine ('구립 신월중앙어린이집', '오정웅', '서울특별시 양천구 곰달래로1길 23 ,(신월동) (신월1동)', '02', '2694', '7567', 19)
2021-08-18 17:41:00,707 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,711 INFO sqlalchemy.engine.base.Engine ('구립 신정2동어린이집', '윤미영', '서울특별시 양천구 신목로14길 4 (신정2동)', '02', '2654', '2007', 19)
2021-08-18 17:41:00,712 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,714 INFO sqlalchemy.engine.base.Engine ('구립 한가람어린이집', '조정자', '서울특별시 광진구 자양번영로2길 30-1 ,(자양동) (자양제2동)', '02', '452', '2800', 6)
2021-08-18 17:41:00,716 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,716 INFO sqlalchemy.engine.base.Engine ('구립금하새빛어린이집', '최예은', '서울특별시 금천구 금하로1가길 10 (독산제1동)', '02', '899', '7457', 8)
2021-08-18 17:41:00,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,718 INFO sqlalchemy.engine.base.Engine ('구립새싹어린이집', '최민서', '서울특별시 금천구 시흥대로34길 9 (시흥제3동)', '02', '892', '1531', 8)
2021-08-18 17:41:00,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,719 INFO sqlalchemy.engine.base.Engine ('구립올고운어린이집', '정민석', '서울특별시 금천구 금하로29길 30 (시흥제2동)', '02', '809', '9970', 8)
2021-08-18 17:41:00,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,721 INFO sqlalchemy.engine.base.Engine ('구립우이한솔어린이집', '김미영', '서울특별시 강북구 4.19로13길 23-3 (우이동)', '02', '902', '7722', 3)
2021-08-18 17:41:00,722 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,723 INFO sqlalchemy.engine.base.Engine ('도란도란어린이집', '윤건우', '서울특별시 마포구 토정로31길 31 (용강동)', '02', '716', '3007', 13)
2021-08-18 17:41:00,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,726 INFO sqlalchemy.engine.base.Engine ('영신어린이집', '서정호', '서울특별시 영등포구 신길로 132 ,(신길동) (신길제4동)', '02', '833', '2841', 20)
2021-08-18 17:41:00,727 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,728 INFO sqlalchemy.engine.base.Engine ('예쁜아이어린이집', '한종수', '서울특별시 영등포구 대방천로 245-19 (신길제6동)', '02', '843', '9898', 20)
2021-08-18 17:41:00,730 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,730 INFO sqlalchemy.engine.base.Engine ('원정어린이집', '박정수', '서울특별시 성북구 보국문로28길 10 (정릉제4동)', '02', '913', '1004', 17)
2021-08-18 17:41:00,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,732 INFO sqlalchemy.engine.base.Engine ('창4동한내어린이집', '최성호', '서울특별시 도봉구 마들로13길 252 (창제4동)', '02', '990', '7044', 10)
2021-08-18 17:41:00,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,735 INFO sqlalchemy.engine.base.Engine ('GKL행복어린이집', '신영철', '서울특별시 중구 남대문로5가 한강대로 416 ,서울스퀘어 5층 (회현동)', '02', '6456', '8816', 24)
2021-08-18 17:41:00,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,736 INFO sqlalchemy.engine.base.Engine ('리나어린이집', '전예준', '서울특별시 강서구 초록마을로22길 24 (화곡본동)', '02', '2602', '9328', 4)
2021-08-18 17:41:00,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,738 INFO sqlalchemy.engine.base.Engine ('블루나인어린이집', '윤유진', '서울특별시 강서구 화곡로66길 186-4 ,186-4 (등촌제1동)', '02', '3665', '9295', 4)
2021-08-18 17:41:00,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,740 INFO sqlalchemy.engine.base.Engine ('효성어린이집', '황진호', '서울특별시 마포구 마포대로 119 ,(공덕동) 4층 (아현동)', '02', '3774', '4678', 13)
2021-08-18 17:41:00,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,742 INFO sqlalchemy.engine.base.Engine ('우리누리송파어린이집', '최성민', '서울특별시 송파구 강동대로 62 ,(풍납동) (풍납2동)', '02', '488', '5450', 18)
2021-08-18 17:41:00,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,743 INFO sqlalchemy.engine.base.Engine ('힐즈어린이집', '이예준', '서울특별시 강남구 자곡로 101 ,래미안강남힐즈어린이집 (세곡동)', '02', '3411', '9663', 1)
2021-08-18 17:41:00,744 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,745 INFO sqlalchemy.engine.base.Engine ('아이누리 어린이집', '신은영', '서울특별시 종로구 사직로8길 20 ,파크팰리스 제1층 제101호 (사직동)', '02', '6959', '7695', 23)
2021-08-18 17:41:00,747 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,747 INFO sqlalchemy.engine.base.Engine ('은솔어린이집', '최민재', '서울특별시 구로구 경인로67길 33 ,101동 1층(신도림동, 아이파크아파트) (신도림동)', '02', '2678', '7728', 7)
2021-08-18 17:41:00,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,749 INFO sqlalchemy.engine.base.Engine ('롯데건설어린이집', '송성호', '서울특별시 서초구 강남대로101안길 33 (잠원동)', '02', '6959', '5580', 15)
2021-08-18 17:41:00,750 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,752 INFO sqlalchemy.engine.base.Engine ('화곡본어린이집', '강지영', '서울특별시 강서구 초록마을로11길 28 (화곡본동)', '02', '2606', '9788', 4)
2021-08-18 17:41:00,753 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,754 INFO sqlalchemy.engine.base.Engine ('예술아이어린이집', '박민서', '서울특별시 성북구 성북로4길 52 ,한진아파트 204동 101호 (돈암제2동)', '02', '928', '1124', 17)

2021-08-18 17:41:00,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,755 INFO sqlalchemy.engine.base.Engine ('선어린이집', '박유진', '서울특별시 양천구 화곡로3길 34 ,102동 104호(신월동, 신도브레뉴2차신월) (신월5동)', '02', '6326', '1031', 19)
2021-08-18 17:41:00,756 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,756 INFO sqlalchemy.engine.base.Engine ('장위도담어린이집', '장민서', '서울특별시 성북구 장위로20길 17-7 (장위제1동)', '02', '911', '0153', 17)
2021-08-18 17:41:00,757 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,761 INFO sqlalchemy.engine.base.Engine ('지구촌어린이집', '김영진', '서울특별시 용산구 회나무로28길 13 (이태원제2동)', '02', '797', '7664', 21)
2021-08-18 17:41:00,762 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,762 INFO sqlalchemy.engine.base.Engine ('강남아이자람어린이집', '강순자', '서울특별시 강남구 자곡로 175 ,704동 102호(자곡동,LH강남아이파크) (세곡동)', '02', '6397', '5999', 1)
2021-08-18 17:41:00,764 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,764 INFO sqlalchemy.engine.base.Engine ('엘키즈 어린이집', '오광수', '서울특별시 성북구 정릉로27길 59 (정릉제2동)', '02', '911', '7780', 17)
2021-08-18 17:41:00,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,768 INFO sqlalchemy.engine.base.Engine ('마곡아이숲어린이집', '전도현', '서울특별시 강서구 마곡중앙로 36 ,1503동 105호(발산1동, 마곡엠밸리15단지) (발산제1동)', '02', '6448', '7839', 4)
2021-08-18 17:41:00,770 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,770 INFO sqlalchemy.engine.base.Engine ('양지2어린이집', '신미영', '서울특별시 서초구 샘마을길 73 (내곡동)', '02', '3411', '3557', 15)
2021-08-18 17:41:00,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,772 INFO sqlalchemy.engine.base.Engine ('구립 매봉도담어린이집', '강성진', '서울특별시 성동구 매봉길 88 (옥수동)', '02', '2293', '3330', 16)
2021-08-18 17:41:00,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,773 INFO sqlalchemy.engine.base.Engine ('구립 텐즈힐두리어린이집', '김성수', '서울특별시 성동구 마장로 137 (왕십리도선동)', '02', '2296', '8200', 16)
2021-08-18 17:41:00,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,775 INFO sqlalchemy.engine.base.Engine ('구립사당4동어린이집', '조정호', '서울특별시 동작구 사당로22나길 70 (사당제4동)', '02', '581', '0010', 12)
2021-08-18 17:41:00,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,776 INFO sqlalchemy.engine.base.Engine ('구립상도3동어린이집', '김민재', '서울특별시 동작구 성대로6가길 5 (상도제3동)', '02', '825', '9153', 12)
2021-08-18 17:41:00,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,777 INFO sqlalchemy.engine.base.Engine ('느티나무어린이집', '박유진', '서울특별시 성북구 흥천사길 29 (돈암제2동)', '02', '927', '1400', 17)
2021-08-18 17:41:00,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,779 INFO sqlalchemy.engine.base.Engine ('보문제일어린이집', '안영철', '서울특별시 성북구 보문동6가 보문로13길 32 (보문동)', '02', '928', '7768', 17)
2021-08-18 17:41:00,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,780 INFO sqlalchemy.engine.base.Engine ('삼선교어린이집', '김경회', '서울특별시 성북구 삼선동3가 삼선교로16가길 41 (삼선동)', '02', '766', '8872', 17)
2021-08-18 17:41:00,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,787 INFO sqlalchemy.engine.base.Engine ('석촌동주민센터어린이집', '이지은', '서울특별시 송파구 백제고분로37길 16 ,석촌동주민센터 1층 (석촌동)', '02', '415', '2100', 18)
2021-08-18 17:41:00,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,790 INFO sqlalchemy.engine.base.Engine ('순복음어린이집', '정지영', '서울특별시 성북구 오패산로 89 (월곡제1동)', '02', '941', '9655', 17)
2021-08-18 17:41:00,791 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,791 INFO sqlalchemy.engine.base.Engine ('연화어린이집', '강지영', '서울특별시 성북구 안암동5가 개운사길 60-46 (안암동)', '02', '921', '5381', 17)
2021-08-18 17:41:00,792 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,793 INFO sqlalchemy.engine.base.Engine ('모래와어린이집', '류지원', '서울특별시 성북구 성북로4길 52 ,203동 102호(돈암동, 한신한진아파트) (돈암제2동)', '02', '6205', '3397', 17)
2021-08-18 17:41:00,793 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,794 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '황성호', '서울특별시 마포구 마포대로 195 ,마포래미안푸르지오아파트 401동 103호 (아현동)', '070', '4133', '3233', 13)
2021-08-18 17:41:00,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,796 INFO sqlalchemy.engine.base.Engine ('동아꼬마숲어린이집', '이성수', '서울특별시 성북구 서경로 31 ,(정릉2동 푸른동아아파트 103동 102호) (정릉제2동)', '02', '943', '3332', 17)
2021-08-18 17:41:00,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,798 INFO sqlalchemy.engine.base.Engine ('더프라임어린이집', '안미경', '서울특별시 용산구 원효로90길 11 ,(원효로1가, 용산더프라임) (원효로제1동)', '02', '712', '1880', 21)
2021-08-18 17:41:00,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,800 INFO sqlalchemy.engine.base.Engine ('에코비어린이집', '신성호', '서울특별시 강남구 자곡로 260 ,402동 102호(자곡동,강남한양수자인) (세곡동)', '02', '3411', '7208', 1)
2021-08-18 17:41:00,802 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,804 INFO sqlalchemy.engine.base.Engine ('꼬마숲아띠어린이집', '황준영', '서울특별시 동대문구 답십리로 130 ,309동 105호(답십리동, 래미안위브아파트) (답십리제1동)', '02', '6012', '5176', 11)
2021-08-18 17:41:00,805 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,807 INFO sqlalchemy.engine.base.Engine ('위례새솔어린이집', '류성수', '서울특별시 송파구 위례순환로 413 ,위례근린공원8호 내 (위례동)', '02', '403', '0011', 18)
2021-08-18 17:41:00,808 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,809 INFO sqlalchemy.engine.base.Engine ('하랑어린이집', '전성수', '서울특별시 동대문구 답십리로 130 ,107동 106호 (답십리동, 래미안위브아파트) (답십리제1동)', '02', '579', '1547', 11)

2021-08-18 17:41:00,810 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,811 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '권성민', '서울특별시 동대문구 답십리로 130 ,106동 106호 (답십리동, 래미안위브아파트) (답십리제1동)', '02', '2212', '5673', 11)
2021-08-18 17:41:00,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,813 INFO sqlalchemy.engine.base.Engine ('마곡3 연두어린이집', '장지혜', '서울특별시 강서구 마곡서1로 132 (방화제1동)', '02', '2666', '3353', 4)
2021-08-18 17:41:00,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,815 INFO sqlalchemy.engine.base.Engine ('구립 대조어린이집', '정지훈', '서울특별시 은평구 역말로 121 (대조동)', '02', '384', '1010', 22)
2021-08-18 17:41:00,815 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,816 INFO sqlalchemy.engine.base.Engine ('개봉푸르지오어린이집', '권정자', '서울특별시 구로구 남부순환로 775 ,개봉푸르지오아파트 복지관1층 개봉푸르지오어린이집 (개봉제1동)', '02', '2615', '5003', 7)
2021-08-18 17:41:00,817 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,818 INFO sqlalchemy.engine.base.Engine ('구립기리울어린이집', '윤지민', '서울특별시 강동구 진황도로49길 17 ,(길동244-3) (길동)', '02', '485', '2212', 2)
2021-08-18 17:41:00,819 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,824 INFO sqlalchemy.engine.base.Engine ('구립동심어린이집', '장준호', '서울특별시 강동구 고덕로27길 33-19 (암사제3동)', '02', '429', '7787', 2)
2021-08-18 17:41:00,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,827 INFO sqlalchemy.engine.base.Engine ('구립마장현대어린이집', '최성호', '서울특별시 성동구 마장로35길 76 ,마장현대아파트 관리동 1층 (마장동)', '02', '2281', '9281', 16)
2021-08-18 17:41:00,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,829 INFO sqlalchemy.engine.base.Engine ('성북생명숲어린이집', '신정순', '서울특별시 성북구 서경로 173 (정릉제4동)', '02', '3292', '1671', 17)
2021-08-18 17:41:00,831 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,835 INFO sqlalchemy.engine.base.Engine ('연우어린이집', '조현준', '서울특별시 구로구 천왕로 50 ,천왕이펜하우스 s (오류제2동)', '02', '2612', '3378', 7)
2021-08-18 17:41:00,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,837 INFO sqlalchemy.engine.base.Engine ('하니어린이집', '송동현', '서울특별시 마포구 마포대로 195 ,마포래미안푸르지오아파트 105동 105호 (아현동)', '02', '376', '1005', 13)
2021-08-18 17:41:00,839 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,839 INFO sqlalchemy.engine.base.Engine ('구립 서울숲더샵어린이집', '정영진', '서울특별시 성동구 왕십리로 241 ,서울숲더샵아 1층 (사근동)', '02', '2296', '2014', 16)
2021-08-18 17:41:00,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,841 INFO sqlalchemy.engine.base.Engine ('새서울어린이집', '신정호', '서울특별시 동대문구 한천로26길 23 ,(장안동) (장안제1동)', '02', '2245', '4804', 11)
2021-08-18 17:41:00,842 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,843 INFO sqlalchemy.engine.base.Engine ('자곡어린이집', '윤은영', '서울특별시 강남구 자곡로 175 ,LH 강남아이파크(관리동) (세곡동)', '02', '445', '3340', 1)
2021-08-18 17:41:00,844 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,845 INFO sqlalchemy.engine.base.Engine ('휘경스마일어린이집', '한영환', '서울특별시 동대문구 이문로8길 8-7 (휘경제1동)', '02', '959', '6401', 11)
2021-08-18 17:41:00,847 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,847 INFO sqlalchemy.engine.base.Engine ('래미안위브어린이집', '윤성호', '서울특별시 동대문구 답십리로 130 ,2단지 (답십리동, 래미안위브아파트) (답십리제1동)', '02', '2244', '8881', 11)
2021-08-18 17:41:00,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,851 INFO sqlalchemy.engine.base.Engine ('솔샘숲어린이집', '김지훈', '서울특별시 동대문구 답십리로 130 ,1단지 (답십리동, 래미안위브아파트) (답십리제1동)', '02', '3394', '7724', 11)
2021-08-18 17:41:00,852 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,853 INFO sqlalchemy.engine.base.Engine ('마곡1 하람어린이집', '황영길', '서울특별시 강서구 마곡서1로 131 (방화제1동)', '02', '2663', '0101', 4)
2021-08-18 17:41:00,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,854 INFO sqlalchemy.engine.base.Engine ('마곡14 아이마당어린이집', '강건우', '서울특별시 강서구 마곡중앙로 33 ,상가동 1층 (발산제1동)', '02', '2661', '1477', 4)
2021-08-18 17:41:00,855 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,856 INFO sqlalchemy.engine.base.Engine ('마곡15 누리어린이집', '박예준', '서울특별시 강서구 마곡중앙로 36 (발산제1동)', '02', '2663', '0015', 4)
2021-08-18 17:41:00,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,859 INFO sqlalchemy.engine.base.Engine ('마곡2 해오름어린이집', '한현정', '서울특별시 강서구 마곡서1로 146 (방화제1동)', '02', '2661', '0204', 4)
2021-08-18 17:41:00,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,862 INFO sqlalchemy.engine.base.Engine ('마곡4 꿈의숲어린이집', '김순자', '서울특별시 강서구 마곡서로 175 (가양제1동)', '02', '2663', '4440', 4)
2021-08-18 17:41:00,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,870 INFO sqlalchemy.engine.base.Engine ('마곡5 해맑은어린이집', '송정수', '서울특별시 강서구 마곡서1로 111-11 (방화제1동)', '02', '2666', '0008', 4)
2021-08-18 17:41:00,874 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,877 INFO sqlalchemy.engine.base.Engine ('마곡6 마곡숲어린이집', '박상철', '서울특별시 강서구 마곡서1로 100 (방화제1동)', '02', '2698', '1004', 4)
2021-08-18 17:41:00,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,880 INFO sqlalchemy.engine.base.Engine ('마곡7 미래꿈어린이집', '안지영', '서울특별시 강서구 마곡서로 133 (방화제1동)', '02', '2664', '0707', 4)
2021-08-18 17:41:00,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,882 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '오상철', '서울특별시 강남구 자곡로3길 45 ,강남 브리즈힐(관리동) (세곡동)', '02', '445', '0045', 1)

2021-08-18 17:41:00,883 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,884 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '이지은', '서울특별시 송파구 위례광장로 163 ,2202동 103호 (위례동)', '02', '404', '5225', 18)
2021-08-18 17:41:00,885 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,886 INFO sqlalchemy.engine.base.Engine ('꿈솜어린이집', '조영환', '서울특별시 성북구 길음로 16 ,610동 101호(길음동, 길음래미안3차) (길음제1동)', '02', '909', '9600', 17)
2021-08-18 17:41:00,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,888 INFO sqlalchemy.engine.base.Engine ('드림어린이집', '황은정', '서울특별시 중랑구 겸재로64길 23 ,(면목동) (면목제3.8동)', '02', '493', '1692', 25)
2021-08-18 17:41:00,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,890 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '황민지', '서울특별시 마포구 마포대로 195 ,아현동, 마포래미안푸르지오1단지 어린이집 (아현동)', '02', '365', '6639', 13)
2021-08-18 17:41:00,892 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,893 INFO sqlalchemy.engine.base.Engine ('아띠어린이집', '류상훈', '서울특별시 성북구 성북로4길 52 ,111동 106호(돈암동, 한신한진아파트) (돈암제2동)', '02', '924', '1258', 17)
2021-08-18 17:41:00,894 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,895 INFO sqlalchemy.engine.base.Engine ('오즈어린이집', '이동현', '서울특별시 마포구 마포대로 195 ,아현동, 마포래미안푸르지오 4단지 어린이집 (아현동)', '02', '363', '0030', 13)
2021-08-18 17:41:00,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,896 INFO sqlalchemy.engine.base.Engine ('토리어린이집', '장예은', '서울특별시 마포구 마포대로 195 ,아현동, 마포래미안푸르지오 3단지 어린이집 (아현동)', '02', '6278', '3537', 13)
2021-08-18 17:41:00,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,898 INFO sqlalchemy.engine.base.Engine ('아람에듀어린이집', '조정자', '서울특별시 마포구 망원로3길 44 ,(망원동) (망원제2동)', '02', '337', '1637', 13)
2021-08-18 17:41:00,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,899 INFO sqlalchemy.engine.base.Engine ('강서한강자이어린이집', '송예은', '서울특별시 강서구 양천로55길 55 ,강서한강자이 관리동어린이집 (가양제1동)', '02', '3661', '4650', 4)
2021-08-18 17:41:00,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,902 INFO sqlalchemy.engine.base.Engine ('진양아이어린이집', '서준서', '서울특별시 강서구 까치산로 18-10 (화곡본동)', '02', '2699', '9041', 4)
2021-08-18 17:41:00,903 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,904 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '정준혁', '서울특별시 강서구 우현로 67 ,118-101(화곡동,강서힐스테이트) (우장산동)', '02', '2601', '6833', 4)
2021-08-18 17:41:00,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,906 INFO sqlalchemy.engine.base.Engine ('구립해여울어린이집', '강수빈', '서울특별시 강동구 상일로12길 60 ,1층(상일동 483) (상일제2동)', '02', '429', '8556', 2)
2021-08-18 17:41:00,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,908 INFO sqlalchemy.engine.base.Engine ('리라어린이집', '임정운', '서울특별시 강서구 초록마을로18길 36 (화곡본동)', '02', '2605', '3355', 4)
2021-08-18 17:41:00,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,910 INFO sqlalchemy.engine.base.Engine ('구립 갈산어린이집', '안유진', '서울특별시 양천구 목동남로4길 48-6 (신정7동)', '02', '2642', '4225', 19)
2021-08-18 17:41:00,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,912 INFO sqlalchemy.engine.base.Engine ('구립 도시마을어린이집', '한도현', '서울특별시 양천구 신정로13가길 6 (신정3동)', '02', '2690', '8885', 19)
2021-08-18 17:41:00,913 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,914 INFO sqlalchemy.engine.base.Engine ('구립도담어린이집', '황현정', '서울특별시 금천구 독산로32나길 48 (시흥제4동)', '02', '891', '0080', 8)
2021-08-18 17:41:00,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,916 INFO sqlalchemy.engine.base.Engine ('구립튼튼이어린이집', '박성호', '서울특별시 금천구 독산로50길 23 (시흥제4동)', '02', '809', '9868', 8)
2021-08-18 17:41:00,917 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,918 INFO sqlalchemy.engine.base.Engine ('구립한빛어린이집', '조병철', '서울특별시 금천구 시흥대로118길 23 (독산제4동)', '02', '855', '0966', 8)
2021-08-18 17:41:00,919 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,920 INFO sqlalchemy.engine.base.Engine ('신원어린이집', '장영길', '서울특별시 강서구 양천로77길 45 ,무학아파트 상가동 (염창동)', '02', '2659', '3967', 4)
2021-08-18 17:41:00,921 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,922 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '황은영', '서울특별시 강남구 광평로34길 55 ,강남데시앙포레아파트 114동 103호 (일원본동)', '02', '6677', '6984', 1)
2021-08-18 17:41:00,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,924 INFO sqlalchemy.engine.base.Engine ('보석어린이집', '장미숙', '서울특별시 중랑구 신내역로1길 85 ,101동103호(신내동,신내우디안1단지) (신내1동)', '02', '3421', '4202', 25)
2021-08-18 17:41:00,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,926 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '서지영', '서울특별시 강서구 마곡중앙로 33 ,1401동 102호 (발산제1동)', '02', '2663', '0675', 4)
2021-08-18 17:41:00,927 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,927 INFO sqlalchemy.engine.base.Engine ('하람어린이집', '신영철', '서울특별시 중랑구 신내역로1길 85 ,(신내동, 신내우디안1단지아파트 관리동) (신내1동)', '02', '3423', '3733', 25)
2021-08-18 17:41:00,929 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,931 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '오종수', '서울특별시 성동구 성수동1가 상원길 63 ,101동 103호(성수동1가, 쌍용아파트) (성수1가제2동)', '02', '498', '5579', 16)
2021-08-18 17:41:00,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,934 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '조민지', '서울특별시 강서구 마곡중앙로 33 ,마곡엠밸리 14단지 1403-105 (발산제1동)', '02', '6214', '5887', 4)

2021-08-18 17:41:00,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,936 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '임준영', '서울특별시 구로구 개봉로18길 35 (개봉제2동)', '070', '4228', '5043', 7)
2021-08-18 17:41:00,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,938 INFO sqlalchemy.engine.base.Engine ('라임어린이집', '이영철', '서울특별시 강서구 우현로 67 ,113동 103호(화곡동,강서힐스테이트) (우장산동)', '02', '2693', '2693', 4)
2021-08-18 17:41:00,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,941 INFO sqlalchemy.engine.base.Engine ('새싹과 나무어린이집', '김준서', '서울특별시 강서구 마곡서로 175 ,403동 101호(마곡동, 마곡엠밸리4단지) (가양제1동)', '02', '6223', '4613', 4)
2021-08-18 17:41:00,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,945 INFO sqlalchemy.engine.base.Engine ('세화어린이집', '황건우', '서울특별시 양천구 목동서로2길 22 ,101동 104호 (목5동, 한신청구아파트) (목5동)', '02', '2654', '2727', 19)
2021-08-18 17:41:00,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,947 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '임민지', '서울특별시 성북구 화랑로48길 16 ,106동 101호(석관동, 두산아파트) (석관동)', '02', '6397', '1253', 17)
2021-08-18 17:41:00,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,949 INFO sqlalchemy.engine.base.Engine ('구립양지어린이집', '송영철', '서울특별시 성동구 난계로 160 (왕십리도선동)', '02', '2299', '9312', 16)
2021-08-18 17:41:00,950 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,951 INFO sqlalchemy.engine.base.Engine ('아이큰숲아기학교어린이집', '신영환', '서울특별시 강서구 초록마을로21길 29 (화곡본동)', '02', '2607', '2235', 4)
2021-08-18 17:41:00,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,953 INFO sqlalchemy.engine.base.Engine ('구립 왕도어린이집', '최미숙', '서울특별시 성동구 무학로6길 9 (왕십리도선동)', '02', '2299', '3889', 16)
2021-08-18 17:41:00,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,955 INFO sqlalchemy.engine.base.Engine ('구립성이어린이집', '장예준', '서울특별시 성동구 성수동2가 성수이로6길 10-2 (성수2가제1동)', '02', '464', '5757', 16)
2021-08-18 17:41:00,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,957 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '최영길', '서울특별시 강서구 마곡서1로 111-11 ,마곡엠밸리 503-104 (방화제1동)', '070', '8253', '9495', 4)
2021-08-18 17:41:00,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,959 INFO sqlalchemy.engine.base.Engine ('우리아이어린이집', '신지영', '서울특별시 강서구 마곡서1로 100 ,마곡엠밸리 609동 104호 (방화제1동)', '02', '2064', '0704', 4)
2021-08-18 17:41:00,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,962 INFO sqlalchemy.engine.base.Engine ('포도나무어린이집', '최민서', '서울특별시 강서구 마곡중앙로 36 ,마곡엠벨리 15단지 1513-127 (발산제1동)', '02', '3662', '9107', 4)
2021-08-18 17:41:00,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,968 INFO sqlalchemy.engine.base.Engine ('별나라어린이집', '서준호', '서울특별시 강서구 우현로 67 ,108동 101호(화곡동, 강서힐스테이트) (우장산동)', '02', '2603', '2378', 4)
2021-08-18 17:41:00,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,970 INFO sqlalchemy.engine.base.Engine ('서초더샵포레어린이집', '오지영', '서울특별시 서초구 헌릉로8길 58 ,104동 1층 (내곡동)', '02', '573', '0812', 15)
2021-08-18 17:41:00,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,972 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '송준서', '서울특별시 강서구 우현로 67 ,119동 103호 (우장산동)', '02', '2602', '1514', 4)
2021-08-18 17:41:00,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,974 INFO sqlalchemy.engine.base.Engine ('예삐어린이집', '류영철', '서울특별시 성북구 길음로9길 40 ,111동 101호(길음동) (길음제1동)', '070', '5022', '0298', 17)
2021-08-18 17:41:00,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,976 INFO sqlalchemy.engine.base.Engine ('구립 갈현1어린이집', '신지은', '서울특별시 은평구 연서로29길 30-13 ,구립 갈현1어린이집 (갈현제1동)', '02', '353', '9455', 22)
2021-08-18 17:41:00,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,979 INFO sqlalchemy.engine.base.Engine ('조이어린이집', '윤유진', '서울특별시 송파구 위례광장로 121 ,2411동 104호 (위례동)', '02', '431', '2222', 18)
2021-08-18 17:41:00,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,981 INFO sqlalchemy.engine.base.Engine ('리베폴어린이집', '송준호', '서울특별시 강서구 마곡서1로 100 ,마곡엠밸리 605-101 (방화제1동)', '02', '2665', '2004', 4)
2021-08-18 17:41:00,982 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,983 INFO sqlalchemy.engine.base.Engine ('창경어린이집', '한준호', '서울특별시 종로구 성균관로1길 6-3 (혜화동)', '02', '766', '1514', 23)
2021-08-18 17:41:00,984 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,985 INFO sqlalchemy.engine.base.Engine ('국회제3어린이집', '정현준', '서울특별시 영등포구 의사당대로 1 (여의동)', '02', '780', '3420', 20)
2021-08-18 17:41:00,986 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,987 INFO sqlalchemy.engine.base.Engine ('서초구립 리본타워2단지어린이집', '최성호', '서울특별시 서초구 매헌로16길 40 ,양재리본타워2단지 관리동(양재동) (양재2동)', '02', '575', '8833', 15)
2021-08-18 17:41:00,988 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,989 INFO sqlalchemy.engine.base.Engine ('서초구립 포레스타3단지어린이집', '신수빈', '서울특별시 서초구 헌릉로8길 22 ,305동 1층 (내곡동)', '02', '3462', '1471', 15)
2021-08-18 17:41:00,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,990 INFO sqlalchemy.engine.base.Engine ('예다움보듬이나눔이어린이집', '강정호', '서울특별시 구로구 개봉로 29 (개봉제3동)', '02', '2689', '9760', 7)
2021-08-18 17:41:00,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,992 INFO sqlalchemy.engine.base.Engine ('가온어린이집', '정민지', '서울특별시 성북구 오패산로3길 17 ,101동 101호(하월곡동, 동신아파트) (월곡제1동)', '02', '909', '3302', 17)

2021-08-18 17:41:00,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,994 INFO sqlalchemy.engine.base.Engine ('광림어린이집', '정도현', '서울특별시 강남구 논현로175길 49 (신사동)', '02', '2056', '5743', 1)
2021-08-18 17:41:00,995 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,996 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '오성민', '서울특별시 영등포구 대방천로 180 ,206동 101호(신길동,신길우성2차아파트) (신길제6동)', '02', '844', '5556', 20)
2021-08-18 17:41:00,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:00,999 INFO sqlalchemy.engine.base.Engine ('햇살내리는어린이집', '박지훈', '서울특별시 성북구 성북로14가길 17-11 ,101호 (성북동)', '02', '6093', '0701', 17)
2021-08-18 17:41:01,000 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,000 INFO sqlalchemy.engine.base.Engine ('그림숲어린이집', '장준혁', '서울특별시 용산구 서빙고로71길 62 ,(동빙고동) (서빙고동)', '02', '790', '2796', 21)
2021-08-18 17:41:01,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,002 INFO sqlalchemy.engine.base.Engine ('창5동가인어린이집', '박성민', '서울특별시 도봉구 노해로63길 43 ,1층 (창제5동)', '02', '996', '7787', 10)
2021-08-18 17:41:01,004 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,005 INFO sqlalchemy.engine.base.Engine ('아기별어린이집', '임상훈', '서울특별시 송파구 중대로 24 ,올림픽훼밀리타운 105동 105호 (문정2동)', '02', '443', '2346', 18)
2021-08-18 17:41:01,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,006 INFO sqlalchemy.engine.base.Engine ('꽃가람어린이집', '이민서', '서울특별시 성동구 마장로 137 ,208동 101호(상왕십리동, 텐즈힐 아파트) (왕십리도선동)', '02', '2299', '6400', 16)
2021-08-18 17:41:01,008 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,009 INFO sqlalchemy.engine.base.Engine ('프레스티지어린이집', '황도현', '서울특별시 동작구 상도로 346-2 ,힐스테이트 상도프레스티지 202동 관리동 (상도제1동)', '02', '6140', '9114', 12)
2021-08-18 17:41:01,010 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,011 INFO sqlalchemy.engine.base.Engine ('서초구립 포레스타5단지어린이집', '강민재', '서울특별시 서초구 청계산로7길 43 ,510동 1층 (내곡동)', '02', '576', '1226', 15)
2021-08-18 17:41:01,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,013 INFO sqlalchemy.engine.base.Engine ('빛나라어린이집', '송민지', '서울특별시 양천구 목동서로 100 ,317동 104호(목5동, 목동아파트3단지) (목5동)', '02', '2646', '8595', 19)
2021-08-18 17:41:01,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,016 INFO sqlalchemy.engine.base.Engine ('영문어린이집', '한성민', '서울특별시 영등포구 문래동4가 도림로143길 32 ,문래동삼환아파트 105동 102호 (문래동)', '02', '2671', '0998', 20)
2021-08-18 17:41:01,017 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,018 INFO sqlalchemy.engine.base.Engine ('센트라스어린이집', '정순자', '서울특별시 성동구 왕십리로 410 ,122동 102호(하왕십리동, 센트라스) (왕십리도선동)', '02', '2299', '1025', 16)
2021-08-18 17:41:01,019 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,020 INFO sqlalchemy.engine.base.Engine ('그린애플어린이집', '이미경', '서울특별시 양천구 중앙로29길 61 ,107동 107호 (신월2동)', '02', '6341', '1070', 19)
2021-08-18 17:41:01,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,023 INFO sqlalchemy.engine.base.Engine ('엔젤라어린이집', '황준서', '서울특별시 양천구 오목로5길 20 ,202동 102호 (신월동, 양천롯데캐슬) (신월4동)', '02', '6378', '1008', 19)
2021-08-18 17:41:01,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,025 INFO sqlalchemy.engine.base.Engine ('구립 극동그린어린이집', '최은영', '서울특별시 성동구 독서당로 175 (옥수동)', '02', '2281', '9297', 16)
2021-08-18 17:41:01,025 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,027 INFO sqlalchemy.engine.base.Engine ('쌍문3동빛초롱어린이집', '조정웅', '서울특별시 도봉구 노해로48길 67-6 (쌍문제3동)', '02', '996', '8501', 10)
2021-08-18 17:41:01,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,029 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '류은영', '서울특별시 성북구 솔샘로5길 7 (정릉제3동)', '02', '913', '9755', 17)
2021-08-18 17:41:01,030 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,031 INFO sqlalchemy.engine.base.Engine ('초원어린이집', '임경자', '서울특별시 성북구 월곡로5길 39 (종암동)', '02', '916', '6238', 17)
2021-08-18 17:41:01,031 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,032 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '정지은', '서울특별시 성북구 돌곶이로34길 4-14 ,(장위2동 75-616) (장위제2동)', '02', '915', '3388', 17)
2021-08-18 17:41:01,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,034 INFO sqlalchemy.engine.base.Engine ('꼬망새어린이집', '황경숙', '서울특별시 강남구 밤고개로21길 25 ,306동 102호(자곡동, 래미안포레) (세곡동)', '02', '6674', '1001', 1)
2021-08-18 17:41:01,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,037 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '박은경', '서울특별시 송파구 올림픽로 435 ,113동 103호(신천동, 파크리오아파트) (잠실4동)', '02', '419', '2230', 18)
2021-08-18 17:41:01,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,040 INFO sqlalchemy.engine.base.Engine ('아기숲어린이집', '김지은', '서울특별시 송파구 중대로 317-14 (오금동)', '02', '421', '4179', 18)
2021-08-18 17:41:01,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,042 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '최지원', '서울특별시 마포구 매봉산로 37 ,DMC산학협력센터 (상암동)', '02', '304', '7630', 13)
2021-08-18 17:41:01,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,044 INFO sqlalchemy.engine.base.Engine ('참사랑서밋어린이집', '강경회', '서울특별시 송파구 동남로18길 45 (가락2동)', '02', '458', '5999', 18)
2021-08-18 17:41:01,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,046 INFO sqlalchemy.engine.base.Engine ('해랑어린이집', '전민서', '서울특별시 양천구 목동중앙남로14길 6 (목3동)', '02', '2649', '6032', 19)

2021-08-18 17:41:01,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,048 INFO sqlalchemy.engine.base.Engine ('메리츠어린이집', '안예준', '서울특별시 영등포구 국제금융로2길 11 (여의동)', '02', '6464', '3310', 20)
2021-08-18 17:41:01,048 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,049 INFO sqlalchemy.engine.base.Engine ('목동하나금융그룹 직장어린이집', '이성민', '서울특별시 양천구 목동동로 347 ,3층 (목5동)', '02', '2654', '9108', 19)
2021-08-18 17:41:01,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,052 INFO sqlalchemy.engine.base.Engine ('구립수유새싹어린이집', '이지훈', '서울특별시 강북구 덕릉로 4-5 (수유1동)', '02', '985', '1700', 3)
2021-08-18 17:41:01,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,054 INFO sqlalchemy.engine.base.Engine ('구립오동어린이집', '임현정', '서울특별시 강북구 도봉로78길 61 (번2동)', '02', '981', '8811', 3)
2021-08-18 17:41:01,055 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,055 INFO sqlalchemy.engine.base.Engine ('세곡나비어린이집', '송서연', '서울특별시 강남구 자곡로 230 ,래미안포레(관리동) (세곡동)', '02', '3412', '7755', 1)
2021-08-18 17:41:01,057 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,058 INFO sqlalchemy.engine.base.Engine ('세곡햇빛어린이집', '오은영', '서울특별시 강남구 자곡로 260 ,강남한양수자인(관리동) (세곡동)', '02', '451', '5088', 1)
2021-08-18 17:41:01,059 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,060 INFO sqlalchemy.engine.base.Engine ('자람터어린이집', '장정자', '서울특별시 구로구 디지털로26길 5 ,에이스하이엔드타워 1차 201호 (구로제3동)', '02', '6220', '2928', 7)
2021-08-18 17:41:01,061 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,062 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '황정식', '서울특별시 강남구 자곡로 260 ,한양수자인아파트 407동 106호 (세곡동)', '02', '3414', '1004', 1)
2021-08-18 17:41:01,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,064 INFO sqlalchemy.engine.base.Engine ('튼튼키즈어린이집', '임정자', '서울특별시 강서구 등촌로39라길 19 (등촌제2동)', '02', '2653', '3133', 4)
2021-08-18 17:41:01,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,066 INFO sqlalchemy.engine.base.Engine ('모래와 어린이집', '강정호', '서울특별시 마포구 도화길 28 ,마포삼성아파트 113동 101호 (도화동)', '02', '719', '3133', 13)
2021-08-18 17:41:01,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,069 INFO sqlalchemy.engine.base.Engine ('구민회관어린이집', '최민재', '서울특별시 종로구 지봉로5길 7-5 ,(창신동 222-8) (창신제1동)', '02', '744', '9700', 23)
2021-08-18 17:41:01,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,072 INFO sqlalchemy.engine.base.Engine ('수도방위사령부 한울어린이집', '황민서', '서울특별시 관악구 과천대로 851 (남현동)', '02', '524', '1614', 5)
2021-08-18 17:41:01,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,077 INFO sqlalchemy.engine.base.Engine ('위례수어린이집', '오은영', '서울특별시 송파구 위례광장로 121 ,2401동 105호 (위례동)', '02', '403', '8797', 18)
2021-08-18 17:41:01,078 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,079 INFO sqlalchemy.engine.base.Engine ('청아어린이집', '윤동현', '서울특별시 마포구 토정로35길 17 (용강동)', '02', '3273', '7979', 13)
2021-08-18 17:41:01,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,081 INFO sqlalchemy.engine.base.Engine ('푸른숲속어린이집', '최건우', '서울특별시 용산구 효창원로 17 ,104동 103호(산천동, 리버힐삼성아파트) (원효로제2동)', '02', '701', '5437', 21)
2021-08-18 17:41:01,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,083 INFO sqlalchemy.engine.base.Engine ('풀무원어린이집', '최서연', '서울특별시 강남구 광평로 280 ,4층 (수서동)', '02', '3412', '7007', 1)
2021-08-18 17:41:01,089 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,090 INFO sqlalchemy.engine.base.Engine ('LH서울어린이집', '박지은', '서울특별시 강남구 선릉로121길 12 (논현2동)', '02', '3416', '3687', 1)
2021-08-18 17:41:01,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,092 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '권영진', '서울특별시 동대문구 사가정로 65 ,206동 104호 (전농1동, 래미안크레시티) (전농제1동)', '02', '2242', '2290', 11)
2021-08-18 17:41:01,093 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,094 INFO sqlalchemy.engine.base.Engine ('노벨어린이집', '황지은', '서울특별시 용산구 후암로22길 10 ,104호(후암동) (후암동)', '02', '796', '7270', 21)
2021-08-18 17:41:01,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,096 INFO sqlalchemy.engine.base.Engine ('롯데아이사랑어린이집', '류정호', '서울특별시 영등포구 양평동4가 선유로49길 30 (양평제2동)', '070', '4849', '4493', 20)
2021-08-18 17:41:01,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,098 INFO sqlalchemy.engine.base.Engine ('용두동어린이집', '서경자', '서울특별시 동대문구 왕산로17길 14 ,(용두동) (용신동)', '02', '921', '3119', 11)
2021-08-18 17:41:01,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,100 INFO sqlalchemy.engine.base.Engine ('구립 신목동어린이집', '최영철', '서울특별시 양천구 신정로 275 ,신트리아파트 201동 (신정동) (신정3동)', '02', '2065', '8590', 19)
2021-08-18 17:41:01,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,102 INFO sqlalchemy.engine.base.Engine ('구립 은솔어린이집', '장민서', '서울특별시 양천구 신정로14길 1 ,학마을아파트2단지보육시설 (신정동) (신정3동)', '02', '2065', '8767', 19)
2021-08-18 17:41:01,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,103 INFO sqlalchemy.engine.base.Engine ('구립새롬어린이집', '신순자', '서울특별시 금천구 독산로58가길 88 (독산제2동)', '02', '808', '9377', 8)
2021-08-18 17:41:01,104 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,105 INFO sqlalchemy.engine.base.Engine ('구립예림어린이집', '황건우', '서울특별시 강북구 도봉로99길 58 ,(수유동) (수유3동)', '02', '904', '9400', 3)
2021-08-18 17:41:01,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,107 INFO sqlalchemy.engine.base.Engine ('방학가람어린이집', '한정호', '서울특별시 도봉구 방학로8길 32 ,(방학동) (방학제1동)', '02', '3493', '0001', 10)
2021-08-18 17:41:01,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,108 INFO sqlalchemy.engine.base.Engine ('신촌사랑어린이집', '황경숙', '서울특별시 마포구 숭문6길 22 (염리동)', '02', '706', '3026', 13)
2021-08-18 17:41:01,109 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,110 INFO sqlalchemy.engine.base.Engine ('MBC푸르니어린이집', '윤영진', '서울특별시 마포구 성암로 267 (상암동)', '02', '789', '2205', 13)
2021-08-18 17:41:01,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,113 INFO sqlalchemy.engine.base.Engine ('숙명여자대학교어린이집', '임경회', '서울특별시 용산구 청파동2가 청파로47길 100 ,숙명여자대학교 사회교육관 1층 (청파동)', '02', '2077', '7952', 21)
2021-08-18 17:41:01,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,114 INFO sqlalchemy.engine.base.Engine ('포도나무어린이집', '이지훈', '서울특별시 중랑구 신내역로 165 ,201동 103호(신내동, 우디안아파트) (신내1동)', '02', '3421', '0678', 25)
2021-08-18 17:41:01,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,117 INFO sqlalchemy.engine.base.Engine ('현대해상 온마음어린이집', '전정웅', '서울특별시 종로구 신문로2가 경희궁1길 9 (사직동)', '02', '725', '5355', 23)
2021-08-18 17:41:01,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,120 INFO sqlalchemy.engine.base.Engine ('디딤돌어린이집', '이영길', '서울특별시 송파구 백제고분로23길 25 (삼전동)', '02', '416', '1589', 18)
2021-08-18 17:41:01,122 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,126 INFO sqlalchemy.engine.base.Engine ('DB손해보험 아이사랑 어린이집', '한성수', '서울특별시 용산구 후암로 107 ,게이트웨이타워 (남영동)', '02', '771', '8607', 21)
2021-08-18 17:41:01,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,129 INFO sqlalchemy.engine.base.Engine ('새로미어린이집', '류현정', '서울특별시 구로구 오리로 1102-10 ,213동 104호(천왕동, 천왕연지타운2단지아파트) (오류제2동)', '02', '6224', '1215', 7)
2021-08-18 17:41:01,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,131 INFO sqlalchemy.engine.base.Engine ('숭실대학교어린이집', '안광수', '서울특별시 동작구 상도로67길 20 (상도제1동)', '02', '816', '4040', 12)
2021-08-18 17:41:01,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,133 INFO sqlalchemy.engine.base.Engine ('사랑이어린이집', '박지혜', '서울특별시 은평구 응암로 232-1 (응암제2동)', '02', '308', '8028', 22)
2021-08-18 17:41:01,134 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,134 INFO sqlalchemy.engine.base.Engine ('신공덕삼성 어린이집', '정영환', '서울특별시 마포구 백범로37길 12 ,106-101(신공덕동, 신공덕1차삼성래미안아파트) (공덕동)', '02', '716', '0101', 13)
2021-08-18 17:41:01,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,136 INFO sqlalchemy.engine.base.Engine ('도담아이 어린이집', '오성민', '서울특별시 성동구 행당로 79 ,119동 103호(행당동, 대림아파트) (행당제2동)', '02', '6213', '5410', 16)
2021-08-18 17:41:01,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,138 INFO sqlalchemy.engine.base.Engine ('라임어린이집', '강정호', '서울특별시 중랑구 중랑역로 234-7 (묵제2동)', '02', '976', '2937', 25)
2021-08-18 17:41:01,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,140 INFO sqlalchemy.engine.base.Engine ('LG광화문어린이집', '류예준', '서울특별시 종로구 신문로2가 새문안로 58 (사직동)', '070', '4065', '0286', 23)
2021-08-18 17:41:01,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,141 INFO sqlalchemy.engine.base.Engine ('아이젤어린이집', '전준호', '서울특별시 은평구 응암로22길 9-9 (응암제2동)', '02', '385', '7020', 22)
2021-08-18 17:41:01,143 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,143 INFO sqlalchemy.engine.base.Engine ('정원어린이집', '윤정순', '서울특별시 양천구 남부순환로29길 17-1 (신월5동)', '02', '2603', '0258', 19)
2021-08-18 17:41:01,145 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,146 INFO sqlalchemy.engine.base.Engine ('꿈에그린어린이집', '안민석', '서울특별시 송파구 위례광장로 121 ,장지동 901, 위례24단지 2413동 101호 (위례동)', '02', '401', '7775', 18)
2021-08-18 17:41:01,147 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,148 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '한종수', '서울특별시 구로구 항동로 42 ,506동 103호(한양수자인에듀힐즈) (항동)', '02', '6085', '9000', 7)
2021-08-18 17:41:01,149 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,151 INFO sqlalchemy.engine.base.Engine ('방학동행복한어린이집', '류경회', '서울특별시 도봉구 도당로6길 36 (방학제1동)', '02', '3494', '6647', 10)
2021-08-18 17:41:01,154 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,154 INFO sqlalchemy.engine.base.Engine ('위례키즈어린이집', '장정호', '서울특별시 송파구 위례광장로 163 ,장지동 879, 위례22단지 2208동 102호 (위례동)', '02', '400', '4468', 18)
2021-08-18 17:41:01,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,156 INFO sqlalchemy.engine.base.Engine ('한화태평로어린이집', '김지훈', '서울특별시 중구 태평로2가 세종대로 92 ,4층 (소공동)', '02', '6366', '7120', 24)
2021-08-18 17:41:01,157 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,158 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '송수빈', '서울특별시 중랑구 신내역로 165 ,(신내동, 신내우디안2단지아파트 관리동) (신내1동)', '02', '3422', '1592', 25)
2021-08-18 17:41:01,158 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,159 INFO sqlalchemy.engine.base.Engine ('한화여의도어린이집', '황지영', '서울특별시 영등포구 여의대로 56 (여의동)', '02', '3772', '8165', 20)
2021-08-18 17:41:01,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,161 INFO sqlalchemy.engine.base.Engine ('단이슬어린이집', '신정수', '서울특별시 강서구 공항대로8가길 40 (공항동)', '02', '3662', '2313', 4)
2021-08-18 17:41:01,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,163 INFO sqlalchemy.engine.base.Engine ('마미맘어린이집', '이준호', '서울특별시 중랑구 신내역로 165 ,213동 103호(신내동,우디안아파트) (신내1동)', '02', '6232', '9500', 25)
2021-08-18 17:41:01,164 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,164 INFO sqlalchemy.engine.base.Engine ('엔젤키즈어린이집', '오영숙', '서울특별시 종로구 자하문로43길 4-13 (부암동)', '02', '379', '5133', 23)
2021-08-18 17:41:01,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,166 INFO sqlalchemy.engine.base.Engine ('창신제일어린이집', '강영자', '서울특별시 종로구 낙산성곽동길 69 ,창신동 (창신제2동)', '02', '3675', '1084', 23)
2021-08-18 17:41:01,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,167 INFO sqlalchemy.engine.base.Engine ('GS건설 꿈과 희망의 어린이집', '최광수', '서울특별시 종로구 종로 33 ,그랑서울 타워2 (2층) (종로1.2.3.4가동)', '02', '3789', '5971', 23)
2021-08-18 17:41:01,168 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,168 INFO sqlalchemy.engine.base.Engine ('연초롱어린이집', '신지은', '서울특별시 구로구 오리로 1102-10 ,천왕2지구 2단지 209동1층 (오류제2동)', '02', '2066', '2500', 7)
2021-08-18 17:41:01,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,170 INFO sqlalchemy.engine.base.Engine ('다니엘어린이집', '권상훈', '서울특별시 강서구 양천로55길 55 ,108동 102호(가양동, 가양한강자이) (가양제1동)', '02', '3663', '5958', 4)
2021-08-18 17:41:01,171 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,172 INFO sqlalchemy.engine.base.Engine ('햇살가득어린이집', '임은영', '서울특별시 은평구 은평터널로 65 ,(대림한숲타운아파트)105동 103호 (수색동)', '02', '303', '3845', 22)
2021-08-18 17:41:01,173 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,173 INFO sqlalchemy.engine.base.Engine ('우리키즈어린이집', '황미경', '서울특별시 송파구 위례광장로 121 ,위례 24단지, 2410동 101호 (위례동)', '02', '6672', '8862', 18)
2021-08-18 17:41:01,175 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,175 INFO sqlalchemy.engine.base.Engine ('아리솔어린이집', '장서현', '서울특별시 송파구 올림픽로51길 62 ,1층 (풍납2동)', '02', '483', '1225', 18)
2021-08-18 17:41:01,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,179 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '류지은', '서울특별시 송파구 위례광장로 121 ,2414동102호(장지동, 위례24단지) (위례동)', '02', '6265', '0965', 18)
2021-08-18 17:41:01,179 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,180 INFO sqlalchemy.engine.base.Engine ('정릉제일어린이집', '김지민', '서울특별시 성북구 정릉로31가길 46 ,정릉제일어린이집 (정릉제1동)', '02', '6959', '9930', 17)
2021-08-18 17:41:01,181 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,183 INFO sqlalchemy.engine.base.Engine ('종암중앙어린이집', '정예준', '서울특별시 성북구 종암로19길 18 ,종암중앙어린이집 (종암동)', '02', '953', '3535', 17)
2021-08-18 17:41:01,183 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,184 INFO sqlalchemy.engine.base.Engine ('아이파크어린이집', '류영철', '서울특별시 양천구 목동동로 180 ,104동 104호(신정2동, 아이파크아파트) (신정2동)', '02', '2605', '7596', 19)
2021-08-18 17:41:01,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,185 INFO sqlalchemy.engine.base.Engine ('위키즈어린이집', '김정순', '서울특별시 송파구 위례광장로 121 ,2410동102호(장지동 위례24단지) (위례동)', '02', '430', '1339', 18)
2021-08-18 17:41:01,186 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,187 INFO sqlalchemy.engine.base.Engine ('해나라어린이집', '안지영', '서울특별시 송파구 위례광장로 163 ,2209동102호(장지동, 위례22단지) (위례동)', '02', '401', '4199', 18)
2021-08-18 17:41:01,188 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,189 INFO sqlalchemy.engine.base.Engine ('서초구립 서리풀어린이집', '최은경', '서울특별시 서초구 반포대로 121 ,(서초동, 사랑의 교회내) (서초3동)', '02', '3495', '1870', 15)
2021-08-18 17:41:01,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,191 INFO sqlalchemy.engine.base.Engine ('보람빅스맘어린이집', '김지영', '서울특별시 송파구 위례광장로 163 ,2201동 106호 (위례동)', '02', '514', '5325', 18)
2021-08-18 17:41:01,191 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,192 INFO sqlalchemy.engine.base.Engine ('새롬마을어린이집', '장지영', '서울특별시 구로구 고척로10길 45 (오류제1동)', '02', '2689', '5588', 7)
2021-08-18 17:41:01,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,197 INFO sqlalchemy.engine.base.Engine ('연지어린이집', '류성진', '서울특별시 구로구 오류로 39 ,연지타운1단지 104동 1층 (오류제2동)', '02', '2682', '2822', 7)
2021-08-18 17:41:01,198 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,199 INFO sqlalchemy.engine.base.Engine ('온새미어린이집', '안수빈', '서울특별시 구로구 새말로18길 130 (구로제5동)', '02', '857', '3322', 7)
2021-08-18 17:41:01,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,201 INFO sqlalchemy.engine.base.Engine ('구립 나무향기어린이집', '정정자', '서울특별시 양천구 가로공원로 66 ,(신월동) (신월3동)', '02', '2696', '7982', 19)
2021-08-18 17:41:01,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,203 INFO sqlalchemy.engine.base.Engine ('구립 푸른마을어린이집', '한정순', '서울특별시 양천구 신정로7길 70 ,푸른마을아1단지보육시설 (신정3동)', '02', '2066', '3359', 19)
2021-08-18 17:41:01,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,205 INFO sqlalchemy.engine.base.Engine ('구립둔촌푸르지오어린이집', '안민재', '서울특별시 강동구 명일로 172 (둔촌제2동)', '02', '475', '5649', 2)
2021-08-18 17:41:01,205 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,206 INFO sqlalchemy.engine.base.Engine ('명랑어린이집', '임종수', '서울특별시 서대문구 홍제내길 18 ,(홍제동) (홍제제1동)', '02', '395', '7777', 14)
2021-08-18 17:41:01,207 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,207 INFO sqlalchemy.engine.base.Engine ('종로생명숲어린이집', '이성수', '서울특별시 종로구 평창문화로 73-7 ,종로생명숲어린이집 (평창동)', '02', '359', '1671', 23)
2021-08-18 17:41:01,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,209 INFO sqlalchemy.engine.base.Engine ('구립 신사1어린이집', '오준영', '서울특별시 은평구 은평로3가길 16 (신사제1동)', '02', '355', '3387', 22)
2021-08-18 17:41:01,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,215 INFO sqlalchemy.engine.base.Engine ('구립 희망샘어린이집', '전지원', '서울특별시 광진구 긴고랑로37길 8 ,(중곡동) (중곡제4동)', '02', '458', '1324', 6)
2021-08-18 17:41:01,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,218 INFO sqlalchemy.engine.base.Engine ('은송어린이집', '윤영진', '서울특별시 송파구 동남로9길 17-10 (가락2동)', '02', '430', '7800', 18)
2021-08-18 17:41:01,220 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,220 INFO sqlalchemy.engine.base.Engine ('한강어린이집', '한정남', '서울특별시 동작구 서달로 91 ,(흑석동, 동부센트레빌2차 관리동) (흑석동)', '02', '3280', '1628', 12)
2021-08-18 17:41:01,222 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,223 INFO sqlalchemy.engine.base.Engine ('서울디지털직장어린이집', '강혜진', '서울특별시 금천구 벚꽃로 298 ,대륭포스트6차 305호 (가산동)', '02', '852', '5555', 8)
2021-08-18 17:41:01,224 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,224 INFO sqlalchemy.engine.base.Engine ('이레어린이집', '이지훈', '서울특별시 강남구 강남대로146길 28 ,103동 101호 (논현1동)', '02', '516', '2003', 1)
2021-08-18 17:41:01,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,227 INFO sqlalchemy.engine.base.Engine ('산마루어린이집', '조지민', '서울특별시 서대문구 북아현로 120 (북아현동)', '02', '364', '6300', 14)
2021-08-18 17:41:01,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,229 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '전상훈', '서울특별시 서대문구 통일로34길 19 ,새솔어린이집 (홍제제2동)', '02', '734', '5900', 14)
2021-08-18 17:41:01,231 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,232 INFO sqlalchemy.engine.base.Engine ('IBK참!좋은어린이집', '서건우', '서울특별시 구로구 디지털로32길 55 ,3층, 구로동 (구로제3동)', '02', '830', '3020', 7)
2021-08-18 17:41:01,233 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,233 INFO sqlalchemy.engine.base.Engine ('구립로미어린이집', '서영환', '서울특별시 동작구 만양로 19 (노량진제1동)', '02', '3280', '3535', 12)
2021-08-18 17:41:01,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,238 INFO sqlalchemy.engine.base.Engine ('구립신대방1동어린이집', '장성호', '서울특별시 동작구 신대방1길 44 (신대방제1동)', '02', '849', '4533', 12)
2021-08-18 17:41:01,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,240 INFO sqlalchemy.engine.base.Engine ('애플키즈어린이집', '신지은', '서울특별시 동대문구 사가정로 65 ,래미안크레시티아파트 110동 101호 (전농제1동)', '02', '2246', '9936', 11)
2021-08-18 17:41:01,241 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,243 INFO sqlalchemy.engine.base.Engine ('예성어린이집', '최준혁', '서울특별시 동대문구 사가정로 65 ,304동 101호 (전농동, 래미안크레시티아파트) (전농제1동)', '02', '6745', '8809', 11)
2021-08-18 17:41:01,245 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,246 INFO sqlalchemy.engine.base.Engine ('신길어린이집', '장영식', '서울특별시 영등포구 영등포로67가길 9 (신길제1동)', '02', '842', '0961', 20)
2021-08-18 17:41:01,247 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,247 INFO sqlalchemy.engine.base.Engine ('키즈빈생태어린이집', '임민지', '서울특별시 영등포구 문래동4가 선유로 26-1 ,고산빌딩1층 (문래동)', '02', '2635', '1999', 20)
2021-08-18 17:41:01,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,249 INFO sqlalchemy.engine.base.Engine ('구립 성삼보듬이나눔이어린이집', '서경숙', '서울특별시 성동구 성수동2가 광나루로 242-17 (성수2가제3동)', '02', '466', '3028', 16)
2021-08-18 17:41:01,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,251 INFO sqlalchemy.engine.base.Engine ('산모건강증진센터어린이집', '안은영', '서울특별시 송파구 충민로2길 20 (장지동)', '02', '404', '2288', 18)
2021-08-18 17:41:01,251 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,252 INFO sqlalchemy.engine.base.Engine ('서초구립 서초3단지어린이집', '신정호', '서울특별시 서초구 양재대로2길 34 ,우면동 408번지 서초보금자리3단지 내 별동 (양재1동)', '02', '572', '5004', 15)
2021-08-18 17:41:01,253 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,254 INFO sqlalchemy.engine.base.Engine ('송파위례22어린이집', '최영진', '서울특별시 송파구 위례광장로 163 (위례동)', '02', '406', '5656', 18)
2021-08-18 17:41:01,255 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,256 INFO sqlalchemy.engine.base.Engine ('송파위례24어린이집', '신영자', '서울특별시 송파구 위례광장로 121 (위례동)', '02', '430', '3663', 18)
2021-08-18 17:41:01,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,258 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '송준영', '서울특별시 송파구 동남로8길 9 (문정1동)', '02', '400', '0882', 18)
2021-08-18 17:41:01,259 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,261 INFO sqlalchemy.engine.base.Engine ('새그린어린이집', '장현준', '서울특별시 송파구 동남로 189 ,303동 109호 (가락2동)', '02', '431', '1333', 18)
2021-08-18 17:41:01,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,263 INFO sqlalchemy.engine.base.Engine ('기쁨샘몬테소리어린이집', '최종수', '서울특별시 관악구 난곡로 55 ,232동 104호(신림동, 관악산휴먼시아아파트) [난향동] (난향동)', '02', '868', '9807', 5)
2021-08-18 17:41:01,264 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,264 INFO sqlalchemy.engine.base.Engine ('봄빛가득한어린이집', '이건우', '서울특별시 관악구 신림로7길 33 ,102-103 (대학동)', '02', '885', '5999', 5)
2021-08-18 17:41:01,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,266 INFO sqlalchemy.engine.base.Engine ('안젤로스어린이집', '정혜진', '서울특별시 송파구 동남로20길 11 (가락2동)', '02', '6080', '6505', 18)
2021-08-18 17:41:01,267 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,268 INFO sqlalchemy.engine.base.Engine ('염창누리봄어린이집', '서준호', '서울특별시 강서구 양천로69길 58 ,염창동 동아1차 아파트 101-112 (염창동)', '02', '305', '0009', 4)

2021-08-18 17:41:01,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,270 INFO sqlalchemy.engine.base.Engine ('세곡연두 어린이집', '장영일', '서울특별시 강남구 자곡로3길 22 ,LH강남3단지(관리동) (세곡동)', '02', '451', '4488', 1)
2021-08-18 17:41:01,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,271 INFO sqlalchemy.engine.base.Engine ('소나무어린이집', '전정호', '서울특별시 관악구 난곡로45길 28 ,(신림동) [미성동] (미성동)', '02', '866', '0301', 5)
2021-08-18 17:41:01,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,274 INFO sqlalchemy.engine.base.Engine ('가로수 어린이집', '권예은', '서울특별시 강남구 압구정로18길 28 ,신구초등학교 (신사동)', '02', '511', '5466', 1)
2021-08-18 17:41:01,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,276 INFO sqlalchemy.engine.base.Engine ('대치도담 어린이집', '강상훈', '서울특별시 강남구 선릉로64길 33 ,도곡초등학교(대치4동) (대치제4동)', '02', '565', '6433', 1)
2021-08-18 17:41:01,279 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,280 INFO sqlalchemy.engine.base.Engine ('예송어린이집', '정미숙', '서울특별시 동대문구 이문로42길 45 (이문제2동)', '02', '6365', '9800', 11)
2021-08-18 17:41:01,281 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,282 INFO sqlalchemy.engine.base.Engine ('이든어린이집', '최민재', '서울특별시 마포구 월드컵북로 235 ,7-103 (성산동,성산시영아트) (성산제2동)', '070', '4139', '6095', 13)
2021-08-18 17:41:01,283 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,283 INFO sqlalchemy.engine.base.Engine ('미래어린이집', '김은정', '서울특별시 용산구 후암로16나길 13 (후암동)', '02', '752', '5506', 21)
2021-08-18 17:41:01,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,285 INFO sqlalchemy.engine.base.Engine ('구립 금삼어린이집', '최유진', '서울특별시 성동구 금호동3가 금호산길 14 (금호2.3가동)', '02', '2233', '6670', 16)
2021-08-18 17:41:01,286 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,287 INFO sqlalchemy.engine.base.Engine ('안암동 하나금융그룹 직장어린이집', '정정순', '서울특별시 성북구 안암동5가 안암로 75 (안암동)', '02', '6380', '2782', 17)
2021-08-18 17:41:01,288 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,289 INFO sqlalchemy.engine.base.Engine ('서초구립 리본타워어린이집', '박영진', '서울특별시 서초구 바우뫼로18길 20 ,101동 1층(양재동, 리본타워) (양재1동)', '02', '3462', '7151', 15)
2021-08-18 17:41:01,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,291 INFO sqlalchemy.engine.base.Engine ('서초구립 포레스타7단지어린이집', '이성호', '서울특별시 서초구 청계산로11길 7-12 ,708동 1층 (내곡동)', '070', '7204', '2030', 15)
2021-08-18 17:41:01,293 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,294 INFO sqlalchemy.engine.base.Engine ('서초구립방배열린어린이집', '오건우', '서울특별시 서초구 방배로 173 ,방배열린문화센터 내 1층 (방배4동)', '02', '3477', '6700', 15)
2021-08-18 17:41:01,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,296 INFO sqlalchemy.engine.base.Engine ('킨더베베어린이집', '안현준', '서울특별시 동대문구 외대역동로 14 ,103동 1층 관리동 (휘경동,센트레빌아파트) (휘경제2동)', '070', '4100', '3708', 11)
2021-08-18 17:41:01,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,300 INFO sqlalchemy.engine.base.Engine ('예뜰어린이집', '서경숙', '서울특별시 동대문구 답십리로30길 11 (답십리제1동)', '02', '2216', '6509', 11)
2021-08-18 17:41:01,301 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,302 INFO sqlalchemy.engine.base.Engine ('리틀바닐라어린이집', '서지원', '서울특별시 송파구 올림픽로 435 ,229동 102호(신천동, 파크리오아파트) (잠실4동)', '02', '6403', '2333', 18)
2021-08-18 17:41:01,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,304 INFO sqlalchemy.engine.base.Engine ('은가람어린이집', '윤영일', '서울특별시 구로구 경인로67길 149 ,신도림구민생활체육관내 1층 (신도림동)', '02', '2635', '1700', 7)
2021-08-18 17:41:01,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,306 INFO sqlalchemy.engine.base.Engine ('다사랑어린이집', '박상철', '서울특별시 동대문구 장안벚꽃로 107 ,116-106(장안동, 현대홈타운아파트) (장안제1동)', '02', '3390', '5550', 11)
2021-08-18 17:41:01,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,308 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '장정자', '서울특별시 성동구 무학로 50 ,106동 105호(하왕십리동, 벽산아파트) (왕십리도선동)', '02', '6237', '3900', 16)
2021-08-18 17:41:01,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,309 INFO sqlalchemy.engine.base.Engine ('우리은행어린이집', '류은경', '서울특별시 성동구 성수동2가 광나루로 324 ,우리은행 화양동지점 (성수2가제3동)', '02', '463', '5015', 16)
2021-08-18 17:41:01,310 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,311 INFO sqlalchemy.engine.base.Engine ('ABC 어린이집', '박병철', '서울특별시 성동구 왕십리로28길 20 ,, 1층(홍익동) (왕십리도선동)', '02', '2299', '4145', 16)
2021-08-18 17:41:01,313 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,314 INFO sqlalchemy.engine.base.Engine ('강변에코비어린이집', '신준호', '서울특별시 광진구 구의강변로 42 ,101동 108호 (구의제3동)', '02', '3436', '0260', 6)
2021-08-18 17:41:01,315 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,316 INFO sqlalchemy.engine.base.Engine ('구기어린이집', '신영숙', '서울특별시 종로구 진흥로22길 8-1 ,(구기동) (평창동)', '02', '391', '7072', 23)
2021-08-18 17:41:01,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,317 INFO sqlalchemy.engine.base.Engine ('수피아어린이집', '이영진', '서울특별시 관악구 인헌12길 46-1 ,208-103 (봉천동,은천아파트) [인헌동] (인헌동)', '02', '6014', '1212', 5)
2021-08-18 17:41:01,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,319 INFO sqlalchemy.engine.base.Engine ('구립 모새미어린이집', '한병철', '서울특별시 양천구 목동중앙본로7길 37-19 (목4동)', '02', '2648', '4682', 19)
2021-08-18 17:41:01,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,321 INFO sqlalchemy.engine.base.Engine ('롯데백화점노원점어린이집', '강서현', '서울특별시 노원구 상계로9가길 9-1 (상계2동)', '070', '4012', '8045', 9)

2021-08-18 17:41:01,323 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,326 INFO sqlalchemy.engine.base.Engine ('을지로 하나금융그룹 직장어린이집', '류수빈', '서울특별시 중구 을지로2가 을지로 55 ,하나은행 2층 (명동)', '02', '779', '6227', 24)
2021-08-18 17:41:01,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,330 INFO sqlalchemy.engine.base.Engine ('SK브로드밴드 행복한 어린이집', '임미영', '서울특별시 중구 남대문로5가 퇴계로 24 ,SK남산그린빌딩 4층 (회현동)', '02', '6266', '2300', 24)
2021-08-18 17:41:01,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,332 INFO sqlalchemy.engine.base.Engine ('농심어린이집', '류영진', '서울특별시 동작구 여의대방로 112 (신대방제2동)', '02', '822', '6800', 12)
2021-08-18 17:41:01,334 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,335 INFO sqlalchemy.engine.base.Engine ('영인어린이집', '이영자', '서울특별시 광진구 아차산로 522 ,802동 101호 (현대아파트 8단지, 광장동) (광장동)', '02', '444', '2566', 6)
2021-08-18 17:41:01,336 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,337 INFO sqlalchemy.engine.base.Engine ('SK ecoplan 행복날개어린이집', '최상훈', '서울특별시 종로구 인사동7길 32 ,SK건설행복날개어린이집 (종로1.2.3.4가동)', '02', '6395', '0202', 23)
2021-08-18 17:41:01,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,339 INFO sqlalchemy.engine.base.Engine ('현대다솜어린이집', '류건우', '서울특별시 종로구 창덕궁길 19 ,현대다솜어린이집 (가회동)', '02', '746', '7601', 23)
2021-08-18 17:41:01,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,341 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '조준호', '서울특별시 강서구 까치산로 166 (화곡제6동)', '02', '2608', '2046', 4)
2021-08-18 17:41:01,344 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,345 INFO sqlalchemy.engine.base.Engine ('아이샘어린이집', '강영자', '서울특별시 강서구 까치산로12길 8-9 (화곡본동)', '02', '2603', '0191', 4)
2021-08-18 17:41:01,346 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,346 INFO sqlalchemy.engine.base.Engine ('신한마리오어린이집', '김서연', '서울특별시 강남구 테헤란로30길 27 (역삼제2동)', '02', '567', '6705', 1)
2021-08-18 17:41:01,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,348 INFO sqlalchemy.engine.base.Engine ('온새미로어린이집', '이민지', '서울특별시 영등포구 당산동3가 영신로 193 ,2동 106호(당산동3가,한양아파트) (당산제1동)', '02', '6369', '2013', 20)
2021-08-18 17:41:01,349 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,350 INFO sqlalchemy.engine.base.Engine ('잠실사임당어린이집', '이정웅', '서울특별시 송파구 잠실로 88 ,116동 101호 (잠실동,레이크팰리스) (잠실3동)', '02', '421', '1052', 18)
2021-08-18 17:41:01,351 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,352 INFO sqlalchemy.engine.base.Engine ('구립 풍림아름다운어린이집', '황성수', '서울특별시 성동구 난계로 84 ,행당역풍림아이원아파트 관리동 (하왕십리동) (왕십리제2동)', '02', '2293', '1005', 16)
2021-08-18 17:41:01,354 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,357 INFO sqlalchemy.engine.base.Engine ('리본어린이집', '신상철', '서울특별시 중랑구 신내로 277 ,101동 1층 (묵동,묵동리본타워) (묵제1동)', '02', '975', '9477', 25)
2021-08-18 17:41:01,357 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,358 INFO sqlalchemy.engine.base.Engine ('꿈마루어린이집', '권예준', '서울특별시 양천구 남부순환로33길 17 ,101호(신월동,대운2차아파트) (신월5동)', '02', '2648', '3418', 19)
2021-08-18 17:41:01,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,360 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '정서연', '서울특별시 관악구 은천로35나길 25-4 (성현동)', '02', '889', '0888', 5)
2021-08-18 17:41:01,362 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,363 INFO sqlalchemy.engine.base.Engine ('아기사랑어린이집', '안은영', '서울특별시 강서구 허준로 175 ,가양6단지 601-106 (가양제3동)', '070', '4208', '5999', 4)
2021-08-18 17:41:01,363 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,364 INFO sqlalchemy.engine.base.Engine ('삼성이솝어린이집', '황진호', '서울특별시 마포구 토정로32길 11 ,101-103 (용강동)', '02', '703', '1418', 13)
2021-08-18 17:41:01,365 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,366 INFO sqlalchemy.engine.base.Engine ('서이어린이집', '서정남', '서울특별시 강남구 헌릉로571길 20 ,강남LH1단지 111-102 (세곡동)', '02', '459', '7878', 1)
2021-08-18 17:41:01,367 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,368 INFO sqlalchemy.engine.base.Engine ('하늘샘어린이집', '신정자', '서울특별시 강서구 강서로47다길 35 (발산제1동)', '02', '2665', '7611', 4)
2021-08-18 17:41:01,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,370 INFO sqlalchemy.engine.base.Engine ('그린업어린이집', '안정수', '서울특별시 관악구 관악로30길 27 ,111동 101호(봉천동 관악푸르지오아파트) (청림동)', '02', '875', '7578', 5)
2021-08-18 17:41:01,371 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,372 INFO sqlalchemy.engine.base.Engine ('예금보험공사어린이집', '한준영', '서울특별시 중구 청계천로 30 ,2층 (명동)', '02', '318', '3701', 24)
2021-08-18 17:41:01,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,374 INFO sqlalchemy.engine.base.Engine ('행복누리어린이집', '강경자', '서울특별시 송파구 오금로34길 12-14 ,102호(가락동,대림하이츠) (가락본동)', '02', '6486', '4553', 18)
2021-08-18 17:41:01,376 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,378 INFO sqlalchemy.engine.base.Engine ('구립세움어린이집', '류성수', '서울특별시 동작구 등용로 24-5 ,세움교회 1층 (상도제2동)', '02', '826', '5656', 12)
2021-08-18 17:41:01,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,380 INFO sqlalchemy.engine.base.Engine ('구립아이누리어린이집', '류영진', '서울특별시 강동구 양재대로122가길 7 (길동)', '02', '470', '1300', 2)
2021-08-18 17:41:01,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,382 INFO sqlalchemy.engine.base.Engine ('구립허브림어린이집', '한정호', '서울특별시 강동구 풍성로65길 15 (둔촌제2동)', '02', '476', '6245', 2)

2021-08-18 17:41:01,384 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,384 INFO sqlalchemy.engine.base.Engine ('키즈네이션어린이집', '장민지', '서울특별시 강서구 양천로67길 71-7 (염창동)', '070', '7681', '7990', 4)
2021-08-18 17:41:01,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,386 INFO sqlalchemy.engine.base.Engine ('구립 꿈나무마을어린이집', '신수빈', '서울특별시 은평구 백련산로14길 20-11 ,구립 꿈나무마을어린이집 (응암제1동)', '02', '384', '1701', 22)
2021-08-18 17:41:01,387 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,387 INFO sqlalchemy.engine.base.Engine ('예다솜어린이집', '안민석', '서울특별시 강남구 헌릉로571길 20 ,강남LH1단지(관리동) (세곡동)', '02', '3412', '1000', 1)
2021-08-18 17:41:01,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,388 INFO sqlalchemy.engine.base.Engine ('현대양재어린이집', '박건우', '서울특별시 서초구 염곡말길 17-6 (내곡동)', '02', '578', '8845', 15)
2021-08-18 17:41:01,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,390 INFO sqlalchemy.engine.base.Engine ('바른아이어린이집', '황영숙', '서울특별시 서초구 양재대로2길 90 ,208동 105호(우면동, LH스타힐스) (양재1동)', '02', '6406', '3688', 15)
2021-08-18 17:41:01,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,392 INFO sqlalchemy.engine.base.Engine ('별나무어린이집', '윤경자', '서울특별시 송파구 가락로28길 7-6 (송파2동)', '02', '413', '5999', 18)
2021-08-18 17:41:01,392 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,394 INFO sqlalchemy.engine.base.Engine ('칙칙폭폭어린이집', '안정웅', '서울특별시 용산구 원효로1가 원효로83길 5-8 ,(원효1동) (원효로제1동)', '02', '714', '0262', 21)
2021-08-18 17:41:01,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,396 INFO sqlalchemy.engine.base.Engine ('햇살마루어린이집', '신영길', '서울특별시 도봉구 도당로2길 23 ,햇살마루어린이집 (쌍문제2동)', '02', '903', '0073', 10)
2021-08-18 17:41:01,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,398 INFO sqlalchemy.engine.base.Engine ('구립도담어린이집', '안지영', '서울특별시 강동구 성내로14길 18 ,(성내동, 선광아파트상가 116호) (성내제1동)', '02', '470', '2922', 2)
2021-08-18 17:41:01,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,400 INFO sqlalchemy.engine.base.Engine ('구립해그린어린이집', '임미영', '서울특별시 강동구 고덕로 427 ,208동 1층 (강일동, 고덕리엔파크2단지 아파트) (강일동)', '02', '3427', '3936', 2)
2021-08-18 17:41:01,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,403 INFO sqlalchemy.engine.base.Engine ('엠코어린이집', '신지은', '서울특별시 동작구 상도로 346-1 ,112동 105호 (상도제1동)', '02', '816', '3003', 12)
2021-08-18 17:41:01,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,405 INFO sqlalchemy.engine.base.Engine ('구립예촌어린이집', '정정남', '서울특별시 관악구 남현1가길 29 ,남현동 복합청사내 1층 (남현동)', '02', '3486', '4333', 5)
2021-08-18 17:41:01,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,406 INFO sqlalchemy.engine.base.Engine ('나무어린이집', '서영환', '서울특별시 송파구 중대로31길 18 ,가동 103호(오금동, 현대타운) (오금동)', '02', '403', '0613', 18)
2021-08-18 17:41:01,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,408 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '박경자', '서울특별시 강서구 방화대로44길 49 (방화제1동)', '02', '2662', '6601', 4)
2021-08-18 17:41:01,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,410 INFO sqlalchemy.engine.base.Engine ('프라임사랑어린이집', '최건우', '서울특별시 광진구 광나루로56길 29 ,11동 102호(구의동, 현대프라임아파트) (구의제3동)', '02', '456', '1279', 6)
2021-08-18 17:41:01,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,412 INFO sqlalchemy.engine.base.Engine ('행복가득한어린이집', '안민지', '서울특별시 성북구 삼선동4가 삼선교로23길 23 ,104-103(코오롱아파트,삼선동) (삼선동)', '02', '6225', '1999', 17)
2021-08-18 17:41:01,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,414 INFO sqlalchemy.engine.base.Engine ('애솔 어린이집', '이정자', '서울특별시 강서구 초록마을로 162-30 (화곡제8동)', '02', '2602', '0091', 4)
2021-08-18 17:41:01,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,415 INFO sqlalchemy.engine.base.Engine ('리틀브레인어린이집', '신건우', '서울특별시 관악구 성현로 80 ,133-101(관악드림타운, 봉천동) (성현동)', '02', '884', '8843', 5)
2021-08-18 17:41:01,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,417 INFO sqlalchemy.engine.base.Engine ('사랑별어린이집', '송수빈', '서울특별시 양천구 목동서로 130 ,410동 104호(목동, 목동신시가지아파트4단지) (목5동)', '070', '7695', '0395', 19)
2021-08-18 17:41:01,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,420 INFO sqlalchemy.engine.base.Engine ('구립 벽산어린이집', '조건우', '서울특별시 성동구 금호동1가 행당로6길 2 ,(금호동1가, 금호벽산제2관리소 2층) (금호1가동)', '02', '2296', '3062', 16)
2021-08-18 17:41:01,422 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,423 INFO sqlalchemy.engine.base.Engine ('삼육어린이집', '전지훈', '서울특별시 영등포구 양평동2가 선유서로21길 19 ,101동104호(양평동2가, 양평동벽산블루밍아파트) (양평제1동)', '02', '2631', '7676', 20)
2021-08-18 17:41:01,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,424 INFO sqlalchemy.engine.base.Engine ('구립 독서당어린이집', '최영진', '서울특별시 성동구 매봉길 17 ,래미안리버젠 2단지 (옥수동)', '02', '2299', '2929', 16)
2021-08-18 17:41:01,428 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,429 INFO sqlalchemy.engine.base.Engine ('래미안베베어린이집', '송혜진', '서울특별시 성북구 한천로 713 ,503동 101호(장위동, 래미안장위퍼스트하이) (장위제3동)', '02', '6061', '0403', 17)
2021-08-18 17:41:01,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,431 INFO sqlalchemy.engine.base.Engine ('콩세알어린이집', '오동현', '서울특별시 서대문구 세검정로1길 106-3 ,(홍은동) (홍은제1동)', '02', '6243', '2600', 14)
2021-08-18 17:41:01,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,433 INFO sqlalchemy.engine.base.Engine ('새움터어린이집', '황상훈', '서울특별시 구로구 디지털로33길 28 ,1차101호 (구로제3동)', '02', '854', '0022', 7)
2021-08-18 17:41:01,434 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,435 INFO sqlalchemy.engine.base.Engine ('아이소리어린이집', '임종수', '서울특별시 송파구 올림픽로 435 ,305동 104호(신천동, 파크리오) (잠실4동)', '02', '476', '7512', 18)
2021-08-18 17:41:01,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,437 INFO sqlalchemy.engine.base.Engine ('가온어린이집', '최준혁', '서울특별시 강남구 헌릉로618길 8 ,대왕초등학교내 (세곡동)', '02', '445', '7890', 1)
2021-08-18 17:41:01,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,439 INFO sqlalchemy.engine.base.Engine ('꼬마숲상아아름어린이집', '오준혁', '서울특별시 양천구 월정로 62 ,102동101호(신월동,상아아름아파트) (신월2동)', '02', '6084', '7279', 19)
2021-08-18 17:41:01,439 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,441 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '이정웅', '서울특별시 관악구 신림로3가길 45-24 ,청광아파트 101동 104호 (대학동)', '02', '878', '5403', 5)
2021-08-18 17:41:01,441 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,442 INFO sqlalchemy.engine.base.Engine ('사랑숲어린이집', '이유진', '서울특별시 광진구 영화사로9길 95-2 ,(중곡동) (중곡제4동)', '02', '452', '8877', 6)
2021-08-18 17:41:01,444 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,445 INFO sqlalchemy.engine.base.Engine ('수연어린이집', '오민지', '서울특별시 강남구 봉은사로59길 22 ,. (삼성제2동)', '02', '546', '6873', 1)
2021-08-18 17:41:01,446 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,447 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '윤광수', '서울특별시 양천구 남부순환로27길 6 ,101호(신월동, 온누리아파트) (신월5동)', '02', '2602', '0117', 19)
2021-08-18 17:41:01,448 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,449 INFO sqlalchemy.engine.base.Engine ('서초구립네이처힐1단지어린이집', '안정호', '서울특별시 서초구 형촌길 35 ,네이처힐1단지 109동 1층 (양재1동)', '02', '572', '0109', 15)
2021-08-18 17:41:01,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,454 INFO sqlalchemy.engine.base.Engine ('서초구립네이처힐6단지어린이집', '박정운', '서울특별시 서초구 태봉로2길 30 ,네이처힐6단지 601동 1층 (양재1동)', '02', '571', '0204', 15)
2021-08-18 17:41:01,460 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,461 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '신종수', '서울특별시 마포구 월드컵북로 235 ,성산시영아파트 18동 103호 (성산제2동)', '02', '309', '3255', 13)
2021-08-18 17:41:01,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,463 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '임예준', '서울특별시 성동구 독서당로 218 ,110-102(옥수동, 옥수삼성아파트) (옥수동)', '02', '2291', '0903', 16)
2021-08-18 17:41:01,464 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,465 INFO sqlalchemy.engine.base.Engine ('푸르미어린이집', '박정운', '서울특별시 송파구 올림픽로35길 104 ,9동 107호(신천동, 장미아파트) (잠실6동)', '02', '418', '8777', 18)
2021-08-18 17:41:01,466 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,467 INFO sqlalchemy.engine.base.Engine ('삼성SDS더자람어린이집', '서종수', '서울특별시 송파구 올림픽로35길 123 ,3층 (잠실6동)', '02', '2152', '7255', 18)
2021-08-18 17:41:01,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,468 INFO sqlalchemy.engine.base.Engine ('큰꿈어린이집', '권건우', '서울특별시 성동구 행당로 82 ,102동 102호(행당제2동, 해모로한진타운) (행당제2동)', '02', '2297', '8490', 16)
2021-08-18 17:41:01,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,471 INFO sqlalchemy.engine.base.Engine ('다사랑어린이집', '류상훈', '서울특별시 양천구 목동서로 280 ,812동 103호 (목동신시가지아파트, 신정6동) (신정6동)', '070', '4224', '2269', 19)
2021-08-18 17:41:01,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,473 INFO sqlalchemy.engine.base.Engine ('목화마을어린이집', '강예준', '서울특별시 영등포구 문래동3가 경인로 775 ,에이스하이테크시티 1-101 (문래동)', '02', '2636', '8001', 20)
2021-08-18 17:41:01,474 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,475 INFO sqlalchemy.engine.base.Engine ('키즈숲 어린이집', '윤종수', '서울특별시 중구 다산로 32 ,15동 101호(신당동, 남산타운) (약수동)', '02', '2256', '0523', 24)
2021-08-18 17:41:01,476 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,476 INFO sqlalchemy.engine.base.Engine ('동글동글어린이집', '류경숙', '서울특별시 강서구 허준로 175 ,가양6단지아파트 603동 101호 (가양제3동)', '02', '3663', '6031', 4)
2021-08-18 17:41:01,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,479 INFO sqlalchemy.engine.base.Engine ('에코맘어린이집', '황도현', '서울특별시 송파구 송파대로32길 15 ,107동 102호(가락동, 가락금호아파트) (가락본동)', '070', '4234', '7979', 18)
2021-08-18 17:41:01,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,481 INFO sqlalchemy.engine.base.Engine ('꿈쟁이어린이집', '조영진', '서울특별시 강동구 고덕로 210 ,506동 106호(명일동, 삼익그린맨션) (명일제1동)', '02', '441', '3330', 2)
2021-08-18 17:41:01,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,482 INFO sqlalchemy.engine.base.Engine ('중곡희망어린이집', '오정남', '서울특별시 광진구 용마산로30길 17 ,(중곡동) (중곡제4동)', '02', '446', '4430', 6)
2021-08-18 17:41:01,483 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,484 INFO sqlalchemy.engine.base.Engine ('군자티움아이어린이집', '박서연', '서울특별시 광진구 동일로38길 8 ,1층(군자동) (군자동)', '02', '498', '1279', 6)
2021-08-18 17:41:01,486 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,487 INFO sqlalchemy.engine.base.Engine ('삼광어린이집', '전종수', '서울특별시 동작구 동작대로17길 33-8 (사당제1동)', '02', '2038', '2822', 12)
2021-08-18 17:41:01,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,491 INFO sqlalchemy.engine.base.Engine ('구립해야해야어린이집', '장영진', '서울특별시 금천구 한내로 69-15 (독산제1동)', '02', '899', '1279', 8)
2021-08-18 17:41:01,492 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,493 INFO sqlalchemy.engine.base.Engine ('딩동댕어린이집', '한상철', '서울특별시 용산구 효창원로 17 ,101동 101호(산천동,리버힐삼성아파트) (원효로제2동)', '02', '6010', '5437', 21)
2021-08-18 17:41:01,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,495 INFO sqlalchemy.engine.base.Engine ('잠실키즈사랑어린이집', '안지혜', '서울특별시 송파구 올림픽로 435 ,308동 103호 (잠실4동)', '02', '423', '0179', 18)
2021-08-18 17:41:01,496 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,497 INFO sqlalchemy.engine.base.Engine ('송이어린이집', '강정호', '서울특별시 양천구 목동동로 430 ,610동 105호(목동, 목동신시가지아파트6단지) (목5동)', '02', '2649', '0003', 19)
2021-08-18 17:41:01,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,498 INFO sqlalchemy.engine.base.Engine ('희망어린이집', '안영진', '서울특별시 중랑구 신내로 127 ,910동 102호(신내동,신내아파트) (신내2동)', '070', '7566', '0138', 25)
2021-08-18 17:41:01,499 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,500 INFO sqlalchemy.engine.base.Engine ('키즈파랑새어린이집', '박수빈', '서울특별시 강서구 공항대로58길 46 ,등촌동 532-7 (등촌제2동)', '02', '2644', '9232', 4)
2021-08-18 17:41:01,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,501 INFO sqlalchemy.engine.base.Engine ('래미안도곡카운티어린이집', '윤준영', '서울특별시 강남구 선릉로 227 ,래미안도곡카운티아파트 관리동 (도곡제2동)', '02', '3462', '7942', 1)
2021-08-18 17:41:01,502 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,502 INFO sqlalchemy.engine.base.Engine ('이랜드코코몽 어린이집', '송은정', '서울특별시 금천구 가산디지털1로 159 (가산동)', '02', '858', '5579', 8)
2021-08-18 17:41:01,503 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,504 INFO sqlalchemy.engine.base.Engine ('아기나무어린이집', '김영길', '서울특별시 성동구 행당로 87 ,107동 103호 (행당제2동, 대림아파트) (행당제2동)', '02', '2296', '2301', 16)
2021-08-18 17:41:01,505 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,506 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '박영일', '서울특별시 송파구 가락로31길 19 ,102호(송파동, 경일아파트) (송파1동)', '02', '403', '7110', 18)
2021-08-18 17:41:01,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,508 INFO sqlalchemy.engine.base.Engine ('미소지움어린이집', '김영진', '서울특별시 양천구 오목로10길 7-8 ,301동 101호(신월동, 신월2차미소지움) (신월2동)', '02', '2603', '8696', 19)
2021-08-18 17:41:01,509 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,510 INFO sqlalchemy.engine.base.Engine ('아이소리어린이집', '장영진', '서울특별시 종로구 지봉로5길 7 ,103-101(창신동,두산아파트) (창신제1동)', '02', '3672', '5011', 23)
2021-08-18 17:41:01,512 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,512 INFO sqlalchemy.engine.base.Engine ('꼬모어린이집', '송미숙', '서울특별시 강서구 양천로 731 ,동아3차 305-103 (염창동)', '070', '4791', '3727', 4)
2021-08-18 17:41:01,514 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,514 INFO sqlalchemy.engine.base.Engine ('하하호호어린이집', '이준혁', '서울특별시 강서구 공항대로75길 30 ,삼정그린코아 102-106 (염창동)', '070', '8815', '9885', 4)
2021-08-18 17:41:01,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,516 INFO sqlalchemy.engine.base.Engine ('구립관악어린이집', '이지민', '서울특별시 관악구 신림로39길 17 (서림동)', '02', '888', '0830', 5)
2021-08-18 17:41:01,517 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,518 INFO sqlalchemy.engine.base.Engine ('구립두드림어린이집', '서준호', '서울특별시 관악구 조원로18길 26 (조원동)', '02', '862', '1680', 5)
2021-08-18 17:41:01,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,523 INFO sqlalchemy.engine.base.Engine ('구립 응암새싹어린이집', '장준호', '서울특별시 은평구 은평로10길 5-2 (응암제1동)', '02', '389', '9045', 22)
2021-08-18 17:41:01,525 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,527 INFO sqlalchemy.engine.base.Engine ('하나둘셋어린이집', '조미경', '서울특별시 송파구 동남로20길 32 (가락2동)', '02', '430', '5941', 18)
2021-08-18 17:41:01,528 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,529 INFO sqlalchemy.engine.base.Engine ('구립 서울숲어린이집', '권민석', '서울특별시 성동구 금호동4가 금호로 17 ,서울숲 푸르지오2차 관리동 (금호4가동)', '02', '2295', '2333', 16)
2021-08-18 17:41:01,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,530 INFO sqlalchemy.engine.base.Engine ('정다운키즈어린이집', '한경숙', '서울특별시 마포구 희우정로 27 (합정동)', '02', '338', '3892', 13)
2021-08-18 17:41:01,531 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,532 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '한정웅', '서울특별시 송파구 중대로 24 ,229-104 (문정2동)', '070', '8222', '1273', 18)
2021-08-18 17:41:01,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,533 INFO sqlalchemy.engine.base.Engine ('한신휴플러스어린이집', '한영길', '서울특별시 강남구 밤고개로27길 20 ,관리동 (세곡동)', '02', '578', '7866', 1)
2021-08-18 17:41:01,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,534 INFO sqlalchemy.engine.base.Engine ('하나별어린이집', '황진호', '서울특별시 은평구 진관4로 100 ,은평뉴타운 상림마을 606동 108호 (진관동)', '02', '6403', '7979', 22)
2021-08-18 17:41:01,535 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,536 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '윤지은', '서울특별시 용산구 새창로 70 ,105동 101호 (용문동)', '070', '4407', '2993', 21)
2021-08-18 17:41:01,537 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,538 INFO sqlalchemy.engine.base.Engine ('그림어린이집', '오지은', '서울특별시 강남구 역삼로70길 19-14 ,101호 (대치제4동)', '070', '8749', '5899', 1)
2021-08-18 17:41:01,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,540 INFO sqlalchemy.engine.base.Engine ('아이다솜어린이집', '이준혁', '서울특별시 광진구 자양로33길 50 ,(구의동) (구의제2동)', '02', '456', '3672', 6)
2021-08-18 17:41:01,542 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,543 INFO sqlalchemy.engine.base.Engine ('포도나무어린이집', '류현정', '서울특별시 광진구 뚝섬로52마길 56 ,102동101호(자양동,로얄동아파트) (자양제2동)', '02', '6212', '0516', 6)
2021-08-18 17:41:01,544 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,545 INFO sqlalchemy.engine.base.Engine ('현대아이사랑어린이집', '정도현', '서울특별시 광진구 광나루로56길 32 ,208동105호(구의동,구의현대아파트) (구의제3동)', '02', '455', '6780', 6)
2021-08-18 17:41:01,546 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,547 INFO sqlalchemy.engine.base.Engine ('LG사랑어린이집', '김은영', '서울특별시 영등포구 여의대로 128 ,LG트윈타워 (여의동)', '02', '3773', '1300', 20)
2021-08-18 17:41:01,548 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,549 INFO sqlalchemy.engine.base.Engine ('고운꿈어린이집', '박현정', '서울특별시 용산구 이촌로 181 ,106동 102호(이촌동, 한강대우아파트) (이촌제1동)', '02', '797', '3797', 21)
2021-08-18 17:41:01,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,553 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '전진호', '서울특별시 송파구 올림픽로35길 104 ,28동105(신천동 11) (잠실6동)', '02', '415', '5010', 18)
2021-08-18 17:41:01,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,554 INFO sqlalchemy.engine.base.Engine ('KDB꿈나무어린이집', '한지훈', '서울특별시 영등포구 은행로 22 ,산업은행 별관 1층 (여의동)', '02', '780', '9066', 20)
2021-08-18 17:41:01,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,556 INFO sqlalchemy.engine.base.Engine ('구립 래미안하이리버어린이집', '장준호', '서울특별시 성동구 금호동2가 금호로 107 ,래미안하이리버아파트 관리동 (금호2.3가동)', '02', '2237', '2255', 16)
2021-08-18 17:41:01,557 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,558 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '박정자', '서울특별시 중구 청구로1길 23 ,113동 103호(신당동,신당삼성아파트) (청구동)', '02', '2252', '4777', 24)
2021-08-18 17:41:01,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,559 INFO sqlalchemy.engine.base.Engine ('해피맘어린이집', '최준영', '서울특별시 중구 청계천로 400 ,롯데캐슬베네치아 105동 704호 (황학동)', '02', '2048', '5756', 24)
2021-08-18 17:41:01,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,562 INFO sqlalchemy.engine.base.Engine ('구립 금호자이햇살어린이집', '장준혁', '서울특별시 성동구 금호동3가 금호산8길 14 ,금호자이2차아파트 내 (금호2.3가동)', '02', '2231', '1432', 16)
2021-08-18 17:41:01,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,564 INFO sqlalchemy.engine.base.Engine ('구립 수호천사어린이집', '류상훈', '서울특별시 광진구 긴고랑로17길 8 ,(중곡동) (중곡제2동)', '02', '447', '2373', 6)
2021-08-18 17:41:01,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,566 INFO sqlalchemy.engine.base.Engine ('상암하늘빛어린이집', '이동현', '서울특별시 마포구 월드컵로42길 2 (상암동)', '02', '323', '6796', 13)
2021-08-18 17:41:01,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,568 INFO sqlalchemy.engine.base.Engine ('서초구립하나푸르니반포어린이집', '전은영', '서울특별시 서초구 서초중앙로33길 10 ,반포4동 (반포4동)', '02', '592', '5181', 15)
2021-08-18 17:41:01,569 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,570 INFO sqlalchemy.engine.base.Engine ('이베이코리아베이트리어린이집', '조성수', '서울특별시 강남구 테헤란로25길 53 (역삼1동)', '02', '566', '3236', 1)
2021-08-18 17:41:01,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,573 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '권동현', '서울특별시 성동구 매봉길 15 ,111동 105호(옥수동, 래미안옥수리버젠 (옥수동)', '02', '2281', '2777', 16)
2021-08-18 17:41:01,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,579 INFO sqlalchemy.engine.base.Engine ('우방샛별어린이집', '황정운', '서울특별시 송파구 성내천로 211 ,102동 107호 (마천2동)', '02', '443', '8669', 18)
2021-08-18 17:41:01,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,581 INFO sqlalchemy.engine.base.Engine ('하늘누리어린이집', '서지은', '서울특별시 강서구 남부순환로17길 58 ,1층 (발산제1동)', '02', '6401', '8018', 4)
2021-08-18 17:41:01,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,582 INFO sqlalchemy.engine.base.Engine ('유하아이비클럽어린이집', '서경회', '서울특별시 서초구 서초중앙로24길 33 ,교대e편한세상아파트 관리동 (서초4동)', '02', '3477', '9235', 15)
2021-08-18 17:41:01,584 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,585 INFO sqlalchemy.engine.base.Engine ('키즈딸기어린이집', '박광수', '서울특별시 도봉구 덕릉로59아길 54 ,1층 (창제2동)', '02', '900', '1939', 10)
2021-08-18 17:41:01,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,587 INFO sqlalchemy.engine.base.Engine ('현대힐스어린이집', '정동현', '서울특별시 동작구 동작대로39길 22 ,이수힐스테이트 아 관리동1층 의무어린이집 109동 앞 (사당제2동)', '02', '591', '5466', 12)
2021-08-18 17:41:01,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,589 INFO sqlalchemy.engine.base.Engine ('WITH MOM어린이집', '전도현', '서울특별시 마포구 상암산로 82 (상암동)', '02', '6933', '7901', 13)
2021-08-18 17:41:01,590 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,591 INFO sqlalchemy.engine.base.Engine ('KIM&CHANG; 어린이집', '이정웅', '서울특별시 종로구 신문로2가 경희궁길 26 ,썬타워빌딩 1층 (사직동)', '02', '738', '6901', 23)
2021-08-18 17:41:01,592 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,594 INFO sqlalchemy.engine.base.Engine ('한신엄마품어린이집', '류성호', '서울특별시 영등포구 양평동5가 양평로24길 9 ,한신아파트 103동 101호 (양평제2동)', '02', '2677', '5054', 20)
2021-08-18 17:41:01,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,596 INFO sqlalchemy.engine.base.Engine ('서초구립네이처힐3단지어린이집', '황정호', '서울특별시 서초구 태봉로2길 60 ,307동 1층(우면동, 서초네이처힐) (양재1동)', '02', '579', '6933', 15)
2021-08-18 17:41:01,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,598 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '전경회', '서울특별시 중구 청계천로 400 ,101동 709호 (황학동)', '02', '2231', '3132', 24)
2021-08-18 17:41:01,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,599 INFO sqlalchemy.engine.base.Engine ('잠실예닮어린이집', '윤정수', '서울특별시 송파구 동남로16길 5 ,1층 (가락2동)', '02', '2043', '6008', 18)
2021-08-18 17:41:01,600 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,601 INFO sqlalchemy.engine.base.Engine ('애플그린어린이집', '황준혁', '서울특별시 마포구 만리재옛길 60 ,1층 (공덕동)', '02', '707', '2220', 13)
2021-08-18 17:41:01,602 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,603 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '장영식', '서울특별시 강서구 방화대로6가길 6 (공항동)', '02', '6052', '0233', 4)
2021-08-18 17:41:01,604 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,605 INFO sqlalchemy.engine.base.Engine ('구립 래미안리버젠어린이집', '강영철', '서울특별시 성동구 매봉길 15 ,래미안리버젠아파트 관리동 (옥수동)', '02', '2291', '2013', 16)
2021-08-18 17:41:01,611 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,612 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '강영진', '서울특별시 중랑구 망우로75길 19 ,106동P층(망우동,중랑숲리가아파트) (망우본동)', '02', '2208', '7707', 25)
2021-08-18 17:41:01,613 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,613 INFO sqlalchemy.engine.base.Engine ('행복가득어린이집', '안종수', '서울특별시 송파구 중대로34길 9-13 (오금동)', '02', '402', '5248', 18)
2021-08-18 17:41:01,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,616 INFO sqlalchemy.engine.base.Engine ('푸른뜰어린이집', '조미숙', '서울특별시 강동구 천호대로221길 18 ,(상일동) (상일제1동)', '02', '427', '4239', 2)
2021-08-18 17:41:01,617 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,618 INFO sqlalchemy.engine.base.Engine ('꼬마숲극동어린이집', '최정운', '서울특별시 광진구 아차산로 552 ,1동103호(광장동, 극동아파트) (광장동)', '02', '402', '7470', 6)
2021-08-18 17:41:01,620 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,621 INFO sqlalchemy.engine.base.Engine ('하랑어린이집', '황민지', '서울특별시 마포구 월드컵로13길 19-16 (망원제1동)', '02', '6379', '7942', 13)
2021-08-18 17:41:01,622 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,623 INFO sqlalchemy.engine.base.Engine ('선정어린이집', '신정웅', '서울특별시 은평구 증산로3길 5-21 ,선정아파트 101-101 (증산동)', '02', '306', '1700', 22)
2021-08-18 17:41:01,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,626 INFO sqlalchemy.engine.base.Engine ('이레어린이집', '안영진', '서울특별시 강서구 금낭화로11길 48 ,(방화동 583-37) (방화제2동)', '02', '2665', '0011', 4)
2021-08-18 17:41:01,627 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,629 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '이서현', '서울특별시 중랑구 동일로157길 59 ,,107호(묵동,세원아파트) (묵제2동)', '02', '948', '8042', 25)
2021-08-18 17:41:01,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,630 INFO sqlalchemy.engine.base.Engine ('햇살가득어린이집', '신병철', '서울특별시 광진구 자양로19길 60 ,1층(자양동) (자양제1동)', '02', '457', '1600', 6)
2021-08-18 17:41:01,631 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,632 INFO sqlalchemy.engine.base.Engine ('엄마마음어린이집', '권준호', '서울특별시 송파구 올림픽로 435 ,227동 104호 (잠실4동)', '02', '419', '5533', 18)
2021-08-18 17:41:01,633 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,634 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '한지영', '서울특별시 강남구 광평로51길 27 ,402동 104호(수서동, 삼익아파트) (수서동)', '02', '445', '2982', 1)
2021-08-18 17:41:01,635 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,636 INFO sqlalchemy.engine.base.Engine ('가람어린이집', '임광수', '서울특별시 성북구 흥천사길 49-23 ,적조사 (돈암제2동)', '02', '925', '5556', 17)
2021-08-18 17:41:01,637 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,638 INFO sqlalchemy.engine.base.Engine ('예꿈어린이집', '강지훈', '서울특별시 서대문구 독립문공원길 20 ,(현저동) (천연동)', '02', '363', '6090', 14)
2021-08-18 17:41:01,638 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,639 INFO sqlalchemy.engine.base.Engine ('은평중앙어린이집', '윤정순', '서울특별시 은평구 은평로8길 15-4 (응암제1동)', '02', '357', '9004', 22)
2021-08-18 17:41:01,640 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,640 INFO sqlalchemy.engine.base.Engine ('꼬마수피아어린이집', '신예은', '서울특별시 송파구 가락로39길 40 ,1층 (방이2동)', '02', '422', '6262', 18)
2021-08-18 17:41:01,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,642 INFO sqlalchemy.engine.base.Engine ('라원어린이집', '임영숙', '서울특별시 송파구 마천로7길 7 (오금동)', '02', '3402', '0050', 18)
2021-08-18 17:41:01,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,645 INFO sqlalchemy.engine.base.Engine ('별하어린이집', '정영숙', '서울특별시 은평구 증산로15길 70 ,1층 (신사제2동)', '02', '374', '1007', 22)
2021-08-18 17:41:01,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,647 INFO sqlalchemy.engine.base.Engine ('별초롱어린이집', '한성호', '서울특별시 동작구 만양로1길 14 ,102호(상도2동 상명하이츠빌) (상도제2동)', '02', '812', '5009', 12)
2021-08-18 17:41:01,648 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,649 INFO sqlalchemy.engine.base.Engine ('구립 빛초롱어린이집', '류영일', '서울특별시 성동구 왕십리로 36 ,강변건영아파트 관리동 2층 (성수동1가) (성수1가제1동)', '02', '499', '8599', 16)
2021-08-18 17:41:01,650 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,650 INFO sqlalchemy.engine.base.Engine ('구립푸른솔어린이집', '신정호', '서울특별시 동작구 상도로52길 23 ,청송경로당 1층 (상도제1동)', '02', '822', '3383', 12)
2021-08-18 17:41:01,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,652 INFO sqlalchemy.engine.base.Engine ('대림늘푸른어린이집', '송민지', '서울특별시 동대문구 답십리로60길 40 ,(답십리동) (답십리제2동)', '02', '2217', '7900', 11)
2021-08-18 17:41:01,653 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,654 INFO sqlalchemy.engine.base.Engine ('고은아이어린이집', '권성호', '서울특별시 광진구 능동로3길 53 ,1동 102호(자양동) (자양제4동)', '02', '464', '1355', 6)
2021-08-18 17:41:01,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,656 INFO sqlalchemy.engine.base.Engine ('리틀짐어린이집', '류건우', '서울특별시 송파구 백제고분로46길 26-11 (송파1동)', '02', '417', '0003', 18)
2021-08-18 17:41:01,656 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,657 INFO sqlalchemy.engine.base.Engine ('무궁화누리어린이집', '류은경', '서울특별시 송파구 오금로23길 23 ,1층 (방이2동)', '02', '413', '4014', 18)
2021-08-18 17:41:01,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,659 INFO sqlalchemy.engine.base.Engine ('예쁜꿈어린이집', '김영환', '서울특별시 은평구 통일로63길 20 (녹번동)', '02', '388', '2233', 22)
2021-08-18 17:41:01,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,661 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '김유진', '서울특별시 은평구 백련산로 84 ,(응암동) 백련산힐스테이트 108동 102호 (응암제2동)', '02', '6369', '1700', 22)
2021-08-18 17:41:01,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,663 INFO sqlalchemy.engine.base.Engine ('그린나래어린이집', '김정운', '서울특별시 관악구 쑥고개로2길 48 (서림동)', '02', '884', '2141', 5)
2021-08-18 17:41:01,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,664 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '황정순', '서울특별시 송파구 송파대로 567 ,505-109(잠실3동, 주공아파트) (잠실3동)', '02', '413', '6004', 18)
2021-08-18 17:41:01,665 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,665 INFO sqlalchemy.engine.base.Engine ('정다운아이들어린이집', '임미영', '서울특별시 은평구 증산로19길 34 (신사제1동)', '02', '302', '9176', 22)
2021-08-18 17:41:01,666 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,667 INFO sqlalchemy.engine.base.Engine ('교보생명다솜이어린이집', '강미경', '서울특별시 종로구 신문로2가 경희궁1가길 3 (사직동)', '02', '722', '2012', 23)
2021-08-18 17:41:01,668 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,668 INFO sqlalchemy.engine.base.Engine ('꿈이크는어린이집', '조준호', '서울특별시 영등포구 도신로 100 ,신길우성5차아파트 502동 105호 (신길제3동)', '02', '849', '1221', 20)
2021-08-18 17:41:01,669 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,670 INFO sqlalchemy.engine.base.Engine ('아란어린이집', '강혜진', '서울특별시 강서구 양천로71가길 43 (염창동)', '02', '3664', '9004', 4)
2021-08-18 17:41:01,671 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,672 INFO sqlalchemy.engine.base.Engine ('극동예랑어린이집', '신영숙', '서울특별시 광진구 아차산로 552 ,6동 109호(광장동, 극동아파트) (광장동)', '02', '454', '1140', 6)
2021-08-18 17:41:01,672 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,673 INFO sqlalchemy.engine.base.Engine ('벧엘어린이집', '권현준', '서울특별시 은평구 증산서길 72 ,칠산아파트 104호 (증산동)', '02', '373', '2267', 22)
2021-08-18 17:41:01,674 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,675 INFO sqlalchemy.engine.base.Engine ('야호어린이집', '강정수', '서울특별시 광진구 아차산로 552 ,11동 101호(광장동, 극동아파트) (광장동)', '02', '455', '5500', 6)
2021-08-18 17:41:01,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,677 INFO sqlalchemy.engine.base.Engine ('홍익어린이집', '강준영', '서울특별시 양천구 지양로9길 5 (신월7동)', '02', '2607', '4523', 19)
2021-08-18 17:41:01,678 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,679 INFO sqlalchemy.engine.base.Engine ('키즈랜드어린이집', '황도현', '서울특별시 서초구 양재대로2길 90 ,서초보금자리2단지 관리동 (양재1동)', '02', '3462', '3500', 15)
2021-08-18 17:41:01,680 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,682 INFO sqlalchemy.engine.base.Engine ('바른예절어린이집', '장성호', '서울특별시 양천구 목동동로 50 ,목동신시가지아파트 1218동 106호 (신정7동)', '02', '2061', '5487', 19)
2021-08-18 17:41:01,684 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,684 INFO sqlalchemy.engine.base.Engine ('작은별어린이집', '장민서', '서울특별시 은평구 불광로8길 7 (불광제1동)', '02', '384', '1840', 22)
2021-08-18 17:41:01,685 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,686 INFO sqlalchemy.engine.base.Engine ('로얄키즈어린이집', '정준혁', '서울특별시 영등포구 당산로 68 ,진로아파트 104동 101호 (당산제1동)', '02', '6166', '5993', 20)
2021-08-18 17:41:01,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,689 INFO sqlalchemy.engine.base.Engine ('우방꿈나무어린이집', '박정남', '서울특별시 은평구 증산로3길 26-1 ,우방아파트 103동 101호 (증산동)', '070', '7340', '8080', 22)
2021-08-18 17:41:01,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,690 INFO sqlalchemy.engine.base.Engine ('보물섬어린이집', '류성수', '서울특별시 송파구 풍성로26길 31 ,202-106(풍납동, 송파현대힐스테이트) (풍납2동)', '02', '477', '3377', 18)
2021-08-18 17:41:01,691 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,692 INFO sqlalchemy.engine.base.Engine ('샘터어린이집', '김경회', '서울특별시 은평구 서오릉로11길 18 ,,18-1 (구산동)', '02', '353', '1038', 22)
2021-08-18 17:41:01,693 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,694 INFO sqlalchemy.engine.base.Engine ('하늘빛사임당어린이집', '박정수', '서울특별시 은평구 진관4로 77 ,702동(진관동, 은평뉴타운상림마을) (진관동)', '02', '354', '8825', 22)
2021-08-18 17:41:01,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,699 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '임은영', '서울특별시 중구 청구로 64 ,청구e편한세상아파트 106동 1층 (동화동)', '02', '2234', '1226', 24)
2021-08-18 17:41:01,701 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,702 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '권혜진', '서울특별시 노원구 동일로207길 50 (중계2.3동)', '02', '973', '9880', 9)
2021-08-18 17:41:01,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,703 INFO sqlalchemy.engine.base.Engine ('이화키즈어린이집', '오지원', '서울특별시 중랑구 신내로17길 39 ,714-101 (신내동, 진로아파트) (신내2동)', '02', '3422', '1002', 25)
2021-08-18 17:41:01,706 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,709 INFO sqlalchemy.engine.base.Engine ('보보키즈어린이집', '오준호', '서울특별시 영등포구 도신로 68 ,102동 103호(신길동,신길우성아파트) (신길제3동)', '02', '6335', '6004', 20)
2021-08-18 17:41:01,710 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,711 INFO sqlalchemy.engine.base.Engine ('미래클나무어린이집', '조건우', '서울특별시 은평구 백련산로 38 ,백련산 힐스테이트 209-101호 (응암제2동)', '02', '6408', '7976', 22)
2021-08-18 17:41:01,712 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,714 INFO sqlalchemy.engine.base.Engine ('하울어린이집', '안성민', '서울특별시 강서구 등촌로53길 39 ,103동 107호 (등촌제2동)', '02', '2643', '6789', 4)
2021-08-18 17:41:01,714 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,716 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '안지영', '서울특별시 양천구 목동동로10길 16-6 ,경남아너스빌 1504동 104호 (신정2동)', '070', '7782', '3517', 19)
2021-08-18 17:41:01,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,718 INFO sqlalchemy.engine.base.Engine ('미소어린이집', '류영진', '서울특별시 양천구 목동중앙북로14길 38 (목2동)', '070', '8267', '4280', 19)
2021-08-18 17:41:01,718 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,719 INFO sqlalchemy.engine.base.Engine ('세곡푸르지오어린이집', '이상훈', '서울특별시 강남구 자곡로 21 ,세곡푸르지오아파트(관리동) (세곡동)', '02', '3411', '5200', 1)
2021-08-18 17:41:01,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,720 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '김준혁', '서울특별시 서대문구 수색로 100 ,(북가좌동144 ) DMC래미안e편한세상(A)211동101호 (북가좌제1동)', '02', '6014', '8112', 14)
2021-08-18 17:41:01,722 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,723 INFO sqlalchemy.engine.base.Engine ('푸르미어린이집', '이준혁', '서울특별시 양천구 남부순환로67길 10-6 (신월4동)', '02', '2605', '6529', 19)
2021-08-18 17:41:01,724 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,724 INFO sqlalchemy.engine.base.Engine ('리틀푸른어린이집', '강종수', '서울특별시 영등포구 시흥대로181길 17 (대림제1동)', '02', '856', '0552', 20)
2021-08-18 17:41:01,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,726 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '안수빈', '서울특별시 성동구 독서당로 156 ,8동 109호(옥수동, 한남하이츠아파트) (옥수동)', '02', '2281', '3901', 16)
2021-08-18 17:41:01,728 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,729 INFO sqlalchemy.engine.base.Engine ('굿모닝어린이집', '윤지민', '서울특별시 강서구 화곡로68길 33 ,라인아파트101-104 (등촌제1동)', '02', '6341', '5200', 4)
2021-08-18 17:41:01,730 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,730 INFO sqlalchemy.engine.base.Engine ('벨라어린이집', '황정수', '서울특별시 송파구 백제고분로48가길 29 ,102호 (방이2동)', '02', '425', '2364', 18)
2021-08-18 17:41:01,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,732 INFO sqlalchemy.engine.base.Engine ('맑은숲어린이집', '황건우', '서울특별시 서대문구 수색로 100 ,407동 1층 (북가좌제1동)', '02', '307', '0873', 14)
2021-08-18 17:41:01,733 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,734 INFO sqlalchemy.engine.base.Engine ('성모어린이집', '임유진', '서울특별시 서대문구 세무서5길 24-2 (홍제제3동)', '02', '396', '0103', 14)
2021-08-18 17:41:01,735 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,735 INFO sqlalchemy.engine.base.Engine ('자연숲어린이집', '장건우', '서울특별시 서대문구 수색로 100 ,105동 1층 (북가좌제1동)', '02', '307', '0845', 14)
2021-08-18 17:41:01,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,737 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '박지원', '서울특별시 서대문구 수색로 100 ,2블럭 207동옆 (북가좌제1동)', '02', '307', '0862', 14)
2021-08-18 17:41:01,738 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,739 INFO sqlalchemy.engine.base.Engine ('하늘숲어린이집', '정예은', '서울특별시 서대문구 수색로 100 ,307동 1층 (북가좌제1동)', '02', '307', '0881', 14)
2021-08-18 17:41:01,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,740 INFO sqlalchemy.engine.base.Engine ('다니엘어린이집', '전정식', '서울특별시 송파구 올림픽로 435 ,225동 103호 (잠실4동)', '02', '420', '6002', 18)
2021-08-18 17:41:01,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,742 INFO sqlalchemy.engine.base.Engine ('온누리어린이집', '권정자', '서울특별시 양천구 오목로 90 ,우당아파트 101동 103호 (신월2동)', '02', '2685', '0990', 19)
2021-08-18 17:41:01,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,744 INFO sqlalchemy.engine.base.Engine ('구립해솔어린이집', '박건우', '서울특별시 강동구 상일로 74 ,310동1층 (상일동, 고덕리엔파크3단지아파트) (상일제2동)', '02', '426', '3244', 2)
2021-08-18 17:41:01,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,746 INFO sqlalchemy.engine.base.Engine ('샤인스쿨어린이집', '류민지', '서울특별시 관악구 당곡길 45-3 (보라매동)', '02', '888', '1143', 5)
2021-08-18 17:41:01,747 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,747 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '송성진', '서울특별시 마포구 토정로 158 ,관리동 1층 (서강동)', '02', '3142', '5353', 13)
2021-08-18 17:41:01,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,749 INFO sqlalchemy.engine.base.Engine ('세곡키즈어린이집', '한예준', '서울특별시 강남구 자곡로 21 ,LH푸르지오 215동 101호 (세곡동)', '070', '8747', '1108', 1)
2021-08-18 17:41:01,749 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,750 INFO sqlalchemy.engine.base.Engine ('롯데캐슬예랑어린이집', '전병철', '서울특별시 강동구 고덕로 131 ,111동 102호(암사동, 롯데캐슬퍼스트) (암사제3동)', '02', '3426', '9898', 2)
2021-08-18 17:41:01,751 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,751 INFO sqlalchemy.engine.base.Engine ('아이으뜸어린이집', '윤순자', '서울특별시 성동구 뚝섬로 51 ,102동 101호(옥수동, 옥수풍림아이원) (옥수동)', '02', '2297', '4650', 16)
2021-08-18 17:41:01,752 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,753 INFO sqlalchemy.engine.base.Engine ('꿈꾸는예지어린이집', '이준영', '서울특별시 관악구 난곡로26길 78 (난곡동)', '02', '857', '1616', 5)
2021-08-18 17:41:01,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,755 INFO sqlalchemy.engine.base.Engine ('화랑아띠어린이집', '한경자', '서울특별시 노원구 화랑로 564 (공릉2동)', '02', '973', '2250', 9)
2021-08-18 17:41:01,755 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,756 INFO sqlalchemy.engine.base.Engine ('마술피리어린이집', '황영길', '서울특별시 강남구 자곡로 21 ,206동 101호 (세곡동)', '02', '459', '4333', 1)
2021-08-18 17:41:01,757 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,757 INFO sqlalchemy.engine.base.Engine ('성산1동꼬마숲어린이집', '최광수', '서울특별시 마포구 성미산로11길 5 (성산제1동)', '02', '335', '6694', 13)
2021-08-18 17:41:01,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,759 INFO sqlalchemy.engine.base.Engine ('나린어린이집', '이영철', '서울특별시 송파구 올림픽로 435 ,파크리오 313-102 (잠실4동)', '070', '7431', '8577', 18)
2021-08-18 17:41:01,762 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,763 INFO sqlalchemy.engine.base.Engine ('올리브어린이집', '서도현', '서울특별시 송파구 올림픽로 435 ,306동104호(신천동,파크리오아파트) (잠실4동)', '02', '423', '2831', 18)
2021-08-18 17:41:01,764 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,765 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '권병철', '서울특별시 송파구 올림픽로 435 ,파크리오 213-104(신천동) (잠실4동)', '02', '421', '8893', 18)
2021-08-18 17:41:01,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,767 INFO sqlalchemy.engine.base.Engine ('반딧불어린이집', '신진호', '서울특별시 송파구 송파대로22길 19 ,1층 (문정1동)', '02', '403', '2310', 18)
2021-08-18 17:41:01,770 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,771 INFO sqlalchemy.engine.base.Engine ('키즈열매어린이집', '조영환', '서울특별시 강남구 자곡로 21 ,LH푸르지오아파트 205-103 (세곡동)', '02', '6407', '6110', 1)
2021-08-18 17:41:01,772 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,772 INFO sqlalchemy.engine.base.Engine ('푸른하늘어린이집', '이정호', '서울특별시 송파구 중대로12길 35 ,101동 102호(가락동, 가락우성2차아파트) (가락본동)', '02', '402', '1253', 18)
2021-08-18 17:41:01,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,774 INFO sqlalchemy.engine.base.Engine ('보배어린이집', '안예준', '서울특별시 강서구 강서로33가길 13-13 ,(화곡3동 1050-26) (화곡제3동)', '02', '2605', '1253', 4)
2021-08-18 17:41:01,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,777 INFO sqlalchemy.engine.base.Engine ('아이가어린이집', '박경자', '서울특별시 송파구 송이로 249 ,1층 (장지동)', '02', '430', '6341', 18)
2021-08-18 17:41:01,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,779 INFO sqlalchemy.engine.base.Engine ('예인꼬마숲어린이집', '정성민', '서울특별시 성동구 금호동4가 금호로 15 ,서울숲푸르지오 1차 105동 102호 (금호4가동)', '02', '2296', '8665', 16)
2021-08-18 17:41:01,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,780 INFO sqlalchemy.engine.base.Engine ('아장아장어린이집', '박민지', '서울특별시 강동구 고덕로 131 ,108동 101호(암사동, 롯데캐슬퍼스트) (암사제3동)', '02', '482', '5339', 2)
2021-08-18 17:41:01,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,782 INFO sqlalchemy.engine.base.Engine ('으뜸꼬마숲어린이집', '조서연', '서울특별시 성동구 금호동1가 독서당로 343 ,203동 102호 (금호동1가, 삼성래미안아파트) (금호1가동)', '02', '2293', '3555', 16)
2021-08-18 17:41:01,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,783 INFO sqlalchemy.engine.base.Engine ('구립 왕십리어린이집', '윤수빈', '서울특별시 성동구 고산자로 262 ,구립 왕십리어린이집 (행당제1동)', '02', '2293', '2010', 16)
2021-08-18 17:41:01,784 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,784 INFO sqlalchemy.engine.base.Engine ('뚜띠어린이집', '정서연', '서울특별시 강서구 허준로 139 ,307-103 (가양제2동)', '070', '8748', '6916', 4)
2021-08-18 17:41:01,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,785 INFO sqlalchemy.engine.base.Engine ('구립 금호자이미소어린이집', '윤성민', '서울특별시 성동구 금호로 117 ,(금호동2가) 금호자이1차아파트 관리동 1층 (104동 앞) (금호2.3가동)', '02', '2233', '7737', 16)
2021-08-18 17:41:01,786 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,787 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '오혜진', '서울특별시 동작구 장승배기로22길 15 (노량진제1동)', '02', '6014', '6243', 12)
2021-08-18 17:41:01,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,788 INFO sqlalchemy.engine.base.Engine ('혜윰어린이집', '서지훈', '서울특별시 강동구 상암로63길 39-4 (명일제2동)', '02', '427', '7012', 2)
2021-08-18 17:41:01,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,789 INFO sqlalchemy.engine.base.Engine ('맘앤아이어린이집', '임영철', '서울특별시 송파구 올림픽로 435 ,217동104호(신천동, 파크리오아파트) (잠실4동)', '02', '420', '1108', 18)
2021-08-18 17:41:01,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,791 INFO sqlalchemy.engine.base.Engine ('토토어린이집', '권유진', '서울특별시 성동구 금호동4가 금호로 17 ,203동 104호(금호동4가, 서울숲2차푸르지오) (금호4가동)', '02', '6326', '3977', 16)
2021-08-18 17:41:01,792 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,793 INFO sqlalchemy.engine.base.Engine ('꼬마대통령어린이집', '박성수', '서울특별시 동작구 흑석한강로 27 ,107동 103호 (흑석동 336, 흑석한강푸르지오) (흑석동)', '02', '537', '1990', 12)
2021-08-18 17:41:01,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,795 INFO sqlalchemy.engine.base.Engine ('삼환어린이집', '조준영', '서울특별시 영등포구 영중로 145 ,삼환아파트 104동 101호 (영등포동)', '02', '2679', '5967', 20)
2021-08-18 17:41:01,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,798 INFO sqlalchemy.engine.base.Engine ('쥬빌리어린이집', '최성호', '서울특별시 강서구 방화대로23길 60-15 ,(방화1동 611-165) (방화제1동)', '02', '2661', '1193', 4)
2021-08-18 17:41:01,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,800 INFO sqlalchemy.engine.base.Engine ('파스텔어린이집', '한준영', '서울특별시 양천구 오목로17길 7 ,동도센트리움 101동 103호 (신월2동)', '02', '2698', '5705', 19)
2021-08-18 17:41:01,801 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,802 INFO sqlalchemy.engine.base.Engine ('키즈온어린이집', '정예은', '서울특별시 송파구 오금로23길 18 ,키즈온어린이집 (방이2동)', '02', '420', '9135', 18)
2021-08-18 17:41:01,809 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,810 INFO sqlalchemy.engine.base.Engine ('파크빅스맘어린이집', '최정웅', '서울특별시 송파구 성내천로47길 38 ,송파파크데일아파트 관리동(마천동, 송파파크데일아파트단지내) (마천1동)', '02', '6954', '0807', 18)
2021-08-18 17:41:01,811 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,812 INFO sqlalchemy.engine.base.Engine ('IBK참!좋은어린이집', '박은경', '서울특별시 노원구 동일로 1527 ,중소기업은행 2층 (상계8동)', '02', '937', '7203', 9)
2021-08-18 17:41:01,813 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,814 INFO sqlalchemy.engine.base.Engine ('빛나라어린이집', '최도현', '서울특별시 용산구 이촌로 303 ,23동 103호(이촌동, 현대아파트) (이촌제1동)', '02', '792', '7906', 21)
2021-08-18 17:41:01,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,817 INFO sqlalchemy.engine.base.Engine ('우정어린이집', '류동현', '서울특별시 동작구 여의대방로62길 23 ,102동 102호, 103호 (대방동)', '02', '834', '7307', 12)
2021-08-18 17:41:01,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,819 INFO sqlalchemy.engine.base.Engine ('구립 사과꽃어린이집', '조준영', '서울특별시 성동구 금호로 111 ,(금호동2가) 래미안하이리버 임대동 1층 (금호2.3가동)', '02', '2231', '0469', 16)
2021-08-18 17:41:01,822 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,823 INFO sqlalchemy.engine.base.Engine ('구립한울어린이집', '한지민', '서울특별시 동작구 보라매로9다길 15 (신대방제2동)', '02', '821', '4645', 12)
2021-08-18 17:41:01,824 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,825 INFO sqlalchemy.engine.base.Engine ('별산솔어린이집', '신성진', '서울특별시 은평구 불광로6길 6-9 (불광제1동)', '02', '389', '2977', 22)
2021-08-18 17:41:01,827 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,828 INFO sqlalchemy.engine.base.Engine ('법무부 남부보라미어린이집', '김민수', '서울특별시 구로구 금오로 865 ,법무부 서울남부구치소내 체육관 1층 (오류제2동)', '02', '2611', '1122', 7)
2021-08-18 17:41:01,829 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,832 INFO sqlalchemy.engine.base.Engine ('사랑뜰어린이집', '조정수', '서울특별시 송파구 성내천로47길 38 ,송파파크데일2단지 205-104 (마천1동)', '02', '400', '5455', 18)
2021-08-18 17:41:01,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,833 INFO sqlalchemy.engine.base.Engine ('성화어린이집', '류예준', '서울특별시 은평구 증산로5길 30 (증산동)', '02', '302', '1626', 22)
2021-08-18 17:41:01,835 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,836 INFO sqlalchemy.engine.base.Engine ('큰빛어린이집', '조경숙', '서울특별시 광진구 자양로 323 ,나동 101동(구의동, 궁전빌라) (구의제2동)', '02', '444', '7779', 6)
2021-08-18 17:41:01,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,838 INFO sqlalchemy.engine.base.Engine ('미래나무어린이집', '권성호', '서울특별시 종로구 종로33길 15 ,(연지동) (종로5.6가동)', '02', '747', '9557', 23)
2021-08-18 17:41:01,839 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,840 INFO sqlalchemy.engine.base.Engine ('두꼬마어린이집', '이은영', '서울특별시 송파구 오금로31길 15-6 ,1층 (방이1동)', '02', '415', '2411', 18)
2021-08-18 17:41:01,841 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,842 INFO sqlalchemy.engine.base.Engine ('현대숲어린이집', '장민수', '서울특별시 서대문구 통일로34길 46 ,110동 103호(홍제동, 인왕산현대아파트) (홍제제2동)', '02', '395', '8885', 14)
2021-08-18 17:41:01,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,844 INFO sqlalchemy.engine.base.Engine ('아이비키즈어린이집', '송종수', '서울특별시 광진구 뚝섬로35길 14 ,(자양동, 한라아파트, 상가 B동 101호 (자양제3동)', '02', '446', '1260', 6)
2021-08-18 17:41:01,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,846 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '정순자', '서울특별시 용산구 이촌로 181 ,108동 103호(이촌동, 한강대우아파트) (이촌제1동)', '02', '790', '2221', 21)
2021-08-18 17:41:01,848 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,848 INFO sqlalchemy.engine.base.Engine ('세빛어린이집', '최건우', '서울특별시 강동구 올림픽로88길 8 ,(천호2동 314-13) (천호제2동)', '02', '472', '0532', 2)
2021-08-18 17:41:01,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,850 INFO sqlalchemy.engine.base.Engine ('예꿈어린이집', '안미숙', '서울특별시 강서구 월정로 160 ,화곡대림아파트 1동 104호 (화곡동 361-1) (화곡제1동)', '070', '4642', '7953', 4)
2021-08-18 17:41:01,851 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,852 INFO sqlalchemy.engine.base.Engine ('구립 키움어린이집', '황영숙', '서울특별시 마포구 신촌로12길 11 ,신촌성결교회내 (서교동)', '02', '338', '5671', 13)
2021-08-18 17:41:01,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,855 INFO sqlalchemy.engine.base.Engine ('꼬마궁어린이집', '전민지', '서울특별시 강서구 등촌로13바길 49-12 (화곡제4동)', '02', '2652', '3805', 4)
2021-08-18 17:41:01,855 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,856 INFO sqlalchemy.engine.base.Engine ('지예슬어린이집', '송영숙', '서울특별시 용산구 이촌로87길 13 ,107동 103호(이촌동,강촌아파트) (이촌제1동)', '02', '6351', '6815', 21)
2021-08-18 17:41:01,857 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,858 INFO sqlalchemy.engine.base.Engine ('구로생명숲어린이집', '임정호', '서울특별시 구로구 천왕로1길 5 ,(오류2동, 구로생명숲어린이집) (오류제2동)', '02', '2616', '1671', 7)
2021-08-18 17:41:01,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:01,860 INFO sqlalchemy.engine.base.Engine ('아이비어린이집', '조지은', '서울특별시 강동구 상암로 225 ,2동 101호(명일동, 삼익맨션) (명일제1동)', '02', '427', '3210', 2)
2021-08-18 17:41:01,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,862 INFO sqlalchemy.engine.base.Engine ('하람어린이집', '조영환', '서울특별시 동작구 동작대로29길 81 ,대아아파트 601동 108호 (사당제2동)', '02', '533', '3005', 12)
2021-08-18 17:41:01,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,864 INFO sqlalchemy.engine.base.Engine ('마주어린이집', '임영식', '서울특별시 중구 중림로 10 ,삼성사이버빌리지 112-102 (중림동)', '02', '6324', '6325', 24)
2021-08-18 17:41:01,865 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,866 INFO sqlalchemy.engine.base.Engine ('꼬마별옹기장이어린이집', '최수빈', '서울특별시 양천구 목동중앙남로3길 11 ,금호아파트 101동 107호 (목4동)', '02', '2644', '9118', 19)
2021-08-18 17:41:01,869 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,870 INFO sqlalchemy.engine.base.Engine ('샤론어린이집', '안정수', '서울특별시 금천구 시흥대로39길 48-3 ,(시흥1동) 시흥1동 492-24 (시흥제1동)', '02', '808', '1556', 8)
2021-08-18 17:41:01,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,872 INFO sqlalchemy.engine.base.Engine ('자빈어린이집', '권민지', '서울특별시 강동구 양재대로151길 16 ,(명일동 305-23) (명일제1동)', '02', '3428', '8255', 2)
2021-08-18 17:41:01,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,873 INFO sqlalchemy.engine.base.Engine ('더크는어린이집', '장민석', '서울특별시 영등포구 대림로8길 9-10 (대림제1동)', '02', '848', '5695', 20)
2021-08-18 17:41:01,874 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,875 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '윤영진', '서울특별시 강서구 국회대로7길 91 ,신도금잔디아파트 104호 (화곡제2동)', '02', '2607', '6421', 4)
2021-08-18 17:41:01,876 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,877 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '황정자', '서울특별시 은평구 진관3로 77 ,구파발 926동 101호 (진관동)', '02', '359', '7746', 22)
2021-08-18 17:41:01,878 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,879 INFO sqlalchemy.engine.base.Engine ('아리어린이집', '안정순', '서울특별시 양천구 오목로11길 17-10 ,두원아파트 A동 101호 (신월2동)', '02', '6402', '4740', 19)
2021-08-18 17:41:01,880 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,883 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '안정순', '서울특별시 송파구 오금로21길 12 ,101호 (방이2동)', '02', '6084', '7928', 18)
2021-08-18 17:41:01,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,885 INFO sqlalchemy.engine.base.Engine ('빛나라어린이집', '조건우', '서울특별시 강동구 상암로 8-1 ,1층(암사동 510-5 ) (암사제2동)', '02', '441', '8097', 2)
2021-08-18 17:41:01,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,887 INFO sqlalchemy.engine.base.Engine ('별나라어린이집', '권영식', '서울특별시 송파구 양산로4길 16 ,502동 103호(거여동, 거여5단지아파트) (거여2동)', '02', '6403', '9131', 18)
2021-08-18 17:41:01,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,889 INFO sqlalchemy.engine.base.Engine ('보보 어린이집', '서도현', '서울특별시 양천구 목동동로12길 60 ,목동현대아파트 103-103 (신정2동)', '02', '2652', '5431', 19)
2021-08-18 17:41:01,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,892 INFO sqlalchemy.engine.base.Engine ('금호어린이집', '이성진', '서울특별시 중랑구 공릉로2길 39 ,,102동106호(묵동,금호어울림아파트) (묵제1동)', '02', '6012', '7579', 25)
2021-08-18 17:41:01,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,894 INFO sqlalchemy.engine.base.Engine ('아이조아어린이집', '전준영', '서울특별시 동작구 상도로 421 ,관악현대아파트 107동 107호 (상도제1동)', '02', '825', '7468', 12)
2021-08-18 17:41:01,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,896 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '안정웅', '서울특별시 관악구 은천로 93 ,벽산블루밍 아파트 209-102 (은천동)', '02', '6265', '6605', 5)
2021-08-18 17:41:01,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,898 INFO sqlalchemy.engine.base.Engine ('푸르미어린이집', '권예준', '서울특별시 동작구 흑석한강로 27 ,단지 내 푸르미어린이집 (흑석동 336,흑석한강푸르지오아파트) (흑석동)', '02', '815', '5004', 12)
2021-08-18 17:41:01,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,900 INFO sqlalchemy.engine.base.Engine ('마이메리어린이집', '송영진', '서울특별시 송파구 문정로11길 15 ,101(가락동 ,세림빌라트제1층 101호~102호) (가락2동)', '02', '403', '8113', 18)
2021-08-18 17:41:01,901 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,902 INFO sqlalchemy.engine.base.Engine ('해누리어린이집', '조정호', '서울특별시 영등포구 대림로 256 ,성원아파트 101동 103호 (대림제3동)', '02', '6105', '5113', 20)
2021-08-18 17:41:01,903 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,904 INFO sqlalchemy.engine.base.Engine ('담희어린이집', '정경숙', '서울특별시 강남구 영동대로138길 12 ,청담자이아파트 관리동 (청담동)', '02', '3445', '1120', 1)
2021-08-18 17:41:01,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,906 INFO sqlalchemy.engine.base.Engine ('미소래스콜라어린이집', '조경자', '서울특별시 양천구 목동중앙남로 46 ,미소래아파트 104호 (목4동)', '02', '2643', '8535', 19)
2021-08-18 17:41:01,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,910 INFO sqlalchemy.engine.base.Engine ('아기숲어린이집', '서예준', '서울특별시 노원구 동일로208길 20 ,214동 106호(중계동, 무지개아파트) (중계2.3동)', '02', '978', '0127', 9)
2021-08-18 17:41:01,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,912 INFO sqlalchemy.engine.base.Engine ('사랑누리어린이집', '김진호', '서울특별시 노원구 한글비석로 530 ,1210동 101호 (상계9동)', '02', '935', '6579', 9)
2021-08-18 17:41:01,913 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,914 INFO sqlalchemy.engine.base.Engine ('제이앤어린이집', '류정자', '서울특별시 강동구 명일로 172 ,105동 101호(둔촌동, 둔촌푸르지오아파트) (둔촌제2동)', '02', '419', '8398', 2)

2021-08-18 17:41:01,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,916 INFO sqlalchemy.engine.base.Engine ('나봄어린이집', '김지영', '서울특별시 은평구 통일로 586-19 ,JR아파트 102-102 (녹번동)', '02', '6383', '9074', 22)
2021-08-18 17:41:01,917 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,918 INFO sqlalchemy.engine.base.Engine ('kids-sure어린이집', '장혜진', '서울특별시 종로구 종로 14 ,(서린동) (종로1.2.3.4가동)', '02', '723', '1272', 23)
2021-08-18 17:41:01,920 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,920 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '임정자', '서울특별시 동작구 국사봉길 98 ,신건드림원빌 1층 101호 (상도제3동)', '02', '826', '9366', 12)
2021-08-18 17:41:01,922 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,924 INFO sqlalchemy.engine.base.Engine ('천사나라어린이집', '조민재', '서울특별시 동작구 여의대방로 30 ,현대아파트 102동 107호 (신대방1동 707번지) (신대방제1동)', '02', '831', '5306', 12)
2021-08-18 17:41:01,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,926 INFO sqlalchemy.engine.base.Engine ('꿈나래어린이집', '황은영', '서울특별시 마포구 월드컵북로 235 ,25동 105(성산동, 성산시영아파트) (성산제2동)', '02', '304', '3644', 13)
2021-08-18 17:41:01,927 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,928 INFO sqlalchemy.engine.base.Engine ('꿈동산어린이집', '강정식', '서울특별시 영등포구 신길로62가길 1-2 (영등포본동)', '02', '833', '3559', 20)
2021-08-18 17:41:01,929 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,930 INFO sqlalchemy.engine.base.Engine ('워커힐행복어린이집', '황준영', '서울특별시 광진구 워커힐로 177 ,(광장동) (광장동)', '02', '450', '6500', 6)
2021-08-18 17:41:01,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,932 INFO sqlalchemy.engine.base.Engine ('지우어린이집', '윤은정', '서울특별시 마포구 성미산로15길 28 (연남동)', '02', '322', '8307', 13)
2021-08-18 17:41:01,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,934 INFO sqlalchemy.engine.base.Engine ('조이너스어린이집', '장영식', '서울특별시 강남구 역삼로19길 12 ,조이너스아파트 101호 (역삼1동)', '02', '566', '9550', 1)
2021-08-18 17:41:01,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,936 INFO sqlalchemy.engine.base.Engine ('디큐브어린이집', '임지민', '서울특별시 구로구 경인로 662 (신도림동)', '02', '2672', '8788', 7)
2021-08-18 17:41:01,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,938 INFO sqlalchemy.engine.base.Engine ('이레어린이집', '안정자', '서울특별시 동작구 사당로10길 1 ,108호 (사당동) (사당제5동)', '02', '523', '7830', 12)
2021-08-18 17:41:01,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,940 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '박유진', '서울특별시 노원구 한글비석로 530 ,1213동 108호 (상계9동)', '02', '952', '4098', 9)
2021-08-18 17:41:01,941 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,942 INFO sqlalchemy.engine.base.Engine ('하늘숲어린이집', '권준혁', '서울특별시 강동구 암사19길 25 ,101동 106호(암사동, 한솔아파트) (암사제1동)', '02', '442', '6056', 2)
2021-08-18 17:41:01,943 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,944 INFO sqlalchemy.engine.base.Engine ('아이러브유어린이집', '임예은', '서울특별시 중랑구 용마산로129가길 54 ,1층 (신내1동)', '02', '432', '1239', 25)
2021-08-18 17:41:01,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,946 INFO sqlalchemy.engine.base.Engine ('이편한어린이집', '오지훈', '서울특별시 양천구 신정로13길 38 ,101동 104호 (신정e-편한세상, 신정3동) (신정3동)', '02', '2693', '7179', 19)
2021-08-18 17:41:01,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,949 INFO sqlalchemy.engine.base.Engine ('하늘정원어린이집', '권정호', '서울특별시 양천구 목동동로 50 ,1204동 104호 (목동신시가지아파트, 신정7동) (신정7동)', '02', '2652', '0452', 19)
2021-08-18 17:41:01,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,954 INFO sqlalchemy.engine.base.Engine ('해피아이어린이집', '권유진', '서울특별시 중랑구 봉화산로56길 123 ,,3동 101호(신내동 ,중앙하이츠아파트) (신내1동)', '02', '493', '6200', 25)
2021-08-18 17:41:01,955 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,955 INFO sqlalchemy.engine.base.Engine ('자연숲어린이집', '김미경', '서울특별시 마포구 월드컵북로30길 9-22 ,105-104 (성산제2동)', '02', '303', '1536', 13)
2021-08-18 17:41:01,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,957 INFO sqlalchemy.engine.base.Engine ('우리들어린이집', '김성호', '서울특별시 구로구 구일로 154-17 ,2동 101호(구로동, 우방아파트) (구로제1동)', '070', '8759', '3685', 7)
2021-08-18 17:41:01,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,959 INFO sqlalchemy.engine.base.Engine ('자연뜰어린이집', '장민지', '서울특별시 구로구 경인로 248-14 ,102동 101호(오류동, 동부아파트) (오류제1동)', '02', '2625', '8887', 7)
2021-08-18 17:41:01,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,962 INFO sqlalchemy.engine.base.Engine ('남성교회어린이집', '송지훈', '서울특별시 관악구 남현1가길 34 (남현동)', '02', '584', '5579', 5)
2021-08-18 17:41:01,964 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,965 INFO sqlalchemy.engine.base.Engine ('동성스마일어린이집', '조영일', '서울특별시 강서구 강서로68길 108 ,동성아파트 106-106 (등촌제3동)', '02', '2699', '1003', 4)
2021-08-18 17:41:01,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,967 INFO sqlalchemy.engine.base.Engine ('드림아이어린이집', '이미숙', '서울특별시 양천구 오목로3길 17 ,삼정그린뷰아파트 103동 101호 (신월4동)', '02', '2654', '9481', 19)
2021-08-18 17:41:01,968 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,969 INFO sqlalchemy.engine.base.Engine ('세꿈어린이집', '임영진', '서울특별시 양천구 목동서로 340 ,926동 107호 (목동신시가지아파트, 신정1동) (신정1동)', '02', '2648', '8136', 19)
2021-08-18 17:41:01,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,970 INFO sqlalchemy.engine.base.Engine ('구립코알라어린이집', '한영숙', '서울특별시 강동구 상일로 152 ,107동 1층(강일동 707, 고덕리엔파크1단지아파트) (강일동)', '02', '426', '0707', 2)

2021-08-18 17:41:01,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,972 INFO sqlalchemy.engine.base.Engine ('꿈담터어린이집', '송지원', '서울특별시 구로구 공원로11길 45 (구로제5동)', '02', '863', '2810', 7)
2021-08-18 17:41:01,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,974 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '최지원', '서울특별시 강동구 상암로 11 ,106동 104호(암사동, 선사현대아파트) (암사제2동)', '02', '428', '6064', 2)
2021-08-18 17:41:01,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,975 INFO sqlalchemy.engine.base.Engine ('서초꿈아이자람어린이집', '신영환', '서울특별시 서초구 남부순환로347길 21-20 (서초2동)', '02', '522', '1486', 15)
2021-08-18 17:41:01,977 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,978 INFO sqlalchemy.engine.base.Engine ('시영어린이집', '김민수', '서울특별시 양천구 신월로 99 ,시영아파트 13동 106호 (신월7동)', '02', '716', '5063', 19)
2021-08-18 17:41:01,979 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,979 INFO sqlalchemy.engine.base.Engine ('아이맘몬테소리어린이집', '오서현', '서울특별시 은평구 백련산로 36 ,백련산힐스테이트 308동 102호 (응암제2동)', '02', '6085', '3650', 22)
2021-08-18 17:41:01,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,981 INFO sqlalchemy.engine.base.Engine ('킹스키즈어린이집', '박성민', '서울특별시 서초구 방배로15길 22 (방배1동)', '02', '522', '3735', 15)
2021-08-18 17:41:01,982 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,982 INFO sqlalchemy.engine.base.Engine ('라온제나어린이집', '안지훈', '서울특별시 노원구 마들로 31 ,107동 103호 (월계동 그랑빌아파트) (월계3동)', '02', '979', '5571', 9)
2021-08-18 17:41:01,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,984 INFO sqlalchemy.engine.base.Engine ('예성어린이집', '황성호', '서울특별시 노원구 마들로 31 ,125동 101호(월계동, 그랑빌아파트) (월계3동)', '02', '979', '2339', 9)
2021-08-18 17:41:01,985 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,995 INFO sqlalchemy.engine.base.Engine ('베베타운어린이집', '황지혜', '서울특별시 관악구 성현로 80 ,104-101(봉천동,관악드림타운) (성현동)', '070', '7801', '9057', 5)
2021-08-18 17:41:01,997 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:01,998 INFO sqlalchemy.engine.base.Engine ('오금사임당어린이집', '강혜진', '서울특별시 송파구 동남로23길 50 (오금동)', '02', '402', '2250', 18)
2021-08-18 17:41:02,000 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,001 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '서동현', '서울특별시 동작구 현충로 151 ,102동 103호 (흑석동 28,한강현대아파트) (흑석동)', '02', '6264', '5948', 12)
2021-08-18 17:41:02,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,003 INFO sqlalchemy.engine.base.Engine ('참어린이집', '서준영', '서울특별시 관악구 신림로29길 8 ,신림현대아파트 110동 102호 (서림동)', '02', '875', '7992', 5)
2021-08-18 17:41:02,004 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,005 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '조영환', '서울특별시 영등포구 도신로29길 28 ,영등포푸르지오 112동 104호 (영등포본동)', '02', '6326', '7127', 20)
2021-08-18 17:41:02,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,006 INFO sqlalchemy.engine.base.Engine ('엄마맘어린이집', '최지훈', '서울특별시 성동구 금호로 107 ,103동 102호 (금호동2가, 래미안하이리버) (금호2.3가동)', '02', '2233', '2235', 16)
2021-08-18 17:41:02,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,007 INFO sqlalchemy.engine.base.Engine ('꼬마친구어린이집', '이수빈', '서울특별시 중랑구 봉화산로 130 ,1304-104 (상봉동, 쌍용아파트) (상봉제1동)', '02', '3421', '6373', 25)
2021-08-18 17:41:02,008 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,010 INFO sqlalchemy.engine.base.Engine ('빛나는어린이집', '오경숙', '서울특별시 동대문구 망우로20길 86 ,105동 103호(휘경동, 브라운스톤아파트) (휘경제2동)', '02', '2217', '7711', 11)
2021-08-18 17:41:02,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,013 INFO sqlalchemy.engine.base.Engine ('유나어린이집', '송정호', '서울특별시 노원구 월계로55길 15 ,302동 107호(월계동, 사슴아파트) (월계3동)', '02', '974', '1114', 9)
2021-08-18 17:41:02,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,015 INFO sqlalchemy.engine.base.Engine ('사랑맘어린이집', '송준호', '서울특별시 노원구 섬밭로 265 ,1동 109호(중계동, 경남아파트) (중계2.3동)', '02', '949', '2266', 9)
2021-08-18 17:41:02,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,019 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '신성호', '서울특별시 노원구 동일로207길 18 ,중계그린아파트 101-111 (중계2.3동)', '070', '7536', '9656', 9)
2021-08-18 17:41:02,020 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,020 INFO sqlalchemy.engine.base.Engine ('현대 키즈맘 어린이집', '이미영', '서울특별시 영등포구 도신로4길 14 ,현대아파트 101동 109호 (대림제3동)', '02', '848', '1007', 20)
2021-08-18 17:41:02,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,021 INFO sqlalchemy.engine.base.Engine ('너울가지어린이집', '신은경', '서울특별시 은평구 가좌로12길 15 ,(신사동, 은평두산위브2차), 102동 102호 (신사제1동)', '02', '383', '3303', 22)
2021-08-18 17:41:02,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,023 INFO sqlalchemy.engine.base.Engine ('방이숲어린이집', '박영길', '서울특별시 송파구 위례성대로14길 7 ,1층 (방이1동)', '02', '422', '7688', 18)
2021-08-18 17:41:02,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,029 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '서민수', '서울특별시 노원구 노원로 564 ,1012동 101호(상계동, 주공10단지아파트) (상계8동)', '070', '8941', '3096', 9)
2021-08-18 17:41:02,030 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,031 INFO sqlalchemy.engine.base.Engine ('예쁘지오어린이집', '최순자', '서울특별시 중랑구 신내로 51 ,103-104(신내동, 성원아파트) (신내2동)', '02', '433', '6645', 25)
2021-08-18 17:41:02,034 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,036 INFO sqlalchemy.engine.base.Engine ('해피아이 어린이집', '한준호', '서울특별시 영등포구 가마산로 312 ,신동아아파트 3동 102호 (대림제3동)', '02', '833', '9722', 20)
2021-08-18 17:41:02,037 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,038 INFO sqlalchemy.engine.base.Engine ('진영꼬마숲어린이집', '신예준', '서울특별시 강서구 곰달래로27길 6 ,301호 (화곡제8동)', '02', '2604', '5111', 4)
2021-08-18 17:41:02,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,039 INFO sqlalchemy.engine.base.Engine ('동화키즈 어린이집', '윤정웅', '서울특별시 송파구 동남로8길 19 ,1층 (문정1동)', '02', '448', '5561', 18)
2021-08-18 17:41:02,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,041 INFO sqlalchemy.engine.base.Engine ('리원어린이집', '안민석', '서울특별시 중구 만리재로33길 21 ,(만리동1가, LIG서울역리가) 102-102 (중림동)', '02', '313', '5355', 24)
2021-08-18 17:41:02,042 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,043 INFO sqlalchemy.engine.base.Engine ('아이누리어린이집', '김상철', '서울특별시 광진구 뚝섬로33길 20 ,(자양3동, 한라아파트 101동 104호) (자양제3동)', '02', '2201', '1260', 6)
2021-08-18 17:41:02,044 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,045 INFO sqlalchemy.engine.base.Engine ('토토빌어린이집', '강경숙', '서울특별시 노원구 동일로227길 26 ,1606동 105호(상계동, 주공아파트) (상계8동)', '02', '6316', '9149', 9)
2021-08-18 17:41:02,046 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,046 INFO sqlalchemy.engine.base.Engine ('베베몬테소리어린이집', '정준혁', '서울특별시 구로구 새말로9길 45 ,102동 102호 (구로동, 신도림현대아파트0 (구로제5동)', '02', '859', '4649', 7)
2021-08-18 17:41:02,048 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,048 INFO sqlalchemy.engine.base.Engine ('아이큰숲어린이집', '김정자', '서울특별시 송파구 백제고분로48가길 21 ,1층 (방이2동)', '02', '417', '7177', 18)
2021-08-18 17:41:02,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,050 INFO sqlalchemy.engine.base.Engine ('영재 어린이집', '박현정', '서울특별시 성동구 살곶이길 50 ,103동 101호 (마장동,현대아파트) (마장동)', '02', '2295', '7077', 16)
2021-08-18 17:41:02,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,052 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '전정호', '서울특별시 관악구 관악로 304 ,현대아파트 123동 104호 (청림동)', '02', '876', '2207', 5)
2021-08-18 17:41:02,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,054 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '안영일', '서울특별시 관악구 관악로 304 ,현대아파트113동101호 (청림동)', '02', '882', '1894', 5)
2021-08-18 17:41:02,055 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,056 INFO sqlalchemy.engine.base.Engine ('푸르미어린이집', '안준호', '서울특별시 중랑구 봉화산로56길 51 ,102-104(신내동, 우남푸르미아파트) (신내1동)', '02', '3421', '5005', 25)
2021-08-18 17:41:02,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,060 INFO sqlalchemy.engine.base.Engine ('동화숲어린이집', '전지원', '서울특별시 영등포구 도신로 31 ,현대3차아파트 304동 104호 (대림제3동)', '02', '845', '1271', 20)
2021-08-18 17:41:02,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,061 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '류정호', '서울특별시 영등포구 선유서로 31 ,현대6차아파트 601동 101호 (문래동)', '02', '6341', '7171', 20)
2021-08-18 17:41:02,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,063 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '안영일', '서울특별시 서초구 마방로10길 54-19 ,(양재동) (양재2동)', '070', '8247', '1798', 15)
2021-08-18 17:41:02,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,066 INFO sqlalchemy.engine.base.Engine ('늘푸른 어린이집', '서지원', '서울특별시 성동구 금호산길 8 ,108-105(금호동3가,금호1차푸르지오) (금호2.3가동)', '02', '2253', '0079', 16)
2021-08-18 17:41:02,066 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,067 INFO sqlalchemy.engine.base.Engine ('리틀삐아제어린이집', '안순자', '서울특별시 서대문구 증가로 200-5 ,1층 (북가좌제2동)', '02', '306', '3360', 14)
2021-08-18 17:41:02,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,069 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '최순자', '서울특별시 광진구 뚝섬로 576 ,201동 107호(자양동, 우성2차아파트) (자양제3동)', '070', '7856', '6645', 6)
2021-08-18 17:41:02,069 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,070 INFO sqlalchemy.engine.base.Engine ('아이행복어린이집', '이지은', '서울특별시 양천구 신월로20길 7 ,두산위브아파트 101동 104호 (신월2동)', '02', '2602', '9979', 19)
2021-08-18 17:41:02,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,071 INFO sqlalchemy.engine.base.Engine ('해뜨는어린이집', '윤민수', '서울특별시 중랑구 봉화산로56길 123 ,4동 110호(신내동, 중앙하이츠아파트) (신내1동)', '02', '433', '7117', 25)
2021-08-18 17:41:02,072 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,075 INFO sqlalchemy.engine.base.Engine ('아이린어린이집', '서정식', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트119동103호 (청림동)', '02', '878', '2323', 5)
2021-08-18 17:41:02,077 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,078 INFO sqlalchemy.engine.base.Engine ('한양에코캠어린이집', '정영철', '서울특별시 서대문구 응암로 28 ,(북가좌동 431)연희한양아파트 2동 102호 (북가좌제1동)', '02', '6351', '6353', 14)
2021-08-18 17:41:02,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,080 INFO sqlalchemy.engine.base.Engine ('베베스쿨어린이집', '강정수', '서울특별시 송파구 올림픽로35길 104 ,24동 103호(신천동, 장미아파트) (잠실6동)', '02', '470', '5345', 18)
2021-08-18 17:41:02,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,082 INFO sqlalchemy.engine.base.Engine ('완두콩어린이집', '서영진', '서울특별시 동작구 대방동27길 36 ,(대방동 380-8) (대방동)', '02', '2296', '9888', 12)
2021-08-18 17:41:02,083 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,084 INFO sqlalchemy.engine.base.Engine ('우성꼬마별어린이집', '류정호', '서울특별시 구로구 구일로2길 60 ,202동 105호 (구로동, 구일우성아파트) (구로제1동)', '02', '866', '2105', 7)

2021-08-18 17:41:02,085 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,086 INFO sqlalchemy.engine.base.Engine ('유니어린이집', '류성진', '서울특별시 노원구 동일로227길 86 ,,1610동 101호(상계동, 상계주공16단지아파트) (상계8동)', '02', '934', '0719', 9)
2021-08-18 17:41:02,087 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,088 INFO sqlalchemy.engine.base.Engine ('삼성해뜰어린이집', '김준서', '서울특별시 마포구 마포대로 173-15 ,공덕5차래미안 관리동 (아현동)', '02', '702', '7955', 13)
2021-08-18 17:41:02,089 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,090 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '권지훈', '서울특별시 은평구 연서로35길 6-1 (불광제2동)', '02', '356', '9004', 22)
2021-08-18 17:41:02,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,091 INFO sqlalchemy.engine.base.Engine ('올리비아어린이집', '안영진', '서울특별시 관악구 관악로30길 27 ,관악푸르지오아파트107동103호 (청림동)', '02', '6265', '4996', 5)
2021-08-18 17:41:02,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,093 INFO sqlalchemy.engine.base.Engine ('예그린어린이집', '강지은', '서울특별시 중랑구 공릉로13길 30 ,102동 104호(묵동, 묵동신도아파트) (묵제1동)', '02', '6215', '0084', 25)
2021-08-18 17:41:02,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,095 INFO sqlalchemy.engine.base.Engine ('윤슬어린이집', '안진호', '서울특별시 노원구 마들로 111 ,,27동 104호(월계3동 삼호아파트) (월계3동)', '070', '8249', '6692', 9)
2021-08-18 17:41:02,096 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,097 INFO sqlalchemy.engine.base.Engine ('하람어린이집', '송정순', '서울특별시 관악구 난곡로 55 ,202동 101호(관악산휴먼시아,신림동) (난향동)', '02', '838', '7723', 5)
2021-08-18 17:41:02,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,098 INFO sqlalchemy.engine.base.Engine ('삼성GEC어린이집', '전민지', '서울특별시 강동구 상일로6길 26 (상일제2동)', '02', '2053', '6200', 2)
2021-08-18 17:41:02,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,099 INFO sqlalchemy.engine.base.Engine ('은솔어린이집', '전준혁', '서울특별시 중랑구 신내로7나길 24 ,209동 103호(상봉동, 건영2차아파트) (상봉제1동)', '02', '433', '3526', 25)
2021-08-18 17:41:02,100 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,101 INFO sqlalchemy.engine.base.Engine ('축복어린이집', '강영철', '서울특별시 노원구 마들로 31 ,,116동 103호(월계동 그랑빌아파트) (월계3동)', '02', '977', '1224', 9)
2021-08-18 17:41:02,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,105 INFO sqlalchemy.engine.base.Engine ('백호사랑어린이집', '서준서', '서울특별시 구로구 신도림로9길 20 (신도림동)', '02', '2677', '5910', 7)
2021-08-18 17:41:02,105 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,106 INFO sqlalchemy.engine.base.Engine ('옹달샘어린이집', '안혜진', '서울특별시 강동구 천호대로 1055 ,106동 102호(천호동, 태영아파트) (천호제3동)', '02', '476', '3950', 2)
2021-08-18 17:41:02,107 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,107 INFO sqlalchemy.engine.base.Engine ('베네베네어린이집', '전성호', '서울특별시 영등포구 당산로 95 ,현대아파트 106동 107호 (당산제1동)', '070', '7857', '8558', 20)
2021-08-18 17:41:02,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,109 INFO sqlalchemy.engine.base.Engine ('첼시어린이집', '강건우', '서울특별시 영등포구 당산동4가 당산로42길 16 ,502동 102호 (당산제2동)', '02', '6332', '2580', 20)
2021-08-18 17:41:02,109 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,110 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '송미경', '서울특별시 구로구 오류로 65 ,101동 101호(오류동, 경남아너스빌) (오류제2동)', '02', '2686', '4002', 7)
2021-08-18 17:41:02,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,115 INFO sqlalchemy.engine.base.Engine ('예쁜별꼬마숲어린이집', '안민서', '서울특별시 노원구 동일로227길 85 ,,1112동 108호(상계8동 주공아파트) (상계8동)', '02', '931', '3031', 9)
2021-08-18 17:41:02,116 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,117 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '강미경', '서울특별시 마포구 새창로 52 ,106-101(도화동, 도화동현대아파트) (도화동)', '02', '702', '3360', 13)
2021-08-18 17:41:02,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,119 INFO sqlalchemy.engine.base.Engine ('행복드림어린이집', '한지훈', '서울특별시 영등포구 문래로20길 14 ,문래공원한신아파트 2동 101호 (문래동)', '02', '3667', '7959', 20)
2021-08-18 17:41:02,120 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,121 INFO sqlalchemy.engine.base.Engine ('하하어린이집', '신상철', '서울특별시 노원구 동일로228길 23 ,,1409동 105호(상계동 주공아파트) (상계9동)', '02', '934', '3238', 9)
2021-08-18 17:41:02,122 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,122 INFO sqlalchemy.engine.base.Engine ('쌍용어린이집', '조성수', '서울특별시 영등포구 도영로7길 15 ,(도림동) (도림동)', '02', '3289', '7771', 20)
2021-08-18 17:41:02,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,124 INFO sqlalchemy.engine.base.Engine ('아림어린이집', '장현정', '서울특별시 노원구 마들로 127 ,, 33동 106호(월계동 삼호아파트) (월계3동)', '070', '8151', '7110', 9)
2021-08-18 17:41:02,126 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,127 INFO sqlalchemy.engine.base.Engine ('키즈꿈나무어린이집', '서현준', '서울특별시 영등포구 도림로143길 32 ,삼환아파트 102동 101호 (문래동)', '02', '6671', '9448', 20)
2021-08-18 17:41:02,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,129 INFO sqlalchemy.engine.base.Engine ('영풍키즈어린이집', '황영철', '서울특별시 마포구 토정로 198 ,영풍아파트 102-101 (신수동)', '02', '704', '0031', 13)
2021-08-18 17:41:02,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,131 INFO sqlalchemy.engine.base.Engine ('자곡나무어린이집', '이민지', '서울특별시 강남구 자곡로7길 8-18 (세곡동)', '02', '445', '0032', 1)
2021-08-18 17:41:02,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,133 INFO sqlalchemy.engine.base.Engine ('아기사랑 어린이집', '조성수', '서울특별시 강남구 도곡로18길 34 ,3동 103호(도곡현대아파트) (도곡1동)', '02', '571', '3022', 1)
2021-08-18 17:41:02,134 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,135 INFO sqlalchemy.engine.base.Engine ('꿈에그린어린이집', '이정운', '서울특별시 마포구 마포대로10길 22 ,한화꿈에그린아파트 101-104 (공덕동)', '02', '702', '0222', 13)
2021-08-18 17:41:02,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,136 INFO sqlalchemy.engine.base.Engine ('에듀온플레이어린이집', '김준영', '서울특별시 강서구 양천로67길 54 ,우성2차아파트 201-102 (염창동)', '02', '3665', '7990', 4)
2021-08-18 17:41:02,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,138 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '윤준호', '서울특별시 서초구 명달로20길 33 ,진흥골든빌라101호(서초동) (서초3동)', '02', '582', '0620', 15)
2021-08-18 17:41:02,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,141 INFO sqlalchemy.engine.base.Engine ('IBK 참!좋은 어린이집', '송민지', '서울특별시 용산구 한남대로 72 (한남동)', '02', '798', '3360', 21)
2021-08-18 17:41:02,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,143 INFO sqlalchemy.engine.base.Engine ('KDB어린이집', '김민재', '서울특별시 영등포구 은행로 14 ,한국산업은행 (여의동)', '02', '787', '4365', 20)
2021-08-18 17:41:02,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,145 INFO sqlalchemy.engine.base.Engine ('IBK 참 ! 좋은 어린이집', '한성수', '서울특별시 강남구 선릉로 332 (대치4동)', '02', '552', '2527', 1)
2021-08-18 17:41:02,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,149 INFO sqlalchemy.engine.base.Engine ('구립 구파발어린이집', '박민재', '서울특별시 은평구 북한산로 2 ,1022동 1층 (진관동)', '02', '387', '2910', 22)
2021-08-18 17:41:02,151 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,152 INFO sqlalchemy.engine.base.Engine ('우성어린이집', '신은경', '서울특별시 구로구 공원로6가길 67 ,2동 103호 (구로동, 구로우성아파트) (구로제5동)', '02', '837', '3330', 7)
2021-08-18 17:41:02,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,154 INFO sqlalchemy.engine.base.Engine ('사랑보듬어린이집', '서영숙', '서울특별시 노원구 동일로227길 86 ,1601동 103호(상계동 주공아파트) (상계8동)', '02', '934', '4142', 9)
2021-08-18 17:41:02,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,156 INFO sqlalchemy.engine.base.Engine ('한스어린이집', '송수빈', '서울특별시 강동구 고덕로24길 19-11 ,1층 (암사제1동)', '02', '442', '0708', 2)
2021-08-18 17:41:02,158 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,158 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '최지은', '서울특별시 강서구 허준로 23 ,한강타운 105동 101호 (가양제1동)', '02', '3662', '5153', 4)
2021-08-18 17:41:02,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,161 INFO sqlalchemy.engine.base.Engine ('우주아이어린이집', '박정웅', '서울특별시 노원구 동일로227길 85 ,1116동 105호(상계동, 상계주공11단지아파트) (상계8동)', '02', '6227', '0082', 9)
2021-08-18 17:41:02,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,163 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '서은영', '서울특별시 강남구 헌릉로590길 63 ,세곡5단지 리엔파크 관리동 (세곡동)', '02', '445', '2326', 1)
2021-08-18 17:41:02,164 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,165 INFO sqlalchemy.engine.base.Engine ('코스모스어린이집', '윤준영', '서울특별시 송파구 백제고분로37가길 20 ,코스모스어린이집 (석촌동)', '02', '423', '3232', 18)
2021-08-18 17:41:02,166 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,166 INFO sqlalchemy.engine.base.Engine ('포도나무 어린이집', '조정호', '서울특별시 강남구 광평로19길 15 ,목련타운 아파트 109동103호 (일원본동)', '02', '445', '9486', 1)
2021-08-18 17:41:02,168 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,169 INFO sqlalchemy.engine.base.Engine ('강남구청 직장어린이집', '윤준영', '서울특별시 강남구 학동로 426 (삼성2동)', '02', '2176', '0950', 1)
2021-08-18 17:41:02,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,171 INFO sqlalchemy.engine.base.Engine ('유엔빌리지어린이집', '신상철', '서울특별시 용산구 독서당로20길 9-5 (한남동)', '02', '792', '2677', 21)
2021-08-18 17:41:02,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,172 INFO sqlalchemy.engine.base.Engine ('튼튼어린이집', '송정자', '서울특별시 강동구 상암로 251 ,901동 102호(고덕주공아파트, 명일동) (명일제2동)', '02', '441', '5060', 2)
2021-08-18 17:41:02,173 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,174 INFO sqlalchemy.engine.base.Engine ('자연닮은꼬마숲어린이집', '안지원', '서울특별시 서초구 사임당로23길 58 ,301동 105호(서초동, 현대3차아파트) (서초1동)', '070', '8624', '7702', 15)
2021-08-18 17:41:02,175 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,177 INFO sqlalchemy.engine.base.Engine ('이화오뚜기어린이집', '윤영철', '서울특별시 서대문구 이화여대길 52 ,(지하1층, 지상1~3층) (신촌동)', '02', '3277', '6609', 14)
2021-08-18 17:41:02,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,179 INFO sqlalchemy.engine.base.Engine ('주영어린이집', '윤순자', '서울특별시 강서구 등촌로39길 42 (등촌제2동)', '02', '2654', '2081', 4)
2021-08-18 17:41:02,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,180 INFO sqlalchemy.engine.base.Engine ('아기동산어린이집', '정병철', '서울특별시 구로구 항동로 8 ,605동 101호(항동, 우남퍼스트빌) (항동)', '02', '2616', '0666', 7)
2021-08-18 17:41:02,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,182 INFO sqlalchemy.engine.base.Engine ('삼양제일어린이집', '김준호', '서울특별시 강북구 삼양로27길 35 ,삼양제일교회 (미아동) (삼각산동)', '02', '989', '5754', 3)
2021-08-18 17:41:02,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,184 INFO sqlalchemy.engine.base.Engine ('구립 응암어린이집', '강예은', '서울특별시 은평구 백련산로 10 (응암제2동)', '02', '302', '3758', 22)
2021-08-18 17:41:02,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,186 INFO sqlalchemy.engine.base.Engine ('농협중앙회어린이집', '송은정', '서울특별시 중구 새문안로 16 (소공동)', '02', '2080', '4941', 24)
2021-08-18 17:41:02,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,188 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '황정수', '서울특별시 서대문구 가재울로12길 36 ,1층(남가좌2동) (남가좌제2동)', '02', '306', '9131', 14)
2021-08-18 17:41:02,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,191 INFO sqlalchemy.engine.base.Engine ('오주어린이집', '신성수', '서울특별시 송파구 성내천로8가길 16-1 ,오주어린이집 (오금동)', '02', '400', '0594', 18)
2021-08-18 17:41:02,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,194 INFO sqlalchemy.engine.base.Engine ('지예슬어린이집', '장영일', '서울특별시 강남구 테헤란로25길 43 (역삼1동)', '02', '3453', '5638', 1)
2021-08-18 17:41:02,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,196 INFO sqlalchemy.engine.base.Engine ('한솔교육&CJ;키즈빌어린이집', '장은경', '서울특별시 마포구 월드컵북로 361 ,5층 (상암동)', '02', '6393', '0640', 13)
2021-08-18 17:41:02,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,199 INFO sqlalchemy.engine.base.Engine ('한울안어린이집', '권은정', '서울특별시 성북구 동소문로26길 32 (동선동)', '02', '924', '1259', 17)
2021-08-18 17:41:02,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,201 INFO sqlalchemy.engine.base.Engine ('보미나어린이집', '오현준', '서울특별시 강남구 학동로20길 25 (논현1동)', '02', '545', '0967', 1)
2021-08-18 17:41:02,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,202 INFO sqlalchemy.engine.base.Engine ('새날어린이집', '이정호', '서울특별시 성북구 종암로25길 29 (종암동)', '02', '953', '1700', 17)
2021-08-18 17:41:02,203 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,204 INFO sqlalchemy.engine.base.Engine ('서초구립신반포어린이집', '안종수', '서울특별시 서초구 신반포로19길 26 ,신반포중학교 내 복합관 (반포2동)', '02', '3477', '7741', 15)
2021-08-18 17:41:02,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,205 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '강수빈', '서울특별시 마포구 모래내로9길 30 ,건영월드컵아파트101-104 (성산제2동)', '02', '374', '2387', 13)
2021-08-18 17:41:02,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,207 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '전지영', '서울특별시 서초구 신반포로33길 15 ,108동 104호 (잠원동, 동아아파트) (반포3동)', '02', '536', '3567', 15)
2021-08-18 17:41:02,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,209 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '권정순', '서울특별시 서초구 서초대로28길 16 ,1층(방배동) (방배1동)', '02', '522', '2628', 15)
2021-08-18 17:41:02,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,213 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '최준서', '서울특별시 마포구 월드컵북로 260 ,시영아파트 31동 110호 (성산제2동)', '02', '307', '3252', 13)
2021-08-18 17:41:02,213 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,214 INFO sqlalchemy.engine.base.Engine ('세빛어린이집', '임지혜', '서울특별시 동대문구 망우로20길 86 ,104동 1층 (휘경동, 브라운스톤아파트) (휘경제2동)', '02', '3394', '5569', 11)
2021-08-18 17:41:02,215 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,216 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '조민서', '서울특별시 강동구 상암로 11 ,115동 102호(암사동,선사현대아파트) (암사제2동)', '02', '3426', '7942', 2)
2021-08-18 17:41:02,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,218 INFO sqlalchemy.engine.base.Engine ('마루별어린이집', '조미경', '서울특별시 송파구 마천로28길 3 ,1층 (오금동)', '02', '407', '8870', 18)
2021-08-18 17:41:02,219 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,220 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '송상훈', '서울특별시 강서구 양천로30길 77 ,103-101 (가양제1동)', '02', '3665', '8000', 4)
2021-08-18 17:41:02,220 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,222 INFO sqlalchemy.engine.base.Engine ('리틀포도나무어린이집', '임혜진', '서울특별시 중구 퇴계로90길 74 ,래미안하이베르아파트 관리동1층 (신당제5동)', '02', '2233', '3515', 24)
2021-08-18 17:41:02,223 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,224 INFO sqlalchemy.engine.base.Engine ('케이알엑스푸르니어린이집', '황종수', '서울특별시 영등포구 여의나루로 76 (여의동)', '02', '3774', '4495', 20)
2021-08-18 17:41:02,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,226 INFO sqlalchemy.engine.base.Engine ('산성몬테소리어린이집', '송은영', '서울특별시 서초구 사평대로 253 (반포1동)', '02', '536', '5893', 15)
2021-08-18 17:41:02,227 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,228 INFO sqlalchemy.engine.base.Engine ('생각이자라는어린이집', '서종수', '서울특별시 용산구 이촌로88길 15 ,왕궁아파트 2동 107호 (이촌제1동)', '02', '6352', '3030', 21)
2021-08-18 17:41:02,229 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,229 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '조건우', '서울특별시 양천구 목동동로 50 ,1225동 104호 (신정7동)', '02', '2652', '8819', 19)
2021-08-18 17:41:02,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,231 INFO sqlalchemy.engine.base.Engine ('캥거루어린이집', '오지은', '서울특별시 양천구 신정이펜1로 50 ,신정이펜하우스 306동 101호 (신정3동)', '02', '2603', '1159', 19)
2021-08-18 17:41:02,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,233 INFO sqlalchemy.engine.base.Engine ('한국수출입은행 꿈누리 어린이집', '김영진', '서울특별시 영등포구 은행로 38 (여의동)', '02', '6255', '5696', 20)
2021-08-18 17:41:02,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,235 INFO sqlalchemy.engine.base.Engine ('열린마음어린이집', '오준영', '서울특별시 송파구 성내천로37길 37 ,(마천동, 송파파크데일1단지관리동) (마천1동)', '02', '406', '8087', 18)
2021-08-18 17:41:02,236 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,237 INFO sqlalchemy.engine.base.Engine ('엘프랜드어린이집', '오준호', '서울특별시 송파구 오금로46길 66 ,1층 (가락2동)', '02', '443', '4011', 18)
2021-08-18 17:41:02,238 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,238 INFO sqlalchemy.engine.base.Engine ('구립해사랑어린이집', '오준영', '서울특별시 구로구 천왕로 91 ,천왕이펜하우스1단지 102동 1층 (오류제2동)', '02', '2614', '5008', 7)
2021-08-18 17:41:02,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,240 INFO sqlalchemy.engine.base.Engine ('해나래어린이집', '오은경', '서울특별시 구로구 천왕로 56 ,천왕이펜하우스3단지 306동 1층 (오류제2동)', '02', '2060', '5578', 7)
2021-08-18 17:41:02,241 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,241 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '신은영', '서울특별시 강북구 삼양로27길 80 ,303동 101호(미아동, 두산위브아파트) (삼각산동)', '02', '6317', '6314', 3)
2021-08-18 17:41:02,242 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,243 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '서영숙', '서울특별시 서초구 태봉로2길 65 ,네이처힐4단지 관리동 1층 (양재1동)', '02', '3461', '1400', 15)
2021-08-18 17:41:02,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,245 INFO sqlalchemy.engine.base.Engine ('상암햇살어린이집', '권건우', '서울특별시 마포구 성암로 330 (상암동)', '02', '305', '7722', 13)
2021-08-18 17:41:02,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,247 INFO sqlalchemy.engine.base.Engine ('잠실3동 주민센터 어린이집', '오영길', '서울특별시 송파구 석촌호수로 155 (잠실3동)', '02', '421', '8637', 18)
2021-08-18 17:41:02,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,251 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '신성호', '서울특별시 송파구 오금로36길 36 (가락본동)', '02', '3402', '0906', 18)
2021-08-18 17:41:02,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,253 INFO sqlalchemy.engine.base.Engine ('우리별어린이집', '박정남', '서울특별시 양천구 신정이펜1로 50 ,신정이펜하우스 303동 101호 (신정3동)', '02', '2694', '6161', 19)
2021-08-18 17:41:02,255 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,256 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '조종수', '서울특별시 강동구 천호옛길 30 ,101동 106호(성내동605, 파라디아아파트) (성내제1동)', '02', '6409', '7982', 2)
2021-08-18 17:41:02,259 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,260 INFO sqlalchemy.engine.base.Engine ('버클리 어린이집', '한미경', '서울특별시 강서구 강서로47바길 21 (발산제1동)', '02', '2663', '5955', 4)
2021-08-18 17:41:02,261 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,261 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '서지은', '서울특별시 용산구 이촌로 201 ,202동 101호(한가람아파트) (이촌제1동)', '02', '792', '4656', 21)
2021-08-18 17:41:02,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,263 INFO sqlalchemy.engine.base.Engine ('마리오아울렛어린이집', '황성호', '서울특별시 금천구 디지털로9길 23 (가산동)', '02', '2109', '7285', 8)
2021-08-18 17:41:02,264 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,264 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '권경숙', '서울특별시 성동구 고산자로 160 ,대림강변아파트 112-101 (응봉동)', '02', '6219', '0536', 16)
2021-08-18 17:41:02,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,265 INFO sqlalchemy.engine.base.Engine ('산울림어린이집', '박건우', '서울특별시 마포구 월드컵북로 233 ,32동108호 (성산제2동)', '070', '4257', '7920', 13)
2021-08-18 17:41:02,266 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,267 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '전유진', '서울특별시 동작구 동작대로35길 22 (사당제2동)', '02', '592', '0660', 12)
2021-08-18 17:41:02,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,269 INFO sqlalchemy.engine.base.Engine ('이호어린이집', '최정웅', '서울특별시 강동구 풍성로38길 14 ,(성내동 296-1 ) (성내제1동)', '02', '477', '2555', 2)
2021-08-18 17:41:02,270 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,271 INFO sqlalchemy.engine.base.Engine ('지혜샘어린이집', '안영진', '서울특별시 동작구 사당로17길 52 ,2동102호(사당동,대림아파트) (사당제3동)', '02', '532', '6681', 12)
2021-08-18 17:41:02,272 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,273 INFO sqlalchemy.engine.base.Engine ('홀츠앤키즈어린이집', '오도현', '서울특별시 동대문구 전농로16길 51 ,관리동 (전농제2동)', '02', '3394', '7206', 11)
2021-08-18 17:41:02,274 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,275 INFO sqlalchemy.engine.base.Engine ('별초롱어린이집', '신민석', '서울특별시 강동구 성내로12길 9-12 ,(성내동 564) (성내제1동)', '02', '485', '3694', 2)
2021-08-18 17:41:02,276 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,277 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '오건우', '서울특별시 동작구 사당로17길 52 ,169-8번지 대림아파트 13동 107호 (사당제3동)', '02', '6334', '2001', 12)
2021-08-18 17:41:02,278 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,279 INFO sqlalchemy.engine.base.Engine ('키즈열매어린이집', '최은영', '서울특별시 서초구 태봉로2길 10 ,702동 102호(우면동, 네이처힐) (양재1동)', '070', '8987', '0666', 15)
2021-08-18 17:41:02,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,280 INFO sqlalchemy.engine.base.Engine ('밀알몬테소리어린이집', '이영식', '서울특별시 강서구 공항대로59길 82 (등촌제1동)', '02', '2658', '9960', 4)
2021-08-18 17:41:02,281 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,282 INFO sqlalchemy.engine.base.Engine ('우아세어린이집', '임준서', '서울특별시 동대문구 답십리로48길 38 ,답십리2동 (답십리2동)', '02', '2216', '3355', 11)
2021-08-18 17:41:02,283 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,284 INFO sqlalchemy.engine.base.Engine ('하랑어린이집', '서성호', '서울특별시 동작구 여의대방로44길 9 ,성원아파트 101동 105호 (대방동)', '02', '823', '5335', 12)
2021-08-18 17:41:02,286 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,286 INFO sqlalchemy.engine.base.Engine ('두산어린이집', '이성호', '서울특별시 동작구 상도로30길 39 ,102-101 (상도제2동)', '02', '822', '0023', 12)
2021-08-18 17:41:02,288 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,289 INFO sqlalchemy.engine.base.Engine ('엔젤스타 어린이집', '김현정', '서울특별시 강남구 헌릉로590길 63 ,512동 102호(세곡동, 강남데시앙파크) (세곡동)', '02', '2226', '2700', 1)
2021-08-18 17:41:02,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,292 INFO sqlalchemy.engine.base.Engine ('서초구립반포서래어린이집', '오경회', '서울특별시 서초구 사평대로28길 70 (반포4동)', '02', '599', '1320', 15)
2021-08-18 17:41:02,294 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,294 INFO sqlalchemy.engine.base.Engine ('우리마포어린이집', '신정호', '서울특별시 마포구 신촌로26길 10 (대흥동)', '02', '702', '3100', 13)
2021-08-18 17:41:02,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,296 INFO sqlalchemy.engine.base.Engine ('다해키즈어린이집', '오지훈', '서울특별시 송파구 잠실로 62 ,313동 104호(잠실동, 트리지움) (잠실3동)', '02', '2203', '0332', 18)
2021-08-18 17:41:02,297 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,298 INFO sqlalchemy.engine.base.Engine ('서초2삼성어린이집', '강성수', '서울특별시 서초구 서초대로74길 4 ,삼성생명 서초타워 3층 (서초2동)', '02', '2055', '3481', 15)
2021-08-18 17:41:02,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,300 INFO sqlalchemy.engine.base.Engine ('해나라어린이집', '윤준서', '서울특별시 동작구 만양로13길 44 ,태영아트빌 1층 (노량진제1동)', '02', '6269', '8478', 12)
2021-08-18 17:41:02,301 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,302 INFO sqlalchemy.engine.base.Engine ('구립 새빛어린이집', '안진호', '서울특별시 양천구 신정이펜1로 51 ,신정이펜하우스 4단지 어린이집 (신정3동)', '02', '2601', '6658', 19)
2021-08-18 17:41:02,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,303 INFO sqlalchemy.engine.base.Engine ('구립 한누리어린이집', '오정호', '서울특별시 양천구 신정이펜1로 99 ,신정이펜하우스 1단지 보육시설 (신정3동)', '02', '2604', '2525', 19)
2021-08-18 17:41:02,304 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,305 INFO sqlalchemy.engine.base.Engine ('타요타요어린이집', '서성진', '서울특별시 용산구 이촌로 100-8 ,동아그린아파트 103동102호 (이촌제2동)', '02', '711', '1105', 21)
2021-08-18 17:41:02,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,307 INFO sqlalchemy.engine.base.Engine ('꼬마성어린이집', '박지영', '서울특별시 용산구 장문로6길 76 ,1단지 1-3 (동빙고동,용산푸르지오파크타운) (서빙고동)', '02', '794', '2796', 21)
2021-08-18 17:41:02,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,309 INFO sqlalchemy.engine.base.Engine ('구립 행당푸르지오어린이집', '신종수', '서울특별시 성동구 고산자로 177 (행당제2동)', '02', '2295', '1220', 16)
2021-08-18 17:41:02,311 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,311 INFO sqlalchemy.engine.base.Engine ('아이비어린이집', '김영환', '서울특별시 송파구 올림픽로 99 ,115-102 (잠실2동)', '02', '421', '6234', 18)
2021-08-18 17:41:02,312 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,313 INFO sqlalchemy.engine.base.Engine ('구립꿈사랑어린이집', '류예은', '서울특별시 강동구 구천면로 304 ,(천호동 234-6) (천호제1동)', '02', '488', '7884', 2)
2021-08-18 17:41:02,314 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,315 INFO sqlalchemy.engine.base.Engine ('두산위브어린이집', '이영철', '서울특별시 동작구 사당로13길 31 ,관리동 1층 (사당제3동)', '02', '536', '0066', 12)
2021-08-18 17:41:02,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,317 INFO sqlalchemy.engine.base.Engine ('리틀스텝어린이집', '신준호', '서울특별시 동작구 상도로34길 36-13 (상도제2동)', '02', '816', '1486', 12)
2021-08-18 17:41:02,318 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,319 INFO sqlalchemy.engine.base.Engine ('힐스테이트사임당어린이집', '황영진', '서울특별시 금천구 시흥대로 165 ,남서울힐스테이트106-104 (시흥제1동)', '02', '6465', '9700', 8)
2021-08-18 17:41:02,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,320 INFO sqlalchemy.engine.base.Engine ('예다미어린이집', '윤건우', '서울특별시 강동구 구천면로68나길 21-4 ,(천호동 29-3 ) (천호제1동)', '02', '471', '3379', 2)
2021-08-18 17:41:02,321 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,322 INFO sqlalchemy.engine.base.Engine ('성균관어린이집', '오수빈', '서울특별시 마포구 월드컵로23길 32-3 ,101호(망원동, 망원동다세대주택) (망원제1동)', '02', '326', '1212', 13)
2021-08-18 17:41:02,323 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,324 INFO sqlalchemy.engine.base.Engine ('아이미소어린이집', '임건우', '서울특별시 양천구 목동동로 50 ,목동신시가지아파트 1202동 104호 (신정7동)', '02', '395', '9923', 19)
2021-08-18 17:41:02,325 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,326 INFO sqlalchemy.engine.base.Engine ('대웅 리틀베어 어린이집', '전순자', '서울특별시 강남구 봉은사로114길 12 (삼성1동)', '02', '550', '8885', 1)
2021-08-18 17:41:02,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,328 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '서지영', '서울특별시 용산구 원효로 216 ,신계동49 이편한테마트 1층 101호 (원효로제1동)', '02', '711', '6401', 21)
2021-08-18 17:41:02,329 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,329 INFO sqlalchemy.engine.base.Engine ('하랑어린이집', '신영길', '서울특별시 용산구 장문로 27 ,청화아파트 3동 103호 (이태원제1동)', '02', '797', '3103', 21)
2021-08-18 17:41:02,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,331 INFO sqlalchemy.engine.base.Engine ('상도아이파크어린이집', '신예준', '서울특별시 동작구 장승배기로 26 ,아이파크상도아파트 101-101 (상도제2동)', '02', '815', '6101', 12)
2021-08-18 17:41:02,332 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,333 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '전유진', '서울특별시 동작구 장승배기로4길 9 ,포스코더샵 아파트 122-101 (상도제2동)', '02', '982', '6173', 12)
2021-08-18 17:41:02,335 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,335 INFO sqlalchemy.engine.base.Engine ('해가빛어린이집', '류서현', '서울특별시 구로구 천왕로 9 ,602동102호(천왕동, 천왕이펜하우스6단지) (오류제2동)', '02', '2619', '2279', 7)
2021-08-18 17:41:02,337 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,338 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '이예은', '서울특별시 은평구 통일로 796 ,북한산힐스테이트7차 101동 101호 (불광제1동)', '02', '387', '0040', 22)
2021-08-18 17:41:02,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,355 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '조정수', '서울특별시 구로구 항동로 43 ,308동 106호 (항동, 항동하버라인3단지) (항동)', '02', '2611', '1911', 7)
2021-08-18 17:41:02,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,357 INFO sqlalchemy.engine.base.Engine ('꽃별아이어린이집', '정상훈', '서울특별시 구로구 경인로8길 64 ,107동 103호(오류동, 영풍마드레빌아파트) (오류제2동)', '02', '6086', '1235', 7)
2021-08-18 17:41:02,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,360 INFO sqlalchemy.engine.base.Engine ('구립 넓은들어린이집', '임민지', '서울특별시 양천구 신정이펜1로 50 ,신정이펜하우스 3단지 보육시설 (신정3동)', '02', '2699', '7967', 19)
2021-08-18 17:41:02,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,362 INFO sqlalchemy.engine.base.Engine ('아기별어린이집', '오영길', '서울특별시 양천구 중앙로29길 96 ,1층 (신정3동)', '02', '2699', '3003', 19)
2021-08-18 17:41:02,364 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,364 INFO sqlalchemy.engine.base.Engine ('푸른솔몬테소리어린이집', '권지은', '서울특별시 중랑구 봉화산로22길 14 (중화제1동)', '02', '963', '5004', 25)
2021-08-18 17:41:02,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,367 INFO sqlalchemy.engine.base.Engine ('좋은열매어린이집', '이지은', '서울특별시 구로구 부일로9길 127 ,(온수힐스테이트아파트115-106 / 온수동 155) (수궁동)', '02', '2685', '0419', 7)
2021-08-18 17:41:02,368 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,369 INFO sqlalchemy.engine.base.Engine ('금융투자협회푸르니어린이집', '이영자', '서울특별시 영등포구 여의나루로 67-8 (여의동)', '02', '780', '7789', 20)
2021-08-18 17:41:02,370 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,371 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '오종수', '서울특별시 금천구 시흥대로 165 ,남서울힐스테이트 204동 101호(시흥동) (시흥제1동)', '02', '806', '1002', 8)
2021-08-18 17:41:02,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,373 INFO sqlalchemy.engine.base.Engine ('거여꼬마숲어린이집', '정준호', '서울특별시 송파구 오금로61길 20 ,203동 106호(거여동, 현대2차아파트) (거여2동)', '02', '400', '1707', 18)
2021-08-18 17:41:02,374 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,375 INFO sqlalchemy.engine.base.Engine ('성덕어린이집', '한준혁', '서울특별시 동작구 등용로 27 ,(상도동) (상도제2동)', '02', '812', '6127', 12)
2021-08-18 17:41:02,376 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,377 INFO sqlalchemy.engine.base.Engine ('한양키움 어린이집', '오민지', '서울특별시 성동구 마장로39길 48 ,(마장동) (마장동)', '02', '2293', '0195', 16)
2021-08-18 17:41:02,378 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,379 INFO sqlalchemy.engine.base.Engine ('로뎀나무어린이집', '한영진', '서울특별시 동작구 동작대로29길 91 ,201동 108호(사당동, 사당우성아파트) (사당제2동)', '02', '6747', '7803', 12)
2021-08-18 17:41:02,380 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,381 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '오정운', '서울특별시 서초구 서초대로23길 85 (방배4동)', '02', '594', '8291', 15)
2021-08-18 17:41:02,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,383 INFO sqlalchemy.engine.base.Engine ('구립 동아어린이집', '윤정순', '서울특별시 성동구 고산자로2길 13 ,구립동아어린이집 (응봉동)', '02', '2294', '1230', 16)
2021-08-18 17:41:02,384 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,385 INFO sqlalchemy.engine.base.Engine ('아이드림어린이집', '정지원', '서울특별시 양천구 신정이펜2로 55 ,203동 101호 (신정3동)', '02', '2699', '7779', 19)
2021-08-18 17:41:02,386 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,386 INFO sqlalchemy.engine.base.Engine ('조이조이어린이집', '윤정운', '서울특별시 양천구 신정이펜2로 55 ,203동 103호 (신정3동, 신정이펜하우스) (신정3동)', '02', '2606', '4475', 19)
2021-08-18 17:41:02,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,388 INFO sqlalchemy.engine.base.Engine ('해누리어린이집', '한준영', '서울특별시 구로구 천왕로 92 ,천왕이펜하우스2단지 203동 1층 (오류제2동)', '02', '2689', '5004', 7)
2021-08-18 17:41:02,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,390 INFO sqlalchemy.engine.base.Engine ('해돋이어린이집', '류종수', '서울특별시 구로구 천왕로 29 ,천왕이펜하우스4단지 408동 1충 (오류제2동)', '02', '2682', '8080', 7)
2021-08-18 17:41:02,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,392 INFO sqlalchemy.engine.base.Engine ('해뜨락어린이집', '강영철', '서울특별시 구로구 천왕로 9 ,천왕이펜하우스6단지 605동 1층 (오류제2동)', '02', '2682', '2121', 7)
2021-08-18 17:41:02,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,394 INFO sqlalchemy.engine.base.Engine ('해랑어린이집', '김지은', '서울특별시 구로구 천왕로 10 ,천왕이펜하우스 5단지 505동 1층 (오류제2동)', '02', '2687', '2277', 7)
2021-08-18 17:41:02,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,396 INFO sqlalchemy.engine.base.Engine ('성내장미어린이집', '황정자', '서울특별시 강동구 풍성로45길 39 ,(성내2동 504-9) (성내제2동)', '02', '3411', '9290', 2)
2021-08-18 17:41:02,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,398 INFO sqlalchemy.engine.base.Engine ('한신리틀어린이집', '전지혜', '서울특별시 강동구 구천면로42길 16 ,1동 104호(천호동, 한신아파트) (천호제1동)', '02', '476', '5345', 2)
2021-08-18 17:41:02,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,400 INFO sqlalchemy.engine.base.Engine ('중앙대학교의료원 어린이집', '전종수', '서울특별시 동작구 흑석한강로 27 ,(흑석동 336) 흑석한강푸르지오 상가D동 B102 (흑석동)', '02', '6332', '0998', 12)

2021-08-18 17:41:02,401 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,402 INFO sqlalchemy.engine.base.Engine ('혜원어린이집', '김미영', '서울특별시 송파구 거마로20길 8 ,(마천동) (마천2동)', '02', '402', '3927', 18)
2021-08-18 17:41:02,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,406 INFO sqlalchemy.engine.base.Engine ('세나어린이집', '신상철', '서울특별시 서대문구 증가로 197-18 (북가좌제2동)', '02', '376', '7600', 14)
2021-08-18 17:41:02,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,408 INFO sqlalchemy.engine.base.Engine ('꿈이열리는어린이집', '박정호', '서울특별시 은평구 증산로 285 ,101동 106호(증산동, 증산중앙하이츠) (증산동)', '02', '375', '0079', 22)
2021-08-18 17:41:02,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,411 INFO sqlalchemy.engine.base.Engine ('LG전자구로어린이집', '김현정', '서울특별시 구로구 가마산로 95 (구로제1동)', '02', '868', '1410', 7)
2021-08-18 17:41:02,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,413 INFO sqlalchemy.engine.base.Engine ('해사랑어린이집', '한영일', '서울특별시 동작구 흑석한강로 12 ,흑석동, 한강센트레빌 관리동 (흑석동)', '02', '812', '9464', 12)
2021-08-18 17:41:02,414 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,414 INFO sqlalchemy.engine.base.Engine ('꿈이룸어린이집', '서지훈', '서울특별시 동작구 상도로34길 42 ,동원 베네스트 (상도제2동)', '02', '873', '3387', 12)
2021-08-18 17:41:02,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,416 INFO sqlalchemy.engine.base.Engine ('삼성영재어린이집', '전지훈', '서울특별시 동대문구 전농로 192 ,삼성아파트 단지내 (전농동) (전농제2동)', '02', '2212', '1212', 11)
2021-08-18 17:41:02,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,418 INFO sqlalchemy.engine.base.Engine ('상계5동보듬이나눔이어린이집', '조영진', '서울특별시 노원구 한글비석로39길 16-5 (상계5동)', '02', '932', '1077', 9)
2021-08-18 17:41:02,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,419 INFO sqlalchemy.engine.base.Engine ('솔바람어린이집', '안종수', '서울특별시 송파구 풍성로20길 3 ,(풍납동) (풍납2동)', '02', '477', '1652', 18)
2021-08-18 17:41:02,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,422 INFO sqlalchemy.engine.base.Engine ('앙팡어린이집', '서혜진', '서울특별시 동대문구 홍릉로10길 18 ,(청량리동) (청량리동)', '02', '969', '5141', 11)
2021-08-18 17:41:02,423 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,424 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '전종수', '서울특별시 동작구 동작대로29길 119 ,102동 110호(사당동, 극동) (사당제2동)', '02', '6414', '2334', 12)
2021-08-18 17:41:02,425 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,426 INFO sqlalchemy.engine.base.Engine ('하나어린이집', '오정호', '서울특별시 송파구 송파대로32길 8 ,5동 103호(가락동, 가락우성아파트) (가락본동)', '02', '401', '7279', 18)
2021-08-18 17:41:02,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,428 INFO sqlalchemy.engine.base.Engine ('예쁜어린이집', '류민재', '서울특별시 서초구 서초중앙로29길 16-8 ,A동 102호(반포동, 대림빌라) (반포4동)', '02', '596', '6466', 15)
2021-08-18 17:41:02,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,430 INFO sqlalchemy.engine.base.Engine ('홀츠앤키즈맑은샘어린이집', '한정식', '서울특별시 은평구 불광로 122-10 ,북한산힐스테이트 3차 관리동 (불광동) (불광제1동)', '02', '386', '1110', 22)
2021-08-18 17:41:02,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,431 INFO sqlalchemy.engine.base.Engine ('구립 큰솔어린이집', '조준호', '서울특별시 양천구 신정이펜2로 55 ,신정이펜하우스 2단지 보육시설 (신정3동)', '02', '2602', '7061', 19)
2021-08-18 17:41:02,433 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,434 INFO sqlalchemy.engine.base.Engine ('청화어린이집', '황준호', '서울특별시 용산구 보광로 14 ,A동 108호(보광동, 신동아1차아파트) (보광동)', '02', '3785', '1684', 21)
2021-08-18 17:41:02,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,436 INFO sqlalchemy.engine.base.Engine ('고운숲어린이집', '장지영', '서울특별시 은평구 진관2로 57-37 ,우물골아파트240동1층 (진관동)', '02', '386', '8880', 22)
2021-08-18 17:41:02,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,439 INFO sqlalchemy.engine.base.Engine ('키즈맘어린이집', '서지원', '서울특별시 동작구 알마타길 28 ,(대방동) (대방동)', '02', '824', '0377', 12)
2021-08-18 17:41:02,440 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,440 INFO sqlalchemy.engine.base.Engine ('새하늘어린이집', '박경숙', '서울특별시 동대문구 왕산로 312 ,제칠안식일예수재림교 본부교회 (휘경제1동)', '02', '967', '0006', 11)
2021-08-18 17:41:02,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,443 INFO sqlalchemy.engine.base.Engine ('대림꼬마숲어린이집', '류혜진', '서울특별시 성동구 행당로 75 ,112동 104호(행당동, 대림이편한세상아파트) (행당제2동)', '02', '2298', '0707', 16)
2021-08-18 17:41:02,444 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,445 INFO sqlalchemy.engine.base.Engine ('자람어린이집', '김정순', '서울특별시 동작구 사당로16길 96 ,102동 101호(사당동, 사당휴먼시아) (사당제4동)', '02', '525', '9151', 12)
2021-08-18 17:41:02,446 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,447 INFO sqlalchemy.engine.base.Engine ('서울의료원어린이집', '정성호', '서울특별시 중랑구 신내로 156 ,(신내동) (신내1동)', '02', '2276', '7601', 25)
2021-08-18 17:41:02,448 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,449 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '장영환', '서울특별시 양천구 신정이펜1로 50 ,이펜하우스 3단지 302동 102호 (신정3동) (신정3동)', '02', '6489', '3003', 19)
2021-08-18 17:41:02,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,451 INFO sqlalchemy.engine.base.Engine ('팬더어린이집', '황지은', '서울특별시 양천구 목동서로 340 ,923동 105호(신정동, 신시가지9단지아파트) (신정1동)', '02', '2646', '2838', 19)
2021-08-18 17:41:02,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,453 INFO sqlalchemy.engine.base.Engine ('서울대학교어린이보육지원센터 느티나무어린이집', '오지훈', '서울특별시 관악구 관악로 1 ,(봉천동) [낙성대동] (낙성대동)', '02', '880', '5798', 5)

2021-08-18 17:41:02,454 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,455 INFO sqlalchemy.engine.base.Engine ('사랑숲어린이집', '한민재', '서울특별시 송파구 중대로20길 8 ,1F (가락2동)', '02', '3012', '7177', 18)
2021-08-18 17:41:02,457 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,458 INFO sqlalchemy.engine.base.Engine ('열린세상어린이집', '장민재', '서울특별시 영등포구 선유로33길 22 ,101동 106호(양평동3가, 양평경남아파트) (양평제1동)', '02', '2672', '9333', 20)
2021-08-18 17:41:02,460 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,460 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '윤지훈', '서울특별시 송파구 송파대로 567 ,515동 103호(잠실동, 주공아파트) (잠실3동)', '02', '416', '0650', 18)
2021-08-18 17:41:02,462 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,463 INFO sqlalchemy.engine.base.Engine ('디즈니 어린이집', '정정수', '서울특별시 성동구 독서당로 377 ,107동 102호(응봉동, 금호현대) (응봉동)', '02', '6212', '5353', 16)
2021-08-18 17:41:02,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,465 INFO sqlalchemy.engine.base.Engine ('서초아이자람어린이집', '황정호', '서울특별시 서초구 사임당로20길 48-4 (서초1동)', '02', '586', '1486', 15)
2021-08-18 17:41:02,466 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,467 INFO sqlalchemy.engine.base.Engine ('구립아이뜰어린이집', '전지영', '서울특별시 금천구 벚꽃로 234 ,에이스하이엔드6차 (가산동) 102,103,104,105,109-1호 (가산동)', '02', '802', '8803', 8)
2021-08-18 17:41:02,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,469 INFO sqlalchemy.engine.base.Engine ('서빙고어린이집', '신정웅', '서울특별시 용산구 녹사평대로 66 ,대우푸르지오파크타운 208동앞 (서빙고동)', '02', '749', '6937', 21)
2021-08-18 17:41:02,473 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,474 INFO sqlalchemy.engine.base.Engine ('누리꿈어린이집', '윤종수', '서울특별시 마포구 백범로 205 ,펜트라우스 104동 1층 (공덕동)', '02', '3275', '1123', 13)
2021-08-18 17:41:02,475 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,476 INFO sqlalchemy.engine.base.Engine ('성원아이뽀어린이집', '정은정', '서울특별시 마포구 독막로28길 7 ,101동 104호(신수동, 신수동성원아파트) (신수동)', '02', '711', '0125', 13)
2021-08-18 17:41:02,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,479 INFO sqlalchemy.engine.base.Engine ('새별어린이집', '최상철', '서울특별시 마포구 희우정로 60-8 ,1층 (합정동) (합정동)', '02', '322', '3208', 13)
2021-08-18 17:41:02,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,481 INFO sqlalchemy.engine.base.Engine ('리틀프린스어린이집', '오정수', '서울특별시 강동구 아리수로93길 40 ,313동 104호(강일동674, 강일리버파크3단지아파트) (강일동)', '02', '481', '1114', 2)
2021-08-18 17:41:02,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,483 INFO sqlalchemy.engine.base.Engine ('아이즐어린이집', '류정식', '서울특별시 강동구 아리수로97길 68 ,208동 101호(강일동668, 강일리버파크2단지아파트) (강일동)', '02', '429', '8777', 2)
2021-08-18 17:41:02,484 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,485 INFO sqlalchemy.engine.base.Engine ('초코렛어린이집', '오영일', '서울특별시 구로구 신도림로 87 ,110동 102호(신도림동, 동아1차아파트) (신도림동)', '02', '2637', '3653', 7)
2021-08-18 17:41:02,486 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,487 INFO sqlalchemy.engine.base.Engine ('롯데예닮어린이집', '장예준', '서울특별시 강동구 상암로 11 ,112동 101호(암사동, 선사현대아파트) (암사제2동)', '02', '3428', '0303', 2)
2021-08-18 17:41:02,488 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,489 INFO sqlalchemy.engine.base.Engine ('성내삼성어린이집', '장상철', '서울특별시 강동구 풍성로 128 ,205동 105호(성내동590, 성내동삼성아파트) (성내제1동)', '02', '486', '3382', 2)
2021-08-18 17:41:02,490 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,490 INFO sqlalchemy.engine.base.Engine ('킨더트리 어린이집', '조경숙', '서울특별시 성북구 종암로24가길 80 ,래미안라센트아파트 관리동 (종암동) (종암동)', '070', '4416', '2722', 17)
2021-08-18 17:41:02,492 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,494 INFO sqlalchemy.engine.base.Engine ('CJ키즈빌 어린이집', '오수빈', '서울특별시 중구 동호로 330 ,(쌍림동) (광희동)', '02', '722', '1070', 24)
2021-08-18 17:41:02,495 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,496 INFO sqlalchemy.engine.base.Engine ('그레이튼어린이집', '신성진', '서울특별시 강남구 도곡로43길 20 ,래미안그레이튼2단지 관리동 (역삼제2동)', '02', '561', '2205', 1)
2021-08-18 17:41:02,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,497 INFO sqlalchemy.engine.base.Engine ('키즈랜드어린이집', '강준서', '서울특별시 강남구 헌릉로590길 100 ,리엔파크 1단지 관리동 내 키즈랜드어린이집 (세곡동)', '02', '451', '5233', 1)
2021-08-18 17:41:02,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,499 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '류성민', '서울특별시 서초구 방배로 16 ,7동 101호(방배동, 임광아파트) (방배3동)', '02', '587', '2312', 15)
2021-08-18 17:41:02,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,500 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '류지원', '서울특별시 구로구 구일로4길 65 ,105동 106호(구로동, 주공아파트) (구로제1동)', '02', '6347', '0198', 7)
2021-08-18 17:41:02,501 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,502 INFO sqlalchemy.engine.base.Engine ('은아어린이집', '송지훈', '서울특별시 영등포구 선유서로 40 ,101동 101호(문래동6가, 베어스타운아파트) (문래동)', '02', '6166', '3072', 20)
2021-08-18 17:41:02,503 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,504 INFO sqlalchemy.engine.base.Engine ('좋은친구어린이집', '권영자', '서울특별시 강동구 상암로4가길 24 ,(암사동) (암사제2동)', '02', '481', '4584', 2)
2021-08-18 17:41:02,505 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,506 INFO sqlalchemy.engine.base.Engine ('해피i어린이집', '임상훈', '서울특별시 광진구 아차산로36길 35 ,702-105(자양동,우성7차아파트 ) (자양제3동)', '02', '454', '1565', 6)
2021-08-18 17:41:02,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,507 INFO sqlalchemy.engine.base.Engine ('산오름어린이집', '윤은정', '서울특별시 강동구 아리수로94길 19 ,604동 104호(강일동, 강일리버파크6단지아파트) (강일동)', '02', '428', '3253', 2)
2021-08-18 17:41:02,509 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,510 INFO sqlalchemy.engine.base.Engine ('예꿈어린이집', '윤광수', '서울특별시 송파구 오금로64나길 9 (거여2동)', '02', '408', '3767', 18)
2021-08-18 17:41:02,511 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,512 INFO sqlalchemy.engine.base.Engine ('꼬꼬맘 어린이집', '박민지', '서울특별시 강남구 논현로4길 41 ,(개포동) (개포제4동)', '02', '501', '2020', 1)
2021-08-18 17:41:02,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,513 INFO sqlalchemy.engine.base.Engine ('햇님나라어린이집', '장혜진', '서울특별시 은평구 진관2로 111-7 ,은평뉴타운우물골아파트 218동 관리동 1층 (진관동) (진관동)', '02', '358', '1005', 22)
2021-08-18 17:41:02,514 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,515 INFO sqlalchemy.engine.base.Engine ('예손유앤아이어린이집', '전영일', '서울특별시 구로구 가마산로 87 ,105동 102호(구로동, 한일유앤아파트) (구로제1동)', '02', '2060', '3497', 7)
2021-08-18 17:41:02,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,517 INFO sqlalchemy.engine.base.Engine ('둥지어린이집', '황예준', '서울특별시 성동구 행당로 79 ,131동 102호(행당동, 행당대림아파트) (행당제2동)', '02', '6464', '9595', 16)
2021-08-18 17:41:02,517 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,519 INFO sqlalchemy.engine.base.Engine ('이우어린이집', '신지영', '서울특별시 송파구 성내천로47길 38 ,207동 101호(마천동, 파크데일아파트) (마천1동)', '02', '400', '5059', 18)
2021-08-18 17:41:02,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,521 INFO sqlalchemy.engine.base.Engine ('뽀로로와친구들 어린이집', '조준호', '서울특별시 강서구 초록마을로16길 24 ,(화곡동) (화곡본동)', '02', '2694', '2023', 4)
2021-08-18 17:41:02,522 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,524 INFO sqlalchemy.engine.base.Engine ('참사랑어린이집', '이지훈', '서울특별시 양천구 목동중앙본로26길 23 ,온세빌라 101호 (목동) (목2동)', '02', '2646', '3321', 19)
2021-08-18 17:41:02,525 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,526 INFO sqlalchemy.engine.base.Engine ('아이네오어린이집', '정정순', '서울특별시 영등포구 당산동3가 당산로31길 32 (당산제1동)', '070', '4327', '0802', 20)
2021-08-18 17:41:02,529 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,530 INFO sqlalchemy.engine.base.Engine ('디딤돌굿맘어린이집', '정정수', '서울특별시 강동구 상일로 74 ,324동 101호(상일동490, 고덕리엔파크) (상일제2동)', '02', '442', '7727', 2)
2021-08-18 17:41:02,531 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,531 INFO sqlalchemy.engine.base.Engine ('이레몬테소리어린이집', '이정호', '서울특별시 구로구 구일로8길 92 ,1동 102호(구로동, 중앙하이츠아파트) (구로제1동)', '02', '6347', '1223', 7)
2021-08-18 17:41:02,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,533 INFO sqlalchemy.engine.base.Engine ('해다미어린이집', '이성진', '서울특별시 구로구 천왕로 91 ,105동T101호(천왕동, 천왕이펜하우스 1단지) (오류제2동)', '02', '6339', '0009', 7)
2021-08-18 17:41:02,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,535 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '황영숙', '서울특별시 중구 동호로14길 11-8 ,B동 102호(신당동, 뉴타운빌) (다산동)', '02', '2236', '4558', 24)
2021-08-18 17:41:02,536 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,537 INFO sqlalchemy.engine.base.Engine ('아가랑어린이집', '한정순', '서울특별시 송파구 송이로23길 22-20 ,101호 (가락2동)', '02', '3012', '9711', 18)
2021-08-18 17:41:02,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,538 INFO sqlalchemy.engine.base.Engine ('아띠어린이집', '강예준', '서울특별시 강서구 까치산로4다길 20 ,(화곡동) (화곡본동)', '02', '2601', '1608', 4)
2021-08-18 17:41:02,539 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,540 INFO sqlalchemy.engine.base.Engine ('꿈땅어린이집', '최정호', '서울특별시 송파구 성내천로37길 37 ,110동 103호(마천동, 송파파크데일1단지) (마천1동)', '02', '6338', '7900', 18)
2021-08-18 17:41:02,541 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,541 INFO sqlalchemy.engine.base.Engine ('라온몬테소리어린이집', '이병철', '서울특별시 송파구 백제고분로28길 26 ,(삼전동) (삼전동)', '02', '417', '7942', 18)
2021-08-18 17:41:02,542 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,543 INFO sqlalchemy.engine.base.Engine ('아이재미어린이집', '황정남', '서울특별시 강동구 고덕로80길 99 ,511동 104호 (고덕센트럴아이파크) (상일제1동)', '070', '4197', '0464', 2)
2021-08-18 17:41:02,544 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,545 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '윤병철', '서울특별시 강동구 고덕로 210 ,503동 105호(명일동, 삼익그린2차) (명일제1동)', '02', '427', '8898', 2)
2021-08-18 17:41:02,546 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,546 INFO sqlalchemy.engine.base.Engine ('홀츠앤키즈어린이집', '조정호', '서울특별시 송파구 충민로 188 ,송파파인타운1단지 관리동 (장지동)', '02', '448', '7991', 18)
2021-08-18 17:41:02,548 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,549 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '송준영', '서울특별시 강동구 진황도로31길 26 ,(천호동 564 성원아파트) (천호제3동)', '02', '427', '0888', 2)
2021-08-18 17:41:02,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,553 INFO sqlalchemy.engine.base.Engine ('휴사랑어린이집', '최정수', '서울특별시 동대문구 서울시립대로 14 ,청계한신휴플러스107-104 (답십리동) (답십리제1동)', '02', '2244', '4117', 11)
2021-08-18 17:41:02,555 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,555 INFO sqlalchemy.engine.base.Engine ('아람 어린이집', '이영일', '서울특별시 도봉구 덕릉로 349 ,402동 103호(창동, 주공4단지아파트) (창제1동)', '02', '907', '9802', 10)
2021-08-18 17:41:02,557 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,558 INFO sqlalchemy.engine.base.Engine ('예원어린이집', '권민서', '서울특별시 구로구 구일로4길 65 ,주공아파트 106동 106호 (구로동) (구로제1동)', '02', '6339', '1020', 7)

2021-08-18 17:41:02,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,560 INFO sqlalchemy.engine.base.Engine ('잠전신사임당어린이집', '임성호', '서울특별시 송파구 백제고분로11길 14-14 ,잠전신사임당 (잠실본동)', '02', '416', '6126', 18)
2021-08-18 17:41:02,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,562 INFO sqlalchemy.engine.base.Engine ('호야 어린이집', '강성진', '서울특별시 강남구 헌릉로590길 11 ,세곡 리엔 파크 아파트 307-103 (세곡동)', '02', '459', '1592', 1)
2021-08-18 17:41:02,563 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,563 INFO sqlalchemy.engine.base.Engine ('이삭어린이집', '오민서', '서울특별시 광진구 뚝섬로40길 63-10 ,(자양동) (자양제3동)', '02', '453', '5359', 6)
2021-08-18 17:41:02,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,565 INFO sqlalchemy.engine.base.Engine ('키즈팜어린이집', '오미경', '서울특별시 광진구 뚝섬로47길 33 ,(자양동) (자양제1동)', '02', '453', '8030', 6)
2021-08-18 17:41:02,566 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,567 INFO sqlalchemy.engine.base.Engine ('호수어린이집', '조지은', '서울특별시 구로구 남부순환로95길 54 ,106동 106호(개봉동, 삼환아파트) (개봉제2동)', '02', '2066', '0776', 7)
2021-08-18 17:41:02,568 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,569 INFO sqlalchemy.engine.base.Engine ('예닮어린이집', '오지은', '서울특별시 중랑구 신내로 155 ,806동 107호(신내동, 두산아파트) (신내2동)', '02', '3423', '3338', 25)
2021-08-18 17:41:02,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,571 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '송민수', '서울특별시 광진구 자양로3길 60 ,(자양동) (자양제2동)', '02', '2201', '5151', 6)
2021-08-18 17:41:02,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,572 INFO sqlalchemy.engine.base.Engine ('이삭어린이집', '강민석', '서울특별시 강동구 아리수로97길 20 ,508동 102호(강일동670, 강일리버파크5단지아파트) (강일동)', '02', '426', '8496', 2)
2021-08-18 17:41:02,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,574 INFO sqlalchemy.engine.base.Engine ('리엔어린이집', '류정순', '서울특별시 강남구 헌릉로590길 11 ,세곡리엔파크3단지 관리동 (세곡동)', '02', '459', '8004', 1)
2021-08-18 17:41:02,575 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,576 INFO sqlalchemy.engine.base.Engine ('반포퍼스티지솔마을어린이집', '송영환', '서울특별시 서초구 반포대로 275 ,래미안퍼스티지 아파트 125동앞 (반포2동)', '02', '534', '7266', 15)
2021-08-18 17:41:02,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,578 INFO sqlalchemy.engine.base.Engine ('리틀아띠어린이집', '이지은', '서울특별시 강동구 상일로 74 ,326동 102호(상일동490, 고덕리엔파크) (상일제2동)', '02', '481', '0079', 2)
2021-08-18 17:41:02,578 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,579 INFO sqlalchemy.engine.base.Engine ('강일유희어린이집', '정상철', '서울특별시 강동구 아리수로98길 25 ,703동102호(강일리버파크7단지) (강일동)', '02', '6397', '7031', 2)
2021-08-18 17:41:02,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,581 INFO sqlalchemy.engine.base.Engine ('꽃뜰어린이집', '한혜진', '서울특별시 구로구 개봉로2길 133-15 ,105동 101호(개봉동, 개봉동현대아이파크아파트) (개봉제2동)', '02', '2618', '2004', 7)
2021-08-18 17:41:02,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,582 INFO sqlalchemy.engine.base.Engine ('리틀킹어린이집', '신지영', '서울특별시 강서구 공항대로 607 (염창동)', '02', '3660', '8053', 4)
2021-08-18 17:41:02,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,587 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '서준서', '서울특별시 강동구 상일로 74 ,336동 104호(고덕리엔파크) (상일제2동)', '070', '4312', '1295', 2)
2021-08-18 17:41:02,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,589 INFO sqlalchemy.engine.base.Engine ('서머힐어린이집', '안성호', '서울특별시 용산구 장문로 27 ,4동 103호(이태원동, 청화아파트) (이태원제1동)', '02', '6241', '0081', 21)
2021-08-18 17:41:02,590 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,591 INFO sqlalchemy.engine.base.Engine ('이편한세상어린이집', '전민석', '서울특별시 동작구 보라매로 70 ,보라매 E-편한세상아파트 101동 보육시설 (신대방동) (신대방제2동)', '02', '816', '5005', 12)
2021-08-18 17:41:02,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,594 INFO sqlalchemy.engine.base.Engine ('라엘어린이집', '권지은', '서울특별시 동작구 성대로10길 44 ,(상도동) (상도제3동)', '02', '826', '4416', 12)
2021-08-18 17:41:02,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,596 INFO sqlalchemy.engine.base.Engine ('대림숲어린이집', '권영철', '서울특별시 구로구 신도림로 16 ,101동 104호(신도림동, 신도림2차e-편한세상) (신도림동)', '02', '2676', '4649', 7)
2021-08-18 17:41:02,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,598 INFO sqlalchemy.engine.base.Engine ('두빛나래어린이집', '정수빈', '서울특별시 강동구 상일로 74 ,336동 102호(상일동490, 고덕리엔파크) (상일제2동)', '02', '426', '8898', 2)
2021-08-18 17:41:02,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,600 INFO sqlalchemy.engine.base.Engine ('동부아이사랑어린이집', '류미숙', '서울특별시 은평구 진관2로 90 ,은평뉴타운 마고정아파트 311동 (진관동) (진관동)', '02', '358', '4500', 22)
2021-08-18 17:41:02,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,602 INFO sqlalchemy.engine.base.Engine ('상상놀이터어린이집', '정지혜', '서울특별시 광진구 자양로6길 9 ,(자양동) (자양제2동)', '02', '6406', '4947', 6)
2021-08-18 17:41:02,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,603 INFO sqlalchemy.engine.base.Engine ('아기랑놀이랑어린이집', '류준영', '서울특별시 강동구 명일로 293 ,505-101(길동, 삼익파크아파트) (길동)', '02', '481', '7942', 2)
2021-08-18 17:41:02,605 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,605 INFO sqlalchemy.engine.base.Engine ('이마트어린이집', '서지원', '서울특별시 성동구 성수동2가 뚝섬로 377 (성수2가제1동)', '02', '380', '9105', 16)
2021-08-18 17:41:02,606 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,606 INFO sqlalchemy.engine.base.Engine ('진관하랑어린이집', '박지영', '서울특별시 은평구 진관2로 77 ,은평뉴타운 우물골아파트 204동 (진관동) (진관동)', '02', '303', '8369', 22)
2021-08-18 17:41:02,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,608 INFO sqlalchemy.engine.base.Engine ('리체꿈나라 어린이집', '김서연', '서울특별시 서초구 고무래로 35 ,(반포동) (반포1동)', '02', '596', '1441', 15)
2021-08-18 17:41:02,610 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,610 INFO sqlalchemy.engine.base.Engine ('양천구청 직장어린이집', '정현준', '서울특별시 양천구 목동동로 81 ,해누리타운 1층 (신정동) (신정6동)', '02', '2061', '0665', 19)
2021-08-18 17:41:02,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,612 INFO sqlalchemy.engine.base.Engine ('강동리베라움어린이집', '안유진', '서울특별시 강동구 동남로79길 26 ,고덕현대아이파크 관리동 1층 (고덕동 499) (고덕제1동)', '02', '426', '0633', 2)
2021-08-18 17:41:02,613 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,614 INFO sqlalchemy.engine.base.Engine ('청정원직장어린이집', '권광수', '서울특별시 동대문구 난계로30길 31 ,(신설동) (용신동)', '02', '2231', '1896', 11)
2021-08-18 17:41:02,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,616 INFO sqlalchemy.engine.base.Engine ('해이림어린이집', '권예은', '서울특별시 강동구 풍성로 147-5 ,(성내동 509-16) (성내제2동)', '02', '489', '5929', 2)
2021-08-18 17:41:02,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,619 INFO sqlalchemy.engine.base.Engine ('KTDS서초어린이집', '전종수', '서울특별시 서초구 효령로 174 ,kds서초 어린이집 (서초3동)', '02', '3471', '1264', 15)
2021-08-18 17:41:02,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,626 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '한민서', '서울특별시 은평구 증산로7길 11-4 (증산동)', '02', '306', '1939', 22)
2021-08-18 17:41:02,627 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,628 INFO sqlalchemy.engine.base.Engine ('금빛어린이집', '김영자', '서울특별시 영등포구 도림로 313 ,가동 104호(신길동, 건영아파트) (신길제3동)', '070', '4312', '2274', 20)
2021-08-18 17:41:02,629 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,630 INFO sqlalchemy.engine.base.Engine ('리틀아트짐어린이집', '박정식', '서울특별시 강동구 상일로 74 ,324동 104호(상일동, 고덕리엔파크) (상일제2동)', '02', '441', '2234', 2)
2021-08-18 17:41:02,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,631 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '신상철', '서울특별시 은평구 연서로44길 30 ,은평뉴타운폭포동아파트 425동 (진관동) (진관동)', '02', '357', '0050', 22)
2021-08-18 17:41:02,632 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,633 INFO sqlalchemy.engine.base.Engine ('암사꼬마숲어린이집', '류준서', '서울특별시 강동구 상암로 11 ,104동 107호(암사동, 선사현대아파트) (암사제2동)', '02', '478', '2476', 2)
2021-08-18 17:41:02,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,635 INFO sqlalchemy.engine.base.Engine ('강남키즈랜드어린이집', '강미경', '서울특별시 강남구 역삼로8길 11 ,(역삼동) (역삼제1동)', '02', '557', '8112', 1)
2021-08-18 17:41:02,636 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,637 INFO sqlalchemy.engine.base.Engine ('라온누리어린이집', '이병철', '서울특별시 영등포구 도림로 365 ,103동 101호(도림동, 동아에코빌) (도림동)', '02', '6080', '9842', 20)
2021-08-18 17:41:02,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,641 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '황미경', '서울특별시 양천구 목동로 212 ,724동 108호(목동, 목동신시가지7단지아파트) (목1동)', '02', '2651', '7716', 19)
2021-08-18 17:41:02,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,643 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '박정순', '서울특별시 성동구 고산자로 164 ,105동 103호(행당동, 행당한신) (행당제1동)', '070', '4312', '3954', 16)
2021-08-18 17:41:02,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,645 INFO sqlalchemy.engine.base.Engine ('현대자연어린이집', '박유진', '서울특별시 은평구 연서로44길 7 ,은평뉴타운폭포동아파트 412동 (진관동) (진관동)', '02', '354', '1188', 22)
2021-08-18 17:41:02,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,647 INFO sqlalchemy.engine.base.Engine ('작은숲어린이집', '안지민', '서울특별시 중랑구 숙선옹주로 91 ,408동 101호(묵동, 신내아파트) (묵제1동)', '02', '3422', '4291', 25)
2021-08-18 17:41:02,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,649 INFO sqlalchemy.engine.base.Engine ('삼성래미안어린이집', '황건우', '서울특별시 은평구 진관3로 77 ,921동(진관동, 은평뉴타운구파발) (진관동)', '02', '356', '7111', 22)
2021-08-18 17:41:02,650 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,651 INFO sqlalchemy.engine.base.Engine ('선사어린이집', '임준혁', '서울특별시 강동구 상암로3길 70 ,(암사동 504-5) (암사제2동)', '02', '3426', '1148', 2)
2021-08-18 17:41:02,652 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,653 INFO sqlalchemy.engine.base.Engine ('이화키즈어린이집', '전지영', '서울특별시 양천구 목동중앙본로2길 45 ,목동근상프리즘아파트 106호 (목동) (목2동)', '02', '2061', '0667', 19)
2021-08-18 17:41:02,654 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,654 INFO sqlalchemy.engine.base.Engine ('양재키움어린이집', '정영철', '서울특별시 서초구 동산로14길 13 ,라동 101호(양재동, 초원파크빌) (양재2동)', '02', '575', '1238', 15)
2021-08-18 17:41:02,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,656 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '장미영', '서울특별시 양천구 목동중앙북로7나길 20 ,1층 (목3동)', '02', '2652', '5755', 19)
2021-08-18 17:41:02,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,658 INFO sqlalchemy.engine.base.Engine ('그린어린이집', '신지영', '서울특별시 강동구 풍성로42길 22 ,(성내동) (성내제1동)', '02', '471', '9192', 2)
2021-08-18 17:41:02,659 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,660 INFO sqlalchemy.engine.base.Engine ('구립성현햇살어린이집', '이경회', '서울특별시 관악구 관악로37길 65 ,(봉천동) [성현동] (성현동)', '02', '878', '6633', 5)
2021-08-18 17:41:02,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,668 INFO sqlalchemy.engine.base.Engine ('해원어린이집', '송준혁', '서울특별시 강북구 도봉로76길 33 ,(미아동) (미아동)', '02', '986', '2299', 3)
2021-08-18 17:41:02,669 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,670 INFO sqlalchemy.engine.base.Engine ('미소담은어린이집', '황민재', '서울특별시 서초구 바우뫼로 89 ,105동 105호(양재동, 우성아파트) (양재1동)', '02', '575', '7989', 15)
2021-08-18 17:41:02,671 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,672 INFO sqlalchemy.engine.base.Engine ('양평늘푸른어린이집', '전영길', '서울특별시 영등포구 양평동3가 선유로 207 ,609동 102호(양평동3가, 현대6차아파트) (양평제2동)', '02', '2672', '0224', 20)
2021-08-18 17:41:02,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,675 INFO sqlalchemy.engine.base.Engine ('참빛어린이집', '오은영', '서울특별시 강동구 상암로 251 ,911동 105호(명일동, 고덕주공아파트) (명일제2동)', '02', '442', '1183', 2)
2021-08-18 17:41:02,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,677 INFO sqlalchemy.engine.base.Engine ('리틀예홍어린이집', '정민지', '서울특별시 강동구 성안로13길 28 ,1층 (성내동) (성내제2동)', '02', '489', '3374', 2)
2021-08-18 17:41:02,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,680 INFO sqlalchemy.engine.base.Engine ('길음성가어린이집', '장정자', '서울특별시 성북구 길음로9길 50 (길음제1동)', '02', '941', '3391', 17)
2021-08-18 17:41:02,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,683 INFO sqlalchemy.engine.base.Engine ('서초양재어린이집', '신서현', '서울특별시 서초구 강남대로34길 46-12 ,1층(양재동) (양재1동)', '02', '578', '7922', 15)
2021-08-18 17:41:02,684 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,685 INFO sqlalchemy.engine.base.Engine ('키즈랜드 어린이집', '권은영', '서울특별시 마포구 월드컵북로 502-7 ,월드컵파크 12단지 관리동 1층 (상암동) (상암동)', '02', '307', '5233', 13)
2021-08-18 17:41:02,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,691 INFO sqlalchemy.engine.base.Engine ('푸른성북어린이집', '최현준', '서울특별시 성북구 지봉로23길 51 ,(보문동2가) (보문동)', '02', '928', '2114', 17)
2021-08-18 17:41:02,692 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,693 INFO sqlalchemy.engine.base.Engine ('상상어린이집', '윤종수', '서울특별시 도봉구 도봉로108길 81 (창제2동)', '02', '991', '3730', 10)
2021-08-18 17:41:02,695 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,695 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '강성호', '서울특별시 용산구 이촌로 347 ,9동 102호(서빙고동, 신동아아파트) (서빙고동)', '070', '8746', '4682', 21)
2021-08-18 17:41:02,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,697 INFO sqlalchemy.engine.base.Engine ('도만스쿨어린이집', '권예은', '서울특별시 양천구 목동중앙본로 50-12 ,101동 101호(목동, 웨스트빌아파트) (목2동)', '02', '2061', '5865', 19)
2021-08-18 17:41:02,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,698 INFO sqlalchemy.engine.base.Engine ('사랑나무 어린이집', '김영자', '서울특별시 마포구 방울내로 36 ,101동 102호(망원동, 두영이지안) (망원제2동)', '02', '334', '2240', 13)
2021-08-18 17:41:02,699 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,700 INFO sqlalchemy.engine.base.Engine ('깊은샘영재 어린이집', '오준호', '서울특별시 마포구 새터산길 1-6 (성산제2동)', '02', '308', '4390', 13)
2021-08-18 17:41:02,700 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,701 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '안정식', '서울특별시 마포구 방울내로11길 27 ,노아아크빌 103호 (망원동) (망원제2동)', '02', '325', '1515', 13)
2021-08-18 17:41:02,702 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,704 INFO sqlalchemy.engine.base.Engine ('지혜로운어린이집', '류도현', '서울특별시 강동구 고덕로20나길 14 (암사제1동)', '02', '429', '5551', 2)
2021-08-18 17:41:02,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,706 INFO sqlalchemy.engine.base.Engine ('누리봄어린이집', '류정웅', '서울특별시 송파구 위례성대로8길 28 ,101동 104호(방이동, 금호베스트빌아파트) (방이2동)', '02', '422', '5271', 18)
2021-08-18 17:41:02,707 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,708 INFO sqlalchemy.engine.base.Engine ('새롬이 어린이집', '류순자', '서울특별시 양천구 신정로13길 38 ,104동 103호(신정동, 신정E-편한세상아파트) (신정3동)', '02', '2065', '2288', 19)
2021-08-18 17:41:02,710 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,712 INFO sqlalchemy.engine.base.Engine ('목3동리라어린이집', '전예준', '서울특별시 양천구 목동중앙남로 69 ,(목동) (목3동)', '02', '2654', '8489', 19)
2021-08-18 17:41:02,713 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,713 INFO sqlalchemy.engine.base.Engine ('미예뜰 어린이집', '윤예은', '서울특별시 성북구 길음로 33 ,삼성래미안 814동(관리동) (길음제1동)', '02', '909', '5453', 17)
2021-08-18 17:41:02,714 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,715 INFO sqlalchemy.engine.base.Engine ('우리캐슬어린이집', '강영식', '서울특별시 양천구 오목로5길 19 ,양천롯데캐슬내 (신월동) (신월4동)', '02', '2601', '6652', 19)
2021-08-18 17:41:02,715 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,716 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '이유진', '서울특별시 영등포구 도신로 68 ,106동 107호(신길동, 신길우성1차아파트) (신길제3동)', '070', '4046', '2274', 20)
2021-08-18 17:41:02,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,718 INFO sqlalchemy.engine.base.Engine ('대성꿈나무 어린이집', '임종수', '서울특별시 양천구 중앙로29길 108 ,101동 103호(신정동, 대성유니드아파트) (신정3동)', '02', '2602', '7763', 19)
2021-08-18 17:41:02,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,719 INFO sqlalchemy.engine.base.Engine ('까꿍 어린이집', '안영진', '서울특별시 성북구 길음로9길 50 ,901동 102호(길음동, 길음뉴타운9단지아파트) (길음제1동)', '070', '4233', '8201', 17)
2021-08-18 17:41:02,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,726 INFO sqlalchemy.engine.base.Engine ('래미안쁘띠 어린이집', '오준호', '서울특별시 성북구 길음로9길 50 ,908동 102호(길음동, 길음뉴타운9단지아파트) (길음제1동)', '070', '4234', '9016', 17)

2021-08-18 17:41:02,729 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,733 INFO sqlalchemy.engine.base.Engine ('두산위브 어린이집', '오준혁', '서울특별시 성북구 길음로13길 22 ,길음뉴타운 두산위브아파트 관리동 (길음동) (길음제1동)', '02', '915', '5650', 17)
2021-08-18 17:41:02,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,735 INFO sqlalchemy.engine.base.Engine ('마미맘어린이집', '류진호', '서울특별시 은평구 불광로 122-10 ,3204동 101호(불광동, 북한산힐스테이트3차아파트) (불광제1동)', '02', '6013', '5106', 22)
2021-08-18 17:41:02,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,737 INFO sqlalchemy.engine.base.Engine ('강동다원어린이집', '박건우', '서울특별시 강동구 고덕로98길 160 ,1406동 103호 (상일제2동)', '02', '470', '4706', 2)
2021-08-18 17:41:02,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,739 INFO sqlalchemy.engine.base.Engine ('꿈터어린이집', '권준서', '서울특별시 성북구 길음로 33 ,래미안아파트 관리동 (길음제1동)', '02', '909', '5277', 17)
2021-08-18 17:41:02,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,741 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '조진호', '서울특별시 성동구 마장로39길 43 ,102동 102호(마장동, 신성미소지움아파트) (마장동)', '02', '2299', '1533', 16)
2021-08-18 17:41:02,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,743 INFO sqlalchemy.engine.base.Engine ('숲속키즈어린이집', '송정자', '서울특별시 용산구 새창로 70 ,103동 102호 (도원동,삼성래미안아파트) (용문동)', '02', '702', '5437', 21)
2021-08-18 17:41:02,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,746 INFO sqlalchemy.engine.base.Engine ('코코엔젤어린이집', '강종수', '서울특별시 마포구 월드컵북로 260 ,20동 109호(성산동, 성산시영) (성산제2동)', '02', '302', '3644', 13)
2021-08-18 17:41:02,747 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,748 INFO sqlalchemy.engine.base.Engine ('메이플트리어린이집', '이정호', '서울특별시 송파구 올림픽로 435 ,관리동 1층 (신천동) (잠실4동)', '02', '425', '2077', 18)
2021-08-18 17:41:02,750 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,750 INFO sqlalchemy.engine.base.Engine ('튼튼어린이집', '윤성수', '서울특별시 송파구 송파대로 567 ,504동 104호(잠실동, 주공아파트) (잠실3동)', '02', '443', '0752', 18)
2021-08-18 17:41:02,752 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,752 INFO sqlalchemy.engine.base.Engine ('도원삼성어린이집', '권영일', '서울특별시 용산구 새창로 70 ,112동 104호(도원동, 삼성래미안아파트) (용문동)', '02', '712', '4242', 21)
2021-08-18 17:41:02,753 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,753 INFO sqlalchemy.engine.base.Engine ('조은아이어린이집', '장정식', '서울특별시 서초구 잠원로14길 41 ,324동 106호(잠원동, 신반포아파트) (잠원동)', '02', '3482', '7220', 15)
2021-08-18 17:41:02,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,756 INFO sqlalchemy.engine.base.Engine ('삼성해맑은 어린이집', '강민서', '서울특별시 성북구 종암로24가길 80 ,101동 103호(종암동, 래미안라센트아파트) (종암동)', '02', '911', '7004', 17)
2021-08-18 17:41:02,757 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,758 INFO sqlalchemy.engine.base.Engine ('킨더바움 어린이집', '이경숙', '서울특별시 성북구 오패산로 90 ,116동 101호 (하월곡동, 래미안월곡아파트) (월곡제1동)', '02', '6229', '0302', 17)
2021-08-18 17:41:02,759 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,760 INFO sqlalchemy.engine.base.Engine ('하랑어린이집', '한영일', '서울특별시 성동구 상원길 59 ,104동 104호(성수동1가, 쌍용아파트) (성수1가제2동)', '02', '6071', '5309', 16)
2021-08-18 17:41:02,761 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,762 INFO sqlalchemy.engine.base.Engine ('라움어린이집', '권서연', '서울특별시 송파구 백제고분로46길 32-34 (송파1동)', '02', '443', '0320', 18)
2021-08-18 17:41:02,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,763 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '강영진', '서울특별시 마포구 월드컵북로 502-36 ,1013동 103호(상암동, 월드컵파크 10단지) (상암동)', '02', '305', '9820', 13)
2021-08-18 17:41:02,764 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,765 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '송예준', '서울특별시 마포구 월드컵북로 502-36 ,월드컵파크 10단지 관리동 1층 (상암동) (상암동)', '02', '307', '3332', 13)
2021-08-18 17:41:02,768 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,768 INFO sqlalchemy.engine.base.Engine ('비율라어린이집', '한순자', '서울특별시 영등포구 도림로141가길 33-4 (문래동)', '02', '2633', '6651', 20)
2021-08-18 17:41:02,769 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,770 INFO sqlalchemy.engine.base.Engine ('태영어린이집', '한상훈', '서울특별시 마포구 독막로 266 ,108동 101호(대흥동, 마포태영아파트) (용강동)', '02', '716', '1026', 13)
2021-08-18 17:41:02,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,771 INFO sqlalchemy.engine.base.Engine ('트리베라어린이집', '한예준', '서울특별시 강북구 삼양로27길 19 ,218동 1층 (미아동, 삼성래미안트리베라2차아파트) (삼각산동)', '02', '981', '2257', 3)
2021-08-18 17:41:02,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,773 INFO sqlalchemy.engine.base.Engine ('아이본어린이집', '권준호', '서울특별시 강동구 상일로19길 36 ,(고덕동 185번지) (고덕제2동)', '02', '442', '8958', 2)
2021-08-18 17:41:02,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,776 INFO sqlalchemy.engine.base.Engine ('풀잎어린이집', '전영철', '서울특별시 은평구 진관2로 60 ,은평뉴타운 마고정 333동 1층 (진관동) (진관동)', '02', '382', '0202', 22)
2021-08-18 17:41:02,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,779 INFO sqlalchemy.engine.base.Engine ('진관라온어린이집', '윤정운', '서울특별시 은평구 진관1로 55 ,은평뉴타운 마고정 309동 1층 (진관동) (진관동)', '02', '387', '0999', 22)
2021-08-18 17:41:02,779 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,780 INFO sqlalchemy.engine.base.Engine ('한신키즈어린이집', '최서연', '서울특별시 중랑구 동일로 752 ,102동 106호(중화동, 중화한신아파트) (중화제1동)', '02', '432', '0133', 25)
2021-08-18 17:41:02,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,781 INFO sqlalchemy.engine.base.Engine ('아이린어린이집', '김경자', '서울특별시 강서구 초록마을로 157-19 (화곡제8동)', '02', '2601', '1300', 4)
2021-08-18 17:41:02,783 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,784 INFO sqlalchemy.engine.base.Engine ('드림아이어린이집', '서영길', '서울특별시 중랑구 동일로 752 ,102동 102호(중화동, 중화한신아파트) (중화제1동)', '02', '495', '3378', 25)
2021-08-18 17:41:02,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,786 INFO sqlalchemy.engine.base.Engine ('사랑숲어린이집', '이정수', '서울특별시 마포구 월드컵북로 502-37 ,월드컵파크 11단지 관리동 1층 (상암동) (상암동)', '02', '302', '8050', 13)
2021-08-18 17:41:02,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,787 INFO sqlalchemy.engine.base.Engine ('브니엘어린이집', '정성호', '서울특별시 강남구 개포로109길 5 ,304동 106호(개포동, 대청아파트) (일원2동)', '02', '6160', '5571', 1)
2021-08-18 17:41:02,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,791 INFO sqlalchemy.engine.base.Engine ('석촌사임당어린이집', '조미숙', '서울특별시 송파구 가락로11길 13 ,(석촌동) (석촌동)', '02', '414', '1866', 18)
2021-08-18 17:41:02,793 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,793 INFO sqlalchemy.engine.base.Engine ('여의동어린이집', '김준호', '서울특별시 영등포구 국제금융로 124 ,(여의도동) (여의동)', '02', '786', '2727', 20)
2021-08-18 17:41:02,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,795 INFO sqlalchemy.engine.base.Engine ('늘사랑어린이집', '황종수', '서울특별시 노원구 누원로 18 ,,4단지내 관리사무소 1층(상계1동 수락리버시티) (상계1동)', '02', '935', '0816', 9)
2021-08-18 17:41:02,796 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,797 INFO sqlalchemy.engine.base.Engine ('이삭 어린이집', '최도현', '서울특별시 성북구 길음로 16 ,609동 104호(길음동, 길음뉴타운) (길음제1동)', '02', '982', '0644', 17)
2021-08-18 17:41:02,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,798 INFO sqlalchemy.engine.base.Engine ('잼잼서밋어린이집', '조은영', '서울특별시 강서구 양천로14길 118 ,우림상가 1층 (방화동) (방화제2동)', '02', '2662', '9009', 4)
2021-08-18 17:41:02,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,799 INFO sqlalchemy.engine.base.Engine ('책읽는어린이집', '강지훈', '서울특별시 용산구 이촌로 201 ,201동 103호(이촌동, 한가람아파트) (이촌제1동)', '02', '6359', '1105', 21)
2021-08-18 17:41:02,801 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,801 INFO sqlalchemy.engine.base.Engine ('베베콩어린이집', '한상철', '서울특별시 중랑구 신내로 127 ,902동 106호(신내동, 신내진흥아파트) (신내2동)', '02', '3422', '6566', 25)
2021-08-18 17:41:02,802 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,803 INFO sqlalchemy.engine.base.Engine ('엄마랑어린이집', '권준혁', '서울특별시 성북구 길음로 33 ,817동 103호(길음동, 길음뉴타운8단지아파트) (길음제1동)', '02', '915', '4060', 17)
2021-08-18 17:41:02,804 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,807 INFO sqlalchemy.engine.base.Engine ('길음꼬마숲 어린이집', '윤수빈', '서울특별시 성북구 길음로 33 ,819동103호(길음동,삼성래미안아파트) (길음제1동)', '02', '943', '1646', 17)
2021-08-18 17:41:02,809 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,809 INFO sqlalchemy.engine.base.Engine ('시온 어린이집', '송종수', '서울특별시 성북구 길음로 33 ,816동101호(길음동,삼성래미안아파트) (길음제1동)', '02', '6053', '1595', 17)
2021-08-18 17:41:02,811 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,811 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '정지영', '서울특별시 영등포구 도신로15라길 5-7 ,101동 103호(도림동, 한라아파트) (도림동)', '02', '833', '3700', 20)
2021-08-18 17:41:02,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,813 INFO sqlalchemy.engine.base.Engine ('상계8동어린이집', '한종수', '서울특별시 노원구 동일로227길 86 ,주공15단지 관리동 (상계8동)', '02', '937', '7735', 9)
2021-08-18 17:41:02,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,815 INFO sqlalchemy.engine.base.Engine ('압구정아람어린이집', '신은경', '서울특별시 강남구 압구정로 311 ,(압구정동) (압구정동)', '02', '545', '0513', 1)
2021-08-18 17:41:02,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,816 INFO sqlalchemy.engine.base.Engine ('키즈래미안어린이집', '전정순', '서울특별시 강북구 삼양로19길 25 ,관리동 (미아동, 삼성래미안트리베라1차아파트) (삼각산동)', '02', '945', '5561', 3)
2021-08-18 17:41:02,817 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,818 INFO sqlalchemy.engine.base.Engine ('파인5어린이집', '윤준서', '서울특별시 송파구 충민로4길 5 ,송파파인타운5단지아파트 내 관리동 (장지동) (장지동)', '02', '404', '5058', 18)
2021-08-18 17:41:02,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,819 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '조성호', '서울특별시 강동구 동남로67길 42 ,(명일동) (명일제2동)', '02', '476', '0607', 2)
2021-08-18 17:41:02,820 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,821 INFO sqlalchemy.engine.base.Engine ('꼬마대통령 어린이집', '최정남', '서울특별시 성동구 무수막길 72 ,(금호동2가) (금호2.3가동)', '02', '2253', '6007', 16)
2021-08-18 17:41:02,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,822 INFO sqlalchemy.engine.base.Engine ('꽃그네어린이집', '서영환', '서울특별시 양천구 목동중앙본로 34 ,월드메르디앙아파트 101동 103호 (목2동)', '02', '2642', '1008', 19)
2021-08-18 17:41:02,823 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,823 INFO sqlalchemy.engine.base.Engine ('힐스테이트 어린이집', '황광수', '서울특별시 성동구 성수일로4길 26 ,서울숲힐스테이트 아파트 단지내 관리노인정 1층 (성수동2가) (성수2가제1동)', '02', '466', '5331', 16)
2021-08-18 17:41:02,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,826 INFO sqlalchemy.engine.base.Engine ('도담공동육아어린이집', '정현준', '서울특별시 도봉구 해등로34길 77 (방학제3동)', '02', '905', '5698', 10)
2021-08-18 17:41:02,827 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,828 INFO sqlalchemy.engine.base.Engine ('다예린어린이집', '이경회', '서울특별시 마포구 월드컵북로 260 ,27동 104호(성산동, 성산시영) (성산제2동)', '02', '309', '0279', 13)

2021-08-18 17:41:02,829 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,830 INFO sqlalchemy.engine.base.Engine ('삼성래미안어린이집', '최혜진', '서울특별시 영등포구 양평동2가 영등포로3길 9 ,105동 106호(양평동2가, 양평삼성아파트) (양평제1동)', '02', '830', '5755', 20)
2021-08-18 17:41:02,831 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,831 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '안영일', '서울특별시 구로구 오류로8다길 9 ,다동 106호(오류동, 우석빌라) (오류제2동)', '02', '2682', '7772', 7)
2021-08-18 17:41:02,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,833 INFO sqlalchemy.engine.base.Engine ('하늘별 어린이집', '장정남', '서울특별시 성북구 오패산로16가길 40 ,101동 104호(하월곡동, 꿈의숲푸르지오아파트) (월곡제1동)', '02', '6406', '7325', 17)
2021-08-18 17:41:02,834 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,835 INFO sqlalchemy.engine.base.Engine ('브레인어린이집', '김준영', '서울특별시 강남구 헌릉로590길 10 ,세곡리엔파크아파트 201동 101호 (세곡동)', '02', '6440', '9533', 1)
2021-08-18 17:41:02,836 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,837 INFO sqlalchemy.engine.base.Engine ('월곡푸르지오어린이집', '황영진', '서울특별시 성북구 오패산로16가길 40 ,113동 104호(하월곡동, 꿈의숲푸르지오아파트) (월곡제1동)', '02', '919', '2233', 17)
2021-08-18 17:41:02,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,839 INFO sqlalchemy.engine.base.Engine ('당산사임당어린이집', '강혜진', '서울특별시 영등포구 당산로36길 12 ,203동 102호(당산동4가, 삼성아파트) (당산제2동)', '02', '2672', '2250', 20)
2021-08-18 17:41:02,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,841 INFO sqlalchemy.engine.base.Engine ('하늘보라어린이집', '오준호', '서울특별시 강동구 성내로6가길 29 ,201동 101호(성내동, 동원아파트) (성내제1동)', '02', '449', '6110', 2)
2021-08-18 17:41:02,842 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,843 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '조준혁', '서울특별시 중랑구 신내로 155 ,802동 103호(신내동, 화성두산아파트) (신내2동)', '02', '3423', '1239', 25)
2021-08-18 17:41:02,844 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,845 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '강은경', '서울특별시 용산구 이촌로87길 13 ,104동 104호(이촌동, 강촌아파트) (이촌제1동)', '02', '790', '3903', 21)
2021-08-18 17:41:02,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,846 INFO sqlalchemy.engine.base.Engine ('사랑해어린이집', '임성민', '서울특별시 광진구 뚝섬로52마길 66 ,(자양동) (자양제2동)', '02', '452', '1198', 6)
2021-08-18 17:41:02,847 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,850 INFO sqlalchemy.engine.base.Engine ('반포퍼스티지 하늘어린이집', '오정운', '서울특별시 서초구 반포대로 275 ,(반포동) (반포2동)', '02', '534', '7274', 15)
2021-08-18 17:41:02,851 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,852 INFO sqlalchemy.engine.base.Engine ('구립 진관어린이집', '강정남', '서울특별시 은평구 진관1로 48 (진관동)', '02', '358', '0181', 22)
2021-08-18 17:41:02,853 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,853 INFO sqlalchemy.engine.base.Engine ('남서울교회부설 꿈이있는어린이집', '김은영', '서울특별시 영등포구 신풍로16길 1 ,꿈이있는 어린이집 (신길제6동)', '02', '833', '7213', 20)
2021-08-18 17:41:02,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,855 INFO sqlalchemy.engine.base.Engine ('튼튼어린이집', '서성호', '서울특별시 강서구 등촌로39라길 21 ,(등촌동) (등촌제2동)', '02', '2653', '3313', 4)
2021-08-18 17:41:02,856 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,857 INFO sqlalchemy.engine.base.Engine ('영어린이집', '한현정', '서울특별시 서초구 잠원로14길 54 ,101호(잠원동, 신화아파트) (잠원동)', '02', '3477', '7929', 15)
2021-08-18 17:41:02,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,859 INFO sqlalchemy.engine.base.Engine ('강일열린어린이집', '임영철', '서울특별시 강동구 아리수로98길 25 ,강일리버파크 7단지 관리동 (강일동 686) (강일동)', '02', '3013', '5233', 2)
2021-08-18 17:41:02,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,863 INFO sqlalchemy.engine.base.Engine ('용산구청직장어린이집', '안성호', '서울특별시 용산구 녹사평대로 150 ,종합행정타운 1층 (이태원동) (이태원제1동)', '02', '794', '2543', 21)
2021-08-18 17:41:02,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,865 INFO sqlalchemy.engine.base.Engine ('e편한어린이집', '이혜진', '서울특별시 강남구 선릉로69길 20 ,역삼e편한세상 관리동 (역삼제2동)', '02', '2051', '4081', 1)
2021-08-18 17:41:02,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,867 INFO sqlalchemy.engine.base.Engine ('구립둔촌숲속어린이집', '임성민', '서울특별시 강동구 천호대로198길 12-12 ,(둔촌동 600-10) (둔촌제2동)', '02', '474', '2233', 2)
2021-08-18 17:41:02,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,869 INFO sqlalchemy.engine.base.Engine ('맘앤키즈어린이집', '윤예준', '서울특별시 용산구 효창원로 17 ,107동 105호(산천동, 삼성리버힐아파트) (원효로제2동)', '02', '719', '4183', 21)
2021-08-18 17:41:02,870 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,871 INFO sqlalchemy.engine.base.Engine ('재미솔솔어린이집', '임순자', '서울특별시 송파구 동남로24길 9 ,1층 (오금동)', '02', '400', '3889', 18)
2021-08-18 17:41:02,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,872 INFO sqlalchemy.engine.base.Engine ('그린나래어린이집', '전준서', '서울특별시 송파구 송파대로22길 5-13 ,1층 그린나래어린이집 (문정1동)', '02', '449', '7994', 18)
2021-08-18 17:41:02,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,874 INFO sqlalchemy.engine.base.Engine ('새봄어린이집', '김준영', '서울특별시 중랑구 중랑천로20길 27-4 (중화제2동)', '02', '496', '5209', 25)
2021-08-18 17:41:02,875 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,876 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '오상훈', '서울특별시 중랑구 용마산로 669 ,106동 104호(신내동, 신내데시앙아파트) (신내1동)', '02', '3422', '5279', 25)
2021-08-18 17:41:02,878 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:02,880 INFO sqlalchemy.engine.base.Engine ('구립강일새롬어린이집', '서영숙', '서울특별시 강동구 고덕로97길 29 ,강일리버파크 9단지 관리동 1층 (강일동 699) (강일동)', '02', '428', '2580', 2)
2021-08-18 17:41:02,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,883 INFO sqlalchemy.engine.base.Engine ('신내데시앙어린이집', '류영식', '서울특별시 중랑구 용마산로 669 ,신내데시앙아파트 114동 1층 (신내동) (신내1동)', '02', '3421', '0331', 25)
2021-08-18 17:41:02,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,885 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '정수빈', '서울특별시 강동구 아리수로97길 20 ,강일리버파크 5단지 관리동 (강일동 670) (강일동)', '02', '442', '5520', 2)
2021-08-18 17:41:02,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,888 INFO sqlalchemy.engine.base.Engine ('아이미소어린이집', '정준호', '서울특별시 구로구 항동로 42 ,한양수자인에듀힐즈 507-101 (항동)', '02', '2688', '7774', 7)
2021-08-18 17:41:02,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,890 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '강동현', '서울특별시 강서구 금낭화로24가길 21 ,(방화동) (방화제3동)', '02', '2665', '5000', 4)
2021-08-18 17:41:02,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,892 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '서도현', '서울특별시 강서구 강서로18다길 33 (화곡제8동)', '02', '2644', '1248', 4)
2021-08-18 17:41:02,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,894 INFO sqlalchemy.engine.base.Engine ('라라어린이집', '한지훈', '서울특별시 중랑구 면목로35길 63 ,401동 102호(면목동, 면목두산아파트) (면목제7동)', '02', '433', '3723', 25)
2021-08-18 17:41:02,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,896 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '박은영', '서울특별시 중구 청구로1길 23 ,108동 102호(신당동, 삼성아파트) (청구동)', '02', '6365', '2004', 24)
2021-08-18 17:41:02,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,898 INFO sqlalchemy.engine.base.Engine ('둘리어린이집', '한영일', '서울특별시 도봉구 우이천로34길 39 ,(쌍문동) (쌍문제1동)', '02', '6409', '9916', 10)
2021-08-18 17:41:02,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,900 INFO sqlalchemy.engine.base.Engine ('꿈이크는어린이집', '임지훈', '서울특별시 구로구 경인로 382 ,111동 101호(개봉동, 한마을아파트) (개봉제1동)', '02', '6347', '4827', 7)
2021-08-18 17:41:02,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,901 INFO sqlalchemy.engine.base.Engine ('현대힐스어린이집', '한정운', '서울특별시 구로구 부일로9길 127 ,온수힐스테이트 107동 (온수동) (수궁동)', '02', '6738', '1400', 7)
2021-08-18 17:41:02,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,902 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '오지훈', '서울특별시 관악구 청룡8길 10 ,청룡동] (봉천동) (청룡동)', '02', '3285', '6279', 5)
2021-08-18 17:41:02,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,916 INFO sqlalchemy.engine.base.Engine ('연세대학교유진어린이집', '황예준', '서울특별시 서대문구 연세로 50 ,연세대학교 (신촌동) (신촌동)', '02', '2123', '8266', 14)
2021-08-18 17:41:02,918 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,919 INFO sqlalchemy.engine.base.Engine ('에반어린이집', '황은영', '서울특별시 강서구 강서로12길 23-7 (화곡제8동)', '02', '2601', '1398', 4)
2021-08-18 17:41:02,920 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,921 INFO sqlalchemy.engine.base.Engine ('토토어린이집', '전현정', '서울특별시 송파구 충민로 188 ,103동 104호(장지동, 송파파인타운1단지아파트) (장지동)', '02', '6083', '7575', 18)
2021-08-18 17:41:02,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,923 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '이성진', '서울특별시 마포구 월드컵로31길 103 ,(망원동) 101호 (망원제2동)', '02', '336', '2303', 13)
2021-08-18 17:41:02,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,925 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '김지은', '서울특별시 구로구 부일로9길 127 ,113동 103호(온수동, 현대힐스테이트) (수궁동)', '02', '2066', '6727', 7)
2021-08-18 17:41:02,926 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,927 INFO sqlalchemy.engine.base.Engine ('하늘사랑어린이집', '권성수', '서울특별시 영등포구 영등포로12길 8 ,3동 107호(양평동1가, 신동아아파트) (양평제1동)', '02', '2678', '6849', 20)
2021-08-18 17:41:02,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,929 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '황성호', '서울특별시 동작구 동작대로29길 110 ,406동 104호(사당동, 신동아4차아파트) (사당제2동)', '02', '599', '5466', 12)
2021-08-18 17:41:02,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,932 INFO sqlalchemy.engine.base.Engine ('포스코 제1 어린이집', '오서연', '서울특별시 강남구 테헤란로 440 ,(대치동) (대치제4동)', '02', '3457', '6282', 1)
2021-08-18 17:41:02,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,934 INFO sqlalchemy.engine.base.Engine ('경희대학교직장어린이집', '송진호', '서울특별시 동대문구 경희대로 26-6 (회기동)', '02', '961', '9326', 11)
2021-08-18 17:41:02,936 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,936 INFO sqlalchemy.engine.base.Engine ('은현어린이집', '신지혜', '서울특별시 서대문구 응암로 151 ,(북가좌동) (북가좌제2동)', '02', '375', '9255', 14)
2021-08-18 17:41:02,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,941 INFO sqlalchemy.engine.base.Engine ('우리은행 어린이집', '안은영', '서울특별시 마포구 월드컵북로60길 17 ,우리금융상암센터 2층 보육시설 (상암동)', '02', '3151', '3865', 13)
2021-08-18 17:41:02,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,943 INFO sqlalchemy.engine.base.Engine ('토리어린이집', '서영철', '서울특별시 도봉구 덕릉로 350 ,401동 102호(창동, 주공4단지아파트) (창제1동)', '02', '6227', '5520', 10)
2021-08-18 17:41:02,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,947 INFO sqlalchemy.engine.base.Engine ('하늘정원어린이집', '김예은', '서울특별시 송파구 새말로12길 16 ,송파파인타운 4단지 관리동 (1층) (장지동) (장지동)', '070', '8877', '3236', 18)

2021-08-18 17:41:02,949 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,950 INFO sqlalchemy.engine.base.Engine ('한국은행 어린이집', '송지은', '서울특별시 중구 남대문로2가 남대문로 55 ,한국은행 소공별관 (소공동)', '02', '750', '6701', 24)
2021-08-18 17:41:02,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,953 INFO sqlalchemy.engine.base.Engine ('미광어린이집', '송영자', '서울특별시 중랑구 용마산로115나길 7 ,(망우동) (망우본동)', '02', '494', '2011', 25)
2021-08-18 17:41:02,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,955 INFO sqlalchemy.engine.base.Engine ('에코비자연어린이집', '임미경', '서울특별시 중랑구 동일로126길 49-1 (중화제1동)', '02', '433', '5679', 25)
2021-08-18 17:41:02,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,957 INFO sqlalchemy.engine.base.Engine ('국회제2어린이집', '한경숙', '서울특별시 영등포구 의사당대로 1 ,(여의도동) (여의동)', '02', '6788', '4794', 20)
2021-08-18 17:41:02,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,959 INFO sqlalchemy.engine.base.Engine ('아름드리어린이집', '오종수', '서울특별시 도봉구 방학로15길 40 ,101동 102호(방학동, 신동아2단지아파트) (방학제3동)', '02', '6232', '1479', 10)
2021-08-18 17:41:02,960 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,961 INFO sqlalchemy.engine.base.Engine ('한별어린이집', '임수빈', '서울특별시 강남구 봉은사로82길 23 ,(삼성동) (삼성제1동)', '02', '569', '8711', 1)
2021-08-18 17:41:02,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,962 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '송상훈', '서울특별시 강동구 아리수로97길 68 ,강일리버파크2단지 관리동 1층 (강일동 668) (강일동)', '02', '2293', '9496', 2)
2021-08-18 17:41:02,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,964 INFO sqlalchemy.engine.base.Engine ('남산타운어린이집', '황유진', '서울특별시 중구 다산로 32 ,(신당동) (약수동)', '02', '2256', '5114', 24)
2021-08-18 17:41:02,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,965 INFO sqlalchemy.engine.base.Engine ('구립아이뜰어린이집', '박서연', '서울특별시 관악구 봉천로33나길 30 ,은천동 복합청사 1층 [은천동] (은천동)', '02', '877', '9179', 5)
2021-08-18 17:41:02,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,967 INFO sqlalchemy.engine.base.Engine ('대학로어린이집', '임진호', '서울특별시 종로구 이화장길 86-22 (이화동)', '02', '741', '0323', 23)
2021-08-18 17:41:02,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,969 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '신미경', '서울특별시 용산구 이촌로71길 10 ,210동 103호 (이촌제1동)', '02', '749', '1684', 21)
2021-08-18 17:41:02,970 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,971 INFO sqlalchemy.engine.base.Engine ('사랑스런어린이집', '윤영철', '서울특별시 송파구 오금로57길 3-7 (거여1동)', '02', '3402', '1001', 18)
2021-08-18 17:41:02,972 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,973 INFO sqlalchemy.engine.base.Engine ('KT연구개발센터 꿈나무어린이집', '황현정', '서울특별시 서초구 태봉로 151 ,(우면동) (양재1동)', '02', '574', '0030', 15)
2021-08-18 17:41:02,974 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,974 INFO sqlalchemy.engine.base.Engine ('은행나무어린이집', '전정자', '서울특별시 강동구 아리수로93가길 25 ,강일리버파크 1단지 관리동 1층 (강일동) (강일동)', '02', '429', '4560', 2)
2021-08-18 17:41:02,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,977 INFO sqlalchemy.engine.base.Engine ('가락본동어린이집', '최준호', '서울특별시 송파구 송이로17길 46 ,(가락동) (가락본동)', '02', '403', '0405', 18)
2021-08-18 17:41:02,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,979 INFO sqlalchemy.engine.base.Engine ('파인7어린이집', '윤정호', '서울특별시 송파구 충민로4길 19 ,파인타운7단지 703동 1층(장지동) (장지동)', '02', '406', '0963', 18)
2021-08-18 17:41:02,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,981 INFO sqlalchemy.engine.base.Engine ('햇빛어린이집', '최혜진', '서울특별시 구로구 디지털로31길 90 ,114동 101호(구로동, 삼성래미안아파트) (구로제3동)', '02', '866', '7637', 7)
2021-08-18 17:41:02,982 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,982 INFO sqlalchemy.engine.base.Engine ('우성사랑어린이집', '류유진', '서울특별시 도봉구 해등로 286-5 ,102동 108호(방학동, 우성아파트) (방학제3동)', '02', '6436', '3700', 10)
2021-08-18 17:41:02,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,984 INFO sqlalchemy.engine.base.Engine ('유앤미어린이집', '서지은', '서울특별시 양천구 곰달래로7길 57-1 (신월1동)', '02', '2608', '0262', 19)
2021-08-18 17:41:02,986 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,986 INFO sqlalchemy.engine.base.Engine ('아이누리어린이집', '정예은', '서울특별시 구로구 중앙로 121 ,106동 101호(고척동, 고척파크푸르지오아파트) (고척제2동)', '02', '2691', '5555', 7)
2021-08-18 17:41:02,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,988 INFO sqlalchemy.engine.base.Engine ('해피트리어린이집', '윤경자', '서울특별시 동대문구 장한로5길 28 ,301동 106호(장안동, 신일해피트리3차아파트) (장안제1동)', '02', '2244', '3533', 11)
2021-08-18 17:41:02,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,989 INFO sqlalchemy.engine.base.Engine ('문래동어린이집', '오준호', '서울특별시 영등포구 도림로141가길 16 ,(문래동4가) (문래동)', '02', '2672', '9990', 20)
2021-08-18 17:41:02,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,992 INFO sqlalchemy.engine.base.Engine ('성원베베아트스쿨어린이집', '임영자', '서울특별시 양천구 목동중앙남로 100 ,103동 106호(목동, 성원아파트) (목3동)', '02', '2652', '0642', 19)
2021-08-18 17:41:02,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,994 INFO sqlalchemy.engine.base.Engine ('우주래미안어린이집', '박정수', '서울특별시 성북구 종암로23길 35 ,래미안종암2차 아파트 관리동 (종암동) (종암동)', '02', '921', '0005', 17)
2021-08-18 17:41:02,994 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,995 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '서민수', '서울특별시 도봉구 우이천로 200 ,금용A101-101호 (창제2동)', '02', '908', '7004', 10)

2021-08-18 17:41:02,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,997 INFO sqlalchemy.engine.base.Engine ('꼬마해림어린이집', '한성호', '서울특별시 양천구 목동서로2길 22 ,108동 110호(목동, 한신청구아파트) (목5동)', '02', '2652', '2246', 19)
2021-08-18 17:41:02,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:02,998 INFO sqlalchemy.engine.base.Engine ('아영어린이집', '류영일', '서울특별시 강동구 아리수로93길 40 ,(강일동, 강일리버파크3단지 관리동) (강일동)', '02', '3426', '4824', 2)
2021-08-18 17:41:03,000 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,000 INFO sqlalchemy.engine.base.Engine ('아이세움어린이집', '강준혁', '서울특별시 강동구 아리수로94길 72 ,강일리버파크 8단지 관리동 1층 (강일동) (강일동)', '02', '481', '6767', 2)
2021-08-18 17:41:03,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,003 INFO sqlalchemy.engine.base.Engine ('다원어린이집', '장수빈', '서울특별시 마포구 독막로 192 ,(신수동) (신수동)', '02', '702', '2992', 13)
2021-08-18 17:41:03,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,005 INFO sqlalchemy.engine.base.Engine ('참빛어린이집', '황성진', '서울특별시 구로구 구일로4길 65 ,109동 108호(구로동, 주공아파트) (구로제1동)', '02', '830', '8749', 7)
2021-08-18 17:41:03,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,007 INFO sqlalchemy.engine.base.Engine ('봄빛어린이집', '전유진', '서울특별시 송파구 백제고분로22길 37 ,101동 110호(삼전동, 현대아파트) (삼전동)', '02', '422', '9386', 18)
2021-08-18 17:41:03,008 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,009 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '오영철', '서울특별시 중랑구 봉화산로 189 ,1103동 101호(신내동, 신내대명아파트) (신내2동)', '02', '6217', '7611', 25)
2021-08-18 17:41:03,011 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,011 INFO sqlalchemy.engine.base.Engine ('조아조아어린이집', '황영식', '서울특별시 강서구 양천로14길 37 ,102동 108호(방화동, 신안테트빌1단지) (방화제2동)', '02', '2663', '6411', 4)
2021-08-18 17:41:03,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,013 INFO sqlalchemy.engine.base.Engine ('엄마품에어린이집', '오정호', '서울특별시 구로구 구일로8길 92 ,5동 105호(구로동, 중앙하이츠아파트) (구로제1동)', '02', '866', '7772', 7)
2021-08-18 17:41:03,015 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,015 INFO sqlalchemy.engine.base.Engine ('아이나라어린이집', '권정웅', '서울특별시 중랑구 신내로7길 20 ,204동 104호(신내동, 건영2차아파트) (신내2동)', '02', '434', '6614', 25)
2021-08-18 17:41:03,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,017 INFO sqlalchemy.engine.base.Engine ('금호사임당어린이집', '한정호', '서울특별시 양천구 목동중앙북로8길 111 ,103동 107호(목동, 목동금호베스트빌) (목2동)', '02', '2654', '4089', 19)
2021-08-18 17:41:03,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,019 INFO sqlalchemy.engine.base.Engine ('아리아어린이집', '전정자', '서울특별시 도봉구 마들로 684-19 ,108동 109호(도봉동, 서원아파트) (도봉제2동)', '02', '6221', '8842', 10)
2021-08-18 17:41:03,019 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,020 INFO sqlalchemy.engine.base.Engine ('상암누리어린이집', '류민지', '서울특별시 마포구 상암산로1길 71 ,마포육아종합지원센터내 1층 (상암동) (상암동)', '02', '304', '3434', 13)
2021-08-18 17:41:03,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,021 INFO sqlalchemy.engine.base.Engine ('루첸키즈빌어린이집', '서미숙', '서울특별시 성북구 월계로36길 27 ,꿈의숲대명루첸아파트 102동 1층 (장위동) (장위제3동)', '02', '919', '1155', 17)
2021-08-18 17:41:03,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,023 INFO sqlalchemy.engine.base.Engine ('열림섬마어린이집', '한정남', '서울특별시 도봉구 노해로70길 119 ,1806동 103호(창동, 주공18단지아파트) (창제4동)', '02', '6221', '9556', 10)
2021-08-18 17:41:03,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,025 INFO sqlalchemy.engine.base.Engine ('꿈사랑어린이집', '이영자', '서울특별시 중랑구 신내로19길 42 ,615동 106호(신내동, 신내대주아파트) (신내2동)', '02', '6461', '2004', 25)
2021-08-18 17:41:03,027 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,028 INFO sqlalchemy.engine.base.Engine ('예은별어린이집', '서영진', '서울특별시 구로구 구로중앙로18길 68 ,1동 108호(구로동, 신구로현대아파트) (구로제4동)', '02', '868', '7234', 7)
2021-08-18 17:41:03,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,030 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '오준혁', '서울특별시 금천구 가산로3길 46 ,(가산동) (가산동)', '02', '862', '7123', 8)
2021-08-18 17:41:03,031 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,032 INFO sqlalchemy.engine.base.Engine ('한강로어린이집', '조건우', '서울특별시 용산구 서빙고로 35 ,111호~113호(용상시티파크1단지) (한강로동)', '02', '790', '8150', 21)
2021-08-18 17:41:03,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,034 INFO sqlalchemy.engine.base.Engine ('리가숲어린이집', '조영길', '서울특별시 구로구 중앙로12길 7 ,리가건영아파트 관리동 (고척동) (고척제1동)', '02', '2613', '9282', 7)
2021-08-18 17:41:03,035 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,036 INFO sqlalchemy.engine.base.Engine ('미리내어린이집', '최정자', '서울특별시 중랑구 용마산로116길 58 ,(망우동) (망우본동)', '02', '495', '6908', 25)
2021-08-18 17:41:03,038 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,038 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '신정호', '서울특별시 양천구 가로공원로60길 9-3 (신월3동)', '02', '2646', '9377', 19)
2021-08-18 17:41:03,040 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,040 INFO sqlalchemy.engine.base.Engine ('드림어린이집', '전서현', '서울특별시 강서구 수명로2길 50 ,(내발산동) (발산제1동)', '02', '2662', '8170', 4)
2021-08-18 17:41:03,042 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,042 INFO sqlalchemy.engine.base.Engine ('수어린이집', '오미영', '서울특별시 송파구 바람드리13길 1 ,(풍납동) (풍납1동)', '02', '487', '6106', 18)
2021-08-18 17:41:03,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,043 INFO sqlalchemy.engine.base.Engine ('국방부청사어린이집', '전현준', '서울특별시 용산구 이태원로 22 ,국방부 (용산동3가) (한강로동)', '02', '798', '0097', 21)
2021-08-18 17:41:03,044 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,046 INFO sqlalchemy.engine.base.Engine ('비손어린이집', '박성호', '서울특별시 영등포구 도림로143길 32 ,101동 104호(문래동4가, 문래동삼환아파트) (문래동)', '02', '2068', '2111', 20)
2021-08-18 17:41:03,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,048 INFO sqlalchemy.engine.base.Engine ('BeBe스쿨어린이집', '전지영', '서울특별시 강서구 초록마을로 146 ,102호 (화곡제8동)', '02', '335', '1730', 4)
2021-08-18 17:41:03,050 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,050 INFO sqlalchemy.engine.base.Engine ('아이원어린이집', '안건우', '서울특별시 성동구 난계로 84 ,107동 101호(하왕십리동, 풍림아이원아파트) (왕십리제2동)', '02', '2282', '2183', 16)
2021-08-18 17:41:03,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,052 INFO sqlalchemy.engine.base.Engine ('하늘빛 어린이집', '오건우', '서울특별시 성북구 화랑로 214 ,102동 102호(석관동, 래미안석관아파트) (석관동)', '02', '959', '3582', 17)
2021-08-18 17:41:03,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,053 INFO sqlalchemy.engine.base.Engine ('아이니어린이집', '임영철', '서울특별시 강동구 아리수로98길 25 ,711동 101호(강일동, 강일리버파크7단지아파트) (강일동)', '02', '426', '7479', 2)
2021-08-18 17:41:03,054 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,055 INFO sqlalchemy.engine.base.Engine ('레이크어린이집', '안서연', '서울특별시 송파구 석촌호수로18길 11-5 (석촌동)', '02', '414', '1861', 18)
2021-08-18 17:41:03,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,058 INFO sqlalchemy.engine.base.Engine ('대우맑은샘어린이집', '송정수', '서울특별시 구로구 중앙로 121 ,104동 102호 (고척제2동)', '02', '2688', '7024', 7)
2021-08-18 17:41:03,059 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,060 INFO sqlalchemy.engine.base.Engine ('예꿈어린이집', '송도현', '서울특별시 용산구 이촌로 347 ,1동 102호 (서빙고동)', '070', '8776', '7070', 21)
2021-08-18 17:41:03,061 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,062 INFO sqlalchemy.engine.base.Engine ('열린어린이집', '송은경', '서울특별시 강서구 허준로 234 ,910동 102호(가양동, 도시개발9단지아파트) (가양제3동)', '070', '8616', '0412', 4)
2021-08-18 17:41:03,062 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,063 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '김영철', '서울특별시 구로구 구일로4길 65 ,111동 108호(구로동, 주공아파트) (구로제1동)', '02', '867', '4280', 7)
2021-08-18 17:41:03,064 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,065 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '신영진', '서울특별시 성동구 행당로 82 ,113동 103호(행당동, 해모로한진타운) (행당제2동)', '02', '2282', '5004', 16)
2021-08-18 17:41:03,066 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,066 INFO sqlalchemy.engine.base.Engine ('정릉햇살가득 어린이집', '류영식', '서울특별시 성북구 북악산로 851 ,정릉2차 E-편한세상 아파트 복리시설 1층 (정릉동) (정릉제1동)', '02', '942', '5252', 17)
2021-08-18 17:41:03,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,067 INFO sqlalchemy.engine.base.Engine ('서울청사푸르미어린이집', '서성진', '서울특별시 종로구 세종로 세종대로 209 ,서울청사 푸르미어린이집 (사직동)', '02', '737', '7327', 23)
2021-08-18 17:41:03,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,069 INFO sqlalchemy.engine.base.Engine ('리틀평강어린이집', '한영식', '서울특별시 양천구 신정로13길 51 ,201동 101호(신월동, 벽산블루밍) (신월6동)', '02', '2699', '1216', 19)
2021-08-18 17:41:03,070 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,070 INFO sqlalchemy.engine.base.Engine ('꿈비어린이집', '윤지혜', '서울특별시 강서구 수명로2가길 22 ,마곡수명산파크7단지 내 꿈비어린이집 (발산제1동)', '02', '2667', '1768', 4)
2021-08-18 17:41:03,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,072 INFO sqlalchemy.engine.base.Engine ('짐키드어린이집', '전서연', '서울특별시 성동구 행당로 82 ,105동 104호(행당동, 해모로한진타운) (행당제2동)', '02', '2281', '5056', 16)
2021-08-18 17:41:03,074 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,075 INFO sqlalchemy.engine.base.Engine ('벽산꿈터어린이집', '정정수', '서울특별시 도봉구 방학로11길 36 ,1동 106호(방학동, 벽산아파트) (방학제3동)', '02', '3491', '4684', 10)
2021-08-18 17:41:03,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,076 INFO sqlalchemy.engine.base.Engine ('대원꼬마숲어린이집', '서영숙', '서울특별시 영등포구 문래로4길 26 ,대원칸타빌 101동 104호 (문래동6가) (문래동)', '02', '2633', '7940', 20)
2021-08-18 17:41:03,077 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,078 INFO sqlalchemy.engine.base.Engine ('꿈땅어린이집', '조미영', '서울특별시 강서구 우장산로8길 42 ,천우네오젠아파트 101호 (내발산동) (우장산동)', '02', '2063', '3392', 4)
2021-08-18 17:41:03,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,080 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '류민재', '서울특별시 양천구 오목로 76-2 ,201동 101호(신월동, 장수마을2단지 동원데쟈뷰아파트) (신월2동)', '02', '2699', '9831', 19)
2021-08-18 17:41:03,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,081 INFO sqlalchemy.engine.base.Engine ('햇살마루 어린이집', '정민석', '서울특별시 서초구 잠원로 202-11 ,2동 108호(잠원동, 훼미리) (잠원동)', '02', '537', '7933', 15)
2021-08-18 17:41:03,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,083 INFO sqlalchemy.engine.base.Engine ('민들레어린이집', '안예준', '서울특별시 강서구 허준로 175 ,613동 103호(가양동, 가양6단지아파트) (가양제3동)', '02', '3663', '3664', 4)
2021-08-18 17:41:03,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,085 INFO sqlalchemy.engine.base.Engine ('올리브어린이집', '박은정', '서울특별시 관악구 은천로 137 ,1동 102호(봉천동,관악유앤아이) [성현동] (성현동)', '02', '882', '0628', 5)
2021-08-18 17:41:03,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,087 INFO sqlalchemy.engine.base.Engine ('더불어숲어린이집', '전지은', '서울특별시 동대문구 한천로33길 11 ,래미안 답십리아파트 단지동 (답십리동) (답십리제2동)', '02', '6253', '1004', 11)

2021-08-18 17:41:03,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,089 INFO sqlalchemy.engine.base.Engine ('마미어린이집', '김성호', '서울특별시 서대문구 증가로32길 58 ,(북가좌동) (북가좌제2동)', '02', '302', '5003', 14)
2021-08-18 17:41:03,090 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,091 INFO sqlalchemy.engine.base.Engine ('서대문구청직장어린이집', '박영철', '서울특별시 서대문구 홍제천로 182 ,(연희동) (연희동)', '02', '323', '3360', 14)
2021-08-18 17:41:03,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,093 INFO sqlalchemy.engine.base.Engine ('이삭어린이집', '강경회', '서울특별시 구로구 구일로4길 65 ,107동 105호(구로동, 구로주공아파트) (구로제1동)', '02', '855', '5894', 7)
2021-08-18 17:41:03,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,094 INFO sqlalchemy.engine.base.Engine ('진흥숲속어린이집', '한지훈', '서울특별시 도봉구 삼양로162가길 42-50 ,진흥숲속어린이집 (쌍문동) (쌍문제1동)', '02', '980', '5248', 10)
2021-08-18 17:41:03,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,096 INFO sqlalchemy.engine.base.Engine ('사랑천사어린이집', '정민석', '서울특별시 도봉구 해등로 231 ,5동 101호(쌍문동, 한양아파트) (쌍문제4동)', '02', '906', '0829', 10)
2021-08-18 17:41:03,096 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,097 INFO sqlalchemy.engine.base.Engine ('신림사임당어린이집', '한정남', '서울특별시 관악구 난곡로59길 16 ,(신림동) [미성동] (미성동)', '02', '852', '9900', 5)
2021-08-18 17:41:03,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,098 INFO sqlalchemy.engine.base.Engine ('좋은나무어린이집', '강진호', '서울특별시 구로구 고척로 49 ,201동 104호(오류동, 동부골든아파트) (오류제1동)', '02', '2688', '2093', 7)
2021-08-18 17:41:03,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,099 INFO sqlalchemy.engine.base.Engine ('향기나무어린이집', '안은경', '서울특별시 강서구 남부순환로 11 ,101동 101호(공항동, 동부센트레빌4차아파트) (공항동)', '02', '6082', '5454', 4)
2021-08-18 17:41:03,100 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,100 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '박혜진', '서울특별시 강동구 고덕로97길 20 ,1008동 104호(강일동, 강일리버파크10단지아파트) (강일동)', '02', '427', '8546', 2)
2021-08-18 17:41:03,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,102 INFO sqlalchemy.engine.base.Engine ('꿈이랑어린이집', '이민서', '서울특별시 양천구 오목로11길 9-12 ,101동 102호(신월동, 남영시티빌아파트) (신월2동)', '02', '2601', '0999', 19)
2021-08-18 17:41:03,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,104 INFO sqlalchemy.engine.base.Engine ('성산어린이집', '조지영', '서울특별시 강서구 개화동로23길 111 (방화제2동)', '02', '2663', '0471', 4)
2021-08-18 17:41:03,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,106 INFO sqlalchemy.engine.base.Engine ('엘림몬테소리어린이집', '송성호', '서울특별시 성동구 금호로 100 ,101동 103호(금호동1가, 벽산아파트) (금호1가동)', '02', '2291', '2769', 16)
2021-08-18 17:41:03,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,109 INFO sqlalchemy.engine.base.Engine ('동부해맑은어린이집', '임성수', '서울특별시 강서구 남부순환로 11 ,103동 101호(공항동, 공항동부센트레빌) (공항동)', '02', '2666', '7952', 4)
2021-08-18 17:41:03,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,111 INFO sqlalchemy.engine.base.Engine ('하늘정원어린이집', '안현정', '서울특별시 강서구 화곡로20길 25 (화곡제1동)', '02', '6237', '0430', 4)
2021-08-18 17:41:03,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,114 INFO sqlalchemy.engine.base.Engine ('참누리어린이집', '최도현', '서울특별시 양천구 목동남로2길 60-30 ,104동 101호(신정동, 세양청마루아파트) (신정7동)', '02', '2654', '3998', 19)
2021-08-18 17:41:03,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,116 INFO sqlalchemy.engine.base.Engine ('늘해랑어린이집', '정준호', '서울특별시 용산구 이촌로29길 21-7 ,101동 101호(한강로3가, 우림필유아파트) (한강로동)', '02', '792', '4683', 21)
2021-08-18 17:41:03,117 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,117 INFO sqlalchemy.engine.base.Engine ('킨더하우스어린이집', '장병철', '서울특별시 강동구 아리수로97길 19 ,407동 106호(강일동, 강일리버파크4단지아파트) (강일동)', '02', '426', '8151', 2)
2021-08-18 17:41:03,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,119 INFO sqlalchemy.engine.base.Engine ('드림하우스어린이집', '최유진', '서울특별시 강동구 아리수로94길 19 ,608동 102호(강일동, 강일리버파크6단지아파트) (강일동)', '02', '428', '8815', 2)
2021-08-18 17:41:03,120 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,120 INFO sqlalchemy.engine.base.Engine ('단향어린이집', '신서연', '서울특별시 강서구 초록마을로 156-3 (화곡제8동)', '02', '3662', '8648', 4)
2021-08-18 17:41:03,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,122 INFO sqlalchemy.engine.base.Engine ('행복한코아루어린이집', '서미숙', '서울특별시 양천구 남부순환로56길 9 ,101동 101호(신월동, 코아루아파트) (신월3동)', '02', '2691', '5001', 19)
2021-08-18 17:41:03,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,124 INFO sqlalchemy.engine.base.Engine ('구립라온어린이집', '송준혁', '서울특별시 동작구 동작대로17길 28 ,(사당동) (사당제1동)', '02', '522', '5298', 12)
2021-08-18 17:41:03,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,126 INFO sqlalchemy.engine.base.Engine ('파인10어린이집', '황정수', '서울특별시 송파구 송파대로8길 20 ,파인10단지 (장지동)', '02', '401', '3044', 18)
2021-08-18 17:41:03,127 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,127 INFO sqlalchemy.engine.base.Engine ('예쁜별어린이집', '신병철', '서울특별시 양천구 신목로2길 11 ,103동 101호(신정동, 청구아파트) (신정2동)', '02', '2625', '0572', 19)
2021-08-18 17:41:03,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,133 INFO sqlalchemy.engine.base.Engine ('사랑둥이어린이집', '안영자', '서울특별시 양천구 신월로 99 ,20동 106호(신월동, 신월시영아파트) (신월7동)', '02', '2696', '4194', 19)
2021-08-18 17:41:03,134 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,135 INFO sqlalchemy.engine.base.Engine ('정다운어린이집', '전준호', '서울특별시 양천구 신월로20길 33 ,신도신월 1차 아파트 103동 104호 (신월2동)', '02', '2699', '9439', 19)
2021-08-18 17:41:03,136 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,137 INFO sqlalchemy.engine.base.Engine ('파인6어린이집', '장정호', '서울특별시 송파구 충민로6길 14 ,(장지동) (장지동)', '02', '407', '7790', 18)
2021-08-18 17:41:03,138 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,138 INFO sqlalchemy.engine.base.Engine ('반포자이어린이집', '최지은', '서울특별시 서초구 신반포로 270 ,129동 103호(반포동, 반포자이아파트) (반포1동)', '070', '8713', '8066', 15)
2021-08-18 17:41:03,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,140 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '이혜진', '서울특별시 구로구 신도림로 16 ,105동 103호(신도림동, 대림2차아파트) (신도림동)', '02', '6738', '5629', 7)
2021-08-18 17:41:03,141 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,141 INFO sqlalchemy.engine.base.Engine ('은빛꼬마숲어린이집', '신미영', '서울특별시 강동구 아리수로97길 20 ,509동 101호(강일동, 강일리버파크5단지아파트) (강일동)', '02', '428', '7372', 2)
2021-08-18 17:41:03,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,143 INFO sqlalchemy.engine.base.Engine ('나무어린이집', '장성호', '서울특별시 중랑구 동일로126길 5-12 ,(중화동) (중화제1동)', '02', '433', '4279', 25)
2021-08-18 17:41:03,145 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,146 INFO sqlalchemy.engine.base.Engine ('서초현대어린이집', '이민지', '서울특별시 서초구 강남대로30길 77-4 ,현대빌라 101호 (양재동) (양재1동)', '02', '579', '4022', 15)
2021-08-18 17:41:03,146 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,147 INFO sqlalchemy.engine.base.Engine ('리틀현대아이어린이집', '윤성진', '서울특별시 강서구 강서로 348 ,118동 103호(내발산동, 현대홈타운) (우장산동)', '02', '2658', '0158', 4)
2021-08-18 17:41:03,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,149 INFO sqlalchemy.engine.base.Engine ('가온어린이집', '신정식', '서울특별시 마포구 모래내로9길 6 ,101동 102호(성산동, 월드컵아이파크) (성산제2동)', '02', '3142', '6255', 13)
2021-08-18 17:41:03,149 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,150 INFO sqlalchemy.engine.base.Engine ('연세중앙어린이집', '조서현', '서울특별시 강남구 개포로 516 ,604동 104호(개포동, 주공6단지아파트) (개포제2동)', '02', '459', '7624', 1)
2021-08-18 17:41:03,151 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,152 INFO sqlalchemy.engine.base.Engine ('양양어린이집', '서성수', '서울특별시 강동구 아리수로94길 72 ,801동 101호(강일동, 강일리버파크8단지아파트) (강일동)', '02', '481', '5533', 2)
2021-08-18 17:41:03,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,154 INFO sqlalchemy.engine.base.Engine ('강일리버빌어린이집', '신준혁', '서울특별시 강동구 아리수로93길 40 ,302동 102호(강일동, 강일리버파크3단지아파트) (강일동)', '02', '429', '0017', 2)
2021-08-18 17:41:03,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,156 INFO sqlalchemy.engine.base.Engine ('파인8 어린이집', '강지민', '서울특별시 송파구 충민로4길 6 ,송파파인8단지 802동 (장지동) (장지동)', '02', '3401', '2285', 18)
2021-08-18 17:41:03,158 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,159 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '전정식', '서울특별시 마포구 토정로 148-14 (서강동)', '02', '3141', '2643', 13)
2021-08-18 17:41:03,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,162 INFO sqlalchemy.engine.base.Engine ('버들어린이집', '한종수', '서울특별시 송파구 충민로6길 10 ,버들어린이집 (장지동)', '02', '403', '9351', 18)
2021-08-18 17:41:03,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,167 INFO sqlalchemy.engine.base.Engine ('신사임당어린이집', '김지영', '서울특별시 송파구 잠실로 62 ,308동 102호(잠실동, 트리지움) (잠실3동)', '02', '416', '2285', 18)
2021-08-18 17:41:03,168 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,169 INFO sqlalchemy.engine.base.Engine ('개롱어린이집', '한은정', '서울특별시 송파구 동남로 225 ,가락래미안파크팰리스아파트 관리동 1층 (가락2동)', '02', '400', '7052', 18)
2021-08-18 17:41:03,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,171 INFO sqlalchemy.engine.base.Engine ('별님스타키즈 어린이집', '전경회', '서울특별시 영등포구 당산로41길 17 (당산제2동)', '02', '2633', '4533', 20)
2021-08-18 17:41:03,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,173 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '신영식', '서울특별시 송파구 올림픽로 525 ,풍납동 현대아파트 101동 108호 (풍납2동)', '02', '6412', '6774', 18)
2021-08-18 17:41:03,183 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,184 INFO sqlalchemy.engine.base.Engine ('서정어린이집', '조민서', '서울특별시 서초구 방배천로 48 ,(방배동) (방배2동)', '02', '581', '7227', 15)
2021-08-18 17:41:03,186 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,187 INFO sqlalchemy.engine.base.Engine ('파인2 어린이집', '장경숙', '서울특별시 송파구 충민로 151 ,파인2단지 내 파인2 어린이집 (장지동) (장지동)', '02', '400', '7119', 18)
2021-08-18 17:41:03,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,189 INFO sqlalchemy.engine.base.Engine ('강남힐스어린이집', '오준혁', '서울특별시 강남구 삼성로111길 8 ,삼성동 힐스테이트 관리동 (삼성제2동)', '02', '516', '1129', 1)
2021-08-18 17:41:03,191 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,191 INFO sqlalchemy.engine.base.Engine ('SDA꿈사랑어린이집', '신민지', '서울특별시 동대문구 망우로 95 ,102동 101호(휘경동, 롯데아파트) (휘경제1동)', '02', '960', '5284', 11)
2021-08-18 17:41:03,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,194 INFO sqlalchemy.engine.base.Engine ('큰사랑어린이집', '오정운', '서울특별시 구로구 신도림로 11 ,601동 104호(신도림동, 대림3차아파트) (신도림동)', '02', '2634', '7922', 7)
2021-08-18 17:41:03,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,196 INFO sqlalchemy.engine.base.Engine ('나무어린이집', '조현정', '서울특별시 마포구 삼개로 38 ,우성아파트, 3-112 (도화동)', '070', '8254', '5458', 13)

2021-08-18 17:41:03,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,198 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '조예준', '서울특별시 용산구 효창원로69길 57 ,101동 104호(효창동, 효창베네스빌) (효창동)', '02', '719', '6545', 21)
2021-08-18 17:41:03,199 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,200 INFO sqlalchemy.engine.base.Engine ('미소가득한어린이집', '송경회', '서울특별시 동대문구 사가정로23길 40 ,경남하이빌102호 (장안동) (장안제2동)', '02', '6012', '4345', 11)
2021-08-18 17:41:03,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,201 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '안정식', '서울특별시 구로구 개봉로1길 170 ,102동 102호(개봉동, 대상아파트) (개봉제3동)', '02', '2611', '5004', 7)
2021-08-18 17:41:03,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,202 INFO sqlalchemy.engine.base.Engine ('북아현어린이집', '서정자', '서울특별시 서대문구 북아현로1가길 6 ,구립북아현어린이집 (북아현동)', '02', '312', '1401', 14)
2021-08-18 17:41:03,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,204 INFO sqlalchemy.engine.base.Engine ('수수꽃다리어린이집', '전예은', '서울특별시 구로구 경인로8길 64 ,109동 102호(오류동, 영풍마드레빌아파트) (오류제2동)', '02', '2060', '8373', 7)
2021-08-18 17:41:03,205 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,206 INFO sqlalchemy.engine.base.Engine ('피카소 어린이집', '전준호', '서울특별시 관악구 관악로30길 12 ,108동101호(봉천동,봉천우성아파트) [행운동] (행운동)', '02', '876', '6057', 5)
2021-08-18 17:41:03,207 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,208 INFO sqlalchemy.engine.base.Engine ('샘터어린이집', '조경자', '서울특별시 동대문구 고산자로 534 ,105동 101호(제기동, 한신아파트) (제기동)', '070', '7655', '5803', 11)
2021-08-18 17:41:03,210 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,210 INFO sqlalchemy.engine.base.Engine ('벼리어린이집', '권예은', '서울특별시 은평구 진관1로 21-9 ,박석고개 12단지 관리동 1층 (진관동) (진관동)', '02', '353', '1060', 22)
2021-08-18 17:41:03,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,212 INFO sqlalchemy.engine.base.Engine ('선사현대사임당어린이집', '김수빈', '서울특별시 강동구 상암로 11 ,109동 101호(암사동, 선사현대아파트) (암사제2동)', '02', '427', '0871', 2)
2021-08-18 17:41:03,215 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,216 INFO sqlalchemy.engine.base.Engine ('영재산새들어린이집', '윤현준', '서울특별시 양천구 남부순환로56길 9 ,신월3동 코아루 A 1단지 102동 101호 (신월3동)', '02', '2692', '7654', 19)
2021-08-18 17:41:03,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,219 INFO sqlalchemy.engine.base.Engine ('한국휴렛팩커드푸르니 어린이집', '임정수', '서울특별시 영등포구 국제금융로8길 27-8 ,엔에이치농협캐피탈빌딩 2층 (여의동)', '02', '780', '7037', 20)
2021-08-18 17:41:03,224 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,225 INFO sqlalchemy.engine.base.Engine ('동산어린이집', '오경회', '서울특별시 노원구 공릉로37길 6 ,(공릉동) (공릉2동)', '02', '979', '7841', 9)
2021-08-18 17:41:03,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,227 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '서정운', '서울특별시 은평구 진관4로 48-50 ,은평뉴타운 상림마을 719동 (진관동)', '02', '382', '8900', 22)
2021-08-18 17:41:03,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,228 INFO sqlalchemy.engine.base.Engine ('아름드리어린이집', '류지원', '서울특별시 강서구 까치산로4라길 20 ,(화곡동) (화곡본동)', '02', '2695', '2295', 4)
2021-08-18 17:41:03,229 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,229 INFO sqlalchemy.engine.base.Engine ('공덕삼성어린이집', '한준호', '서울특별시 마포구 마포대로 115-12 ,공덕삼성아파트 관리동 내 (아현동)', '02', '706', '2727', 13)
2021-08-18 17:41:03,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,235 INFO sqlalchemy.engine.base.Engine ('해피엔젤어린이집', '김준호', '서울특별시 강서구 까치산로12길 59 (화곡본동)', '02', '2608', '3562', 4)
2021-08-18 17:41:03,237 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,237 INFO sqlalchemy.engine.base.Engine ('아보어린이집', '이영길', '서울특별시 동대문구 장안벚꽃로 167 ,210동 103호 (장안동, 래미안장안2차아파트) (장안제2동)', '02', '3394', '6660', 11)
2021-08-18 17:41:03,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,240 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '임정순', '서울특별시 동대문구 전농로10길 20 ,101동 102호(답십리동, 청솔우성아파트) (답십리제2동)', '02', '2212', '0567', 11)
2021-08-18 17:41:03,242 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,243 INFO sqlalchemy.engine.base.Engine ('한나어린이집', '전경회', '서울특별시 동대문구 고산자로 534 ,111동 104호(제기동, 한신아파트) (제기동)', '02', '959', '0177', 11)
2021-08-18 17:41:03,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,244 INFO sqlalchemy.engine.base.Engine ('수린목어린이집', '김종수', '서울특별시 은평구 진관4로 48 -51 ,740동 1층 (진관동)', '02', '353', '2280', 22)
2021-08-18 17:41:03,245 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,246 INFO sqlalchemy.engine.base.Engine ('우주어린이집', '한준영', '서울특별시 중랑구 신내로19길 42 ,611동 102호(신내동, 신내대주아파트) (신내2동)', '070', '7715', '7773', 25)
2021-08-18 17:41:03,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,249 INFO sqlalchemy.engine.base.Engine ('예맘어린이집', '정영길', '서울특별시 강동구 명일로 157-6 ,(둔촌동) (둔촌제2동)', '02', '474', '7022', 2)
2021-08-18 17:41:03,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,251 INFO sqlalchemy.engine.base.Engine ('마포삼성어린이집', '임성민', '서울특별시 마포구 도화길 28 ,마포삼성아파트 103-104 (도화동)', '02', '6080', '6008', 13)
2021-08-18 17:41:03,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,253 INFO sqlalchemy.engine.base.Engine ('새송이어린이집', '오지영', '서울특별시 송파구 양재대로62길 17 ,대원빌딩 1층 (가락본동)', '02', '3401', '3575', 18)
2021-08-18 17:41:03,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,255 INFO sqlalchemy.engine.base.Engine ('대광어린이집', '조경자', '서울특별시 구로구 개봉로11길 17 ,(개봉동) (개봉제3동)', '02', '2614', '4776', 7)
2021-08-18 17:41:03,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,257 INFO sqlalchemy.engine.base.Engine ('동작구청어린이집', '윤준영', '서울특별시 동작구 장승배기로 161 ,동작구청 47동 2층 2호(노량진동) (노량진제2동)', '02', '820', '1567', 12)
2021-08-18 17:41:03,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,259 INFO sqlalchemy.engine.base.Engine ('키즈브레인어린이집', '송진호', '서울특별시 송파구 오금로34길 4 ,(가락동) (가락본동)', '02', '3012', '0123', 18)
2021-08-18 17:41:03,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,261 INFO sqlalchemy.engine.base.Engine ('새싹아이어린이집', '황영진', '서울특별시 도봉구 노해로69길 103 ,112동 101호(창동, 동아청솔아파트) (창제4동)', '02', '6437', '0606', 10)
2021-08-18 17:41:03,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,263 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '한준영', '서울특별시 강동구 상일로 152 ,104-102(강일동, 고덕리엔파크A) (강일동)', '02', '408', '0485', 2)
2021-08-18 17:41:03,264 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,265 INFO sqlalchemy.engine.base.Engine ('보석어린이집', '이서연', '서울특별시 구로구 구로동로47길 21 ,(구로동) (구로제2동)', '02', '6403', '2929', 7)
2021-08-18 17:41:03,266 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,267 INFO sqlalchemy.engine.base.Engine ('바움어린이집', '박준호', '서울특별시 강동구 고덕로 131 ,133동 101호(암사동, 강동롯데캐슬퍼스트아파트) (암사제3동)', '02', '452', '5370', 2)
2021-08-18 17:41:03,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,268 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '윤서연', '서울특별시 동작구 장승배기로4길 9 ,105동 1층(상도동, 포스코더샵) (상도제2동)', '02', '817', '6270', 12)
2021-08-18 17:41:03,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,270 INFO sqlalchemy.engine.base.Engine ('아기천사 어린이집', '전성호', '서울특별시 성북구 월계로36길 27 ,108동 102호(장위동, 꿈의숲대명루첸아파트) (장위제3동)', '02', '943', '9979', 17)
2021-08-18 17:41:03,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,271 INFO sqlalchemy.engine.base.Engine ('아이캐슬어린이집', '서민수', '서울특별시 강동구 고덕로 333 ,110동 104호 (고덕그라시움) (고덕제2동)', '02', '6475', '7942', 2)
2021-08-18 17:41:03,272 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,273 INFO sqlalchemy.engine.base.Engine ('아가꿈어린이집', '박지은', '서울특별시 양천구 목동동로 258 ,101동 102호(목동, 금호1차아파트) (목1동)', '02', '2648', '9225', 19)
2021-08-18 17:41:03,274 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,274 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '송영숙', '서울특별시 노원구 동일로232길 16 ,연호빌딩1층 (상계동) (상계1동)', '02', '951', '6437', 9)
2021-08-18 17:41:03,276 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,276 INFO sqlalchemy.engine.base.Engine ('빛나어린이집', '오준호', '서울특별시 송파구 올림픽로 435 ,309동 104호(신천동, 파크리오아파트) (잠실4동)', '02', '6216', '8577', 18)
2021-08-18 17:41:03,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,278 INFO sqlalchemy.engine.base.Engine ('해랑어린이집', '오병철', '서울특별시 강동구 상암로 251 ,903동 108호(명일동, 고덕주공아파트) (명일제2동)', '02', '487', '5406', 2)
2021-08-18 17:41:03,279 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,280 INFO sqlalchemy.engine.base.Engine ('꿈나무 어린이집', '임민석', '서울특별시 성동구 독서당로 218 ,104동 103호(옥수동, 삼성아파트) (옥수동)', '02', '2294', '3297', 16)
2021-08-18 17:41:03,281 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,282 INFO sqlalchemy.engine.base.Engine ('아이린어린이집', '조준호', '서울특별시 송파구 올림픽로 135 ,209동 102호(잠실동, 리센츠) (잠실2동)', '02', '424', '3575', 18)
2021-08-18 17:41:03,283 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,284 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '류영철', '서울특별시 송파구 올림픽로 99 ,123동 102호(잠실동, 잠실엘스) (잠실2동)', '02', '423', '6212', 18)
2021-08-18 17:41:03,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,285 INFO sqlalchemy.engine.base.Engine ('SK네트웍스새싹어린이집', '오경숙', '서울특별시 종로구 청계천로 85 ,삼일빌딩, 3층 (종로1.2.3.4가동)', '070', '7800', '2115', 23)
2021-08-18 17:41:03,288 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,288 INFO sqlalchemy.engine.base.Engine ('레인보우어린이집', '김건우', '서울특별시 송파구 올림픽로 99 ,엘스아파트 107동104호(구 주공1단지) (잠실동) (잠실2동)', '02', '424', '6437', 18)
2021-08-18 17:41:03,290 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,291 INFO sqlalchemy.engine.base.Engine ('참나무어린이집', '서민서', '서울특별시 마포구 새터산길 35 (성산제2동)', '02', '3141', '4271', 13)
2021-08-18 17:41:03,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,294 INFO sqlalchemy.engine.base.Engine ('프라이어생태어린이집', '윤정수', '서울특별시 강동구 고덕로 130 ,프라이어팰리스 관리동 1층 (암사제1동)', '02', '6402', '1400', 2)
2021-08-18 17:41:03,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,295 INFO sqlalchemy.engine.base.Engine ('나무와숲어린이집', '최영숙', '서울특별시 강서구 금낭화로13길 36 ,101동 106호(방화동, 방화4차태승훼미리아파트) (방화제2동)', '02', '2663', '1010', 4)
2021-08-18 17:41:03,296 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,297 INFO sqlalchemy.engine.base.Engine ('상상나라팅커벨어린이집', '신영진', '서울특별시 은평구 진관4로 47 ,708동 1층 (은평뉴타운 상림마을 3단지) (진관동)', '02', '388', '4970', 22)
2021-08-18 17:41:03,298 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,299 INFO sqlalchemy.engine.base.Engine ('프리오리어린이집', '장성호', '서울특별시 서초구 서초대로25길 97 ,(방배동) 1,2층 (방배4동)', '02', '595', '6360', 15)
2021-08-18 17:41:03,300 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,301 INFO sqlalchemy.engine.base.Engine ('부리도어린이집', '최영길', '서울특별시 송파구 올림픽로 99 ,엘스아파트단지내 통합관리사무실1층 (잠실동) (잠실2동)', '02', '416', '5545', 18)

2021-08-18 17:41:03,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,303 INFO sqlalchemy.engine.base.Engine ('꿈빛나무어린이집', '강도현', '서울특별시 서대문구 세검정로1길 116 ,홍은 복지관내 꿈빛나무어린이집 (홍은제1동)', '02', '391', '0090', 14)
2021-08-18 17:41:03,304 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,304 INFO sqlalchemy.engine.base.Engine ('휴먼시아어린이집', '최지영', '서울특별시 동작구 사당로16길 96 ,108동 101호(사당동, 사당휴먼시아아파트) (사당제4동)', '02', '598', '0907', 12)
2021-08-18 17:41:03,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,306 INFO sqlalchemy.engine.base.Engine ('아리솔어린이집', '이정남', '서울특별시 노원구 동일로205길 13 ,(중계2동 아리솔어린이집) (중계2.3동)', '02', '975', '1279', 9)
2021-08-18 17:41:03,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,308 INFO sqlalchemy.engine.base.Engine ('향기어린이집', '오지혜', '서울특별시 금천구 시흥대로120길 44 ,B동 103호(독산동, 상진아파트) (독산제4동)', '02', '869', '3003', 8)
2021-08-18 17:41:03,310 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,310 INFO sqlalchemy.engine.base.Engine ('동그라미어린이집', '조순자', '서울특별시 송파구 올림픽로 99 ,127동 102호(잠실동, 잠실엘스) (잠실2동)', '02', '414', '4425', 18)
2021-08-18 17:41:03,311 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,312 INFO sqlalchemy.engine.base.Engine ('라임나무어린이집', '김예준', '서울특별시 송파구 올림픽로 99 ,124동 104호(잠실동, 잠실엘스) (잠실2동)', '02', '6405', '3320', 18)
2021-08-18 17:41:03,313 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,313 INFO sqlalchemy.engine.base.Engine ('엘스사임당어린이집', '최정수', '서울특별시 송파구 올림픽로 99 ,132동 101호(잠실동, 잠실엘스) (잠실2동)', '02', '420', '6886', 18)
2021-08-18 17:41:03,314 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,315 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '류건우', '서울특별시 송파구 올림픽로 435 ,212동 101호(신천동, 파크리오아파트) (잠실4동)', '02', '481', '4072', 18)
2021-08-18 17:41:03,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,316 INFO sqlalchemy.engine.base.Engine ('다정한어린이집', '김영진', '서울특별시 양천구 목동서로 400 ,1015동 104호(신정동, 신시가지10단지아파트) (신정1동)', '02', '2644', '9644', 19)
2021-08-18 17:41:03,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,318 INFO sqlalchemy.engine.base.Engine ('동심어린이집', '장민지', '서울특별시 양천구 목동동로12길 60 ,105동 108호(신정동, 목동현대아파트) (신정2동)', '02', '2642', '4289', 19)
2021-08-18 17:41:03,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,321 INFO sqlalchemy.engine.base.Engine ('바론어린이집', '윤건우', '서울특별시 마포구 방울내로9안길 57 ,101동 101호(망원동, 동원데자뷰아파트) (망원제2동)', '02', '336', '1338', 13)
2021-08-18 17:41:03,322 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,322 INFO sqlalchemy.engine.base.Engine ('로고스어린이집', '이준호', '서울특별시 동작구 성대로6다길 18 (상도제3동)', '02', '6085', '3302', 12)
2021-08-18 17:41:03,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,325 INFO sqlalchemy.engine.base.Engine ('넘버원어린이집', '강서연', '서울특별시 양천구 오목로 39-22 ,101동 104호(신월동, 신월3차미소지움아파트) (신월4동)', '02', '2601', '7942', 19)
2021-08-18 17:41:03,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,328 INFO sqlalchemy.engine.base.Engine ('자이젠토들러어린이집', '권민지', '서울특별시 송파구 올림픽로 435 ,314동 103호(신천동, 파크리오아파트) (잠실4동)', '02', '483', '2500', 18)
2021-08-18 17:41:03,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,329 INFO sqlalchemy.engine.base.Engine ('키즈리베어린이집', '윤정식', '서울특별시 송파구 위례광장로 121 ,2414동 103호 (위례동)', '02', '422', '1706', 18)
2021-08-18 17:41:03,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,330 INFO sqlalchemy.engine.base.Engine ('금나래어린이집', '전지영', '서울특별시 금천구 시흥대로73길 70 ,금천구청 2층 (시흥동) (시흥제1동)', '02', '802', '1224', 8)
2021-08-18 17:41:03,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,332 INFO sqlalchemy.engine.base.Engine ('구립꿈나래어린이집', '정정호', '서울특별시 금천구 금하로3길 32 ,(시흥동) (시흥제1동)', '02', '805', '1215', 8)
2021-08-18 17:41:03,333 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,333 INFO sqlalchemy.engine.base.Engine ('하늘숲어린이집', '임준호', '서울특별시 중랑구 숙선옹주로3길 20-7 (묵제1동)', '02', '978', '5005', 25)
2021-08-18 17:41:03,335 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,335 INFO sqlalchemy.engine.base.Engine ('아이큰숲자연학교어린이집', '오영일', '서울특별시 강서구 초록마을로21길 37 ,아이큰숲자연학교 (화곡본동)', '02', '2691', '0489', 4)
2021-08-18 17:41:03,336 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,337 INFO sqlalchemy.engine.base.Engine ('아장아장어린이집', '최정순', '서울특별시 강서구 방화대로47가길 22 ,404동 103호(방화동, 삼환아파트) (방화제3동)', '02', '2662', '9002', 4)
2021-08-18 17:41:03,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,338 INFO sqlalchemy.engine.base.Engine ('애플어린이집', '박지훈', '서울특별시 송파구 올림픽로 135 ,221동 102호(잠실동, 리센츠) (잠실2동)', '02', '3486', '4775', 18)
2021-08-18 17:41:03,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,340 INFO sqlalchemy.engine.base.Engine ('더조은영재어린이집', '임진호', '서울특별시 강서구 방화대로34길 88 ,102동 103호(방화동, 마곡푸르지오아파트) (방화제1동)', '02', '2661', '1150', 4)
2021-08-18 17:41:03,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,342 INFO sqlalchemy.engine.base.Engine ('책사랑어린이집', '최민서', '서울특별시 중랑구 신내로17길 41 ,706동 102호(신내동, 진로) (신내2동)', '02', '3421', '1605', 25)
2021-08-18 17:41:03,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,344 INFO sqlalchemy.engine.base.Engine ('초록세상어린이집', '권영철', '서울특별시 양천구 화곡로14길 8 ,(신월동) (신월5동)', '02', '307', '3337', 19)
2021-08-18 17:41:03,346 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,347 INFO sqlalchemy.engine.base.Engine ('관악구청직장어린이집', '류영일', '서울특별시 관악구 관악로 145 ,관악구청 별관 2층 (봉천동) [청룡동] (청룡동)', '02', '886', '5006', 5)
2021-08-18 17:41:03,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,349 INFO sqlalchemy.engine.base.Engine ('코알라 베이비 어린이집', '오미경', '서울특별시 성동구 금호로 100 ,108동 101호(금호동1가, 벽산아파트) (금호1가동)', '02', '2236', '7942', 16)
2021-08-18 17:41:03,350 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,350 INFO sqlalchemy.engine.base.Engine ('바름이어린이집', '임준영', '서울특별시 서초구 서초대로45길 20 ,서울변호사교육문화관 1층 (서초동) (서초3동)', '02', '3476', '0572', 15)
2021-08-18 17:41:03,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,358 INFO sqlalchemy.engine.base.Engine ('태영키즈어린이집', '한병철', '서울특별시 강동구 천호대로 1055 ,103동 101호(천호동, 천호태영) (천호제3동)', '02', '470', '2129', 2)
2021-08-18 17:41:03,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,360 INFO sqlalchemy.engine.base.Engine ('매일어린이집', '장혜진', '서울특별시 도봉구 노해로69가길 11 ,107동 103호(창동, 동아청솔아파트) (창제4동)', '02', '904', '0205', 10)
2021-08-18 17:41:03,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,362 INFO sqlalchemy.engine.base.Engine ('리센츠사임당어린이집', '장미숙', '서울특별시 송파구 올림픽로 135 ,202동 102호(잠실동, 리센츠) (잠실2동)', '02', '424', '3650', 18)
2021-08-18 17:41:03,363 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,364 INFO sqlalchemy.engine.base.Engine ('선한어린이집', '임지훈', '서울특별시 관악구 남부순환로256라길 25 ,한일유앤아이아파트 101-101호(남현동) [남현동] (남현동)', '070', '7719', '1240', 5)
2021-08-18 17:41:03,365 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,365 INFO sqlalchemy.engine.base.Engine ('아이샘어린이집', '강지은', '서울특별시 도봉구 마들로 684-19 ,106동 101호(도봉동, 서원아파트) (도봉제2동)', '02', '954', '7079', 10)
2021-08-18 17:41:03,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,367 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '정상훈', '서울특별시 도봉구 노해로62길 36-3 (창제1동)', '02', '990', '0455', 10)
2021-08-18 17:41:03,368 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,369 INFO sqlalchemy.engine.base.Engine ('서초1삼성어린이집', '박영환', '서울특별시 서초구 서초대로74길 11 ,삼성전자 內 (서초동) (서초2동)', '02', '2255', '2130', 15)
2021-08-18 17:41:03,370 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,371 INFO sqlalchemy.engine.base.Engine ('하나푸르니신길어린이집', '권성민', '서울특별시 영등포구 신길로40길 5 ,(신길동) (신길제4동)', '02', '831', '2544', 20)
2021-08-18 17:41:03,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,373 INFO sqlalchemy.engine.base.Engine ('우리누리 어린이집', '이정수', '서울특별시 중구 삼일대로 340 ,나라키움빌딩 2층 (저동1가) (명동)', '02', '2260', '0257', 24)
2021-08-18 17:41:03,374 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,375 INFO sqlalchemy.engine.base.Engine ('쥬베베어린이집', '이지영', '서울특별시 강동구 상암로 11 ,115동 104호(암사동, 선사현대아파트) (암사제2동)', '02', '427', '5994', 2)
2021-08-18 17:41:03,383 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,384 INFO sqlalchemy.engine.base.Engine ('사랑초어린이집', '안성수', '서울특별시 양천구 월정로 183-1 ,1층 (신월동) (신월1동)', '02', '2607', '7252', 19)
2021-08-18 17:41:03,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,385 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '한순자', '서울특별시 송파구 충민로 152 ,303동 102호(장지동, 송파파인타운3단지아파트) (장지동)', '02', '430', '9600', 18)
2021-08-18 17:41:03,386 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,387 INFO sqlalchemy.engine.base.Engine ('행복한예향어린이집', '송순자', '서울특별시 은평구 통일로92길 11-3 (불광제2동)', '02', '2135', '2422', 22)
2021-08-18 17:41:03,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,389 INFO sqlalchemy.engine.base.Engine ('로뎀나무어린이집', '전현정', '서울특별시 송파구 충민로 152 ,302동 101호(장지동, 송파파인타운3단지아파트) (장지동)', '02', '423', '7178', 18)
2021-08-18 17:41:03,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,391 INFO sqlalchemy.engine.base.Engine ('푸른어린이집', '김준영', '서울특별시 송파구 올림픽로 135 ,리센츠아파트 250동 1층 (잠실동) (잠실2동)', '02', '413', '6750', 18)
2021-08-18 17:41:03,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,394 INFO sqlalchemy.engine.base.Engine ('해가람어린이집', '전종수', '서울특별시 마포구 마포대로26길 19 (공덕동)', '02', '393', '9544', 13)
2021-08-18 17:41:03,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,395 INFO sqlalchemy.engine.base.Engine ('키즈브라운어린이집', '최민수', '서울특별시 노원구 한글비석로24마길 8 ,(상계동) (상계3.4동)', '02', '952', '7199', 9)
2021-08-18 17:41:03,398 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,399 INFO sqlalchemy.engine.base.Engine ('꽃뜰어린이집', '장도현', '서울특별시 양천구 목동서로 340 ,913동 104호(신정동, 신시가지9단지아파트) (신정1동)', '02', '2653', '9356', 19)
2021-08-18 17:41:03,400 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,401 INFO sqlalchemy.engine.base.Engine ('잠실어린이집', '서영숙', '서울특별시 송파구 올림픽로37길 121 ,(신천동) (잠실4동)', '02', '424', '5672', 18)
2021-08-18 17:41:03,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,403 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '정준호', '서울특별시 강서구 방화대로44길 42 ,101동 103호(방화동, 승윤노블리안아파트) (방화제1동)', '02', '2666', '9551', 4)
2021-08-18 17:41:03,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,405 INFO sqlalchemy.engine.base.Engine ('사랑맘어린이집', '임민석', '서울특별시 강서구 방화대로34길 88 ,107동 104호(방화동, 대우푸르지오) (방화제1동)', '02', '2665', '1800', 4)
2021-08-18 17:41:03,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,406 INFO sqlalchemy.engine.base.Engine ('아이조아어린이집', '서준영', '서울특별시 중랑구 신내로7가길 54-12 (상봉제1동)', '02', '436', '5205', 25)

2021-08-18 17:41:03,408 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,409 INFO sqlalchemy.engine.base.Engine ('오즈의마법사어린이집', '서정수', '서울특별시 강서구 수명로1길 16 ,412동 1층(내발산동, 마곡수명산파크4단지아파트) (발산제1동)', '02', '2667', '3544', 4)
2021-08-18 17:41:03,410 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,410 INFO sqlalchemy.engine.base.Engine ('대치아이리베슐레어린이집', '조성민', '서울특별시 강남구 선릉로 222 ,대치아이파크 관리동 (대치제1동)', '02', '563', '8877', 1)
2021-08-18 17:41:03,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,414 INFO sqlalchemy.engine.base.Engine ('성신어린이집', '신예준', '서울특별시 송파구 송파대로8길 17 ,송파파인타운9단지 내 관리동 (장지동)', '02', '401', '5388', 18)
2021-08-18 17:41:03,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,416 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '류도현', '서울특별시 강남구 개포로 516 ,609동 101호(개포동, 주공아파트) (개포제2동)', '02', '445', '7909', 1)
2021-08-18 17:41:03,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,418 INFO sqlalchemy.engine.base.Engine ('항동발도르프어린이집', '황준영', '서울특별시 구로구 연동로 296-18 ,105동 102호(항동, 유승빌리지) (항동)', '02', '2612', '5354', 7)
2021-08-18 17:41:03,418 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,419 INFO sqlalchemy.engine.base.Engine ('아람어린이집', '이병철', '서울특별시 구로구 경인로 382 ,120동 102호(개봉동, 한마을아파트) (개봉제1동)', '02', '2060', '6291', 7)
2021-08-18 17:41:03,420 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,421 INFO sqlalchemy.engine.base.Engine ('송파사임당어린이집', '송영진', '서울특별시 송파구 송파대로18길 14-5 (문정1동)', '02', '407', '3379', 18)
2021-08-18 17:41:03,422 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,422 INFO sqlalchemy.engine.base.Engine ('아이미소어린이집', '신지훈', '서울특별시 도봉구 노해로70길 54 ,1903동 111호(창동, 상계주공19차아파트) (창제4동)', '02', '905', '7942', 10)
2021-08-18 17:41:03,423 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,424 INFO sqlalchemy.engine.base.Engine ('영재몬테소리어린이집', '조성호', '서울특별시 동대문구 고산자로 534 ,102동 101호(제기동, 한신아파트) (제기동)', '02', '959', '5031', 11)
2021-08-18 17:41:03,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,426 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '조건우', '서울특별시 송파구 송파대로8길 58 ,서울송파구송파대로8길 58 (장지동)', '02', '408', '0147', 18)
2021-08-18 17:41:03,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,428 INFO sqlalchemy.engine.base.Engine ('마곡사임당어린이집', '신은영', '서울특별시 강서구 수명로2길 105 ,마곡수명산파크5단지 509동 관리동 마곡사임당어린이집 (발산제1동)', '02', '2667', '6548', 4)
2021-08-18 17:41:03,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,430 INFO sqlalchemy.engine.base.Engine ('꿈이있는어린이집', '임종수', '서울특별시 강서구 공항대로59길 64 ,202동 106호(등촌동, 한사랑삼성2차아파트) (등촌제1동)', '070', '8292', '4739', 4)
2021-08-18 17:41:03,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,431 INFO sqlalchemy.engine.base.Engine ('성은어린이집', '송영길', '서울특별시 송파구 백제고분로 122 ,(잠실동) (잠실본동)', '02', '413', '8603', 18)
2021-08-18 17:41:03,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,434 INFO sqlalchemy.engine.base.Engine ('향기나무어린이집', '류건우', '서울특별시 광진구 아차산로 552 ,(광장동) 극동아파트 6동 105호 (광장동)', '02', '3436', '3995', 6)
2021-08-18 17:41:03,435 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,435 INFO sqlalchemy.engine.base.Engine ('아이빌어린이집', '안성민', '서울특별시 구로구 개봉로11길 46-23 (개봉제3동)', '02', '2616', '0025', 7)
2021-08-18 17:41:03,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,437 INFO sqlalchemy.engine.base.Engine ('롯데i어린이집', '오상훈', '서울특별시 양천구 월정로 303 ,102동 104호(신월동, 수명산롯데캐슬아파트) (신월5동)', '02', '2607', '6077', 19)
2021-08-18 17:41:03,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,439 INFO sqlalchemy.engine.base.Engine ('해송어린이집', '송지훈', '서울특별시 강서구 강서로18바길 9 ,골든리치빌102호 (화곡동) (화곡제8동)', '02', '2605', '5226', 4)
2021-08-18 17:41:03,440 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,441 INFO sqlalchemy.engine.base.Engine ('꿈쟁이어린이집', '전준영', '서울특별시 도봉구 해등로 118 ,5동 101호(창동, 상아1차아파트) (창제5동)', '070', '8742', '8525', 10)
2021-08-18 17:41:03,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,443 INFO sqlalchemy.engine.base.Engine ('해사랑어린이집', '강준서', '서울특별시 강서구 강서로47길 158 ,203동 1층(내발산동, 마곡수명산파크2단지아파트) (발산제1동)', '02', '2667', '6007', 4)
2021-08-18 17:41:03,444 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,444 INFO sqlalchemy.engine.base.Engine ('별동이어린이집', '장은경', '서울특별시 은평구 증산로11길 35 ,삼성빌라 102호 (증산동) (증산동)', '02', '302', '3809', 22)
2021-08-18 17:41:03,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,446 INFO sqlalchemy.engine.base.Engine ('풀잎어린이집', '안영환', '서울특별시 송파구 오금로 551 ,201동 101호(e편한세상송파파크센트럴) (거여2동)', '02', '409', '4506', 18)
2021-08-18 17:41:03,447 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,447 INFO sqlalchemy.engine.base.Engine ('서울청사햇살어린이집', '한정식', '서울특별시 종로구 세종대로 209 (사직동)', '02', '2100', '4788', 23)
2021-08-18 17:41:03,449 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,450 INFO sqlalchemy.engine.base.Engine ('다해영재어린이집', '강영식', '서울특별시 강서구 강서로 266 ,우장산대림e편한세상파크 관리동 다해영재어린이집 (우장산동)', '02', '2608', '0101', 4)
2021-08-18 17:41:03,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,453 INFO sqlalchemy.engine.base.Engine ('미래스쿨어린이집', '오준호', '서울특별시 강서구 까치산로18길 7-13 ,미래스쿨어린이집 (화곡제6동)', '02', '2691', '0917', 4)
2021-08-18 17:41:03,456 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,456 INFO sqlalchemy.engine.base.Engine ('푸르지오 어린이집', '이미경', '서울특별시 성동구 금호동4가 독서당로 272 ,102동 101호(금호동4가, 금호동대우아파트) (금호4가동)', '02', '2235', '2026', 16)
2021-08-18 17:41:03,458 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,458 INFO sqlalchemy.engine.base.Engine ('보금자리어린이집', '권정수', '서울특별시 동대문구 이문로1길 21 ,8동 107호(회기동, 신현대아파트) (회기동)', '02', '964', '0567', 11)
2021-08-18 17:41:03,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,460 INFO sqlalchemy.engine.base.Engine ('자이어린이집', '최정순', '서울특별시 구로구 도림로 107 ,1동 102호(구로동, 럭키아파트) (구로제4동)', '02', '838', '2206', 7)
2021-08-18 17:41:03,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,461 INFO sqlalchemy.engine.base.Engine ('나무와숲어린이집', '정준서', '서울특별시 금천구 시흥대로47길 43 ,(시흥동) 시흥1동 럭키아파트 5-109 (시흥제1동)', '02', '6264', '8893', 8)
2021-08-18 17:41:03,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,464 INFO sqlalchemy.engine.base.Engine ('아기랑어린이집', '장은정', '서울특별시 관악구 난곡로 55 ,205동 103호(신림동, 관악산휴먼시아2단지아파트) (난향동)', '02', '864', '5825', 5)
2021-08-18 17:41:03,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,466 INFO sqlalchemy.engine.base.Engine ('지니맘어린이집', '황성호', '서울특별시 동대문구 한천로11다길 86 ,(답십리동) (답십리제2동)', '070', '8111', '0030', 11)
2021-08-18 17:41:03,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,469 INFO sqlalchemy.engine.base.Engine ('엔젤음악속어린이집', '이경회', '서울특별시 노원구 동일로250길 18 ,미주동방벽운아파트 내 (상계동) (상계1동)', '02', '3391', '1811', 9)
2021-08-18 17:41:03,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,470 INFO sqlalchemy.engine.base.Engine ('구립 상림마을어린이집', '강은영', '서울특별시 은평구 진관4로 48-17 ,709동 1층(진관동, 은평뉴타운상림마을7단지아파트) (진관동)', '02', '356', '7092', 22)
2021-08-18 17:41:03,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,473 INFO sqlalchemy.engine.base.Engine ('구립 은마루어린이집', '최영환', '서울특별시 은평구 진관4로 78-8 ,701동 1층(진관동, 은평뉴타운상림마을7단지아파트) (진관동)', '02', '386', '5607', 22)
2021-08-18 17:41:03,474 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,475 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '김민지', '서울특별시 동작구 국사봉길 86-6 (상도제3동)', '02', '815', '9440', 12)
2021-08-18 17:41:03,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,477 INFO sqlalchemy.engine.base.Engine ('아이천국어린이집', '이종수', '서울특별시 구로구 고척로 28 ,예원빌딩1층 (오류동) (오류제1동)', '02', '2613', '2556', 7)
2021-08-18 17:41:03,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,479 INFO sqlalchemy.engine.base.Engine ('상록꼬마숲어린이집', '안상훈', '서울특별시 마포구 숭문길 106 ,상록 아파트 관리동 1층 (염리동)', '02', '3273', '2021', 13)
2021-08-18 17:41:03,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,481 INFO sqlalchemy.engine.base.Engine ('행복가득어린이집', '전성민', '서울특별시 영등포구 문래동4가 도림로143길 27 ,202동 103호(문래동4가, 리버뷰신안인스빌) (문래동)', '02', '6414', '9396', 20)
2021-08-18 17:41:03,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,484 INFO sqlalchemy.engine.base.Engine ('우리누리어린이집', '한정웅', '서울특별시 동대문구 약령시로 159 ,(청량리동) (청량리동)', '02', '963', '5885', 11)
2021-08-18 17:41:03,485 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,486 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '권정웅', '서울특별시 관악구 남부순환로 1969 ,(봉천동) [행운동] (행운동)', '02', '889', '7253', 5)
2021-08-18 17:41:03,487 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,488 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '임영숙', '서울특별시 중구 중림로 10 ,106동 103호(중림동, 사이버빌리지) (중림동)', '02', '364', '3642', 24)
2021-08-18 17:41:03,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,489 INFO sqlalchemy.engine.base.Engine ('코코베베어린이집', '황지훈', '서울특별시 강서구 양천로75길 57 ,104동 102호(염창동, 현대1차아파트) (염창동)', '02', '2659', '7977', 4)
2021-08-18 17:41:03,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,491 INFO sqlalchemy.engine.base.Engine ('아이제일어린이집', '김성수', '서울특별시 용산구 이태원로49길 24-7 ,아이제일어린이집 (한남동) (한남동)', '02', '797', '8551', 21)
2021-08-18 17:41:03,493 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,493 INFO sqlalchemy.engine.base.Engine ('서대문천연사임당어린이집', '전민지', '서울특별시 서대문구 독립문로8길 54 ,114동 103호(천연동, 뜨란채A 114동) (천연동)', '02', '364', '8188', 14)
2021-08-18 17:41:03,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,496 INFO sqlalchemy.engine.base.Engine ('동그라미어린이집', '최준호', '서울특별시 강서구 강서로 266 ,117동 102호(화곡동, 우장산아이파크이편한세상아파트) (우장산동)', '02', '832', '4350', 4)
2021-08-18 17:41:03,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,497 INFO sqlalchemy.engine.base.Engine ('서울시인재개발원 쑥쑥어린이집', '윤종수', '서울특별시 서초구 남부순환로340길 58 ,서울시인재개발원직장어린이집 (서초1동)', '02', '523', '2527', 15)
2021-08-18 17:41:03,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,499 INFO sqlalchemy.engine.base.Engine ('요엘행복한어린이집', '최정식', '서울특별시 송파구 양산로10길 22 ,(거여동) (거여2동)', '02', '406', '2227', 18)
2021-08-18 17:41:03,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,503 INFO sqlalchemy.engine.base.Engine ('해든어린이집', '황민재', '서울특별시 관악구 복은길 109 ,101호 (신림동) [서림동] (서림동)', '02', '877', '6549', 5)
2021-08-18 17:41:03,506 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,506 INFO sqlalchemy.engine.base.Engine ('해리어린이집', '한정식', '서울특별시 동대문구 답십리로66길 20 ,101동 101호(장안동, 금강아미움 아파트) (장안제1동)', '02', '2246', '2270', 11)
2021-08-18 17:41:03,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,509 INFO sqlalchemy.engine.base.Engine ('중원어린이집', '류영철', '서울특별시 양천구 남부순환로85길 16 ,103동 102호(신월동, 대주파크빌) (신월6동)', '02', '2699', '4841', 19)

2021-08-18 17:41:03,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,510 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '박성호', '서울특별시 서초구 효령로34길 59 ,3동 102호(방배동, 삼익아파트) (방배3동)', '02', '584', '7821', 15)
2021-08-18 17:41:03,512 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,513 INFO sqlalchemy.engine.base.Engine ('브라운스톤어린이집', '한준호', '서울특별시 동작구 상도로31길 19 ,104동 101호(상도동, 브라운스톤상도아파트) (상도제2동)', '02', '823', '0101', 12)
2021-08-18 17:41:03,514 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,515 INFO sqlalchemy.engine.base.Engine ('파란하늘빛어린이집', '송지원', '서울특별시 강서구 양천로47길 94 ,101동 105호(마곡동, 금호어울림아파트) (가양제1동)', '02', '3661', '8770', 4)
2021-08-18 17:41:03,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,517 INFO sqlalchemy.engine.base.Engine ('새서원어린이집', '조광수', '서울특별시 강서구 화곡로24길 55 ,(화곡동) (화곡제1동)', '02', '2663', '2100', 4)
2021-08-18 17:41:03,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,519 INFO sqlalchemy.engine.base.Engine ('광암 어린이집', '서성호', '서울특별시 은평구 가좌로7라길 43 ,(응암동) (응암제3동)', '02', '303', '1751', 22)
2021-08-18 17:41:03,521 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,521 INFO sqlalchemy.engine.base.Engine ('보미어린이집', '정현준', '서울특별시 강서구 화곡로44나길 25 ,(화곡동) (화곡제6동)', '02', '2692', '7711', 4)
2021-08-18 17:41:03,522 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,523 INFO sqlalchemy.engine.base.Engine ('한가람어린이집', '신영일', '서울특별시 양천구 목동동로 10 ,1104동 101호(신정동, 신시가지11단지아파트) (신정7동)', '02', '2651', '5777', 19)
2021-08-18 17:41:03,525 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,525 INFO sqlalchemy.engine.base.Engine ('해울어린이집', '신예준', '서울특별시 강서구 양천로 595 ,금호타운아파트 상가 1층 (염창동) (염창동)', '02', '2654', '7513', 4)
2021-08-18 17:41:03,527 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,527 INFO sqlalchemy.engine.base.Engine ('수명산어린이집', '김정호', '서울특별시 강서구 강서로47길 108 ,마곡수명산파크 1단지 보육시설 (발산제1동)', '02', '2667', '8532', 4)
2021-08-18 17:41:03,528 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,529 INFO sqlalchemy.engine.base.Engine ('보나어린이집', '박예준', '서울특별시 성북구 보국문로 116 ,303동 106호(정릉동, 정릉힐스테이트3차아파트) (정릉제4동)', '02', '917', '4601', 17)
2021-08-18 17:41:03,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,530 INFO sqlalchemy.engine.base.Engine ('고려대학교 구로병원 어린이집', '신성진', '서울특별시 구로구 구로동로28길 33-41 (구로제2동)', '02', '2626', '1919', 7)
2021-08-18 17:41:03,531 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,532 INFO sqlalchemy.engine.base.Engine ('구립 노을어린이집', '전건우', '서울특별시 마포구 월드컵로42길 12 ,805동 1층(상암동, 상암월드컵파크8단지아파트) (상암동)', '02', '305', '9880', 13)
2021-08-18 17:41:03,533 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,534 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '송민서', '서울특별시 동대문구 천호대로89길 33 ,202동 102호(장안동, 형인허브빌아파트) (장안제1동)', '02', '2245', '3600', 11)
2021-08-18 17:41:03,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,535 INFO sqlalchemy.engine.base.Engine ('나무를키우는햇살어린이집', '조정호', '서울특별시 중랑구 양원역로 17-13 (망우본동)', '02', '437', '4374', 25)
2021-08-18 17:41:03,537 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,538 INFO sqlalchemy.engine.base.Engine ('마곡 행복한i어린이집', '강미영', '서울특별시 강서구 수명로2길 63 ,마곡수명산파크602동 관리동 (발산제1동)', '02', '2667', '7714', 4)
2021-08-18 17:41:03,539 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,540 INFO sqlalchemy.engine.base.Engine ('다해어린이집', '오서현', '서울특별시 송파구 잠실로 62 ,트리지움아파트 관리동 1층 (잠실동) (잠실3동)', '02', '413', '0331', 18)
2021-08-18 17:41:03,541 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,542 INFO sqlalchemy.engine.base.Engine ('모아어린이집', '권예준', '서울특별시 송파구 성내천로 182 ,정우빌딩 1층 모아어린이집 (마천2동)', '02', '430', '2524', 18)
2021-08-18 17:41:03,543 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,544 INFO sqlalchemy.engine.base.Engine ('신월은혜어린이집', '윤영철', '서울특별시 양천구 월정로8길 8 ,101동 106호(신월동, 방주기픈샘아파트) (신월2동)', '02', '2608', '5141', 19)
2021-08-18 17:41:03,545 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,547 INFO sqlalchemy.engine.base.Engine ('아기새어린이집', '황준영', '서울특별시 강서구 양천로6길 57 ,102동 106호(방화동, 이편한세상아파트) (방화제2동)', '02', '2664', '7277', 4)
2021-08-18 17:41:03,548 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,549 INFO sqlalchemy.engine.base.Engine ('키즈맘 어린이집', '임준호', '서울특별시 성동구 금호로 15 ,101동 101호(금호동4가, 서울숲푸르지오아파트) (금호4가동)', '02', '2298', '4290', 16)
2021-08-18 17:41:03,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,551 INFO sqlalchemy.engine.base.Engine ('한결어린이집', '류영길', '서울특별시 강서구 강서로 266 ,111동 103호(화곡동, 우장산아이파크이편한세상아파트) (우장산동)', '02', '3667', '1894', 4)
2021-08-18 17:41:03,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,552 INFO sqlalchemy.engine.base.Engine ('이레뜰어린이집', '신상철', '서울특별시 송파구 올림픽로35길 104 ,22동 108호(신천동, 장미2차아파트) (잠실6동)', '02', '489', '2307', 18)
2021-08-18 17:41:03,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,553 INFO sqlalchemy.engine.base.Engine ('아이랑어린이집', '조서연', '서울특별시 강서구 양천로3길 17 ,101동 106호(방화동, 개화산 동부센트레빌) (방화제1동)', '02', '2665', '4552', 4)
2021-08-18 17:41:03,554 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,555 INFO sqlalchemy.engine.base.Engine ('하연어린이집', '황민서', '서울특별시 용산구 효창원로86라길 31-10 ,현대휴먼101호 (청파동1가) (청파동)', '02', '3273', '3276', 21)
2021-08-18 17:41:03,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,556 INFO sqlalchemy.engine.base.Engine ('상미어린이집', '서민수', '서울특별시 강동구 천중로21길 39 ,(천호동 303-18) (천호제2동)', '02', '478', '6715', 2)
2021-08-18 17:41:03,558 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,558 INFO sqlalchemy.engine.base.Engine ('엄마품속어린이집', '조성호', '서울특별시 노원구 동일로230가길 16 ,(상계1동 엄마품속어린이집, 1층) (상계1동)', '02', '952', '2771', 9)
2021-08-18 17:41:03,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,559 INFO sqlalchemy.engine.base.Engine ('포그니어린이집', '안준혁', '서울특별시 관악구 신림로29길 3-20 ,106동 113호(신림동, 신림현대아파트) [서림동] (서림동)', '02', '872', '7772', 5)
2021-08-18 17:41:03,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,561 INFO sqlalchemy.engine.base.Engine ('둘리어린이집', '오준호', '서울특별시 금천구 독산로14길 5 ,(시흥동) (시흥제5동)', '02', '896', '2332', 8)
2021-08-18 17:41:03,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,563 INFO sqlalchemy.engine.base.Engine ('새서울어린이집', '이민지', '서울특별시 은평구 응암로21길 1-5 (응암제3동)', '02', '353', '3611', 22)
2021-08-18 17:41:03,566 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,567 INFO sqlalchemy.engine.base.Engine ('예빛어린이집', '전민수', '서울특별시 구로구 신도림로 87 ,신도림동동아1차아파트106동 101호 (신도림동)', '02', '2671', '0779', 7)
2021-08-18 17:41:03,568 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,569 INFO sqlalchemy.engine.base.Engine ('서초구청 직장어린이집', '서종수', '서울특별시 서초구 남부순환로347길 46 ,(서초동) (서초2동)', '02', '598', '9341', 15)
2021-08-18 17:41:03,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,571 INFO sqlalchemy.engine.base.Engine ('언북 어린이집', '장영환', '서울특별시 강남구 삼성로135길 42 ,언북 초등학교 내 교육문화센터 2층 (청담동) (청담동)', '02', '547', '0134', 1)
2021-08-18 17:41:03,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,572 INFO sqlalchemy.engine.base.Engine ('킨더리베어린이집', '서민서', '서울특별시 영등포구 여의대방로43나길 25 ,101동 108호(신길동, 삼환아파트) (신길제7동)', '02', '847', '7893', 20)
2021-08-18 17:41:03,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,575 INFO sqlalchemy.engine.base.Engine ('아가랑어린이집', '황성진', '서울특별시 구로구 중앙로5길 62 ,4동 106호(고척동, 서울가든아파트) (고척제1동)', '02', '2613', '1187', 7)
2021-08-18 17:41:03,575 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,576 INFO sqlalchemy.engine.base.Engine ('아기세상어린이집', '윤은정', '서울특별시 구로구 경인로2길 30 ,102동 101호(오류동, 은하수수목원2차아파트) (오류제2동)', '02', '2060', '1343', 7)
2021-08-18 17:41:03,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,577 INFO sqlalchemy.engine.base.Engine ('응암우리어린이집', '최정식', '서울특별시 은평구 은평로6길 8-16 (응암제1동)', '02', '386', '6111', 22)
2021-08-18 17:41:03,579 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,580 INFO sqlalchemy.engine.base.Engine ('구립송암어린이집', '안성민', '서울특별시 강북구 삼양로 357 ,송암교회 교육관 1층 (수유동) (인수동)', '02', '906', '4580', 3)
2021-08-18 17:41:03,581 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,582 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '전예은', '서울특별시 구로구 남부순환로95길 88 ,101동 102호(개봉동, 두산아파트) (개봉제2동)', '02', '2611', '0784', 7)
2021-08-18 17:41:03,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,584 INFO sqlalchemy.engine.base.Engine ('서초우주 어린이집', '권영숙', '서울특별시 서초구 동광로18길 22 ,(방배동) (방배4동)', '02', '535', '3631', 15)
2021-08-18 17:41:03,585 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,586 INFO sqlalchemy.engine.base.Engine ('성내참사랑어린이집', '안건우', '서울특별시 강동구 성내로18길 19 ,(성내동 435-26) (성내제1동)', '02', '470', '0248', 2)
2021-08-18 17:41:03,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,587 INFO sqlalchemy.engine.base.Engine ('KT혜화 어린이집', '윤정운', '서울특별시 종로구 대학로 65 ,(연건동) (이화동)', '02', '3676', '9300', 23)
2021-08-18 17:41:03,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,589 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '임예준', '서울특별시 은평구 백련산로 177-19 (응암제1동)', '02', '358', '4830', 22)
2021-08-18 17:41:03,590 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,591 INFO sqlalchemy.engine.base.Engine ('예쁜꼬마어린이집', '황정자', '서울특별시 구로구 신도림로 78 ,309동 101호(신도림동, 동아3차아파트) (신도림동)', '02', '6737', '7213', 7)
2021-08-18 17:41:03,592 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,592 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '김민지', '서울특별시 동대문구 장안벚꽃로1길 7 ,힐스테이트 단지내 (장안동) (장안제2동)', '02', '3394', '6679', 11)
2021-08-18 17:41:03,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,594 INFO sqlalchemy.engine.base.Engine ('아이사랑가정어린이집', '김정호', '서울특별시 금천구 금하로 816 ,519동 106호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '808', '2355', 8)
2021-08-18 17:41:03,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,595 INFO sqlalchemy.engine.base.Engine ('수아어린이집', '조정수', '서울특별시 도봉구 시루봉로 107 ,29동 105호(방학동, 신동아1차아파트) (방학제3동)', '02', '3493', '2440', 10)
2021-08-18 17:41:03,596 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,597 INFO sqlalchemy.engine.base.Engine ('키즈맘어린이집', '김서현', '서울특별시 노원구 동일로245가길 41 ,208동 102호(상계동, 은빛2단지아파트) (상계1동)', '02', '937', '6111', 9)
2021-08-18 17:41:03,598 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,598 INFO sqlalchemy.engine.base.Engine ('프라임어린이집', '권예은', '서울특별시 송파구 충민로4길 19 ,704동 101호(장지동, 송파파인타운7단지아파트) (장지동)', '02', '406', '4019', 18)
2021-08-18 17:41:03,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,600 INFO sqlalchemy.engine.base.Engine ('새별어린이집', '강미숙', '서울특별시 양천구 신정로 293 ,104동 111호(신정동, 신트리아파트) (신정3동)', '02', '2606', '3362', 19)

2021-08-18 17:41:03,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,602 INFO sqlalchemy.engine.base.Engine ('e-다솔어린이집', '전진호', '서울특별시 강서구 강서로45나길 15 ,101동 101호(내발산동, 수산오성아파트) (발산제1동)', '02', '2696', '5621', 4)
2021-08-18 17:41:03,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,604 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '조지영', '서울특별시 도봉구 우이천로48길 3-13 ,(쌍문1동) (쌍문제1동)', '02', '905', '7887', 10)
2021-08-18 17:41:03,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,610 INFO sqlalchemy.engine.base.Engine ('아이빛어린이집', '윤민석', '서울특별시 마포구 독막로 145 ,아이빛어린이집 (서강동)', '02', '3144', '0007', 13)
2021-08-18 17:41:03,611 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,612 INFO sqlalchemy.engine.base.Engine ('대건어린이집', '한은경', '서울특별시 구로구 구일로8길 16 ,(구로동) (구로제1동)', '02', '866', '9901', 7)
2021-08-18 17:41:03,613 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,614 INFO sqlalchemy.engine.base.Engine ('제이백합어린이집', '장지은', '서울특별시 구로구 경인로43길 22 ,(고척동) (고척제1동)', '02', '6414', '1434', 7)
2021-08-18 17:41:03,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,618 INFO sqlalchemy.engine.base.Engine ('성내다솔어린이집', '서영철', '서울특별시 강동구 풍성로54길 38 ,424-10호2층(성내동 424) (성내제3동)', '02', '484', '0341', 2)
2021-08-18 17:41:03,619 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,619 INFO sqlalchemy.engine.base.Engine ('현대키즈어린이집', '권준혁', '서울특별시 금천구 벚꽃로 73 ,101동 102호(독산동, 금천현대아파트) (독산제1동)', '02', '6265', '1880', 8)
2021-08-18 17:41:03,620 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,621 INFO sqlalchemy.engine.base.Engine ('은평구청어린이집', '권성진', '서울특별시 은평구 은평로 195 ,은평구청 별관1층(녹번동) (녹번동)', '02', '3157', '1552', 22)
2021-08-18 17:41:03,622 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,622 INFO sqlalchemy.engine.base.Engine ('보명어린이집', '안영철', '서울특별시 도봉구 도봉로129길 45-12 ,1동 108호(쌍문동, 경남) (쌍문제2동)', '02', '6227', '5920', 10)
2021-08-18 17:41:03,623 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,624 INFO sqlalchemy.engine.base.Engine ('보라빛어린이집', '임지훈', '서울특별시 관악구 남부순환로246나길 15-2 ,(봉천동) [인헌동] (인헌동)', '02', '887', '2829', 5)
2021-08-18 17:41:03,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,625 INFO sqlalchemy.engine.base.Engine ('선애아이어린이집', '박종수', '서울특별시 구로구 구로동로12길 70 ,101호 (구로동) (구로제4동)', '02', '867', '5915', 7)
2021-08-18 17:41:03,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,627 INFO sqlalchemy.engine.base.Engine ('아이삭어린이집', '한영자', '서울특별시 강서구 강서로47길 108 ,106동 101호(내발산동, 마곡수명산파크1단지아파트) (발산제1동)', '02', '2667', '1006', 4)
2021-08-18 17:41:03,629 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,629 INFO sqlalchemy.engine.base.Engine ('아남어린이집', '조정호', '서울특별시 송파구 마천로35길 18 ,아남아파트 106호 (마천동) (마천2동)', '02', '3012', '6033', 18)
2021-08-18 17:41:03,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,631 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '서지민', '서울특별시 은평구 증산로21가길 5-2 (신사제1동)', '02', '307', '1149', 22)
2021-08-18 17:41:03,632 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,632 INFO sqlalchemy.engine.base.Engine ('꼬마또래어린이집', '안미숙', '서울특별시 양천구 오목로13길 14 ,1동 102호(신월동, 동양부로미아파트) (신월2동)', '02', '2602', '8788', 19)
2021-08-18 17:41:03,633 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,634 INFO sqlalchemy.engine.base.Engine ('예다운어린이집', '류민석', '서울특별시 성북구 종암로24가길 53 ,103동 101호(종암동, SK아파트) (종암동)', '02', '942', '4656', 17)
2021-08-18 17:41:03,635 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,636 INFO sqlalchemy.engine.base.Engine ('정다운어린이집', '오은영', '서울특별시 은평구 은평로 18-11 (신사제1동)', '02', '376', '9176', 22)
2021-08-18 17:41:03,638 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,638 INFO sqlalchemy.engine.base.Engine ('꿈사랑어린이집', '임미경', '서울특별시 강서구 강서로47길 108 ,104동 101호(내발산동, 마곡수명산파크1단지아파트) (발산제1동)', '02', '2667', '1235', 4)
2021-08-18 17:41:03,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,640 INFO sqlalchemy.engine.base.Engine ('누리터어린이집', '윤준영', '서울특별시 용산구 백범로90길 74 ,102동 102호(문배동, 용산이안아파트) (원효로제1동)', '02', '6401', '2379', 21)
2021-08-18 17:41:03,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,643 INFO sqlalchemy.engine.base.Engine ('우성어린이집', '오준호', '서울특별시 강동구 천호대로193길 37 ,관리동(길동, 길동우성아파트) (길동)', '02', '476', '2233', 2)
2021-08-18 17:41:03,645 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,645 INFO sqlalchemy.engine.base.Engine ('행복나무어린이집', '권정자', '서울특별시 성북구 오패산로3길 17 ,103동102호(하월곡동,동신아파트) (월곡제1동)', '02', '949', '0179', 17)
2021-08-18 17:41:03,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,647 INFO sqlalchemy.engine.base.Engine ('노브랜드노블베이비어린이집', '정혜진', '서울특별시 송파구 오금로46길 62 ,2층 (가락동) (가락2동)', '02', '430', '8142', 18)
2021-08-18 17:41:03,648 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,649 INFO sqlalchemy.engine.base.Engine ('트리지움어린이집', '전정남', '서울특별시 송파구 올림픽로35길 104 ,1동 110호 (잠실6동)', '02', '3432', '8009', 18)
2021-08-18 17:41:03,650 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,651 INFO sqlalchemy.engine.base.Engine ('미소담어린이집', '조종수', '서울특별시 강서구 곰달래로18길 33-13 ,1층 (화곡동) (화곡제1동)', '02', '2695', '2220', 4)
2021-08-18 17:41:03,652 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,653 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '신성호', '서울특별시 금천구 범안로15길 7 ,101동 104호(독산동, 계룡아파트) (독산제1동)', '02', '6085', '7255', 8)
2021-08-18 17:41:03,653 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,654 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '신영자', '서울특별시 관악구 관천로22길 43 ,1,2,3층 [신림동] (신림동) (신림동)', '02', '882', '5953', 5)
2021-08-18 17:41:03,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,655 INFO sqlalchemy.engine.base.Engine ('반디어린이집', '황도현', '서울특별시 양천구 곰달래로6길 35-1 (신월1동)', '02', '2608', '6868', 19)
2021-08-18 17:41:03,656 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,657 INFO sqlalchemy.engine.base.Engine ('아띠어린이집', '서예은', '서울특별시 동작구 양녕로26길 42 ,101동 103호(상도동, 롯데캐슬비엔) (상도제4동)', '02', '3280', '0127', 12)
2021-08-18 17:41:03,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,659 INFO sqlalchemy.engine.base.Engine ('별꿈어린이집', '정영진', '서울특별시 양천구 목동서로 400 ,1034동 105호(신정동, 신시가지10단지아파트) (신정1동)', '02', '2645', '6672', 19)
2021-08-18 17:41:03,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,661 INFO sqlalchemy.engine.base.Engine ('아띠어린이집', '류준혁', '서울특별시 양천구 은행정로7길 14 ,신세계하이츠아파트102호 (신정4동)', '02', '2651', '8001', 19)
2021-08-18 17:41:03,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,663 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '전지은', '서울특별시 은평구 은평로 182-8 (응암제1동)', '02', '354', '3562', 22)
2021-08-18 17:41:03,665 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,666 INFO sqlalchemy.engine.base.Engine ('은행나무어린이집', '전영진', '서울특별시 은평구 응암로16길 30 (응암제2동)', '02', '387', '8222', 22)
2021-08-18 17:41:03,668 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,669 INFO sqlalchemy.engine.base.Engine ('쁘띠아미 에꼴 어린이집', '오준영', '서울특별시 강서구 곰달래로53길 133 ,(화곡동) (화곡제4동)', '02', '2647', '4700', 4)
2021-08-18 17:41:03,670 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,671 INFO sqlalchemy.engine.base.Engine ('삼성새싹어린이집', '황정호', '서울특별시 성북구 월곡로14길 26 ,102동 103호(하월곡동, 월곡래미안루나밸리아파트) (월곡제2동)', '02', '917', '2223', 17)
2021-08-18 17:41:03,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,674 INFO sqlalchemy.engine.base.Engine ('화목어린이집', '윤예은', '서울특별시 구로구 구로중앙로8길 41-20 (구로제4동)', '02', '869', '3374', 7)
2021-08-18 17:41:03,675 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,676 INFO sqlalchemy.engine.base.Engine ('함께행복한어린이집', '안서연', '서울특별시 성북구 월곡로14길 26 ,106동 101호(하월곡, 월곡래미안루나밸리) (월곡제2동)', '02', '917', '2224', 17)
2021-08-18 17:41:03,677 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,678 INFO sqlalchemy.engine.base.Engine ('해뜰어린이집', '류예준', '서울특별시 도봉구 마들로 573 ,207동 101호(창동, 현대아이2차아파트) (창제4동)', '02', '904', '5109', 10)
2021-08-18 17:41:03,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,679 INFO sqlalchemy.engine.base.Engine ('꽃구름어린이집', '한정운', '서울특별시 도봉구 마들로 573 ,203동 104호(창동, 현대아이2차아파트) (창제4동)', '02', '995', '4050', 10)
2021-08-18 17:41:03,681 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,681 INFO sqlalchemy.engine.base.Engine ('영일우리어린이집', '장도현', '서울특별시 영등포구 영신로9나길 8 ,(영등포본동) (영등포본동)', '02', '835', '1232', 20)
2021-08-18 17:41:03,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,683 INFO sqlalchemy.engine.base.Engine ('완두콩어린이집', '송경숙', '서울특별시 성북구 솔샘로25길 28 ,108동 102호(정릉동, 풍림아이원) (정릉제4동)', '02', '913', '7888', 17)
2021-08-18 17:41:03,684 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,684 INFO sqlalchemy.engine.base.Engine ('영주어린이집', '전준혁', '서울특별시 용산구 두텁바위로 91 ,(후암동) (후암동)', '02', '318', '2242', 21)
2021-08-18 17:41:03,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,688 INFO sqlalchemy.engine.base.Engine ('터전어린이집', '장은영', '서울특별시 도봉구 마들로 551 ,쌍용아파트 관리동 1층 터전어린이집 (창제4동)', '02', '997', '9004', 10)
2021-08-18 17:41:03,691 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,692 INFO sqlalchemy.engine.base.Engine ('럭키어린이집', '장정호', '서울특별시 도봉구 도봉로169길 31 ,103동 110호(도봉동, 럭키아파트) (도봉제1동)', '02', '930', '7117', 10)
2021-08-18 17:41:03,693 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,694 INFO sqlalchemy.engine.base.Engine ('예향어린이집', '전민석', '서울특별시 은평구 통일로92길 11 ,(불광동) (불광제2동)', '02', '353', '2496', 22)
2021-08-18 17:41:03,695 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,696 INFO sqlalchemy.engine.base.Engine ('우리누리어린이집', '류민재', '서울특별시 영등포구 선유로 243 (양평제2동)', '02', '3667', '0801', 20)
2021-08-18 17:41:03,697 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,699 INFO sqlalchemy.engine.base.Engine ('백합어린이집', '박현준', '서울특별시 서대문구 가재울미래로 2 ,218동103호(남가좌1동,DMC파크뷰자이) (남가좌제1동)', '02', '372', '2137', 14)
2021-08-18 17:41:03,700 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,701 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '류준호', '서울특별시 동대문구 장안벚꽃로 167 ,205동 102호(장안동, 장안아파트2단지) (장안제2동)', '02', '446', '3791', 11)
2021-08-18 17:41:03,702 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,703 INFO sqlalchemy.engine.base.Engine ('현대참사랑어린이집', '최경숙', '서울특별시 동대문구 장안벚꽃로1길 7 ,1008동 102호(장안동, 장안힐스테이트아파트) (장안제2동)', '02', '2249', '6655', 11)
2021-08-18 17:41:03,704 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,704 INFO sqlalchemy.engine.base.Engine ('솔로몬스쿨어린이집', '임동현', '서울특별시 강서구 수명로2길 108 ,마곡수명산파크8단지802동관리동내 (발산제1동)', '02', '2665', '1874', 4)
2021-08-18 17:41:03,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,707 INFO sqlalchemy.engine.base.Engine ('키즈스쿨어린이집', '김지민', '서울특별시 송파구 동남로 193 ,25동(가락동, 가락1차쌍용아파트) (가락2동)', '02', '408', '5365', 18)
2021-08-18 17:41:03,708 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,708 INFO sqlalchemy.engine.base.Engine ('뽀로롱어린이집', '정예은', '서울특별시 송파구 마천로51가길 16 ,(마천동) (마천1동)', '02', '448', '5054', 18)
2021-08-18 17:41:03,711 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,712 INFO sqlalchemy.engine.base.Engine ('SK행복어린이집', '정영숙', '서울특별시 종로구 종로 26 ,SK서린동빌딩 2층 (종로1.2.3.4가동)', '02', '2121', '1611', 23)
2021-08-18 17:41:03,713 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,714 INFO sqlalchemy.engine.base.Engine ('예찬어린이집', '윤지은', '서울특별시 성북구 고려대로24가길 13-6 (안암동)', '02', '929', '5268', 17)
2021-08-18 17:41:03,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,719 INFO sqlalchemy.engine.base.Engine ('동그라미어린이집', '임지민', '서울특별시 동대문구 천호대로77길 63 ,101동 104호(장안동, 대명이룸아파트) (장안제1동)', '02', '2248', '0103', 11)
2021-08-18 17:41:03,721 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,723 INFO sqlalchemy.engine.base.Engine ('해맑음몬테소리어린이집', '김민지', '서울특별시 송파구 석촌호수로 133 ,레이크팰리스아파트 관리사무소 (잠실3동)', '02', '2147', '1154', 18)
2021-08-18 17:41:03,726 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,726 INFO sqlalchemy.engine.base.Engine ('바다어린이집', '한광수', '서울특별시 구로구 구일로4길 65 ,104동 103호(구로동, 구로주공아파트) (구로제1동)', '02', '857', '5488', 7)
2021-08-18 17:41:03,728 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,728 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '류준혁', '서울특별시 강동구 양재대로121길 57 ,1층(천호동 53-3 ) (천호제3동)', '02', '483', '0342', 2)
2021-08-18 17:41:03,729 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,731 INFO sqlalchemy.engine.base.Engine ('예아어린이집', '오현준', '서울특별시 도봉구 마들로 646 ,관리동 (방학동, 삼성래미안아파트) (방학제1동)', '02', '3493', '3345', 10)
2021-08-18 17:41:03,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,732 INFO sqlalchemy.engine.base.Engine ('해피맘 어린이집', '이광수', '서울특별시 성북구 오패산로 46 ,114동 106호(하월곡동, 월곡두산위브아파트) (월곡제1동)', '02', '942', '0993', 17)
2021-08-18 17:41:03,733 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,734 INFO sqlalchemy.engine.base.Engine ('유창어린이집', '신순자', '서울특별시 강서구 우장산로2길 21-22 ,101동 103호(내발산동, 신세계5차) (우장산동)', '02', '2663', '2153', 4)
2021-08-18 17:41:03,735 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,735 INFO sqlalchemy.engine.base.Engine ('솔비어린이집', '김정남', '서울특별시 양천구 목동중앙남로7길 12 ,(목동) (목4동)', '02', '2651', '0307', 19)
2021-08-18 17:41:03,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,737 INFO sqlalchemy.engine.base.Engine ('리틀엔젤어린이집', '최성수', '서울특별시 도봉구 도봉로136길 28 ,520동 101호(창동, 북한산아이파크아파트) (창제5동)', '02', '908', '3404', 10)
2021-08-18 17:41:03,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,739 INFO sqlalchemy.engine.base.Engine ('예찬어린이집', '안영진', '서울특별시 강북구 도봉로96길 43 ,(번동) (번1동)', '02', '997', '7584', 3)
2021-08-18 17:41:03,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,741 INFO sqlalchemy.engine.base.Engine ('하이츠어린이집', '윤은영', '서울특별시 성북구 아리랑로19길 56 ,(정릉동) (정릉제2동)', '02', '6326', '7942', 17)
2021-08-18 17:41:03,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,744 INFO sqlalchemy.engine.base.Engine ('바다의별어린이집', '이민지', '서울특별시 동대문구 한천로 248 ,108동 104호(휘경동, 주공아파트) (휘경제2동)', '02', '2212', '5096', 11)
2021-08-18 17:41:03,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,745 INFO sqlalchemy.engine.base.Engine ('L캐슬어린이집', '박민지', '서울특별시 양천구 목동중앙북로 38 ,목동롯데캐슬위너지원센터1층 (목동) (목3동)', '02', '2644', '1061', 19)
2021-08-18 17:41:03,746 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,747 INFO sqlalchemy.engine.base.Engine ('경찰청어린이집', '강성호', '서울특별시 서대문구 통일로 97 ,(미근동) (충현동)', '02', '363', '9675', 14)
2021-08-18 17:41:03,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,748 INFO sqlalchemy.engine.base.Engine ('부렴어린이집', '이민재', '서울특별시 송파구 도곡로64길 7-15 ,부렴어린이집 (잠실동) (잠실본동)', '02', '424', '2459', 18)
2021-08-18 17:41:03,749 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,750 INFO sqlalchemy.engine.base.Engine ('사무엘어린이집', '안정자', '서울특별시 양천구 남부순환로54길 9 ,신월동성결교회 (신월동) (신월3동)', '02', '2605', '1397', 19)
2021-08-18 17:41:03,751 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,752 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '최영길', '서울특별시 은평구 불광로2길 16 (불광제1동)', '02', '353', '3202', 22)
2021-08-18 17:41:03,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,755 INFO sqlalchemy.engine.base.Engine ('구립시흥4동어린이집', '서병철', '서울특별시 금천구 독산로36길 14 ,(시흥동) (시흥제4동)', '02', '806', '7959', 8)
2021-08-18 17:41:03,756 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,757 INFO sqlalchemy.engine.base.Engine ('은행나무어린이집', '안준혁', '서울특별시 성북구 삼양로9길 14-17 (길음제1동)', '02', '945', '4567', 17)
2021-08-18 17:41:03,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,759 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '장유진', '서울특별시 금천구 독산로80길 11-10 (독산제4동)', '02', '861', '1656', 8)
2021-08-18 17:41:03,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,761 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '장은영', '서울특별시 양천구 목동중앙남로16다길 14-8 ,1층 (목3동)', '02', '2642', '5153', 19)
2021-08-18 17:41:03,762 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,762 INFO sqlalchemy.engine.base.Engine ('펠리스어린이집', '이성민', '서울특별시 영등포구 대림로31가길 16 ,(대림동) (대림제3동)', '02', '849', '3027', 20)
2021-08-18 17:41:03,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,764 INFO sqlalchemy.engine.base.Engine ('썬에듀스쿨어린이집', '조준영', '서울특별시 강서구 곰달래로15길 32 ,(화곡동) (화곡제1동)', '02', '2694', '1300', 4)
2021-08-18 17:41:03,765 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,765 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '임영일', '서울특별시 금천구 한내로 69-54 ,1402동 103호(독산동, 주공14단지아파트) (독산제1동)', '02', '896', '9824', 8)
2021-08-18 17:41:03,767 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,768 INFO sqlalchemy.engine.base.Engine ('드림키즈어린이집', '권현정', '서울특별시 양천구 월정로15길 16 ,1층 (신월1동)', '02', '2607', '8628', 19)
2021-08-18 17:41:03,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,772 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '임도현', '서울특별시 송파구 양재대로71길 42-19 ,101호(방이동, 유성빌라) (방이1동)', '02', '422', '7177', 18)
2021-08-18 17:41:03,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,774 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '임예준', '서울특별시 송파구 백제고분로42길 5 ,송파여성문화회관 2층 행복한 어린이집 (송파동) (송파1동)', '02', '417', '0891', 18)
2021-08-18 17:41:03,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,775 INFO sqlalchemy.engine.base.Engine ('또래친구어린이집', '신정남', '서울특별시 구로구 오리로20길 39 ,(1~3층) (수궁동)', '02', '3666', '3434', 7)
2021-08-18 17:41:03,776 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,777 INFO sqlalchemy.engine.base.Engine ('레드로빈어린이집', '오지은', '서울특별시 강서구 공항대로67길 29-12 ,세왕네스트빌 102호 레드로빈어린이집 (염창동) (염창동)', '02', '6737', '0110', 4)
2021-08-18 17:41:03,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,778 INFO sqlalchemy.engine.base.Engine ('배꼽어린이집', '안영길', '서울특별시 강동구 천중로39길 105 ,(천호동 39-15) (천호제1동)', '02', '472', '0494', 2)
2021-08-18 17:41:03,779 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,779 INFO sqlalchemy.engine.base.Engine ('큰별어린이집', '오미영', '서울특별시 구로구 구로동로22길 88-1 ,101호.102호 (구로제4동)', '02', '868', '3531', 7)
2021-08-18 17:41:03,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,782 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '황예은', '서울특별시 도봉구 마들로 684-9 (도봉제2동)', '02', '3494', '0304', 10)
2021-08-18 17:41:03,783 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,783 INFO sqlalchemy.engine.base.Engine ('무지개동산어린이집', '임병철', '서울특별시 은평구 역말로 7 ,B동 (역촌동) (역촌동)', '02', '382', '5945', 22)
2021-08-18 17:41:03,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,786 INFO sqlalchemy.engine.base.Engine ('반디어린이집', '전성호', '서울특별시 송파구 잠실로 88 ,124동 104호(잠실동, 레이크팰리스아파트) (잠실3동)', '02', '425', '1658', 18)
2021-08-18 17:41:03,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,787 INFO sqlalchemy.engine.base.Engine ('리틀영재어린이집', '장민지', '서울특별시 도봉구 시루봉로 107 ,2동 106호(방학동, 신동아1차아파트) (방학제3동)', '02', '3494', '3535', 10)
2021-08-18 17:41:03,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,789 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '장경자', '서울특별시 양천구 곰달래로11길 21 ,102동 104호(신월동, 길훈엔트런스빌) (신월1동)', '02', '2697', '3629', 19)
2021-08-18 17:41:03,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,791 INFO sqlalchemy.engine.base.Engine ('삼성이화어린이집', '권정호', '서울특별시 서대문구 수색로6길 43 ,삼성래미안2차아파트 (남가좌동) (남가좌제1동)', '02', '308', '2215', 14)
2021-08-18 17:41:03,792 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,792 INFO sqlalchemy.engine.base.Engine ('청운창의어린이집', '윤병철', '서울특별시 성북구 종암로 98-9 (종암동)', '02', '909', '6327', 17)
2021-08-18 17:41:03,794 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,794 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '류민석', '서울특별시 노원구 월계로45길 21 ,109동 102호(월계동, 롯데캐슬아파트) (월계2동)', '02', '994', '1023', 9)
2021-08-18 17:41:03,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,796 INFO sqlalchemy.engine.base.Engine ('연신아트어린이집', '최정식', '서울특별시 은평구 연서로37길 49 ,(불광동) (불광제2동)', '02', '357', '2030', 22)
2021-08-18 17:41:03,796 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,797 INFO sqlalchemy.engine.base.Engine ('발산 빅스맘 어린이집', '박병철', '서울특별시 강서구 우장산로2길 57 ,(내발산동) (우장산동)', '02', '3664', '8510', 4)
2021-08-18 17:41:03,798 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,799 INFO sqlalchemy.engine.base.Engine ('선린어린이집', '전준영', '서울특별시 광진구 뚝섬로43길 14 ,(자양동) (자양제1동)', '02', '447', '8093', 6)
2021-08-18 17:41:03,801 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,802 INFO sqlalchemy.engine.base.Engine ('조광어린이집', '권영숙', '서울특별시 성북구 장위로32길 6-10 (장위제1동)', '02', '913', '2567', 17)
2021-08-18 17:41:03,803 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,804 INFO sqlalchemy.engine.base.Engine ('백호어린이집', '황민서', '서울특별시 구로구 신도림로9길 24 ,(신도림동) (신도림동)', '02', '2676', '3569', 7)
2021-08-18 17:41:03,805 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,805 INFO sqlalchemy.engine.base.Engine ('토란어린이집', '조준영', '서울특별시 강서구 방화대로34길 113 ,101동 105호(방화동, 방화삼성아파트) (방화제1동)', '02', '2649', '6980', 4)
2021-08-18 17:41:03,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,818 INFO sqlalchemy.engine.base.Engine ('아기샘어린이집', '최영길', '서울특별시 관악구 신림로29길 3-20 ,107동 104호(신림동, 신림현대아파트) (서림동)', '02', '876', '1301', 5)
2021-08-18 17:41:03,820 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,820 INFO sqlalchemy.engine.base.Engine ('아이누리어린이집', '박영철', '서울특별시 노원구 동일로198길 24 ,, 101동 101호(공릉1동 우성아파트) (공릉1동)', '02', '6404', '0505', 9)
2021-08-18 17:41:03,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,822 INFO sqlalchemy.engine.base.Engine ('봄햇살어린이집', '최정웅', '서울특별시 강동구 천중로40길 49 ,(길동 380-2) (길동)', '02', '477', '4523', 2)
2021-08-18 17:41:03,824 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,825 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '신성호', '서울특별시 구로구 오리로 1197 ,114동 101호(오류동, 금강수목원아파트) (오류제2동)', '02', '2687', '2228', 7)
2021-08-18 17:41:03,826 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,827 INFO sqlalchemy.engine.base.Engine ('꿈씨어린이집', '임정남', '서울특별시 노원구 상계로9나길 25 ,(상계2동 436-11) (상계2동)', '02', '937', '3446', 9)
2021-08-18 17:41:03,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,829 INFO sqlalchemy.engine.base.Engine ('나섬어린이집', '강지원', '서울특별시 광진구 광장로1나길 4 ,107호(광장동, 동부빌라) (광장동)', '02', '6497', '0033', 6)
2021-08-18 17:41:03,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,831 INFO sqlalchemy.engine.base.Engine ('상떼빌키즈어린이집', '전정수', '서울특별시 동작구 신대방1가길 38 ,동작 상떼빌아파트 101동 상떼빌어린이집 (신대방동) (신대방제1동)', '02', '3289', '1246', 12)
2021-08-18 17:41:03,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,833 INFO sqlalchemy.engine.base.Engine ('SBS어린이집', '황준영', '서울특별시 양천구 국회대로 214 ,1~2층 (신정동) (신정4동)', '02', '2651', '2394', 19)
2021-08-18 17:41:03,834 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,837 INFO sqlalchemy.engine.base.Engine ('다예린어린이집', '강민서', '서울특별시 광진구 광장로 65 ,(광장동) (광장동)', '02', '455', '2366', 6)
2021-08-18 17:41:03,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,839 INFO sqlalchemy.engine.base.Engine ('해피용마어린이집', '오지혜', '서울특별시 광진구 용마산로12길 5 ,(중곡동) (중곡제4동)', '02', '453', '7938', 6)
2021-08-18 17:41:03,841 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,842 INFO sqlalchemy.engine.base.Engine ('위브어린이집', '권준호', '서울특별시 구로구 디지털로31길 85 ,두산위브아파트 내 보육시설 (구로동) (구로제3동)', '02', '864', '9191', 7)
2021-08-18 17:41:03,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,844 INFO sqlalchemy.engine.base.Engine ('꿈이있는 어린이집', '전서현', '서울특별시 은평구 갈현로4길 23-1 ,태경맨션 101 (역촌동) (역촌동)', '02', '382', '6575', 22)
2021-08-18 17:41:03,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,846 INFO sqlalchemy.engine.base.Engine ('청구 어린이집', '박준혁', '서울특별시 영등포구 도영로7길 5 ,101동 112호(도림동, 도림청구아파트) (도림동)', '02', '849', '8859', 20)
2021-08-18 17:41:03,846 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,847 INFO sqlalchemy.engine.base.Engine ('코오롱미소천사어린이집', '박서현', '서울특별시 영등포구 도영로 2-5 ,102동 102호(대림동, 대림코오롱아파트) (대림제3동)', '02', '843', '3215', 20)
2021-08-18 17:41:03,849 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,849 INFO sqlalchemy.engine.base.Engine ('명지어린이집', '장준서', '서울특별시 양천구 곰달래로9길 72 ,(신월동) (신월1동)', '02', '2601', '7005', 19)
2021-08-18 17:41:03,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,851 INFO sqlalchemy.engine.base.Engine ('동아개구쟁이어린이집', '송혜진', '서울특별시 동대문구 한천로11길 10-1 ,104동 103호(답십리동, 동아아파트) (답십리제2동)', '02', '2217', '1233', 11)
2021-08-18 17:41:03,852 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,853 INFO sqlalchemy.engine.base.Engine ('월계숲속어린이집', '전영진', '서울특별시 노원구 월계로44나길 31-4 (월계1동)', '02', '943', '2446', 9)
2021-08-18 17:41:03,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,854 INFO sqlalchemy.engine.base.Engine ('이레삐아제어린이집', '장예준', '서울특별시 노원구 섬밭로 209 ,11동 109호(하계동, 벽산) (하계2동)', '02', '974', '9172', 9)
2021-08-18 17:41:03,855 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,856 INFO sqlalchemy.engine.base.Engine ('미소천사어린이집', '오은경', '서울특별시 금천구 금하로14길 51 ,(시흥동) (시흥제1동)', '02', '895', '9004', 8)
2021-08-18 17:41:03,857 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,857 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '윤수빈', '서울특별시 송파구 송이로 88 ,5동 111호(가락동, 대림아파트) (가락본동)', '02', '400', '6214', 18)
2021-08-18 17:41:03,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,859 INFO sqlalchemy.engine.base.Engine ('꿈꾸는새싹어린이집', '한영진', '서울특별시 관악구 남현길 91 ,103동 102호(남현동, 우림루미아트) [남현동] (남현동)', '02', '535', '9799', 5)
2021-08-18 17:41:03,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,863 INFO sqlalchemy.engine.base.Engine ('예원어린이집', '전지영', '서울특별시 강북구 오현로9길 27 ,(미아동) (송중동)', '02', '980', '9384', 3)
2021-08-18 17:41:03,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,865 INFO sqlalchemy.engine.base.Engine ('구산클애들어린이집', '장성호', '서울특별시 은평구 갈현로17가길 5-1 (구산동)', '02', '356', '2964', 22)
2021-08-18 17:41:03,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,867 INFO sqlalchemy.engine.base.Engine ('하나연어린이집', '강혜진', '서울특별시 은평구 녹번로 29-2 (녹번동)', '02', '388', '3324', 22)
2021-08-18 17:41:03,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,868 INFO sqlalchemy.engine.base.Engine ('뉴한가람어린이집', '최지은', '서울특별시 송파구 성내천로 162 ,(마천동) (마천2동)', '02', '443', '0138', 18)
2021-08-18 17:41:03,870 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,870 INFO sqlalchemy.engine.base.Engine ('은평감리교회방과후어린이집', '김영길', '서울특별시 은평구 응암로 376 ,(녹번동) (녹번동)', '070', '7759', '8545', 22)
2021-08-18 17:41:03,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,872 INFO sqlalchemy.engine.base.Engine ('SKT행복날개어린이집', '오영자', '서울특별시 중구 을지로2가 을지로 65 ,SK-T타워 3층 (명동)', '02', '6100', '0115', 24)
2021-08-18 17:41:03,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,874 INFO sqlalchemy.engine.base.Engine ('더크는킨더앤어린이집', '송민석', '서울특별시 동작구 성대로31길 2 ,서울시 동작구 성대로 31길 2 (상도동) (상도제4동)', '02', '823', '0733', 12)
2021-08-18 17:41:03,874 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,875 INFO sqlalchemy.engine.base.Engine ('숲속반디어린이집', '안경숙', '서울특별시 성북구 오패산로 90 ,래미안 월곡 아파트 관리동 숲속반디어린이집 (하월곡동) (월곡제1동)', '02', '909', '1322', 17)
2021-08-18 17:41:03,876 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,877 INFO sqlalchemy.engine.base.Engine ('꿈밭어린이집', '이영길', '서울특별시 노원구 덕릉로79길 23 ,102동 102호(중계동, 염광아파트) (중계4동)', '02', '3391', '8391', 9)
2021-08-18 17:41:03,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,878 INFO sqlalchemy.engine.base.Engine ('아이나무어린이집', '서민지', '서울특별시 노원구 마들로 111 ,24동 103호(월계동, 삼호) (월계3동)', '02', '973', '8625', 9)
2021-08-18 17:41:03,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,879 INFO sqlalchemy.engine.base.Engine ('영재사관어린이집', '신은경', '서울특별시 중랑구 동일로95나길 12-8 ,(면목동) (면목제5동)', '02', '432', '2344', 25)
2021-08-18 17:41:03,881 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,882 INFO sqlalchemy.engine.base.Engine ('무역센터 꿈나무 어린이집', '정건우', '서울특별시 강남구 영동대로 513 ,컨벤션센터 2층 (삼성1동)', '02', '6000', '8355', 1)
2021-08-18 17:41:03,883 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,885 INFO sqlalchemy.engine.base.Engine ('예원사랑어린이집', '오성수', '서울특별시 노원구 덕릉로73길 28 ,202동 101호(중계동, 양지대림아파트) (중계1동)', '02', '6224', '3784', 9)
2021-08-18 17:41:03,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,888 INFO sqlalchemy.engine.base.Engine ('구립 푸른빛어린이집', '류영철', '서울특별시 은평구 진흥로16길 7-6 (녹번동)', '02', '388', '4060', 22)
2021-08-18 17:41:03,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,890 INFO sqlalchemy.engine.base.Engine ('세종어린이집', '임준영', '서울특별시 강동구 천호옛6길 3 ,(성내동 119-14) (성내제2동)', '02', '487', '0746', 2)
2021-08-18 17:41:03,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,892 INFO sqlalchemy.engine.base.Engine ('월곡무지개어린이집', '황은영', '서울특별시 성북구 화랑로7길 8 ,(하월곡동) (월곡제2동)', '02', '914', '6673', 17)
2021-08-18 17:41:03,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,894 INFO sqlalchemy.engine.base.Engine ('돈암이수어린이집', '임영길', '서울특별시 성북구 북악산로 844 ,102동 102호(돈암동, 돈암이수브라운스톤아파트) (돈암제2동)', '02', '6221', '5857', 17)
2021-08-18 17:41:03,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,896 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '안예은', '서울특별시 금천구 시흥대로130길 24-4 (독산제4동)', '02', '859', '7786', 8)
2021-08-18 17:41:03,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,897 INFO sqlalchemy.engine.base.Engine ('곤지곤지어린이집', '황준호', '서울특별시 은평구 연서로3길 31-11 ,101호 (역촌동)', '02', '382', '9220', 22)
2021-08-18 17:41:03,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,903 INFO sqlalchemy.engine.base.Engine ('보람통통어린이집', '정정운', '서울특별시 양천구 남부순환로67길 15 ,101동 101호(신월동, 보람쉬움1차아파트) (신월4동)', '02', '2696', '7040', 19)
2021-08-18 17:41:03,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,906 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '윤준영', '서울특별시 강동구 고덕로24가길 19 ,(암사동 453-17) (암사제1동)', '02', '441', '1050', 2)
2021-08-18 17:41:03,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,908 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '한은영', '서울특별시 도봉구 도봉로118길 28-4 ,(창동 658-25) 사과나무 어린이집 (창제1동)', '02', '904', '0301', 10)
2021-08-18 17:41:03,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,910 INFO sqlalchemy.engine.base.Engine ('새가산어린이집', '한지영', '서울특별시 금천구 시흥대로153길 85 ,(가산동) (가산동)', '02', '6012', '4939', 8)
2021-08-18 17:41:03,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,911 INFO sqlalchemy.engine.base.Engine ('예닮누리 어린이집', '정민서', '서울특별시 도봉구 도봉로110다길 51 ,112동 101호(창동, 태영데시앙) (창제2동)', '02', '999', '1180', 10)
2021-08-18 17:41:03,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,914 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '정영길', '서울특별시 노원구 섬밭로 265 ,14동 108호(중계동, 상아아파트) (중계2.3동)', '02', '973', '2229', 9)
2021-08-18 17:41:03,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,915 INFO sqlalchemy.engine.base.Engine ('신나게노는어린이집', '강서현', '서울특별시 용산구 이촌로2가길 122 ,103동105호 (이촌제2동)', '02', '6354', '1105', 21)
2021-08-18 17:41:03,916 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,917 INFO sqlalchemy.engine.base.Engine ('예뜨랑어린이집', '조도현', '서울특별시 양천구 곰달래로2길 31 ,101동 106호(신월동, 방원예뜨랑아파트) (신월1동)', '02', '2691', '0179', 19)
2021-08-18 17:41:03,917 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,918 INFO sqlalchemy.engine.base.Engine ('은혜큰어린이집', '장정수', '서울특별시 광진구 천호대로124길 122 ,(능동) (능동)', '02', '455', '3595', 6)
2021-08-18 17:41:03,919 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,919 INFO sqlalchemy.engine.base.Engine ('토브키즈어린이집', '박미경', '서울특별시 강서구 수명로1길 16 ,마곡택지개발지구 753번지 수명산파크 407-102 (발산제1동)', '02', '2667', '7566', 4)
2021-08-18 17:41:03,921 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,921 INFO sqlalchemy.engine.base.Engine ('해랑어린이집', '송성수', '서울특별시 관악구 난곡로 55 ,216동 101호(신림동, 관악산휴먼시아아파트) [난향동] (난향동)', '02', '6264', '2116', 5)

2021-08-18 17:41:03,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,924 INFO sqlalchemy.engine.base.Engine ('i보라어린이집', '류지은', '서울특별시 노원구 공릉로34길 38 ,1019동 104호(공릉동, 태강) (공릉2동)', '02', '6231', '3409', 9)
2021-08-18 17:41:03,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,929 INFO sqlalchemy.engine.base.Engine ('늘평화어린이집', '안정수', '서울특별시 광진구 능동로51길 17 ,(중곡동) (중곡제3동)', '02', '499', '7758', 6)
2021-08-18 17:41:03,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,930 INFO sqlalchemy.engine.base.Engine ('새벽어린이집', '황지원', '서울특별시 광진구 영화사로 53 ,(중곡동) (중곡제4동)', '02', '458', '5279', 6)
2021-08-18 17:41:03,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,932 INFO sqlalchemy.engine.base.Engine ('아이앤아이어린이집', '임진호', '서울특별시 노원구 마들로 111 ,17동 103호(월계동, 미륭) (월계3동)', '02', '975', '3396', 9)
2021-08-18 17:41:03,934 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,934 INFO sqlalchemy.engine.base.Engine ('유린원광종합사회복지관방과후교실어린이집', '강서현', '서울특별시 중랑구 신내로 56 ,2층(신내동) (신내1동)', '070', '7011', '1042', 25)
2021-08-18 17:41:03,936 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,937 INFO sqlalchemy.engine.base.Engine ('작은꼬마어린이집', '강준호', '서울특별시 노원구 동일로213길 21 ,107동 103호(상계동, 상계주공1단지아파트) (상계6.7동)', '02', '934', '5942', 9)
2021-08-18 17:41:03,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,938 INFO sqlalchemy.engine.base.Engine ('푸른나래어린이집', '한종수', '서울특별시 노원구 한글비석로 480 ,209동 106호(상계동, 보람아파트) (상계9동)', '02', '3392', '3211', 9)
2021-08-18 17:41:03,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,940 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '김성호', '서울특별시 노원구 덕릉로 780 ,104동 101호(상계동, 동아불암) (상계3.4동)', '02', '938', '2287', 9)
2021-08-18 17:41:03,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,942 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '정정식', '서울특별시 송파구 석촌호수로18길 22 ,은하수빌라 105호 (석촌동) (석촌동)', '02', '3432', '7979', 18)
2021-08-18 17:41:03,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,944 INFO sqlalchemy.engine.base.Engine ('라인어린이집', '조정웅', '서울특별시 강동구 천중로50길 48-12 ,101동 110호(길동, 라인아파트) (길동)', '02', '484', '7978', 2)
2021-08-18 17:41:03,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,946 INFO sqlalchemy.engine.base.Engine ('코코어린이집', '정영환', '서울특별시 양천구 목동로 186 ,710동 102호(목동, 목동신시가지7단지아파트) (목1동)', '02', '2647', '8778', 19)
2021-08-18 17:41:03,947 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,950 INFO sqlalchemy.engine.base.Engine ('채움어린이집', '한지훈', '서울특별시 노원구 월계로45가길 94 ,403동 101호(월계동, 청백) (월계2동)', '02', '905', '9501', 9)
2021-08-18 17:41:03,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,952 INFO sqlalchemy.engine.base.Engine ('해와달어린이집', '권지영', '서울특별시 동작구 성대로16길 67-6 (상도제4동)', '02', '824', '3753', 12)
2021-08-18 17:41:03,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,954 INFO sqlalchemy.engine.base.Engine ('늘해랑어린이집', '전진호', '서울특별시 중랑구 상봉로26길 32 ,늘해랑어린이집 (망우본동)', '02', '437', '3232', 25)
2021-08-18 17:41:03,955 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,955 INFO sqlalchemy.engine.base.Engine ('해아뜰어린이집', '최영식', '서울특별시 동작구 장승배기로3길 1 ,(상도동) (상도제2동)', '02', '821', '6927', 12)
2021-08-18 17:41:03,957 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,958 INFO sqlalchemy.engine.base.Engine ('서초이화어린이집', '박영식', '서울특별시 서초구 방배로39길 42 ,(방배동) (방배본동)', '02', '593', '9779', 15)
2021-08-18 17:41:03,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,959 INFO sqlalchemy.engine.base.Engine ('사랑받는어린이집', '송예준', '서울특별시 양천구 목동서로 280 ,808동 104호(신정동, 신시가지8단지아파트) (신정6동)', '02', '2651', '3231', 19)
2021-08-18 17:41:03,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,961 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '류성호', '서울특별시 강북구 삼양로54다길 14 ,(미아동312-22 101호) (송천동)', '02', '982', '5563', 3)
2021-08-18 17:41:03,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,963 INFO sqlalchemy.engine.base.Engine ('동부영재어린이집', '박도현', '서울특별시 송파구 송파대로37길 29 ,103동 106호(가락동, 송파동부쎈트레빌) (가락1동)', '070', '7550', '2944', 18)
2021-08-18 17:41:03,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,966 INFO sqlalchemy.engine.base.Engine ('별초롱 어린이집', '오지영', '서울특별시 성북구 길음로 16 ,래미안3차 관리동 1층 (길음제1동)', '02', '915', '7769', 17)
2021-08-18 17:41:03,967 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,969 INFO sqlalchemy.engine.base.Engine ('123어린이집', '임예준', '서울특별시 관악구 성현로 80 ,123동 102호(봉천동, 관악드림타운) [성현동] (성현동)', '02', '887', '2233', 5)
2021-08-18 17:41:03,970 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,971 INFO sqlalchemy.engine.base.Engine ('주손어린이집', '장경회', '서울특별시 노원구 한글비석로8길 41 ,603동 104호(중계동, 주공6단지아파트) (중계본동)', '02', '930', '8551', 9)
2021-08-18 17:41:03,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,972 INFO sqlalchemy.engine.base.Engine ('리틀기쁜샘어린이집', '강은정', '서울특별시 마포구 독막로 266 ,105동 101호(대흥동, 마포태영아파트) (용강동)', '070', '7631', '2025', 13)
2021-08-18 17:41:03,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,974 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '장서현', '서울특별시 중랑구 답십리로75길 73 ,경남아너스빌아파트 106동 102호 (면목동) (면목제4동)', '02', '435', '5788', 25)
2021-08-18 17:41:03,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:03,976 INFO sqlalchemy.engine.base.Engine ('웃음가득해피어린이집', '류준영', '서울특별시 도봉구 우이천로20길 6 ,101동 109호(창동, 수산트리플아파트) (창제2동)', '02', '6012', '9461', 10)
2021-08-18 17:41:03,977 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,978 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '송정운', '서울특별시 영등포구 63로 45 ,11동 12호(여의도동, 여의도시범아파트) (여의동)', '02', '782', '7809', 20)
2021-08-18 17:41:03,979 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,980 INFO sqlalchemy.engine.base.Engine ('오르다킨더가든어린이집', '윤준서', '서울특별시 은평구 서오릉로8길 12 ,(대조동) (대조동)', '02', '359', '5607', 22)
2021-08-18 17:41:03,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,984 INFO sqlalchemy.engine.base.Engine ('해아뜰숲어린이집', '강성민', '서울특별시 은평구 통일로89길 18-26 (갈현제1동)', '02', '353', '5050', 22)
2021-08-18 17:41:03,984 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,985 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '이상훈', '서울특별시 서초구 잠원로 37-48 ,203동 104호(잠원동,신반포4차 아파트) (반포3동)', '02', '535', '2624', 15)
2021-08-18 17:41:03,986 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,986 INFO sqlalchemy.engine.base.Engine ('양지1어린이집', '류준영', '서울특별시 서초구 샘마을길 73 ,내곡동, 양지1어린이집 (내곡동)', '02', '577', '2091', 15)
2021-08-18 17:41:03,988 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,989 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '황건우', '서울특별시 동대문구 장한로28가길 11 ,SM해그린아파트 단지동 (장안동) (장안제2동)', '02', '2242', '6185', 11)
2021-08-18 17:41:03,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,991 INFO sqlalchemy.engine.base.Engine ('혜시의사과나무어린이집', '한영일', '서울특별시 강서구 강서로45길 37 ,(화곡동) (화곡제3동)', '02', '2603', '2888', 4)
2021-08-18 17:41:03,992 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,994 INFO sqlalchemy.engine.base.Engine ('리틀나라어린이집', '황은영', '서울특별시 노원구 마들로 111 ,28동 101호(월계동, 삼호) (월계3동)', '02', '974', '9555', 9)
2021-08-18 17:41:03,994 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,995 INFO sqlalchemy.engine.base.Engine ('싱글벙글어린이집', '권은영', '서울특별시 관악구 청룡길 78 ,103-101(봉천동,서울대입구아이원) [청룡동] (청룡동)', '02', '888', '7367', 5)
2021-08-18 17:41:03,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,997 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '최민재', '서울특별시 성북구 길음로 16 ,611동 104호(길음동, 래미안길음3차아파트) (길음제1동)', '02', '6221', '0098', 17)
2021-08-18 17:41:03,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:03,999 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '장현준', '서울특별시 서대문구 연희로35길 13-10 (연희동)', '02', '326', '0340', 14)
2021-08-18 17:41:04,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,002 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '오준호', '서울특별시 강서구 강서로35길 47-5 ,(화곡3동 1047-6) 허벌빌 101호 (화곡제3동)', '02', '2699', '1045', 4)
2021-08-18 17:41:04,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,004 INFO sqlalchemy.engine.base.Engine ('린아어린이집', '박경숙', '서울특별시 동작구 상도로53길 70 ,상도SH빌 관리동1층 (상도동) (상도제1동)', '02', '815', '2535', 12)
2021-08-18 17:41:04,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,006 INFO sqlalchemy.engine.base.Engine ('공릉사임당어린이집', '신정남', '서울특별시 노원구 공릉로34길 38 ,1008동 101호(공릉동,태강) (공릉2동)', '02', '979', '3520', 9)
2021-08-18 17:41:04,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,008 INFO sqlalchemy.engine.base.Engine ('루하마어린이집', '장정수', '서울특별시 강동구 구천면로53가길 1 ,(암사동 478-53) (암사제1동)', '02', '3013', '8255', 2)
2021-08-18 17:41:04,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,009 INFO sqlalchemy.engine.base.Engine ('포르테몬테소리어린이집', '안영자', '서울특별시 동대문구 장한로12길 76-1 (장안제1동)', '02', '2247', '1263', 11)
2021-08-18 17:41:04,010 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,011 INFO sqlalchemy.engine.base.Engine ('베베랑어린이집', '임상철', '서울특별시 노원구 노원로 564 ,상계주공10단지 1005동 105호 (상계8동)', '02', '3392', '0929', 9)
2021-08-18 17:41:04,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,013 INFO sqlalchemy.engine.base.Engine ('명화어린이집', '박예은', '서울특별시 도봉구 시루봉로 107 ,7동 103호(방학동, 신동아1차아파트) (방학제3동)', '02', '3491', '3221', 10)
2021-08-18 17:41:04,015 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,015 INFO sqlalchemy.engine.base.Engine ('두산피노키오어린이집', '강지영', '서울특별시 노원구 공릉로 126 ,101동 104호(공릉동, 두산힐스빌아파트) (공릉2동)', '02', '6229', '0968', 9)
2021-08-18 17:41:04,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,017 INFO sqlalchemy.engine.base.Engine ('열린창의어린이집', '신영숙', '서울특별시 중랑구 중랑천로 324 ,(묵동) (묵제2동)', '02', '976', '9834', 25)
2021-08-18 17:41:04,020 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,020 INFO sqlalchemy.engine.base.Engine ('리틀클애들어린이집', '류영철', '서울특별시 은평구 역말로4길 18 ,103동 101호(역촌동, 부호아파트) (역촌동)', '02', '359', '5658', 22)
2021-08-18 17:41:04,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,022 INFO sqlalchemy.engine.base.Engine ('숲속나라어린이집', '권준혁', '서울특별시 강서구 까치산로4길 64-6 ,(화곡동) (화곡본동)', '02', '2695', '1918', 4)
2021-08-18 17:41:04,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,025 INFO sqlalchemy.engine.base.Engine ('밝은마음어린이집', '한지민', '서울특별시 구로구 경인로35길 71 ,(고척동2773-59 1층 일부) (고척제2동)', '02', '2616', '2555', 7)
2021-08-18 17:41:04,026 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,027 INFO sqlalchemy.engine.base.Engine ('즐거운코뿔소어린이집', '강민석', '서울특별시 영등포구 양평동1가 문래북로 31 ,양평동1가 13-25 (양평제1동)', '02', '3667', '6686', 20)

2021-08-18 17:41:04,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,030 INFO sqlalchemy.engine.base.Engine ('SK꼬마숲어린이집', '장영진', '서울특별시 노원구 월계로42길 97 ,103동 102호(월계동,꿈의숲sk뷰) (월계1동)', '02', '917', '6725', 9)
2021-08-18 17:41:04,032 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,032 INFO sqlalchemy.engine.base.Engine ('동아어린이집', '조현정', '서울특별시 동대문구 한천로11길 10-1 ,동아아파트 단지내 유치원동 (답십리동) (답십리제2동)', '02', '2242', '8337', 11)
2021-08-18 17:41:04,034 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,035 INFO sqlalchemy.engine.base.Engine ('숲속몬테소리어린이집', '조지원', '서울특별시 서대문구 연희로31길 33 (연희동)', '02', '334', '3006', 14)
2021-08-18 17:41:04,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,037 INFO sqlalchemy.engine.base.Engine ('새롬어린이집', '장은정', '서울특별시 중랑구 면목로42길 22 ,(면목동) (면목제7동)', '02', '494', '7612', 25)
2021-08-18 17:41:04,038 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,039 INFO sqlalchemy.engine.base.Engine ('성신어린이집', '신순자', '서울특별시 노원구 섬밭로 190 ,613동 104호(하계동, 장미) (하계2동)', '02', '979', '3332', 9)
2021-08-18 17:41:04,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,042 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '한영자', '서울특별시 도봉구 시루봉로17길 20 ,(방학동) (방학제2동)', '02', '3493', '5004', 10)
2021-08-18 17:41:04,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,044 INFO sqlalchemy.engine.base.Engine ('해아띠스쿨어린이집', '임동현', '서울특별시 강서구 초록마을로6길 37-13 (화곡본동)', '02', '6085', '7772', 4)
2021-08-18 17:41:04,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,046 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '최정운', '서울특별시 송파구 백제고분로22길 15-15 (삼전동)', '02', '416', '3725', 18)
2021-08-18 17:41:04,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,048 INFO sqlalchemy.engine.base.Engine ('아가세상어린이집', '윤현준', '서울특별시 영등포구 도신로29길 28 ,214동 101호(영등포동, 영등포푸르지오2단지아파트) (영등포본동)', '02', '843', '2282', 20)
2021-08-18 17:41:04,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,050 INFO sqlalchemy.engine.base.Engine ('벽산어린이집', '한민재', '서울특별시 양천구 월정로9길 20 ,203동 107호(신월동, 양천벽산블루밍아파트) (신월4동)', '02', '2693', '3584', 19)
2021-08-18 17:41:04,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,052 INFO sqlalchemy.engine.base.Engine ('보내고싶은 어린이집', '안경숙', '서울특별시 마포구 월드컵로26길 57 ,이움아파트 102호 (성산동) (성산제1동)', '02', '336', '5254', 13)
2021-08-18 17:41:04,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,054 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '송정호', '서울특별시 은평구 서오릉로15길 15-4 (구산동)', '02', '357', '6445', 22)
2021-08-18 17:41:04,055 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,056 INFO sqlalchemy.engine.base.Engine ('상은어린이집', '김현준', '서울특별시 구로구 도림로12길 12 ,101호 (구로동) (구로제3동)', '02', '3281', '9687', 7)
2021-08-18 17:41:04,057 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,058 INFO sqlalchemy.engine.base.Engine ('휴먼시아어린이집', '한동현', '서울특별시 관악구 난곡로 55 ,201동 101호(신림동, 관악산휴먼시아2단지아파트) [난향동] (난향동)', '02', '3281', '7723', 5)
2021-08-18 17:41:04,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,059 INFO sqlalchemy.engine.base.Engine ('하나몬테소리어린이집', '이영일', '서울특별시 은평구 증산로17길 25-1 (신사제2동)', '02', '375', '1233', 22)
2021-08-18 17:41:04,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,061 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '김민석', '서울특별시 구로구 고척로 49 ,206동 104호(오류동, 동부골든아파트) (오류제1동)', '02', '2684', '4722', 7)
2021-08-18 17:41:04,061 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,062 INFO sqlalchemy.engine.base.Engine ('물빛어린이집', '황병철', '서울특별시 금천구 시흥대로40마길 23-3 ,(시흥5동) (시흥제5동)', '02', '802', '8748', 8)
2021-08-18 17:41:04,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,064 INFO sqlalchemy.engine.base.Engine ('해사랑어린이집', '이은경', '서울특별시 은평구 역말로9길 35 ,(대조동) (대조동)', '02', '383', '2238', 22)
2021-08-18 17:41:04,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,066 INFO sqlalchemy.engine.base.Engine ('금강햇살어린이집', '윤동현', '서울특별시 양천구 남부순환로64길 23 ,101동 110호(신월동, 금강아파트) (신월3동)', '02', '2606', '3008', 19)
2021-08-18 17:41:04,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,069 INFO sqlalchemy.engine.base.Engine ('꿈여울어린이집', '송영자', '서울특별시 관악구 은천로 93 ,207동 102호(봉천동, 벽산블루밍아파트) [은천동] (은천동)', '02', '889', '8893', 5)
2021-08-18 17:41:04,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,072 INFO sqlalchemy.engine.base.Engine ('아가야어린이집', '김지훈', '서울특별시 서초구 방배중앙로15길 22 ,1층 (방배동) (방배4동)', '02', '594', '3926', 15)
2021-08-18 17:41:04,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,074 INFO sqlalchemy.engine.base.Engine ('포도원어린이집', '조영진', '서울특별시 강서구 금낭화로23길 8 ,110동 103호(방화동, 동성아파트) (방화제3동)', '02', '6092', '2214', 4)
2021-08-18 17:41:04,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,077 INFO sqlalchemy.engine.base.Engine ('예닮뜰 어린이집', '전준호', '서울특별시 강북구 오현로 207 ,404동 108호(번동, 주공아파트) (번2동)', '02', '985', '9920', 3)
2021-08-18 17:41:04,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,079 INFO sqlalchemy.engine.base.Engine ('예쁜친구어린이집', '신영식', '서울특별시 관악구 난곡로 55 ,207동 101호(신림동, 관악산휴먼시아2단지아파트) (난향동)', '02', '6346', '5083', 5)
2021-08-18 17:41:04,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,081 INFO sqlalchemy.engine.base.Engine ('사랑모아어린이집', '정영길', '서울특별시 구로구 가마산로 87 ,103동 101호(한일유앤아이아파트) (구로제1동)', '02', '866', '6675', 7)
2021-08-18 17:41:04,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,083 INFO sqlalchemy.engine.base.Engine ('하늘꿈어린이집', '신준혁', '서울특별시 중랑구 용마산로86길 9-27 ,101동 102호(면목동, 신성미소지움아파트) (면목제3.8동)', '02', '2207', '5294', 25)
2021-08-18 17:41:04,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,084 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '송현준', '서울특별시 관악구 난곡로 55 ,219동 104호(신림동, 관악산휴먼시아2단지아파트) (난향동)', '02', '855', '7815', 5)
2021-08-18 17:41:04,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,086 INFO sqlalchemy.engine.base.Engine ('사랑가득어린이집', '전지훈', '서울특별시 도봉구 해등로 242-7 ,104동 103호(쌍문동, 성원아파트) (쌍문제4동)', '02', '902', '0677', 10)
2021-08-18 17:41:04,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,089 INFO sqlalchemy.engine.base.Engine ('우리누리 어린이집', '황영식', '서울특별시 강남구 테헤란로 114 ,국세종합상담센터 (역삼동) (역삼제1동)', '02', '556', '3331', 1)
2021-08-18 17:41:04,090 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,091 INFO sqlalchemy.engine.base.Engine ('리라어린이집', '신민재', '서울특별시 은평구 은평로21길 19-4 (녹번동)', '02', '383', '5363', 22)
2021-08-18 17:41:04,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,092 INFO sqlalchemy.engine.base.Engine ('코끼리어린이집', '오영일', '서울특별시 영등포구 가마산로61가길 14 ,(신길동) (신길제3동)', '02', '831', '2280', 20)
2021-08-18 17:41:04,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,098 INFO sqlalchemy.engine.base.Engine ('현강유아교육어린이집', '안지훈', '서울특별시 강서구 까치산로10길 57 ,(화곡동) (화곡본동)', '02', '2603', '5307', 4)
2021-08-18 17:41:04,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,102 INFO sqlalchemy.engine.base.Engine ('알곡방과후교실어린이집', '류준호', '서울특별시 관악구 난곡로24길 42 ,(난곡동) (신림동) (난곡동)', '02', '838', '8447', 5)
2021-08-18 17:41:04,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,104 INFO sqlalchemy.engine.base.Engine ('역삼푸르지오어린이집', '박지원', '서울특별시 강남구 언주로 332 ,역삼푸르지오 관리동 (역삼제2동)', '02', '501', '0030', 1)
2021-08-18 17:41:04,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,107 INFO sqlalchemy.engine.base.Engine ('개봉사랑나무어린이집', '임준혁', '서울특별시 구로구 개봉로2길 133-15 ,110동 102호(개봉동, 개봉동아이파크아파트) (개봉제2동)', '02', '2685', '5146', 7)
2021-08-18 17:41:04,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,109 INFO sqlalchemy.engine.base.Engine ('뽀뽀어린이집', '장정수', '서울특별시 구로구 신도림로 16 ,504동 103호(신도림동, 대림1차아파트) (신도림동)', '02', '2676', '4875', 7)
2021-08-18 17:41:04,111 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,112 INFO sqlalchemy.engine.base.Engine ('삼육어린이집', '전준호', '서울특별시 강남구 선릉로69길 20 ,105동 104호(역삼동, E편한세상) (역삼제2동)', '02', '566', '1369', 1)
2021-08-18 17:41:04,113 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,114 INFO sqlalchemy.engine.base.Engine ('예원아트어린이집', '최서연', '서울특별시 양천구 목동중앙남로4길 16 ,(목동) (목4동)', '02', '2642', '9626', 19)
2021-08-18 17:41:04,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,116 INFO sqlalchemy.engine.base.Engine ('LG전자 어린이집', '송미숙', '서울특별시 금천구 두산로 79 ,메이시티 1층 (독산동) (독산제1동)', '02', '830', '2660', 8)
2021-08-18 17:41:04,117 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,117 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '조종수', '서울특별시 양천구 신월로 99 ,8동 101호신월동신월시영아파트 (신월7동)', '02', '2695', '4025', 19)
2021-08-18 17:41:04,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,121 INFO sqlalchemy.engine.base.Engine ('수성어린이집', '윤은영', '서울특별시 강서구 가로공원로84길 27 ,(화곡동) (화곡제1동)', '02', '2699', '1322', 4)
2021-08-18 17:41:04,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,124 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '권정순', '서울특별시 강서구 양천로6길 28 ,1206동 101호(방화동, 방화도시개발공사아파트) (방화제2동)', '02', '2661', '4582', 4)
2021-08-18 17:41:04,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,125 INFO sqlalchemy.engine.base.Engine ('기쁜숲어린이집', '오성수', '서울특별시 성북구 오패산로 90 ,113동 101호(하월곡동, 삼성래미안아파트) (월곡제1동)', '02', '6221', '3863', 17)
2021-08-18 17:41:04,127 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,127 INFO sqlalchemy.engine.base.Engine ('청담어린이집', '류영철', '서울특별시 강남구 도산대로56길 14 ,(청담동) (청담동)', '02', '511', '1734', 1)
2021-08-18 17:41:04,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,129 INFO sqlalchemy.engine.base.Engine ('리틀디모데어린이집', '조지영', '서울특별시 영등포구 영등포로86길 19 ,(신길동) (신길제7동)', '02', '832', '7002', 20)
2021-08-18 17:41:04,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,130 INFO sqlalchemy.engine.base.Engine ('맑은샘어린이집', '신정호', '서울특별시 노원구 공릉로59길 25 ,707동 106호(하계동, 청솔) (하계1동)', '02', '977', '0050', 9)
2021-08-18 17:41:04,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,133 INFO sqlalchemy.engine.base.Engine ('아소비어린이집', '오서현', '서울특별시 강동구 동남로65길 17 ,(명일동 196 ) (명일제2동)', '02', '429', '6620', 2)
2021-08-18 17:41:04,136 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,137 INFO sqlalchemy.engine.base.Engine ('청솔어린이집', '임은영', '서울특별시 금천구 가산로 106 ,두산주상복합상가 101 (가산동)', '02', '862', '2399', 8)
2021-08-18 17:41:04,138 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,139 INFO sqlalchemy.engine.base.Engine ('은담어린이집', '전정순', '서울특별시 서대문구 증가로8길 33 ,(남가좌동) (남가좌제2동)', '02', '303', '2324', 14)
2021-08-18 17:41:04,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,141 INFO sqlalchemy.engine.base.Engine ('완두콩어린이집', '황지은', '서울특별시 영등포구 디지털로 420 ,신대림2차 신동아 파밀리에 104동 103호 (대림제1동)', '02', '842', '5695', 20)
2021-08-18 17:41:04,141 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,142 INFO sqlalchemy.engine.base.Engine ('늘푸른베이비어린이집', '전진호', '서울특별시 강서구 가로공원로76가길 53 ,1층 (화곡동) (화곡제1동)', '02', '2604', '3220', 4)
2021-08-18 17:41:04,143 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,144 INFO sqlalchemy.engine.base.Engine ('주주어린이집', '권영환', '서울특별시 양천구 목동로 212 ,729동 105호(목동, 목동신시가지7단지아파트) (목1동)', '02', '6274', '1105', 19)
2021-08-18 17:41:04,145 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,145 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '권미경', '서울특별시 노원구 한글비석로48길 6 ,5동 102호(상계동, 한신2차아파트) (상계5동)', '02', '937', '1211', 9)
2021-08-18 17:41:04,146 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,147 INFO sqlalchemy.engine.base.Engine ('파랑새 어린이집', '안혜진', '서울특별시 강서구 가로공원로84길 42 ,(화곡동) (화곡제1동)', '02', '2699', '9424', 4)
2021-08-18 17:41:04,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,149 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '서지은', '서울특별시 은평구 진흥로 128-5 ,(녹번동) (녹번동)', '02', '357', '0130', 22)
2021-08-18 17:41:04,150 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,151 INFO sqlalchemy.engine.base.Engine ('휘경사임당어린이집', '한수빈', '서울특별시 동대문구 한천로 248 ,102동 105호(휘경동, 주공아파트) (휘경제2동)', '02', '6403', '4345', 11)
2021-08-18 17:41:04,152 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,153 INFO sqlalchemy.engine.base.Engine ('풍납사임당어린이집', '조정수', '서울특별시 송파구 한가람로 468 ,102동 104호(풍납동, 신성노바빌아파트) (풍납1동)', '02', '487', '9765', 18)
2021-08-18 17:41:04,154 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,155 INFO sqlalchemy.engine.base.Engine ('예인어린이집', '정지영', '서울특별시 강북구 도봉로97길 42-1 (수유3동)', '02', '902', '0287', 3)
2021-08-18 17:41:04,156 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,157 INFO sqlalchemy.engine.base.Engine ('꼬마숲햇살 어린이집', '박광수', '서울특별시 성북구 동소문로34길 24 ,103동 103호(돈암동, 삼성아파트) (돈암제1동)', '02', '6318', '0103', 17)
2021-08-18 17:41:04,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,161 INFO sqlalchemy.engine.base.Engine ('꿈동산몬테소리어린이집', '안정호', '서울특별시 광진구 면목로4길 3 ,101호(군자동, 동산골든빌라) (군자동)', '02', '462', '0363', 6)
2021-08-18 17:41:04,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,163 INFO sqlalchemy.engine.base.Engine ('아띠 어린이집', '안민지', '서울특별시 도봉구 도봉로177길 76-5 (도봉제1동)', '02', '955', '0030', 10)
2021-08-18 17:41:04,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,166 INFO sqlalchemy.engine.base.Engine ('아해뜰어린이집', '신정식', '서울특별시 중랑구 용마산로100길 47 ,(망우동) (망우제3동)', '02', '433', '1202', 25)
2021-08-18 17:41:04,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,170 INFO sqlalchemy.engine.base.Engine ('크라인어린이집', '윤종수', '서울특별시 도봉구 해등로 169 ,114동 105호(쌍문동, 삼익세라믹아파트) (쌍문제2동)', '02', '6316', '3164', 10)
2021-08-18 17:41:04,171 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,171 INFO sqlalchemy.engine.base.Engine ('생명어린이집', '신경회', '서울특별시 금천구 금하로23길 19 ,(시흥동) (시흥제5동)', '02', '895', '7979', 8)
2021-08-18 17:41:04,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,173 INFO sqlalchemy.engine.base.Engine ('역삼래미안어린이집', '서영식', '서울특별시 강남구 선릉로69길 19 ,역삼래미안 관리동 (역삼제2동)', '02', '501', '7713', 1)
2021-08-18 17:41:04,175 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,175 INFO sqlalchemy.engine.base.Engine ('우리또래어린이집', '송영환', '서울특별시 서대문구 증가로29길 30-14 ,B동 102호(북가좌동, 충우팰리스) (북가좌제2동)', '02', '373', '9433', 14)
2021-08-18 17:41:04,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,177 INFO sqlalchemy.engine.base.Engine ('소망어린이집', '황정자', '서울특별시 영등포구 여의대방로53길 38-4 (신길제1동)', '02', '832', '0924', 20)
2021-08-18 17:41:04,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,179 INFO sqlalchemy.engine.base.Engine ('노벨어린이집', '장지훈', '서울특별시 도봉구 도봉로104길 61-25 (창제2동)', '02', '6315', '4564', 10)
2021-08-18 17:41:04,179 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,180 INFO sqlalchemy.engine.base.Engine ('붕붕어린이집', '정병철', '서울특별시 구로구 고척로33길 47 ,금강주택101호 (고척동) (고척제2동)', '02', '2689', '9932', 7)
2021-08-18 17:41:04,181 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,182 INFO sqlalchemy.engine.base.Engine ('잠실아이사랑어린이집', '임지훈', '서울특별시 송파구 잠실로 88 ,109동 102호(잠실동, 레이크펠리스아파트) (잠실3동)', '02', '421', '1005', 18)
2021-08-18 17:41:04,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,185 INFO sqlalchemy.engine.base.Engine ('초롱별어린이집', '강정남', '서울특별시 송파구 백제고분로41길 8-8 (송파1동)', '02', '417', '9005', 18)
2021-08-18 17:41:04,186 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,187 INFO sqlalchemy.engine.base.Engine ('빛과소금어린이집', '황은정', '서울특별시 중랑구 면목로36길 15 ,(면목동) (면목제7동)', '02', '491', '5600', 25)
2021-08-18 17:41:04,188 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,189 INFO sqlalchemy.engine.base.Engine ('삼전중앙어린이집', '임정호', '서울특별시 송파구 백제고분로28길 23-3 (삼전동)', '02', '418', '8558', 18)
2021-08-18 17:41:04,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,191 INFO sqlalchemy.engine.base.Engine ('키즈어울림어린이집', '장정식', '서울특별시 중랑구 양원역로 18 ,108동 107호(망우동, 금호어울림아파트) (망우본동)', '02', '433', '3401', 25)
2021-08-18 17:41:04,192 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,193 INFO sqlalchemy.engine.base.Engine ('예영어린이집', '박유진', '서울특별시 동작구 여의대방로 22 ,2동 102호(신대방동, 우성아파트) (신대방제1동)', '02', '847', '4410', 12)
2021-08-18 17:41:04,194 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,195 INFO sqlalchemy.engine.base.Engine ('작은또래어린이집', '전준서', '서울특별시 영등포구 양평로24길 9 ,102동 104호(양평동5가, 한신아파트) (양평제2동)', '02', '2676', '0994', 20)
2021-08-18 17:41:04,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,196 INFO sqlalchemy.engine.base.Engine ('장위3동어린이집', '이영일', '서울특별시 성북구 돌곶이로32길 43 ,(장위동) (장위제3동)', '02', '913', '1741', 17)
2021-08-18 17:41:04,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,198 INFO sqlalchemy.engine.base.Engine ('멘토어린이집', '신영숙', '서울특별시 영등포구 당산로42길 16 ,510동 104호(당산동4가, 현대5차아파트) (당산제2동)', '02', '2636', '1650', 20)
2021-08-18 17:41:04,199 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,200 INFO sqlalchemy.engine.base.Engine ('킨더빌어린이집', '조성민', '서울특별시 중랑구 양원역로 18 ,금호어울림아파트 관리동 (망우동) (망우본동)', '02', '493', '4833', 25)
2021-08-18 17:41:04,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,203 INFO sqlalchemy.engine.base.Engine ('사랑해어린이집', '강광수', '서울특별시 동대문구 한천로58길 139 ,103동 102호(이문동, 대우아파트) (이문제2동)', '02', '967', '5580', 11)
2021-08-18 17:41:04,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,205 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '권준서', '서울특별시 동작구 동작대로45길 22 ,105동 104호(동작동, KCC스위첸) (사당제2동)', '02', '3473', '4886', 12)
2021-08-18 17:41:04,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,207 INFO sqlalchemy.engine.base.Engine ('꽃동산 어린이집', '최지민', '서울특별시 금천구 남부순환로 1364 ,(독산동) (독산제3동)', '02', '866', '6570', 8)
2021-08-18 17:41:04,209 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,209 INFO sqlalchemy.engine.base.Engine ('예담아이어린이집', '최유진', '서울특별시 양천구 목동동로 50 ,1113동 103호(신정동, 신시가지11단지아파트) (신정7동)', '02', '2642', '0701', 19)
2021-08-18 17:41:04,210 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,211 INFO sqlalchemy.engine.base.Engine ('EQ어린이집', '조예준', '서울특별시 양천구 신월로 99 ,7동 101호(신월동, 신월시영아파트) (신월7동)', '02', '2603', '0314', 19)
2021-08-18 17:41:04,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,213 INFO sqlalchemy.engine.base.Engine ('스마일어린이집', '강지영', '서울특별시 양천구 목동중앙본로5길 26 ,가동 101호(목동, 상진지오밸리) (목4동)', '02', '2644', '2207', 19)
2021-08-18 17:41:04,215 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,216 INFO sqlalchemy.engine.base.Engine ('창의스쿨어린이집', '한유진', '서울특별시 노원구 동일로191가길 59 ,103동 108호(공릉동, 신도 1차) (공릉1동)', '02', '973', '5212', 9)
2021-08-18 17:41:04,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,218 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '장서연', '서울특별시 은평구 은평로11길 6 ,(응암동) (응암제1동)', '02', '351', '9897', 22)
2021-08-18 17:41:04,222 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,223 INFO sqlalchemy.engine.base.Engine ('삼성하얀어린이집', '임준영', '서울특별시 마포구 백범로25길 63 ,106동 103호(염리동, 염리삼성래미안아파트) (염리동)', '02', '717', '7339', 13)
2021-08-18 17:41:04,224 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,225 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '강병철', '서울특별시 종로구 평창문화로 172 ,102동 106호(평창동, 삼성아파트) (평창동)', '02', '379', '1317', 23)
2021-08-18 17:41:04,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,227 INFO sqlalchemy.engine.base.Engine ('리틀바움어린이집', '윤민석', '서울특별시 강남구 개포로109길 21 ,대치2단지 관리동 1층 (일원제2동)', '02', '451', '8704', 1)
2021-08-18 17:41:04,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,229 INFO sqlalchemy.engine.base.Engine ('성미산어린이집', '오진호', '서울특별시 마포구 성미산로7안길 44 ,(성산동) (성산제1동)', '02', '6082', '6060', 13)
2021-08-18 17:41:04,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,231 INFO sqlalchemy.engine.base.Engine ('한신붕붕어린이집', '안정운', '서울특별시 금천구 한내로 62 ,6동 101호(독산동, 한신) (독산제1동)', '02', '899', '8999', 8)
2021-08-18 17:41:04,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,233 INFO sqlalchemy.engine.base.Engine ('은혜영재어린이집', '박민지', '서울특별시 강동구 상암로3길 54 ,한건새봄아파트 103호 (암사동504-8) (암사제2동)', '02', '428', '5169', 2)
2021-08-18 17:41:04,235 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,236 INFO sqlalchemy.engine.base.Engine ('우리두리어린이집', '전성호', '서울특별시 송파구 강동대로 61-15 ,. (풍납2동)', '02', '489', '5417', 18)
2021-08-18 17:41:04,237 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,238 INFO sqlalchemy.engine.base.Engine ('행복한에덴어린이집', '황영철', '서울특별시 금천구 금하로 793 ,106동 102호(시흥동, 벽산아파트) (시흥제2동)', '02', '809', '1557', 8)
2021-08-18 17:41:04,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,240 INFO sqlalchemy.engine.base.Engine ('킨더벨트어린이집', '전지훈', '서울특별시 영등포구 여의대방로43나길 25 ,107동 101호(신길동, 삼환아파트) (신길제7동)', '02', '6746', '7893', 20)
2021-08-18 17:41:04,241 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,242 INFO sqlalchemy.engine.base.Engine ('다윗어린이집', '오현정', '서울특별시 성북구 고려대로7길 120 ,돈암성당 내 (동선동2가) (동선동)', '02', '925', '3224', 17)
2021-08-18 17:41:04,243 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,244 INFO sqlalchemy.engine.base.Engine ('도곡어린이집', '장정자', '서울특별시 강남구 선릉로 217 ,(도곡동) (도곡제2동)', '02', '572', '9110', 1)
2021-08-18 17:41:04,245 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,246 INFO sqlalchemy.engine.base.Engine ('뜨란어린이집', '서영길', '서울특별시 서대문구 독립문로8길 54 ,뜨란채아파트 107동 관리동 (천연동) (천연동)', '02', '365', '8967', 14)

2021-08-18 17:41:04,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,249 INFO sqlalchemy.engine.base.Engine ('숲어린이집', '강순자', '서울특별시 서대문구 독립문로8길 54 ,101동 104호(천연동, 주공뜨란채아파트) (천연동)', '02', '313', '4876', 14)
2021-08-18 17:41:04,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,251 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '이영진', '서울특별시 강서구 금낭화로23길 8 ,101동 106호(방화동, 동성아파트) (방화제3동)', '02', '2661', '9757', 4)
2021-08-18 17:41:04,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,253 INFO sqlalchemy.engine.base.Engine ('(재)천주교서울대교구유지재단천사어린이집', '권영철', '서울특별시 송파구 거마로24길 11 ,(마천동) (마천2동)', '02', '409', '1406', 18)
2021-08-18 17:41:04,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,255 INFO sqlalchemy.engine.base.Engine ('꿈사랑몬테소리어린이집', '장민지', '서울특별시 강남구 삼성로51길 35 ,대치팰리스아파트 2단지 내 관리동 (대치제1동)', '02', '556', '9645', 1)
2021-08-18 17:41:04,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,257 INFO sqlalchemy.engine.base.Engine ('해피모아어린이집', '조영진', '서울특별시 도봉구 해등로 242-11 ,101동 101호(쌍문동, 성원아파트) (쌍문제4동)', '02', '991', '6173', 10)
2021-08-18 17:41:04,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,261 INFO sqlalchemy.engine.base.Engine ('응암홍익어린이집', '김지은', '서울특별시 은평구 가좌로7다길 3 ,응암홍익 어린이집 (응암동) (응암제3동)', '02', '374', '6565', 22)
2021-08-18 17:41:04,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,263 INFO sqlalchemy.engine.base.Engine ('배광 어린이집', '정민지', '서울특별시 강서구 등촌로 101 ,(등촌동) (등촌제2동)', '02', '2643', '0126', 4)
2021-08-18 17:41:04,264 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,265 INFO sqlalchemy.engine.base.Engine ('동광어린이집', '이민수', '서울특별시 동작구 성대로1가길 14 ,(상도동) (상도제4동)', '02', '821', '1009', 12)
2021-08-18 17:41:04,266 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,267 INFO sqlalchemy.engine.base.Engine ('미가어린이집', '임도현', '서울특별시 서대문구 수색로6길 43 ,101동 101호(남가좌동, 래미안남가좌2차아파트) (남가좌제1동)', '02', '302', '2656', 14)
2021-08-18 17:41:04,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,269 INFO sqlalchemy.engine.base.Engine ('대림어린이집', '정민석', '서울특별시 강서구 공항대로39길 100 ,105동 103호(등촌동, 대림아파트) (등촌제3동)', '02', '3662', '6422', 4)
2021-08-18 17:41:04,270 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,271 INFO sqlalchemy.engine.base.Engine ('숲속키즈나라어린이집', '강유진', '서울특별시 은평구 연서로11길 30-2 (구산동)', '02', '382', '8763', 22)
2021-08-18 17:41:04,272 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,274 INFO sqlalchemy.engine.base.Engine ('예향어린이집', '김영숙', '서울특별시 강남구 개포로22길 87 ,(개포동) 포이교육문화관 1층 (개포제4동)', '02', '3462', '4048', 1)
2021-08-18 17:41:04,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,275 INFO sqlalchemy.engine.base.Engine ('새서울숲어린이집', '한진호', '서울특별시 성북구 장위로15길 73 ,(장위동) (장위제1동)', '02', '941', '6070', 17)
2021-08-18 17:41:04,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,279 INFO sqlalchemy.engine.base.Engine ('햇살가득어린이집', '신민서', '서울특별시 중랑구 겸재로29길 32 ,(면목동) (면목본동)', '02', '434', '1253', 25)
2021-08-18 17:41:04,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,281 INFO sqlalchemy.engine.base.Engine ('베베키즈어린이집', '전정수', '서울특별시 강서구 강서로45길 18 ,태승훼미리아파트 101동103호 (내발산동) (발산제1동)', '02', '2607', '5595', 4)
2021-08-18 17:41:04,282 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,283 INFO sqlalchemy.engine.base.Engine ('으뜸어린이집', '최준서', '서울특별시 양천구 신정중앙로 60 ,(신정동) (신정4동)', '02', '2693', '0648', 19)
2021-08-18 17:41:04,283 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,284 INFO sqlalchemy.engine.base.Engine ('화동교회방과후어린이집', '김지원', '서울특별시 강서구 곰달래로 200 ,(화곡동) (화곡제2동)', '070', '7169', '9910', 4)
2021-08-18 17:41:04,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,286 INFO sqlalchemy.engine.base.Engine ('세모네모재능어린이집', '김성수', '서울특별시 중랑구 중랑역로 72-8 (중화제2동)', '02', '432', '6167', 25)
2021-08-18 17:41:04,287 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,288 INFO sqlalchemy.engine.base.Engine ('함께하는어린이집', '황은영', '서울특별시 송파구 풍성로14길 19 ,현대아파트 106호 (풍납동) (풍납2동)', '02', '470', '4993', 18)
2021-08-18 17:41:04,290 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,291 INFO sqlalchemy.engine.base.Engine ('선인방과후교실어린이집', '윤성진', '서울특별시 용산구 효창원로8길 17 ,선인중앙교회 (원효로4가) (원효로제2동)', '02', '718', '0691', 21)
2021-08-18 17:41:04,293 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,294 INFO sqlalchemy.engine.base.Engine ('예동영재어린이집', '정정수', '서울특별시 동작구 사당로2길 64 ,(사당동) (사당제5동)', '02', '3486', '1418', 12)
2021-08-18 17:41:04,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,296 INFO sqlalchemy.engine.base.Engine ('아이빛나어린이집', '강미영', '서울특별시 노원구 마들로 111 ,21동 102호(월계동, 미륭) (월계3동)', '02', '974', '2779', 9)
2021-08-18 17:41:04,297 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,298 INFO sqlalchemy.engine.base.Engine ('푸르미엔젤어린이집', '이정자', '서울특별시 노원구 한글비석로 530 ,1208동 101호(상계동, 상계주공12단지아파트) (상계9동)', '02', '3392', '2269', 9)
2021-08-18 17:41:04,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,300 INFO sqlalchemy.engine.base.Engine ('신광어린이집', '이은영', '서울특별시 금천구 독산로80가길 14 ,(독산동) (독산제4동)', '02', '865', '0011', 8)
2021-08-18 17:41:04,301 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,302 INFO sqlalchemy.engine.base.Engine ('예든어린이집', '류은정', '서울특별시 동대문구 장한로26다길 84 ,201동 105호(장안동, 현대홈타운아파트) (장안제2동)', '02', '6414', '8600', 11)
2021-08-18 17:41:04,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,304 INFO sqlalchemy.engine.base.Engine ('꾸러기어린이집', '정정식', '서울특별시 서대문구 세검정로1길 93 ,103동 103호(홍은동, 벽산아파트) (홍은제1동)', '02', '396', '8319', 14)
2021-08-18 17:41:04,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,306 INFO sqlalchemy.engine.base.Engine ('강동빅스맘어린이집', '류종수', '서울특별시 강동구 상일로7길 12-5 ,(상일동 240) (상일제1동)', '02', '426', '8588', 2)
2021-08-18 17:41:04,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,309 INFO sqlalchemy.engine.base.Engine ('예나어린이집', '서종수', '서울특별시 은평구 통일로73길 5-6 (대조동)', '02', '383', '4274', 22)
2021-08-18 17:41:04,310 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,311 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '장건우', '서울특별시 은평구 불광로 162-9 (불광제1동)', '02', '389', '2131', 22)
2021-08-18 17:41:04,312 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,313 INFO sqlalchemy.engine.base.Engine ('이화젠어린이집', '장진호', '서울특별시 도봉구 우이천로4라길 11-14 ,신도브래뉴2차 단지내 (창동) (창제3동)', '02', '903', '0008', 10)
2021-08-18 17:41:04,313 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,315 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '최민재', '서울특별시 성북구 솔샘로 120 ,124동 105호(정릉동, 풍림아이원) (정릉제4동)', '02', '913', '8931', 17)
2021-08-18 17:41:04,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,316 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '강지영', '서울특별시 송파구 거마로7길 42 ,(거여동) (거여1동)', '02', '443', '5996', 18)
2021-08-18 17:41:04,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,318 INFO sqlalchemy.engine.base.Engine ('다솔 방과후교실', '권지영', '서울특별시 종로구 통일로8길 16 ,(송월동) (교남동)', '02', '722', '5011', 23)
2021-08-18 17:41:04,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,321 INFO sqlalchemy.engine.base.Engine ('별강서어린이집', '이준호', '서울특별시 강서구 까치산로22길 10 ,(화곡동) (화곡제6동)', '02', '2065', '5151', 4)
2021-08-18 17:41:04,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,325 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '장혜진', '서울특별시 강서구 강서로17가길 14 ,나동 101호(화곡동, 계명아파트) (화곡제1동)', '02', '6401', '9195', 4)
2021-08-18 17:41:04,326 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,327 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '이진호', '서울특별시 성북구 성북동1가 성북로 37 ,한빛 어린이집 (성북동)', '02', '741', '5236', 17)
2021-08-18 17:41:04,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,328 INFO sqlalchemy.engine.base.Engine ('강남방과후교실어린이집', '강예은', '서울특별시 동작구 만양로 76 ,2층 (노량진동,강남교회) (노량진제1동)', '02', '814', '7616', 12)
2021-08-18 17:41:04,329 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,331 INFO sqlalchemy.engine.base.Engine ('성애어린이집', '임영진', '서울특별시 중랑구 신내로8길 46 ,성애어린이집 (신내1동)', '02', '433', '2777', 25)
2021-08-18 17:41:04,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,332 INFO sqlalchemy.engine.base.Engine ('유앤아이사랑어린이집', '오순자', '서울특별시 구로구 중앙로15길 151 ,103동 101호(고척동, 한일유앤아이아파트) (고척제2동)', '02', '2060', '9364', 7)
2021-08-18 17:41:04,333 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,334 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '임은영', '서울특별시 송파구 양재대로72길 52 ,오륜파크빌103호 (오금동) (오금동)', '02', '431', '0007', 18)
2021-08-18 17:41:04,335 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,336 INFO sqlalchemy.engine.base.Engine ('하늘한조각어린이집', '안건우', '서울특별시 은평구 역말로 14 ,(역촌동) (역촌동)', '02', '382', '5616', 22)
2021-08-18 17:41:04,337 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,337 INFO sqlalchemy.engine.base.Engine ('하린어린이집', '오정호', '서울특별시 서대문구 연희로11마길 52 ,(연희동) (연희동)', '02', '334', '8085', 14)
2021-08-18 17:41:04,339 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,340 INFO sqlalchemy.engine.base.Engine ('구립 용강어린이집', '임영자', '서울특별시 마포구 토정로37가길 34 (용강동)', '02', '704', '3386', 13)
2021-08-18 17:41:04,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,342 INFO sqlalchemy.engine.base.Engine ('아이엠어린이집', '권미숙', '서울특별시 동작구 여의대방로10길 13 ,한성아파트단지내 (신대방동) (신대방제2동)', '02', '835', '6046', 12)
2021-08-18 17:41:04,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,344 INFO sqlalchemy.engine.base.Engine ('강서구청어린이집', '류영일', '서울특별시 강서구 화곡로44나길 72 ,1층,2층 강서구청어린이집 (화곡제6동)', '070', '8879', '0622', 4)
2021-08-18 17:41:04,345 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,346 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '한지훈', '서울특별시 광진구 면목로 164 ,(중곡동) (중곡제3동)', '02', '452', '0804', 6)
2021-08-18 17:41:04,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,348 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '류경숙', '서울특별시 은평구 증산로17가길 14 ,(신사동) (신사제2동)', '02', '375', '3354', 22)
2021-08-18 17:41:04,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,349 INFO sqlalchemy.engine.base.Engine ('아뜰어린이집', '전서연', '서울특별시 동대문구 안암로 6 ,대광고등학교내 (신설동) (용신동)', '02', '924', '0235', 11)
2021-08-18 17:41:04,350 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,351 INFO sqlalchemy.engine.base.Engine ('영성방과후교실', '강예준', '서울특별시 동작구 국사봉1길 146 ,영성교회1층 (상도동) (상도제3동)', '02', '821', '1146', 12)
2021-08-18 17:41:04,352 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,353 INFO sqlalchemy.engine.base.Engine ('중앙어린이집', '박서연', '서울특별시 성북구 정릉로26길 8 ,중앙하이츠빌 2단지 관리동1층 (정릉동) (정릉제2동)', '02', '6223', '1005', 17)
2021-08-18 17:41:04,354 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,356 INFO sqlalchemy.engine.base.Engine ('푸르내어린이집', '권지혜', '서울특별시 광진구 긴고랑로36길 15 ,(중곡동) (중곡제4동)', '02', '3436', '3488', 6)
2021-08-18 17:41:04,357 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,357 INFO sqlalchemy.engine.base.Engine ('한남어린이집', '류순자', '서울특별시 용산구 대사관로5길 1 ,(한남동) (한남동)', '02', '749', '0824', 21)
2021-08-18 17:41:04,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,359 INFO sqlalchemy.engine.base.Engine ('해달별 아이사랑어린이집', '황은정', '서울특별시 영등포구 대림로23가길 2-1 (대림제2동)', '02', '849', '9746', 20)
2021-08-18 17:41:04,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,362 INFO sqlalchemy.engine.base.Engine ('해와별 어린이집', '오준서', '서울특별시 성북구 화랑로48길 16 ,108동 101호(석관동, 두산아파트) (석관동)', '02', '957', '6463', 17)
2021-08-18 17:41:04,363 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,364 INFO sqlalchemy.engine.base.Engine ('우림어린이집', '조영진', '서울특별시 구로구 서해안로 2368 ,우림필유상가동 (오류동) (오류제2동)', '02', '2687', '6187', 7)
2021-08-18 17:41:04,365 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,366 INFO sqlalchemy.engine.base.Engine ('수정어린이집', '송지원', '서울특별시 광진구 천호대로102길 41 ,(군자동) (군자동)', '02', '466', '4807', 6)
2021-08-18 17:41:04,368 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,368 INFO sqlalchemy.engine.base.Engine ('꿈모아어린이집', '임정남', '서울특별시 은평구 갈현로4길 5-16 (역촌동)', '02', '355', '2775', 22)
2021-08-18 17:41:04,370 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,371 INFO sqlalchemy.engine.base.Engine ('세진어린이집', '한민지', '서울특별시 양천구 곰달래로 28 ,(신월동) (신월1동)', '02', '2608', '0808', 19)
2021-08-18 17:41:04,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,373 INFO sqlalchemy.engine.base.Engine ('크는나무어린이집', '류예준', '서울특별시 양천구 신목로5길 5 ,개진빌딩1층 (신정동) (신정2동)', '02', '2652', '7734', 19)
2021-08-18 17:41:04,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,375 INFO sqlalchemy.engine.base.Engine ('다솜아이어린이집', '신영식', '서울특별시 노원구 동일로215길 23 ,219동 101호(상계동, 주공아파트) (상계6.7동)', '02', '932', '2004', 9)
2021-08-18 17:41:04,377 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,378 INFO sqlalchemy.engine.base.Engine ('현대i어린이집', '박영식', '서울특별시 강서구 강서로 348 ,우장산 힐스테이트 관리동 1층 (우장산동)', '02', '2658', '0175', 4)
2021-08-18 17:41:04,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,380 INFO sqlalchemy.engine.base.Engine ('은평사임당어린이집', '오미숙', '서울특별시 은평구 진흥로12나길 1-31 (녹번동)', '02', '353', '6990', 22)
2021-08-18 17:41:04,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,383 INFO sqlalchemy.engine.base.Engine ('한신타운어린이집', '임현준', '서울특별시 구로구 고척로 52 ,102동 104호(오류동, 한신아파트) (오류제1동)', '02', '6347', '7979', 7)
2021-08-18 17:41:04,384 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,386 INFO sqlalchemy.engine.base.Engine ('세라핌어린이집', '전성진', '서울특별시 구로구 고척로18길 92 ,오류동감리교회 세라핌어린이집 (오류동) (오류제1동)', '02', '2612', '6501', 7)
2021-08-18 17:41:04,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,390 INFO sqlalchemy.engine.base.Engine ('산위의마을어린이집', '장준영', '서울특별시 광진구 용마산로7길 39 ,(중곡동) (중곡제2동)', '02', '457', '8953', 6)
2021-08-18 17:41:04,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,392 INFO sqlalchemy.engine.base.Engine ('이루리어린이집', '조예준', '서울특별시 송파구 백제고분로50길 19-15 (방이2동)', '02', '414', '5858', 18)
2021-08-18 17:41:04,394 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,395 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '권현준', '서울특별시 강서구 방화대로 259 ,101동 104호(공항동,해태아파트) (공항동)', '02', '2662', '0583', 4)
2021-08-18 17:41:04,396 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,397 INFO sqlalchemy.engine.base.Engine ('지앤지어린이집', '강지영', '서울특별시 도봉구 삼양로 574-44 (쌍문제1동)', '02', '992', '4050', 10)
2021-08-18 17:41:04,398 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,399 INFO sqlalchemy.engine.base.Engine ('현경어린이집', '오준영', '서울특별시 구로구 부일로11길 105 ,(궁동) (수궁동)', '02', '2617', '4345', 7)
2021-08-18 17:41:04,400 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,402 INFO sqlalchemy.engine.base.Engine ('온머리어린이집', '이동현', '서울특별시 영등포구 영등포로 351 ,102동 101호(신길동, 신길동경남아파트) (신길제1동)', '02', '842', '1171', 20)
2021-08-18 17:41:04,403 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,403 INFO sqlalchemy.engine.base.Engine ('작은꽃영아어린이집', '정병철', '서울특별시 노원구 노원로 532 ,915동 102호(상계동, 주공아파트) (상계10동)', '02', '930', '9516', 9)
2021-08-18 17:41:04,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,406 INFO sqlalchemy.engine.base.Engine ('베베스쿨 어린이집', '황영일', '서울특별시 성북구 정릉로 404 ,103동 106호(돈암동, 현대아파트) (돈암제1동)', '02', '929', '1008', 17)
2021-08-18 17:41:04,408 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,410 INFO sqlalchemy.engine.base.Engine ('두산오르다어린이집', '정민지', '서울특별시 동대문구 답십리로56길 8 ,(답십리동) (답십리제2동)', '02', '2243', '0532', 11)
2021-08-18 17:41:04,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,413 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '최영철', '서울특별시 구로구 중앙로12길 12 ,102동 103호(고척동, 센츄리아파트) (고척제1동)', '02', '6406', '1770', 7)
2021-08-18 17:41:04,414 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,415 INFO sqlalchemy.engine.base.Engine ('은석어린이집', '신지영', '서울특별시 영등포구 여의대방로23길 11 ,(신길동) (신길제6동)', '02', '841', '4242', 20)
2021-08-18 17:41:04,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,419 INFO sqlalchemy.engine.base.Engine ('동도삐아제어린이집', '윤민재', '서울특별시 노원구 한글비석로19길 15 ,101동 108호(중계동, 동도센트리움아파트) (중계4동)', '02', '935', '1413', 9)
2021-08-18 17:41:04,420 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,421 INFO sqlalchemy.engine.base.Engine ('여의도순복음어린이집', '류지은', '서울특별시 영등포구 국회대로76길 25 ,(여의도동) (여의도동)', '02', '785', '3927', 20)
2021-08-18 17:41:04,422 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,425 INFO sqlalchemy.engine.base.Engine ('하나로사랑담어린이집', '신영환', '서울특별시 은평구 서오릉로 235 (구산동)', '02', '382', '8862', 22)
2021-08-18 17:41:04,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,427 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '임영숙', '서울특별시 성북구 돌곶이로 43-11 (석관동)', '02', '969', '1952', 17)
2021-08-18 17:41:04,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,429 INFO sqlalchemy.engine.base.Engine ('아이동산어린이집', '장종수', '서울특별시 성북구 종암로9길 71 ,214동 101호(종암동, 현대아이파크2차아파트) (종암동)', '02', '6225', '3126', 17)
2021-08-18 17:41:04,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,430 INFO sqlalchemy.engine.base.Engine ('만나어린이집', '서예은', '서울특별시 종로구 혜화로14길 19 ,(혜화동) (혜화동)', '02', '766', '5763', 23)
2021-08-18 17:41:04,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,434 INFO sqlalchemy.engine.base.Engine ('꼬마친구어린이집', '윤영식', '서울특별시 노원구 한글비석로14길 37 ,201동 101호(중계동, 중앙하이츠) (중계4동)', '070', '8770', '0504', 9)
2021-08-18 17:41:04,437 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,438 INFO sqlalchemy.engine.base.Engine ('구립수유2동어린이집', '강영식', '서울특별시 강북구 삼양로138길 18 ,(수유동) (수유2동)', '02', '900', '0067', 3)
2021-08-18 17:41:04,441 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,442 INFO sqlalchemy.engine.base.Engine ('고려창의스쿨어린이집', '안정웅', '서울특별시 양천구 은행정로7길 24 ,(신정동) (신정4동)', '02', '2693', '8252', 19)
2021-08-18 17:41:04,443 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,444 INFO sqlalchemy.engine.base.Engine ('상명어린이집', '권영환', '서울특별시 광진구 동일로80길 30 ,(중곡동) (중곡제3동)', '02', '464', '5984', 6)
2021-08-18 17:41:04,451 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,451 INFO sqlalchemy.engine.base.Engine ('가온누리어린이집', '권정웅', '서울특별시 중랑구 동일로99길 38 ,(면목동) (면목제2동)', '02', '433', '6441', 25)
2021-08-18 17:41:04,453 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,455 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '윤지훈', '서울특별시 서초구 반포대로 180 ,다솜어린이집[서초경찰서 맞은편] (서초3동)', '02', '592', '9944', 15)
2021-08-18 17:41:04,456 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,460 INFO sqlalchemy.engine.base.Engine ('딩동댕어린이집', '윤준호', '서울특별시 성동구 둘레13길 15 ,(성수동2가) (성수2가제1동)', '02', '497', '1919', 16)
2021-08-18 17:41:04,462 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,464 INFO sqlalchemy.engine.base.Engine ('새롬어린이집', '윤영철', '서울특별시 광진구 구의강변로 94 ,601동 105호(구의동, 구의현대6단지아파트) (구의제3동)', '02', '2201', '3037', 6)
2021-08-18 17:41:04,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,466 INFO sqlalchemy.engine.base.Engine ('별사탕어린이집', '윤정호', '서울특별시 도봉구 마들로 684-9 ,113동 103호(도봉동, 서원아파트) (도봉제2동)', '02', '3494', '1197', 10)
2021-08-18 17:41:04,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,468 INFO sqlalchemy.engine.base.Engine ('새빛어린이집', '강영자', '서울특별시 강서구 화곡로18길 14-41 ,1층 새빛어린이집 (화곡제1동)', '02', '2608', '7830', 4)
2021-08-18 17:41:04,469 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,470 INFO sqlalchemy.engine.base.Engine ('꼬마숲웬디어린이집', '오정순', '서울특별시 양천구 신목로 77 ,101동 102호(신정동, 유원목동아파트) (신정2동)', '070', '8269', '9566', 19)
2021-08-18 17:41:04,471 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,472 INFO sqlalchemy.engine.base.Engine ('한아름어린이집', '황준혁', '서울특별시 금천구 독산로41가길 25 ,(시흥동) (시흥제1동)', '02', '808', '5470', 8)
2021-08-18 17:41:04,473 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,474 INFO sqlalchemy.engine.base.Engine ('성북청소년수련관 방과후교실 어린이집', '서상철', '서울특별시 성북구 한천로 660-9 ,시립성북청소년수련관 (장위동) (장위제3동)', '02', '3292', '1708', 17)
2021-08-18 17:41:04,475 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,476 INFO sqlalchemy.engine.base.Engine ('리나어린이집', '전정운', '서울특별시 송파구 송이로2길 20 ,(송파동) (송파2동)', '02', '417', '2919', 18)
2021-08-18 17:41:04,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,478 INFO sqlalchemy.engine.base.Engine ('파란어린이집', '안지혜', '서울특별시 송파구 풍성로 52 (풍납2동)', '02', '477', '4881', 18)
2021-08-18 17:41:04,479 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,480 INFO sqlalchemy.engine.base.Engine ('참솔어린이집', '권지원', '서울특별시 도봉구 시루봉로13가길 23-21 ,참솔어린이집 (방학동) (방학제2동)', '02', '956', '0003', 10)
2021-08-18 17:41:04,483 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,484 INFO sqlalchemy.engine.base.Engine ('예원사랑어린이집', '서지훈', '서울특별시 은평구 연서로18가길 4 ,(대조동) (대조동)', '02', '385', '4014', 22)
2021-08-18 17:41:04,485 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,486 INFO sqlalchemy.engine.base.Engine ('명지어린이집', '임현정', '서울특별시 강서구 등촌로13아길 44 ,101동 106호(화곡동, 명지해드는터 아파트) (화곡제4동)', '02', '2644', '8778', 4)
2021-08-18 17:41:04,487 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,488 INFO sqlalchemy.engine.base.Engine ('구립 성원어린이집', '김경회', '서울특별시 성동구 뚝섬로3길 18 ,(성수동1가) (성수1가제1동)', '02', '461', '1690', 16)
2021-08-18 17:41:04,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,490 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '서민지', '서울특별시 중랑구 용마산로114길 4 ,(망우동) (망우본동)', '02', '496', '4446', 25)
2021-08-18 17:41:04,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,492 INFO sqlalchemy.engine.base.Engine ('좋은나무어린이집', '강민지', '서울특별시 노원구 동일로237길 37 ,102동 105호(상계동, 상계현대1차) (상계1동)', '070', '8658', '1756', 9)
2021-08-18 17:41:04,493 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,494 INFO sqlalchemy.engine.base.Engine ('경기어린이집', '장지민', '서울특별시 마포구 양화로1길 108 ,(합정동) (합정동)', '02', '323', '1980', 13)
2021-08-18 17:41:04,495 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,496 INFO sqlalchemy.engine.base.Engine ('삼성푸른숲어린이집', '권수빈', '서울특별시 마포구 마포대로11길 50 ,409동 1층(공덕동, 공덕래미안4차아파트) (아현동)', '02', '3272', '3438', 13)
2021-08-18 17:41:04,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,499 INFO sqlalchemy.engine.base.Engine ('단꿈어린이집', '조정남', '서울특별시 강서구 양천로47길 118 ,104동 101호 (마곡동, 벽산아파트) (가양제1동)', '02', '6341', '7979', 4)
2021-08-18 17:41:04,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,502 INFO sqlalchemy.engine.base.Engine ('예쁜꼬마어린이집', '오은영', '서울특별시 도봉구 덕릉로59아길 17 ,107동 103호(창동, 창동대우아파트) (창제2동)', '02', '6227', '0011', 10)
2021-08-18 17:41:04,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,505 INFO sqlalchemy.engine.base.Engine ('별나라어린이집', '이지민', '서울특별시 구로구 신도림로11가길 36 ,5동 101호(신도림동, 미성아파트) (신도림동)', '02', '2068', '9993', 7)
2021-08-18 17:41:04,506 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,507 INFO sqlalchemy.engine.base.Engine ('아가페어린이집', '이예은', '서울특별시 금천구 독산로60길 38 ,(독산동) (독산제2동)', '02', '808', '9930', 8)
2021-08-18 17:41:04,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,509 INFO sqlalchemy.engine.base.Engine ('해다미어린이집', '황민수', '서울특별시 강서구 곰달래로35길 13 ,(화곡동) (화곡제2동)', '02', '2607', '4001', 4)
2021-08-18 17:41:04,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,511 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '장지혜', '서울특별시 강북구 노해로27길 48 ,(수유동) (수유2동)', '02', '900', '5176', 3)
2021-08-18 17:41:04,512 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,515 INFO sqlalchemy.engine.base.Engine ('밤비어린이집', '정동현', '서울특별시 강동구 풍성로37길 40-19 ,(성내동 140-5) (성내제2동)', '02', '484', '2871', 2)
2021-08-18 17:41:04,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,517 INFO sqlalchemy.engine.base.Engine ('삼성래미안어린이집', '오미숙', '서울특별시 마포구 마포대로7길 22 ,삼성래미안공덕3차아파트 복지관1층 (공덕동) (아현동)', '02', '3275', '3273', 13)
2021-08-18 17:41:04,518 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,519 INFO sqlalchemy.engine.base.Engine ('꿈이크는어린이집', '이지영', '서울특별시 노원구 한글비석로 530 ,1206동 101호 (상계동, 주공12단지아파트) (상계9동)', '02', '931', '5882', 9)
2021-08-18 17:41:04,521 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,522 INFO sqlalchemy.engine.base.Engine ('소담사임당어린이집', '이민수', '서울특별시 강동구 양재대로121길 50 ,101동 104호(천호동, 예전이룸아파트) (천호제1동)', '02', '476', '5001', 2)
2021-08-18 17:41:04,524 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,527 INFO sqlalchemy.engine.base.Engine ('공동육아통통어린이집', '조민지', '서울특별시 노원구 동일로236길 60-4 (상계1동)', '02', '3391', '2889', 9)
2021-08-18 17:41:04,529 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,533 INFO sqlalchemy.engine.base.Engine ('삼성어린이집', '송정자', '서울특별시 강동구 상암로3길 77 ,103동 104호(암사동, 삼성광나루) (암사제2동)', '02', '3013', '3600', 2)
2021-08-18 17:41:04,535 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,536 INFO sqlalchemy.engine.base.Engine ('또바기어린이집', '류은영', '서울특별시 마포구 월드컵로5길 33-18 ,합정동 (합정동)', '02', '333', '4421', 13)
2021-08-18 17:41:04,537 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,538 INFO sqlalchemy.engine.base.Engine ('포그니어린이집', '안정웅', '서울특별시 양천구 화곡로3길 20-19 ,샤인팰리스101호 (신월동) (신월5동)', '02', '2602', '7027', 19)
2021-08-18 17:41:04,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,540 INFO sqlalchemy.engine.base.Engine ('세인어린이집', '안준호', '서울특별시 도봉구 방학로3길 100 ,(쌍문동) (쌍문제2동)', '02', '994', '5230', 10)
2021-08-18 17:41:04,542 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,543 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '강진호', '서울특별시 도봉구 덕릉로59자길 15 ,(창동) (창제2동)', '02', '990', '5792', 10)
2021-08-18 17:41:04,545 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,545 INFO sqlalchemy.engine.base.Engine ('사랑담아어린이집', '안경숙', '서울특별시 노원구 동일로213길 21 ,118동 106호(상계동, 상계주공1차) (상계6.7동)', '02', '6221', '8201', 9)
2021-08-18 17:41:04,547 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,548 INFO sqlalchemy.engine.base.Engine ('푸르니어린이집', '조영철', '서울특별시 노원구 섬밭로 123 ,(공릉1동, 라이프아파트3단지 관리사무소 1층) (공릉1동)', '02', '975', '9010', 9)
2021-08-18 17:41:04,549 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,550 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '황은정', '서울특별시 중랑구 겸재로3길 8 ,대경빌라 101호 (면목제2동)', '02', '433', '1345', 25)
2021-08-18 17:41:04,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,552 INFO sqlalchemy.engine.base.Engine ('숲으로 가는 어린이집', '조성민', '서울특별시 강서구 양천로69길 18 ,101동 111호(염창동, 극동아파트) (염창동)', '02', '2658', '6399', 4)
2021-08-18 17:41:04,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,555 INFO sqlalchemy.engine.base.Engine ('장미어린이집', '임은경', '서울특별시 구로구 경인로 343 ,삼환로즈빌아파트 단지 내 1층 장미 어린이집 (고척동) (고척제1동)', '02', '2060', '0406', 7)
2021-08-18 17:41:04,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,557 INFO sqlalchemy.engine.base.Engine ('꼬마대통령어린이집', '이병철', '서울특별시 영등포구 여의대방로47길 12 ,(신길동) (신길제7동)', '02', '842', '5555', 20)
2021-08-18 17:41:04,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,560 INFO sqlalchemy.engine.base.Engine ('토마토어린이집', '황예은', '서울특별시 양천구 목동서로 70 ,219동 104호(목동, 목동2단지아파트) (목5동)', '070', '7553', '2925', 19)
2021-08-18 17:41:04,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,562 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '서영식', '서울특별시 강동구 양재대로101길 51-10 ,104동 101호(성내동, 우성A 104-101) (성내제3동)', '02', '483', '8295', 2)
2021-08-18 17:41:04,563 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,564 INFO sqlalchemy.engine.base.Engine ('해오름 어린이집', '김지영', '서울특별시 영등포구 여의대방로31길 10 ,(신길동) (신길제6동)', '02', '846', '1323', 20)
2021-08-18 17:41:04,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,566 INFO sqlalchemy.engine.base.Engine ('한양자연어린이집', '장민재', '서울특별시 노원구 공릉로 213 ,103동 104호(공릉동, 동신) (공릉2동)', '02', '976', '7771', 9)
2021-08-18 17:41:04,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,568 INFO sqlalchemy.engine.base.Engine ('행복한아이세상어린이집', '황경회', '서울특별시 노원구 동일로227길 26 ,1609동 101호(상계동, 상계주공16차) (상계8동)', '02', '932', '5506', 9)
2021-08-18 17:41:04,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,571 INFO sqlalchemy.engine.base.Engine ('꿈이있는어린이집', '강성호', '서울특별시 구로구 벚꽃로 484 ,화원사회종합복지관내 (구로동) (구로제2동)', '02', '863', '0106', 7)
2021-08-18 17:41:04,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,573 INFO sqlalchemy.engine.base.Engine ('건영어린이집', '최예은', '서울특별시 중랑구 신내로7나길 24 ,206동 101호(상봉동, 건영2차아파트) (상봉제1동)', '02', '496', '0434', 25)
2021-08-18 17:41:04,579 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,580 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '황지영', '서울특별시 서초구 청두곶길 46 ,1층 (방배동) (방배2동)', '02', '588', '5354', 15)
2021-08-18 17:41:04,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,582 INFO sqlalchemy.engine.base.Engine ('삼성푸른어린이집', '권정자', '서울특별시 마포구 만리재로 74 ,204동 102호(신공덕동, 삼성래미안아파트) (공덕동)', '02', '712', '5543', 13)
2021-08-18 17:41:04,584 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,585 INFO sqlalchemy.engine.base.Engine ('아이뜰 어린이집', '최준영', '서울특별시 성북구 화랑로48길 16 ,109동 101호(석관동, 두산아파트) (석관동)', '02', '965', '7907', 17)
2021-08-18 17:41:04,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,587 INFO sqlalchemy.engine.base.Engine ('봄샘푸르지오어린이집', '한광수', '서울특별시 관악구 남부순환로 1430 ,관리동 1층 (신림동, 대우푸르지오아파트) [미성동] (미성동)', '02', '830', '6654', 5)
2021-08-18 17:41:04,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,590 INFO sqlalchemy.engine.base.Engine ('세림 어린이집', '강영길', '서울특별시 성동구 마장로42길 14 ,6동 104호(마장동, 세림아파트) (마장동)', '02', '2298', '1553', 16)
2021-08-18 17:41:04,592 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,593 INFO sqlalchemy.engine.base.Engine ('우리들어린이집', '강민재', '서울특별시 양천구 신월로11길 36 ,,101동 104호(신월동, 정은스카이빌아파트) (신월4동)', '02', '2693', '6434', 19)
2021-08-18 17:41:04,594 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,595 INFO sqlalchemy.engine.base.Engine ('꼬마성어린이집', '황상훈', '서울특별시 노원구 초안산로1길 18 ,214동 102호(월계동, 월계주공2단지아파트) (월계2동)', '02', '904', '5279', 9)
2021-08-18 17:41:04,596 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,597 INFO sqlalchemy.engine.base.Engine ('꿈쟁이어린이집', '송지영', '서울특별시 노원구 동일로214길 21 ,411동 106호(상계동, 주공아파트) (상계6.7동)', '02', '6224', '1479', 9)
2021-08-18 17:41:04,598 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,598 INFO sqlalchemy.engine.base.Engine ('래미안어린이집', '장성수', '서울특별시 성북구 길음로9길 40 ,삼성래미안1차아파트 (길음동) (길음제1동)', '02', '919', '8086', 17)
2021-08-18 17:41:04,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,600 INFO sqlalchemy.engine.base.Engine ('구립 보듬손어린이집', '강민재', '서울특별시 은평구 통일로78길 16 ,(불광동) (불광제1동)', '02', '354', '3388', 22)
2021-08-18 17:41:04,602 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,603 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '윤건우', '서울특별시 송파구 백제고분로36가길 21 ,(석촌동) (석촌동)', '02', '416', '2515', 18)
2021-08-18 17:41:04,604 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,606 INFO sqlalchemy.engine.base.Engine ('영재키즈어린이집', '서정식', '서울특별시 은평구 은평터널로 60 ,102동 101호(수색동, 진흥엣세벨) (수색동)', '02', '303', '6703', 22)
2021-08-18 17:41:04,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,608 INFO sqlalchemy.engine.base.Engine ('딸기어린이집', '신준서', '서울특별시 은평구 진흥로1길 50 ,딩크아파트 101호 (역촌동) (역촌동)', '02', '353', '7890', 22)
2021-08-18 17:41:04,609 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,610 INFO sqlalchemy.engine.base.Engine ('캐비스쿨예랑어린이집', '황경회', '서울특별시 마포구 월드컵북로 260 ,30동 101호(성산동, 성산시영) (성산제2동)', '02', '306', '0070', 13)
2021-08-18 17:41:04,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,613 INFO sqlalchemy.engine.base.Engine ('금융감독원어린이집', '정민서', '서울특별시 영등포구 여의대로 38 ,금융감독원어린이집 (여의도동) (여의동)', '02', '3145', '6050', 20)
2021-08-18 17:41:04,614 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,615 INFO sqlalchemy.engine.base.Engine ('로뎀어린이집', '전수빈', '서울특별시 동작구 양녕로26길 11 ,A동 102호(상도동, 약수맨션아파트) (상도제4동)', '02', '823', '1187', 12)

2021-08-18 17:41:04,616 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,617 INFO sqlalchemy.engine.base.Engine ('SK어린이집', '임건우', '서울특별시 강북구 솔샘로 174 ,104동 102호(미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '982', '3728', 3)
2021-08-18 17:41:04,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,619 INFO sqlalchemy.engine.base.Engine ('새조양어린이집', '류은경', '서울특별시 성북구 정릉로38다길 6 ,(정릉동) (정릉제1동)', '02', '913', '8552', 17)
2021-08-18 17:41:04,621 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,622 INFO sqlalchemy.engine.base.Engine ('에코빌i어린이집', '권지은', '서울특별시 도봉구 도봉로180길 6-23 ,104동 102호(도봉동, 동아에코빌아파트) (도봉제2동)', '02', '3492', '5333', 10)
2021-08-18 17:41:04,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,624 INFO sqlalchemy.engine.base.Engine ('가나어린이집', '김경자', '서울특별시 관악구 당곡6길 16-3 ,보라매동] (봉천동) (보라매동)', '02', '877', '4804', 5)
2021-08-18 17:41:04,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,626 INFO sqlalchemy.engine.base.Engine ('아기별어린이집', '송준호', '서울특별시 노원구 한글비석로 396 ,105동 109호(상계동, 벽산) (상계5동)', '02', '6229', '8864', 9)
2021-08-18 17:41:04,627 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,628 INFO sqlalchemy.engine.base.Engine ('푸른하늘어린이집', '최경자', '서울특별시 성북구 길음로 119 ,205동 102호(길음동, 대우아파트) (길음제1동)', '02', '911', '6227', 17)
2021-08-18 17:41:04,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,629 INFO sqlalchemy.engine.base.Engine ('미주키즈어린이집', '윤성호', '서울특별시 동대문구 약령시로 154 ,3동 105호(청량리동, 미주아파트) (청량리동)', '02', '959', '5941', 11)
2021-08-18 17:41:04,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,631 INFO sqlalchemy.engine.base.Engine ('아이다움어린이집', '장도현', '서울특별시 도봉구 도당로 13 ,102동 101호(쌍문동, 쌍문청구아파트) (쌍문제2동)', '02', '6227', '8277', 10)
2021-08-18 17:41:04,632 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,633 INFO sqlalchemy.engine.base.Engine ('예뜨락어린이집', '임준호', '서울특별시 은평구 갈현로7길 9 ,1층 (역촌동) (역촌동)', '02', '357', '0740', 22)
2021-08-18 17:41:04,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,636 INFO sqlalchemy.engine.base.Engine ('사랑 어린이집', '윤순자', '서울특별시 성동구 무학로 50 ,107동 107호(하왕십리동, 청계벽산아파트) (왕십리도선동)', '02', '2294', '2989', 16)
2021-08-18 17:41:04,637 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,638 INFO sqlalchemy.engine.base.Engine ('아이파크어린이집', '조영식', '서울특별시 강서구 등촌로 163 ,203동 103호(등촌동, 등촌동아이파크아파트) (등촌제2동)', '02', '2645', '2629', 4)
2021-08-18 17:41:04,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,640 INFO sqlalchemy.engine.base.Engine ('열린삐아제 어린이집', '윤성호', '서울특별시 강동구 고덕로62길 29 ,101동 105호(명일동, 명일삼환아파트) (명일제2동)', '02', '428', '3223', 2)
2021-08-18 17:41:04,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,642 INFO sqlalchemy.engine.base.Engine ('영재어린이집', '강정순', '서울특별시 성북구 월계로36길 27 ,103동 103호 (장위제3동)', '02', '909', '2777', 17)
2021-08-18 17:41:04,645 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,646 INFO sqlalchemy.engine.base.Engine ('엘프어린이집', '전준혁', '서울특별시 동작구 동작대로29길 110 ,403동 102호(사당동, 신동아4차아파트) (사당제2동)', '02', '594', '2505', 12)
2021-08-18 17:41:04,647 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,648 INFO sqlalchemy.engine.base.Engine ('삼성한울어린이집', '송성민', '서울특별시 서대문구 통일로 319 ,101동 102호(홍제동, 홍제삼성래미안) (홍제제1동)', '02', '722', '2219', 14)
2021-08-18 17:41:04,650 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,650 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '오성호', '서울특별시 서대문구 세검정로 134 ,104동 110호(홍제동, 유원하나아파트) (홍제제3동)', '02', '391', '0650', 14)
2021-08-18 17:41:04,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,652 INFO sqlalchemy.engine.base.Engine ('도림방과후교실어린이집', '김경숙', '서울특별시 영등포구 도영로 37 ,(도림동) (도림동)', '02', '2181', '6130', 20)
2021-08-18 17:41:04,654 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,655 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '정현준', '서울특별시 마포구 성미산로 25-6 (성산제1동)', '02', '324', '0933', 13)
2021-08-18 17:41:04,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,658 INFO sqlalchemy.engine.base.Engine ('예진선교어린이집', '박영환', '서울특별시 관악구 관악로12길 9 ,(봉천동) [낙성대동] (낙성대동)', '02', '872', '7471', 5)
2021-08-18 17:41:04,659 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,660 INFO sqlalchemy.engine.base.Engine ('햇살가득 어린이집', '강지혜', '서울특별시 성북구 길음로 119 ,212동 103호(길음동, 대우아파트) (길음제1동)', '02', '919', '5252', 17)
2021-08-18 17:41:04,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,662 INFO sqlalchemy.engine.base.Engine ('예능 어린이집', '서서현', '서울특별시 성북구 길음로 118 ,418동 102호(길음동, 길음뉴타운) (길음제1동)', '02', '942', '7090', 17)
2021-08-18 17:41:04,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,664 INFO sqlalchemy.engine.base.Engine ('사랑둥이어린이집', '안순자', '서울특별시 강서구 강서로 348 ,111동 101호(내발산동, 우장산현대홈타운아파트) (우장산동)', '02', '2668', '1515', 4)
2021-08-18 17:41:04,665 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,666 INFO sqlalchemy.engine.base.Engine ('키즈월드어린이집', '정은영', '서울특별시 강서구 강서로 348 ,115동 102호(내발산동, 현대홈타운) (우장산동)', '02', '3661', '0208', 4)
2021-08-18 17:41:04,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,668 INFO sqlalchemy.engine.base.Engine ('늘사랑어린이집', '박건우', '서울특별시 금천구 시흥대로47길 43 ,5동 101호(시흥동, 럭키남서울아파트) (시흥제1동)', '02', '802', '8893', 8)
2021-08-18 17:41:04,669 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,670 INFO sqlalchemy.engine.base.Engine ('e-편한세상 어린이집', '장성호', '서울특별시 성북구 길음로 118 ,418동 104호(길음동, 대림아파트) (길음제1동)', '02', '909', '3434', 17)
2021-08-18 17:41:04,671 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,672 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '이유진', '서울특별시 동작구 성대로3길 13 ,(상도동) (상도제4동)', '02', '827', '0331', 12)
2021-08-18 17:41:04,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,674 INFO sqlalchemy.engine.base.Engine ('샘물어린이집', '권서현', '서울특별시 노원구 마들로 111 ,19동 109호(월계동, 미륭아파트) (월계3동)', '02', '6221', '4314', 9)
2021-08-18 17:41:04,676 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,676 INFO sqlalchemy.engine.base.Engine ('착한어린이집', '김준혁', '서울특별시 광진구 뚝섬로52다길 17 ,(자양동) (자양제2동)', '02', '453', '3072', 6)
2021-08-18 17:41:04,677 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,678 INFO sqlalchemy.engine.base.Engine ('천사나라어린이집', '송정호', '서울특별시 동대문구 제기로 131 ,106동 103호(청량리동, 청량한2차신아파트) (청량리동)', '02', '967', '0172', 11)
2021-08-18 17:41:04,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,679 INFO sqlalchemy.engine.base.Engine ('나무와열매어린이집', '한정호', '서울특별시 강서구 방화대로48길 40 ,방화2단지아파트(방화동) (방화제3동)', '02', '2662', '6668', 4)
2021-08-18 17:41:04,680 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,681 INFO sqlalchemy.engine.base.Engine ('텀블랜드어린이집', '송미영', '서울특별시 서초구 바우뫼로37길 9 ,(양재동) (양재1동)', '02', '3463', '3305', 15)
2021-08-18 17:41:04,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,683 INFO sqlalchemy.engine.base.Engine ('한아름어린이집', '강정자', '서울특별시 동대문구 장안벚꽃로 167 ,삼성래미안2차아파트단지내 (장안동) (장안제2동)', '02', '2245', '0105', 11)
2021-08-18 17:41:04,685 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,686 INFO sqlalchemy.engine.base.Engine ('함께행복한어린이집', '정정수', '서울특별시 동대문구 왕산로23길 89 ,103동 105호(제기동, 이수브라운 스톤아파트) (제기동)', '02', '925', '5123', 11)
2021-08-18 17:41:04,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,687 INFO sqlalchemy.engine.base.Engine ('미성어린이집', '강정호', '서울특별시 노원구 마들로 111 ,15동 102호(월계동, 미성) (월계3동)', '02', '948', '5391', 9)
2021-08-18 17:41:04,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,689 INFO sqlalchemy.engine.base.Engine ('동심영재어린이집', '박예은', '서울특별시 마포구 월드컵로31길 78 ,(망원동) (망원제2동)', '02', '322', '7826', 13)
2021-08-18 17:41:04,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,691 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '강예은', '서울특별시 관악구 조원로16길 34 ,2층 (신림동) [조원동] (조원동)', '02', '862', '1004', 5)
2021-08-18 17:41:04,695 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,695 INFO sqlalchemy.engine.base.Engine ('길음빛어린이집', '황정식', '서울특별시 성북구 길음로 92 ,(길음동) (길음제1동)', '02', '942', '4881', 17)
2021-08-18 17:41:04,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,697 INFO sqlalchemy.engine.base.Engine ('꿈빛어린이집', '류은영', '서울특별시 강서구 화곡로34길 13 ,동광빌라 101 (화곡동) (화곡본동)', '02', '2690', '7955', 4)
2021-08-18 17:41:04,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,699 INFO sqlalchemy.engine.base.Engine ('선유몬테소리어린이집', '안지훈', '서울특별시 영등포구 양평로24길 9 ,104동 105호(양평동5가, 한신아파트) (양평제2동)', '02', '2677', '2339', 20)
2021-08-18 17:41:04,700 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,701 INFO sqlalchemy.engine.base.Engine ('해뜨는어린이집', '강수빈', '서울특별시 은평구 통일로77길 20 ,(대조동) (대조동)', '02', '354', '9135', 22)
2021-08-18 17:41:04,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,704 INFO sqlalchemy.engine.base.Engine ('희망어린이집', '김서현', '서울특별시 성북구 장위로31길 17-22 ,희망어린이집 (장위동) (장위제1동)', '02', '943', '1475', 17)
2021-08-18 17:41:04,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,706 INFO sqlalchemy.engine.base.Engine ('참예쁜어린이집', '전건우', '서울특별시 노원구 중계로8길 29 ,104동 104호(중계동, 한화꿈에그린아파트) (중계본동)', '02', '936', '7757', 9)
2021-08-18 17:41:04,707 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,707 INFO sqlalchemy.engine.base.Engine ('아드래따래i어린이집', '황미영', '서울특별시 노원구 중계로8길 29 ,102동 102호(중계동, 한화꿈에그린아파트) (중계본동)', '02', '935', '9003', 9)
2021-08-18 17:41:04,708 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,709 INFO sqlalchemy.engine.base.Engine ('고운꽃뜰 어린이집', '이건우', '서울특별시 성동구 행당로 79 ,120동 102호(행당동, 대림이편한세상아파트) (행당제2동)', '02', '2293', '2708', 16)
2021-08-18 17:41:04,712 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,712 INFO sqlalchemy.engine.base.Engine ('엄마무릎베베어린이집', '조정호', '서울특별시 도봉구 도봉로170길 40 ,104동 102호(도봉동, 도봉래미안아파트) (도봉제2동)', '02', '956', '0333', 10)
2021-08-18 17:41:04,713 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,714 INFO sqlalchemy.engine.base.Engine ('코레일오류동어린이집', '윤영길', '서울특별시 구로구 경인로20가길 24 ,오류동 행복주택 내 직장어린이집 (오류제1동)', '02', '2612', '2762', 7)
2021-08-18 17:41:04,715 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,716 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '서준서', '서울특별시 성북구 정릉로 305 ,101동 103호(정릉동, 경남아파트) (정릉제1동)', '02', '6231', '6997', 17)
2021-08-18 17:41:04,717 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,718 INFO sqlalchemy.engine.base.Engine ('구립 연화어린이집', '안광수', '서울특별시 마포구 도화4길 94 ,(도화동) (도화동)', '02', '713', '8318', 13)
2021-08-18 17:41:04,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,720 INFO sqlalchemy.engine.base.Engine ('궁더쿵어린이집', '조건우', '서울특별시 구로구 오리로20길 32 ,(궁동 평화교회1층) (수궁동)', '02', '2625', '9769', 7)

2021-08-18 17:41:04,721 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,722 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '서예은', '서울특별시 광진구 자양로51길 11-12 ,(구의동) (구의제2동)', '02', '447', '1477', 6)
2021-08-18 17:41:04,723 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,724 INFO sqlalchemy.engine.base.Engine ('젬젬어린이집', '황예은', '서울특별시 관악구 봉천로 387 ,1동 1층(봉천동, 두산아파트) (은천동)', '02', '3285', '7406', 5)
2021-08-18 17:41:04,726 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,727 INFO sqlalchemy.engine.base.Engine ('현대키즈어린이집', '류성수', '서울특별시 강남구 학동로68길 29 ,105동 103호(삼성동, 삼성동힐스테이트1차아파트) (삼성제2동)', '02', '542', '0561', 1)
2021-08-18 17:41:04,728 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,729 INFO sqlalchemy.engine.base.Engine ('멘토어린이집', '최도현', '서울특별시 구로구 연동로13길 25 ,111동 104호(항동, 서울수목원 현대홈타운 스위트) (항동)', '02', '6404', '8822', 7)
2021-08-18 17:41:04,730 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,730 INFO sqlalchemy.engine.base.Engine ('예나어린이집', '한상철', '서울특별시 도봉구 시루봉로22길 27-17 (방학제2동)', '02', '3494', '0155', 10)
2021-08-18 17:41:04,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,735 INFO sqlalchemy.engine.base.Engine ('선교어린이집', '권종수', '서울특별시 양천구 신월로15길 21 ,103동 104호(신월동, 대성유니드아파트) (신월4동)', '02', '6741', '6500', 19)
2021-08-18 17:41:04,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,737 INFO sqlalchemy.engine.base.Engine ('뽀뽀뽀어린이집', '이민석', '서울특별시 양천구 신월로15길 21 ,105동 103호(신월동, 대성유니드아파트) (신월4동)', '02', '2692', '5967', 19)
2021-08-18 17:41:04,738 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,739 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '류혜진', '서울특별시 도봉구 도봉로136길 28 ,(창동) (창제5동)', '02', '999', '2008', 10)
2021-08-18 17:41:04,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,740 INFO sqlalchemy.engine.base.Engine ('서울청사한빛어린이집', '오정호', '서울특별시 종로구 세종대로 209 ,서울청사관리소 (사직동)', '02', '735', '6400', 23)
2021-08-18 17:41:04,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,742 INFO sqlalchemy.engine.base.Engine ('규현어린이집', '윤미숙', '서울특별시 동대문구 한천로58길 47 ,103동 102호(이문동, 쌍용아파트) (이문제2동)', '02', '6221', '4386', 11)
2021-08-18 17:41:04,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,743 INFO sqlalchemy.engine.base.Engine ('꿀벌어린이집', '류건우', '서울특별시 동대문구 장안벚꽃로 167 ,224동 102호(장안동, 장안아파트2단지) (장안제2동)', '02', '2249', '3739', 11)
2021-08-18 17:41:04,744 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,745 INFO sqlalchemy.engine.base.Engine ('조앤아이어린이집', '조성호', '서울특별시 동대문구 장안벚꽃로 167 ,215동 102호(장안동, 장안아파트2단지) (장안제2동)', '02', '2246', '2789', 11)
2021-08-18 17:41:04,746 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,747 INFO sqlalchemy.engine.base.Engine ('상계백병원어린이집', '전상철', '서울특별시 노원구 상계로12길 12-10 ,인성관1층 (상계동) (상계2동)', '02', '950', '4893', 9)
2021-08-18 17:41:04,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,749 INFO sqlalchemy.engine.base.Engine ('떡잎어린이집', '이혜진', '서울특별시 관악구 장군봉7길 12 ,청룡동] (봉천동) (청룡동)', '02', '879', '2844', 5)
2021-08-18 17:41:04,750 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,751 INFO sqlalchemy.engine.base.Engine ('샤론어린이집', '황영진', '서울특별시 동작구 동작대로39가길 55 ,104동 103호(동작동, 금강케이씨씨아파트) (사당제2동)', '02', '537', '9547', 12)
2021-08-18 17:41:04,752 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,752 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '오은경', '서울특별시 동작구 상도로 107 ,쌍용스위트닷홈아파트상가아이세상어린이집 (상도동) (상도제3동)', '02', '812', '6775', 12)
2021-08-18 17:41:04,753 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,754 INFO sqlalchemy.engine.base.Engine ('월곡어린이집', '최미경', '서울특별시 성북구 오패산로16길 23 ,(하월곡동) (월곡제1동)', '02', '916', '2188', 17)
2021-08-18 17:41:04,755 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,756 INFO sqlalchemy.engine.base.Engine ('참빛어린이집', '박영길', '서울특별시 강북구 한천로109길 81-21 (번3동)', '02', '987', '6854', 3)
2021-08-18 17:41:04,757 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,758 INFO sqlalchemy.engine.base.Engine ('홍은어린이집', '장혜진', '서울특별시 서대문구 모래내로 332-10 ,구립 홍은어린이집 (홍은동) (홍은제2동)', '02', '391', '9002', 14)
2021-08-18 17:41:04,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,759 INFO sqlalchemy.engine.base.Engine ('마포구청 직장어린이집', '오은경', '서울특별시 마포구 월드컵로 212 ,마포구청 1층 (성산제2동)', '02', '302', '8754', 13)
2021-08-18 17:41:04,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,761 INFO sqlalchemy.engine.base.Engine ('삼성짐키드어린이집', '신지원', '서울특별시 동작구 상도로53길 8 ,삼성래미안3차아파트 단지내 삼성짐키드어린이집 (상도동) (상도제1동)', '02', '813', '3332', 12)
2021-08-18 17:41:04,761 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,762 INFO sqlalchemy.engine.base.Engine ('새동산어린이집', '신성진', '서울특별시 구로구 구일로4길 65 ,113동 104호(구로동, 구로주공아파트) (구로제1동)', '02', '838', '8333', 7)
2021-08-18 17:41:04,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,763 INFO sqlalchemy.engine.base.Engine ('영재키즈어린이집', '이미영', '서울특별시 노원구 상계로 193-14 ,103동 101호(상계동, 상계대림E편한세상) (상계3.4동)', '02', '932', '6464', 9)
2021-08-18 17:41:04,765 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,770 INFO sqlalchemy.engine.base.Engine ('삼성어린이집', '황민지', '서울특별시 성동구 용답중앙11다길 22 ,(용답동) (용답동)', '02', '2244', '3775', 16)
2021-08-18 17:41:04,772 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,773 INFO sqlalchemy.engine.base.Engine ('그랑빌어린이집', '장도현', '서울특별시 노원구 마들로 31 ,118동 104호(월계동, 한진한화그랑빌) (월계3동)', '02', '979', '1190', 9)
2021-08-18 17:41:04,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,776 INFO sqlalchemy.engine.base.Engine ('키즈랜드어린이집', '전준영', '서울특별시 금천구 금하로 816 ,512동 102호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '896', '9171', 8)
2021-08-18 17:41:04,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,777 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '안민지', '서울특별시 송파구 삼학사로13길 12 ,(삼전동) (삼전동)', '02', '412', '6918', 18)
2021-08-18 17:41:04,779 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,779 INFO sqlalchemy.engine.base.Engine ('고은어린이집', '안성진', '서울특별시 노원구 동일로208길 20 ,211동 106호(중계동, 중계무지개아파트) (중계2.3동)', '02', '978', '9016', 9)
2021-08-18 17:41:04,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,781 INFO sqlalchemy.engine.base.Engine ('구산방과후교실어린이집', '장정식', '서울특별시 은평구 연서로11길 32 ,구산교회방과후교실 (구산동) (구산동)', '02', '386', '4070', 22)
2021-08-18 17:41:04,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,783 INFO sqlalchemy.engine.base.Engine ('성민어린이집', '류수빈', '서울특별시 구로구 고척로21나길 48-41 (개봉제1동)', '02', '2689', '1040', 7)
2021-08-18 17:41:04,784 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,785 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '서예은', '서울특별시 광진구 아차산로 451 ,101동 105호(구의동, 세림리오빌) (구의제3동)', '02', '447', '0739', 6)
2021-08-18 17:41:04,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,788 INFO sqlalchemy.engine.base.Engine ('행복숲어린이집', '윤지영', '서울특별시 송파구 문정로13길 14 (가락2동)', '02', '443', '3337', 18)
2021-08-18 17:41:04,790 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,792 INFO sqlalchemy.engine.base.Engine ('이슬어린이집', '조서현', '서울특별시 강동구 양재대로134길 87 ,101동 104호(명일동, 현대) (명일제1동)', '02', '3426', '9544', 2)
2021-08-18 17:41:04,793 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,794 INFO sqlalchemy.engine.base.Engine ('현대키즈어린이집', '송혜진', '서울특별시 강서구 양천로75길 19 ,107동 104호(염창동, 현대홈타운아파트) (염창동)', '02', '3665', '3717', 4)
2021-08-18 17:41:04,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,795 INFO sqlalchemy.engine.base.Engine ('글샘어린이집', '권준서', '서울특별시 동대문구 천호대로35길 39 ,(용두동) (용신동)', '02', '969', '0073', 11)
2021-08-18 17:41:04,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,797 INFO sqlalchemy.engine.base.Engine ('꿈그린어린이집', '권예준', '서울특별시 관악구 관악로 285 ,108동 101호(봉천동, 봉천동아1차아파트) [성현동] (성현동)', '02', '6335', '1190', 5)
2021-08-18 17:41:04,798 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,799 INFO sqlalchemy.engine.base.Engine ('사랑스런어린이집', '황영진', '서울특별시 동대문구 왕산로43길 74 ,1층 (청량리동) (청량리동)', '02', '967', '0415', 11)
2021-08-18 17:41:04,800 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,801 INFO sqlalchemy.engine.base.Engine ('신동아 어린이집', '안정호', '서울특별시 서초구 사임당로 130 ,7동 113호(서초동, 신동아아파트) (서초2동)', '02', '522', '1163', 15)
2021-08-18 17:41:04,802 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,805 INFO sqlalchemy.engine.base.Engine ('예원i어린이집', '한혜진', '서울특별시 노원구 마들로 59 ,11동 105호(월계동,미성아파트) (월계3동)', '02', '975', '6114', 9)
2021-08-18 17:41:04,808 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,810 INFO sqlalchemy.engine.base.Engine ('예지원어린이집', '권정수', '서울특별시 강북구 삼양로98길 7 ,(수유동) (수유3동)', '02', '905', '9282', 3)
2021-08-18 17:41:04,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,813 INFO sqlalchemy.engine.base.Engine ('주영광어린이집', '최민지', '서울특별시 강북구 한천로 1004 ,(번동) (번1동)', '02', '999', '0548', 3)
2021-08-18 17:41:04,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,815 INFO sqlalchemy.engine.base.Engine ('지안어린이집', '송준호', '서울특별시 광진구 뚝섬로58가길 26-4 ,(자양동) (자양제2동)', '02', '3436', '3866', 6)
2021-08-18 17:41:04,817 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,818 INFO sqlalchemy.engine.base.Engine ('초록햇살어린이집', '오준영', '서울특별시 동작구 상도로41길 15 ,(상도1동) (상도제1동)', '02', '816', '3334', 12)
2021-08-18 17:41:04,819 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,820 INFO sqlalchemy.engine.base.Engine ('콩알어린이집', '김지원', '서울특별시 도봉구 덕릉로66길 17 ,1705동 112호(창동, 상계주공17차아파트) (창제4동)', '02', '902', '2533', 10)
2021-08-18 17:41:04,822 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,823 INFO sqlalchemy.engine.base.Engine ('해피둥지어린이집', '윤수빈', '서울특별시 도봉구 덕릉로62길 38 ,(창동) (창제3동)', '02', '900', '3712', 10)
2021-08-18 17:41:04,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,825 INFO sqlalchemy.engine.base.Engine ('꼬마사랑어린이집', '송성수', '서울특별시 광진구 긴고랑로8길 14 ,(중곡동) (중곡제1동)', '02', '464', '6788', 6)
2021-08-18 17:41:04,826 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,827 INFO sqlalchemy.engine.base.Engine ('보배어린이집', '류영자', '서울특별시 광진구 아차산로36길 39 ,3동 1호(자양동, 자양우성7차아파트) (자양제3동)', '02', '457', '1565', 6)
2021-08-18 17:41:04,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,829 INFO sqlalchemy.engine.base.Engine ('소꿉 어린이집', '정준호', '서울특별시 강남구 개포로 516 ,603동 108호(개포동,주공아파트) (개포제2동)', '02', '3462', '6223', 1)
2021-08-18 17:41:04,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,831 INFO sqlalchemy.engine.base.Engine ('아람어린이집', '강준호', '서울특별시 은평구 연서로27길 19-1 (갈현제2동)', '02', '358', '4586', 22)
2021-08-18 17:41:04,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,833 INFO sqlalchemy.engine.base.Engine ('아침햇살어린이집', '김정수', '서울특별시 중랑구 면목로54길 67 ,(면목동 433-34) (면목제3.8동)', '02', '492', '4440', 25)
2021-08-18 17:41:04,835 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,835 INFO sqlalchemy.engine.base.Engine ('앙코아어린이집', '윤민석', '서울특별시 성북구 장월로 54 (장위제2동)', '02', '913', '6860', 17)
2021-08-18 17:41:04,836 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,837 INFO sqlalchemy.engine.base.Engine ('영등포사임당어린이집', '안준혁', '서울특별시 영등포구 양산로 177 ,경남아너스빌아파트 관리동 (영등포동7가) (영등포동)', '02', '2676', '0579', 20)
2021-08-18 17:41:04,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,840 INFO sqlalchemy.engine.base.Engine ('영성어린이집', '강정호', '서울특별시 영등포구 영중로33길 9 ,비동(영등포성결교회내) (영등포동8가) (영등포동)', '02', '2676', '4276', 20)
2021-08-18 17:41:04,841 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,843 INFO sqlalchemy.engine.base.Engine ('유신어린이집', '정경자', '서울특별시 관악구 난곡로 84 ,2층 (신림동) [난향동] (난향동)', '02', '861', '3551', 5)
2021-08-18 17:41:04,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,859 INFO sqlalchemy.engine.base.Engine ('코코어린이집', '임민지', '서울특별시 서초구 명달로4길 8 ,정양빌딩 1층 (서초동) (서초3동)', '02', '586', '5254', 15)
2021-08-18 17:41:04,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,861 INFO sqlalchemy.engine.base.Engine ('동광어린이집', '전미경', '서울특별시 강서구 양천로75길 57 ,104동 110호(염창동 288, 현대1차) (염창동)', '02', '6734', '9988', 4)
2021-08-18 17:41:04,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,863 INFO sqlalchemy.engine.base.Engine ('동산어린이집', '신영진', '서울특별시 강서구 양천로75길 44 ,(염창동) (염창동)', '02', '2658', '6267', 4)
2021-08-18 17:41:04,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,865 INFO sqlalchemy.engine.base.Engine ('리라빅스맘어린이집', '최혜진', '서울특별시 양천구 남부순환로40가길 12-2 (신월3동)', '02', '2696', '1120', 19)
2021-08-18 17:41:04,867 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,868 INFO sqlalchemy.engine.base.Engine ('별초롱 어린이집', '황성수', '서울특별시 성동구 성수동1가 성덕정길 25-96 (성수1가제1동)', '02', '468', '0190', 16)
2021-08-18 17:41:04,869 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,870 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '윤민서', '서울특별시 노원구 초안산로1길 18 ,205동 103호(월계동, 월계주공2단지아파트) (월계2동)', '02', '6224', '8787', 9)
2021-08-18 17:41:04,872 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,872 INFO sqlalchemy.engine.base.Engine ('에덴동산Kids 어린이집', '송지혜', '서울특별시 강동구 상일로5길 10-14 ,(상일동270-2) (상일제1동)', '02', '428', '4527', 2)
2021-08-18 17:41:04,874 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,875 INFO sqlalchemy.engine.base.Engine ('은하어린이집', '장준호', '서울특별시 마포구 독막로34길 30 ,(신수동) (신수동)', '02', '713', '1686', 13)
2021-08-18 17:41:04,876 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,877 INFO sqlalchemy.engine.base.Engine ('한사랑 어린이집', '황정웅', '서울특별시 영등포구 선유로43가길 24 ,107동 102호(양평동3가, 거성파스텔아파트) (양평제2동)', '02', '6264', '3446', 20)
2021-08-18 17:41:04,878 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,879 INFO sqlalchemy.engine.base.Engine ('가람어린이집', '권혜진', '서울특별시 양천구 목동동로 50 ,1219동 106호(신정동,목동신시가지아파트) (신정7동)', '02', '2642', '7731', 19)
2021-08-18 17:41:04,880 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,881 INFO sqlalchemy.engine.base.Engine ('금빛 어린이집', '최지혜', '서울특별시 성동구 마장로37길 7 ,101동 102호(마장동, 대성유니드아파트) (마장동)', '02', '2291', '0555', 16)
2021-08-18 17:41:04,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,883 INFO sqlalchemy.engine.base.Engine ('노벨어린이집', '최병철', '서울특별시 성북구 정릉로8길 40-20 (정릉제3동)', '02', '943', '1145', 17)
2021-08-18 17:41:04,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,885 INFO sqlalchemy.engine.base.Engine ('예주어린이집', '황미영', '서울특별시 동작구 동작대로11길 77 ,1층 (사당동, 예주어린이집) (사당제1동)', '02', '521', '7739', 12)
2021-08-18 17:41:04,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,888 INFO sqlalchemy.engine.base.Engine ('왕성어린이집', '정준호', '서울특별시 관악구 신림로58길 10 ,서원동] (신림동) (서원동)', '02', '875', '8302', 5)
2021-08-18 17:41:04,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,890 INFO sqlalchemy.engine.base.Engine ('토마토어린이집', '신경회', '서울특별시 서초구 서초중앙로24길 43 ,101동 103호(서초동, 유원아파트) (서초4동)', '02', '534', '5235', 15)
2021-08-18 17:41:04,891 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,892 INFO sqlalchemy.engine.base.Engine ('하얀마음어린이집', '강지영', '서울특별시 강서구 초록마을로14길 24 ,(화곡동) (화곡본동)', '02', '2603', '3910', 4)
2021-08-18 17:41:04,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,895 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '임영진', '서울특별시 구로구 경인로 343 ,105동 104호(고척동, 삼환로즈빌) (고척제1동)', '02', '2066', '9998', 7)
2021-08-18 17:41:04,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,897 INFO sqlalchemy.engine.base.Engine ('참나무방과후 어린이집', '전지훈', '서울특별시 용산구 새창로12길 11-18 ,용산제일교회내 참나무방과후교실 (도원동) (용문동)', '02', '714', '0693', 21)
2021-08-18 17:41:04,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,900 INFO sqlalchemy.engine.base.Engine ('엔젤키즈어린이집', '김지민', '서울특별시 구로구 경인로 382 ,122동 101호(개봉동, 한마을아파트) (개봉제1동)', '02', '6095', '0079', 7)
2021-08-18 17:41:04,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,903 INFO sqlalchemy.engine.base.Engine ('참베이비스쿨어린이집', '정영철', '서울특별시 마포구 방울내로9안길 6 ,(망원동) (망원제2동)', '02', '322', '9553', 13)
2021-08-18 17:41:04,904 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,905 INFO sqlalchemy.engine.base.Engine ('기쁨어린이집', '류준혁', '서울특별시 은평구 가좌로 344 ,111동 102호(신사동, 현대2차아파트) (신사제1동)', '02', '386', '0366', 22)
2021-08-18 17:41:04,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,908 INFO sqlalchemy.engine.base.Engine ('둥지어린이집', '김미숙', '서울특별시 노원구 동일로207길 18 ,111동 104호(중계동, 중계그린1단지아파트) (중계2.3동)', '02', '973', '2508', 9)
2021-08-18 17:41:04,910 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,910 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '서상훈', '서울특별시 도봉구 해등로 242-12 ,현대아파트 101동 106호 (쌍문제4동)', '02', '990', '6677', 10)
2021-08-18 17:41:04,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,912 INFO sqlalchemy.engine.base.Engine ('꿈터어린이집', '오영환', '서울특별시 서초구 바우뫼로 91 ,101동 101호(양재동, 양재우성아파트) (양재1동)', '02', '587', '0669', 15)
2021-08-18 17:41:04,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,913 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '류준서', '서울특별시 성동구 둘레15길 15-1 (성수2가제1동)', '02', '469', '9566', 16)
2021-08-18 17:41:04,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,914 INFO sqlalchemy.engine.base.Engine ('동부어린이집', '오병철', '서울특별시 성북구 정릉로 388 ,동부센트레빌아파트 관리동 (돈암동) (돈암제1동)', '02', '927', '0185', 17)
2021-08-18 17:41:04,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,918 INFO sqlalchemy.engine.base.Engine ('물빛사랑어린이집', '박정순', '서울특별시 금천구 시흥대로40마길 23-1 (시흥제5동)', '02', '802', '8746', 8)
2021-08-18 17:41:04,919 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,920 INFO sqlalchemy.engine.base.Engine ('새롬어린이집', '신서현', '서울특별시 송파구 삼학사로6길 29 ,현대파크빌 101호 (석촌동) (석촌동)', '02', '418', '1379', 18)
2021-08-18 17:41:04,922 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,923 INFO sqlalchemy.engine.base.Engine ('새소망어린이집', '임정웅', '서울특별시 강서구 강서로18길 125 ,(화곡동) (화곡제2동)', '02', '2601', '0885', 4)
2021-08-18 17:41:04,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,925 INFO sqlalchemy.engine.base.Engine ('소라어린이집', '한서현', '서울특별시 강서구 곰달래로45길 15 ,1층 소라어린이집 (화곡제2동)', '02', '2601', '4788', 4)
2021-08-18 17:41:04,926 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,927 INFO sqlalchemy.engine.base.Engine ('숲속마을어린이집', '오수빈', '서울특별시 금천구 시흥대로88길 21-8 (독산제2동)', '02', '896', '9998', 8)
2021-08-18 17:41:04,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,929 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '김영식', '서울특별시 노원구 한글비석로 479 ,103동 104호(상계동, 보람1단지아파트) (상계9동)', '02', '6223', '5099', 9)
2021-08-18 17:41:04,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,932 INFO sqlalchemy.engine.base.Engine ('베들레헴 어린이집', '한미숙', '서울특별시 성북구 창경궁로35다길 108 ,(성북동) (성북동)', '02', '3676', '7705', 17)
2021-08-18 17:41:04,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,934 INFO sqlalchemy.engine.base.Engine ('우성그린어린이집', '오상철', '서울특별시 동대문구 답십리로59길 33 ,102동 101호(답십리동, 우성그린아파트) (답십리제2동)', '02', '6213', '0623', 11)
2021-08-18 17:41:04,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,936 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '전은정', '서울특별시 양천구 목동서로 280 ,806동 104호(신정동, 신시가지8단지아파트) (신정6동)', '02', '2647', '5233', 19)
2021-08-18 17:41:04,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,938 INFO sqlalchemy.engine.base.Engine ('베베키즈룸어린이집', '윤민재', '서울특별시 강남구 도곡로43길 21 ,래미안그레이튼1단지아파트 관리동 (역삼제2동)', '02', '557', '0509', 1)
2021-08-18 17:41:04,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,941 INFO sqlalchemy.engine.base.Engine ('예원어린이집', '윤영길', '서울특별시 강남구 논현로151길 32-1 (신사동)', '02', '518', '8907', 1)
2021-08-18 17:41:04,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,942 INFO sqlalchemy.engine.base.Engine ('세광어린이집', '송정자', '서울특별시 금천구 독산로 124 ,세광교회 내 (시흥동) (시흥제4동)', '02', '893', '4675', 8)
2021-08-18 17:41:04,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,946 INFO sqlalchemy.engine.base.Engine ('이편한어린이집', '장성민', '서울특별시 구로구 신도림로 16 ,대림아파트 관리동1층 (신도림동) (신도림동)', '02', '6741', '5629', 7)
2021-08-18 17:41:04,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,949 INFO sqlalchemy.engine.base.Engine ('조이어린이집', '이정식', '서울특별시 노원구 섬밭로 196 ,604동 104호(하계동, 장미) (하계2동)', '02', '6437', '9325', 9)
2021-08-18 17:41:04,950 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,951 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '최영숙', '서울특별시 금천구 시흥대로62가길 23-1 (시흥제1동)', '02', '892', '4588', 8)
2021-08-18 17:41:04,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,953 INFO sqlalchemy.engine.base.Engine ('아름다운어린이집', '박민서', '서울특별시 광진구 천호대로123길 34 ,(중곡동) (중곡제2동)', '02', '444', '5561', 6)
2021-08-18 17:41:04,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,955 INFO sqlalchemy.engine.base.Engine ('또래또어린이집', '임민수', '서울특별시 관악구 관악로30길 12 ,102동 108호(봉천동, 우성아파트) [행운동] (행운동)', '02', '871', '1316', 5)
2021-08-18 17:41:04,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,957 INFO sqlalchemy.engine.base.Engine ('빛나어린이집', '신민수', '서울특별시 구로구 구로중앙로18길 56 ,1동 104호(구로동, 성삼하이츠아파트) (구로제4동)', '02', '868', '3670', 7)
2021-08-18 17:41:04,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,958 INFO sqlalchemy.engine.base.Engine ('초록별어린이집', '서지훈', '서울특별시 노원구 한글비석로 56 ,3동 107호(하계동, 미성) (하계1동)', '02', '978', '5077', 9)
2021-08-18 17:41:04,959 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:04,960 INFO sqlalchemy.engine.base.Engine ('해피아이어린이집', '권민수', '서울특별시 노원구 노원로1가길 10 ,805동 101호(공릉동, 청솔8단지아파트) (공릉2동)', '02', '6224', '5321', 9)
2021-08-18 17:41:04,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,962 INFO sqlalchemy.engine.base.Engine ('맑은샘어린이집', '윤미숙', '서울특별시 양천구 목동동로 10 ,1119동 105호(신정동, 신시가지11단지아파트) (신정7동)', '02', '2644', '2296', 19)
2021-08-18 17:41:04,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,964 INFO sqlalchemy.engine.base.Engine ('삼성래미안어린이집', '정민석', '서울특별시 성북구 종암로25길 30 ,삼성래미안아파트 관리동 1층 (종암동) (종암동)', '02', '6431', '7707', 17)
2021-08-18 17:41:04,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,966 INFO sqlalchemy.engine.base.Engine ('예원비전스쿨어린이집', '권은영', '서울특별시 강서구 강서로24길 65 ,(화곡동) (화곡본동)', '02', '3665', '9126', 4)
2021-08-18 17:41:04,967 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,968 INFO sqlalchemy.engine.base.Engine ('완두콩어린이집', '박은정', '서울특별시 용산구 청파로71길 58 ,아이딜아파트 101호 (청파동1가) (청파동)', '02', '3272', '3368', 21)
2021-08-18 17:41:04,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,971 INFO sqlalchemy.engine.base.Engine ('주공신나는어린이집', '장민지', '서울특별시 동대문구 한천로 248 ,112동 101호(휘경동, 주공아파트) (휘경제2동)', '02', '6212', '7949', 11)
2021-08-18 17:41:04,972 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,972 INFO sqlalchemy.engine.base.Engine ('꿈보어린이집', '한정수', '서울특별시 성북구 북악산로 844 ,103동 103호(돈암동, 돈암이수브라운스톤아파트) (돈암제2동)', '02', '6218', '0808', 17)
2021-08-18 17:41:04,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,974 INFO sqlalchemy.engine.base.Engine ('꿈샘어린이집', '송종수', '서울특별시 양천구 은행정로 75 ,(신정동) 청원아파트 102호 (신정4동)', '02', '2603', '1578', 19)
2021-08-18 17:41:04,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,975 INFO sqlalchemy.engine.base.Engine ('뜰이삭어린이집', '안은경', '서울특별시 동작구 사당로20다길 1 ,(사당동) (사당제4동)', '02', '585', '0042', 12)
2021-08-18 17:41:04,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,977 INFO sqlalchemy.engine.base.Engine ('샘키즈어린이집', '윤은영', '서울특별시 양천구 남부순환로40길 65 (신월3동)', '02', '2692', '1619', 19)
2021-08-18 17:41:04,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,979 INFO sqlalchemy.engine.base.Engine ('쥬베베어린이집', '안준혁', '서울특별시 중랑구 신내로14길 21 ,쥬베베어린이집 (신내1동)', '02', '973', '1199', 25)
2021-08-18 17:41:04,981 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,982 INFO sqlalchemy.engine.base.Engine ('대림어린이집', '류민재', '서울특별시 구로구 신도림로 16 ,501동 102호(신도림동, 대림1차아파트) (신도림동)', '02', '2635', '7147', 7)
2021-08-18 17:41:04,984 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,986 INFO sqlalchemy.engine.base.Engine ('무지개 어린이집', '전유진', '서울특별시 성북구 북악산로 844 ,112동 104호 (돈암동, 브라운스톤 돈암 아파트) (돈암제2동)', '02', '6315', '0606', 17)
2021-08-18 17:41:04,988 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,989 INFO sqlalchemy.engine.base.Engine ('반석방과후어린이집', '권정남', '서울특별시 동대문구 답십리로58길 17 ,(답십리동) (답십리제2동)', '02', '2247', '0653', 11)
2021-08-18 17:41:04,990 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,991 INFO sqlalchemy.engine.base.Engine ('보림어린이집', '김지영', '서울특별시 동대문구 외대역동로 114-1 (이문제1동)', '02', '957', '3805', 11)
2021-08-18 17:41:04,992 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,993 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '이민지', '서울특별시 강남구 강남대로54길 9 ,한우리교회 (도곡동) (도곡제1동)', '02', '3462', '7881', 1)
2021-08-18 17:41:04,994 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,995 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '이현정', '서울특별시 관악구 조원로16길 7 ,102동 106호(신림동, 신도도브래뉴아파트) [조원동] (조원동)', '02', '830', '1210', 5)
2021-08-18 17:41:04,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,997 INFO sqlalchemy.engine.base.Engine ('내친구어린이집', '정서현', '서울특별시 관악구 장군봉2길 35 ,1층 [청룡동] (청룡동)', '02', '886', '3398', 5)
2021-08-18 17:41:04,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:04,999 INFO sqlalchemy.engine.base.Engine ('방주어린이집', '전정순', '서울특별시 강동구 천호대로187길 31 ,(길동 길1동 406-1) (길동)', '02', '470', '6613', 2)
2021-08-18 17:41:05,000 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,001 INFO sqlalchemy.engine.base.Engine ('스마일어린이집', '오정수', '서울특별시 구로구 구로동로43길 10 ,101동 104호(구로동, 우리유앤미아파트) (구로제2동)', '02', '854', '3808', 7)
2021-08-18 17:41:05,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,004 INFO sqlalchemy.engine.base.Engine ('키즈랜드어린이집', '강지민', '서울특별시 광진구 능동로48길 56 ,(중곡동) (중곡제2동)', '02', '453', '0860', 6)
2021-08-18 17:41:05,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,007 INFO sqlalchemy.engine.base.Engine ('푸른꿈어린이집', '김지민', '서울특별시 중랑구 공릉로12나길 16 (묵제1동)', '02', '948', '7977', 25)
2021-08-18 17:41:05,008 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,009 INFO sqlalchemy.engine.base.Engine ('하나어린이집', '최유진', '서울특별시 서대문구 통일로39가길 57 ,102동 102호(홍제동, 현대아파트) (홍제제1동)', '02', '391', '0826', 14)
2021-08-18 17:41:05,011 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,012 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '서은영', '서울특별시 동대문구 답십리로68길 52-4 (장안제1동)', '02', '2213', '2020', 11)
2021-08-18 17:41:05,013 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,014 INFO sqlalchemy.engine.base.Engine ('남문 어린이집', '최서현', '서울특별시 금천구 독산로94가길 29 (독산제3동)', '02', '862', '8671', 8)
2021-08-18 17:41:05,015 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,016 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '김민지', '서울특별시 강동구 천호대로174길 49 ,101동 101호(성내동386, 비앤비아파트) (성내제3동)', '02', '484', '9124', 2)
2021-08-18 17:41:05,017 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,018 INFO sqlalchemy.engine.base.Engine ('신사홍익어린이집', '권지훈', '서울특별시 은평구 은평터널로7길 3 ,(신사동) (신사제2동)', '02', '306', '5231', 22)
2021-08-18 17:41:05,019 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,020 INFO sqlalchemy.engine.base.Engine ('우리또래어린이집', '오예은', '서울특별시 동작구 상도로22나길 29 ,101호 (상도제4동)', '02', '821', '2280', 12)
2021-08-18 17:41:05,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,022 INFO sqlalchemy.engine.base.Engine ('천사마을어린이집', '오정자', '서울특별시 금천구 독산로24길 19 ,(시흥동) (시흥제4동)', '02', '892', '8004', 8)
2021-08-18 17:41:05,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,024 INFO sqlalchemy.engine.base.Engine ('슬기어린이집', '정준호', '서울특별시 관악구 남부순환로159길 5 ,(신림동) [신사동] (신사동)', '02', '852', '2770', 5)
2021-08-18 17:41:05,025 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,026 INFO sqlalchemy.engine.base.Engine ('영서어린이집', '박성민', '서울특별시 구로구 도림로20길 44 ,(구로동) (구로제3동)', '02', '852', '7790', 7)
2021-08-18 17:41:05,028 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,029 INFO sqlalchemy.engine.base.Engine ('예쁜숲어린이집', '송미숙', '서울특별시 노원구 마들로 31 ,113동 102호(월계동, 한진한화그랑빌) (월계3동)', '02', '949', '6960', 9)
2021-08-18 17:41:05,030 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,032 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '안경자', '서울특별시 강서구 허준로 234 ,912동 106호(가양동, 도시개발9단지아파트) (가양제3동)', '02', '2659', '5333', 4)
2021-08-18 17:41:05,034 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,035 INFO sqlalchemy.engine.base.Engine ('석화어린이집', '박지은', '서울특별시 영등포구 선유서로 115 ,101동 106호(양평동3가, 삼천리아파트) (양평제1동)', '02', '2677', '9533', 20)
2021-08-18 17:41:05,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,037 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '류영숙', '서울특별시 도봉구 우이천로34길 33 ,1층 (쌍문동) (쌍문제1동)', '02', '999', '9339', 10)
2021-08-18 17:41:05,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,040 INFO sqlalchemy.engine.base.Engine ('연꽃어린이집', '류민석', '서울특별시 성북구 서경로 108 ,(정릉동) (정릉제4동)', '02', '943', '7977', 17)
2021-08-18 17:41:05,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,042 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '이영철', '서울특별시 중랑구 신내로7나길 24 ,210동 101호(상봉동, 건영2차아파트) (상봉제1동)', '02', '435', '3946', 25)
2021-08-18 17:41:05,044 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,045 INFO sqlalchemy.engine.base.Engine ('산돌어린이집', '조동현', '서울특별시 송파구 성내천로24길 5 ,(마천동) (마천2동)', '02', '404', '6003', 18)
2021-08-18 17:41:05,046 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,047 INFO sqlalchemy.engine.base.Engine ('우리꿈터어린이집', '강영자', '서울특별시 구로구 도림로22길 8 ,105동 105호(구로동, 이화우성아파트) (구로제3동)', '02', '839', '2848', 7)
2021-08-18 17:41:05,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,050 INFO sqlalchemy.engine.base.Engine ('키즈스마일어린이집', '김지혜', '서울특별시 금천구 독산로36길 73 ,오성로얄아파트 101호 (시흥동) (시흥제4동)', '02', '808', '2555', 8)
2021-08-18 17:41:05,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,052 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '박경회', '서울특별시 동대문구 답십리로 210-30 ,2동 114호(답십리동, 한신아파트) (답십리제2동)', '02', '6495', '0058', 11)
2021-08-18 17:41:05,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,054 INFO sqlalchemy.engine.base.Engine ('엄마맘어린이집', '임예준', '서울특별시 서대문구 홍제원4길 25 ,(홍제동) (홍제제2동)', '02', '734', '0175', 14)
2021-08-18 17:41:05,055 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,056 INFO sqlalchemy.engine.base.Engine ('앙팡베이비어린이집', '황영진', '서울특별시 노원구 노해로 508 ,608동 101호(상계동, 상계주공6차) (상계6.7동)', '02', '938', '5607', 9)
2021-08-18 17:41:05,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,059 INFO sqlalchemy.engine.base.Engine ('천동어린이집', '한현준', '서울특별시 강동구 성안로 194-1 ,(길동 373-19) (길동)', '02', '489', '0777', 2)
2021-08-18 17:41:05,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,061 INFO sqlalchemy.engine.base.Engine ('로뎀아이어린이집', '류지원', '서울특별시 도봉구 우이천로32길 65 ,4동 105호(쌍문동, 동익파크) (쌍문제1동)', '02', '991', '7083', 10)
2021-08-18 17:41:05,062 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,064 INFO sqlalchemy.engine.base.Engine ('별초롱어린이집', '이준호', '서울특별시 노원구 월계로45길 21 ,112동 101호(월계동, 롯데캐슬루나아파트) (월계2동)', '02', '997', '4272', 9)
2021-08-18 17:41:05,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,067 INFO sqlalchemy.engine.base.Engine ('재크어린이집', '김예은', '서울특별시 구로구 디지털로31길 90 ,구로동 삼성래미안아파트 관리동 1층 (구로제3동)', '02', '838', '8020', 7)
2021-08-18 17:41:05,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,069 INFO sqlalchemy.engine.base.Engine ('해뜨는어린이집', '김혜진', '서울특별시 노원구 우이천로 102 ,203동 112호(월계동, 초안아파트) (월계2동)', '02', '999', '5051', 9)
2021-08-18 17:41:05,070 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,072 INFO sqlalchemy.engine.base.Engine ('현대하나어린이집', '전경숙', '서울특별시 노원구 덕릉로122길 12-6 ,104동 101호(상계동, 불암현대아파트) (상계3.4동)', '02', '6223', '4501', 9)
2021-08-18 17:41:05,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,075 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '박상철', '서울특별시 중랑구 사가정로51길 47 ,(면목동) (면목제3.8동)', '02', '2208', '6010', 25)
2021-08-18 17:41:05,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,077 INFO sqlalchemy.engine.base.Engine ('장안현대어린이집', '한영진', '서울특별시 동대문구 장안벚꽃로 107 ,현대홈타운아파트 단지동 (장안동) (장안제1동)', '02', '2214', '7051', 11)
2021-08-18 17:41:05,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,080 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '한정순', '서울특별시 성북구 종암로25길 30 ,117동 102호(종암동, 삼성래미안아파트) (종암동)', '02', '923', '1311', 17)
2021-08-18 17:41:05,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,083 INFO sqlalchemy.engine.base.Engine ('사임당어린이집', '정미경', '서울특별시 성북구 지봉로20길 38 ,사임당어린이집 (보문동6가) (보문동)', '02', '929', '6605', 17)
2021-08-18 17:41:05,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,085 INFO sqlalchemy.engine.base.Engine ('월드빌연서가정어린이집', '신성수', '서울특별시 은평구 증산로 333 ,101동 102호(증산동, 월드빌아파트) (증산동)', '02', '308', '4527', 22)
2021-08-18 17:41:05,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,087 INFO sqlalchemy.engine.base.Engine ('큰나무어린이집', '안성수', '서울특별시 노원구 공릉로59길 25 ,706동 102호(하계동, 청솔) (하계1동)', '02', '974', '9747', 9)
2021-08-18 17:41:05,089 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,090 INFO sqlalchemy.engine.base.Engine ('꽃뜰어린이집', '최서현', '서울특별시 송파구 새말로8길 12 ,104동 102호(문정동, 건영아파트) (장지동)', '02', '449', '3759', 18)
2021-08-18 17:41:05,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,092 INFO sqlalchemy.engine.base.Engine ('세광방과후교실', '임성호', '서울특별시 금천구 독산로 124 ,(시흥동) (시흥제4동)', '02', '893', '4674', 8)
2021-08-18 17:41:05,093 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,094 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '송민지', '서울특별시 강서구 공항대로39길 74 ,505동 105호(등촌동, 등촌주공5단지아파트) (등촌제3동)', '02', '3662', '5201', 4)
2021-08-18 17:41:05,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,096 INFO sqlalchemy.engine.base.Engine ('오성어린이집', '윤영환', '서울특별시 관악구 난곡로18길 13-4 ,(신림동) [난곡동] (난곡동)', '02', '865', '4549', 5)
2021-08-18 17:41:05,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,098 INFO sqlalchemy.engine.base.Engine ('요한어린이집', '류동현', '서울특별시 강북구 도봉로49길 62 ,천주교회 내 (미아동) (미아동)', '02', '983', '1146', 3)
2021-08-18 17:41:05,100 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,101 INFO sqlalchemy.engine.base.Engine ('꿈나래어린이집', '서성호', '서울특별시 노원구 동일로245가길 41 ,201동 103호(상계동, 은빛2단지아파트) (상계1동)', '02', '952', '7940', 9)
2021-08-18 17:41:05,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,104 INFO sqlalchemy.engine.base.Engine ('성은어린이집', '류수빈', '서울특별시 중랑구 동일로 752 ,108동 102호(중화동, 중화한신아파트) (중화제1동)', '02', '493', '3026', 25)
2021-08-18 17:41:05,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,107 INFO sqlalchemy.engine.base.Engine ('잠원시온어린이집', '김정남', '서울특별시 서초구 잠원로 150 ,잠원한신아파트 4동 107호 (잠원동)', '02', '594', '5432', 15)
2021-08-18 17:41:05,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,109 INFO sqlalchemy.engine.base.Engine ('큰세상어린이집', '권정자', '서울특별시 구로구 디지털로31길 86 ,104동 101호(구로동, 삼성래미안아파트) (구로제3동)', '02', '838', '9778', 7)
2021-08-18 17:41:05,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,110 INFO sqlalchemy.engine.base.Engine ('꿈을여는어린이집', '정지원', '서울특별시 강서구 곰달래로53가길 6 ,(화곡동) (화곡제4동)', '02', '2648', '2445', 4)
2021-08-18 17:41:05,111 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,112 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '오성진', '서울특별시 동작구 만양로 19 ,701동 103호(노량진동, 신동아리버파크) (노량진제1동)', '02', '3280', '0033', 12)
2021-08-18 17:41:05,113 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,114 INFO sqlalchemy.engine.base.Engine ('아이큰숲어린이집', '권정호', '서울특별시 강남구 학동로68길 29 ,관리동 (삼성제2동)', '02', '3445', '4181', 1)
2021-08-18 17:41:05,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,116 INFO sqlalchemy.engine.base.Engine ('예원어린이집', '윤지원', '서울특별시 강동구 천중로9길 32 ,(천호동 315-33) (천호제2동)', '02', '489', '2211', 2)
2021-08-18 17:41:05,117 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,117 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '전지은', '서울특별시 송파구 송파대로44길 22 ,(/1층) (송파동) (송파1동)', '02', '417', '9004', 18)
2021-08-18 17:41:05,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,119 INFO sqlalchemy.engine.base.Engine ('구립예본몬테소리어린이집', '김영철', '서울특별시 금천구 독산로22길 94 ,(시흥동) (시흥제5동)', '02', '807', '2627', 8)
2021-08-18 17:41:05,120 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,122 INFO sqlalchemy.engine.base.Engine ('참행복한어린이집', '박현정', '서울특별시 강서구 강서로45라길 52 ,103호(내발산동, 강성레스트빌) (발산제1동)', '02', '2662', '4095', 4)
2021-08-18 17:41:05,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,124 INFO sqlalchemy.engine.base.Engine ('고은별어린이집', '안성수', '서울특별시 송파구 올림픽로35길 104 ,24동 110호(신천동, 장미2차아파트) (잠실6동)', '02', '416', '4113', 18)
2021-08-18 17:41:05,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,125 INFO sqlalchemy.engine.base.Engine ('서울숲어린이집', '강준영', '서울특별시 광진구 뚝섬로28길 13 ,(자양4동45-2) (자양제4동)', '02', '499', '1998', 6)
2021-08-18 17:41:05,126 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,127 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '전경자', '서울특별시 은평구 은평로6길 11 (응암제1동)', '02', '358', '7020', 22)
2021-08-18 17:41:05,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,129 INFO sqlalchemy.engine.base.Engine ('강동구청직장어린이집', '임영진', '서울특별시 강동구 성내로 25 ,1층,강동구청직장어린이집 (성내제1동)', '02', '471', '5996', 2)
2021-08-18 17:41:05,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,131 INFO sqlalchemy.engine.base.Engine ('가베보물섬어린이집', '권은영', '서울특별시 노원구 마들로 111 ,29동 102호(월계동, 삼호) (월계3동)', '070', '8742', '5256', 9)
2021-08-18 17:41:05,132 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,133 INFO sqlalchemy.engine.base.Engine ('나연어린이집', '권영숙', '서울특별시 노원구 노원로 564 ,1026동 106호(상계동, 주공아파트) (상계8동)', '02', '935', '4545', 9)
2021-08-18 17:41:05,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,136 INFO sqlalchemy.engine.base.Engine ('라라어린이집', '조지영', '서울특별시 노원구 공릉로34길 62 ,1001동 105호(공릉동, 태강) (공릉2동)', '02', '3296', '1244', 9)
2021-08-18 17:41:05,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,138 INFO sqlalchemy.engine.base.Engine ('삼성숲어린이집', '권정호', '서울특별시 동작구 매봉로 123 ,삼성래미안단지내 (본동) (노량진제1동)', '02', '821', '5288', 12)
2021-08-18 17:41:05,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,139 INFO sqlalchemy.engine.base.Engine ('상아어린이집', '류경숙', '서울특별시 송파구 오금로 407 ,7동 103호(오금동, 상아아파트) (오금동)', '02', '6285', '6285', 18)
2021-08-18 17:41:05,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,141 INFO sqlalchemy.engine.base.Engine ('건영어린이집', '오지영', '서울특별시 동작구 만양로 26 ,103동 102호(노량진동, 건영) (노량진제1동)', '02', '821', '2008', 12)
2021-08-18 17:41:05,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,143 INFO sqlalchemy.engine.base.Engine ('일루어린이집', '박지혜', '서울특별시 양천구 목동서로 70 ,목동아파트 2단지내 보육시설 (목5동) (목5동)', '02', '2649', '9272', 19)
2021-08-18 17:41:05,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,145 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '황영환', '서울특별시 마포구 희우정로17길 11 ,102동 102호 (망원제1동)', '02', '338', '6333', 13)
2021-08-18 17:41:05,146 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,147 INFO sqlalchemy.engine.base.Engine ('새빛아이어린이집', '권경회', '서울특별시 강서구 강서로33가길 86 ,101동 106호(화곡동, 프라임팰리스) (화곡제3동)', '02', '2603', '7288', 4)
2021-08-18 17:41:05,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,149 INFO sqlalchemy.engine.base.Engine ('현이어린이집', '조성수', '서울특별시 강남구 밤고개로21길 25 ,래미안포레아파트 315동 101호 (세곡동)', '02', '459', '7201', 1)
2021-08-18 17:41:05,150 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,152 INFO sqlalchemy.engine.base.Engine ('개구리 어린이집', '강영진', '서울특별시 강서구 초록마을로24길 21-4 (화곡본동)', '02', '2691', '7338', 4)
2021-08-18 17:41:05,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,154 INFO sqlalchemy.engine.base.Engine ('예꼬키즈어린이집', '정성호', '서울특별시 송파구 잠실로 88 ,114동 104호(잠실동, 레이크펠리스) (잠실3동)', '02', '415', '2321', 18)
2021-08-18 17:41:05,156 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,156 INFO sqlalchemy.engine.base.Engine ('또래어린이집', '조성수', '서울특별시 서대문구 증가로 191 ,113동 103호(남가좌동, 삼성아파트) (남가좌제2동)', '02', '373', '5060', 14)
2021-08-18 17:41:05,157 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,158 INFO sqlalchemy.engine.base.Engine ('아람어린이집', '강미숙', '서울특별시 양천구 신월로 99 ,11동 101호(신월동, 신월시영아파트) (신월7동)', '02', '2694', '8956', 19)
2021-08-18 17:41:05,159 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,160 INFO sqlalchemy.engine.base.Engine ('하늘꿈어린이집', '박민지', '서울특별시 도봉구 노해로63나길 16 (창제5동)', '02', '990', '9658', 10)
2021-08-18 17:41:05,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,162 INFO sqlalchemy.engine.base.Engine ('해님달님어린이집', '안준혁', '서울특별시 구로구 중앙로6길 5-15 ,101동 104호(고척동, 청구아파트) (고척제1동)', '02', '6737', '4242', 7)
2021-08-18 17:41:05,163 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,164 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '송건우', '서울특별시 동작구 사당로17길 8 ,8동 105호(사당동, 대림) (사당제3동)', '02', '595', '5791', 12)
2021-08-18 17:41:05,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,165 INFO sqlalchemy.engine.base.Engine ('청담몬테소리어린이집', '안서현', '서울특별시 영등포구 당산동4가 당산로42길 16 ,504동 103호(당산동4가, 현대5차아파트) (당산제2동)', '02', '2632', '8100', 20)
2021-08-18 17:41:05,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,168 INFO sqlalchemy.engine.base.Engine ('해피키즈어린이집', '황준호', '서울특별시 노원구 노원로1길 21 ,903동 106호(공릉동, 청솔9차아파트) (공릉2동)', '02', '975', '1642', 9)
2021-08-18 17:41:05,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,170 INFO sqlalchemy.engine.base.Engine ('봄내어린이집', '오혜진', '서울특별시 중랑구 면목로63길 47-4 (면목본동)', '02', '438', '9707', 25)
2021-08-18 17:41:05,171 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,172 INFO sqlalchemy.engine.base.Engine ('오색무지개어린이집', '김영일', '서울특별시 도봉구 해등로12길 44 ,204동 102호(창동, 주공2단지아파트) (창제5동)', '02', '905', '6613', 10)
2021-08-18 17:41:05,173 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,173 INFO sqlalchemy.engine.base.Engine ('솜사탕어린이집', '김현정', '서울특별시 금천구 독산로58나길 38 ,101호 (독산제2동)', '02', '894', '1007', 8)
2021-08-18 17:41:05,175 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,175 INFO sqlalchemy.engine.base.Engine ('예뜰어린이집', '황병철', '서울특별시 노원구 동일로215길 48 ,319동 101호(상계동, 상계주공3차) (상계6.7동)', '02', '934', '8849', 9)
2021-08-18 17:41:05,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,177 INFO sqlalchemy.engine.base.Engine ('큰꿈어린이집', '정은영', '서울특별시 노원구 동일로177길 29 ,녹주아파트 101호 (공릉동) (공릉1동)', '02', '971', '4327', 9)
2021-08-18 17:41:05,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,178 INFO sqlalchemy.engine.base.Engine ('구립 사근다솜어린이집', '권은영', '서울특별시 성동구 사근동길 37 ,(사근동) (사근동)', '02', '2281', '3308', 16)

2021-08-18 17:41:05,179 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,180 INFO sqlalchemy.engine.base.Engine ('꽃담어린이집', '임경자', '서울특별시 노원구 동일로215길 48 ,317동 104호(상계동, 주공아파트) (상계6.7동)', '02', '931', '1235', 9)
2021-08-18 17:41:05,181 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,182 INFO sqlalchemy.engine.base.Engine ('큰별어린이집', '이미경', '서울특별시 노원구 동일로215길 48 ,303동 106호(상계동, 상계주공3차) (상계6.7동)', '02', '933', '6610', 9)
2021-08-18 17:41:05,183 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,184 INFO sqlalchemy.engine.base.Engine ('실로암어린이집', '서정남', '서울특별시 동작구 성대로6마길 8-18 (상도제3동)', '02', '821', '6934', 12)
2021-08-18 17:41:05,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,186 INFO sqlalchemy.engine.base.Engine ('중앙어린이집', '이민재', '서울특별시 동대문구 사가정로 148 ,111동 101호(전농동, SK아파트) (전농제2동)', '02', '2247', '5043', 11)
2021-08-18 17:41:05,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,188 INFO sqlalchemy.engine.base.Engine ('온무리어린이집', '김영길', '서울특별시 서초구 남부순환로364길 7-4 (양재1동)', '02', '574', '0510', 15)
2021-08-18 17:41:05,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,189 INFO sqlalchemy.engine.base.Engine ('한일교회어린이집', '권미숙', '서울특별시 중구 퇴계로88다길 19 ,한일교회 교육관1층 (신당동) (신당제5동)', '02', '6408', '0110', 24)
2021-08-18 17:41:05,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,192 INFO sqlalchemy.engine.base.Engine ('참조아어린이집', '이수빈', '서울특별시 광진구 긴고랑로7길 65 ,(중곡동) (중곡제3동)', '02', '498', '9902', 6)
2021-08-18 17:41:05,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,193 INFO sqlalchemy.engine.base.Engine ('드림어린이집', '한민석', '서울특별시 성북구 동소문로34길 24 ,106동 109호(돈암동, 삼성아파트) (돈암제1동)', '02', '779', '7795', 17)
2021-08-18 17:41:05,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,196 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '장정식', '서울특별시 노원구 동일로215길 23 ,205동 101호(상계동, 상계주공2차) (상계6.7동)', '02', '930', '0525', 9)
2021-08-18 17:41:05,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,198 INFO sqlalchemy.engine.base.Engine ('삼익영재어린이집', '권유진', '서울특별시 도봉구 해등로 195 ,106동 102호(쌍문동, 삼익세라믹아파트) (쌍문제2동)', '02', '905', '0867', 10)
2021-08-18 17:41:05,199 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,200 INFO sqlalchemy.engine.base.Engine ('은혜뜰어린이집', '윤준호', '서울특별시 구로구 부일로 985 ,수정아파트 102호 (궁동) (수궁동)', '02', '2688', '7187', 7)
2021-08-18 17:41:05,201 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,202 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '신영식', '서울특별시 관악구 성현로 80 ,110동 103호(봉천동, 관악드림타운) [성현동] (성현동)', '02', '885', '7956', 5)
2021-08-18 17:41:05,203 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,203 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '전민서', '서울특별시 중랑구 동일로140길 69 ,(중화동) (중화제1동)', '02', '433', '8291', 25)
2021-08-18 17:41:05,205 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,206 INFO sqlalchemy.engine.base.Engine ('에코맘어린이집', '송민지', '서울특별시 중랑구 동일로 752 ,109동 107호(중화동, 중화한신아파트) (중화제1동)', '02', '2208', '1155', 25)
2021-08-18 17:41:05,207 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,208 INFO sqlalchemy.engine.base.Engine ('대우아이조아어린이집', '서유진', '서울특별시 도봉구 덕릉로59아길 17 ,105동 108호(창동, 창동대우아파트) (창제2동)', '02', '900', '0843', 10)
2021-08-18 17:41:05,209 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,210 INFO sqlalchemy.engine.base.Engine ('영재교육어린이집', '황정자', '서울특별시 송파구 오금로16길 19 ,(송파동) (송파1동)', '02', '3432', '9125', 18)
2021-08-18 17:41:05,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,212 INFO sqlalchemy.engine.base.Engine ('아장아장어린이집', '전준호', '서울특별시 노원구 석계로 49 ,106동 101호(월계동, 현대아파트) (월계1동)', '02', '912', '9710', 9)
2021-08-18 17:41:05,213 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,214 INFO sqlalchemy.engine.base.Engine ('중계사임당어린이집', '송은영', '서울특별시 노원구 동일로207길 18 ,118동 103호(중계동, 중계그린아파트) (중계2.3동)', '02', '974', '5482', 9)
2021-08-18 17:41:05,216 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,216 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '황지영', '서울특별시 구로구 구일로8길 31 ,101동 107호(구로동, 우성아파트) (구로제1동)', '02', '851', '4839', 7)
2021-08-18 17:41:05,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,218 INFO sqlalchemy.engine.base.Engine ('구립금주어린이집', '오예준', '서울특별시 금천구 시흥대로70길 34 ,(시흥동) (시흥제1동)', '02', '808', '1175', 8)
2021-08-18 17:41:05,220 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,220 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '류상철', '서울특별시 구로구 고척로1길 14-41 (오류제1동)', '02', '2615', '7978', 7)
2021-08-18 17:41:05,222 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,222 INFO sqlalchemy.engine.base.Engine ('대서울어린이집', '권미숙', '서울특별시 광진구 자양번영로3길 15 ,(자양동) (자양제3동)', '02', '457', '9742', 6)
2021-08-18 17:41:05,224 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,224 INFO sqlalchemy.engine.base.Engine ('성동구청 무지개 어린이집', '조영식', '서울특별시 성동구 왕십리로 281 ,(행당동)1층 (행당1동)', '02', '2291', '6095', 16)
2021-08-18 17:41:05,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,226 INFO sqlalchemy.engine.base.Engine ('압구정어린이집', '권성호', '서울특별시 강남구 언주로157길 8 ,(신사동) (압구정동)', '02', '545', '0868', 1)
2021-08-18 17:41:05,227 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,228 INFO sqlalchemy.engine.base.Engine ('재재어린이집', '신성호', '서울특별시 서대문구 증가로 191 ,104동 102호(남가좌동, 삼성아파트) (남가좌제2동)', '02', '373', '4347', 14)
2021-08-18 17:41:05,229 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,231 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '안정호', '서울특별시 관악구 남부순환로 1430 ,106동 102호(신림동, 신림푸르지오) [미성동] (미성동)', '02', '6337', '7893', 5)
2021-08-18 17:41:05,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,233 INFO sqlalchemy.engine.base.Engine ('포그니어린이집', '이진호', '서울특별시 중랑구 신내로7가길 31 ,101동 102호(상봉동, 동부건영아파트) (상봉제1동)', '02', '2208', '4910', 25)
2021-08-18 17:41:05,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,235 INFO sqlalchemy.engine.base.Engine ('백송어린이집', '정정운', '서울특별시 용산구 효창원로76길 25-6 (효창동)', '02', '718', '3103', 21)
2021-08-18 17:41:05,236 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,237 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '서준영', '서울특별시 은평구 연서로9길 5-7 (역촌동)', '02', '385', '2562', 22)
2021-08-18 17:41:05,238 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,239 INFO sqlalchemy.engine.base.Engine ('진성어린이집', '정민지', '서울특별시 광진구 용마산로 152 ,(중곡동) (중곡제4동)', '02', '454', '3166', 6)
2021-08-18 17:41:05,240 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,241 INFO sqlalchemy.engine.base.Engine ('초록영재어린이집', '황은정', '서울특별시 강서구 초록마을로14길 2 ,(화곡동) (화곡본동)', '02', '2698', '2293', 4)
2021-08-18 17:41:05,243 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,244 INFO sqlalchemy.engine.base.Engine ('도담도담어린이집', '정지영', '서울특별시 노원구 노해로 508 ,612동 101호(상계동, 상계주공6차) (상계6.7동)', '02', '932', '9330', 9)
2021-08-18 17:41:05,245 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,246 INFO sqlalchemy.engine.base.Engine ('솔샘어린이집', '정상훈', '서울특별시 양천구 목동남로4길 6-23 ,207동 105호(신정동, 목동2차우성아파트) (신정7동)', '02', '2646', '2011', 19)
2021-08-18 17:41:05,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,247 INFO sqlalchemy.engine.base.Engine ('푸른별어린이집', '황건우', '서울특별시 노원구 한글비석로14길 36 ,, 101동 103호(중계4동 극동의푸른별2차아파트) (중계4동)', '02', '938', '3407', 9)
2021-08-18 17:41:05,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,248 INFO sqlalchemy.engine.base.Engine ('성산종합사회복지관방과후교실어린이집', '황예준', '서울특별시 마포구 월드컵로 215 ,이대성산종합사회복지관 (성산제2동)', '02', '372', '5884', 13)
2021-08-18 17:41:05,249 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,249 INFO sqlalchemy.engine.base.Engine ('현지아한솔어린이집', '안성진', '서울특별시 강남구 광평로10길 6 ,(일원동, 현지아한솔어린이집) (일원본동)', '02', '6241', '3397', 1)
2021-08-18 17:41:05,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,251 INFO sqlalchemy.engine.base.Engine ('꼬깨비어린이집', '윤정호', '서울특별시 노원구 마들로 111 ,29동 110호(월계동, 삼호아파트) (월계3동)', '02', '6318', '4831', 9)
2021-08-18 17:41:05,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,253 INFO sqlalchemy.engine.base.Engine ('새로미어린이집', '권지영', '서울특별시 노원구 노원로 532 ,907동 105호(상계동, 상계주공9단지아파트) (상계10동)', '02', '934', '7400', 9)
2021-08-18 17:41:05,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,255 INFO sqlalchemy.engine.base.Engine ('채송화어린이집', '정광수', '서울특별시 은평구 연서로 103 ,201동 101호(구산동, 세화샤이닝2차아파트) (구산동)', '02', '357', '7813', 22)
2021-08-18 17:41:05,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,257 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '신영진', '서울특별시 노원구 광운로 46 ,102동 101호(월계동, 대동아파트) (월계1동)', '02', '3292', '1333', 9)
2021-08-18 17:41:05,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,258 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '장영진', '서울특별시 강북구 한천로155길 38 ,(수유동) (수유2동)', '02', '900', '8851', 3)
2021-08-18 17:41:05,259 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,259 INFO sqlalchemy.engine.base.Engine ('까꿍어린이집', '한지은', '서울특별시 강서구 강서로10길 150 ,(화곡동) (화곡제2동)', '02', '2608', '3465', 4)
2021-08-18 17:41:05,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,261 INFO sqlalchemy.engine.base.Engine ('하늘꿈어린이집', '류지은', '서울특별시 서대문구 통일로25길 30 ,102동 101호(홍제동, 홍제한양아파트) (홍제제1동)', '02', '720', '0838', 14)
2021-08-18 17:41:05,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,262 INFO sqlalchemy.engine.base.Engine ('서울영신어린이집', '오정웅', '서울특별시 노원구 공릉로 187 ,(공릉동) (공릉2동)', '02', '974', '6412', 9)
2021-08-18 17:41:05,266 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,268 INFO sqlalchemy.engine.base.Engine ('성북구청직장어린이집', '이영자', '서울특별시 성북구 보문로 168 ,1층 (삼선동5가) (삼선동)', '02', '2241', '4861', 17)
2021-08-18 17:41:05,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,269 INFO sqlalchemy.engine.base.Engine ('연두빛어린이집', '황정순', '서울특별시 구로구 새말로 31 ,108동 101호(구로동, 롯데아파트) (구로제5동)', '02', '859', '7717', 7)
2021-08-18 17:41:05,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,272 INFO sqlalchemy.engine.base.Engine ('아이해피어린이집', '강영길', '서울특별시 노원구 섬밭로 209 ,2동 105호(하계동, 극동) (하계2동)', '02', '6229', '4551', 9)
2021-08-18 17:41:05,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,273 INFO sqlalchemy.engine.base.Engine ('코뿔소어린이집', '박수빈', '서울특별시 영등포구 양평동1가 선유로 85-7 (양평제1동)', '02', '2675', '6686', 20)
2021-08-18 17:41:05,274 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,275 INFO sqlalchemy.engine.base.Engine ('하늘사랑어린이집', '류성진', '서울특별시 노원구 광운로 53-17 ,1동 201호(월계동, 월계로즈빌) (월계1동)', '02', '912', '5373', 9)
2021-08-18 17:41:05,278 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,279 INFO sqlalchemy.engine.base.Engine ('본동어린이집', '안수빈', '서울특별시 구로구 구로동로40길 21-1 ,(구로동) (구로제2동)', '02', '3281', '6529', 7)
2021-08-18 17:41:05,282 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,283 INFO sqlalchemy.engine.base.Engine ('시원키즈스쿨어린이집', '김정수', '서울특별시 동작구 만양로 19 ,705동 101호(노량진동, 신동아리버파크) (노량진제1동)', '02', '6332', '7828', 12)
2021-08-18 17:41:05,284 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,286 INFO sqlalchemy.engine.base.Engine ('파랑새꿈어린이집', '정건우', '서울특별시 도봉구 해등로 50 ,316동 107호(창동, 주공3단지아파트) (창제1동)', '02', '6225', '1582', 10)
2021-08-18 17:41:05,288 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,288 INFO sqlalchemy.engine.base.Engine ('통통그림어린이집', '오영환', '서울특별시 노원구 상계로1길 92 ,712동 101호(상계동, 상계주공7차) (상계10동)', '02', '936', '9199', 9)
2021-08-18 17:41:05,289 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,290 INFO sqlalchemy.engine.base.Engine ('훼밀리어린이집', '김성호', '서울특별시 송파구 중대로 24 ,106동 105호(문정동, 올림픽훼밀리타운아파트) (문정2동)', '02', '400', '3421', 18)
2021-08-18 17:41:05,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,292 INFO sqlalchemy.engine.base.Engine ('키즈어린이집', '김현준', '서울특별시 동작구 서달로12길 46 ,(흑석동 93-123,키즈어린이집) (흑석동)', '02', '812', '7880', 12)
2021-08-18 17:41:05,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,293 INFO sqlalchemy.engine.base.Engine ('오즈어린이집', '신동현', '서울특별시 동작구 장승배기로 26 ,104동 103호(상도동, 아이파크) (상도제2동)', '02', '815', '7220', 12)
2021-08-18 17:41:05,294 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,295 INFO sqlalchemy.engine.base.Engine ('제일성민어린이집', '권준영', '서울특별시 동작구 성대로12길 71 ,(상도동) (상도제4동)', '02', '822', '8379', 12)
2021-08-18 17:41:05,296 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,297 INFO sqlalchemy.engine.base.Engine ('내또래어린이집', '안동현', '서울특별시 송파구 새말로8길 12 ,102동 101호(문정동, 건영아파트) (장지동)', '02', '404', '3744', 18)
2021-08-18 17:41:05,298 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,299 INFO sqlalchemy.engine.base.Engine ('사랑아이어린이집', '임준혁', '서울특별시 노원구 동일로198길 24 ,, 102동 102호(공릉1동 우성아파트) (공릉1동)', '02', '977', '7258', 9)
2021-08-18 17:41:05,300 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,301 INFO sqlalchemy.engine.base.Engine ('새롬영재어린이집', '장영일', '서울특별시 노원구 동일로182길 47-7 (공릉1동)', '02', '977', '1488', 9)
2021-08-18 17:41:05,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,302 INFO sqlalchemy.engine.base.Engine ('킨더어린이집', '윤준영', '서울특별시 동작구 매봉로 134 ,3동 103호(본동, 신동아아파트) (노량진제1동)', '02', '817', '8478', 12)
2021-08-18 17:41:05,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,304 INFO sqlalchemy.engine.base.Engine ('푸른꿈어린이집', '송영자', '서울특별시 강서구 공항대로55길 50 ,203동 101호(등촌동, 대동황토방2차아파트) (등촌제1동)', '02', '2668', '1079', 4)
2021-08-18 17:41:05,306 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,307 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '신정웅', '서울특별시 강서구 양천로24가길 59 ,105동 102호(방화동, 한진로즈힐) (방화제1동)', '02', '2664', '6606', 4)
2021-08-18 17:41:05,308 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,309 INFO sqlalchemy.engine.base.Engine ('연세중앙어린이집', '신민수', '서울특별시 송파구 가락로11길 15-15 ,하인즈빌라 101,2호 (석촌동) (석촌동)', '02', '2202', '5596', 18)
2021-08-18 17:41:05,309 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,310 INFO sqlalchemy.engine.base.Engine ('세종어린이집', '안정수', '서울특별시 광진구 면목로 12 ,(군자동) (군자동)', '02', '466', '2329', 6)
2021-08-18 17:41:05,310 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,311 INFO sqlalchemy.engine.base.Engine ('해우리어린이집', '서미영', '서울특별시 노원구 상계로3길 50 ,101동 101호(상계동, 노원현대) (상계2동)', '02', '932', '3472', 9)
2021-08-18 17:41:05,312 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,314 INFO sqlalchemy.engine.base.Engine ('파란나라어린이집', '김도현', '서울특별시 서초구 서초대로1길 30 ,현대1차B상가 201호 (방배동) (방배4동)', '02', '3477', '2164', 15)
2021-08-18 17:41:05,315 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,316 INFO sqlalchemy.engine.base.Engine ('큰다우리발도르프어린이집', '한혜진', '서울특별시 구로구 구로동로28길 33-5 ,1층~2층 (구로동339-70) (구로제2동)', '070', '8229', '2897', 7)
2021-08-18 17:41:05,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,318 INFO sqlalchemy.engine.base.Engine ('튼튼어린이집', '정정식', '서울특별시 영등포구 디지털로37길 5 ,(대림동) (대림제2동)', '02', '833', '5789', 20)
2021-08-18 17:41:05,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,320 INFO sqlalchemy.engine.base.Engine ('아이사랑 어린이집', '이영철', '서울특별시 마포구 삼개로 38 ,8동 109호(도화동, 도화우성아파트) (도화동)', '02', '712', '0849', 13)
2021-08-18 17:41:05,321 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,322 INFO sqlalchemy.engine.base.Engine ('길터어린이집', '서수빈', '서울특별시 동대문구 장한로36길 15 ,신부 3차 아파트 102호 길터어린이집 (장안동) (장안제2동)', '02', '2245', '5123', 11)
2021-08-18 17:41:05,323 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,323 INFO sqlalchemy.engine.base.Engine ('무지개나라어린이집', '한도현', '서울특별시 구로구 디지털로31길 86 ,112동 102호(구로동, 삼성래미안아파트) (구로제3동)', '02', '837', '8094', 7)
2021-08-18 17:41:05,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,325 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '최지은', '서울특별시 성북구 아리랑로19길 60 ,102동 103호(정릉동, 중앙하이츠빌아파트) (정릉제2동)', '02', '914', '0340', 17)
2021-08-18 17:41:05,326 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,326 INFO sqlalchemy.engine.base.Engine ('서초남서울어린이집', '한병철', '서울특별시 서초구 반포대로 310-5 ,구립서초남서울어린이집 (반포3동)', '02', '3482', '1501', 15)

2021-08-18 17:41:05,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,328 INFO sqlalchemy.engine.base.Engine ('문정어린이집', '윤정순', '서울특별시 송파구 송이로32길 21 ,(문정동) (문정1동)', '02', '407', '6307', 18)
2021-08-18 17:41:05,329 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,330 INFO sqlalchemy.engine.base.Engine ('피터팬키즈클럽어린이집', '정민지', '서울특별시 중랑구 용마산로 252 ,101동 106호(면목동, 현대아파트) (면목제7동)', '02', '492', '6086', 25)
2021-08-18 17:41:05,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,331 INFO sqlalchemy.engine.base.Engine ('함초롬어린이집', '박영철', '서울특별시 광진구 군자로 176 ,(군자동) (군자동)', '02', '463', '8336', 6)
2021-08-18 17:41:05,332 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,333 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '윤지영', '서울특별시 송파구 동남로 193 ,302동 101호(가락동, 가락1차쌍용아파트) (가락2동)', '02', '430', '9359', 18)
2021-08-18 17:41:05,334 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,334 INFO sqlalchemy.engine.base.Engine ('새싹나라어린이집', '장정자', '서울특별시 구로구 오류로8길 11 ,105동 102호(오류동, 오류동푸르지오아파트) (오류제2동)', '02', '2689', '8446', 7)
2021-08-18 17:41:05,336 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,337 INFO sqlalchemy.engine.base.Engine ('밝은어린이집', '송서현', '서울특별시 노원구 한글비석로 479 ,109동 104호(상계동, 보람1단지아파트) (상계9동)', '02', '931', '9318', 9)
2021-08-18 17:41:05,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,339 INFO sqlalchemy.engine.base.Engine ('사랑샘어린이집', '한성호', '서울특별시 동대문구 이문로12길 3-10 ,107동 101호(이문동, 삼성래미안아파트2차) (이문제1동)', '02', '964', '9951', 11)
2021-08-18 17:41:05,340 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,340 INFO sqlalchemy.engine.base.Engine ('청운어린이집', '류지은', '서울특별시 성북구 종암로 98-9 (종암동)', '02', '913', '6327', 17)
2021-08-18 17:41:05,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,341 INFO sqlalchemy.engine.base.Engine ('주연어린이집', '장은영', '서울특별시 강서구 까치산로12길 7-17 (화곡본동)', '02', '2606', '0887', 4)
2021-08-18 17:41:05,342 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,343 INFO sqlalchemy.engine.base.Engine ('엄마마음어린이집', '전정수', '서울특별시 노원구 동일로228길 23 ,1404동 113호(상계동, 상계주공14차) (상계9동)', '02', '935', '6767', 9)
2021-08-18 17:41:05,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,344 INFO sqlalchemy.engine.base.Engine ('수산나어린이집', '서영식', '서울특별시 동작구 여의대방로 28 ,106동 101호(신대방동, 현대아파트) (신대방제1동)', '02', '847', '3657', 12)
2021-08-18 17:41:05,345 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,345 INFO sqlalchemy.engine.base.Engine ('초롱베베어린이집', '신준서', '서울특별시 노원구 동일로227길 26 ,1613동 106호(상계동, 상계주공16차) (상계8동)', '02', '935', '9619', 9)
2021-08-18 17:41:05,346 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,347 INFO sqlalchemy.engine.base.Engine ('고은어린이집', '한성수', '서울특별시 마포구 도화길 28 ,107동 104호(도화동, 삼성아파트) (도화동)', '02', '717', '1124', 13)
2021-08-18 17:41:05,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,349 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '서순자', '서울특별시 금천구 독산로10길 33 ,(시흥동) (시흥제5동)', '02', '809', '1550', 8)
2021-08-18 17:41:05,350 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,351 INFO sqlalchemy.engine.base.Engine ('한마음어린이집', '김상훈', '서울특별시 중랑구 동일로 501 (면목제4동)', '02', '492', '8111', 25)
2021-08-18 17:41:05,352 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,352 INFO sqlalchemy.engine.base.Engine ('발산어린이집', '오순자', '서울특별시 강서구 우장산로 45 ,구립 발산어린이집 (내발산동) (우장산동)', '02', '3661', '8894', 4)
2021-08-18 17:41:05,353 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,355 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '전민재', '서울특별시 도봉구 도봉로110아길 55 ,(창동) (창제2동)', '02', '900', '1562', 10)
2021-08-18 17:41:05,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,357 INFO sqlalchemy.engine.base.Engine ('친구사이어린이집', '강민수', '서울특별시 노원구 동일로207길 18 ,115동 106호(중계동, 중계그린1단지아파트) (중계2.3동)', '02', '974', '2539', 9)
2021-08-18 17:41:05,358 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,359 INFO sqlalchemy.engine.base.Engine ('토토어린이집', '권민지', '서울특별시 노원구 노원로 564 ,1007동 101호(상계동, 상계주공10단지아파트) (상계8동)', '02', '952', '7082', 9)
2021-08-18 17:41:05,360 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,360 INFO sqlalchemy.engine.base.Engine ('고척재미난방과후교실', '권지영', '서울특별시 구로구 고척로60길 47 ,(고척동) (고척제2동)', '02', '2686', '5883', 7)
2021-08-18 17:41:05,362 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,363 INFO sqlalchemy.engine.base.Engine ('신사임당어린이집', '신은영', '서울특별시 양천구 목동서로 400 ,1009동 101호(신정동, 신시가지10단지아파트) (신정1동)', '02', '6469', '3769', 19)
2021-08-18 17:41:05,364 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,365 INFO sqlalchemy.engine.base.Engine ('예꿈어린이집', '신경자', '서울특별시 강동구 상암로 89 ,(암사동 490-39) (암사제1동)', '02', '427', '3591', 2)
2021-08-18 17:41:05,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,367 INFO sqlalchemy.engine.base.Engine ('아랑어린이집', '강정수', '서울특별시 성북구 종암로19다길 4 ,(종암동) (종암동)', '02', '3291', '7942', 17)
2021-08-18 17:41:05,368 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,368 INFO sqlalchemy.engine.base.Engine ('자연유아어린이집', '권성진', '서울특별시 금천구 시흥대로40길 93 ,(시흥동) (시흥제5동)', '02', '808', '6000', 8)
2021-08-18 17:41:05,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,370 INFO sqlalchemy.engine.base.Engine ('강변어린이집', '황상철', '서울특별시 마포구 신수로 15 ,강변힐스테이트 관리동 (현석동) (신수동)', '02', '707', '3407', 13)

2021-08-18 17:41:05,371 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,372 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '박영식', '서울특별시 구로구 구일로10길 53 ,101동 102호(구로동, 현대상선아파트) (구로제1동)', '02', '867', '5677', 7)
2021-08-18 17:41:05,373 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,374 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '조영숙', '서울특별시 노원구 마들로 111 ,18동 102호(월계동, 미륭) (월계3동)', '02', '6232', '3388', 9)
2021-08-18 17:41:05,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,375 INFO sqlalchemy.engine.base.Engine ('새싹i어린이집', '신정호', '서울특별시 노원구 월계로53길 21 ,105동 101호(월계동, 동원베네스트아파트) (월계2동)', '02', '934', '1079', 9)
2021-08-18 17:41:05,376 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,377 INFO sqlalchemy.engine.base.Engine ('삼성성모어린이집', '조경회', '서울특별시 관악구 보라매로 62 ,102동 109호(봉천동, 보라매삼성아파트) [보라매동] (보라매동)', '02', '875', '7028', 5)
2021-08-18 17:41:05,378 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,379 INFO sqlalchemy.engine.base.Engine ('무궁화 어린이집', '임민서', '서울특별시 도봉구 방학로 193 ,1동 106호(방학동, 신동아1차아파트) (방학제3동)', '02', '954', '3574', 10)
2021-08-18 17:41:05,380 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,381 INFO sqlalchemy.engine.base.Engine ('우리별어린이집', '정영진', '서울특별시 노원구 마들로 111 ,32동 110호(월계동, 삼호) (월계3동)', '02', '6224', '5959', 9)
2021-08-18 17:41:05,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,382 INFO sqlalchemy.engine.base.Engine ('모든삐아제어린이집', '박지은', '서울특별시 동작구 상도로 99-7 ,(상도동) (상도제3동)', '02', '821', '2292', 12)
2021-08-18 17:41:05,383 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,384 INFO sqlalchemy.engine.base.Engine ('리틀창의스쿨어린이집', '정미숙', '서울특별시 노원구 마들로 127 ,37동 102호(월계동, 삼호) (월계3동)', '02', '974', '6293', 9)
2021-08-18 17:41:05,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,386 INFO sqlalchemy.engine.base.Engine ('애플키즈어린이집', '최예은', '서울특별시 중랑구 공릉로2라길 15 ,101동 101호(묵동, 신안1차아파트) (묵제1동)', '02', '949', '7374', 25)
2021-08-18 17:41:05,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,389 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '신준호', '서울특별시 은평구 갈현로27길 6 ,삼진맨션 101 (갈현동) (갈현제2동)', '02', '388', '2289', 22)
2021-08-18 17:41:05,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,394 INFO sqlalchemy.engine.base.Engine ('연봉어린이집', '이준서', '서울특별시 마포구 만리재로16길 20-8 (공덕동)', '02', '711', '3927', 13)
2021-08-18 17:41:05,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,396 INFO sqlalchemy.engine.base.Engine ('한결어린이집', '송정자', '서울특별시 관악구 신원로3라길 7 ,(신림동) [신원동] (신원동)', '02', '862', '8314', 5)
2021-08-18 17:41:05,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,398 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '김지영', '서울특별시 강서구 강서로56나길 37 ,305동 104호(등촌동, 등촌주공3단지아파트) (등촌제3동)', '02', '3665', '9419', 4)
2021-08-18 17:41:05,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,400 INFO sqlalchemy.engine.base.Engine ('세정어린이집', '박정남', '서울특별시 강동구 동남로81길 16 ,(고덕동 501-1) (고덕제1동)', '02', '428', '3151', 2)
2021-08-18 17:41:05,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,406 INFO sqlalchemy.engine.base.Engine ('행복한해오름어린이집', '김민재', '서울특별시 성북구 정릉로 390 ,(돈암동) (돈암제1동)', '02', '921', '0904', 17)
2021-08-18 17:41:05,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,408 INFO sqlalchemy.engine.base.Engine ('건영아이자람어린이집', '최정호', '서울특별시 성동구 동일로 263 ,102동 101호(송정동, 건영아파트) (송정동)', '02', '466', '8417', 16)
2021-08-18 17:41:05,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,410 INFO sqlalchemy.engine.base.Engine ('빙고어린이집', '임지민', '서울특별시 송파구 삼학사로4길 13-1 (석촌동)', '02', '417', '3937', 18)
2021-08-18 17:41:05,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,412 INFO sqlalchemy.engine.base.Engine ('아이조아어린이집', '류정식', '서울특별시 구로구 고척로52길 48 ,105동 106호 고척대우아파트 (고척제2동)', '02', '2614', '9751', 7)
2021-08-18 17:41:05,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,414 INFO sqlalchemy.engine.base.Engine ('꼬꼬마숲어린이집', '오경회', '서울특별시 노원구 동일로245가길 41 ,202동 105호(상계동, 은빛2단지아파트) (상계1동)', '02', '951', '5880', 9)
2021-08-18 17:41:05,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,415 INFO sqlalchemy.engine.base.Engine ('예뜨랑어린이집', '최지영', '서울특별시 노원구 동일로179길 16 ,(공릉동) (공릉1동)', '02', '948', '3434', 9)
2021-08-18 17:41:05,416 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,417 INFO sqlalchemy.engine.base.Engine ('당성어린이집', '강영환', '서울특별시 영등포구 당산로18길 14-2 (당산제1동)', '02', '2069', '2345', 20)
2021-08-18 17:41:05,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,418 INFO sqlalchemy.engine.base.Engine ('무림어린이집', '임영숙', '서울특별시 동작구 신대방13길 1 ,(신대방동) (신대방제1동)', '02', '843', '9888', 12)
2021-08-18 17:41:05,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,420 INFO sqlalchemy.engine.base.Engine ('푸른나무어린이집', '강정식', '서울특별시 동대문구 장한로14길 81 ,삼성래미안1차아파트 관리동 1층 (장안제1동)', '02', '2215', '3373', 11)
2021-08-18 17:41:05,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,422 INFO sqlalchemy.engine.base.Engine ('좋은씨앗어린이집', '전건우', '서울특별시 도봉구 해등로 113 ,101동 104호(창동, 주공1단지아파트) (창제5동)', '02', '905', '7142', 10)
2021-08-18 17:41:05,423 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,423 INFO sqlalchemy.engine.base.Engine ('포이사임당어린이집', '김영환', '서울특별시 강남구 논현로8길 52 ,서울빌딩2층 (개포제4동)', '02', '575', '8096', 1)
2021-08-18 17:41:05,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,425 INFO sqlalchemy.engine.base.Engine ('초록별어린이집', '장영진', '서울특별시 도봉구 해등로 295 ,202동 102호(방학동, 우성1차아파트) (방학제3동)', '02', '954', '8586', 10)
2021-08-18 17:41:05,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,431 INFO sqlalchemy.engine.base.Engine ('솔로몬어린이집', '오민수', '서울특별시 은평구 연서로22길 9-4 ,은평솔로몬어린이집 (대조동)', '02', '353', '0340', 22)
2021-08-18 17:41:05,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,433 INFO sqlalchemy.engine.base.Engine ('구립 역촌2어린이집', '이지영', '서울특별시 은평구 연서로3길 14-5 (역촌동)', '02', '352', '8663', 22)
2021-08-18 17:41:05,433 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,434 INFO sqlalchemy.engine.base.Engine ('피카소어린이집', '전지은', '서울특별시 중랑구 동일로123길 42-7 (중화제2동)', '02', '494', '9049', 25)
2021-08-18 17:41:05,435 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,436 INFO sqlalchemy.engine.base.Engine ('샛별 어린이집', '안정호', '서울특별시 강남구 광평로19길 10 ,1006동 103호(수서동, 까치마을아파트) (일원본동)', '02', '445', '3069', 1)
2021-08-18 17:41:05,437 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,437 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '임지영', '서울특별시 강북구 삼양로41길 4 ,(미아동) (삼양동)', '02', '987', '3754', 3)
2021-08-18 17:41:05,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,440 INFO sqlalchemy.engine.base.Engine ('니꼴라오 어린이집', '강은영', '서울특별시 서초구 논현로5길 28 ,(양재동) (양재2동)', '02', '575', '5121', 15)
2021-08-18 17:41:05,441 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,442 INFO sqlalchemy.engine.base.Engine ('한사랑어린이집', '최정호', '서울특별시 강서구 방화대로7길 59-3 (공항동)', '02', '2667', '0652', 4)
2021-08-18 17:41:05,443 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,444 INFO sqlalchemy.engine.base.Engine ('방화엔젤어린이집', '서영일', '서울특별시 강서구 금낭화로 287-19 ,(방화동) (방화제3동)', '02', '2662', '2230', 4)
2021-08-18 17:41:05,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,446 INFO sqlalchemy.engine.base.Engine ('경동제일어린이집', '한민재', '서울특별시 중랑구 봉화산로 91 ,(중화동) (중화제1동)', '02', '434', '2680', 25)
2021-08-18 17:41:05,447 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,447 INFO sqlalchemy.engine.base.Engine ('마곡자연숲어린이집', '김영철', '서울특별시 강서구 수명로1길 110 ,마곡수명산파크3단지 303 (발산제1동)', '02', '2667', '7728', 4)
2021-08-18 17:41:05,448 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,449 INFO sqlalchemy.engine.base.Engine ('브레인에듀어린이집', '황서현', '서울특별시 동대문구 장안벚꽃로 107 ,116동 103호(장안동, 현대홈타운아파트) (장안제1동)', '02', '2241', '7879', 11)
2021-08-18 17:41:05,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,451 INFO sqlalchemy.engine.base.Engine ('성암교회방과후교실어린이집', '최은정', '서울특별시 은평구 서오릉로4길 6 ,(녹번동) (녹번동)', '02', '388', '5233', 22)
2021-08-18 17:41:05,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,453 INFO sqlalchemy.engine.base.Engine ('재원몬테소리어린이집', '이경숙', '서울특별시 동작구 상도로55길 47 ,(상도동) (상도제1동)', '02', '827', '0201', 12)
2021-08-18 17:41:05,455 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,456 INFO sqlalchemy.engine.base.Engine ('푸우어린이집', '윤지은', '서울특별시 노원구 노해로 508 ,627동 101호(상계동, 상계주공6차) (상계6.7동)', '02', '6436', '4156', 9)
2021-08-18 17:41:05,458 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,458 INFO sqlalchemy.engine.base.Engine ('한나몬테소리어린이집', '한광수', '서울특별시 송파구 백제고분로41길 36-5 (송파1동)', '02', '420', '5030', 18)
2021-08-18 17:41:05,460 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,460 INFO sqlalchemy.engine.base.Engine ('대공원어린이집', '김미영', '서울특별시 광진구 천호대로116길 22-14 ,(능동) (능동)', '02', '455', '3594', 6)
2021-08-18 17:41:05,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,462 INFO sqlalchemy.engine.base.Engine ('용두희망어린이집', '정유진', '서울특별시 동대문구 무학로49길 75 ,(용두동) (용신동)', '02', '923', '0836', 11)
2021-08-18 17:41:05,463 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,464 INFO sqlalchemy.engine.base.Engine ('대성어린이집', '송은영', '서울특별시 용산구 백범로51길 1 ,(효창동) (효창동)', '02', '713', '0344', 21)
2021-08-18 17:41:05,465 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,466 INFO sqlalchemy.engine.base.Engine ('옹달샘어린이집', '안지혜', '서울특별시 도봉구 노해로70길 54 ,1902동 110호(창동, 상계주공19차아파트) (창제4동)', '02', '990', '1290', 10)
2021-08-18 17:41:05,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,468 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '오성수', '서울특별시 서대문구 연희로 38-20 ,대우아파트 관리동 2층 (연희동) (연희동)', '02', '3141', '0933', 14)
2021-08-18 17:41:05,469 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,469 INFO sqlalchemy.engine.base.Engine ('예나어린이집', '황상훈', '서울특별시 양천구 곰달래로11길 21 ,101동 104호 (신월동, 길훈엔트런스빌) (신월1동)', '02', '2603', '4068', 19)
2021-08-18 17:41:05,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,471 INFO sqlalchemy.engine.base.Engine ('오즈 어린이집', '장준영', '서울특별시 강서구 방화대로45길 32 ,101동 102호(방화동, 방화동부센트레빌) (방화제1동)', '02', '2665', '9946', 4)
2021-08-18 17:41:05,473 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,474 INFO sqlalchemy.engine.base.Engine ('행복한 어린이집', '전영일', '서울특별시 마포구 망원로2길 103 ,104동 106호(망원동, 대림1차아파트) (망원제1동)', '02', '3144', '2302', 13)
2021-08-18 17:41:05,475 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,476 INFO sqlalchemy.engine.base.Engine ('도봉구청직장어린이집', '황병철', '서울특별시 도봉구 마들로 656 ,도봉구청내1층직장어린이집 (방학제1동)', '02', '2091', '5996', 10)
2021-08-18 17:41:05,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,478 INFO sqlalchemy.engine.base.Engine ('해돋는어린이집', '정정호', '서울특별시 강서구 강서로26길 63 (화곡본동)', '02', '2691', '5138', 4)
2021-08-18 17:41:05,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,481 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '김영진', '서울특별시 동작구 보라매로13길 12 ,(신대방동) (신대방제2동)', '02', '3280', '5373', 12)
2021-08-18 17:41:05,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,483 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '강성진', '서울특별시 강서구 양천로 125 ,101동 107호(방화동, 장미아파트) (방화제3동)', '02', '2666', '5989', 4)
2021-08-18 17:41:05,484 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,485 INFO sqlalchemy.engine.base.Engine ('지원어린이집', '황민서', '서울특별시 양천구 남부순환로73길 15-8 (신월4동)', '02', '2695', '4006', 19)
2021-08-18 17:41:05,487 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,488 INFO sqlalchemy.engine.base.Engine ('영재아이짐어린이집', '임지은', '서울특별시 강동구 양재대로121길 17 (천호제3동)', '02', '485', '6271', 2)
2021-08-18 17:41:05,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,490 INFO sqlalchemy.engine.base.Engine ('이림어린이집', '윤지영', '서울특별시 강동구 양재대로97길 44 ,(성내동 386-58) (성내제3동)', '02', '486', '5929', 2)
2021-08-18 17:41:05,492 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,495 INFO sqlalchemy.engine.base.Engine ('금강어린이집', '권예준', '서울특별시 구로구 오리로 1197 ,금강수목원아파트 관리동 (오류동) (오류제2동)', '02', '2687', '2220', 7)
2021-08-18 17:41:05,496 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,496 INFO sqlalchemy.engine.base.Engine ('초록별어린이집', '임영철', '서울특별시 중랑구 숙선옹주로 91 ,,406동 106호(묵동, 신내아파트) (묵제1동)', '02', '3422', '1117', 25)
2021-08-18 17:41:05,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,498 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '최정자', '서울특별시 구로구 개봉로17길 30-6 (개봉제2동)', '02', '2681', '2845', 7)
2021-08-18 17:41:05,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,499 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '신병철', '서울특별시 구로구 오리로 1197 ,109동 104호(오류동, 금강수목원아파트) (오류제2동)', '02', '6095', '5004', 7)
2021-08-18 17:41:05,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,500 INFO sqlalchemy.engine.base.Engine ('미소천사어린이집', '임광수', '서울특별시 노원구 동일로227길 25 ,1108동 106호 (상계8동)', '02', '6435', '9721', 9)
2021-08-18 17:41:05,501 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,503 INFO sqlalchemy.engine.base.Engine ('베베어린이집', '서정순', '서울특별시 노원구 섬밭로 139 ,풍림아파트 108동 106호 (공릉1동)', '02', '977', '0300', 9)
2021-08-18 17:41:05,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,505 INFO sqlalchemy.engine.base.Engine ('두산비쥬어린이집', '강종수', '서울특별시 성북구 오패산로 46 ,두산위브아파트 관리동 1층 (월곡제1동)', '02', '919', '3010', 17)
2021-08-18 17:41:05,506 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,507 INFO sqlalchemy.engine.base.Engine ('새하늘어린이집', '정영진', '서울특별시 은평구 갈현로45길 28-1 (갈현제1동)', '02', '356', '8354', 22)
2021-08-18 17:41:05,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,508 INFO sqlalchemy.engine.base.Engine ('은비어린이집', '이성민', '서울특별시 관악구 관악로30길 27 ,109동 103호 (봉천동,대우푸르지오아파트) [청림동] (청림동)', '02', '889', '3807', 5)
2021-08-18 17:41:05,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,511 INFO sqlalchemy.engine.base.Engine ('주은어린이집', '최종수', '서울특별시 도봉구 노해로49길 38 ,(쌍문동) (쌍문제4동)', '02', '908', '0227', 10)
2021-08-18 17:41:05,512 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,512 INFO sqlalchemy.engine.base.Engine ('태영어린이집', '장수빈', '서울특별시 도봉구 도봉로110다길 51 ,태영아파트 단지내 (창제2동)', '02', '999', '1666', 10)
2021-08-18 17:41:05,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,514 INFO sqlalchemy.engine.base.Engine ('해나리어린이집', '강민석', '서울특별시 양천구 목동로 212 ,718동 105호(목동, 목동신시가지7단지아파트) (목1동)', '02', '2645', '0773', 19)
2021-08-18 17:41:05,515 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,516 INFO sqlalchemy.engine.base.Engine ('꾸러기어린이집', '황종수', '서울특별시 도봉구 우이천로 304 ,9동 107호(쌍문동, 한양아파트) (쌍문제3동)', '02', '999', '1705', 10)
2021-08-18 17:41:05,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,519 INFO sqlalchemy.engine.base.Engine ('루하이어린이집', '송영일', '서울특별시 노원구 섬밭로 265 ,5동 107호(중계동, 경남아파트) (중계2.3동)', '02', '978', '9781', 9)
2021-08-18 17:41:05,521 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,522 INFO sqlalchemy.engine.base.Engine ('무릎학교어린이집', '조동현', '서울특별시 관악구 은천로 93 ,209동 101호(봉천동, 벽산블루밍아파트) [은천동] (은천동)', '02', '3285', '3567', 5)
2021-08-18 17:41:05,524 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,525 INFO sqlalchemy.engine.base.Engine ('자이맘어린이집', '정민지', '서울특별시 강동구 천호대로 1239 ,GS강동자이아파트 관리동 1층 (길동)', '02', '471', '1196', 2)
2021-08-18 17:41:05,526 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,527 INFO sqlalchemy.engine.base.Engine ('롯데어린이집', '장민지', '서울특별시 강서구 공항대로 382 ,롯데낙천대아파트 단지 내 롯데어린이집 (화곡제6동)', '02', '2699', '1188', 4)
2021-08-18 17:41:05,528 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,529 INFO sqlalchemy.engine.base.Engine ('젬마어린이집', '강유진', '서울특별시 광진구 동일로26길 51 ,(화양동) (화양동)', '02', '461', '0788', 6)
2021-08-18 17:41:05,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,531 INFO sqlalchemy.engine.base.Engine ('EQ어린이집', '윤민수', '서울특별시 광진구 동일로26길 41 ,(화양동) (화양동)', '02', '466', '1071', 6)
2021-08-18 17:41:05,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,533 INFO sqlalchemy.engine.base.Engine ('신중앙어린이집', '임진호', '서울특별시 성북구 보문동2가 보문로25길 20 ,(보문동2가) (보문동)', '02', '922', '9052', 17)
2021-08-18 17:41:05,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,536 INFO sqlalchemy.engine.base.Engine ('꿈키아어린이집', '황정수', '서울특별시 노원구 동일로215길 23 ,218동 106호(상계6·7동, 주공아파트) (상계6.7동)', '02', '976', '1457', 9)
2021-08-18 17:41:05,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,539 INFO sqlalchemy.engine.base.Engine ('청운어린이집', '신성호', '서울특별시 양천구 남부순환로85길 12-19 ,(신월동) (신월6동)', '02', '2695', '5004', 19)
2021-08-18 17:41:05,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,541 INFO sqlalchemy.engine.base.Engine ('두란노어린이집', '최상철', '서울특별시 서대문구 증가로20가길 62 ,(북가좌동) (북가좌제2동)', '02', '304', '6613', 14)
2021-08-18 17:41:05,543 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,544 INFO sqlalchemy.engine.base.Engine ('황성영재어린이집', '장건우', '서울특별시 금천구 독산로40길 47 ,(시흥동) (시흥제4동)', '02', '808', '8895', 8)
2021-08-18 17:41:05,545 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,545 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '이지원', '서울특별시 광진구 뚝섬로35길 32 ,306동 102호(자양동) (자양제3동)', '02', '456', '2910', 6)
2021-08-18 17:41:05,547 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,547 INFO sqlalchemy.engine.base.Engine ('보물섬어린이집', '정준호', '서울특별시 관악구 관악로 285 ,105동 101호(봉천동, 봉천동아1차아파트) [성현동] (성현동)', '02', '6332', '1190', 5)
2021-08-18 17:41:05,549 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,549 INFO sqlalchemy.engine.base.Engine ('현서어린이집', '김지훈', '서울특별시 양천구 중앙로54길 31 ,1층 (신정동) (신정4동)', '02', '2606', '9990', 19)
2021-08-18 17:41:05,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,551 INFO sqlalchemy.engine.base.Engine ('열린어린이집', '임정수', '서울특별시 구로구 경인로 643 ,(신도림동) (신도림동)', '02', '6346', '1248', 7)
2021-08-18 17:41:05,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,554 INFO sqlalchemy.engine.base.Engine ('구립천일방과후어린이집', '이예은', '서울특별시 강동구 구천면로42길 59 ,(천호동 76-2) (천호제1동)', '02', '472', '7333', 2)
2021-08-18 17:41:05,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,557 INFO sqlalchemy.engine.base.Engine ('서초래미안어린이집', '황영철', '서울특별시 서초구 서초대로65길 13-10 ,서초래미안아파트 관리동 1층 (서초동) (서초4동)', '02', '3477', '4533', 15)
2021-08-18 17:41:05,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,559 INFO sqlalchemy.engine.base.Engine ('즐거운산들어린이집', '류성수', '서울특별시 광진구 자양로50길 74 ,(구의2동) (구의제2동)', '02', '458', '7122', 6)
2021-08-18 17:41:05,560 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,561 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '강정수', '서울특별시 은평구 서오릉로6길 6-1 (녹번동)', '02', '357', '3429', 22)
2021-08-18 17:41:05,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,563 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '신현준', '서울특별시 구로구 새말로9길 45 ,103동 106호(구로동, 신도림현대아파트) (구로제5동)', '02', '859', '3408', 7)
2021-08-18 17:41:05,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,565 INFO sqlalchemy.engine.base.Engine ('새벽산어린이집', '장준서', '서울특별시 서대문구 세검정로1길 95 ,101동 103호(홍은동, 벽산아파트) (홍은제1동)', '02', '396', '1509', 14)
2021-08-18 17:41:05,566 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,566 INFO sqlalchemy.engine.base.Engine ('하늘꿈 어린이집', '서정웅', '서울특별시 성동구 고산자로 164 ,116동 104호(행당동, 한신아파트) (행당제1동)', '02', '2298', '9921', 16)
2021-08-18 17:41:05,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,568 INFO sqlalchemy.engine.base.Engine ('아기천사어린이집', '김지훈', '서울특별시 노원구 동일로227길 25 ,1105동 101호(상계동, 상계주공11차) (상계8동)', '02', '6229', '7009', 9)
2021-08-18 17:41:05,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,571 INFO sqlalchemy.engine.base.Engine ('아이랑행복한어린이집', '최동현', '서울특별시 노원구 한글비석로 530 ,1211동 106호(상계동, 상계주공12차) (상계9동)', '02', '939', '6324', 9)
2021-08-18 17:41:05,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,573 INFO sqlalchemy.engine.base.Engine ('아이또래어린이집', '권영일', '서울특별시 중랑구 신내로 155 ,805동 102호(신내동, 두산아파트) (신내2동)', '02', '3421', '2193', 25)
2021-08-18 17:41:05,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,575 INFO sqlalchemy.engine.base.Engine ('하나어린이집', '조영환', '서울특별시 노원구 동일로227길 26 ,1604동 105호(상계동, 상계주공16차) (상계8동)', '02', '937', '1178', 9)
2021-08-18 17:41:05,576 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,577 INFO sqlalchemy.engine.base.Engine ('구립우리꿈어린이집', '한예준', '서울특별시 관악구 은천로 93 ,벽산블루밍아파트 1718동 1호 (은천동)', '02', '887', '3788', 5)
2021-08-18 17:41:05,578 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,579 INFO sqlalchemy.engine.base.Engine ('리틀빌리지어린이집', '류은정', '서울특별시 강서구 공항대로67길 29-4 (염창동)', '02', '3663', '9533', 4)
2021-08-18 17:41:05,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,581 INFO sqlalchemy.engine.base.Engine ('하늘사랑어린이집', '이경자', '서울특별시 구로구 부광로 96-16 ,703동 106호(항동, 제일풍경채포레스트) (항동)', '02', '2684', '2500', 7)
2021-08-18 17:41:05,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,582 INFO sqlalchemy.engine.base.Engine ('재능어린이집', '윤민서', '서울특별시 양천구 월정로 143 ,(신월동) (신월1동)', '02', '2699', '4946', 19)
2021-08-18 17:41:05,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,584 INFO sqlalchemy.engine.base.Engine ('그림나라어린이집', '정은정', '서울특별시 구로구 구로동로18길 56 ,103호 (구로제4동)', '02', '854', '3383', 7)
2021-08-18 17:41:05,585 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,586 INFO sqlalchemy.engine.base.Engine ('신세인어린이집', '전성수', '서울특별시 도봉구 도봉로134길 5 ,(창동) (창제5동)', '02', '997', '4385', 10)
2021-08-18 17:41:05,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,587 INFO sqlalchemy.engine.base.Engine ('예쁜꼬마어린이집', '송영일', '서울특별시 노원구 노원로 532 ,905동 102호(상계동, 상계주공9차) (상계10동)', '02', '6221', '1504', 9)
2021-08-18 17:41:05,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,589 INFO sqlalchemy.engine.base.Engine ('아이사랑 어린이집', '조지원', '서울특별시 송파구 도곡로62길 49 ,(잠실동) (잠실본동)', '02', '413', '3944', 18)
2021-08-18 17:41:05,589 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,590 INFO sqlalchemy.engine.base.Engine ('쿠키어린이집', '이준혁', '서울특별시 강북구 솔매로 106-1 (미아동)', '02', '984', '0286', 3)
2021-08-18 17:41:05,591 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,591 INFO sqlalchemy.engine.base.Engine ('인영어린이집', '송정수', '서울특별시 동대문구 약령시로 25 ,안암골벽산아파트 단지내 (제기동) (제기동)', '02', '929', '1697', 11)
2021-08-18 17:41:05,592 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,593 INFO sqlalchemy.engine.base.Engine ('아가방어린이집', '김미경', '서울특별시 은평구 증산로21길 20 ,(신사동) (신사제1동)', '02', '303', '1212', 22)
2021-08-18 17:41:05,594 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,594 INFO sqlalchemy.engine.base.Engine ('육영몬테소리어린이집', '최지훈', '서울특별시 마포구 성미산로 116-7 (연남동)', '02', '325', '7755', 13)
2021-08-18 17:41:05,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,596 INFO sqlalchemy.engine.base.Engine ('오렌지어린이집', '송정남', '서울특별시 영등포구 당산로42길 7 ,201동 105호(당산동5가, 효성아파트) (당산제2동)', '02', '6267', '1326', 20)
2021-08-18 17:41:05,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,604 INFO sqlalchemy.engine.base.Engine ('새예닮어린이집', '서정호', '서울특별시 영등포구 신길로60마길 10 ,(신길동) (영등포본동)', '02', '847', '3751', 20)
2021-08-18 17:41:05,605 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,606 INFO sqlalchemy.engine.base.Engine ('폴디어린이집', '신예은', '서울특별시 구로구 신도림로 16 ,103동 101호(신도림동, 대림2차아파트) (신도림동)', '02', '2636', '3512', 7)
2021-08-18 17:41:05,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,608 INFO sqlalchemy.engine.base.Engine ('그루터기어린이집', '장준호', '서울특별시 서대문구 통일로25길 30 ,101동 101호 (홍제동, 홍제한양아파트) (홍제제1동)', '02', '6373', '9133', 14)
2021-08-18 17:41:05,609 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,610 INFO sqlalchemy.engine.base.Engine ('공간어린이집', '윤상철', '서울특별시 강서구 양천로69길 58 ,공간어린이집 (염창동) (염창동)', '02', '3662', '8355', 4)
2021-08-18 17:41:05,611 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,612 INFO sqlalchemy.engine.base.Engine ('새해든어린이집', '한영일', '서울특별시 노원구 한글비석로14길 8 ,201동 112호(중계동, 주공2단지아파트) (중계4동)', '02', '6221', '9234', 9)
2021-08-18 17:41:05,613 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,616 INFO sqlalchemy.engine.base.Engine ('해바라기어린이집', '한정남', '서울특별시 중랑구 봉우재로20길 45 ,(면목동) (면목제2동)', '02', '491', '2323', 25)
2021-08-18 17:41:05,617 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,618 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '서정호', '서울특별시 동대문구 장안벚꽃로 107 ,115동 104호(장안동, 현대홈타운아파트) (장안제1동)', '02', '2249', '5624', 11)
2021-08-18 17:41:05,620 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,623 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '강동현', '서울특별시 강동구 진황도로 209-11 ,(둔촌동 98-48) (둔촌제2동)', '02', '486', '1080', 2)
2021-08-18 17:41:05,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,625 INFO sqlalchemy.engine.base.Engine ('성진어린이집', '한유진', '서울특별시 동작구 동작대로9길 76 ,(사당동) (사당제1동)', '02', '525', '6450', 12)
2021-08-18 17:41:05,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,626 INFO sqlalchemy.engine.base.Engine ('아이위즈어린이집', '최정수', '서울특별시 관악구 은천로 93 ,103동 103호(봉천동, 벽산블루밍아파트) [은천동] (은천동)', '02', '3285', '0307', 5)
2021-08-18 17:41:05,627 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,628 INFO sqlalchemy.engine.base.Engine ('신도어린이집', '전도현', '서울특별시 도봉구 도봉로136나길 40 ,107동 104호(창동, 창동신도브래뉴1차아파트) (창제5동)', '02', '999', '1171', 10)
2021-08-18 17:41:05,629 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,630 INFO sqlalchemy.engine.base.Engine ('구립고덕2어린이집', '서종수', '서울특별시 강동구 동남로82길 83 ,(고덕동 258-7) (고덕제2동)', '02', '427', '3102', 2)
2021-08-18 17:41:05,631 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,632 INFO sqlalchemy.engine.base.Engine ('푸르미어린이집', '송미경', '서울특별시 강서구 양천로67길 32 ,103동 105호(염창동, 신동아아파트) (염창동)', '02', '3661', '7002', 4)
2021-08-18 17:41:05,633 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,633 INFO sqlalchemy.engine.base.Engine ('아이비영재어린이집', '황종수', '서울특별시 동작구 신대방6길 25 ,(신대방동) (신대방제1동)', '02', '845', '2658', 12)
2021-08-18 17:41:05,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,635 INFO sqlalchemy.engine.base.Engine ('꾸러기키즈 어린이집', '한영식', '서울특별시 마포구 독막로 266 ,113동 103호(대흥동, 마포태영아파트) (용강동)', '02', '704', '1025', 13)
2021-08-18 17:41:05,636 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,637 INFO sqlalchemy.engine.base.Engine ('구립 응봉어린이집', '안준영', '서울특별시 성동구 독서당로60길 12-7 (응봉동)', '02', '2295', '1021', 16)
2021-08-18 17:41:05,638 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,640 INFO sqlalchemy.engine.base.Engine ('광진구청직장어린이집', '김종수', '서울특별시 광진구 자양로 117 ,광진구청 1동 777호(자양동) (자양제1동)', '02', '450', '1650', 6)
2021-08-18 17:41:05,641 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,642 INFO sqlalchemy.engine.base.Engine ('아이나라어린이집', '권건우', '서울특별시 동작구 여의대방로10길 38 ,106동 102호(신대방동, 롯데낙천대아파트) (신대방제1동)', '02', '846', '0802', 12)
2021-08-18 17:41:05,647 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,648 INFO sqlalchemy.engine.base.Engine ('영광어린이집', '최상훈', '서울특별시 성북구 오패산로10길 27 ,(하월곡동) (월곡제1동)', '02', '916', '3100', 17)
2021-08-18 17:41:05,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,650 INFO sqlalchemy.engine.base.Engine ('리틀영재어린이집', '임민석', '서울특별시 금천구 독산로67길 22 ,(독산동) (독산제2동)', '02', '806', '4583', 8)
2021-08-18 17:41:05,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,652 INFO sqlalchemy.engine.base.Engine ('신일어린이집', '임경숙', '서울특별시 영등포구 영등포로84길 24-5 ,(신길동) (신길제1동)', '02', '846', '8674', 20)
2021-08-18 17:41:05,653 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,654 INFO sqlalchemy.engine.base.Engine ('파란꿈어린이집', '윤정호', '서울특별시 서초구 잠원로 37-6 ,202동 107호(잠원동, 신반포한신아파트) (반포3동)', '02', '6254', '5571', 15)
2021-08-18 17:41:05,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,656 INFO sqlalchemy.engine.base.Engine ('소망어린이집', '임지민', '서울특별시 송파구 백제고분로27길 25 ,(삼전동) (삼전동)', '02', '2202', '4610', 18)
2021-08-18 17:41:05,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,658 INFO sqlalchemy.engine.base.Engine ('예나어린이집', '김정수', '서울특별시 강북구 삼양로 256 ,105동 103호(미아동, 미아래미안1차) (삼양동)', '02', '988', '8911', 3)
2021-08-18 17:41:05,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,659 INFO sqlalchemy.engine.base.Engine ('늘푸른동아어린이집', '최민수', '서울특별시 중랑구 동일로 476 ,늘푸른동아아파트 102동 101호,102호 (면목동) (면목제4동)', '02', '493', '6985', 25)
2021-08-18 17:41:05,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,661 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '전성진', '서울특별시 강남구 논현로51길 25 ,현대그린아파트 105호 (도곡동) (도곡제1동)', '02', '3462', '6995', 1)
2021-08-18 17:41:05,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,663 INFO sqlalchemy.engine.base.Engine ('또오기어린이집', '한지원', '서울특별시 서대문구 연희로41길 102 ,3동 109호(홍은동, 미성맨션) (홍은제2동)', '02', '394', '0638', 14)
2021-08-18 17:41:05,664 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,665 INFO sqlalchemy.engine.base.Engine ('서울특별시립보라매병원어린이집', '서영일', '서울특별시 동작구 보라매로5길 20 ,시립보라매병원 본관3층 (신대방동) (신대방제2동)', '02', '870', '2935', 12)
2021-08-18 17:41:05,665 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,666 INFO sqlalchemy.engine.base.Engine ('동산어린이집', '전서현', '서울특별시 구로구 연동로 233 ,104동 103호(항동, 중흥에스클래스베르데카운티) (항동)', '02', '2611', '5558', 7)
2021-08-18 17:41:05,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,668 INFO sqlalchemy.engine.base.Engine ('새색동어린이집', '박종수', '서울특별시 마포구 성암로11길 60 ,청구아파트 관리사무소2층 미키어린이집 (성산제2동)', '02', '3152', '0909', 13)
2021-08-18 17:41:05,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,681 INFO sqlalchemy.engine.base.Engine ('푸르니서초 어린이집', '한준호', '서울특별시 서초구 효령로67길 4 ,(서초동) (서초1동)', '02', '525', '1232', 15)
2021-08-18 17:41:05,687 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,688 INFO sqlalchemy.engine.base.Engine ('녹번푸름숲어린이집', '조지은', '서울특별시 은평구 녹번로3가길 4-8 ,1층 (녹번동)', '02', '358', '5351', 22)
2021-08-18 17:41:05,694 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,696 INFO sqlalchemy.engine.base.Engine ('소월어린이집', '임건우', '서울특별시 용산구 신흥로18길 3-5 (용산2가동)', '02', '749', '5391', 21)
2021-08-18 17:41:05,697 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,700 INFO sqlalchemy.engine.base.Engine ('에코빌어린이집', '이준혁', '서울특별시 도봉구 도봉로180길 6-23 ,동아에코빌아파트 단지내 (도봉동) (도봉제2동)', '02', '3494', '5333', 10)
2021-08-18 17:41:05,701 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,701 INFO sqlalchemy.engine.base.Engine ('왕자와공주어린이집', '안영철', '서울특별시 서대문구 통일로25길 30 ,103동 110호(홍제동, 홍제한양아파트) (홍제제1동)', '02', '722', '9837', 14)
2021-08-18 17:41:05,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,706 INFO sqlalchemy.engine.base.Engine ('풍림 어린이집', '장상훈', '서울특별시 성북구 솔샘로25길 20 ,120동 104호(정릉동, 풍림아이원) (정릉제4동)', '02', '6223', '0880', 17)
2021-08-18 17:41:05,707 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,708 INFO sqlalchemy.engine.base.Engine ('리틀엔젤어린이집', '김지은', '서울특별시 동작구 대방동길 20 ,은송빌라 102호 (대방동) (대방동)', '02', '823', '0301', 12)
2021-08-18 17:41:05,710 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,711 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '한현정', '서울특별시 광진구 영화사로7길 4 ,4동 103호(중곡동,삼보드림아파트) (중곡제4동)', '02', '453', '7563', 6)
2021-08-18 17:41:05,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,721 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '정준영', '서울특별시 도봉구 노해로66길 21 ,110동 101호(창동, 삼성래미안아파트) (창제1동)', '02', '996', '2278', 10)
2021-08-18 17:41:05,723 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,724 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '신광수', '서울특별시 서대문구 가재울로 45 ,103동 101호(남가좌동, 현대아파트) (남가좌제2동)', '02', '303', '3223', 14)
2021-08-18 17:41:05,726 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,727 INFO sqlalchemy.engine.base.Engine ('로뎀어린이집', '최지영', '서울특별시 구로구 새말로 31 ,107동 102호(구로동, 롯데아파트) (구로제5동)', '02', '851', '6199', 7)

2021-08-18 17:41:05,728 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,729 INFO sqlalchemy.engine.base.Engine ('예랑어린이집', '박예준', '서울특별시 서대문구 간호대로3길 35 ,101호(홍제동) (홍제제3동)', '02', '394', '1267', 14)
2021-08-18 17:41:05,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,732 INFO sqlalchemy.engine.base.Engine ('KTi행복한어린이집', '서영진', '서울특별시 양천구 목동서로 201 ,KT정보시스템본부 1층 (목1동)', '02', '3219', '1840', 19)
2021-08-18 17:41:05,733 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,734 INFO sqlalchemy.engine.base.Engine ('두란노어린이집', '이예준', '서울특별시 강북구 한천로109길 69 ,101동 107호(번동, 번동한양아파트) (번3동)', '02', '988', '2942', 3)
2021-08-18 17:41:05,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,736 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '장은경', '서울특별시 강서구 양천로17길 25 ,(방화동) (방화제1동)', '02', '2664', '9831', 4)
2021-08-18 17:41:05,738 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,738 INFO sqlalchemy.engine.base.Engine ('궁전 어린이집', '권지훈', '서울특별시 광진구 긴고랑로36길 65 ,101호 (중곡동) (중곡제4동)', '02', '458', '5666', 6)
2021-08-18 17:41:05,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,740 INFO sqlalchemy.engine.base.Engine ('리틀노벨 어린이집', '윤준혁', '서울특별시 도봉구 도봉로110다길 51 ,111동 102호(창동, 태영아파트) (창제2동)', '02', '993', '4564', 10)
2021-08-18 17:41:05,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,742 INFO sqlalchemy.engine.base.Engine ('별이달이어린이집', '황준영', '서울특별시 도봉구 도봉로180나길 20 ,102동 102호(도봉동, 양우내안애아파트) (도봉제2동)', '070', '8112', '5097', 10)
2021-08-18 17:41:05,742 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,744 INFO sqlalchemy.engine.base.Engine ('보령어린이집', '황정수', '서울특별시 동대문구 이문로54길 36 ,101동 103호(이문동, 이문e편한세상아파트) (이문제2동)', '02', '966', '3066', 11)
2021-08-18 17:41:05,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,749 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '장준호', '서울특별시 서대문구 증가로31길 41 ,(북가좌동) (북가좌제2동)', '02', '304', '5999', 14)
2021-08-18 17:41:05,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,755 INFO sqlalchemy.engine.base.Engine ('신나는 어린이집', '윤정수', '서울특별시 성북구 오패산로 46 ,114동 104호(하월곡동, 월곡두산위브아파트) (월곡제1동)', '02', '6435', '9656', 17)
2021-08-18 17:41:05,756 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,758 INFO sqlalchemy.engine.base.Engine ('라온제나어린이집', '권미숙', '서울특별시 도봉구 도당로19길 57 ,(방학동) (방학제2동)', '02', '906', '7700', 10)
2021-08-18 17:41:05,759 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,760 INFO sqlalchemy.engine.base.Engine ('요요몬테소리어린이집', '김준영', '서울특별시 송파구 오금로27길 37 ,(방이동) (방이1동)', '02', '421', '1129', 18)
2021-08-18 17:41:05,761 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,763 INFO sqlalchemy.engine.base.Engine ('역촌교회방과후교실어린이집', '최성진', '서울특별시 은평구 연서로14길 12 ,(역촌동) (역촌동)', '02', '353', '3470', 22)
2021-08-18 17:41:05,767 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,768 INFO sqlalchemy.engine.base.Engine ('사랑아띠어린이집', '오준혁', '서울특별시 노원구 공릉로34길 38 ,1009동 102호(공릉동, 태강) (공릉2동)', '02', '975', '9913', 9)
2021-08-18 17:41:05,769 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,770 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '류준서', '서울특별시 구로구 경인로 390 ,210동 103호(고척동, 벽산블루밍) (고척제1동)', '02', '2616', '2356', 7)
2021-08-18 17:41:05,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,772 INFO sqlalchemy.engine.base.Engine ('고척어린이집', '류영환', '서울특별시 구로구 중앙로5길 62 ,(고척동) (고척제1동)', '02', '2686', '9745', 7)
2021-08-18 17:41:05,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,774 INFO sqlalchemy.engine.base.Engine ('솔샘어린이집', '최민서', '서울특별시 관악구 봉천로 387 ,102동 101호(봉천동, 두산아파트) [은천동] (은천동)', '02', '3285', '1105', 5)
2021-08-18 17:41:05,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,776 INFO sqlalchemy.engine.base.Engine ('롯데호텔어린이집', '오은정', '서울특별시 송파구 백제고분로45길 24 ,정명빌딩 1층 (송파동) (송파1동)', '02', '3431', '6110', 18)
2021-08-18 17:41:05,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,778 INFO sqlalchemy.engine.base.Engine ('중앙아이나라어린이집', '정영숙', '서울특별시 구로구 구로동로47길 24 ,103동 101호(구로동, 중앙하이츠아파트) (구로제2동)', '02', '868', '0522', 7)
2021-08-18 17:41:05,779 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,780 INFO sqlalchemy.engine.base.Engine ('별초롱어린이집', '이병철', '서울특별시 서대문구 응암로 28 ,4동103호(북가좌1동,연희한양아파트) (북가좌제1동)', '02', '309', '7488', 14)
2021-08-18 17:41:05,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,783 INFO sqlalchemy.engine.base.Engine ('더크는어린이집', '최경자', '서울특별시 강동구 풍성로63길 36-7 (둔촌제2동)', '02', '485', '3975', 2)
2021-08-18 17:41:05,784 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,784 INFO sqlalchemy.engine.base.Engine ('자연아이발트슐레어린이집', '안지영', '서울특별시 중랑구 동일로154길 7-7 (묵제1동)', '02', '977', '2299', 25)
2021-08-18 17:41:05,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,786 INFO sqlalchemy.engine.base.Engine ('신태양 어린이집', '한종수', '서울특별시 용산구 만리재로 178 ,(서계동) (청파동)', '02', '702', '0338', 21)
2021-08-18 17:41:05,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,788 INFO sqlalchemy.engine.base.Engine ('연세어린이집', '강경숙', '서울특별시 동대문구 장한로27나길 65 ,(장안동) (장안제2동)', '02', '2245', '6390', 11)
2021-08-18 17:41:05,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,790 INFO sqlalchemy.engine.base.Engine ('참좋은어린이집', '오광수', '서울특별시 노원구 동일로227길 25 ,1111동 102호(상계동, 상계주공11차) (상계8동)', '02', '936', '2277', 9)

2021-08-18 17:41:05,791 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,794 INFO sqlalchemy.engine.base.Engine ('아침어린이집', '서정남', '서울특별시 송파구 오금로32길 42 ,101동 101호(송파동, 현대) (송파2동)', '02', '414', '6047', 18)
2021-08-18 17:41:05,796 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,797 INFO sqlalchemy.engine.base.Engine ('예대어린이집', '한경자', '서울특별시 노원구 한글비석로46길 69 ,예대어린이집 (상계동) (상계5동)', '02', '937', '9481', 9)
2021-08-18 17:41:05,798 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,798 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '정서현', '서울특별시 중랑구 봉화산로 146 ,LG쌍용아파트 1309동 1층 (상봉제1동)', '02', '6462', '1232', 25)
2021-08-18 17:41:05,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,800 INFO sqlalchemy.engine.base.Engine ('즐거운 어린이집', '전혜진', '서울특별시 마포구 월드컵로11길 35 ,함성월드빌2차아파트 101동 101호 (망원제1동)', '02', '332', '9689', 13)
2021-08-18 17:41:05,800 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,801 INFO sqlalchemy.engine.base.Engine ('예닮아이들 어린이집', '조정수', '서울특별시 도봉구 해등로 242-11 ,102동 101호(쌍문동, 성원아파트) (쌍문제4동)', '02', '905', '4507', 10)
2021-08-18 17:41:05,802 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,802 INFO sqlalchemy.engine.base.Engine ('미래꿈어린이집', '이성호', '서울특별시 강북구 한천로130길 9 ,461-74 1층 (번1동)', '02', '995', '0789', 3)
2021-08-18 17:41:05,803 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,804 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '오유진', '서울특별시 성북구 삼선동2가 보문로29다길 31 ,115동 102호(삼선동2가, 대우푸르지오아파트) (삼선동)', '02', '741', '7142', 17)
2021-08-18 17:41:05,805 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,807 INFO sqlalchemy.engine.base.Engine ('행복한사과나무어린이집', '황민서', '서울특별시 은평구 갈현로4길 31-2 ,1층 (역촌동)', '02', '353', '4007', 22)
2021-08-18 17:41:05,808 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,809 INFO sqlalchemy.engine.base.Engine ('서울숲미래연 어린이집', '전지은', '서울특별시 성동구 금호로 15 ,서울숲푸르지오아파트 관리동 1층 (금호동4가) (금호4가동)', '02', '2298', '4280', 16)
2021-08-18 17:41:05,810 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,811 INFO sqlalchemy.engine.base.Engine ('미래클어린이집', '강민재', '서울특별시 중랑구 신내로 128 ,5동 101호(신내동, 동성아파트) (신내1동)', '02', '491', '1334', 25)
2021-08-18 17:41:05,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,812 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '한현정', '서울특별시 성동구 행당로 79 ,122동 101호(행당동, 대림이편한세상아파트) (행당제2동)', '02', '2291', '1294', 16)
2021-08-18 17:41:05,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,814 INFO sqlalchemy.engine.base.Engine ('은빛 어린이집', '한지민', '서울특별시 성북구 길음로9길 40 ,103동 103호(길음동, 삼성래미안1차아파트) (길음제1동)', '02', '941', '0026', 17)
2021-08-18 17:41:05,815 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,816 INFO sqlalchemy.engine.base.Engine ('뉴피터팬어린이집', '박현정', '서울특별시 동작구 만양로 26 ,104동 106호(노량진동, 건영) (노량진제1동)', '02', '826', '7828', 12)
2021-08-18 17:41:05,817 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,817 INFO sqlalchemy.engine.base.Engine ('꿀벌어린이집', '정준영', '서울특별시 도봉구 덕릉로59차길 36 ,(창동) (창제2동)', '02', '999', '2530', 10)
2021-08-18 17:41:05,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,819 INFO sqlalchemy.engine.base.Engine ('누리어린이집', '최지영', '서울특별시 은평구 연서로 85-1 (역촌동)', '02', '352', '9468', 22)
2021-08-18 17:41:05,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,822 INFO sqlalchemy.engine.base.Engine ('아이꿈나무어린이집', '오예은', '서울특별시 영등포구 문래로4길 6 ,201동 106호(문래동6가, 현대아파트) (문래동)', '02', '847', '9448', 20)
2021-08-18 17:41:05,823 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,823 INFO sqlalchemy.engine.base.Engine ('동화마을어린이집', '전준혁', '서울특별시 구로구 도림로 59 ,105동 104호(구로동, 구로두산아파트) (구로제4동)', '02', '867', '3332', 7)
2021-08-18 17:41:05,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,826 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '한서연', '서울특별시 강북구 삼양로139나길 33 ,(수유동) (우이동)', '02', '990', '0010', 3)
2021-08-18 17:41:05,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,828 INFO sqlalchemy.engine.base.Engine ('국민체육진흥공단어린이집', '윤현정', '서울특별시 송파구 올림픽로 424 ,올림픽공원내 올림픽수영장건물 국민체육진흥공단어린이집 (오륜동)', '02', '410', '1248', 18)
2021-08-18 17:41:05,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,830 INFO sqlalchemy.engine.base.Engine ('대림어린이집', '이성수', '서울특별시 마포구 월드컵북로30길 9-22 ,110동 1층 2호(성산동, 성산월드타운대림) (성산제2동)', '02', '302', '7858', 13)
2021-08-18 17:41:05,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,833 INFO sqlalchemy.engine.base.Engine ('즐거운 어린이집', '장정식', '서울특별시 구로구 신도림로 105 ,203동 105호(신도림동, 우성아파트) (신도림동)', '02', '2636', '5988', 7)
2021-08-18 17:41:05,834 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,835 INFO sqlalchemy.engine.base.Engine ('강서어린이집', '김영길', '서울특별시 강서구 까치산로 128 ,(화곡동) (화곡제6동)', '02', '2602', '2767', 4)
2021-08-18 17:41:05,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,838 INFO sqlalchemy.engine.base.Engine ('꿀벌어린이집', '류상훈', '서울특별시 노원구 노원로 564 ,1011동 108호(상계동, 상계주공10차) (상계8동)', '02', '937', '6902', 9)
2021-08-18 17:41:05,839 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,840 INFO sqlalchemy.engine.base.Engine ('쑥쑥어린이집', '한영진', '서울특별시 동작구 여의대방로 250 ,102동 108호(대방동, 대림아파트) (대방동)', '02', '6264', '7116', 12)
2021-08-18 17:41:05,841 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,842 INFO sqlalchemy.engine.base.Engine ('이삭어린이집', '최성호', '서울특별시 마포구 월드컵북로 167-6 ,(성산동) (성산제2동)', '02', '309', '8153', 13)
2021-08-18 17:41:05,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,844 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '박영일', '서울특별시 용산구 장문로19길 31 (보광동)', '02', '790', '8137', 21)
2021-08-18 17:41:05,845 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,846 INFO sqlalchemy.engine.base.Engine ('삼전어린이집', '전지영', '서울특별시 송파구 백제고분로32길 35 ,삼전종합사회복지관 1층 (삼전동)', '02', '421', '9489', 18)
2021-08-18 17:41:05,847 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,848 INFO sqlalchemy.engine.base.Engine ('두툼돌어린이집', '정정순', '서울특별시 용산구 후암로13길 8 ,(후암동) (후암동)', '02', '777', '8346', 21)
2021-08-18 17:41:05,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,850 INFO sqlalchemy.engine.base.Engine ('반디어린이집', '최성진', '서울특별시 노원구 중계로 230 ,509동 102호(중계동, 주공5단지아파트) (중계1동)', '02', '931', '2584', 9)
2021-08-18 17:41:05,852 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,853 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '장건우', '서울특별시 양천구 목동중앙본로 10 ,101동 102호(목동, 극동늘푸른아파트) (목2동)', '02', '2646', '6979', 19)
2021-08-18 17:41:05,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,856 INFO sqlalchemy.engine.base.Engine ('애플베이비어린이집', '이준호', '서울특별시 노원구 노해로 508 ,613동 106호(상계동, 주공아파트) (상계6.7동)', '02', '935', '2253', 9)
2021-08-18 17:41:05,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,859 INFO sqlalchemy.engine.base.Engine ('이큐어린이집', '강준호', '서울특별시 강동구 명일로 293 ,509동 105호(길동, 삼익파크) (길동)', '02', '488', '8933', 2)
2021-08-18 17:41:05,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,861 INFO sqlalchemy.engine.base.Engine ('효성어린이집', '김진호', '서울특별시 강북구 오패산로 191 ,(미아동) (송중동)', '02', '946', '0811', 3)
2021-08-18 17:41:05,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,862 INFO sqlalchemy.engine.base.Engine ('해바라기어린이집', '강준영', '서울특별시 도봉구 덕릉로59바길 10 ,(창동) (창제2동)', '02', '999', '0691', 10)
2021-08-18 17:41:05,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,865 INFO sqlalchemy.engine.base.Engine ('삼성래미안어린이집', '강정운', '서울특별시 송파구 오금로32길 14 ,삼성래미안아파트관리동 (송파동) (송파2동)', '02', '420', '3238', 18)
2021-08-18 17:41:05,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,867 INFO sqlalchemy.engine.base.Engine ('서소문삼성어린이집', '오정순', '서울특별시 중구 을지로1가 을지로 19 ,2,3,5층 서소문삼성어린이집 (명동)', '02', '757', '5463', 24)
2021-08-18 17:41:05,867 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,868 INFO sqlalchemy.engine.base.Engine ('아랑어린이집', '송준서', '서울특별시 강북구 솔샘로 159 ,106동 102호(미아동, 벽산라이브파크) (삼양동)', '02', '984', '6706', 3)
2021-08-18 17:41:05,870 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,871 INFO sqlalchemy.engine.base.Engine ('노벨어린이집', '이병철', '서울특별시 중랑구 용마공원로 34-1 (망우제3동)', '02', '439', '8053', 25)
2021-08-18 17:41:05,872 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,873 INFO sqlalchemy.engine.base.Engine ('바다의별어린이집', '한영식', '서울특별시 중랑구 면목로 388-23 (면목본동)', '02', '2209', '3351', 25)
2021-08-18 17:41:05,876 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,885 INFO sqlalchemy.engine.base.Engine ('좋은친구어린이집', '정준서', '서울특별시 노원구 동일로241길 53 ,106동 102호(상계동, 두산주공아파트) (상계1동)', '02', '6314', '7979', 9)
2021-08-18 17:41:05,886 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,888 INFO sqlalchemy.engine.base.Engine ('정다운어린이집', '이성민', '서울특별시 성북구 종암로13길 4-16 ,(종암동) (종암동)', '02', '922', '0005', 17)
2021-08-18 17:41:05,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,890 INFO sqlalchemy.engine.base.Engine ('삼성아이어린이집', '류영길', '서울특별시 영등포구 버드나루로 130 ,강변삼성래미안아파트 3차 관리동 1층 (당산제2동)', '02', '2677', '2279', 20)
2021-08-18 17:41:05,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,894 INFO sqlalchemy.engine.base.Engine ('신혜원어린이집', '이지은', '서울특별시 중랑구 상봉로12가길 1 (망우제3동)', '02', '432', '8292', 25)
2021-08-18 17:41:05,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,896 INFO sqlalchemy.engine.base.Engine ('충현방과후교실어린이집', '권종수', '서울특별시 서대문구 북아현로22길 38 ,충현동 주민센터 3층 방과후교실 (북아현동)', '02', '313', '7402', 14)
2021-08-18 17:41:05,898 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,899 INFO sqlalchemy.engine.base.Engine ('강북구청어린이집', '조영진', '서울특별시 강북구 도봉로89길 13 ,강북구청 (수유동) (수유3동)', '02', '995', '4348', 3)
2021-08-18 17:41:05,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,901 INFO sqlalchemy.engine.base.Engine ('경일어린이집', '류영철', '서울특별시 도봉구 도당로13길 34-5 (방학제2동)', '02', '3492', '2722', 10)
2021-08-18 17:41:05,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,903 INFO sqlalchemy.engine.base.Engine ('새랑꿈이랑 어린이집', '한도현', '서울특별시 용산구 새창로 70 ,삼성래미안아파트 단지내 (도원동) (용문동)', '02', '3273', '2992', 21)
2021-08-18 17:41:05,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,905 INFO sqlalchemy.engine.base.Engine ('한마음 어린이집', '장준영', '서울특별시 강서구 양천로 637 ,101동 103호(염창동, 삼성한마음아파트) (염창동)', '02', '6738', '5307', 4)
2021-08-18 17:41:05,906 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,907 INFO sqlalchemy.engine.base.Engine ('하니삐아제 어린이집', '이준호', '서울특별시 성동구 독서당로 272 ,대우아파트 관리사무소내 하니삐아제 어린이집 (금호4가동)', '02', '2297', '9501', 16)
2021-08-18 17:41:05,908 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:05,909 INFO sqlalchemy.engine.base.Engine ('구립봄샘어린이집', '정정호', '서울특별시 금천구 금하로 796 ,벽산6단지 아파트 관리동 (시흥제2동)', '02', '809', '1145', 8)
2021-08-18 17:41:05,910 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,910 INFO sqlalchemy.engine.base.Engine ('독산빅스맘어린이집', '최민서', '서울특별시 금천구 시흥대로150길 6 ,101동 108호(독산동, 한양수자인아파트) (독산제3동)', '02', '867', '0179', 8)
2021-08-18 17:41:05,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,911 INFO sqlalchemy.engine.base.Engine ('예원어린이집', '조순자', '서울특별시 금천구 금하로 816 ,513동 103호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '893', '0594', 8)
2021-08-18 17:41:05,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,913 INFO sqlalchemy.engine.base.Engine ('해와달어린이집', '정동현', '서울특별시 노원구 동일로193길 7 ,101동 104호(공릉동, 신도브래뉴2차아파트) (공릉1동)', '02', '971', '9300', 9)
2021-08-18 17:41:05,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,914 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '신지원', '서울특별시 강서구 공항대로 447 ,(등촌동) (등촌제1동)', '02', '3661', '8153', 4)
2021-08-18 17:41:05,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,915 INFO sqlalchemy.engine.base.Engine ('미성어린이집', '류준호', '서울특별시 관악구 조원로2길 13 ,1동 112호 (신림동,미성아파트) [조원동] (조원동)', '02', '854', '3141', 5)
2021-08-18 17:41:05,916 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,917 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '임예은', '서울특별시 마포구 마포대로20길 26 ,공덕2차 삼성래미안아파트 단지내 (공덕동)', '02', '3275', '1113', 13)
2021-08-18 17:41:05,919 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,920 INFO sqlalchemy.engine.base.Engine ('곤지곤지어린이집', '윤지혜', '서울특별시 마포구 월드컵북로 260 ,15동 106호(성산동, 성산시영) (성산제2동)', '02', '303', '3644', 13)
2021-08-18 17:41:05,920 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,921 INFO sqlalchemy.engine.base.Engine ('아이파크어린이집', '황민지', '서울특별시 중랑구 중랑천로 286 ,라동(묵동, 현대아이파크) (묵제2동)', '02', '971', '1266', 25)
2021-08-18 17:41:05,922 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,923 INFO sqlalchemy.engine.base.Engine ('위즈키즈어린이집', '권수빈', '서울특별시 영등포구 가마산로79길 7 ,(신길동) 삼성래미안아파트 제1상가 (신길제4동)', '02', '841', '8387', 20)
2021-08-18 17:41:05,924 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,925 INFO sqlalchemy.engine.base.Engine ('서초예랑어린이집', '임성진', '서울특별시 서초구 효령로23길 82 ,103호(방배동, 퍼시픽하우스) (방배1동)', '02', '586', '9869', 15)
2021-08-18 17:41:05,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,928 INFO sqlalchemy.engine.base.Engine ('은평교회방과후교실어린이집', '조경자', '서울특별시 은평구 은평로3길 10 ,은평성결교회 (역촌동) (역촌동)', '02', '2640', '3209', 22)
2021-08-18 17:41:05,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,930 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '최성호', '서울특별시 강서구 화곡로53길 43-13 (화곡제6동)', '02', '2606', '1732', 4)
2021-08-18 17:41:05,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,932 INFO sqlalchemy.engine.base.Engine ('신현대어린이집', '황지은', '서울특별시 동대문구 이문로1길 21 ,신현대아파트 관리소동 1층 (회기동) (회기동)', '02', '959', '7989', 11)
2021-08-18 17:41:05,934 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,935 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '강도현', '서울특별시 동대문구 사가정로 148 ,112동 103호(전농동, SK아파트) (전농제2동)', '02', '2248', '9802', 11)
2021-08-18 17:41:05,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,937 INFO sqlalchemy.engine.base.Engine ('예삐어린이집', '한민지', '서울특별시 관악구 문성로 238 ,1,2층 (신림동) [신원동] (신원동)', '02', '863', '7884', 5)
2021-08-18 17:41:05,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,940 INFO sqlalchemy.engine.base.Engine ('한솔키즈클럽어린이집', '오성진', '서울특별시 서대문구 문화촌길 6-24 ,문화촌 현대아파트 상가내 (홍제제3동)', '02', '394', '1192', 14)
2021-08-18 17:41:05,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,944 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '황정순', '서울특별시 구로구 가마산로20라길 20-16 (구로제2동)', '02', '838', '8481', 7)
2021-08-18 17:41:05,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,946 INFO sqlalchemy.engine.base.Engine ('하늘정원어린이집', '한영철', '서울특별시 서대문구 독립문로14길 56 ,104동 상가 101호(냉천동, 동부센트레빌아파트) (천연동)', '02', '393', '6323', 14)
2021-08-18 17:41:05,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,947 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '조은경', '서울특별시 강동구 양재대로130길 26 ,101호(명일동,다성씨티아파트) (명일제1동)', '02', '3427', '0913', 2)
2021-08-18 17:41:05,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,949 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '박동현', '서울특별시 중랑구 면목로37길 57 ,두산3차아파트 301동 1층 (면목동) (면목제7동)', '02', '2209', '1475', 25)
2021-08-18 17:41:05,950 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,951 INFO sqlalchemy.engine.base.Engine ('큰숲어린이집', '조성진', '서울특별시 노원구 한글비석로14길 8 ,210동 103호(중계동, 주공2단지아파트) (중계4동)', '02', '6231', '0205', 9)
2021-08-18 17:41:05,952 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,953 INFO sqlalchemy.engine.base.Engine ('수잔나어린이집', '김민재', '서울특별시 강서구 강서로15길 24 ,태흥빌라 102호 (화곡동) (화곡제1동)', '02', '2607', '0224', 4)
2021-08-18 17:41:05,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,957 INFO sqlalchemy.engine.base.Engine ('성동 어린이집', '전상훈', '서울특별시 성동구 금호동2가 무수막길 80 ,1층 (금호동2가) (금호2.3가동)', '02', '2231', '9797', 16)
2021-08-18 17:41:05,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,959 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '전지민', '서울특별시 양천구 목동동로 10 ,1106동 101호(신정동, 신시가지11단지아파트) (신정7동)', '02', '6095', '0531', 19)

2021-08-18 17:41:05,960 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,960 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '서예준', '서울특별시 중랑구 면목로21길 5 (면목제4동)', '02', '432', '2472', 25)
2021-08-18 17:41:05,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,963 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '정준호', '서울특별시 마포구 성암로 91 ,102동 103호(중동, 현대아파트) (성산제2동)', '02', '307', '3250', 13)
2021-08-18 17:41:05,964 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,965 INFO sqlalchemy.engine.base.Engine ('성심어린이집', '강준영', '서울특별시 송파구 백제고분로40길 19-8 ,() (석촌동)', '02', '418', '3889', 18)
2021-08-18 17:41:05,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,967 INFO sqlalchemy.engine.base.Engine ('이현어린이집', '황종수', '서울특별시 구로구 경인로 382 ,101동 102호(개봉동, 한마을아파트) (개봉제1동)', '02', '2613', '2720', 7)
2021-08-18 17:41:05,968 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,969 INFO sqlalchemy.engine.base.Engine ('아이사랑영재 어린이집', '김건우', '서울특별시 성동구 고산자로 164 ,102동 104호(행당동, 행당한신) (행당제1동)', '02', '2299', '4470', 16)
2021-08-18 17:41:05,970 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,972 INFO sqlalchemy.engine.base.Engine ('시온어린이집', '오영환', '서울특별시 중랑구 면목로84길 31 ,(면목동) (면목본동)', '02', '2207', '6006', 25)
2021-08-18 17:41:05,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,973 INFO sqlalchemy.engine.base.Engine ('예꿈아이어린이집', '강성민', '서울특별시 동작구 현충로 119 ,102동 104호(흑석동, 명수대현대아파트) (흑석동)', '02', '826', '1170', 12)
2021-08-18 17:41:05,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,975 INFO sqlalchemy.engine.base.Engine ('예쁜무지개어린이집', '강현준', '서울특별시 은평구 은평로16길 22-6 (응암제1동)', '02', '359', '2220', 22)
2021-08-18 17:41:05,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,977 INFO sqlalchemy.engine.base.Engine ('중앙하이츠 어린이집', '황영환', '서울특별시 구로구 구로동로47길 24 ,(구로동, 중앙하이츠아파트 관리동1층) (구로제2동)', '02', '859', '5555', 7)
2021-08-18 17:41:05,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,978 INFO sqlalchemy.engine.base.Engine ('벽산타운사임당어린이집', '안민지', '서울특별시 금천구 금하로 816 ,517동 103호(시흥동, 관악산벽산타운아파트) (시흥제2동)', '02', '802', '3517', 8)
2021-08-18 17:41:05,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,981 INFO sqlalchemy.engine.base.Engine ('아이자람어린이집', '오예준', '서울특별시 광진구 아차산로70길 62 ,304동 102호(광장동, 현대3단지아파트) (광장동)', '02', '453', '1486', 6)
2021-08-18 17:41:05,985 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,986 INFO sqlalchemy.engine.base.Engine ('바로미어린이집', '김지은', '서울특별시 서초구 서초중앙로 157 ,서울법원종합청사별관 (서초동) (서초3동)', '02', '530', '2632', 15)
2021-08-18 17:41:05,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,988 INFO sqlalchemy.engine.base.Engine ('아렌어린이집', '정광수', '서울특별시 동작구 양녕로26길 64 ,(상도동) (상도제4동)', '02', '825', '1187', 12)
2021-08-18 17:41:05,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,990 INFO sqlalchemy.engine.base.Engine ('꿈별어린이집', '윤정운', '서울특별시 강남구 양재대로55길 10 ,118동 106호(일원동, 수서1단지아파트) (일원제1동)', '02', '445', '9381', 1)
2021-08-18 17:41:05,991 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,992 INFO sqlalchemy.engine.base.Engine ('굿모닝어린이집', '오광수', '서울특별시 관악구 호암로 417 ,국제산장아파트 관리동 2층 [삼성동] (신림동) (삼성동)', '02', '871', '2155', 5)
2021-08-18 17:41:05,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,993 INFO sqlalchemy.engine.base.Engine ('하계지혜어린이집', '전지영', '서울특별시 노원구 섬밭로 196 ,607동 105호(하계동, 장미) (하계2동)', '02', '6061', '5077', 9)
2021-08-18 17:41:05,994 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,994 INFO sqlalchemy.engine.base.Engine ('기쁜어린이집', '류영철', '서울특별시 서초구 바우뫼로9길 22-8 ,(우면동) (양재1동)', '070', '7539', '6887', 15)
2021-08-18 17:41:05,995 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,996 INFO sqlalchemy.engine.base.Engine ('구의사랑어린이집', '최정호', '서울특별시 광진구 자양로48길 31 ,(구의동) (구의제2동)', '02', '456', '7339', 6)
2021-08-18 17:41:05,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,997 INFO sqlalchemy.engine.base.Engine ('연두어린이집', '오예준', '서울특별시 강북구 월계로21가길 14-5 ,(미아동) (송중동)', '02', '983', '8655', 3)
2021-08-18 17:41:05,998 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:05,999 INFO sqlalchemy.engine.base.Engine ('우리꿈어린이집', '강지원', '서울특별시 노원구 동일로214길 21 ,409동 106호(상계동, 상계주공4단지아파트) (상계6.7동)', '02', '6223', '9975', 9)
2021-08-18 17:41:06,000 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,001 INFO sqlalchemy.engine.base.Engine ('도담도담어린이집', '조민수', '서울특별시 중랑구 동일로 476 ,102동 107호(면목동, 늘푸른동아아파트) (면목제4동)', '02', '435', '7787', 25)
2021-08-18 17:41:06,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,004 INFO sqlalchemy.engine.base.Engine ('웰라이어린이집', '권광수', '서울특별시 영등포구 영등포로62길 42 ,101동 104호(영등포동, 순영웰라이빌) (영등포본동)', '02', '842', '3412', 20)
2021-08-18 17:41:06,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,008 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '류혜진', '서울특별시 동대문구 답십리로26길 12 ,(전농동) (전농제1동)', '02', '2212', '2207', 11)
2021-08-18 17:41:06,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,010 INFO sqlalchemy.engine.base.Engine ('예그리나어린이집', '전영진', '서울특별시 노원구 동일로208길 20 ,206동 110호(중계동, 중계무지개아파트) (중계2.3동)', '02', '973', '7929', 9)
2021-08-18 17:41:06,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,016 INFO sqlalchemy.engine.base.Engine ('청은어린이집', '윤성호', '서울특별시 노원구 한글비석로 203 ,(중계동) (중계1동)', '02', '931', '8268', 9)
2021-08-18 17:41:06,017 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,018 INFO sqlalchemy.engine.base.Engine ('아띠어린이집', '신성호', '서울특별시 노원구 동일로208길 20 ,210동 106호(중계동, 중계무지개아파트) (중계2.3동)', '02', '6229', '4435', 9)
2021-08-18 17:41:06,019 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,020 INFO sqlalchemy.engine.base.Engine ('동화속어린이집', '강정수', '서울특별시 노원구 한글비석로 479 ,101동 113호(상계동, 보람1단지아파트) (상계9동)', '02', '939', '2330', 9)
2021-08-18 17:41:06,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,021 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '권민재', '서울특별시 영등포구 도신로29길 28 ,205동 104호(영등포동, 영등포푸르지오2단지아파트) (영등포본동)', '02', '6677', '6363', 20)
2021-08-18 17:41:06,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,023 INFO sqlalchemy.engine.base.Engine ('늘사랑어린이집', '박미영', '서울특별시 도봉구 해등로 206 ,7동 101호(쌍문동, 금호1차아파트) (쌍문제4동)', '02', '904', '8060', 10)
2021-08-18 17:41:06,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,025 INFO sqlalchemy.engine.base.Engine ('동아 어린이집', '임예은', '서울특별시 성북구 장월로1길 28 ,110동 104호(상월곡동, 동아에코빌아파트) (월곡제2동)', '02', '942', '0380', 17)
2021-08-18 17:41:06,026 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,026 INFO sqlalchemy.engine.base.Engine ('라임어린이집', '정지혜', '서울특별시 관악구 난곡로35길 28-7 ,라동 103호(신림동,건영아파트) (난곡동)', '02', '6269', '1717', 5)
2021-08-18 17:41:06,027 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,028 INFO sqlalchemy.engine.base.Engine ('효창방과후어린이집', '임정수', '서울특별시 용산구 효창원로 146-12 (효창동)', '070', '4713', '9433', 21)
2021-08-18 17:41:06,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,030 INFO sqlalchemy.engine.base.Engine ('해맑은방과후교실어린이집', '권정운', '서울특별시 강서구 방화대로48길 40 ,(방화동) (방화제3동)', '070', '4339', '5343', 4)
2021-08-18 17:41:06,030 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,031 INFO sqlalchemy.engine.base.Engine ('강동해님이놀러온어린이집', '오준서', '서울특별시 강동구 풍성로41길 64-41 ,(성내동 233-7) (성내제2동)', '02', '483', '1265', 2)
2021-08-18 17:41:06,032 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,032 INFO sqlalchemy.engine.base.Engine ('인화어린이집', '황동현', '서울특별시 양천구 목동동로 130 ,1429동 101호(신정동, 목동신시가지14단지아파트) (신정6동)', '02', '2642', '4229', 19)
2021-08-18 17:41:06,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,034 INFO sqlalchemy.engine.base.Engine ('상계종합사회복지관방과후어린이집', '박서연', '서울특별시 노원구 덕릉로115나길 25 ,(상계동) (상계3.4동)', '02', '951', '9930', 9)
2021-08-18 17:41:06,035 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,038 INFO sqlalchemy.engine.base.Engine ('경성어린이집', '강현정', '서울특별시 동대문구 신이문로 3-4 (이문제2동)', '02', '965', '2835', 11)
2021-08-18 17:41:06,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,040 INFO sqlalchemy.engine.base.Engine ('래미안파인탑어린이집', '신영철', '서울특별시 송파구 오금로32길 31 ,래미안송파파인탑 단지 내 (송파2동)', '02', '2202', '6112', 18)
2021-08-18 17:41:06,041 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,042 INFO sqlalchemy.engine.base.Engine ('동아리틀어린이집', '장성호', '서울특별시 구로구 신도림로 78 ,동아3차아파트 관리동 1층 (신도림동)', '02', '2678', '0227', 7)
2021-08-18 17:41:06,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,044 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '한경숙', '서울특별시 강동구 명일로 102 ,102동 105호(둔촌동, 둔촌신성미소지움1차아파트) (둔촌제2동)', '02', '474', '9839', 2)
2021-08-18 17:41:06,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,046 INFO sqlalchemy.engine.base.Engine ('향기로운어린이집', '이정자', '서울특별시 강동구 양재대로130길 47 ,명일동 268-2 (명일제1동)', '02', '6471', '1235', 2)
2021-08-18 17:41:06,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,048 INFO sqlalchemy.engine.base.Engine ('꿈동산어린이집', '박지원', '서울특별시 관악구 봉천로21길 66 ,보라매동] (봉천동) (보라매동)', '02', '888', '2611', 5)
2021-08-18 17:41:06,048 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,050 INFO sqlalchemy.engine.base.Engine ('예꼬어린이집', '윤은영', '서울특별시 영등포구 도신로29길 28 ,202동 101호(영등포동, 영등포푸르지오2단지아파트) (영등포본동)', '02', '844', '5994', 20)
2021-08-18 17:41:06,050 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,052 INFO sqlalchemy.engine.base.Engine ('천응방과후어린이집', '송정남', '서울특별시 동대문구 제기로 128-6 (청량리동)', '02', '965', '2423', 11)
2021-08-18 17:41:06,052 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,053 INFO sqlalchemy.engine.base.Engine ('가베영재어린이집', '최영길', '서울특별시 노원구 동일로239길 68 ,102동 108호(상계동, 상계대림E편한세상) (상계1동)', '02', '932', '8999', 9)
2021-08-18 17:41:06,054 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,055 INFO sqlalchemy.engine.base.Engine ('현대해바라기어린이집', '정진호', '서울특별시 노원구 중계로8길 106 ,112동 103호(중계동, 현대4차아파트) (중계본동)', '02', '6314', '2061', 9)
2021-08-18 17:41:06,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,057 INFO sqlalchemy.engine.base.Engine ('노틀담방과후교실어린이집', '박성진', '서울특별시 종로구 북촌로 54 ,가회동 (가회동)', '02', '762', '8010', 23)
2021-08-18 17:41:06,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,062 INFO sqlalchemy.engine.base.Engine ('용마어린이집', '오지민', '서울특별시 중랑구 용마산로 393 ,(면목동) (면목제3.8동)', '02', '439', '5595', 25)
2021-08-18 17:41:06,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,064 INFO sqlalchemy.engine.base.Engine ('민들레어린이집', '윤동현', '서울특별시 광진구 뚝섬로52마길 32 ,(자양동) (자양제2동)', '02', '456', '5003', 6)

2021-08-18 17:41:06,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,066 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '최미경', '서울특별시 영등포구 도신로29길 28 ,215동 104호(영등포동, 영등포푸르지오2단지아파트) (영등포본동)', '02', '833', '2285', 20)
2021-08-18 17:41:06,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,068 INFO sqlalchemy.engine.base.Engine ('새누리어린이집', '장지훈', '서울특별시 은평구 가좌로7나길 35 ,경남아파트단지 내 (응암동) (응암제3동)', '02', '307', '6955', 22)
2021-08-18 17:41:06,071 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,072 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '송영철', '서울특별시 금천구 시흥대로144길 27 ,(독산동) (독산제3동)', '02', '855', '5101', 8)
2021-08-18 17:41:06,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,074 INFO sqlalchemy.engine.base.Engine ('아이스쿨어린이집', '황병철', '서울특별시 광진구 용마산로3길 91-4 ,(중곡동) (중곡제2동)', '02', '447', '0412', 6)
2021-08-18 17:41:06,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,078 INFO sqlalchemy.engine.base.Engine ('신사어린이집', '정준혁', '서울특별시 강남구 도산대로15길 26 ,(신사동) (신사동)', '02', '548', '5240', 1)
2021-08-18 17:41:06,079 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,080 INFO sqlalchemy.engine.base.Engine ('예뜰어린이집', '안은영', '서울특별시 구로구 구로동로7길 27 ,(가리봉동) (가리봉동)', '02', '866', '0779', 7)
2021-08-18 17:41:06,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,081 INFO sqlalchemy.engine.base.Engine ('희망누리어린이집', '정준호', '서울특별시 노원구 석계로13길 6-9 ,101동 101호(월계동, 장은아파트) (월계1동)', '02', '942', '6033', 9)
2021-08-18 17:41:06,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,083 INFO sqlalchemy.engine.base.Engine ('꿈초롱어린이집', '안지민', '서울특별시 중랑구 중랑천로14길 34 ,202동 102호(중화동,동양엔파트2차) (중화제2동)', '02', '493', '8996', 25)
2021-08-18 17:41:06,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,084 INFO sqlalchemy.engine.base.Engine ('구립공항어린이집', '김준혁', '서울특별시 강서구 남부순환로11길 81 ,(공항동) (공항동)', '02', '2665', '1514', 4)
2021-08-18 17:41:06,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,086 INFO sqlalchemy.engine.base.Engine ('신명나는어린이집', '서은정', '서울특별시 노원구 동일로228길 23 ,1412동 106호(상계동, 상계주공14차) (상계9동)', '02', '6232', '3325', 9)
2021-08-18 17:41:06,087 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,088 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '권광수', '서울특별시 성북구 보국문로17길 8 ,(정릉동) (정릉제4동)', '02', '913', '8564', 17)
2021-08-18 17:41:06,089 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,090 INFO sqlalchemy.engine.base.Engine ('예쁜별어린이집', '서병철', '서울특별시 구로구 서해안로28길 18 ,(오류동) (오류제2동)', '02', '2618', '6187', 7)
2021-08-18 17:41:06,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,092 INFO sqlalchemy.engine.base.Engine ('인성어린이집', '송도현', '서울특별시 강남구 개포로109길 5 ,305동 102호(개포동, 대청아파트) (일원제2동)', '02', '459', '0360', 1)
2021-08-18 17:41:06,093 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,094 INFO sqlalchemy.engine.base.Engine ('신창아가어린이집', '조건우', '서울특별시 도봉구 덕릉로62길 13 ,신창아파트 내 (창동) (창제3동)', '02', '996', '2716', 10)
2021-08-18 17:41:06,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,096 INFO sqlalchemy.engine.base.Engine ('큰나무어린이집', '송현정', '서울특별시 송파구 송파대로 567 ,527동 101호(잠실동, 주공아파트) (잠실3동)', '02', '413', '7036', 18)
2021-08-18 17:41:06,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,100 INFO sqlalchemy.engine.base.Engine ('피카소어린이집', '임영자', '서울특별시 구로구 고척로30길 8 ,(개봉동) (개봉제1동)', '02', '2618', '6229', 7)
2021-08-18 17:41:06,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,102 INFO sqlalchemy.engine.base.Engine ('아이맘어린이집', '한민지', '서울특별시 강북구 삼각산로34길 42 ,(수유동) (수유3동)', '02', '991', '6960', 3)
2021-08-18 17:41:06,104 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,105 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '안정호', '서울특별시 관악구 인헌길 116 ,101호 (봉천동,라인맨션) [인헌동] (인헌동)', '02', '875', '2711', 5)
2021-08-18 17:41:06,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,107 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '류성호', '서울특별시 강북구 노해로25길 62 ,(수유동) (수유2동)', '02', '997', '4241', 3)
2021-08-18 17:41:06,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,109 INFO sqlalchemy.engine.base.Engine ('구립 하늘숲어린이집', '송영자', '서울특별시 강서구 강서로45다길 102 ,(화곡동) (화곡제3동)', '02', '2699', '2220', 4)
2021-08-18 17:41:06,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,111 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '최광수', '서울특별시 관악구 은천로 86 ,2단지 관리동 1층 (봉천동, 두산아파트) [은천동] (은천동)', '02', '875', '3455', 5)
2021-08-18 17:41:06,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,113 INFO sqlalchemy.engine.base.Engine ('언남해피어린이집', '윤미숙', '서울특별시 서초구 동산로13길 35 ,(양재동) (양재2동)', '02', '576', '7525', 15)
2021-08-18 17:41:06,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,114 INFO sqlalchemy.engine.base.Engine ('꿈땅어린이집', '이성수', '서울특별시 성북구 장월로 28 ,. (장위제2동)', '02', '911', '3920', 17)
2021-08-18 17:41:06,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,116 INFO sqlalchemy.engine.base.Engine ('누리어린이집', '최성민', '서울특별시 양천구 목동서로 236 ,102동 103호(목동, 벽산아파트) (목1동)', '02', '2642', '4789', 19)
2021-08-18 17:41:06,117 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,118 INFO sqlalchemy.engine.base.Engine ('고려대학교의료원 안암병원 어린이집', '오영자', '서울특별시 성북구 안암로 145 ,(안암동5가 산1-61) (안암동)', '02', '921', '6585', 17)

2021-08-18 17:41:06,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,120 INFO sqlalchemy.engine.base.Engine ('미예뜰어린이집', '임순자', '서울특별시 광진구 긴고랑로7길 69 ,(중곡동) (중곡제3동)', '02', '463', '4242', 6)
2021-08-18 17:41:06,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,122 INFO sqlalchemy.engine.base.Engine ('신일교회어린이집', '김정순', '서울특별시 중구 다산로 128-9 (약수동)', '02', '2253', '1159', 24)
2021-08-18 17:41:06,123 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,124 INFO sqlalchemy.engine.base.Engine ('햇살꼬마숲어린이집', '서은경', '서울특별시 용산구 원효로 216 ,109동 104호(신계동, 용산E편한세상) (원효로제1동)', '02', '714', '3151', 21)
2021-08-18 17:41:06,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,126 INFO sqlalchemy.engine.base.Engine ('행복한우리어린이집', '송영철', '서울특별시 성북구 아리랑로19다길 38-14 (정릉제2동)', '02', '942', '7032', 17)
2021-08-18 17:41:06,127 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,128 INFO sqlalchemy.engine.base.Engine ('구립 은행어린이집', '박미경', '서울특별시 성동구 고산자로10길 18 ,(행당동) (행당제1동)', '02', '2281', '4477', 16)
2021-08-18 17:41:06,129 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,130 INFO sqlalchemy.engine.base.Engine ('단비어린이집', '신정수', '서울특별시 강동구 명일로 293 ,502동 106호(길동, 삼익파크) (길동)', '02', '483', '5919', 2)
2021-08-18 17:41:06,131 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,132 INFO sqlalchemy.engine.base.Engine ('에듀케어어린이집', '최준호', '서울특별시 강남구 선릉로130길 19 ,102동 108호(삼성동, 서광) (삼성제2동)', '02', '517', '1417', 1)
2021-08-18 17:41:06,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,134 INFO sqlalchemy.engine.base.Engine ('구로한빛어린이집', '김정호', '서울특별시 구로구 서해안로34가길 18 ,금강아파트 상가 (오류동) (오류제2동)', '02', '2615', '8926', 7)
2021-08-18 17:41:06,136 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,137 INFO sqlalchemy.engine.base.Engine ('새꿈어린이집', '정준혁', '서울특별시 용산구 후암로57길 26 ,(동자동) (남영동)', '02', '775', '6514', 21)
2021-08-18 17:41:06,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,140 INFO sqlalchemy.engine.base.Engine ('꿈꾸는어린이집', '박상철', '서울특별시 광진구 능동로50길 23 ,(중곡동) (중곡제3동)', '02', '454', '9797', 6)
2021-08-18 17:41:06,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,145 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '정준영', '서울특별시 노원구 동일로227길 25 ,1110동 101호(상계동, 상계주공11단지아파트) (상계8동)', '02', '934', '3095', 9)
2021-08-18 17:41:06,147 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,148 INFO sqlalchemy.engine.base.Engine ('아기천국어린이집', '신동현', '서울특별시 강동구 진황도로27길 9 ,(천호동166-81) (천호제3동)', '02', '471', '1576', 2)
2021-08-18 17:41:06,150 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,151 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '안상철', '서울특별시 성북구 숭인로2길 61 ,동부센트레빌아파트 관리동 1층 (길음제2동)', '02', '983', '9886', 17)
2021-08-18 17:41:06,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,153 INFO sqlalchemy.engine.base.Engine ('비테에어린이집', '한성진', '서울특별시 강북구 솔샘로 174 ,관리동 (미아동, SK아파트) (삼각산동)', '02', '982', '3833', 3)
2021-08-18 17:41:06,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,155 INFO sqlalchemy.engine.base.Engine ('동아어린이집', '김준호', '서울특별시 구로구 경인로 643 ,신도림동, 동아2차아파트 관리동 (신도림동)', '02', '2678', '4008', 7)
2021-08-18 17:41:06,157 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,158 INFO sqlalchemy.engine.base.Engine ('우정어린이집', '권지훈', '서울특별시 서대문구 연희로8길 21 ,구립 우정어린이집 (연희동)', '02', '3143', '4925', 14)
2021-08-18 17:41:06,159 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,160 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '오영자', '서울특별시 동대문구 황물로 32 ,서울특별시 동대문구 황물로 32(답십리동) 초롱 어린이집 (답십리제1동)', '02', '2212', '6314', 11)
2021-08-18 17:41:06,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,162 INFO sqlalchemy.engine.base.Engine ('대건어린이집', '조도현', '서울특별시 중랑구 신내로7길 6 ,(신내동) (신내2동)', '02', '2208', '0457', 25)
2021-08-18 17:41:06,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,163 INFO sqlalchemy.engine.base.Engine ('삼동어린이집', '권성진', '서울특별시 강북구 한천로105길 24 ,202동(번동, 주공2단지아파트) (번3동)', '02', '989', '5696', 3)
2021-08-18 17:41:06,164 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,164 INFO sqlalchemy.engine.base.Engine ('수정어린이집', '송미숙', '서울특별시 도봉구 마들로 616 ,104동 103호(방학동, 대상타운현대아파트) (방학제1동)', '02', '956', '7810', 10)
2021-08-18 17:41:06,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,169 INFO sqlalchemy.engine.base.Engine ('창4동어린이집', '오영진', '서울특별시 도봉구 마들로 339-13 (창제4동)', '02', '996', '3222', 10)
2021-08-18 17:41:06,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,171 INFO sqlalchemy.engine.base.Engine ('둥근달어린이집', '송성호', '서울특별시 도봉구 도봉로117길 80-7 (쌍문제3동)', '02', '990', '0121', 10)
2021-08-18 17:41:06,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,173 INFO sqlalchemy.engine.base.Engine ('새날어린이집', '오건우', '서울특별시 용산구 새창로8길 7 ,삼성래미안아파트 2단지내 관리동1층 (도원동) (용문동)', '02', '718', '6635', 21)
2021-08-18 17:41:06,174 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,174 INFO sqlalchemy.engine.base.Engine ('알지오어린이집', '권준혁', '서울특별시 중랑구 봉화산로3길 229-6 ,(묵동) (묵제2동)', '02', '3422', '0988', 25)
2021-08-18 17:41:06,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,177 INFO sqlalchemy.engine.base.Engine ('우림어린이집', '정민수', '서울특별시 은평구 연서로18길 7 ,(대조동) (대조동)', '02', '357', '2235', 22)

2021-08-18 17:41:06,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,180 INFO sqlalchemy.engine.base.Engine ('온누리어린이집', '임예은', '서울특별시 노원구 동일로227길 47 ,(상계동) (상계8동)', '02', '937', '2080', 9)
2021-08-18 17:41:06,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,181 INFO sqlalchemy.engine.base.Engine ('이모어린이집', '정서현', '서울특별시 노원구 마들로 31 ,102동 101호(월계동, 한진한화그랑빌) (월계3동)', '02', '948', '1212', 9)
2021-08-18 17:41:06,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,183 INFO sqlalchemy.engine.base.Engine ('자이어린이집', '신준서', '서울특별시 동작구 사당로2가길 102 (사당제5동)', '02', '587', '1139', 12)
2021-08-18 17:41:06,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,186 INFO sqlalchemy.engine.base.Engine ('신파랑새어린이집', '권은영', '서울특별시 광진구 영화사로9길 32 ,A동 104호(중곡동, 현대하이츠빌라) (중곡제4동)', '02', '3436', '3631', 6)
2021-08-18 17:41:06,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,188 INFO sqlalchemy.engine.base.Engine ('큐티프리스쿨어린이집', '조미경', '서울특별시 관악구 호암로 399 ,관리동 (신림동,삼성산주공아파트) [삼성동] (삼성동)', '02', '3285', '2030', 5)
2021-08-18 17:41:06,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,190 INFO sqlalchemy.engine.base.Engine ('구름나무어린이집', '한정남', '서울특별시 성북구 장위로 51 ,(장위동) (장위제1동)', '02', '915', '6076', 17)
2021-08-18 17:41:06,191 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,191 INFO sqlalchemy.engine.base.Engine ('늘푸른아이어린이집', '안준호', '서울특별시 노원구 노원로 564 ,1002동 108호(상계동, 상계주공10차) (상계8동)', '02', '933', '0877', 9)
2021-08-18 17:41:06,192 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,193 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '조성진', '서울특별시 서대문구 연희로32길 48 ,101동 보육시설 (연희동)', '02', '325', '9355', 14)
2021-08-18 17:41:06,194 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,195 INFO sqlalchemy.engine.base.Engine ('송림어린이집', '신은영', '서울특별시 동대문구 장안벚꽃로 167 ,209동 103호(장안동, 장안아파트2단지) (장안제2동)', '02', '2212', '8480', 11)
2021-08-18 17:41:06,196 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,196 INFO sqlalchemy.engine.base.Engine ('보현어린이집', '이병철', '서울특별시 강북구 솔샘로 174 ,140동 104호 (미아동, 에스케이북한산시티아파트) (삼각산동)', '02', '982', '3720', 3)
2021-08-18 17:41:06,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,198 INFO sqlalchemy.engine.base.Engine ('아름누리어린이집', '정성수', '서울특별시 금천구 독산로50길 89 ,삼익아파트 단지내 (시흥제4동)', '02', '893', '6333', 8)
2021-08-18 17:41:06,199 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,200 INFO sqlalchemy.engine.base.Engine ('자양미래몬테소리어린이집', '신동현', '서울특별시 광진구 자양번영로3길 6 ,(자양동) (자양제3동)', '02', '457', '3497', 6)
2021-08-18 17:41:06,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,203 INFO sqlalchemy.engine.base.Engine ('라온어린이집', '정지영', '서울특별시 성동구 살곶이길 50 ,107동 102호(마장동, 현대아파트) (마장동)', '02', '2297', '9229', 16)
2021-08-18 17:41:06,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,205 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '박예준', '서울특별시 강북구 삼양로149가길 17 ,(우이동) (우이동)', '02', '997', '2206', 3)
2021-08-18 17:41:06,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,207 INFO sqlalchemy.engine.base.Engine ('월계비츠어린이집', '최은경', '서울특별시 노원구 마들로 31 ,108동 101호(월계동, 한진한화그랑빌) (월계3동)', '02', '949', '9772', 9)
2021-08-18 17:41:06,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,208 INFO sqlalchemy.engine.base.Engine ('효림어린이집', '장지혜', '서울특별시 동대문구 한천로 248 ,111동 105호(휘경동, 주공아파트) (휘경제2동)', '02', '6238', '0460', 11)
2021-08-18 17:41:06,209 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,210 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '신정순', '서울특별시 광진구 자양로47길 11 ,(구의2동) (구의제2동)', '02', '452', '7639', 6)
2021-08-18 17:41:06,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,212 INFO sqlalchemy.engine.base.Engine ('성복어린이집', '권정수', '서울특별시 성북구 월곡로 2 ,(종암동) (종암동)', '02', '941', '8830', 17)
2021-08-18 17:41:06,213 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,214 INFO sqlalchemy.engine.base.Engine ('베어스어린이집', '김지원', '서울특별시 영등포구 선유서로 40 ,101동 106호(문래동6가, 베어스타운아파트) (문래동)', '02', '6264', '0521', 20)
2021-08-18 17:41:06,215 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,216 INFO sqlalchemy.engine.base.Engine ('새롬어린이집', '김영숙', '서울특별시 은평구 증산로5길 10 ,(증산동) (증산동)', '02', '303', '0820', 22)
2021-08-18 17:41:06,217 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,218 INFO sqlalchemy.engine.base.Engine ('삼보어린이집', '서예준', '서울특별시 성북구 화랑로13길 79-10 (월곡제1동)', '02', '915', '0507', 17)
2021-08-18 17:41:06,219 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,220 INFO sqlalchemy.engine.base.Engine ('행복한어린이집', '강광수', '서울특별시 성북구 숭인로2길 61 ,110동 103호(길음동, 동부센트레빌아파트) (길음제2동)', '02', '984', '7600', 17)
2021-08-18 17:41:06,221 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,221 INFO sqlalchemy.engine.base.Engine ('예님어린이집', '정영진', '서울특별시 영등포구 도영로7길 10 ,(도림동) (도림동)', '02', '849', '0466', 20)
2021-08-18 17:41:06,222 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,223 INFO sqlalchemy.engine.base.Engine ('꼬마에디슨 어린이집', '류정자', '서울특별시 성동구 금호동1가 금호로 100 ,벽산아파트 관리동 (금호1가동)', '02', '2293', '8090', 16)
2021-08-18 17:41:06,223 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,225 INFO sqlalchemy.engine.base.Engine ('별나라어린이집', '조민지', '서울특별시 강북구 솔샘로 159 ,110동 101호(미아동, 벽산라이브파크) (삼양동)', '02', '983', '5960', 3)

2021-08-18 17:41:06,226 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,227 INFO sqlalchemy.engine.base.Engine ('꼬꼬마가베어린이집', '임민서', '서울특별시 노원구 동일로 1456 ,715동 114호(상계동, 상계주공7차) (상계10동)', '02', '952', '1981', 9)
2021-08-18 17:41:06,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,228 INFO sqlalchemy.engine.base.Engine ('아트성광어린이집', '신영숙', '서울특별시 노원구 한글비석로27길 29 ,(상계동) (상계5동)', '02', '936', '1521', 9)
2021-08-18 17:41:06,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,232 INFO sqlalchemy.engine.base.Engine ('대천어린이집', '전정순', '서울특별시 동작구 신대방14가길 23 ,(신대방동) (신대방제1동)', '02', '847', '0456', 12)
2021-08-18 17:41:06,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,236 INFO sqlalchemy.engine.base.Engine ('꿈아이 어린이집', '류상훈', '서울특별시 성북구 숭인로 16 ,102동 104호(길음동, 동부센트레빌아파트) (길음제2동)', '02', '6317', '5837', 17)
2021-08-18 17:41:06,238 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,239 INFO sqlalchemy.engine.base.Engine ('해찬어린이집', '장영환', '서울특별시 동대문구 한천로 248 ,휘경주공2차아파트 단지동 (휘경동) (휘경제2동)', '02', '6451', '7942', 11)
2021-08-18 17:41:06,241 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,242 INFO sqlalchemy.engine.base.Engine ('성광어린이집', '강예은', '서울특별시 노원구 상계로18길 32 ,(상계동) (상계2동)', '02', '936', '9506', 9)
2021-08-18 17:41:06,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,244 INFO sqlalchemy.engine.base.Engine ('여의도아이사랑어린이집', '조정운', '서울특별시 영등포구 국제금융로 79 ,C동 102호(여의도동, 한양아파트) (여의동)', '02', '786', '7642', 20)
2021-08-18 17:41:06,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,247 INFO sqlalchemy.engine.base.Engine ('풍림어린이집', '박은영', '서울특별시 노원구 섬밭로 139 ,풍림아파트 단지내 어린이집 (공릉동) (공릉1동)', '02', '973', '5452', 9)
2021-08-18 17:41:06,249 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,250 INFO sqlalchemy.engine.base.Engine ('강남영재어린이집', '장성진', '서울특별시 강남구 논현로 205 ,(도곡동) (도곡1동)', '02', '575', '4033', 1)
2021-08-18 17:41:06,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,254 INFO sqlalchemy.engine.base.Engine ('솔어린이집', '한경회', '서울특별시 용산구 장문로 95 ,(보광동) (보광동)', '02', '797', '6858', 21)
2021-08-18 17:41:06,255 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,256 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '김영일', '서울특별시 동작구 양녕로27길 60 ,(상도동) (상도제4동)', '02', '816', '2226', 12)
2021-08-18 17:41:06,259 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,260 INFO sqlalchemy.engine.base.Engine ('향기어린이집', '김영진', '서울특별시 강동구 고덕로 210 ,507동 102호(명일동, 삼익그린맨션) (명일제1동)', '02', '3426', '7755', 2)
2021-08-18 17:41:06,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,263 INFO sqlalchemy.engine.base.Engine ('구립자양2동어린이집', '윤민재', '서울특별시 광진구 자양로3가길 26 ,(자양동) (자양제2동)', '02', '453', '7587', 6)
2021-08-18 17:41:06,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,267 INFO sqlalchemy.engine.base.Engine ('한일어린이집', '윤영일', '서울특별시 동대문구 외대역동로 118 ,(이문동) (이문제1동)', '02', '969', '2558', 11)
2021-08-18 17:41:06,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,270 INFO sqlalchemy.engine.base.Engine ('남현어린이집', '정성진', '서울특별시 관악구 남현1가길 18-4 ,남현동] (남현동) (남현동)', '02', '584', '2855', 5)
2021-08-18 17:41:06,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,272 INFO sqlalchemy.engine.base.Engine ('팝콘어린이집', '강현정', '서울특별시 중랑구 숙선옹주로 91 ,405동 103호(묵동, 신내아파트) (묵제1동)', '02', '3422', '1441', 25)
2021-08-18 17:41:06,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,274 INFO sqlalchemy.engine.base.Engine ('물샘어린이집', '윤지영', '서울특별시 은평구 갈현로29길 5-14 (갈현제2동)', '02', '353', '1781', 22)
2021-08-18 17:41:06,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,277 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '황예준', '서울특별시 노원구 동일로 1280 ,202동 104호(중계동, 중계무지개아파트) (중계2.3동)', '070', '7785', '2654', 9)
2021-08-18 17:41:06,278 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,279 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '한광수', '서울특별시 마포구 성미산로2길 23 ,두영빌라 101호 (서교동) (서교동)', '02', '326', '2684', 13)
2021-08-18 17:41:06,281 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,282 INFO sqlalchemy.engine.base.Engine ('구립서초사랑어린이집', '황성수', '서울특별시 서초구 잠원로 213-3 (잠원동)', '02', '3478', '2334', 15)
2021-08-18 17:41:06,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,286 INFO sqlalchemy.engine.base.Engine ('옥스포드어린이집', '오준영', '서울특별시 용산구 청파동3가 원효로97길 32 (청파동)', '02', '703', '8258', 21)
2021-08-18 17:41:06,287 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,291 INFO sqlalchemy.engine.base.Engine ('샘소슬 어린이집', '전영환', '서울특별시 구로구 부일로17길 5 ,(사실상1~3 층) (궁동) (수궁동)', '02', '2688', '2936', 7)
2021-08-18 17:41:06,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,293 INFO sqlalchemy.engine.base.Engine ('사랑몬테소리어린이집', '황성수', '서울특별시 구로구 개봉로20길 6 ,103동 101호(개봉동, 현대아파트) (개봉제2동)', '070', '4028', '8246', 7)
2021-08-18 17:41:06,294 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,296 INFO sqlalchemy.engine.base.Engine ('햇님데이케어어린이집', '신예준', '서울특별시 관악구 성현로 80 ,110동 104호(봉천동, 관악드림타운) [성현동] (성현동)', '02', '886', '6985', 5)
2021-08-18 17:41:06,298 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,299 INFO sqlalchemy.engine.base.Engine ('둔촌아이사랑어린이집', '신진호', '서울특별시 강동구 진황도로61길 7 ,102동 101호(둔촌동, 둔촌동현대아파트) (둔촌제2동)', '02', '485', '5463', 2)

2021-08-18 17:41:06,300 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,301 INFO sqlalchemy.engine.base.Engine ('은평제일어린이집', '오정수', '서울특별시 은평구 백련산로 165 ,(응암동) (응암제1동)', '02', '389', '9492', 22)
2021-08-18 17:41:06,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,303 INFO sqlalchemy.engine.base.Engine ('구의미소어린이집', '박준서', '서울특별시 광진구 자양로 297 ,(구의2동) (구의제2동)', '02', '456', '7336', 6)
2021-08-18 17:41:06,304 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,305 INFO sqlalchemy.engine.base.Engine ('보라어린이집', '안유진', '서울특별시 관악구 난곡로24가길 6 ,(신림동) [난곡동] (난곡동)', '02', '859', '4548', 5)
2021-08-18 17:41:06,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,308 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '윤정호', '서울특별시 마포구 양화로11길 27-8 ,(서교동) (서교동)', '02', '3142', '6432', 13)
2021-08-18 17:41:06,309 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,310 INFO sqlalchemy.engine.base.Engine ('종교교회어린이집', '권정호', '서울특별시 종로구 사직로8길 48 ,종교교회내 1층 (도렴동) (사직동)', '02', '6322', '2190', 23)
2021-08-18 17:41:06,312 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,313 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '최지영', '서울특별시 노원구 우이천로 102 ,203동 109호(월계동, 초안아파트) (월계2동)', '02', '990', '5051', 9)
2021-08-18 17:41:06,314 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,315 INFO sqlalchemy.engine.base.Engine ('하나놀이방 어린이집', '류정수', '서울특별시 동작구 상도로47가길 16 (상도제1동)', '02', '824', '3730', 12)
2021-08-18 17:41:06,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,317 INFO sqlalchemy.engine.base.Engine ('다다어린이집', '서지혜', '서울특별시 노원구 공릉로34길 62 ,1001동 104호(공릉동, 태강) (공릉2동)', '02', '977', '1244', 9)
2021-08-18 17:41:06,318 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,319 INFO sqlalchemy.engine.base.Engine ('서울교통공사대공원어린이집', '이민지', '서울특별시 광진구 능동로 247-1 ,(군자동) (군자동)', '02', '6311', '7979', 6)
2021-08-18 17:41:06,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,321 INFO sqlalchemy.engine.base.Engine ('예나어린이집', '박서현', '서울특별시 동대문구 경동시장로23길 14 ,(제기동) (제기동)', '02', '967', '2229', 11)
2021-08-18 17:41:06,322 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,323 INFO sqlalchemy.engine.base.Engine ('꿈사랑어린이집', '한상훈', '서울특별시 서대문구 이화여대8길 62 ,서울특별시 서대문구 북아현동 두산아파트 단지내 (북아현동)', '02', '313', '3448', 14)
2021-08-18 17:41:06,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,324 INFO sqlalchemy.engine.base.Engine ('꿈나무가정어린이집', '송지원', '서울특별시 관악구 성현로 80 ,143동 101호(봉천동, 관악드림타운) [성현동] (성현동)', '02', '888', '8279', 5)
2021-08-18 17:41:06,326 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,327 INFO sqlalchemy.engine.base.Engine ('소망어린이집', '안진호', '서울특별시 금천구 범안로 1187 ,(독산동) (독산제1동)', '02', '895', '6942', 8)
2021-08-18 17:41:06,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,329 INFO sqlalchemy.engine.base.Engine ('롯데어린이집', '권동현', '서울특별시 구로구 새말로 31 ,롯데아파트 관리동1층 (구로제5동)', '02', '838', '8456', 7)
2021-08-18 17:41:06,331 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,332 INFO sqlalchemy.engine.base.Engine ('연세어린이집', '장정자', '서울특별시 금천구 독산로65길 14 ,(독산동) (독산제2동)', '02', '891', '7509', 8)
2021-08-18 17:41:06,334 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,336 INFO sqlalchemy.engine.base.Engine ('스타터즈어린이집', '이동현', '서울특별시 용산구 이촌로 174 ,동부센트레빌 105 (이촌제1동)', '02', '749', '8247', 21)
2021-08-18 17:41:06,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,339 INFO sqlalchemy.engine.base.Engine ('횃불자연어린이집', '권준서', '서울특별시 양천구 오목로52길 12 ,(목동) (목1동)', '02', '2652', '6640', 19)
2021-08-18 17:41:06,341 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,342 INFO sqlalchemy.engine.base.Engine ('새소망 어린이집', '최미영', '서울특별시 성북구 화랑로48길 16 ,102동 102호(석관동, 두산아파트) (석관동)', '02', '964', '2673', 17)
2021-08-18 17:41:06,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,344 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '강건우', '서울특별시 광진구 뚝섬로57길 48 ,101호(극동하이빌) (자양제1동)', '02', '457', '5529', 6)
2021-08-18 17:41:06,346 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,347 INFO sqlalchemy.engine.base.Engine ('크레용어린이집', '신서현', '서울특별시 관악구 법원단지5가길 21 ,1,2층 (신림동) [미성동] (미성동)', '02', '3281', '0550', 5)
2021-08-18 17:41:06,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,349 INFO sqlalchemy.engine.base.Engine ('혜지어린이집', '권민지', '서울특별시 관악구 성현로 80 ,120동 101호(봉천동, 관악드림타운) [성현동] (성현동)', '02', '885', '6832', 5)
2021-08-18 17:41:06,350 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,351 INFO sqlalchemy.engine.base.Engine ('물댄동산어린이집', '오상철', '서울특별시 강북구 삼각산로 143-1 ,12동 110호(수유동, 수유벽산) (수유2동)', '02', '902', '7970', 3)
2021-08-18 17:41:06,352 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,353 INFO sqlalchemy.engine.base.Engine ('열린방과후어린이집', '강서현', '서울특별시 동대문구 전농로16길 59 ,열린방과후교실 (전농제2동)', '02', '2248', '0421', 11)
2021-08-18 17:41:06,354 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,355 INFO sqlalchemy.engine.base.Engine ('사랑아이방과후어린이집', '최서연', '서울특별시 동대문구 약령시로5길 22 ,(제기동) (제기동)', '02', '920', '4541', 11)
2021-08-18 17:41:06,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,357 INFO sqlalchemy.engine.base.Engine ('아이뜰어린이집', '강민석', '서울특별시 강남구 개포로22길 39-11 (개포제4동)', '02', '577', '8210', 1)

2021-08-18 17:41:06,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,360 INFO sqlalchemy.engine.base.Engine ('사군자어린이집', '신서연', '서울특별시 동대문구 장한로5길 45 ,(장안동) (장안제1동)', '02', '2246', '5801', 11)
2021-08-18 17:41:06,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,362 INFO sqlalchemy.engine.base.Engine ('늘푸른아이들어린이집', '조예은', '서울특별시 서초구 신반포로15길 4 ,101동 101호(반포동, 반포대우아파트) (반포2동)', '02', '3482', '2310', 15)
2021-08-18 17:41:06,364 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,365 INFO sqlalchemy.engine.base.Engine ('예사랑어린이집', '서경자', '서울특별시 노원구 마들로 31 ,114동 106호(월계동, 한진한화그랑빌) (월계3동)', '02', '949', '8772', 9)
2021-08-18 17:41:06,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,369 INFO sqlalchemy.engine.base.Engine ('석란어린이집', '장지훈', '서울특별시 강서구 초록마을로32길 38 ,(화곡동) (화곡제8동)', '02', '2604', '0735', 4)
2021-08-18 17:41:06,371 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,373 INFO sqlalchemy.engine.base.Engine ('예쁜아이어린이집', '황미경', '서울특별시 노원구 동일로215길 48 ,320동 102호(상계동, 상계주공3단지아파트) (상계6.7동)', '02', '6435', '5959', 9)
2021-08-18 17:41:06,373 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,374 INFO sqlalchemy.engine.base.Engine ('꼬마별어린이집', '전준서', '서울특별시 광진구 천호대로127길 33 ,103호(중곡동, 선화빌라11차) (중곡제4동)', '02', '456', '3149', 6)
2021-08-18 17:41:06,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,376 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '송정식', '서울특별시 성동구 무학로 50 ,103동 101호(하왕십리동, 청계벽산아파트) (왕십리도선동)', '02', '2296', '4697', 16)
2021-08-18 17:41:06,377 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,378 INFO sqlalchemy.engine.base.Engine ('소슬어린이집', '박준호', '서울특별시 관악구 성현로 80 ,성현동] (봉천동) (성현동)', '02', '6671', '6002', 5)
2021-08-18 17:41:06,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,380 INFO sqlalchemy.engine.base.Engine ('배화어린이집', '전준혁', '서울특별시 서대문구 경기대로 82 ,광산빌딩 1층 배화어린이집 (충정로2가) (충현동)', '02', '312', '2100', 14)
2021-08-18 17:41:06,381 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,382 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '서순자', '서울특별시 강서구 허준로 23 ,101동 104호(가양동, 한강타운) (가양제1동)', '02', '2668', '3808', 4)
2021-08-18 17:41:06,383 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,384 INFO sqlalchemy.engine.base.Engine ('성신어린이집', '류순자', '서울특별시 성북구 동소문동7가 아리랑로5길 36 ,(동소문동7가) (동선동)', '02', '923', '5756', 17)
2021-08-18 17:41:06,385 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,386 INFO sqlalchemy.engine.base.Engine ('파크빌어린이집', '박경숙', '서울특별시 광진구 아차산로 549 ,현대파크빌단지내(광장동) (광장동)', '02', '456', '5677', 6)
2021-08-18 17:41:06,387 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,388 INFO sqlalchemy.engine.base.Engine ('삼창어린이집', '김서현', '서울특별시 노원구 광운로2가길 23 ,(월계1동 삼창상가 2층) (월계1동)', '02', '911', '3474', 9)
2021-08-18 17:41:06,389 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,390 INFO sqlalchemy.engine.base.Engine ('키즈모아어린이집', '강정순', '서울특별시 광진구 뚝섬로 698 ,(자양동) (자양제2동)', '02', '427', '2869', 6)
2021-08-18 17:41:06,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,392 INFO sqlalchemy.engine.base.Engine ('새봄어린이집', '전민서', '서울특별시 강북구 한천로150길 35-3 (수유3동)', '02', '900', '8856', 3)
2021-08-18 17:41:06,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,394 INFO sqlalchemy.engine.base.Engine ('프라임어린이집', '안지은', '서울특별시 노원구 마들로 127 ,35동 102호(월계동, 삼호) (월계3동)', '02', '6225', '5050', 9)
2021-08-18 17:41:06,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,396 INFO sqlalchemy.engine.base.Engine ('나무바다어린이집', '조정호', '서울특별시 관악구 은천로 86 ,207동 102호(봉천동, 두산아파트) [은천동] (은천동)', '02', '6105', '5282', 5)
2021-08-18 17:41:06,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,397 INFO sqlalchemy.engine.base.Engine ('혜빛어린이집', '김정호', '서울특별시 동대문구 사가정로9길 18-1 ,(전농동) (전농제1동)', '02', '2248', '9787', 11)
2021-08-18 17:41:06,401 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,403 INFO sqlalchemy.engine.base.Engine ('깨모어린이집', '김미영', '서울특별시 양천구 신정로13길 50 ,101동 106호(신월동, 벽산블루밍1단지) (신월6동)', '02', '2607', '1737', 19)
2021-08-18 17:41:06,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,406 INFO sqlalchemy.engine.base.Engine ('강남사임당어린이집', '안정호', '서울특별시 강남구 언주로 420 ,역삼자이아파트 관리동 (역삼제2동)', '02', '556', '1680', 1)
2021-08-18 17:41:06,407 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,408 INFO sqlalchemy.engine.base.Engine ('로뎀어린이집', '안미경', '서울특별시 강서구 양천로24길 31 ,로뎀어린이집 (방화동) (방화제1동)', '02', '2664', '7060', 4)
2021-08-18 17:41:06,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,410 INFO sqlalchemy.engine.base.Engine ('사랑채움어린이집', '한지민', '서울특별시 영등포구 선유로 207 ,601동 102호(양평동3가, 현대6차아파트) (양평제2동)', '070', '8236', '5319', 20)
2021-08-18 17:41:06,411 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,411 INFO sqlalchemy.engine.base.Engine ('일원사임당어린이집', '강민재', '서울특별시 강남구 개포로 648 ,동형빌딩101호 (일원동) (일원제1동)', '02', '3411', '4333', 1)
2021-08-18 17:41:06,412 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,412 INFO sqlalchemy.engine.base.Engine ('노들어린이집', '윤민서', '서울특별시 동작구 만양로2길 76 ,현대씨티빌 102호 (상도동) (상도제1동)', '02', '816', '0107', 12)
2021-08-18 17:41:06,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,414 INFO sqlalchemy.engine.base.Engine ('엔젤어린이집', '한종수', '서울특별시 금천구 문성로1길 7 ,(독산동) (독산제3동)', '02', '866', '7723', 8)
2021-08-18 17:41:06,414 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,415 INFO sqlalchemy.engine.base.Engine ('예쁜둥지어린이집', '서병철', '서울특별시 중랑구 동일로152길 45-5 (묵제1동)', '02', '974', '3393', 25)
2021-08-18 17:41:06,416 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,416 INFO sqlalchemy.engine.base.Engine ('청구어린이집', '신정식', '서울특별시 노원구 동일로207길 186 ,(하계2동 학여울청구아파트 117동앞) (하계2동)', '02', '948', '2336', 9)
2021-08-18 17:41:06,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,418 INFO sqlalchemy.engine.base.Engine ('빛초롱어린이집', '윤종수', '서울특별시 동대문구 사가정로 168 ,SK아파트 제2관리소 단지동 (전농동) (전농제2동)', '02', '2244', '5550', 11)
2021-08-18 17:41:06,420 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,423 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '조정남', '서울특별시 동대문구 답십리로56길 21-1 ,두산아파트단지내 조은어린이집 (답십리제2동)', '02', '2244', '4220', 11)
2021-08-18 17:41:06,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,425 INFO sqlalchemy.engine.base.Engine ('아이조아어린이집', '조민지', '서울특별시 노원구 동일로245가길 41 ,203동 103호(상계동, 은빛2단지아파트) (상계1동)', '02', '952', '0009', 9)
2021-08-18 17:41:06,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,427 INFO sqlalchemy.engine.base.Engine ('솜송이어린이집', '조종수', '서울특별시 동대문구 이문로16길 37 ,(이문동) (이문제1동)', '02', '967', '1971', 11)
2021-08-18 17:41:06,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,429 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '송예은', '서울특별시 중구 다산로 32 ,남산타운 단지내 한솔어린이집 (약수동)', '02', '2256', '0330', 24)
2021-08-18 17:41:06,431 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,431 INFO sqlalchemy.engine.base.Engine ('동대문구청직장어린이집', '안정자', '서울특별시 동대문구 고산자로28길 13 ,(용두동) (용신동)', '02', '6929', '2601', 11)
2021-08-18 17:41:06,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,433 INFO sqlalchemy.engine.base.Engine ('솔로몬소망어린이집', '안순자', '서울특별시 강북구 삼양로 324 ,(수유동) (수유1동)', '02', '988', '9485', 3)
2021-08-18 17:41:06,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,437 INFO sqlalchemy.engine.base.Engine ('세브란스어린이집', '류예준', '서울특별시 서대문구 연대동문길 41 ,세브란스 어린이집 (신촌동)', '02', '312', '7990', 14)
2021-08-18 17:41:06,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,439 INFO sqlalchemy.engine.base.Engine ('선우어린이집', '류미영', '서울특별시 서초구 방배로15길 26 ,1층 (방배동) (방배1동)', '02', '584', '4295', 15)
2021-08-18 17:41:06,440 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,441 INFO sqlalchemy.engine.base.Engine ('순복음어린이집', '황미숙', '서울특별시 노원구 노원로 440 ,순복음노원교회 본관 (상계동) (상계2동)', '02', '3391', '6112', 9)
2021-08-18 17:41:06,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,443 INFO sqlalchemy.engine.base.Engine ('수표교어린이집', '권경숙', '서울특별시 서초구 명달로 52 ,(서초동) (서초3동)', '02', '597', '7172', 15)
2021-08-18 17:41:06,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,446 INFO sqlalchemy.engine.base.Engine ('무지개유아스쿨어린이집', '권병철', '서울특별시 강북구 숭인로7길 28 ,(미아동) (송천동)', '02', '987', '5471', 3)
2021-08-18 17:41:06,448 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,449 INFO sqlalchemy.engine.base.Engine ('한진또래어린이집', '송은영', '서울특별시 구로구 개봉로1나길 58 ,(개봉동) (개봉제3동)', '02', '2686', '3997', 7)
2021-08-18 17:41:06,451 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,452 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '안민지', '서울특별시 구로구 새말로 93 ,111동 102호(구로동, 신도림태영타운아파트) (구로제5동)', '02', '868', '9723', 7)
2021-08-18 17:41:06,454 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,455 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '이영철', '서울특별시 양천구 곰달래로10길 15-4 (신월1동)', '02', '2065', '6568', 19)
2021-08-18 17:41:06,456 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,457 INFO sqlalchemy.engine.base.Engine ('파미유어린이집', '윤서현', '서울특별시 도봉구 시루봉로27가길 11-3 (도봉제1동)', '02', '3491', '2541', 10)
2021-08-18 17:41:06,458 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,459 INFO sqlalchemy.engine.base.Engine ('햇살가득어린이집', '정미경', '서울특별시 구로구 신도림로 78 ,302동 102호(신도림동, 신도림3차동아아파트) (신도림동)', '02', '2671', '9396', 7)
2021-08-18 17:41:06,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,461 INFO sqlalchemy.engine.base.Engine ('섬기는어린이집', '임정수', '서울특별시 구로구 우마1다길 25 ,구립 섬기는 어린이집 (가리봉동)', '02', '865', '9111', 7)
2021-08-18 17:41:06,462 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,463 INFO sqlalchemy.engine.base.Engine ('어린이나라어린이집', '정지민', '서울특별시 광진구 자양로26길 9 ,(구의동) (구의제1동)', '02', '446', '3232', 6)
2021-08-18 17:41:06,464 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,465 INFO sqlalchemy.engine.base.Engine ('솔이어린이집', '장진호', '서울특별시 송파구 양산로2길 44 ,거여아파트3단지내 (거여2동)', '02', '400', '6753', 18)
2021-08-18 17:41:06,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,467 INFO sqlalchemy.engine.base.Engine ('한마음어린이집', '권혜진', '서울특별시 서대문구 가좌로 100-8 (홍은제2동)', '02', '374', '1700', 14)
2021-08-18 17:41:06,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,469 INFO sqlalchemy.engine.base.Engine ('새자연어린이집', '신예은', '서울특별시 강서구 방화대로47가길 22 ,삼익아파트 내 유치원동 (방화동) (방화제3동)', '02', '2666', '6467', 4)
2021-08-18 17:41:06,470 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,471 INFO sqlalchemy.engine.base.Engine ('꿈쟁이어린이집', '이성민', '서울특별시 동대문구 한천로58길 47 ,102동 102호(이문동, 쌍용아파트) (이문제2동)', '02', '964', '8213', 11)
2021-08-18 17:41:06,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,473 INFO sqlalchemy.engine.base.Engine ('청아어린이집', '조준혁', '서울특별시 성북구 보국문로30길 15 ,대우아파트 102동 103, 104호 (정릉동) (정릉제4동)', '02', '919', '5752', 17)
2021-08-18 17:41:06,474 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,475 INFO sqlalchemy.engine.base.Engine ('대림어린이집', '이진호', '서울특별시 노원구 상계로 193-14 ,(상계3.4동 상계대림아파트 관리동 1층) (상계3.4동)', '02', '932', '6363', 9)
2021-08-18 17:41:06,476 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,477 INFO sqlalchemy.engine.base.Engine ('몬테소리동화나라어린이집', '오진호', '서울특별시 강서구 방화대로 319 ,101동 102호(방화동, 길성아파트) (방화제1동)', '02', '2661', '6335', 4)
2021-08-18 17:41:06,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,478 INFO sqlalchemy.engine.base.Engine ('키큰어린이집', '한정남', '서울특별시 은평구 통일로 796 ,북한산힐스테이트7차아파트 106동 102호(불광동) (불광제1동)', '02', '383', '9907', 22)
2021-08-18 17:41:06,481 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,481 INFO sqlalchemy.engine.base.Engine ('디즈니프리스쿨어린이집', '전준서', '서울특별시 중랑구 신내로19길 42 ,608동 106호(신내동, 신내대주아파트) (신내2동)', '02', '3421', '9647', 25)
2021-08-18 17:41:06,483 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,483 INFO sqlalchemy.engine.base.Engine ('아이나라어린이집', '서지영', '서울특별시 구로구 새말로 93 ,107동 105호(구로동, 신도림태영타운아파트) (구로제5동)', '070', '8839', '9985', 7)
2021-08-18 17:41:06,484 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,485 INFO sqlalchemy.engine.base.Engine ('동광어린이집', '한정수', '서울특별시 노원구 덕릉로 623-1 (중계1동)', '02', '935', '8268', 9)
2021-08-18 17:41:06,486 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,487 INFO sqlalchemy.engine.base.Engine ('반석어린이집', '권지혜', '서울특별시 용산구 효창원로 178 ,(청파동3가) (청파동)', '02', '719', '9271', 21)
2021-08-18 17:41:06,489 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,490 INFO sqlalchemy.engine.base.Engine ('예니어린이집', '황준영', '서울특별시 광진구 아차산로63길 27 ,(구의동) (구의제3동)', '02', '456', '4365', 6)
2021-08-18 17:41:06,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,492 INFO sqlalchemy.engine.base.Engine ('구립 산들어린이집', '이서연', '서울특별시 양천구 신정중앙로2길 10-13 ,() (신정4동)', '02', '2690', '1393', 19)
2021-08-18 17:41:06,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,495 INFO sqlalchemy.engine.base.Engine ('한터어린이집', '정예은', '서울특별시 중랑구 면목로56가길 21 ,(면목동) (면목본동)', '02', '437', '2672', 25)
2021-08-18 17:41:06,496 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,496 INFO sqlalchemy.engine.base.Engine ('꿈동이어린이집', '윤지영', '서울특별시 양천구 신정로 260 ,401동 101호(신정동, 신트리아파트) (신정3동)', '02', '2692', '6604', 19)
2021-08-18 17:41:06,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,498 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '이종수', '서울특별시 중랑구 면목로65길 13 ,(면목동) (면목본동)', '02', '2207', '7727', 25)
2021-08-18 17:41:06,499 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,499 INFO sqlalchemy.engine.base.Engine ('행복한 아이들 어린이집', '서준영', '서울특별시 강서구 까치산로 145 ,(화곡동) (화곡제6동)', '02', '2692', '6561', 4)
2021-08-18 17:41:06,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,501 INFO sqlalchemy.engine.base.Engine ('우리아이어린이집', '박도현', '서울특별시 노원구 마들로3길 37 ,402동 109호(월계동, 성원아파트) (월계3동)', '02', '976', '3142', 9)
2021-08-18 17:41:06,502 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,502 INFO sqlalchemy.engine.base.Engine ('월계아장아장어린이집', '조도현', '서울특별시 노원구 광운로2나길 30 ,1동 107호(월계동, 동신아파트) (월계1동)', '02', '917', '9711', 9)
2021-08-18 17:41:06,503 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,504 INFO sqlalchemy.engine.base.Engine ('유마어린이집', '류성수', '서울특별시 동대문구 제기로31길 10-3 ,(청량사내) (청량리동) (청량리동)', '02', '965', '4121', 11)
2021-08-18 17:41:06,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,505 INFO sqlalchemy.engine.base.Engine ('꿈동산 어린이집', '정광수', '서울특별시 동작구 양녕로22가길 39 ,(상도동) (상도제4동)', '02', '824', '8115', 12)
2021-08-18 17:41:06,506 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,506 INFO sqlalchemy.engine.base.Engine ('꿈밭어린이집', '권경자', '서울특별시 용산구 이촌로81길 34 ,꿈밭어린이집 (이촌제1동)', '02', '792', '8645', 21)
2021-08-18 17:41:06,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,508 INFO sqlalchemy.engine.base.Engine ('소담어린이집', '강민지', '서울특별시 강서구 월정로32길 31 ,(화곡동) (화곡제1동)', '02', '2694', '1030', 4)
2021-08-18 17:41:06,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,509 INFO sqlalchemy.engine.base.Engine ('아이짐어린이집', '류혜진', '서울특별시 광진구 광나루로37길 8 ,(구의2동) (구의제2동)', '02', '455', '5220', 6)
2021-08-18 17:41:06,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,511 INFO sqlalchemy.engine.base.Engine ('으뜸어린이집', '류정순', '서울특별시 광진구 능동로4길 88 ,(자양동) (자양제3동)', '02', '458', '3372', 6)
2021-08-18 17:41:06,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,514 INFO sqlalchemy.engine.base.Engine ('프란치스코어린이집', '장영길', '서울특별시 강서구 송정로1길 13 ,프란치스코어린이집 (공항동)', '02', '2665', '7050', 4)
2021-08-18 17:41:06,515 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,516 INFO sqlalchemy.engine.base.Engine ('효성어린이집', '신성수', '서울특별시 영등포구 당산로42길 13 ,효성아파트 1차 관리동1층 (당산동5가) (당산제2동)', '02', '2069', '1770', 20)
2021-08-18 17:41:06,517 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,518 INFO sqlalchemy.engine.base.Engine ('광진선교어린이집', '이도현', '서울특별시 구로구 개봉로3길 87 ,한진아파트 내유치원동 (개봉동) (개봉제3동)', '02', '2625', '0764', 7)
2021-08-18 17:41:06,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,519 INFO sqlalchemy.engine.base.Engine ('해담솔 어린이집', '오민지', '서울특별시 성동구 금호로 100 ,106동 104호(금호동1가, 벽산아파트) (금호1가동)', '02', '2293', '8431', 16)
2021-08-18 17:41:06,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,521 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '전정순', '서울특별시 동대문구 고산자로 534 ,제기한신아파트 단지동 (제기동) (제기동)', '02', '964', '1442', 11)
2021-08-18 17:41:06,522 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,523 INFO sqlalchemy.engine.base.Engine ('예능어린이집', '전종수', '서울특별시 구로구 신도림로 87 ,신도림1차동아 1층 (신도림동)', '02', '2675', '8788', 7)
2021-08-18 17:41:06,524 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,525 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '강지영', '서울특별시 양천구 목동동로 100 ,1333동 106호(신정동, 신시가지13단지아파트) (신정6동)', '02', '2653', '8301', 19)
2021-08-18 17:41:06,526 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,527 INFO sqlalchemy.engine.base.Engine ('미광어린이집', '안건우', '서울특별시 노원구 공릉로34길 62 ,태강아파트 관리사무소2층 (공릉2동)', '02', '948', '3353', 9)
2021-08-18 17:41:06,529 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,529 INFO sqlalchemy.engine.base.Engine ('초원어린이집', '권미영', '서울특별시 송파구 백제고분로19길 12-14 ,남강로얄맨션 101호 (잠실본동)', '02', '421', '8365', 18)
2021-08-18 17:41:06,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,531 INFO sqlalchemy.engine.base.Engine ('색동어린이집', '황종수', '서울특별시 중랑구 동일로109길 31 ,(면목동) (면목제2동)', '02', '493', '8030', 25)
2021-08-18 17:41:06,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,532 INFO sqlalchemy.engine.base.Engine ('고려서머힐어린이집', '이지민', '서울특별시 송파구 동남로18길 44 ,프라자아파트 관리동1층 고려서머힐어린이집 (가락2동)', '02', '400', '1137', 18)
2021-08-18 17:41:06,533 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,534 INFO sqlalchemy.engine.base.Engine ('꿈땅어린이집', '송정운', '서울특별시 강남구 도곡로73길 11 ,라이트빌 1층 (대치4동)', '02', '553', '6447', 1)
2021-08-18 17:41:06,535 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,537 INFO sqlalchemy.engine.base.Engine ('뽀로롱어린이집', '황지훈', '서울특별시 강동구 상암로 11 ,108동 104호(암사동, 선사현대아파트) (암사제2동)', '070', '4388', '8669', 2)
2021-08-18 17:41:06,541 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,542 INFO sqlalchemy.engine.base.Engine ('한국성서대학교어린이집', '황영숙', '서울특별시 노원구 동일로214길 32 ,한국성서대학교어린이집 (상계6.7동)', '02', '950', '5498', 9)
2021-08-18 17:41:06,543 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,544 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '신지은', '서울특별시 동대문구 약령시로5길 22 ,(제기동) (제기동)', '02', '929', '0081', 11)
2021-08-18 17:41:06,545 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,546 INFO sqlalchemy.engine.base.Engine ('현대키즈어린이집', '전예은', '서울특별시 마포구 신수로 15 ,110동 102호(현석동, 현대홈타운) (신수동)', '02', '6383', '9691', 13)
2021-08-18 17:41:06,548 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,549 INFO sqlalchemy.engine.base.Engine ('신성어린이집', '조정남', '서울특별시 강서구 양천로28길 18 ,(방화동) (방화제1동)', '02', '2661', '1800', 4)
2021-08-18 17:41:06,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,551 INFO sqlalchemy.engine.base.Engine ('빛나래어린이집', '박민석', '서울특별시 노원구 월계로45가길 94 ,401동 107호(월계동, 청백) (월계2동)', '02', '999', '8584', 9)
2021-08-18 17:41:06,553 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,554 INFO sqlalchemy.engine.base.Engine ('구립 해바라기어린이집', '전성진', '서울특별시 양천구 목동동로1길 33 (신정1동)', '02', '2647', '6784', 19)
2021-08-18 17:41:06,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,556 INFO sqlalchemy.engine.base.Engine ('구립로야어린이집', '박민서', '서울특별시 동작구 상도로62길 87 ,(상도동) (상도제1동)', '02', '822', '2246', 12)
2021-08-18 17:41:06,558 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,558 INFO sqlalchemy.engine.base.Engine ('사랑꼬마숲어린이집', '최서현', '서울특별시 용산구 우사단로2가길 42-5 (보광동)', '02', '798', '1620', 21)
2021-08-18 17:41:06,560 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,561 INFO sqlalchemy.engine.base.Engine ('우방어린이집', '임상철', '서울특별시 은평구 증산로3길 26-1 ,101동 103호(증산동, 우방아파트) (증산동)', '02', '376', '3035', 22)
2021-08-18 17:41:06,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,563 INFO sqlalchemy.engine.base.Engine ('전농방과후어린이집', '송은영', '서울특별시 동대문구 서울시립대로12길 99 ,(전농동)355-1 (전농제1동)', '02', '2215', '8514', 11)
2021-08-18 17:41:06,564 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,565 INFO sqlalchemy.engine.base.Engine ('서대문종합사회복지관방과후교실어린이집', '이미숙', '서울특별시 서대문구 모래내로 177 ,(남가좌동) (남가좌제1동)', '02', '375', '5040', 14)
2021-08-18 17:41:06,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,566 INFO sqlalchemy.engine.base.Engine ('키움어린이집', '한영환', '서울특별시 중랑구 공릉로2라길 4 ,104동 101호(묵동, 묵동신안아파트) (묵제1동)', '02', '910', '8888', 25)
2021-08-18 17:41:06,568 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,569 INFO sqlalchemy.engine.base.Engine ('서울베다니어린이집', '오준서', '서울특별시 양천구 남부순환로65길 16-1 (신월1동)', '02', '2605', '9237', 19)
2021-08-18 17:41:06,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,571 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '황병철', '서울특별시 노원구 섬밭로 196 ,605동 102호(하계동, 장미) (하계2동)', '02', '979', '1715', 9)
2021-08-18 17:41:06,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,573 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '정지원', '서울특별시 노원구 공릉로34길 62 ,1015동 104호(공릉동, 태강) (공릉2동)', '02', '949', '0353', 9)
2021-08-18 17:41:06,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,575 INFO sqlalchemy.engine.base.Engine ('참사랑어린이집', '강현정', '서울특별시 중랑구 면목로74길 27 ,1층 (면목동) (면목본동)', '02', '496', '1412', 25)
2021-08-18 17:41:06,575 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,576 INFO sqlalchemy.engine.base.Engine ('바다의 별어린이집', '조정호', '서울특별시 성북구 정릉로10라길 31 ,(정릉동) (정릉제3동)', '02', '941', '8918', 17)
2021-08-18 17:41:06,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,578 INFO sqlalchemy.engine.base.Engine ('강남새 어린이집', '윤준서', '서울특별시 영등포구 당산로42길 16 ,현대5차아파트 단지내 (당산동4가) (당산제2동)', '02', '2676', '9637', 20)
2021-08-18 17:41:06,578 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,579 INFO sqlalchemy.engine.base.Engine ('또래가정어린이집', '황상훈', '서울특별시 관악구 관악로30길 12 ,105동 113호 (봉천동,우성아파트) [행운동] (행운동)', '02', '876', '1315', 5)
2021-08-18 17:41:06,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,580 INFO sqlalchemy.engine.base.Engine ('아이원어린이집', '강준혁', '서울특별시 구로구 고척로52길 104-5 (개봉제1동)', '02', '2685', '6750', 7)
2021-08-18 17:41:06,581 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,582 INFO sqlalchemy.engine.base.Engine ('요정나라어린이집', '안경회', '서울특별시 구로구 경인로 643 ,202동 104호(신도림동, 동아2차아파트) (신도림동)', '02', '2678', '1248', 7)
2021-08-18 17:41:06,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,585 INFO sqlalchemy.engine.base.Engine ('동산 어린이집', '박혜진', '서울특별시 성동구 서울숲2길 37 ,(성수동1가) (성수1가제2동)', '02', '465', '7738', 16)
2021-08-18 17:41:06,586 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,587 INFO sqlalchemy.engine.base.Engine ('꿈동산어린이집', '장영철', '서울특별시 동대문구 사가정로 148 ,103동 103호(전농동, SK아파트) (전농제2동)', '02', '2243', '3016', 11)
2021-08-18 17:41:06,589 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,590 INFO sqlalchemy.engine.base.Engine ('상계그림나라어린이집', '안영진', '서울특별시 노원구 노해로 508 ,620동 101호(상계동, 상계주공6차) (상계6.7동)', '02', '952', '9975', 9)
2021-08-18 17:41:06,591 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,592 INFO sqlalchemy.engine.base.Engine ('영산어린이집', '김은영', '서울특별시 은평구 불광로3길 6 ,(불광동) (불광제1동)', '02', '359', '6385', 22)
2021-08-18 17:41:06,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,594 INFO sqlalchemy.engine.base.Engine ('우이동교회부설방과후어린이집', '오정순', '서울특별시 도봉구 삼양로 574-48 (쌍문제1동)', '02', '902', '8393', 10)
2021-08-18 17:41:06,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,596 INFO sqlalchemy.engine.base.Engine ('소명어린이집', '오도현', '서울특별시 노원구 덕릉로94길 21 ,(상계3.4동 불암대림아파트 단지내) (상계3.4동)', '02', '934', '7077', 9)
2021-08-18 17:41:06,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,598 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '서미숙', '서울특별시 구로구 고척로18길 9 ,(개봉동) (개봉제1동)', '02', '2682', '2730', 7)
2021-08-18 17:41:06,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,600 INFO sqlalchemy.engine.base.Engine ('한사랑어린이집', '장정웅', '서울특별시 양천구 목동중앙본로22길 63 ,건영아파트 상가203,204,205호 (목동) (목2동)', '02', '2644', '2434', 19)
2021-08-18 17:41:06,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,602 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '임정수', '서울특별시 강북구 한천로109길 57-15 (번3동)', '02', '981', '4376', 3)
2021-08-18 17:41:06,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,605 INFO sqlalchemy.engine.base.Engine ('비선삐아제어린이집', '강은경', '서울특별시 노원구 화랑로51길 78 ,505동 103호(공릉동, 비선아파트) (공릉2동)', '02', '971', '8970', 9)
2021-08-18 17:41:06,606 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,607 INFO sqlalchemy.engine.base.Engine ('혜원어린이집', '권영자', '서울특별시 중랑구 상봉로16가길 14 ,(망우동) (망우제3동)', '02', '433', '4845', 25)
2021-08-18 17:41:06,608 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,609 INFO sqlalchemy.engine.base.Engine ('모모어린이집', '이민석', '서울특별시 중랑구 송림길 16 ,훼밀리상가 (신내1동)', '02', '491', '6141', 25)
2021-08-18 17:41:06,610 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,611 INFO sqlalchemy.engine.base.Engine ('동아어린이집', '임지훈', '서울특별시 서초구 신반포로33길 15 ,103동 103호(잠원동, 동아아파트) (반포3동)', '02', '537', '7929', 15)
2021-08-18 17:41:06,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,613 INFO sqlalchemy.engine.base.Engine ('광진어린이집', '장지영', '서울특별시 구로구 고척로30길 18 ,(개봉동) (개봉제1동)', '02', '2611', '6229', 7)
2021-08-18 17:41:06,614 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,614 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '강영철', '서울특별시 송파구 삼전로4길 4 (삼전동)', '02', '422', '9376', 18)
2021-08-18 17:41:06,616 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,617 INFO sqlalchemy.engine.base.Engine ('동아어린이집', '권도현', '서울특별시 관악구 관악로37길 20 ,동아 아파트 B상가 2층 (성현동)', '02', '888', '0306', 5)
2021-08-18 17:41:06,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,620 INFO sqlalchemy.engine.base.Engine ('옥수종합사회복지관 부설 좋은벗방과후교실어린이집', '권정수', '서울특별시 성동구 한림말길 16-5 ,옥수종합사회복지관 (옥수동) (옥수동)', '02', '2282', '1100', 16)
2021-08-18 17:41:06,622 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,623 INFO sqlalchemy.engine.base.Engine ('해솔예술어린이집', '조서현', '서울특별시 금천구 시흥대로90길 63 (독산제2동)', '02', '3286', '9001', 8)
2021-08-18 17:41:06,624 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,625 INFO sqlalchemy.engine.base.Engine ('나나어린이집', '정준혁', '서울특별시 강북구 수유로4길 23 ,(수유동) (수유1동)', '02', '985', '0705', 3)
2021-08-18 17:41:06,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,628 INFO sqlalchemy.engine.base.Engine ('노랑어린이집', '박정남', '서울특별시 강북구 도봉로98길 33 ,(번동) (번1동)', '02', '997', '7588', 3)
2021-08-18 17:41:06,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,629 INFO sqlalchemy.engine.base.Engine ('신도림제일어린이집', '황영일', '서울특별시 구로구 신도림로13길 18 ,19-6 (신도림동)', '02', '2672', '5074', 7)
2021-08-18 17:41:06,630 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,631 INFO sqlalchemy.engine.base.Engine ('육영어린이집', '임민지', '서울특별시 관악구 문성로16가길 42-3 ,(신림동) [미성동] (미성동)', '02', '858', '7797', 5)
2021-08-18 17:41:06,633 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,634 INFO sqlalchemy.engine.base.Engine ('혜지어린이집', '전순자', '서울특별시 구로구 구로중앙로8길 16 ,2층, 구로동 (구로제4동)', '02', '864', '7427', 7)
2021-08-18 17:41:06,636 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,638 INFO sqlalchemy.engine.base.Engine ('구립청능어린이집', '권영일', '서울특별시 관악구 관악로11길 79-11 ,(봉천동) [청룡동] (청룡동)', '02', '875', '7003', 5)
2021-08-18 17:41:06,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,640 INFO sqlalchemy.engine.base.Engine ('아나율장애아어린이집', '정유진', '서울특별시 구로구 디지털로31길 93 ,(구로동) (구로제3동)', '02', '852', '1628', 7)
2021-08-18 17:41:06,641 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,642 INFO sqlalchemy.engine.base.Engine ('태릉어린이집', '신정호', '서울특별시 노원구 화랑로51길 81 ,(공릉2동 태릉어린이집, 2층) (공릉2동)', '02', '971', '0373', 9)
2021-08-18 17:41:06,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,645 INFO sqlalchemy.engine.base.Engine ('새영어린이집', '정광수', '서울특별시 강서구 양천로63길 58 ,벽산아파트 관리동 새영어린이집 (염창동)', '02', '3661', '6590', 4)
2021-08-18 17:41:06,647 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,648 INFO sqlalchemy.engine.base.Engine ('한마을어린이집', '김준서', '서울특별시 구로구 경인로 382 ,한마을아파트상가 (관리동2층) (개봉동) (개봉제1동)', '02', '2689', '5123', 7)
2021-08-18 17:41:06,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,650 INFO sqlalchemy.engine.base.Engine ('꿈을여는어린이집', '서예준', '서울특별시 은평구 진흥로 267-20 (불광제1동)', '02', '357', '6746', 22)
2021-08-18 17:41:06,652 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,654 INFO sqlalchemy.engine.base.Engine ('새연어린이집', '류준서', '서울특별시 구로구 구로중앙로28다길 15 ,(구로동) (구로제5동)', '02', '852', '7171', 7)
2021-08-18 17:41:06,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,656 INFO sqlalchemy.engine.base.Engine ('참좋은어린이집', '서건우', '서울특별시 구로구 고척로 190 ,(고척2동161-55 / 지하1층~지상5층) (고척제2동)', '02', '2614', '0222', 7)
2021-08-18 17:41:06,657 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,658 INFO sqlalchemy.engine.base.Engine ('원당어린이집', '송지혜', '서울특별시 도봉구 시루봉로5길 48 ,구립원당어린이집 (방학제3동)', '02', '3491', '0533', 10)
2021-08-18 17:41:06,659 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,660 INFO sqlalchemy.engine.base.Engine ('목양몬테소리어린이집', '이영자', '서울특별시 구로구 개봉로17마길 8 ,(개봉동) (개봉제2동)', '02', '2615', '7605', 7)
2021-08-18 17:41:06,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,665 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '최은영', '서울특별시 중랑구 동일로118길 9 ,(상봉동) (상봉제2동)', '02', '496', '0866', 25)
2021-08-18 17:41:06,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,668 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '권지민', '서울특별시 중랑구 겸재로48길 13 ,101동 102호(면목동, 남청파인힐아파트) (면목본동)', '02', '495', '2468', 25)
2021-08-18 17:41:06,669 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,669 INFO sqlalchemy.engine.base.Engine ('은진어린이집', '이성호', '서울특별시 구로구 구로동로20길 28-7 ,1층 (구로동) (구로제4동)', '02', '851', '2612', 7)
2021-08-18 17:41:06,670 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,671 INFO sqlalchemy.engine.base.Engine ('피카소어린이집', '권준혁', '서울특별시 성북구 서경로 28 ,태영아파트 단지내 (관리동2층) (정릉동) (정릉제1동)', '02', '943', '1151', 17)
2021-08-18 17:41:06,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,674 INFO sqlalchemy.engine.base.Engine ('솔밭어린이집', '장유진', '서울특별시 강북구 삼양로149길 12 ,(우이동) (우이동)', '02', '900', '3030', 3)
2021-08-18 17:41:06,675 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,676 INFO sqlalchemy.engine.base.Engine ('아이사랑어린이집', '윤광수', '서울특별시 관악구 난곡로9길 6 ,(신림동) [난향동] (난향동)', '02', '853', '9414', 5)
2021-08-18 17:41:06,677 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,678 INFO sqlalchemy.engine.base.Engine ('규전어린이집', '최건우', '서울특별시 동대문구 휘경로 42 ,(휘경동) (휘경제1동)', '02', '964', '6580', 11)
2021-08-18 17:41:06,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,679 INFO sqlalchemy.engine.base.Engine ('미키몬테소리어린이집', '정은영', '서울특별시 구로구 경인로 390 ,벽산블루밍아파트 관리동1층 미키몬테소리어린이집 (고척동) (고척제1동)', '02', '2619', '5200', 7)
2021-08-18 17:41:06,680 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,681 INFO sqlalchemy.engine.base.Engine ('새상아어린이집', '박예준', '서울특별시 영등포구 신길로8길 11 (신길제6동)', '02', '836', '0881', 20)
2021-08-18 17:41:06,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,683 INFO sqlalchemy.engine.base.Engine ('서울시청직장어린이집', '안미경', '서울특별시 중구 서소문로11길 24 ,5-1번지 서울시청직장어린이집 (소공동)', '02', '775', '5491', 24)
2021-08-18 17:41:06,684 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,685 INFO sqlalchemy.engine.base.Engine ('해달별어린이집', '김서연', '서울특별시 광진구 구의강변로3가길 39 ,701동 102호(구의동,7단지 현대아파트 ) (구의제3동)', '02', '3437', '3373', 6)
2021-08-18 17:41:06,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,687 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '강준영', '서울특별시 양천구 중앙로36길 36 ,(신정동) (신정1동)', '02', '2654', '0716', 19)
2021-08-18 17:41:06,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,689 INFO sqlalchemy.engine.base.Engine ('방학1동어린이집', '이광수', '서울특별시 도봉구 도당로27길 16 ,(방학동) (방학제1동)', '02', '3491', '0509', 10)
2021-08-18 17:41:06,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,691 INFO sqlalchemy.engine.base.Engine ('신월이화어린이집', '이지혜', '서울특별시 양천구 지양로13길 20 ,(신월동) (신월7동)', '02', '2606', '1409', 19)
2021-08-18 17:41:06,692 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,693 INFO sqlalchemy.engine.base.Engine ('구립 행당어린이집', '임지훈', '서울특별시 성동구 행당로 82 ,한진2차아파트 관리동2층 (행당동) (행당제2동)', '02', '2295', '3918', 16)
2021-08-18 17:41:06,694 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,696 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '류정남', '서울특별시 중랑구 신내역로 165 ,217동 304호(신내동, 우디안아파트) (신내1동)', '02', '2207', '6888', 25)
2021-08-18 17:41:06,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,697 INFO sqlalchemy.engine.base.Engine ('고덕샛별어린이집', '한예준', '서울특별시 강동구 양재대로 1706 ,4동 104호(고덕동, 아남아파트) (고덕제1동)', '02', '441', '7956', 2)
2021-08-18 17:41:06,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,699 INFO sqlalchemy.engine.base.Engine ('꾸러기어린이집', '최정운', '서울특별시 관악구 문성로 242 ,(신림동) [신원동] (신원동)', '02', '864', '6636', 5)
2021-08-18 17:41:06,699 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,700 INFO sqlalchemy.engine.base.Engine ('동심어린이집', '안정순', '서울특별시 금천구 독산로56길 34 ,(시흥동) (시흥제4동)', '02', '895', '1590', 8)
2021-08-18 17:41:06,702 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,702 INFO sqlalchemy.engine.base.Engine ('금빛어린이집', '박준혁', '서울특별시 중랑구 용마산로53길 26 (면목제7동)', '02', '433', '1212', 25)
2021-08-18 17:41:06,704 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,704 INFO sqlalchemy.engine.base.Engine ('꽃길어린이집', '권종수', '서울특별시 강북구 인수봉로52가길 42 ,(수유동) (인수동)', '02', '987', '8487', 3)
2021-08-18 17:41:06,706 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,707 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '윤민지', '서울특별시 성북구 정릉로 305 ,경남아파트 경남아파트단지내 (정릉동) (정릉제1동)', '02', '916', '6993', 17)
2021-08-18 17:41:06,708 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,708 INFO sqlalchemy.engine.base.Engine ('늘기쁜어린이집', '전준호', '서울특별시 강북구 숭인로7가길 37 ,108동 105호(미아동, 미아동부센트레빌) (송천동)', '02', '981', '6346', 3)
2021-08-18 17:41:06,709 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,710 INFO sqlalchemy.engine.base.Engine ('키즈동화나라어린이집', '장상철', '서울특별시 마포구 독막로 266 ,102동 103호 (용강동)', '02', '3273', '7948', 13)
2021-08-18 17:41:06,711 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,711 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '안은정', '서울특별시 강남구 개포로36길 14 ,해맑은어린이집 (개포동) (개포제4동)', '02', '574', '1026', 1)
2021-08-18 17:41:06,712 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,713 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '안예준', '서울특별시 동작구 여의대방로 8 ,102동 105호(신대방동, 우성아파트) (신대방제1동)', '02', '847', '4447', 12)
2021-08-18 17:41:06,714 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,715 INFO sqlalchemy.engine.base.Engine ('꿈나라어린이집', '임지훈', '서울특별시 영등포구 신풍로19가길 12-1 ,원형스위트빌 101호 (신길동) (신길제6동)', '02', '848', '4810', 20)
2021-08-18 17:41:06,716 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,717 INFO sqlalchemy.engine.base.Engine ('쌍문1동어린이집', '한은정', '서울특별시 도봉구 노해로 149-5 (쌍문제1동)', '02', '904', '6868', 10)
2021-08-18 17:41:06,718 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,719 INFO sqlalchemy.engine.base.Engine ('토리어린이집', '황건우', '서울특별시 양천구 은행정로17길 16 ,(신정동) (신정4동)', '02', '2602', '6241', 19)
2021-08-18 17:41:06,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,721 INFO sqlalchemy.engine.base.Engine ('새순어린이집', '강상철', '서울특별시 강동구 상암로17길 49-6 ,(암사1동 492-12) (암사제1동)', '02', '426', '9752', 2)
2021-08-18 17:41:06,722 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,723 INFO sqlalchemy.engine.base.Engine ('자연빅스맘어린이집', '서서현', '서울특별시 양천구 곰달래로5길 37 ,101동 102호(신월동, 태형아파트) (신월1동)', '02', '2695', '2700', 19)
2021-08-18 17:41:06,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,730 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '윤성수', '서울특별시 서대문구 응암로 28 ,1동 109호(북가좌동, 한양아파트) (북가좌제1동)', '02', '307', '3175', 14)
2021-08-18 17:41:06,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,732 INFO sqlalchemy.engine.base.Engine ('청화어린이집', '김준서', '서울특별시 강북구 오현로 179-9 (번2동)', '02', '987', '8824', 3)
2021-08-18 17:41:06,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,736 INFO sqlalchemy.engine.base.Engine ('하얀어린이집', '황지훈', '서울특별시 구로구 개봉로11길 7-11 ,하얀어린이집 (개봉동) (개봉제3동)', '02', '6326', '3257', 7)
2021-08-18 17:41:06,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,739 INFO sqlalchemy.engine.base.Engine ('사무엘어린이집', '강민석', '서울특별시 강북구 한천로109길 83 ,101동 105호(번동, 번동솔그린쌍방울아파트) (번3동)', '02', '985', '6991', 3)
2021-08-18 17:41:06,740 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,741 INFO sqlalchemy.engine.base.Engine ('구립 진터마루어린이집', '안지민', '서울특별시 성동구 둘레3길 18 ,(성수동1가) (성수1가제1동)', '02', '2205', '5004', 16)
2021-08-18 17:41:06,742 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,743 INFO sqlalchemy.engine.base.Engine ('또래방어린이집', '임정식', '서울특별시 강서구 강서로 266 ,126동 104호(화곡동, 우장산아이파크이편한세상) (우장산동)', '02', '2605', '1406', 4)
2021-08-18 17:41:06,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,745 INFO sqlalchemy.engine.base.Engine ('꿈나래어린이집', '류지훈', '서울특별시 구로구 개봉로16가길 10-26 (개봉제2동)', '02', '2066', '6610', 7)
2021-08-18 17:41:06,747 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,747 INFO sqlalchemy.engine.base.Engine ('구립행복어린이집', '권준영', '서울특별시 강북구 인수봉로19길 5-8 (삼양동)', '02', '988', '8384', 3)
2021-08-18 17:41:06,749 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,752 INFO sqlalchemy.engine.base.Engine ('천사들의어린이집', '박영철', '서울특별시 송파구 문정로 55 ,103동 101호(문정동, 문정대우푸르지오아파트) (문정1동)', '02', '401', '0792', 18)
2021-08-18 17:41:06,754 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,755 INFO sqlalchemy.engine.base.Engine ('구립둔촌어린이집', '장민석', '서울특별시 강동구 명일로 129 ,(둔촌동 81-4) (둔촌제2동)', '02', '474', '7445', 2)
2021-08-18 17:41:06,756 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,757 INFO sqlalchemy.engine.base.Engine ('새믿음어린이집', '임준호', '서울특별시 중랑구 용마산로116길 26 ,(망우동) (망우본동)', '02', '494', '4545', 25)
2021-08-18 17:41:06,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,759 INFO sqlalchemy.engine.base.Engine ('튼튼삐아제어린이집', '서준서', '서울특별시 성동구 행당로 75 ,대림아파트제2관리소2층 (행당제2동)', '02', '2296', '3071', 16)
2021-08-18 17:41:06,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,761 INFO sqlalchemy.engine.base.Engine ('미성엔젤어린이집', '신영식', '서울특별시 은평구 통일로 780 ,6동 108호(불광동, 미성아파트) (불광제1동)', '02', '385', '3359', 22)
2021-08-18 17:41:06,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,763 INFO sqlalchemy.engine.base.Engine ('성은어린이집', '전준호', '서울특별시 구로구 구로동로25길 14 ,(구로동) (구로제2동)', '02', '864', '8114', 7)
2021-08-18 17:41:06,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,767 INFO sqlalchemy.engine.base.Engine ('맑은샘어린이집', '황영숙', '서울특별시 구로구 경인로47가길 23 ,(사실상1~4층) (고척동) (고척제1동)', '02', '2687', '1339', 7)
2021-08-18 17:41:06,768 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,769 INFO sqlalchemy.engine.base.Engine ('한뜻어린이집', '윤지혜', '서울특별시 노원구 노원로 428 ,(상계2동 중앙하이츠아파트2차 단지내) (상계2동)', '02', '934', '2554', 9)
2021-08-18 17:41:06,771 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,772 INFO sqlalchemy.engine.base.Engine ('제일몬테소리어린이집', '한병철', '서울특별시 강동구 아리수로66길 10 ,(고덕동 532) (고덕제1동)', '02', '427', '1158', 2)
2021-08-18 17:41:06,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,775 INFO sqlalchemy.engine.base.Engine ('청수어린이집', '서서현', '서울특별시 강남구 압구정로79길 26 ,청수어린이집 (청담동) (청담동)', '02', '512', '5151', 1)
2021-08-18 17:41:06,776 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,777 INFO sqlalchemy.engine.base.Engine ('어린왕자어린이집', '김현정', '서울특별시 동대문구 신이문로6길 10 ,(이문동) (이문제2동)', '02', '959', '5977', 11)
2021-08-18 17:41:06,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,779 INFO sqlalchemy.engine.base.Engine ('행복가득어린이집', '송준서', '서울특별시 구로구 고척로60길 30 ,고척벽산베스트블루밍아파트 103동102호 (고척제2동)', '02', '2613', '9285', 7)
2021-08-18 17:41:06,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,781 INFO sqlalchemy.engine.base.Engine ('연동어린이집', '정지훈', '서울특별시 종로구 대학로3길 9 ,(연지동) (종로5.6가동)', '02', '3673', '2866', 23)
2021-08-18 17:41:06,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,783 INFO sqlalchemy.engine.base.Engine ('은성어린이집', '한혜진', '서울특별시 광진구 동일로4길 52 ,(자양동) (자양제4동)', '02', '465', '7476', 6)
2021-08-18 17:41:06,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,786 INFO sqlalchemy.engine.base.Engine ('화가마을어린이집', '조정수', '서울특별시 강동구 동남로82길 87 ,(고덕동 258-8) (고덕제2동)', '02', '427', '9693', 2)
2021-08-18 17:41:06,787 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,788 INFO sqlalchemy.engine.base.Engine ('군자어린이집', '황준혁', '서울특별시 광진구 동일로56가길 31 ,(군자동) (군자동)', '02', '461', '2440', 6)
2021-08-18 17:41:06,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,790 INFO sqlalchemy.engine.base.Engine ('아침해 어린이집', '신은정', '서울특별시 강서구 양천로 731 ,동아3차아파트 관리소2층 아침해어린이집 (염창동)', '02', '2668', '6733', 4)
2021-08-18 17:41:06,791 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,801 INFO sqlalchemy.engine.base.Engine ('키드윈아트어린이집', '정영환', '서울특별시 양천구 목동중앙남로 57-5 ,키드윈어린이집 (목4동)', '02', '2642', '7709', 19)
2021-08-18 17:41:06,809 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,810 INFO sqlalchemy.engine.base.Engine ('삼청어린이집', '서영식', '서울특별시 종로구 삼청로7길 26 ,(팔판동) (삼청동)', '02', '723', '0155', 23)
2021-08-18 17:41:06,811 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,812 INFO sqlalchemy.engine.base.Engine ('구립빗살어린이집', '송성진', '서울특별시 강동구 구천면로17길 22 ,(천호동 340-39) (천호제2동)', '02', '477', '2141', 2)
2021-08-18 17:41:06,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,814 INFO sqlalchemy.engine.base.Engine ('꼬마숲어린이집', '강경자', '서울특별시 강서구 강서로45다길 30-27 ,초록아파트 단지 내 관리사무소 1층 꼬마숲어린이집 (화곡제3동)', '02', '2696', '3275', 4)
2021-08-18 17:41:06,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,817 INFO sqlalchemy.engine.base.Engine ('잠원어린이집', '서영자', '서울특별시 서초구 신반포로33길 15 ,동아아파트 관리동 1층 잠원어린이집 (반포3동)', '02', '533', '6673', 15)
2021-08-18 17:41:06,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,819 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '오준혁', '서울특별시 도봉구 해등로25길 41 ,701동 106호(쌍문동, 한양아파트) (쌍문제4동)', '02', '904', '3567', 10)
2021-08-18 17:41:06,820 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,821 INFO sqlalchemy.engine.base.Engine ('성은어린이집', '강영식', '서울특별시 동대문구 한천로 434 ,(이문동) (이문제2동)', '02', '967', '7178', 11)
2021-08-18 17:41:06,822 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,823 INFO sqlalchemy.engine.base.Engine ('도담아이어린이집', '류영환', '서울특별시 노원구 동일로 1383 ,322동 102호(상계동, 상계주공3차) (상계6.7동)', '02', '933', '8711', 9)
2021-08-18 17:41:06,824 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,824 INFO sqlalchemy.engine.base.Engine ('동아어린이집', '최지영', '서울특별시 강서구 양천로 731 ,306동 102호(염창동, 동아3차아파트) (염창동)', '02', '2658', '9837', 4)
2021-08-18 17:41:06,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,826 INFO sqlalchemy.engine.base.Engine ('나하나어린이집', '윤민수', '서울특별시 강남구 양재대로55길 6 ,상가동 304,305호 (일원제1동)', '02', '451', '7635', 1)
2021-08-18 17:41:06,826 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,827 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '최영철', '서울특별시 노원구 덕릉로70가길 92 ,(상계동, 초록어린이집) (상계6.7동)', '02', '951', '6118', 9)
2021-08-18 17:41:06,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,829 INFO sqlalchemy.engine.base.Engine ('하나영재어린이집', '임민수', '서울특별시 강서구 양천로 507 ,강나루현대아파트 단지내 (가양동) (가양제3동)', '02', '3663', '3088', 4)
2021-08-18 17:41:06,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,831 INFO sqlalchemy.engine.base.Engine ('그림나라어린이집', '윤준영', '서울특별시 노원구 한글비석로 57 ,9동 101호(하계동, 청구) (하계1동)', '02', '948', '3169', 9)
2021-08-18 17:41:06,831 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,832 INFO sqlalchemy.engine.base.Engine ('꿈의어린이집', '권영자', '서울특별시 강북구 오현로31길 85-7 ,102동 106호(번동, 금호아파트) (번2동)', '02', '945', '3915', 3)
2021-08-18 17:41:06,834 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,835 INFO sqlalchemy.engine.base.Engine ('구립참사랑어린이집', '한은경', '서울특별시 동작구 동작대로17길 37 ,(사당동) (사당제1동)', '02', '582', '2072', 12)
2021-08-18 17:41:06,837 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,837 INFO sqlalchemy.engine.base.Engine ('구립비둘기어린이집', '황종수', '서울특별시 동작구 여의대방로44길 47 ,(대방동) (대방동)', '02', '817', '2903', 12)
2021-08-18 17:41:06,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,839 INFO sqlalchemy.engine.base.Engine ('창5동어린이집', '정준영', '서울특별시 도봉구 해등로16길 52-13 (창제5동)', '02', '994', '3004', 10)
2021-08-18 17:41:06,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,840 INFO sqlalchemy.engine.base.Engine ('홍익어린이집', '송정식', '서울특별시 은평구 가좌로11길 5-3 (신사제2동)', '02', '303', '4142', 22)
2021-08-18 17:41:06,841 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,842 INFO sqlalchemy.engine.base.Engine ('예솔어린이집', '권상훈', '서울특별시 중랑구 동일로123길 67 ,(3층) (중화동) (중화제2동)', '02', '435', '0178', 25)
2021-08-18 17:41:06,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,843 INFO sqlalchemy.engine.base.Engine ('예림어린이집', '강민서', '서울특별시 성북구 장위로33길 17 ,(장위동) (장위제2동)', '02', '919', '0179', 17)
2021-08-18 17:41:06,848 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,849 INFO sqlalchemy.engine.base.Engine ('구립인수동어린이집', '서민수', '서울특별시 강북구 삼양로107길 46 ,(수유동) (인수동)', '02', '999', '0970', 3)
2021-08-18 17:41:06,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,850 INFO sqlalchemy.engine.base.Engine ('고은천사어린이집', '강민재', '서울특별시 도봉구 노해로70길 119 ,1805동 106호(창동, 주공18단지아파트) (창제4동)', '02', '994', '0809', 10)
2021-08-18 17:41:06,851 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,852 INFO sqlalchemy.engine.base.Engine ('수잔나어린이집', '안민수', '서울특별시 구로구 고척로51길 73 ,(고척동) (고척제2동)', '02', '2689', '1225', 7)
2021-08-18 17:41:06,853 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,853 INFO sqlalchemy.engine.base.Engine ('환희어린이집', '류성수', '서울특별시 서대문구 증가로10길 16-9 (남가좌제2동)', '02', '306', '7518', 14)
2021-08-18 17:41:06,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,855 INFO sqlalchemy.engine.base.Engine ('또또 어린이집', '송성민', '서울특별시 성동구 행당로 82 ,111동 101호(행당동, 해모로한진타운) (행당제2동)', '02', '2281', '8992', 16)
2021-08-18 17:41:06,857 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,857 INFO sqlalchemy.engine.base.Engine ('씽씽어린이집', '이준영', '서울특별시 관악구 대학18길 6 ,101동 208호(신림동, 금호타운1차) [대학동] (대학동)', '02', '888', '7721', 5)
2021-08-18 17:41:06,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,859 INFO sqlalchemy.engine.base.Engine ('혜원유아학교어린이집', '김준혁', '서울특별시 양천구 신정로 260 ,신트리아파트4단지 보육시설 (신정동) (신정3동)', '02', '2065', '8011', 19)
2021-08-18 17:41:06,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,861 INFO sqlalchemy.engine.base.Engine ('구립독산본동어린이집', '박경자', '서울특별시 금천구 시흥대로150길 79 ,(독산동) (독산제3동)', '02', '839', '3550', 8)
2021-08-18 17:41:06,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,863 INFO sqlalchemy.engine.base.Engine ('세천사어린이집', '류건우', '서울특별시 양천구 남부순환로70길 17-1 (신월7동)', '02', '2693', '2088', 19)
2021-08-18 17:41:06,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,864 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '한혜진', '서울특별시 강동구 양재대로 1305 ,(성내동441-3) (성내제3동)', '02', '473', '3006', 2)
2021-08-18 17:41:06,865 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,866 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '전영환', '서울특별시 성북구 돌곶이로 52-9 (석관동)', '02', '966', '1824', 17)
2021-08-18 17:41:06,867 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,867 INFO sqlalchemy.engine.base.Engine ('그린어린이집', '권도현', '서울특별시 노원구 동일로207길 18 ,114동 103호(중계동, 중계그린1단지아파트) (중계2.3동)', '02', '978', '4658', 9)
2021-08-18 17:41:06,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,869 INFO sqlalchemy.engine.base.Engine ('창동어린이집', '장지훈', '서울특별시 도봉구 덕릉로 329 ,(창동) (창제1동)', '02', '904', '3222', 10)
2021-08-18 17:41:06,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,871 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '임서현', '서울특별시 금천구 독산로 78-1 (시흥제4동)', '02', '891', '2215', 8)
2021-08-18 17:41:06,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,874 INFO sqlalchemy.engine.base.Engine ('윤슬어린이집', '윤지원', '서울특별시 강북구 삼각산로 143-1 ,201동 110호(수유동, 수유벽산2차) (수유2동)', '02', '902', '8018', 3)
2021-08-18 17:41:06,875 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,876 INFO sqlalchemy.engine.base.Engine ('벧엘어린이집', '김경자', '서울특별시 마포구 성암로 79 ,201동 107호(중동, 현대아파트) (성산제2동)', '02', '3142', '4750', 13)
2021-08-18 17:41:06,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,878 INFO sqlalchemy.engine.base.Engine ('한나어린이집', '강은영', '서울특별시 강서구 등촌로5길 60 ,(화곡동) (화곡제4동)', '02', '2644', '9280', 4)
2021-08-18 17:41:06,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,880 INFO sqlalchemy.engine.base.Engine ('은성어린이집', '안영환', '서울특별시 강남구 개포로110길 15 ,111동 102호(일원동, 우성7차아파트) (일원2동)', '02', '445', '2670', 1)
2021-08-18 17:41:06,881 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,882 INFO sqlalchemy.engine.base.Engine ('해맑은어린이집', '류영철', '서울특별시 중랑구 용마공원로4길 11 ,(망우동) (망우제3동)', '02', '2209', '3516', 25)
2021-08-18 17:41:06,883 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,884 INFO sqlalchemy.engine.base.Engine ('화곡꼬마천사어린이집', '장은경', '서울특별시 강서구 강서로26길 11 ,(화곡동) (화곡본동)', '02', '2694', '7982', 4)
2021-08-18 17:41:06,887 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,888 INFO sqlalchemy.engine.base.Engine ('밝은어린이집', '송지민', '서울특별시 구로구 구로동로7길 74 (가리봉동)', '02', '3283', '3737', 7)
2021-08-18 17:41:06,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,890 INFO sqlalchemy.engine.base.Engine ('중곡1동어린이집', '이미영', '서울특별시 광진구 능동로43길 27-14 ,(중곡동) (중곡제1동)', '02', '498', '2878', 6)
2021-08-18 17:41:06,893 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,894 INFO sqlalchemy.engine.base.Engine ('꿈동이어린이집', '신준호', '서울특별시 용산구 이촌로87길 21 ,101동 101호(이촌동, 이촌코오롱) (이촌제1동)', '02', '795', '5475', 21)
2021-08-18 17:41:06,895 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,895 INFO sqlalchemy.engine.base.Engine ('홍익어린이집', '오정호', '서울특별시 노원구 덕릉로71길 30 ,(중계1동 양지대림아파트단지내) (중계1동)', '02', '930', '1004', 9)
2021-08-18 17:41:06,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,897 INFO sqlalchemy.engine.base.Engine ('근로복지공단모아래어린이집', '김영철', '서울특별시 금천구 가산로9길 35 ,(가산동) (가산동)', '02', '865', '7220', 8)
2021-08-18 17:41:06,898 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,899 INFO sqlalchemy.engine.base.Engine ('함께크는어린이집', '전경자', '서울특별시 서초구 바우뫼로11안길 12 ,(우면동) (양재1동)', '02', '3462', '7599', 15)
2021-08-18 17:41:06,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,900 INFO sqlalchemy.engine.base.Engine ('엘림어린이집', '한상훈', '서울특별시 노원구 동일로198길 9 ,(공릉동) (공릉1동)', '02', '977', '9624', 9)
2021-08-18 17:41:06,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,902 INFO sqlalchemy.engine.base.Engine ('사랑마을어린이집', '최영철', '서울특별시 노원구 노원로 564 ,1009동 105호(상계동, 상계주공10차) (상계8동)', '02', '932', '4852', 9)
2021-08-18 17:41:06,903 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,904 INFO sqlalchemy.engine.base.Engine ('샬롬어린이집', '전영진', '서울특별시 노원구 덕릉로73길 28 ,(중계1동 양지대림아파트 2단지 관리동내) (중계1동)', '02', '3391', '9532', 9)
2021-08-18 17:41:06,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,906 INFO sqlalchemy.engine.base.Engine ('구립백운어린이집', '송병철', '서울특별시 강북구 인수봉로77길 10 ,(수유동) (인수동)', '02', '999', '9091', 3)
2021-08-18 17:41:06,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,908 INFO sqlalchemy.engine.base.Engine ('꼬꼬마 어린이집', '임정순', '서울특별시 성동구 동호로 100 ,106동 101호(금호동3가, 두산아파트) (금호2.3가동)', '02', '2254', '4248', 16)
2021-08-18 17:41:06,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,910 INFO sqlalchemy.engine.base.Engine ('왕자와공주어린이집', '서영철', '서울특별시 송파구 올림픽로 435 ,214동 102호(신천동,파크리오) (잠실4동)', '02', '422', '3436', 18)
2021-08-18 17:41:06,911 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,912 INFO sqlalchemy.engine.base.Engine ('경기몬테소리어린이집', '조경회', '서울특별시 서초구 서리풀4길 15-5 (서초1동)', '02', '588', '1163', 15)
2021-08-18 17:41:06,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,915 INFO sqlalchemy.engine.base.Engine ('공릉2동어린이집', '조민재', '서울특별시 노원구 공릉로34길 73 ,(공릉2동 77번지) (공릉2동)', '02', '973', '3053', 9)
2021-08-18 17:41:06,916 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,917 INFO sqlalchemy.engine.base.Engine ('병아리어린이집', '류영진', '서울특별시 강서구 공항대로 351-21 ,101동 106호(등촌동, 진로미주아파트) (등촌제3동)', '02', '2668', '3574', 4)
2021-08-18 17:41:06,919 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,920 INFO sqlalchemy.engine.base.Engine ('녹색어린이집', '최정수', '서울특별시 성북구 한천로90길 49 ,2층 (장위동) (장위제3동)', '02', '914', '9430', 17)
2021-08-18 17:41:06,921 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,922 INFO sqlalchemy.engine.base.Engine ('청담어린이집', '안진호', '서울특별시 금천구 탑골로 35 ,(시흥동) (시흥제5동)', '02', '896', '1393', 8)
2021-08-18 17:41:06,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,923 INFO sqlalchemy.engine.base.Engine ('구립 행복한숲어린이집', '서미경', '서울특별시 은평구 갈현로7가길 9 ,(역촌동) (역촌동)', '02', '352', '7178', 22)
2021-08-18 17:41:06,925 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,925 INFO sqlalchemy.engine.base.Engine ('동아또래또 어린이집', '송은영', '서울특별시 도봉구 도봉로180길 6-23 ,106동 102호(도봉동, 동아에코빌아파트) (도봉제2동)', '02', '3493', '8823', 10)
2021-08-18 17:41:06,927 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,928 INFO sqlalchemy.engine.base.Engine ('늘품어린이집', '이서현', '서울특별시 강서구 강서로18다길 41 ,2층 (화곡제8동)', '02', '2608', '0177', 4)
2021-08-18 17:41:06,931 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,932 INFO sqlalchemy.engine.base.Engine ('벽산어린이집', '신정수', '서울특별시 서대문구 세검정로1길 95 ,116동 104호(홍은동, 홍은동벽산아파트) (홍은제1동)', '02', '396', '1500', 14)
2021-08-18 17:41:06,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,934 INFO sqlalchemy.engine.base.Engine ('구립미래클어린이집', '강준혁', '서울특별시 관악구 법원단지2길 15-4 ,(신림동) [난곡동] (난곡동)', '02', '863', '7001', 5)
2021-08-18 17:41:06,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,936 INFO sqlalchemy.engine.base.Engine ('다연어린이집', '장동현', '서울특별시 마포구 마포대로11길 84 ,1동 110호(공덕동,마포현대아파트) (아현동)', '02', '712', '8998', 13)
2021-08-18 17:41:06,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,938 INFO sqlalchemy.engine.base.Engine ('대원어린이집', '송지혜', '서울특별시 광진구 자양로43길 115 ,(중곡동) (중곡제4동)', '02', '3437', '7173', 6)
2021-08-18 17:41:06,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,939 INFO sqlalchemy.engine.base.Engine ('배꽃어린이집', '서도현', '서울특별시 중랑구 용마산로109길 18 ,(망우동) (망우본동)', '02', '494', '5511', 25)
2021-08-18 17:41:06,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,941 INFO sqlalchemy.engine.base.Engine ('신석어린이집', '박지훈', '서울특별시 마포구 대흥로 11 ,(현석동) (신수동)', '02', '704', '2269', 13)
2021-08-18 17:41:06,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,942 INFO sqlalchemy.engine.base.Engine ('아이들세상어린이집', '권영식', '서울특별시 광진구 긴고랑로26길 31 ,(중곡동) (중곡제2동)', '02', '3436', '4611', 6)
2021-08-18 17:41:06,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,945 INFO sqlalchemy.engine.base.Engine ('초록별어린이집', '한은경', '서울특별시 강서구 강서로45다길 30-27 ,106동 201호(화곡동, 초록아파트) (화곡제3동)', '02', '2604', '9470', 4)
2021-08-18 17:41:06,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,947 INFO sqlalchemy.engine.base.Engine ('효창어린이집', '류영환', '서울특별시 용산구 효창원로69길 14-3 ,(효창동) (효창동)', '02', '711', '5408', 21)
2021-08-18 17:41:06,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,950 INFO sqlalchemy.engine.base.Engine ('시흥어린이집', '조준혁', '서울특별시 금천구 시흥대로20길 17 ,(시흥동) (시흥제3동)', '02', '805', '4104', 8)
2021-08-18 17:41:06,951 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,952 INFO sqlalchemy.engine.base.Engine ('앙팡어린이집', '이준영', '서울특별시 강북구 삼양로118길 10-7 ,(수유동) (수유2동)', '02', '997', '9209', 3)
2021-08-18 17:41:06,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,953 INFO sqlalchemy.engine.base.Engine ('새하늘어린이집', '황진호', '서울특별시 구로구 구일로4길 46 ,201동 101호(구로동, 현대연예인아파트) (구로제1동)', '02', '858', '1430', 7)
2021-08-18 17:41:06,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,955 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '강경회', '서울특별시 강동구 풍성로51길 7 ,(성내동 409-10) (성내제3동)', '02', '482', '9082', 2)
2021-08-18 17:41:06,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,956 INFO sqlalchemy.engine.base.Engine ('능동어린이집', '정종수', '서울특별시 광진구 천호대로114길 47 ,(능동) (능동)', '02', '458', '0670', 6)
2021-08-18 17:41:06,957 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,958 INFO sqlalchemy.engine.base.Engine ('한양대학교 한양어린이집', '안준혁', '서울특별시 성동구 왕십리로 222-1 ,한양대학교 내 (사근동)', '02', '2220', '1528', 16)
2021-08-18 17:41:06,958 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,959 INFO sqlalchemy.engine.base.Engine ('역삼럭키어린이집', '최정순', '서울특별시 강남구 논현로 213 ,102동 116호(도곡동, 역삼럭키아파트) (도곡제1동)', '02', '575', '3213', 1)
2021-08-18 17:41:06,960 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,960 INFO sqlalchemy.engine.base.Engine ('예꼴예능어린이집', '류경숙', '서울특별시 서대문구 독립문공원길 17 ,예꼴예능어린이집 (천연동)', '02', '392', '8189', 14)
2021-08-18 17:41:06,962 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,962 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '정정수', '서울특별시 서대문구 가재울로 45 ,102동 104호(남가좌동, 현대아파트) (남가좌제2동)', '02', '374', '9566', 14)
2021-08-18 17:41:06,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,964 INFO sqlalchemy.engine.base.Engine ('성결어린이집', '김지영', '서울특별시 마포구 독막로28길 19 ,(신수동) (신수동)', '02', '719', '3411', 13)
2021-08-18 17:41:06,966 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:06,968 INFO sqlalchemy.engine.base.Engine ('놀이나라어린이집', '류지은', '서울특별시 노원구 동일로227길 86 ,1602동 102호(상계동, 상계주공16차) (상계8동)', '02', '6223', '7011', 9)
2021-08-18 17:41:06,970 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,971 INFO sqlalchemy.engine.base.Engine ('예성어린이집', '윤지훈', '서울특별시 동작구 사당로30길 24 ,3층 (사당동) (사당제1동)', '02', '582', '4406', 12)
2021-08-18 17:41:06,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,974 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '황건우', '서울특별시 은평구 갈현로3길 48 ,(신사동) (신사제1동)', '02', '359', '8458', 22)
2021-08-18 17:41:06,975 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,976 INFO sqlalchemy.engine.base.Engine ('명화어린이집', '윤종수', '서울특별시 구로구 개봉로17다길 6 ,(개봉동) (개봉제2동)', '02', '2612', '2552', 7)
2021-08-18 17:41:06,977 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,978 INFO sqlalchemy.engine.base.Engine ('목련어린이집', '송지영', '서울특별시 강남구 개포로 617-8 (일원제2동)', '02', '3412', '1998', 1)
2021-08-18 17:41:06,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,981 INFO sqlalchemy.engine.base.Engine ('푸른어린이집', '장정호', '서울특별시 영등포구 신길로62나길 3-1 (영등포본동)', '02', '835', '0835', 20)
2021-08-18 17:41:06,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,984 INFO sqlalchemy.engine.base.Engine ('엘림어린이집', '권현준', '서울특별시 도봉구 시루봉로11길 25 ,(방학동) (방학제3동)', '02', '3493', '9194', 10)
2021-08-18 17:41:06,985 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,986 INFO sqlalchemy.engine.base.Engine ('성심어린이집', '류영숙', '서울특별시 광진구 용마산로3길 60 ,(중곡동) (중곡제2동)', '02', '3437', '2381', 6)
2021-08-18 17:41:06,988 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,988 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '서지훈', '서울특별시 관악구 행운1마길 29 ,(봉천동) [행운동] (행운동)', '02', '888', '6766', 5)
2021-08-18 17:41:06,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,990 INFO sqlalchemy.engine.base.Engine ('서울주택도시공사 으뜸어린이집', '정준호', '서울특별시 강남구 개포로 621 ,SH공사 14동 5호(개포동) (일원제2동)', '02', '6940', '8680', 1)
2021-08-18 17:41:06,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,994 INFO sqlalchemy.engine.base.Engine ('한신어린이집', '류민지', '서울특별시 동대문구 제기로 131 ,청량한신2차아파트 단지동 (청량리동) (청량리동)', '02', '957', '0656', 11)
2021-08-18 17:41:06,996 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:06,998 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '황준호', '서울특별시 송파구 백제고분로20길 16 ,현대아파트 단지내 (잠실본동)', '02', '424', '9019', 18)
2021-08-18 17:41:06,999 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,000 INFO sqlalchemy.engine.base.Engine ('성동종합사회복지관 부설 방과후 어린이집', '신경자', '서울특별시 성동구 청계천로 506 ,성동종합사회복지관 부설 방과후어린이집 3층(늘푸른통합교실) (마장동)', '02', '2290', '3163', 16)
2021-08-18 17:41:07,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,003 INFO sqlalchemy.engine.base.Engine ('구립고은어린이집', '황영숙', '서울특별시 동작구 신대방2길 42-10 (신대방제1동)', '02', '834', '1097', 12)
2021-08-18 17:41:07,004 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,005 INFO sqlalchemy.engine.base.Engine ('윤지어린이집', '강영진', '서울특별시 영등포구 도림천로21길 33 (대림제2동)', '02', '844', '4050', 20)
2021-08-18 17:41:07,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,006 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '송영진', '서울특별시 영등포구 도림천로 431 ,105동 101호(대림동, 대림한솔 솔파크) (대림제2동)', '02', '833', '3535', 20)
2021-08-18 17:41:07,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,008 INFO sqlalchemy.engine.base.Engine ('힘찬어린이집', '안민석', '서울특별시 서대문구 증가로 214-1 (북가좌제2동)', '02', '308', '8520', 14)
2021-08-18 17:41:07,009 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,010 INFO sqlalchemy.engine.base.Engine ('북아현방과후교실어린이집', '송건우', '서울특별시 서대문구 북아현로1가길 6 ,(북아현동) (북아현동)', '02', '364', '0098', 14)
2021-08-18 17:41:07,010 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,011 INFO sqlalchemy.engine.base.Engine ('고은쁘띠에꼴어린이집', '윤정웅', '서울특별시 강서구 허준로 47 ,가양2단지도시개발아파트 관리사무소내 (가양동) (가양제1동)', '02', '2668', '5445', 4)
2021-08-18 17:41:07,013 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,013 INFO sqlalchemy.engine.base.Engine ('은별어린이집', '김영진', '서울특별시 구로구 오리로22나길 8-3 (수궁동)', '02', '2684', '7053', 7)
2021-08-18 17:41:07,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,015 INFO sqlalchemy.engine.base.Engine ('딩동댕어린이집', '서경숙', '서울특별시 은평구 가좌로 294 (신사제1동)', '02', '384', '0003', 22)
2021-08-18 17:41:07,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,017 INFO sqlalchemy.engine.base.Engine ('다래어린이집', '정지영', '서울특별시 송파구 오금로42길 9 (가락2동)', '02', '404', '0237', 18)
2021-08-18 17:41:07,018 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,019 INFO sqlalchemy.engine.base.Engine ('삼육대학교부설어린이집', '전정수', '서울특별시 노원구 화랑로 815 ,(공릉동) (공릉2동)', '02', '3399', '1198', 9)
2021-08-18 17:41:07,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,022 INFO sqlalchemy.engine.base.Engine ('피터팬어린이집', '이서현', '서울특별시 영등포구 당산로 95 ,102동 101호(당산동2가, 한전현대아파트) (당산제1동)', '02', '2633', '8078', 20)
2021-08-18 17:41:07,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,024 INFO sqlalchemy.engine.base.Engine ('우리아이어린이집', '김영숙', '서울특별시 서대문구 가재울로 43 ,104동 104호(남가좌동, 현대아파트) (남가좌제2동)', '02', '372', '9158', 14)
2021-08-18 17:41:07,025 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,026 INFO sqlalchemy.engine.base.Engine ('양문어린이집', '윤정순', '서울특별시 금천구 시흥대로45길 35 ,(시흥동) 1층 (시흥제1동)', '02', '805', '1800', 8)
2021-08-18 17:41:07,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,031 INFO sqlalchemy.engine.base.Engine ('달님별님어린이집', '류서연', '서울특별시 강서구 곰달래로51길 14 ,(화곡동) (화곡제4동)', '02', '2653', '1335', 4)
2021-08-18 17:41:07,032 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,032 INFO sqlalchemy.engine.base.Engine ('사랑샘오감어린이집', '최경회', '서울특별시 노원구 한글비석로 480 ,206동 105호(상계동, 보람아파트) (상계9동)', '02', '935', '7465', 9)
2021-08-18 17:41:07,040 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,041 INFO sqlalchemy.engine.base.Engine ('구립금강어린이집', '장정운', '서울특별시 관악구 신림로48길 25 ,(신림동) [서원동] (서원동)', '02', '876', '8854', 5)
2021-08-18 17:41:07,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,043 INFO sqlalchemy.engine.base.Engine ('홍제동성당부설방과후교실어린이집', '임영일', '서울특별시 서대문구 통일로40길 18 ,(홍제동) (홍제제3동)', '02', '379', '6808', 14)
2021-08-18 17:41:07,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,046 INFO sqlalchemy.engine.base.Engine ('예다인어린이집', '오은경', '서울특별시 양천구 월정로6길 14 ,(신월동) (신월2동)', '02', '2608', '9889', 19)
2021-08-18 17:41:07,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,047 INFO sqlalchemy.engine.base.Engine ('믿음어린이집', '윤경회', '서울특별시 관악구 신원로4길 46 ,(신림동) [신원동] (신원동)', '02', '851', '4030', 5)
2021-08-18 17:41:07,050 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,050 INFO sqlalchemy.engine.base.Engine ('신영어린이집', '서수빈', '서울특별시 도봉구 방학로 187 ,104동 107호(방학동, 한화성원아파트) (방학제3동)', '02', '955', '9484', 10)
2021-08-18 17:41:07,052 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,053 INFO sqlalchemy.engine.base.Engine ('작은꽃어린이집', '한진호', '서울특별시 노원구 노원로 532 ,915동 103호(상계동, 주공아파트) (상계10동)', '02', '930', '9511', 9)
2021-08-18 17:41:07,054 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,054 INFO sqlalchemy.engine.base.Engine ('한올어린이집', '강건우', '서울특별시 강북구 도봉로59길 40 ,(미아동) (미아동)', '02', '987', '6162', 3)
2021-08-18 17:41:07,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,056 INFO sqlalchemy.engine.base.Engine ('서울선교어린이집', '오도현', '서울특별시 관악구 낙성대로3길 26 ,1층 (봉천동) [낙성대동] (낙성대동)', '02', '888', '7623', 5)
2021-08-18 17:41:07,057 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,058 INFO sqlalchemy.engine.base.Engine ('숲속천사킨더가르텐어린이집', '임예은', '서울특별시 동작구 사당로16자길 15-7 ,사당4동 300-84 (사당제4동)', '02', '597', '3383', 12)
2021-08-18 17:41:07,059 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,061 INFO sqlalchemy.engine.base.Engine ('방학3동어린이집', '전성민', '서울특별시 도봉구 방학로11길 24 ,(방학동) (방학제3동)', '02', '3493', '0009', 10)
2021-08-18 17:41:07,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,064 INFO sqlalchemy.engine.base.Engine ('오금 어린이집', '정지원', '서울특별시 송파구 마천로27길 4 ,(오금동) (오금동)', '02', '403', '2057', 18)
2021-08-18 17:41:07,065 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,066 INFO sqlalchemy.engine.base.Engine ('현일어린이집', '오영철', '서울특별시 구로구 구로중앙로22길 70 ,(구로동) (구로제5동)', '02', '855', '6434', 7)
2021-08-18 17:41:07,067 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,068 INFO sqlalchemy.engine.base.Engine ('제일어린이집', '한동현', '서울특별시 강북구 삼양로163길 63 ,(우이동) (우이동)', '02', '904', '8002', 3)
2021-08-18 17:41:07,069 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,072 INFO sqlalchemy.engine.base.Engine ('샤이닝키즈어린이집', '한경자', '서울특별시 서초구 서초대로74길 30 ,(서초동) (서초2동)', '02', '525', '2577', 15)
2021-08-18 17:41:07,073 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,074 INFO sqlalchemy.engine.base.Engine ('큰나무어린이집', '신종수', '서울특별시 구로구 고척로52길 48 ,대우아파트단지내 (고척제2동)', '02', '3666', '1400', 7)
2021-08-18 17:41:07,075 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,076 INFO sqlalchemy.engine.base.Engine ('레인보우어린이집', '신영식', '서울특별시 강서구 허준로 234 ,가양아파트 9단지내 관리사무실 2층 (가양동) (가양제3동)', '02', '3663', '5300', 4)
2021-08-18 17:41:07,077 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,079 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '김혜진', '서울특별시 관악구 인헌17길 25 ,(봉천동) [인헌동] (인헌동)', '02', '875', '2841', 5)
2021-08-18 17:41:07,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,080 INFO sqlalchemy.engine.base.Engine ('알토랑밤토랑어린이집', '전지훈', '서울특별시 관악구 조원로 168 ,1층(신림동) [신사동] (신사동)', '02', '853', '1513', 5)
2021-08-18 17:41:07,081 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,082 INFO sqlalchemy.engine.base.Engine ('한티어린이집', '신민수', '서울특별시 강남구 영동대로57길 7 ,대치평생학습관 3층 (대치동) (대치제2동)', '02', '501', '0079', 1)
2021-08-18 17:41:07,083 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,083 INFO sqlalchemy.engine.base.Engine ('교육촌어린이집', '류정운', '서울특별시 노원구 월계로44길 61 ,(월계동) (월계1동)', '02', '911', '8617', 9)
2021-08-18 17:41:07,084 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,085 INFO sqlalchemy.engine.base.Engine ('명지대학교어린이집', '조종수', '서울특별시 서대문구 거북골로 34 ,(남가좌동) (남가좌제2동)', '02', '300', '1830', 14)
2021-08-18 17:41:07,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,086 INFO sqlalchemy.engine.base.Engine ('큰별어린이집', '김은영', '서울특별시 강동구 양재대로124길 70-3 ,(길동 342-10) (길동)', '02', '473', '0446', 2)
2021-08-18 17:41:07,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,089 INFO sqlalchemy.engine.base.Engine ('하늘어린이집', '임성호', '서울특별시 강동구 암사13길 30 ,(암사동 437-4) (암사제1동)', '02', '426', '5882', 2)
2021-08-18 17:41:07,089 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,090 INFO sqlalchemy.engine.base.Engine ('구립 신목장애아어린이집', '안예준', '서울특별시 양천구 목동동로12길 59 ,(목동) (목1동)', '02', '2643', '6554', 19)
2021-08-18 17:41:07,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,091 INFO sqlalchemy.engine.base.Engine ('구립번2동어린이집', '신준혁', '서울특별시 강북구 덕릉로40길 48 ,(번동) (번2동)', '02', '981', '8550', 3)
2021-08-18 17:41:07,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,093 INFO sqlalchemy.engine.base.Engine ('방아골어린이집', '류영자', '서울특별시 도봉구 시루봉로17길 42 ,방아골종합사회복지관 1층 (방학동) (방학제2동)', '02', '3491', '5560', 10)
2021-08-18 17:41:07,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,095 INFO sqlalchemy.engine.base.Engine ('태양어린이집', '강예준', '서울특별시 서대문구 북아현로4길 9-7 (북아현동)', '02', '363', '0167', 14)
2021-08-18 17:41:07,096 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,097 INFO sqlalchemy.engine.base.Engine ('꿈꾸는 어린이집', '강민지', '서울특별시 강북구 삼양로173가길 58 ,(우이동) (우이동)', '02', '995', '1802', 3)
2021-08-18 17:41:07,098 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,099 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '전영진', '서울특별시 중랑구 동일로126길 6 ,(중화동) (중화제1동)', '02', '438', '5678', 25)
2021-08-18 17:41:07,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,101 INFO sqlalchemy.engine.base.Engine ('예쁜새싹어린이집', '정순자', '서울특별시 중랑구 면목로44라길 12 ,(면목동) (면목제3.8동)', '02', '433', '1539', 25)
2021-08-18 17:41:07,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,102 INFO sqlalchemy.engine.base.Engine ('신나는꼬마숲어린이집', '한지은', '서울특별시 송파구 송파대로32길 15 ,104동 104호(가락동, 금호아파트) (가락본동)', '02', '403', '9631', 18)
2021-08-18 17:41:07,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,104 INFO sqlalchemy.engine.base.Engine ('꼬맹이어린이집', '안정운', '서울특별시 도봉구 마들로 684-19 ,110동 101호(도봉동, 서원아파트) (도봉제2동)', '02', '3491', '3471', 10)
2021-08-18 17:41:07,105 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,105 INFO sqlalchemy.engine.base.Engine ('산들어린이집', '안정순', '서울특별시 구로구 경인로35길 64-12 (개봉제1동)', '02', '2611', '7306', 7)
2021-08-18 17:41:07,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,107 INFO sqlalchemy.engine.base.Engine ('상계2동어린이집', '권성진', '서울특별시 노원구 상계로3길 38-17 (상계2동)', '02', '939', '3696', 9)
2021-08-18 17:41:07,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,109 INFO sqlalchemy.engine.base.Engine ('서울성모병원어린이집', '송정수', '서울특별시 서초구 반포대로 222 ,강남성모병원 내 별관 2층 어린이집 (반포동) (반포4동)', '02', '2258', '8180', 15)
2021-08-18 17:41:07,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,111 INFO sqlalchemy.engine.base.Engine ('장위1동어린이집', '한순자', '서울특별시 성북구 월계로32길 15 ,(장위동) (장위제1동)', '02', '909', '3638', 17)
2021-08-18 17:41:07,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,112 INFO sqlalchemy.engine.base.Engine ('초록어린이집', '전은정', '서울특별시 강서구 까치산로12길 8-9 ,(화곡동) (화곡본동)', '02', '2607', '0359', 4)
2021-08-18 17:41:07,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,116 INFO sqlalchemy.engine.base.Engine ('부암어린이집', '김지훈', '서울특별시 종로구 세검정로6다길 10-7 (부암동)', '02', '396', '6226', 23)
2021-08-18 17:41:07,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,119 INFO sqlalchemy.engine.base.Engine ('거원아트어린이집', '조영진', '서울특별시 송파구 양산로8길 23 (거여2동)', '02', '404', '5109', 18)
2021-08-18 17:41:07,120 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,124 INFO sqlalchemy.engine.base.Engine ('비룡어린이집', '윤지훈', '서울특별시 구로구 고척로33길 43 ,(1~4층) (고척제2동)', '02', '2619', '9933', 7)
2021-08-18 17:41:07,127 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,128 INFO sqlalchemy.engine.base.Engine ('한양키즈어린이집', '이민지', '서울특별시 구로구 구일로2길 60 ,(구로동, 구일우성아파트 관리동) (구로제1동)', '02', '867', '2425', 7)
2021-08-18 17:41:07,129 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,129 INFO sqlalchemy.engine.base.Engine ('건강한현대어린이집', '한준호', '서울특별시 영등포구 도신로 31 ,현대아파트 관리동 (대림제3동)', '02', '836', '0073', 20)
2021-08-18 17:41:07,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,131 INFO sqlalchemy.engine.base.Engine ('구립 단비어린이집', '조동현', '서울특별시 성동구 용답중앙길 49 ,(용답동) (용답동)', '02', '2249', '3215', 16)
2021-08-18 17:41:07,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,134 INFO sqlalchemy.engine.base.Engine ('청호어린이집', '이서연', '서울특별시 동작구 서달로2길 29 ,103동(흑석동, 청호아파트) (흑석동)', '02', '826', '1076', 12)
2021-08-18 17:41:07,136 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,137 INFO sqlalchemy.engine.base.Engine ('하나어린이집', '윤미경', '서울특별시 동작구 남부순환로257가길 22 ,(사당동) (사당제1동)', '02', '3471', '6593', 12)
2021-08-18 17:41:07,138 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,141 INFO sqlalchemy.engine.base.Engine ('딩동댕장미어린이집', '전은영', '서울특별시 송파구 올림픽로35길 104 ,18동 107(신천동, 장미아파트) (잠실6동)', '02', '418', '6813', 18)
2021-08-18 17:41:07,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,143 INFO sqlalchemy.engine.base.Engine ('까치산어린이집', '송정자', '서울특별시 강서구 강서로12길 29-10 (화곡제8동)', '02', '2699', '2181', 4)
2021-08-18 17:41:07,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,145 INFO sqlalchemy.engine.base.Engine ('솔로몬어린이집', '임지훈', '서울특별시 광진구 긴고랑로7길 73 ,(중곡동) (중곡제3동)', '02', '469', '9976', 6)
2021-08-18 17:41:07,146 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,147 INFO sqlalchemy.engine.base.Engine ('쌍문삼성어린이집', '조미경', '서울특별시 도봉구 노해로 238 ,쌍문삼성어린이집 (쌍문동) (쌍문제3동)', '02', '994', '2476', 10)
2021-08-18 17:41:07,148 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,148 INFO sqlalchemy.engine.base.Engine ('예쁜튼튼어린이집', '송현준', '서울특별시 구로구 구로중앙로26가길 11-5 ,(구로동) (구로제5동)', '02', '838', '8850', 7)
2021-08-18 17:41:07,150 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,150 INFO sqlalchemy.engine.base.Engine ('성결어린이집', '박수빈', '서울특별시 양천구 월정로19길 11 ,(신월동) (신월1동)', '02', '2695', '4050', 19)
2021-08-18 17:41:07,151 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,153 INFO sqlalchemy.engine.base.Engine ('세신어린이집', '김영진', '서울특별시 양천구 목동동로 75 ,세신교회 (신정동) (신정6동)', '02', '2649', '6204', 19)
2021-08-18 17:41:07,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,156 INFO sqlalchemy.engine.base.Engine ('서초연꽃어린이집', '안준영', '서울특별시 서초구 사임당로19길 51 ,(서초동) (서초1동)', '02', '521', '1750', 15)
2021-08-18 17:41:07,158 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,159 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '윤영길', '서울특별시 노원구 노원로1길 85-10 (공릉2동)', '02', '949', '0570', 9)
2021-08-18 17:41:07,160 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,160 INFO sqlalchemy.engine.base.Engine ('구립새들어린이집', '한정웅', '서울특별시 관악구 관천로16길 55 ,(신림동) [신림동] (신림동)', '02', '888', '2601', 5)
2021-08-18 17:41:07,162 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,162 INFO sqlalchemy.engine.base.Engine ('슈가베이비어린이집', '이정순', '서울특별시 노원구 동일로213길 21 ,106동 102호(상계동, 상계주공1차) (상계6.7동)', '02', '932', '3625', 9)
2021-08-18 17:41:07,163 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,164 INFO sqlalchemy.engine.base.Engine ('연희어린이집', '최성수', '서울특별시 서대문구 가좌로 16-16 (연희동)', '02', '333', '0406', 14)
2021-08-18 17:41:07,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,166 INFO sqlalchemy.engine.base.Engine ('중앙어린이집', '송준혁', '서울특별시 광진구 자양로13다길 31 ,(자양동) (자양제1동)', '02', '446', '9066', 6)
2021-08-18 17:41:07,167 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,168 INFO sqlalchemy.engine.base.Engine ('금성어린이집', '정예은', '서울특별시 중랑구 상봉로12길 44 ,(망우동) (망우제3동)', '02', '492', '2808', 25)
2021-08-18 17:41:07,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,170 INFO sqlalchemy.engine.base.Engine ('한국중앙어린이집', '송서연', '서울특별시 광진구 능동로 447 ,(중곡동) (중곡제3동)', '02', '467', '6824', 6)
2021-08-18 17:41:07,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,173 INFO sqlalchemy.engine.base.Engine ('푸른어린이집', '임준혁', '서울특별시 관악구 낙성대로3길 15 ,(봉천동) [낙성대동] (낙성대동)', '02', '877', '3486', 5)
2021-08-18 17:41:07,175 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,176 INFO sqlalchemy.engine.base.Engine ('예닮어린이집', '전성민', '서울특별시 양천구 가로공원로60길 17 ,(신월동) (신월3동)', '02', '2696', '7770', 19)
2021-08-18 17:41:07,177 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,178 INFO sqlalchemy.engine.base.Engine ('구립큰나무어린이집', '류현준', '서울특별시 동작구 사당로2가길 219 ,(사당동) (사당제5동)', '02', '585', '0700', 12)
2021-08-18 17:41:07,179 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,181 INFO sqlalchemy.engine.base.Engine ('성모어린이집', '송혜진', '서울특별시 영등포구 63로 10 (여의동)', '02', '3779', '1970', 20)
2021-08-18 17:41:07,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,183 INFO sqlalchemy.engine.base.Engine ('바우솔어린이집', '최수빈', '서울특별시 구로구 구로동로25길 33-10 (구로제2동)', '02', '856', '1101', 7)
2021-08-18 17:41:07,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,185 INFO sqlalchemy.engine.base.Engine ('구립백로어린이집', '박정웅', '서울특별시 동작구 장승배기로19라길 51 ,(상도동) (상도제2동)', '02', '816', '1031', 12)
2021-08-18 17:41:07,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,188 INFO sqlalchemy.engine.base.Engine ('두발로어린이집', '정정수', '서울특별시 도봉구 덕릉로62길 25 ,(창동) (창제3동)', '02', '999', '2855', 10)
2021-08-18 17:41:07,190 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,190 INFO sqlalchemy.engine.base.Engine ('청솔어린이집', '장경회', '서울특별시 성북구 돌곶이로14길 30 ,(석관동) (석관동)', '02', '957', '3702', 17)
2021-08-18 17:41:07,191 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,192 INFO sqlalchemy.engine.base.Engine ('한신또래어린이집', '권영진', '서울특별시 영등포구 양평로24길 9 ,105동 101호(양평동5가, 한신아파트) (양평제2동)', '02', '2634', '0993', 20)
2021-08-18 17:41:07,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,195 INFO sqlalchemy.engine.base.Engine ('서초한별어린이집', '한은영', '서울특별시 서초구 마방로2길 15-9 (양재2동)', '02', '579', '1850', 15)
2021-08-18 17:41:07,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,197 INFO sqlalchemy.engine.base.Engine ('성분도어린이집', '장정웅', '서울특별시 서초구 방배로 40 ,. (방배3동)', '02', '522', '0290', 15)
2021-08-18 17:41:07,198 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,199 INFO sqlalchemy.engine.base.Engine ('푸른솔어린이집', '조민수', '서울특별시 관악구 낙성대역길 67 ,1,2층 (봉천동) [인헌동] (인헌동)', '02', '871', '1215', 5)
2021-08-18 17:41:07,201 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,202 INFO sqlalchemy.engine.base.Engine ('동서울어린이집', '황민지', '서울특별시 광진구 광나루로44길 23 ,(구의동) (구의제3동)', '02', '456', '7295', 6)

2021-08-18 17:41:07,203 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,204 INFO sqlalchemy.engine.base.Engine ('영락교회어린이집', '신정수', '서울특별시 중구 수표로 33 ,(저동2가) (을지로동)', '02', '2266', '5878', 24)
2021-08-18 17:41:07,206 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,207 INFO sqlalchemy.engine.base.Engine ('서문교회부설어린이집', '조미영', '서울특별시 은평구 가좌로10길 10 ,(응암동) (응암제3동)', '02', '309', '7983', 22)
2021-08-18 17:41:07,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,208 INFO sqlalchemy.engine.base.Engine ('구립 연꽃어린이집', '이상철', '서울특별시 성동구 한림말길 16-5 (옥수동)', '02', '2282', '1105', 16)
2021-08-18 17:41:07,209 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,210 INFO sqlalchemy.engine.base.Engine ('성아어린이집', '한정수', '서울특별시 강남구 논현로32길 16 ,성아어린이집 (도곡동) (도곡제2동)', '02', '575', '8323', 1)
2021-08-18 17:41:07,211 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,212 INFO sqlalchemy.engine.base.Engine ('온터어린이집', '오경자', '서울특별시 성북구 솔샘로5길 92 (정릉제3동)', '02', '917', '1506', 17)
2021-08-18 17:41:07,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,213 INFO sqlalchemy.engine.base.Engine ('밤비어린이집', '장영철', '서울특별시 성북구 화랑로48길 16 ,107동 104호(석관동, 두산아파트) (석관동)', '02', '957', '8035', 17)
2021-08-18 17:41:07,214 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,215 INFO sqlalchemy.engine.base.Engine ('뉴솔로몬어린이집', '한지혜', '서울특별시 중랑구 용마공원로5길 15 ,(망우동) (망우본동)', '02', '495', '0101', 25)
2021-08-18 17:41:07,216 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,217 INFO sqlalchemy.engine.base.Engine ('그린어린이집', '김예준', '서울특별시 동대문구 망우로20가길 34-6 (휘경제2동)', '02', '2213', '7273', 11)
2021-08-18 17:41:07,218 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,218 INFO sqlalchemy.engine.base.Engine ('꿈동산 어린이집', '최건우', '서울특별시 금천구 독산로 106 ,(시흥동) (시흥제4동)', '02', '896', '5588', 8)
2021-08-18 17:41:07,219 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,220 INFO sqlalchemy.engine.base.Engine ('숭인어린이집', '류준혁', '서울특별시 종로구 지봉로 86 ,(숭인동) (숭인제1동)', '02', '743', '7527', 23)
2021-08-18 17:41:07,221 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,222 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '이은경', '서울특별시 강동구 양재대로123길 30 ,102동 107호(천호동, 강동이루미아파트) (천호제1동)', '02', '476', '7934', 2)
2021-08-18 17:41:07,223 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,224 INFO sqlalchemy.engine.base.Engine ('피터팬어린이집', '한상철', '서울특별시 강동구 구천면로64길 6 ,2층 (천호동 18-47호 2층) (천호제1동)', '02', '483', '7259', 2)
2021-08-18 17:41:07,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,226 INFO sqlalchemy.engine.base.Engine ('한우리어린이집', '송미영', '서울특별시 금천구 독산로50길 57 ,(시흥동) (시흥제4동)', '02', '804', '7725', 8)
2021-08-18 17:41:07,229 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,230 INFO sqlalchemy.engine.base.Engine ('꿈담어린이집', '류민석', '서울특별시 노원구 노원로 564 ,1010동 106호(상계동, 상계주공10단지아파트) (상계8동)', '02', '939', '9361', 9)
2021-08-18 17:41:07,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,233 INFO sqlalchemy.engine.base.Engine ('온터방과후교실어린이집', '황서연', '서울특별시 관악구 신림로23길 17 ,(대학동) (신림동) (대학동)', '02', '876', '6187', 5)
2021-08-18 17:41:07,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,234 INFO sqlalchemy.engine.base.Engine ('서울대학교어린이보육지원센터 백학어린이집', '오정운', '서울특별시 관악구 관악로 1 ,(봉천동) [낙성대동] (낙성대동)', '02', '880', '5767', 5)
2021-08-18 17:41:07,236 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,237 INFO sqlalchemy.engine.base.Engine ('아이다솜어린이집', '송영철', '서울특별시 중랑구 용마산로 348 ,,105동102호(면목동, 용마금호타운아파트) (면목제3.8동)', '02', '492', '4808', 25)
2021-08-18 17:41:07,238 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,238 INFO sqlalchemy.engine.base.Engine ('참고은어린이집', '송정자', '서울특별시 영등포구 도림로47길 18-1 ,(대림동) (대림제3동)', '02', '849', '3747', 20)
2021-08-18 17:41:07,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,240 INFO sqlalchemy.engine.base.Engine ('청운어린이집', '윤영숙', '서울특별시 용산구 효창원로94길 23 ,(청파동1가) (청파동)', '02', '715', '1657', 21)
2021-08-18 17:41:07,240 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,241 INFO sqlalchemy.engine.base.Engine ('구립은하어린이집', '임은정', '서울특별시 동작구 여의대방로22아길 77 (신대방제2동)', '02', '821', '0421', 12)
2021-08-18 17:41:07,242 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,243 INFO sqlalchemy.engine.base.Engine ('사랑나무 어린이집', '강영진', '서울특별시 성북구 오패산로3길 17 ,103동 103호(하월곡동, 동신아파트) (월곡제2동)', '02', '942', '0179', 17)
2021-08-18 17:41:07,244 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,245 INFO sqlalchemy.engine.base.Engine ('송파구청어린이집', '황지민', '서울특별시 송파구 올림픽로 326 ,(신천동) (잠실6동)', '02', '2147', '4268', 18)
2021-08-18 17:41:07,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,247 INFO sqlalchemy.engine.base.Engine ('종로구청직장어린이집', '송정운', '서울특별시 종로구 종로1길 36 ,대림빌딩 (종로1.2.3.4가동)', '02', '720', '5852', 23)
2021-08-18 17:41:07,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,248 INFO sqlalchemy.engine.base.Engine ('행화어린이집', '강민서', '서울특별시 마포구 마포대로 195 ,아현동, 마포래미안푸르지오 2단지 어린이집 (아현동)', '02', '393', '0409', 13)
2021-08-18 17:41:07,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,250 INFO sqlalchemy.engine.base.Engine ('까리따스어린이집', '류지영', '서울특별시 서초구 남부순환로 2124 ,(방배동) (방배2동)', '02', '581', '9004', 15)

2021-08-18 17:41:07,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,252 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '안성호', '서울특별시 송파구 양산로2길 38 ,거여6단지아파트 관리사무소 1층 조은어린이집 (거여동) (거여2동)', '02', '430', '5765', 18)
2021-08-18 17:41:07,253 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,254 INFO sqlalchemy.engine.base.Engine ('샘물퐁퐁어린이집', '조진호', '서울특별시 은평구 불광로 137-13 ,(불광동) (불광제1동)', '02', '358', '8005', 22)
2021-08-18 17:41:07,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,256 INFO sqlalchemy.engine.base.Engine ('수성어린이집', '임은정', '서울특별시 은평구 갈현로33가길 24-1 (갈현제1동)', '02', '353', '6076', 22)
2021-08-18 17:41:07,258 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,258 INFO sqlalchemy.engine.base.Engine ('신예랑어린이집', '김혜진', '서울특별시 영등포구 도신로54길 12-4 (신길제1동)', '02', '844', '1999', 20)
2021-08-18 17:41:07,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,260 INFO sqlalchemy.engine.base.Engine ('느티나무어린이집', '서현정', '서울특별시 광진구 광나루로26길 39 ,(화양동) (화양동)', '02', '444', '2544', 6)
2021-08-18 17:41:07,262 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,262 INFO sqlalchemy.engine.base.Engine ('효지어린이집', '장지혜', '서울특별시 광진구 아차산로36길 55 ,(자양동) (자양제3동)', '02', '2201', '0558', 6)
2021-08-18 17:41:07,263 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,264 INFO sqlalchemy.engine.base.Engine ('또래어린이집', '윤예준', '서울특별시 서초구 신반포로33길 15 ,101동 105호(잠원동, 동아아파트) (반포3동)', '02', '536', '3563', 15)
2021-08-18 17:41:07,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,266 INFO sqlalchemy.engine.base.Engine ('사랑의어린이집', '이수빈', '서울특별시 서초구 신반포로33길 22 (반포3동)', '02', '3477', '9818', 15)
2021-08-18 17:41:07,267 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,268 INFO sqlalchemy.engine.base.Engine ('킹스키즈어린이집', '조종수', '서울특별시 강남구 도곡로73길 31-1 (대치제4동)', '02', '3453', '1997', 1)
2021-08-18 17:41:07,269 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,270 INFO sqlalchemy.engine.base.Engine ('구립 도담어린이집', '조정자', '서울특별시 양천구 목동중앙북로8길 104 ,(목동) (목2동)', '02', '2651', '4415', 19)
2021-08-18 17:41:07,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,272 INFO sqlalchemy.engine.base.Engine ('당곡1어린이집', '오지혜', '서울특별시 관악구 당곡2가길 11 ,당곡1어린이집 [보라매동] (봉천동) (보라매동)', '02', '882', '1237', 5)
2021-08-18 17:41:07,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,274 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '전상훈', '서울특별시 강북구 삼양로85길 4 ,(수유동) (수유1동)', '02', '996', '1538', 3)
2021-08-18 17:41:07,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,276 INFO sqlalchemy.engine.base.Engine ('동심어린이집', '서준호', '서울특별시 강북구 솔샘로65길 39 ,(미아동) (송천동)', '02', '987', '5517', 3)
2021-08-18 17:41:07,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,277 INFO sqlalchemy.engine.base.Engine ('길동새순어린이집', '김영자', '서울특별시 강동구 명일로12길 56 ,101동 102호(둔촌동, 성원아파트) (둔촌제2동)', '02', '483', '8663', 2)
2021-08-18 17:41:07,278 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,279 INFO sqlalchemy.engine.base.Engine ('구립 은행정어린이집', '전민지', '서울특별시 양천구 중앙로46길 57 ,(신정동) (신정4동)', '02', '2608', '0406', 19)
2021-08-18 17:41:07,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,281 INFO sqlalchemy.engine.base.Engine ('아이세상어린이집', '서정자', '서울특별시 강서구 허준로 23 ,105동 106호(가양동, 한강타운아파트) (가양제1동)', '02', '2659', '2431', 4)
2021-08-18 17:41:07,282 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,283 INFO sqlalchemy.engine.base.Engine ('옥토어린이집', '황혜진', '서울특별시 송파구 양산로8길 4 ,106동 118호(거여동, 거여1단지) (거여2동)', '02', '448', '5937', 18)
2021-08-18 17:41:07,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,286 INFO sqlalchemy.engine.base.Engine ('새솔어린이집', '류종수', '서울특별시 구로구 공원로 35 ,(구로5동 108-2 새솔금호아파트내 1층) (구로제5동)', '02', '857', '3431', 7)
2021-08-18 17:41:07,287 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,288 INFO sqlalchemy.engine.base.Engine ('아람마주이야기어린이집', '안지훈', '서울특별시 서초구 동광로12길 12 ,(방배동) (방배4동)', '02', '591', '9777', 15)
2021-08-18 17:41:07,289 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,290 INFO sqlalchemy.engine.base.Engine ('고우리어린이집', '정민재', '서울특별시 강동구 고덕로10길 16 (암사제1동)', '02', '428', '9350', 2)
2021-08-18 17:41:07,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,291 INFO sqlalchemy.engine.base.Engine ('논현어린이집', '한건우', '서울특별시 강남구 강남대로124길 65 ,(논현동) (논현제1동)', '02', '515', '6572', 1)
2021-08-18 17:41:07,292 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,293 INFO sqlalchemy.engine.base.Engine ('아기둥지어린이집', '권민지', '서울특별시 강서구 허준로 23 ,109동 103호(가양동, 한강타운아파트) (가양제1동)', '02', '2642', '6318', 4)
2021-08-18 17:41:07,293 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,294 INFO sqlalchemy.engine.base.Engine ('무지개어린이집', '전은경', '서울특별시 서대문구 북아현로14길 7 ,(북아현동) (충현동)', '02', '364', '8965', 14)
2021-08-18 17:41:07,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,296 INFO sqlalchemy.engine.base.Engine ('본향선교어린이집', '강지은', '서울특별시 도봉구 덕릉로54길 41 ,(창동) (창제3동)', '02', '996', '9423', 10)
2021-08-18 17:41:07,296 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,297 INFO sqlalchemy.engine.base.Engine ('하람어린이집', '김정웅', '서울특별시 서대문구 가재울로 36 ,(남가좌동) (남가좌제2동)', '02', '308', '8370', 14)

2021-08-18 17:41:07,299 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,300 INFO sqlalchemy.engine.base.Engine ('대흥어린이집', '박영일', '서울특별시 마포구 백범로 79 (대흥동)', '02', '3273', '7859', 13)
2021-08-18 17:41:07,301 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,302 INFO sqlalchemy.engine.base.Engine ('리틀코끼리어린이집', '류경자', '서울특별시 양천구 목동로21길 30 ,(신정동) (신정4동)', '02', '2607', '3757', 19)
2021-08-18 17:41:07,303 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,304 INFO sqlalchemy.engine.base.Engine ('스머프어린이집', '장영자', '서울특별시 중랑구 면목로66길 57 ,(면목동) (면목본동)', '02', '2209', '7546', 25)
2021-08-18 17:41:07,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,306 INFO sqlalchemy.engine.base.Engine ('신이화어린이집', '조민지', '서울특별시 영등포구 문래동5가 선유로3길 23 (문래동)', '02', '2637', '5881', 20)
2021-08-18 17:41:07,306 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,307 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '임예은', '서울특별시 성북구 삼양로2길 55 ,(길음동) (길음제2동)', '02', '982', '8363', 17)
2021-08-18 17:41:07,309 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,310 INFO sqlalchemy.engine.base.Engine ('구립성내삼어린이집', '한민재', '서울특별시 강동구 강동대로51길 28-1 ,(성내3동 446-30) (성내제3동)', '02', '470', '2433', 2)
2021-08-18 17:41:07,311 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,312 INFO sqlalchemy.engine.base.Engine ('예담어린이집', '임성호', '서울특별시 중랑구 중랑천로 20 ,3동 101호(면목동, 한신아파트) (면목제2동)', '02', '436', '9125', 25)
2021-08-18 17:41:07,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,319 INFO sqlalchemy.engine.base.Engine ('선우어린이집', '권광수', '서울특별시 강남구 도곡로18길 9 ,(도곡동) (도곡제1동)', '02', '578', '6878', 1)
2021-08-18 17:41:07,320 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,321 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '전예은', '서울특별시 마포구 마포대로 195 ,, 404동 103호(아현동, 마포래미안푸르지오아파트) (아현동)', '02', '313', '3636', 13)
2021-08-18 17:41:07,323 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,324 INFO sqlalchemy.engine.base.Engine ('일광어린이집', '서준영', '서울특별시 금천구 독산로35가길 8 ,(시흥동) (시흥제1동)', '02', '806', '3349', 8)
2021-08-18 17:41:07,325 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,325 INFO sqlalchemy.engine.base.Engine ('서울영재어린이집', '권지민', '서울특별시 구로구 오류로8길 151-1 (오류제2동)', '02', '2613', '8926', 7)
2021-08-18 17:41:07,327 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,328 INFO sqlalchemy.engine.base.Engine ('리틀몬테소리어린이집', '전혜진', '서울특별시 구로구 새말로9길 22 ,101동 103호(구로동, 일신건영아파트) (구로제5동)', '02', '868', '4649', 7)
2021-08-18 17:41:07,330 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,331 INFO sqlalchemy.engine.base.Engine ('묵동제일어린이집', '정성호', '서울특별시 중랑구 동일로148가길 21 ,(묵동) (묵제1동)', '02', '974', '4997', 25)
2021-08-18 17:41:07,332 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,333 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '김영환', '서울특별시 은평구 백련산로2길 19 ,백련산힐스테이트 204동 105호 (응암제2동)', '02', '389', '9420', 22)
2021-08-18 17:41:07,334 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,335 INFO sqlalchemy.engine.base.Engine ('꿈터 어린이집', '최정운', '서울특별시 성동구 용답중앙길 89-2 (용답동)', '02', '2242', '2989', 16)
2021-08-18 17:41:07,336 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,337 INFO sqlalchemy.engine.base.Engine ('개나리동산어린이집', '안정식', '서울특별시 성동구 둘레5길 14-1 (성수1가제1동)', '02', '469', '1325', 16)
2021-08-18 17:41:07,338 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,339 INFO sqlalchemy.engine.base.Engine ('소리나는어린이집', '조민서', '서울특별시 은평구 갈현로29길 51-15 ,은평공동육아협동조합 소리나는 어린이집 (갈현동) (갈현제2동)', '02', '358', '7725', 22)
2021-08-18 17:41:07,340 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,341 INFO sqlalchemy.engine.base.Engine ('은현어린이집', '장유진', '서울특별시 은평구 갈현로43길 9 ,(갈현동) (갈현제1동)', '02', '359', '0671', 22)
2021-08-18 17:41:07,342 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,342 INFO sqlalchemy.engine.base.Engine ('돌마리어린이집', '류정호', '서울특별시 송파구 백제고분로40길 13-16 ,돌마리어린이집 2층 (석촌동) (석촌동)', '02', '3431', '8535', 18)
2021-08-18 17:41:07,343 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,344 INFO sqlalchemy.engine.base.Engine ('꾸러기어린이집', '류예준', '서울특별시 금천구 가산로 34-7 ,2층 (독산동) (독산제3동)', '02', '3281', '7200', 8)
2021-08-18 17:41:07,345 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,346 INFO sqlalchemy.engine.base.Engine ('양문어린이집', '이병철', '서울특별시 양천구 신월로 109 ,(신월동) (신월7동)', '02', '2603', '3548', 19)
2021-08-18 17:41:07,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,348 INFO sqlalchemy.engine.base.Engine ('꼬예미키즈어린이집', '오지훈', '서울특별시 송파구 오금로36길 37 ,(가락동) (가락본동)', '02', '448', '4481', 18)
2021-08-18 17:41:07,348 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,349 INFO sqlalchemy.engine.base.Engine ('명성어린이집', '임지혜', '서울특별시 광진구 아차산로55길 59 ,(구의동) (구의제1동)', '02', '2201', '9696', 6)
2021-08-18 17:41:07,350 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,351 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '황지원', '서울특별시 강동구 천중로53길 19 ,(길동 341-26) (길동)', '02', '472', '2433', 2)
2021-08-18 17:41:07,352 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,353 INFO sqlalchemy.engine.base.Engine ('영암어린이집', '김상훈', '서울특별시 성북구 정릉로 402-12 (돈암제1동)', '02', '922', '0600', 17)

2021-08-18 17:41:07,355 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,360 INFO sqlalchemy.engine.base.Engine ('새문안어린이집', '박현정', '서울특별시 종로구 삼청로5길 22 (삼청동)', '02', '733', '9194', 23)
2021-08-18 17:41:07,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,363 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '신민재', '서울특별시 강서구 강서로13길 28 ,(화곡동) (화곡제1동)', '02', '2697', '6733', 4)
2021-08-18 17:41:07,366 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,367 INFO sqlalchemy.engine.base.Engine ('또래미키어린이집', '윤영진', '서울특별시 양천구 곰달래로2길 16 ,성원아파트 111호 (신월1동)', '02', '2692', '0047', 19)
2021-08-18 17:41:07,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,370 INFO sqlalchemy.engine.base.Engine ('예전몬테소리어린이집', '송정수', '서울특별시 마포구 서강로5길 16-19 (서강동)', '02', '337', '0385', 13)
2021-08-18 17:41:07,373 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,373 INFO sqlalchemy.engine.base.Engine ('이솝어린이집', '서지원', '서울특별시 송파구 동남로9길 31 ,(가락동) (가락2동)', '02', '406', '3322', 18)
2021-08-18 17:41:07,375 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,376 INFO sqlalchemy.engine.base.Engine ('파랑어린이집', '권정운', '서울특별시 영등포구 도신로29길 28 ,103동 104호(영등포동, 영등포푸르지오1단지아파트) (영등포본동)', '02', '849', '7893', 20)
2021-08-18 17:41:07,378 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,378 INFO sqlalchemy.engine.base.Engine ('아띠랑어린이집', '최미숙', '서울특별시 중랑구 동일로169길 41 ,102동 101호(묵동, 동구햇살아파트) (묵제2동)', '02', '2209', '7717', 25)
2021-08-18 17:41:07,380 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,380 INFO sqlalchemy.engine.base.Engine ('구립 한솔어린이집', '장예준', '서울특별시 성동구 왕십리로16길 12-21 (성수1가제2동)', '02', '462', '4691', 16)
2021-08-18 17:41:07,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,383 INFO sqlalchemy.engine.base.Engine ('둘리어린이집', '김정호', '서울특별시 중랑구 신내로 127 ,신내아파트관리사무소1층 (신내2동)', '02', '3421', '9514', 25)
2021-08-18 17:41:07,384 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,385 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '정경회', '서울특별시 성동구 마장로27가길 15 (마장동)', '02', '2292', '8800', 16)
2021-08-18 17:41:07,386 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,387 INFO sqlalchemy.engine.base.Engine ('구립성내일어린이집', '임정호', '서울특별시 강동구 풍성로42길 20 ,(성내동 521-7) (성내제1동)', '02', '483', '3732', 2)
2021-08-18 17:41:07,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,391 INFO sqlalchemy.engine.base.Engine ('다솔창의어린이집', '최종수', '서울특별시 동대문구 휘경로 45 (휘경제1동)', '02', '960', '4281', 11)
2021-08-18 17:41:07,392 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,393 INFO sqlalchemy.engine.base.Engine ('미래연 어린이집', '송영철', '서울특별시 동작구 사당로16길 82 ,(사당동) (사당제4동)', '02', '521', '2662', 12)
2021-08-18 17:41:07,394 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,394 INFO sqlalchemy.engine.base.Engine ('아이들세상어린이집', '정준영', '서울특별시 도봉구 방학로 193 ,10동 106호(방학동, 신동아1차아파트) (방학제3동)', '02', '3493', '0800', 10)
2021-08-18 17:41:07,395 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,396 INFO sqlalchemy.engine.base.Engine ('가산중앙어린이집', '정준영', '서울특별시 금천구 시흥대로145길 79 ,가산동 (가산동)', '02', '868', '4939', 8)
2021-08-18 17:41:07,397 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,398 INFO sqlalchemy.engine.base.Engine ('동성어린이집', '서미영', '서울특별시 강서구 화곡로18길 39 ,(화곡동) (화곡제1동)', '02', '2605', '4176', 4)
2021-08-18 17:41:07,399 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,400 INFO sqlalchemy.engine.base.Engine ('행복한삐아제어린이집', '조민서', '서울특별시 양천구 중앙로29길 55 ,(신월동) (신월6동)', '02', '2606', '7775', 19)
2021-08-18 17:41:07,402 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,403 INFO sqlalchemy.engine.base.Engine ('삼익리틀어린이집', '박순자', '서울특별시 노원구 공릉로46길 28 ,103동 106호(공릉동, 삼익) (공릉2동)', '02', '949', '1604', 9)
2021-08-18 17:41:07,404 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,405 INFO sqlalchemy.engine.base.Engine ('구립우이동어린이집', '권경숙', '서울특별시 강북구 삼양로159가길 7 ,(우이동) (우이동)', '02', '990', '5666', 3)
2021-08-18 17:41:07,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,408 INFO sqlalchemy.engine.base.Engine ('노원구청직장어린이집', '전진호', '서울특별시 노원구 노해로 437 ,(상계동 노원구청직장어린이집) (상계6.7동)', '02', '3392', '1912', 9)
2021-08-18 17:41:07,409 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,410 INFO sqlalchemy.engine.base.Engine ('여명어린이집', '조영숙', '서울특별시 중랑구 동일로160길 49 ,(묵동) (묵제1동)', '02', '976', '2806', 25)
2021-08-18 17:41:07,411 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,412 INFO sqlalchemy.engine.base.Engine ('연화어린이집', '전종수', '서울특별시 강남구 학동로43길 17 (논현제2동)', '02', '542', '7765', 1)
2021-08-18 17:41:07,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,413 INFO sqlalchemy.engine.base.Engine ('창2동어린이집', '송민지', '서울특별시 도봉구 덕릉로59길 73-9 (창제2동)', '02', '999', '8886', 10)
2021-08-18 17:41:07,414 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,415 INFO sqlalchemy.engine.base.Engine ('청아어린이집', '황미숙', '서울특별시 도봉구 노해로69가길 11 ,4동(창동, 동아청솔아파트) (창제4동)', '02', '907', '3811', 10)
2021-08-18 17:41:07,416 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,417 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '강지훈', '서울특별시 양천구 신월로 226 ,(신월동) (신월2동)', '02', '2607', '9549', 19)
2021-08-18 17:41:07,418 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,419 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '이유진', '서울특별시 관악구 당곡2가길 29 ,1,2층 (봉천동) [보라매동] (보라매동)', '02', '872', '8856', 5)
2021-08-18 17:41:07,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,421 INFO sqlalchemy.engine.base.Engine ('서머힐어린이집', '장민수', '서울특별시 도봉구 우이천로 492 ,-1 (쌍문제1동)', '02', '995', '7037', 10)
2021-08-18 17:41:07,422 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,423 INFO sqlalchemy.engine.base.Engine ('중계1동어린이집', '장민서', '서울특별시 노원구 덕릉로 593 ,(중계동) (중계1동)', '02', '3391', '9413', 9)
2021-08-18 17:41:07,424 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,425 INFO sqlalchemy.engine.base.Engine ('은화어린이집', '장예준', '서울특별시 은평구 통일로89길 18-25 (갈현제1동)', '02', '352', '5513', 22)
2021-08-18 17:41:07,426 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,426 INFO sqlalchemy.engine.base.Engine ('성모자애어린이집', '전정수', '서울특별시 은평구 통일로78길 10 ,(불광동) (불광제1동)', '02', '354', '1400', 22)
2021-08-18 17:41:07,428 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,428 INFO sqlalchemy.engine.base.Engine ('참새어린이집', '윤은정', '서울특별시 중랑구 봉화산로 216 ,401동 106호(신내동, 동성아파트) (신내1동)', '02', '3421', '0925', 25)
2021-08-18 17:41:07,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,430 INFO sqlalchemy.engine.base.Engine ('한빛 어린이집', '최서연', '서울특별시 성동구 행당로 79 ,110동 102호(행당동, 대림아파트) (행당제2동)', '02', '2299', '1567', 16)
2021-08-18 17:41:07,431 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,432 INFO sqlalchemy.engine.base.Engine ('행복가득어린이집', '권미숙', '서울특별시 성동구 송정18가길 34 ,(송정동) (송정동)', '02', '498', '7383', 16)
2021-08-18 17:41:07,433 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,434 INFO sqlalchemy.engine.base.Engine ('예나몬테소리 어린이집', '서예은', '서울특별시 도봉구 노해로69길 103 ,110동 102호(창동, 동아청솔아파트) (창제4동)', '02', '997', '2555', 10)
2021-08-18 17:41:07,436 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,437 INFO sqlalchemy.engine.base.Engine ('오르다어린이집', '황경숙', '서울특별시 강남구 봉은사로73길 3-4 (삼성제2동)', '02', '546', '6855', 1)
2021-08-18 17:41:07,438 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,439 INFO sqlalchemy.engine.base.Engine ('헤세드어린이집', '전민지', '서울특별시 성동구 독서당로 375 ,(응봉동) (응봉동)', '02', '2292', '1191', 16)
2021-08-18 17:41:07,440 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,441 INFO sqlalchemy.engine.base.Engine ('강북솔로몬어린이집', '오성호', '서울특별시 강북구 삼양로47길 17-6 ,(미아동) (삼양동)', '02', '983', '5629', 3)
2021-08-18 17:41:07,442 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,442 INFO sqlalchemy.engine.base.Engine ('키즈용맹어린이집', '박종수', '서울특별시 광진구 긴고랑로 148 ,(중곡동) (중곡제4동)', '02', '453', '5210', 6)
2021-08-18 17:41:07,443 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,444 INFO sqlalchemy.engine.base.Engine ('리틀어린이집', '한경자', '서울특별시 구로구 고척로21나길 40 ,(1~3층) (개봉제1동)', '02', '2612', '4611', 7)
2021-08-18 17:41:07,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,446 INFO sqlalchemy.engine.base.Engine ('지암어린이집', '조영식', '서울특별시 구로구 개봉로11길 55-16 ,55-16, 55-14 (개봉제3동)', '02', '2686', '4755', 7)
2021-08-18 17:41:07,447 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,449 INFO sqlalchemy.engine.base.Engine ('구립탐구어린이집', '정영길', '서울특별시 강북구 오패산로 162 ,(미아동) (송중동)', '02', '989', '4646', 3)
2021-08-18 17:41:07,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,452 INFO sqlalchemy.engine.base.Engine ('중앙어린이집', '장동현', '서울특별시 마포구 망원로 84-5 ,중앙어린이집 (망원동) (망원제1동)', '02', '333', '0363', 13)
2021-08-18 17:41:07,454 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,455 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '조경회', '서울특별시 노원구 동일로 1456 ,707동 106호 (상계10동)', '02', '952', '3607', 9)
2021-08-18 17:41:07,456 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,456 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '오정자', '서울특별시 도봉구 도봉로151길 130 ,(방학동) (방학제2동)', '02', '3493', '4106', 10)
2021-08-18 17:41:07,457 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,458 INFO sqlalchemy.engine.base.Engine ('초원어린이집', '최정운', '서울특별시 중랑구 용마산로125나길 15 ,(신내동) (신내1동)', '02', '2209', '4546', 25)
2021-08-18 17:41:07,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,460 INFO sqlalchemy.engine.base.Engine ('바다어린이집', '권미영', '서울특별시 노원구 동일로208길 19 ,205동 107호(중계동, 무지개아파트) (중계2.3동)', '02', '948', '9514', 9)
2021-08-18 17:41:07,461 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,462 INFO sqlalchemy.engine.base.Engine ('까리타스어린이집', '이영식', '서울특별시 강북구 노해로 29 ,(수유동 10-3) (수유3동)', '02', '996', '1556', 3)
2021-08-18 17:41:07,464 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,464 INFO sqlalchemy.engine.base.Engine ('반야어린이집', '서상철', '서울특별시 구로구 경인로67길 133 ,(신도림동) (신도림동)', '02', '2631', '9792', 7)
2021-08-18 17:41:07,466 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,467 INFO sqlalchemy.engine.base.Engine ('영천어린이집', '김지혜', '서울특별시 성북구 장위로 34 ,지상1층 (장위동) (장위제1동)', '02', '941', '6779', 17)
2021-08-18 17:41:07,469 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,470 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '임건우', '서울특별시 강동구 성안로31마길 6 ,(천호동 186-7호) (천호제3동)', '02', '488', '5826', 2)
2021-08-18 17:41:07,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,472 INFO sqlalchemy.engine.base.Engine ('초망몬테소리어린이집', '윤진호', '서울특별시 강남구 봉은사로105길 24 ,(삼성동) (삼성제1동)', '02', '545', '2137', 1)
2021-08-18 17:41:07,474 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,475 INFO sqlalchemy.engine.base.Engine ('제일어린이집', '권영식', '서울특별시 강서구 곰달래로53길 80 ,(화곡동) (화곡제4동)', '02', '2654', '0300', 4)
2021-08-18 17:41:07,476 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,477 INFO sqlalchemy.engine.base.Engine ('품속어린이집', '류상철', '서울특별시 노원구 동일로230가길 16 ,(상계동) (상계1동)', '02', '952', '2770', 9)
2021-08-18 17:41:07,478 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,479 INFO sqlalchemy.engine.base.Engine ('애솔 어린이집', '권준호', '서울특별시 강남구 언주로 3 ,5동 106호(개포동, 우성6차아파트) (개포제4동)', '02', '573', '8533', 1)
2021-08-18 17:41:07,480 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,481 INFO sqlalchemy.engine.base.Engine ('참사랑어린이집', '송은영', '서울특별시 은평구 불광로 208 ,(불광동) 101동 107호 (불광제2동)', '02', '389', '4167', 22)
2021-08-18 17:41:07,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,484 INFO sqlalchemy.engine.base.Engine ('합정어린이집', '정준호', '서울특별시 마포구 양화진길 43 ,(합정동) (합정동)', '02', '338', '0922', 13)
2021-08-18 17:41:07,491 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,491 INFO sqlalchemy.engine.base.Engine ('하은어린이집', '한지훈', '서울특별시 노원구 동일로227길 26 ,1607동 106호(상계동, 상계주공16차) (상계8동)', '02', '937', '4819', 9)
2021-08-18 17:41:07,492 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,493 INFO sqlalchemy.engine.base.Engine ('구립복은어린이집', '신정자', '서울특별시 관악구 복은2길 6-24 ,(신림동) [서림동] (서림동)', '02', '877', '2246', 5)
2021-08-18 17:41:07,494 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,495 INFO sqlalchemy.engine.base.Engine ('영신어린이집', '황건우', '서울특별시 동대문구 답십리로 51 ,(전농동) (전농제1동)', '02', '2213', '0304', 11)
2021-08-18 17:41:07,496 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,497 INFO sqlalchemy.engine.base.Engine ('동성어린이집', '윤지은', '서울특별시 광진구 아차산로30길 25-10 ,(자양동) (자양제4동)', '02', '465', '8688', 6)
2021-08-18 17:41:07,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,499 INFO sqlalchemy.engine.base.Engine ('다정어린이집', '한영환', '서울특별시 노원구 한글비석로24바길 54 ,(상계동) (상계3.4동)', '02', '932', '5252', 9)
2021-08-18 17:41:07,500 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,501 INFO sqlalchemy.engine.base.Engine ('중계4동어린이집', '조영식', '서울특별시 노원구 덕릉로79길 23 ,105동(중계동, 염광아파트) (중계4동)', '02', '3391', '3303', 9)
2021-08-18 17:41:07,502 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,503 INFO sqlalchemy.engine.base.Engine ('중랑구청직장어린이집', '윤영철', '서울특별시 중랑구 봉화산로 179 ,(신내동, 중랑구청 1층) (신내2동)', '02', '3422', '3687', 25)
2021-08-18 17:41:07,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,505 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '임경자', '서울특별시 강동구 천중로39길 19-25 ,(천호동 54-17) (천호제3동)', '02', '489', '2432', 2)
2021-08-18 17:41:07,505 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,506 INFO sqlalchemy.engine.base.Engine ('돈암2동 어린이집', '황민지', '서울특별시 성북구 성북로4길 52 ,한진아파트 406동 (돈암동) (돈암제2동)', '02', '924', '6778', 17)
2021-08-18 17:41:07,507 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,508 INFO sqlalchemy.engine.base.Engine ('도만스쿨프라임어린이집', '류지은', '서울특별시 광진구 광나루로56길 5 ,2동 104호(구의동, 현대프라임아파트) (구의제3동)', '02', '453', '6060', 6)
2021-08-18 17:41:07,509 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,510 INFO sqlalchemy.engine.base.Engine ('솔로몬영재어린이집', '한건우', '서울특별시 강북구 삼양로77길 43-6 ,(수유동) (수유1동)', '02', '988', '9482', 3)
2021-08-18 17:41:07,511 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,511 INFO sqlalchemy.engine.base.Engine ('유림어린이집', '박영일', '서울특별시 강서구 곰달래로22길 35 ,유림어린이집 (화곡동) (화곡제1동)', '02', '2697', '6472', 4)
2021-08-18 17:41:07,512 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,513 INFO sqlalchemy.engine.base.Engine ('아이어린이집', '서민지', '서울특별시 중랑구 동일로157라길 12-20 (묵제2동)', '02', '976', '7571', 25)
2021-08-18 17:41:07,515 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,515 INFO sqlalchemy.engine.base.Engine ('데커어린이집', '김준혁', '서울특별시 광진구 뚝섬로52라길 39-3 ,(자양동) (자양제2동)', '02', '453', '1308', 6)
2021-08-18 17:41:07,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,517 INFO sqlalchemy.engine.base.Engine ('잠원꿈밭어린이집', '김성호', '서울특별시 서초구 강남대로95길 48-58 (잠원동)', '02', '514', '1953', 15)
2021-08-18 17:41:07,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,520 INFO sqlalchemy.engine.base.Engine ('여명어린이집', '강준호', '서울특별시 강남구 역삼로67길 11 ,(대치동) (대치제4동)', '02', '508', '2686', 1)
2021-08-18 17:41:07,526 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,527 INFO sqlalchemy.engine.base.Engine ('은마어린이집', '조성민', '서울특별시 강남구 삼성로 212 ,30동 114호(대치동, 은마아파트) (대치제2동)', '02', '555', '9659', 1)
2021-08-18 17:41:07,528 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,529 INFO sqlalchemy.engine.base.Engine ('짐랜드어린이집', '신상철', '서울특별시 노원구 공릉로62가길 30 ,인성빌딩2층 (하계동) (하계1동)', '02', '973', '6989', 9)
2021-08-18 17:41:07,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,530 INFO sqlalchemy.engine.base.Engine ('구립예담어린이집', '류정식', '서울특별시 동작구 매봉로 43 ,예담어린이집 (상도1동 511) (상도제1동)', '02', '815', '6893', 12)
2021-08-18 17:41:07,532 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,533 INFO sqlalchemy.engine.base.Engine ('구립율곡어린이집', '송현준', '서울특별시 강북구 오패산로52마길 8-4 (미아동)', '02', '984', '1977', 3)
2021-08-18 17:41:07,533 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,535 INFO sqlalchemy.engine.base.Engine ('자연어린이집', '임지영', '서울특별시 강북구 오현로28길 11 ,(번동) (번3동)', '02', '985', '0221', 3)
2021-08-18 17:41:07,536 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,537 INFO sqlalchemy.engine.base.Engine ('영재어린이집', '이영진', '서울특별시 중랑구 상봉로11길 44-7 ,(면목동) (면목본동)', '02', '2209', '1390', 25)
2021-08-18 17:41:07,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,539 INFO sqlalchemy.engine.base.Engine ('영재스쿨어린이집', '박정호', '서울특별시 중랑구 동일로 752 ,109동 102호(중화동, 중화한신아파트) (중화제1동)', '02', '491', '9170', 25)
2021-08-18 17:41:07,540 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,540 INFO sqlalchemy.engine.base.Engine ('쌍용어린이집', '박성호', '서울특별시 송파구 동남로 193 ,가락쌍용아파트관리동 (가락2동)', '02', '400', '3401', 18)
2021-08-18 17:41:07,541 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,542 INFO sqlalchemy.engine.base.Engine ('다온어린이집', '황유진', '서울특별시 도봉구 해등로 32 ,서울가든 아파트 상가 (창동) (창제1동)', '02', '999', '2900', 10)
2021-08-18 17:41:07,543 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,544 INFO sqlalchemy.engine.base.Engine ('아음어린이집', '정지은', '서울특별시 양천구 목동중앙북로16가길 10 ,(목동) (목2동)', '02', '2646', '1816', 19)
2021-08-18 17:41:07,545 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,546 INFO sqlalchemy.engine.base.Engine ('이태원삼성어린이집', '서경숙', '서울특별시 용산구 이태원로27길 34-30 (이태원제1동)', '02', '3785', '2478', 21)
2021-08-18 17:41:07,547 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,548 INFO sqlalchemy.engine.base.Engine ('다사랑어린이집', '강지영', '서울특별시 노원구 노원로 532 ,914동 106호(상계동, 주공아파트) (상계10동)', '02', '951', '8864', 9)
2021-08-18 17:41:07,549 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,549 INFO sqlalchemy.engine.base.Engine ('미소사랑어린이집', '조지은', '서울특별시 은평구 역말로 84-8 (역촌동)', '02', '386', '1340', 22)
2021-08-18 17:41:07,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,552 INFO sqlalchemy.engine.base.Engine ('꽃나래어린이집', '황서현', '서울특별시 도봉구 도봉로136길 28 ,512동 102호(창동, 북한산아이파크아파트) (창제5동)', '02', '908', '6768', 10)
2021-08-18 17:41:07,554 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,554 INFO sqlalchemy.engine.base.Engine ('반석어린이집', '이영진', '서울특별시 동대문구 답십리로58길 17 ,(답십리동) (답십리제2동)', '02', '2215', '0654', 11)
2021-08-18 17:41:07,555 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,556 INFO sqlalchemy.engine.base.Engine ('은지어린이집', '전은정', '서울특별시 영등포구 신풍로19가길 12-1 ,102호(신길동) (신길제6동)', '02', '848', '4833', 20)
2021-08-18 17:41:07,557 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,558 INFO sqlalchemy.engine.base.Engine ('일곱색깔어린이집', '권정웅', '서울특별시 성북구 장월로 31-1 ,(장위동) (장위제2동)', '02', '942', '0360', 17)
2021-08-18 17:41:07,559 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,559 INFO sqlalchemy.engine.base.Engine ('구립보라매어린이집', '박상철', '서울특별시 동작구 여의대방로22길 44 ,(신대방동) (신대방제2동)', '02', '826', '4503', 12)
2021-08-18 17:41:07,561 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,561 INFO sqlalchemy.engine.base.Engine ('구립상일어린이집', '송영식', '서울특별시 강동구 고덕로80길 41 ,구립상일어린이집 (상일제1동)', '02', '426', '3701', 2)
2021-08-18 17:41:07,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,563 INFO sqlalchemy.engine.base.Engine ('구립큰별어린이집', '오지영', '서울특별시 동작구 흑석한강로 28 ,구립큰별어린이집 (흑석동 336-1번지) (흑석동)', '02', '827', '0082', 12)
2021-08-18 17:41:07,563 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,564 INFO sqlalchemy.engine.base.Engine ('배봉어린이집', '최성민', '서울특별시 중랑구 신내로 115 ,(신내동) (신내2동)', '02', '3422', '1891', 25)
2021-08-18 17:41:07,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,566 INFO sqlalchemy.engine.base.Engine ('영등포구청직장어린이집', '윤준혁', '서울특별시 영등포구 당산동3가 선유동1로 80 ,영등포구청직장어린이집 (당산제1동)', '02', '2678', '1221', 20)
2021-08-18 17:41:07,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,568 INFO sqlalchemy.engine.base.Engine ('용곡어린이집', '박지훈', '서울특별시 광진구 능동로48길 64 ,(중곡동) 운형빌라 101호 (중곡제2동)', '02', '3437', '6676', 6)
2021-08-18 17:41:07,569 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,572 INFO sqlalchemy.engine.base.Engine ('서울아산병원어린이집', '이성수', '서울특별시 송파구 올림픽로43길 88 ,(풍납동) (풍납2동)', '02', '3010', '6902', 18)
2021-08-18 17:41:07,574 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,575 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '오영일', '서울특별시 송파구 한가람로 448 ,105동 105호(풍납동, 동아한가람아파트) (풍납1동)', '02', '487', '6105', 18)
2021-08-18 17:41:07,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,578 INFO sqlalchemy.engine.base.Engine ('아이나무어린이집', '윤영철', '서울특별시 성동구 마장로42길 16 ,1동 106호(마장동, 세림아파트) (마장동)', '02', '2281', '4543', 16)
2021-08-18 17:41:07,579 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,580 INFO sqlalchemy.engine.base.Engine ('푸른잔디어린이집', '신상철', '서울특별시 양천구 목동동로 430 ,615동 101호(목동, 목동6단지아파트) (목5동)', '02', '2645', '9676', 19)
2021-08-18 17:41:07,581 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,582 INFO sqlalchemy.engine.base.Engine ('훈세어린이집', '이지은', '서울특별시 관악구 관천로15길 100 ,2층 (신림동) [신사동] (신사동)', '02', '863', '7908', 5)
2021-08-18 17:41:07,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,584 INFO sqlalchemy.engine.base.Engine ('명성 어린이집', '신정식', '서울특별시 강서구 등촌로13길 76 ,(화곡동) (화곡제4동)', '02', '2644', '3800', 4)
2021-08-18 17:41:07,585 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,587 INFO sqlalchemy.engine.base.Engine ('우리또래어린이집', '류준호', '서울특별시 양천구 지양로11길 9 ,(1~2층) (신월7동)', '02', '2601', '6603', 19)
2021-08-18 17:41:07,588 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,588 INFO sqlalchemy.engine.base.Engine ('서머힐어린이집', '전혜진', '서울특별시 노원구 상계로17길 42 ,(상계동) (상계2동)', '02', '952', '4477', 9)
2021-08-18 17:41:07,589 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,591 INFO sqlalchemy.engine.base.Engine ('한가람어린이집', '전준영', '서울특별시 송파구 한가람로 446 ,동아한가람아파트 단지내 (풍납동) (풍납1동)', '02', '478', '1210', 18)
2021-08-18 17:41:07,592 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,592 INFO sqlalchemy.engine.base.Engine ('그림나라어린이집', '류영환', '서울특별시 도봉구 해등로 50 ,320동 106호(창동, 주공3단지아파트) (창제1동)', '02', '6228', '7356', 10)
2021-08-18 17:41:07,594 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,594 INFO sqlalchemy.engine.base.Engine ('또래또래어린이집', '최영식', '서울특별시 노원구 상계로1길 92 ,709동 106호(상계동, 상계주공7차) (상계10동)', '02', '3391', '7561', 9)
2021-08-18 17:41:07,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,596 INFO sqlalchemy.engine.base.Engine ('즐거운몬테소리어린이집', '이민재', '서울특별시 노원구 한글비석로54길 92 ,1304동 101호(상계동, 상계주공13차) (상계9동)', '02', '3391', '2008', 9)
2021-08-18 17:41:07,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,597 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '전민지', '서울특별시 중랑구 중랑천로10길 87 ,(상봉동) (상봉제2동)', '02', '2207', '7806', 25)
2021-08-18 17:41:07,600 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,601 INFO sqlalchemy.engine.base.Engine ('가명어린이집', '정준서', '서울특별시 중구 청파로 447-1 ,가명어린이집 (중림동)', '02', '365', '7021', 24)
2021-08-18 17:41:07,602 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,603 INFO sqlalchemy.engine.base.Engine ('한남어린이집', '김진호', '서울특별시 영등포구 양산로 182 ,(영등포동6가) (영등포동)', '02', '2679', '9516', 20)
2021-08-18 17:41:07,605 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,607 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '박은경', '서울특별시 송파구 토성로15길 15-6 ,비동(풍납동) (풍납2동)', '02', '484', '3953', 18)
2021-08-18 17:41:07,608 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,609 INFO sqlalchemy.engine.base.Engine ('구립성대어린이집', '전민수', '서울특별시 동작구 성대로10길 27 ,성대어린이집 (상도동) (상도제4동)', '02', '826', '9003', 12)
2021-08-18 17:41:07,610 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,611 INFO sqlalchemy.engine.base.Engine ('동심어린이집', '조종수', '서울특별시 광진구 뚝섬로 609 ,(자양동) (자양제1동)', '02', '2201', '6230', 6)
2021-08-18 17:41:07,612 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,613 INFO sqlalchemy.engine.base.Engine ('한둘어린이집', '류상훈', '서울특별시 강북구 삼양로163길 15 ,(우이동) (우이동)', '02', '902', '5997', 3)
2021-08-18 17:41:07,614 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,614 INFO sqlalchemy.engine.base.Engine ('역삼어린이집', '이지은', '서울특별시 강남구 테헤란로22길 46 ,(역삼동) (역삼제1동)', '02', '553', '1130', 1)
2021-08-18 17:41:07,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,616 INFO sqlalchemy.engine.base.Engine ('조은세상어린이집', '강정자', '서울특별시 동작구 상도로15길 9 ,(상도동)1층 (상도제3동)', '02', '821', '2020', 12)
2021-08-18 17:41:07,617 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,618 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '조준영', '서울특별시 광진구 천호대로117길 51 ,(중곡동) (중곡제2동)', '02', '458', '7005', 6)
2021-08-18 17:41:07,619 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,620 INFO sqlalchemy.engine.base.Engine ('미담어린이집', '김영숙', '서울특별시 강남구 일원로 115 ,삼성생명빌딩 (개포동) (일원본동)', '02', '2226', '9286', 1)
2021-08-18 17:41:07,621 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,622 INFO sqlalchemy.engine.base.Engine ('신예지어린이집', '강은영', '서울특별시 광진구 자양로45길 16 ,(구의2동) (구의제2동)', '02', '458', '8538', 6)
2021-08-18 17:41:07,623 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,624 INFO sqlalchemy.engine.base.Engine ('아름다운집어린이집', '황정식', '서울특별시 서대문구 북아현로14길 15-6 (충현동)', '02', '312', '3248', 14)
2021-08-18 17:41:07,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,626 INFO sqlalchemy.engine.base.Engine ('구립 양천어린이집', '이영식', '서울특별시 양천구 목동로3길 57 (신정7동)', '02', '2651', '0856', 19)
2021-08-18 17:41:07,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,627 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '윤미영', '서울특별시 관악구 신림로3길 40 ,2층 (신림동, 건영아파트 관리동) [대학동] (대학동)', '02', '885', '1941', 5)
2021-08-18 17:41:07,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,628 INFO sqlalchemy.engine.base.Engine ('파란나라어린이집', '신준호', '서울특별시 성북구 보국문로20길 16 ,(정릉동) (정릉제4동)', '02', '918', '1423', 17)
2021-08-18 17:41:07,629 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,630 INFO sqlalchemy.engine.base.Engine ('약수교회어린이집', '서은영', '서울특별시 중구 다산로8길 32 ,(신당동) (약수동)', '02', '2233', '5131', 24)
2021-08-18 17:41:07,634 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,636 INFO sqlalchemy.engine.base.Engine ('서강사랑어린이집', '윤현준', '서울특별시 마포구 독막로 127 ,(창전동) (서강동)', '02', '324', '4020', 13)
2021-08-18 17:41:07,637 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,638 INFO sqlalchemy.engine.base.Engine ('아가랑어린이집', '박영일', '서울특별시 노원구 초안산로5길 28 ,(월계동) (월계2동)', '02', '907', '1029', 9)
2021-08-18 17:41:07,639 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,641 INFO sqlalchemy.engine.base.Engine ('기독어린이집', '권지훈', '서울특별시 금천구 시흥대로26길 28 ,(시흥동) (시흥제3동)', '02', '894', '2023', 8)
2021-08-18 17:41:07,643 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,643 INFO sqlalchemy.engine.base.Engine ('건대꼬마숲어린이집', '최영길', '서울특별시 광진구 동일로28길 45 ,(화양동) (화양동)', '02', '467', '6489', 6)
2021-08-18 17:41:07,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,645 INFO sqlalchemy.engine.base.Engine ('하늘빛어린이집', '정경회', '서울특별시 용산구 우사단로10길 115 ,765-23 (한남동)', '02', '796', '1689', 21)
2021-08-18 17:41:07,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,647 INFO sqlalchemy.engine.base.Engine ('동우어린이나라어린이집', '류건우', '서울특별시 서대문구 북아현로22나길 85 ,(북아현동) (충현동)', '02', '364', '1285', 14)
2021-08-18 17:41:07,648 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,649 INFO sqlalchemy.engine.base.Engine ('풍납어린이집', '류지원', '서울특별시 송파구 토성로 52 ,(풍납동) (풍납2동)', '02', '485', '8267', 18)
2021-08-18 17:41:07,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,652 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '신민지', '서울특별시 강동구 진황도로 195 ,(둔촌동 94의3호) (둔촌제2동)', '02', '483', '5427', 2)
2021-08-18 17:41:07,655 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,655 INFO sqlalchemy.engine.base.Engine ('우정어린이집', '오정호', '서울특별시 은평구 갈현로41길 26-2 ,(갈현동) (갈현제1동)', '02', '387', '4131', 22)
2021-08-18 17:41:07,656 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,657 INFO sqlalchemy.engine.base.Engine ('강동아이슐레어린이집', '박현정', '서울특별시 강동구 고덕로24가길 36 ,(암사동 437-1) (암사제1동)', '02', '441', '0053', 2)
2021-08-18 17:41:07,659 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,659 INFO sqlalchemy.engine.base.Engine ('예뜰창의어린이집', '한준영', '서울특별시 금천구 시흥대로126길 47 ,(독산동) (독산제4동)', '02', '865', '1211', 8)
2021-08-18 17:41:07,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,661 INFO sqlalchemy.engine.base.Engine ('햇빛어린이집', '류정수', '서울특별시 용산구 효창원로86가길 28 ,(청파동1가) (청파동)', '02', '706', '1344', 21)
2021-08-18 17:41:07,662 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,663 INFO sqlalchemy.engine.base.Engine ('그림터어린이집', '황병철', '서울특별시 강서구 초록마을로2길 22 ,(화곡동) (화곡본동)', '02', '2698', '9875', 4)
2021-08-18 17:41:07,664 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,665 INFO sqlalchemy.engine.base.Engine ('푸른숲어린이집', '전영식', '서울특별시 영등포구 당산로 95 ,한전현대아파트 단지내 푸른숲어린이집 당산동2가 (당산제1동)', '02', '2636', '3505', 20)
2021-08-18 17:41:07,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,668 INFO sqlalchemy.engine.base.Engine ('숙명어린이집', '전민지', '서울특별시 양천구 목동동로 50 ,1224동 106호(신정동, 신시가지12단지아파트) (신정7동)', '02', '2652', '8545', 19)
2021-08-18 17:41:07,669 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,670 INFO sqlalchemy.engine.base.Engine ('주나어린이집', '류동현', '서울특별시 노원구 노원로30길 58-10 ,주나어린이집 (상계동) (상계2동)', '02', '952', '5853', 9)
2021-08-18 17:41:07,671 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,672 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '권진호', '서울특별시 용산구 원효로67길 13 ,(원효로2가) (원효로제1동)', '02', '701', '7289', 21)
2021-08-18 17:41:07,673 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,674 INFO sqlalchemy.engine.base.Engine ('세네동어린이집', '서지원', '서울특별시 노원구 상계로39길 10 ,(상계동) (상계3.4동)', '02', '936', '5205', 9)
2021-08-18 17:41:07,675 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,676 INFO sqlalchemy.engine.base.Engine ('희망나래어린이집', '이은영', '서울특별시 노원구 동일로186길 53-26 (공릉1동)', '02', '978', '1007', 9)
2021-08-18 17:41:07,677 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,678 INFO sqlalchemy.engine.base.Engine ('엘림어린이집', '오성민', '서울특별시 금천구 독산로70길 39 ,(독산동) (독산제4동)', '02', '855', '3253', 8)
2021-08-18 17:41:07,679 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,680 INFO sqlalchemy.engine.base.Engine ('포그니어린이집', '오영진', '서울특별시 강남구 학동로64길 7 ,102동 107호(삼성동, 한솔파크아파트) (삼성2동)', '02', '543', '9443', 1)
2021-08-18 17:41:07,681 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,681 INFO sqlalchemy.engine.base.Engine ('새소리어린이집', '임건우', '서울특별시 중랑구 봉우재로1길 14 ,(면목동) (면목제2동)', '02', '437', '8912', 25)
2021-08-18 17:41:07,682 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,684 INFO sqlalchemy.engine.base.Engine ('사랑샘i스쿨어린이집', '임현준', '서울특별시 노원구 수락산로 234 ,304동 107호(상계동, 상계현대3차) (상계1동)', '02', '6223', '8409', 9)
2021-08-18 17:41:07,685 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,686 INFO sqlalchemy.engine.base.Engine ('아트어린이집', '안은경', '서울특별시 성북구 장월로1길 60 ,동덕빌딩2층아트어린이집 (상월곡동) (월곡제2동)', '02', '909', '2325', 17)
2021-08-18 17:41:07,687 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,687 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '조준호', '서울특별시 구로구 새말로16길 70 ,110호 (구로제5동)', '02', '862', '0450', 7)
2021-08-18 17:41:07,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,689 INFO sqlalchemy.engine.base.Engine ('상봉삼성어린이집', '장유진', '서울특별시 중랑구 면목로88길 9 ,(상봉동) (상봉제2동)', '02', '434', '0191', 25)
2021-08-18 17:41:07,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,691 INFO sqlalchemy.engine.base.Engine ('가현어린이집', '장영길', '서울특별시 구로구 경인로35길 113-5 ,가현어린이집 (고척동) (고척제2동)', '02', '2683', '3933', 7)
2021-08-18 17:41:07,691 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,692 INFO sqlalchemy.engine.base.Engine ('동화어린이집', '강영환', '서울특별시 동대문구 망우로12가길 20 ,(휘경동) (휘경제2동)', '02', '2244', '9118', 11)
2021-08-18 17:41:07,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,697 INFO sqlalchemy.engine.base.Engine ('꿈동산어린이집', '서준혁', '서울특별시 도봉구 노해로45길 26 ,104동 105호(쌍문동, 극동아파트) (쌍문제1동)', '02', '907', '1156', 10)
2021-08-18 17:41:07,700 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,701 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '김영일', '서울특별시 동대문구 서울시립대로 14 ,청계한신휴플러스아파트 관리동 (답십리동) (답십리제1동)', '02', '2212', '8439', 11)
2021-08-18 17:41:07,702 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,703 INFO sqlalchemy.engine.base.Engine ('수서서머힐어린이집', '임준혁', '서울특별시 강남구 광평로51길 22 ,한아름아파트 관리동 (수서동)', '02', '445', '5040', 1)
2021-08-18 17:41:07,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,704 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '조지훈', '서울특별시 성북구 서경로13길 26 ,(정릉동) (정릉제2동)', '02', '916', '9820', 17)
2021-08-18 17:41:07,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,706 INFO sqlalchemy.engine.base.Engine ('작은나무수수꽃다리어린이집', '송정호', '서울특별시 구로구 오류로8길 11 ,106동 101호(오류동, 오류동푸르지오아파트) (오류제2동)', '02', '6097', '0659', 7)
2021-08-18 17:41:07,707 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,708 INFO sqlalchemy.engine.base.Engine ('짐랜드어린이집', '박지원', '서울특별시 강북구 노해로14길 8 ,(수유동) (수유3동)', '02', '996', '2013', 3)
2021-08-18 17:41:07,709 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,710 INFO sqlalchemy.engine.base.Engine ('영이어린이집', '김경자', '서울특별시 영등포구 영중로4길 31 ,(영등포동3가) (영등포동)', '02', '2631', '0283', 20)
2021-08-18 17:41:07,711 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,712 INFO sqlalchemy.engine.base.Engine ('모난어린이집', '이현정', '서울특별시 성북구 화랑로19길 67 ,(장위동) (장위제2동)', '02', '915', '3901', 17)
2021-08-18 17:41:07,713 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,715 INFO sqlalchemy.engine.base.Engine ('참예은어린이집', '황건우', '서울특별시 중랑구 동일로116길 47 ,(상봉동) (상봉제2동)', '02', '435', '0434', 25)
2021-08-18 17:41:07,716 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,718 INFO sqlalchemy.engine.base.Engine ('역촌꿈의숲어린이집', '전순자', '서울특별시 은평구 진흥로5길 8-1 ,(역촌동) (역촌동)', '02', '384', '7898', 22)
2021-08-18 17:41:07,719 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,720 INFO sqlalchemy.engine.base.Engine ('대청어린이집', '송준호', '서울특별시 강남구 양재대로37길 19 ,(일원동) (일원제1동)', '02', '445', '2630', 1)
2021-08-18 17:41:07,721 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,721 INFO sqlalchemy.engine.base.Engine ('참고은어린이집', '장순자', '서울특별시 구로구 고척로19길 8 ,(개봉동) (개봉제1동)', '02', '841', '1004', 7)
2021-08-18 17:41:07,722 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,722 INFO sqlalchemy.engine.base.Engine ('베비텔어린이집', '윤성수', '서울특별시 중랑구 봉우재로65길 45 ,(망우동) (망우본동)', '02', '493', '0144', 25)
2021-08-18 17:41:07,723 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,724 INFO sqlalchemy.engine.base.Engine ('서문어린이집', '정예준', '서울특별시 서대문구 홍은중앙로 139 ,(홍은동) (홍은제1동)', '02', '394', '1985', 14)
2021-08-18 17:41:07,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,726 INFO sqlalchemy.engine.base.Engine ('꽃사슴어린이집', '신민수', '서울특별시 구로구 개봉로20길 6 ,102동 103호(개봉동, 현대아파트) (개봉제2동)', '02', '2066', '8959', 7)
2021-08-18 17:41:07,727 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,728 INFO sqlalchemy.engine.base.Engine ('유성어린이집', '윤지은', '서울특별시 강서구 강서로48길 22 ,(내발산동) (우장산동)', '02', '3664', '0667', 4)
2021-08-18 17:41:07,729 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,730 INFO sqlalchemy.engine.base.Engine ('은혜감사어린이집', '임정수', '서울특별시 서대문구 명지대3길 19 ,(남가좌동) (남가좌제2동)', '02', '375', '6470', 14)
2021-08-18 17:41:07,731 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,731 INFO sqlalchemy.engine.base.Engine ('홍연어린이집', '신영자', '서울특별시 서대문구 홍제천로 174-13 (연희동)', '02', '336', '0036', 14)
2021-08-18 17:41:07,732 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,733 INFO sqlalchemy.engine.base.Engine ('미소가득어린이집', '안경회', '서울특별시 강서구 방화대로40길 66 ,태승훼미리 105호 (방화동) (방화제1동)', '02', '2666', '3957', 4)
2021-08-18 17:41:07,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,735 INFO sqlalchemy.engine.base.Engine ('창일어린이집', '권예은', '서울특별시 종로구 종로50라길 41-3 (창신제1동)', '02', '763', '3358', 23)
2021-08-18 17:41:07,736 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,737 INFO sqlalchemy.engine.base.Engine ('관인 큰돌 몬테소리 어린이집', '안지영', '서울특별시 금천구 독산로50가길 6 (시흥제4동)', '02', '803', '1125', 8)
2021-08-18 17:41:07,738 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,738 INFO sqlalchemy.engine.base.Engine ('꿈을키우는어린이집', '이영숙', '서울특별시 성북구 월곡로 31 ,(종암동) (종암동)', '02', '919', '3110', 17)
2021-08-18 17:41:07,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,740 INFO sqlalchemy.engine.base.Engine ('신기어린이집', '권민재', '서울특별시 강북구 삼양로79길 12 ,(수유동) (수유1동)', '02', '986', '1771', 3)
2021-08-18 17:41:07,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:07,742 INFO sqlalchemy.engine.base.Engine ('지성어린이집', '이성민', '서울특별시 강북구 노해로13길 22 ,(수유동) (수유3동)', '02', '903', '2435', 3)
2021-08-18 17:41:07,744 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,744 INFO sqlalchemy.engine.base.Engine ('꽃햇살어린이집', '이준호', '서울특별시 은평구 증산로17길 39-11 (신사제2동)', '02', '375', '0153', 22)
2021-08-18 17:41:07,746 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,759 INFO sqlalchemy.engine.base.Engine ('별하어린이집', '정예준', '서울특별시 중랑구 봉우재로12길 12-11 (면목제2동)', '02', '433', '1365', 25)
2021-08-18 17:41:07,760 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,760 INFO sqlalchemy.engine.base.Engine ('한국원자력의학원어린이집', '정민석', '서울특별시 노원구 노원로 75 ,한국원자력의학원어린이집 (공릉동) (공릉2동)', '02', '970', '2137', 9)
2021-08-18 17:41:07,762 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,763 INFO sqlalchemy.engine.base.Engine ('리틀피카소어린이집', '권민수', '서울특별시 중랑구 용마산로94길 50 ,(면목동) (면목제3.8동)', '02', '493', '0030', 25)
2021-08-18 17:41:07,763 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,764 INFO sqlalchemy.engine.base.Engine ('숲속어린이집', '조정자', '서울특별시 동작구 등용로10길 24 ,(대방동) (대방동)', '02', '812', '7564', 12)
2021-08-18 17:41:07,765 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,765 INFO sqlalchemy.engine.base.Engine ('성심어린이집', '박예은', '서울특별시 중랑구 용마산로94길 88 ,(면목동) (면목제3.8동)', '02', '494', '5072', 25)
2021-08-18 17:41:07,766 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,767 INFO sqlalchemy.engine.base.Engine ('은현어린이집', '한수빈', '서울특별시 관악구 난곡로11길 8 ,(신림동) [난향동] (난향동)', '02', '858', '0893', 5)
2021-08-18 17:41:07,768 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,769 INFO sqlalchemy.engine.base.Engine ('일원어린이집', '황준영', '서울특별시 강남구 광평로3길 21 ,일원어린이집 (일원동) (일원본동)', '02', '459', '3221', 1)
2021-08-18 17:41:07,770 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,771 INFO sqlalchemy.engine.base.Engine ('독립문어린이집', '정준호', '서울특별시 서대문구 독립문로 12 ,독립문어린이집 (천연동)', '02', '313', '4666', 14)
2021-08-18 17:41:07,772 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,773 INFO sqlalchemy.engine.base.Engine ('색동원어린이집', '신준호', '서울특별시 동작구 사당로2자길 38 ,(사당동) 102 (사당제5동)', '02', '535', '0095', 12)
2021-08-18 17:41:07,774 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,774 INFO sqlalchemy.engine.base.Engine ('나이팅게일어린이집', '송상철', '서울특별시 강북구 노해로23길 95 ,(수유동) (수유2동)', '02', '999', '9605', 3)
2021-08-18 17:41:07,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,776 INFO sqlalchemy.engine.base.Engine ('가나어린이집', '강은경', '서울특별시 도봉구 노해로46길 47 ,(쌍문동) (쌍문제3동)', '02', '996', '0310', 10)
2021-08-18 17:41:07,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,777 INFO sqlalchemy.engine.base.Engine ('사직어린이집', '전현준', '서울특별시 종로구 필운대로1길 16-8 (사직동)', '02', '720', '0798', 23)
2021-08-18 17:41:07,778 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,779 INFO sqlalchemy.engine.base.Engine ('엄마품어린이집', '류준영', '서울특별시 송파구 오금로31길 19 ,2층 (방이1동)', '02', '413', '8668', 18)
2021-08-18 17:41:07,782 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,784 INFO sqlalchemy.engine.base.Engine ('강동제일 어린이집', '강정식', '서울특별시 강동구 고덕로20가길 43 ,(암사동 452-13) (암사제1동)', '02', '442', '1584', 2)
2021-08-18 17:41:07,786 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,786 INFO sqlalchemy.engine.base.Engine ('사과나무어린이집', '신지민', '서울특별시 강남구 학동로12길 16 ,(논현동) (논현제1동)', '02', '516', '1807', 1)
2021-08-18 17:41:07,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,788 INFO sqlalchemy.engine.base.Engine ('빛나어린이집', '김정호', '서울특별시 동대문구 전농로23길 47 ,(전농동) (전농제1동)', '02', '2212', '0406', 11)
2021-08-18 17:41:07,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,790 INFO sqlalchemy.engine.base.Engine ('태화어린이집', '서경숙', '서울특별시 중랑구 봉화산로 193 ,신내대명 아파트 단지내 (신내2동)', '02', '3421', '1141', 25)
2021-08-18 17:41:07,792 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,792 INFO sqlalchemy.engine.base.Engine ('꾸미나라어린이집', '박성진', '서울특별시 송파구 풍성로 38 ,(2층) (풍납2동)', '02', '487', '2953', 18)
2021-08-18 17:41:07,793 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,794 INFO sqlalchemy.engine.base.Engine ('꼬꼬마어린이집', '김경숙', '서울특별시 서대문구 거북골로 154 ,101동 101호(북가좌동, 삼호) (북가좌제2동)', '02', '309', '4439', 14)
2021-08-18 17:41:07,795 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,796 INFO sqlalchemy.engine.base.Engine ('아기별어린이집', '최건우', '서울특별시 은평구 연서로27길 13-10 (갈현제2동)', '02', '388', '5943', 22)
2021-08-18 17:41:07,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,797 INFO sqlalchemy.engine.base.Engine ('아이동산어린이집', '박유진', '서울특별시 영등포구 선유동2로 17 ,(양평동3가) (양평제2동)', '02', '2068', '9327', 20)
2021-08-18 17:41:07,799 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,799 INFO sqlalchemy.engine.base.Engine ('구민회관어린이집', '김미영', '서울특별시 강남구 삼성로 154 ,(대치동) (대치제2동)', '02', '501', '6057', 1)
2021-08-18 17:41:07,801 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,801 INFO sqlalchemy.engine.base.Engine ('예은어린이집', '오성호', '서울특별시 강서구 방화대로49길 52 (방화제3동)', '02', '2664', '1768', 4)
2021-08-18 17:41:07,802 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,803 INFO sqlalchemy.engine.base.Engine ('중앙삐아제어린이집', '김지원', '서울특별시 동대문구 한천로63길 5-8 (이문제2동)', '02', '966', '9614', 11)

2021-08-18 17:41:07,804 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,805 INFO sqlalchemy.engine.base.Engine ('애지어린이집', '황서연', '서울특별시 강동구 진황도로 160 ,(둔촌동 452-2) (둔촌제2동)', '02', '471', '8842', 2)
2021-08-18 17:41:07,806 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,807 INFO sqlalchemy.engine.base.Engine ('키즈랜드어린이집', '오경숙', '서울특별시 강동구 성안로13길 42-7 ,(성내동 507-6) (성내제2동)', '02', '476', '3821', 2)
2021-08-18 17:41:07,808 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,809 INFO sqlalchemy.engine.base.Engine ('예일어린이집', '이정호', '서울특별시 동작구 상도로34가길 23 ,(상도동) (상도제2동)', '02', '825', '0152', 12)
2021-08-18 17:41:07,810 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,811 INFO sqlalchemy.engine.base.Engine ('구립 배다리어린이집', '박준영', '서울특별시 강서구 곰달래로15길 25 ,(화곡동) (화곡제1동)', '02', '2693', '9190', 4)
2021-08-18 17:41:07,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,812 INFO sqlalchemy.engine.base.Engine ('노엘어린이집', '신광수', '서울특별시 도봉구 도봉로109길 98 ,(쌍문동) (쌍문제3동)', '02', '995', '8081', 10)
2021-08-18 17:41:07,813 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,813 INFO sqlalchemy.engine.base.Engine ('또래끼리어린이집', '최혜진', '서울특별시 금천구 독산로8다길 6-1 (시흥제5동)', '02', '804', '2623', 8)
2021-08-18 17:41:07,814 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,815 INFO sqlalchemy.engine.base.Engine ('서초구립 서초성모어린이집', '전예은', '서울특별시 서초구 고무래로8길 21 ,(반포동) (반포4동)', '02', '594', '2124', 15)
2021-08-18 17:41:07,816 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,817 INFO sqlalchemy.engine.base.Engine ('양재복지관어린이집', '황성호', '서울특별시 서초구 남부순환로 2610 ,(양재동) (양재1동)', '02', '571', '6141', 15)
2021-08-18 17:41:07,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,819 INFO sqlalchemy.engine.base.Engine ('예쁜꼬마어린이집', '송건우', '서울특별시 중랑구 동일로169길 41 ,103동 102호(묵동, 동구햇살아파트) (묵제2동)', '02', '495', '3527', 25)
2021-08-18 17:41:07,819 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,820 INFO sqlalchemy.engine.base.Engine ('올망졸망어린이집', '조상철', '서울특별시 중랑구 신내로 128 ,3동 103호(신내동, 동성아파트) (신내1동)', '02', '433', '7686', 25)
2021-08-18 17:41:07,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,822 INFO sqlalchemy.engine.base.Engine ('믿음어린이집', '강건우', '서울특별시 금천구 시흥대로100길 38 ,(독산동) (독산제2동)', '02', '807', '3316', 8)
2021-08-18 17:41:07,823 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,824 INFO sqlalchemy.engine.base.Engine ('비테에영재어린이집', '한미숙', '서울특별시 송파구 오금로46길 51 ,103호(가락동, 훼미리빌라) (가락2동)', '02', '3401', '1999', 18)
2021-08-18 17:41:07,826 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,826 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '송수빈', '서울특별시 강동구 고덕로 210 ,삼익그린아파트 상가 (명일동 28) (명일제1동)', '02', '3427', '4985', 2)
2021-08-18 17:41:07,828 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,828 INFO sqlalchemy.engine.base.Engine ('오르다어린이집', '윤정남', '서울특별시 동대문구 답십리로48길 24 ,(답십리동) (답십리제2동)', '02', '2246', '0532', 11)
2021-08-18 17:41:07,829 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,830 INFO sqlalchemy.engine.base.Engine ('유유어린이집', '신정순', '서울특별시 도봉구 노해로63나길 8-11 (창제5동)', '02', '905', '0143', 10)
2021-08-18 17:41:07,831 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,832 INFO sqlalchemy.engine.base.Engine ('화곡어린이집', '윤경자', '서울특별시 강서구 까치산로 60 ,화곡어린이집 (화곡동) (화곡본동)', '02', '2697', '3105', 4)
2021-08-18 17:41:07,833 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,833 INFO sqlalchemy.engine.base.Engine ('양무리어린이집', '임도현', '서울특별시 송파구 백제고분로11길 8 ,(잠실동) (잠실본동)', '02', '421', '4187', 18)
2021-08-18 17:41:07,834 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,835 INFO sqlalchemy.engine.base.Engine ('조약돌어린이집', '오현정', '서울특별시 송파구 삼학사로1길 18 ,(삼전동) (삼전동)', '02', '3432', '0008', 18)
2021-08-18 17:41:07,836 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,837 INFO sqlalchemy.engine.base.Engine ('평화종합사회복지관 방과후 어린이집', '안은경', '서울특별시 노원구 노원로 333 ,(중계3동 평화종합사회복지관내) (중계2.3동)', '02', '949', '0120', 9)
2021-08-18 17:41:07,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,839 INFO sqlalchemy.engine.base.Engine ('강남아이트라움어린이집', '안미숙', '서울특별시 강남구 개포로124길 13 ,(일원동) (일원제1동)', '02', '2226', '5600', 1)
2021-08-18 17:41:07,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,841 INFO sqlalchemy.engine.base.Engine ('본향어린이집', '이지훈', '서울특별시 성동구 난계로 61 -46 ,본향어린이집 (금호1가동)', '02', '2291', '2350', 16)
2021-08-18 17:41:07,842 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,843 INFO sqlalchemy.engine.base.Engine ('아기별삐아제어린이집', '한영자', '서울특별시 노원구 동일로207길 18 ,106동 106호(중계동, 중계그린1단지아파트) (중계2.3동)', '02', '6224', '7609', 9)
2021-08-18 17:41:07,844 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,845 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '조경숙', '서울특별시 서대문구 통일로39다길 8 ,(홍제동) (홍제제1동)', '02', '379', '3235', 14)
2021-08-18 17:41:07,847 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,848 INFO sqlalchemy.engine.base.Engine ('푸른나무어린이집', '박준호', '서울특별시 도봉구 도봉로 715 ,(방학동) (방학제1동)', '02', '3493', '7747', 10)
2021-08-18 17:41:07,848 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,849 INFO sqlalchemy.engine.base.Engine ('서초장미어린이집', '김경숙', '서울특별시 서초구 남부순환로 2543-5 (서초2동)', '02', '3474', '6333', 15)

2021-08-18 17:41:07,850 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,851 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '조정호', '서울특별시 서대문구 연희로41길 45 ,(홍은동) (홍은제2동)', '02', '379', '6441', 14)
2021-08-18 17:41:07,852 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,853 INFO sqlalchemy.engine.base.Engine ('칭찬가득어린이집', '권영철', '서울특별시 성북구 숭인로 16 ,117동 104호(길음동, 동부센트레빌아파트) (길음제2동)', '02', '984', '6223', 17)
2021-08-18 17:41:07,854 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,855 INFO sqlalchemy.engine.base.Engine ('샛별영재어린이집', '류성진', '서울특별시 강서구 허준로 175 ,607동 103호(가양동, 가양6단지아파트) (가양제3동)', '02', '3661', '5129', 4)
2021-08-18 17:41:07,856 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,857 INFO sqlalchemy.engine.base.Engine ('전박사어린이집', '윤미경', '서울특별시 관악구 보라매로 62 ,보라매 삼성아파트 단지내 전박사 어린이집 (보라매동)', '02', '873', '7208', 5)
2021-08-18 17:41:07,858 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,858 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '서준호', '서울특별시 강남구 개포로128길 19 ,(일원동) (일원제1동)', '02', '2226', '1010', 1)
2021-08-18 17:41:07,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,860 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '강민지', '서울특별시 양천구 목동동로 419 ,(목동) (목5동)', '02', '2655', '1135', 19)
2021-08-18 17:41:07,861 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,862 INFO sqlalchemy.engine.base.Engine ('고모랑이모랑어린이집', '이정운', '서울특별시 강서구 송정로 46-6 (공항동)', '02', '2661', '2202', 4)
2021-08-18 17:41:07,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,867 INFO sqlalchemy.engine.base.Engine ('신영어린이집', '윤정수', '서울특별시 동작구 여의대방로 28 ,현대아파트 104동 앞 (신대방제1동)', '02', '845', '9874', 12)
2021-08-18 17:41:07,868 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,869 INFO sqlalchemy.engine.base.Engine ('선애어린이집', '임정운', '서울특별시 마포구 망원로6길 6-1 (망원제1동)', '02', '3141', '7470', 13)
2021-08-18 17:41:07,871 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,872 INFO sqlalchemy.engine.base.Engine ('꽃사슴어린이집', '한민서', '서울특별시 양천구 목동중앙본로2길 13 ,(목동) (목2동)', '02', '2647', '1465', 19)
2021-08-18 17:41:07,873 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,876 INFO sqlalchemy.engine.base.Engine ('강동무지개어린이집', '오민석', '서울특별시 강동구 양재대로125길 30 (천호제1동)', '02', '473', '7662', 2)
2021-08-18 17:41:07,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,878 INFO sqlalchemy.engine.base.Engine ('프뢰벨슐레어린이집', '서종수', '서울특별시 노원구 동일로242다길 11 ,(상계동) (상계1동)', '02', '932', '6966', 9)
2021-08-18 17:41:07,879 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,880 INFO sqlalchemy.engine.base.Engine ('서초중앙어린이집', '최예은', '서울특별시 서초구 남부순환로289길 35 ,(방배동) (방배3동)', '02', '582', '4356', 15)
2021-08-18 17:41:07,881 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,882 INFO sqlalchemy.engine.base.Engine ('네잎크로버어린이집', '임지은', '서울특별시 도봉구 덕릉로59아길 42 (창제2동)', '02', '902', '8543', 10)
2021-08-18 17:41:07,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,885 INFO sqlalchemy.engine.base.Engine ('명일어린이집', '오지원', '서울특별시 강동구 천중로49길 58 ,102동 106호(길동, 우성아파트) (길동)', '02', '3427', '4825', 2)
2021-08-18 17:41:07,886 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,887 INFO sqlalchemy.engine.base.Engine ('송정어린이집', '전영환', '서울특별시 성동구 동일로 187 ,(송정동) (송정동)', '02', '498', '6198', 16)
2021-08-18 17:41:07,888 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,888 INFO sqlalchemy.engine.base.Engine ('피노키오그림나라어린이집', '류민지', '서울특별시 송파구 가락로21길 30 ,(송파동) (송파1동)', '02', '417', '5378', 18)
2021-08-18 17:41:07,889 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,890 INFO sqlalchemy.engine.base.Engine ('구립구의2동어린이집', '장은경', '서울특별시 광진구 자양로44길 91 ,(구의동) (구의제2동)', '02', '446', '6435', 6)
2021-08-18 17:41:07,890 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,891 INFO sqlalchemy.engine.base.Engine ('두리두리어린이집', '최수빈', '서울특별시 성동구 왕십리로31나길 22 ,3동 109호(하왕십리동, 한신무학아파트) (왕십리제2동)', '02', '2295', '5689', 16)
2021-08-18 17:41:07,892 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,893 INFO sqlalchemy.engine.base.Engine ('짐랜드 어린이집', '최민수', '서울특별시 성북구 정릉로29길 10 ,(정릉동) (정릉제1동)', '02', '943', '2007', 17)
2021-08-18 17:41:07,894 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,894 INFO sqlalchemy.engine.base.Engine ('또또어린이집', '윤서현', '서울특별시 노원구 공릉로 126 ,103동 104호(공릉동, 두산힐스빌아파트) (공릉2동)', '02', '976', '6922', 9)
2021-08-18 17:41:07,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,897 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '한상훈', '서울특별시 마포구 월드컵로15길 59 ,(망원동) (망원제1동)', '02', '332', '9894', 13)
2021-08-18 17:41:07,898 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,898 INFO sqlalchemy.engine.base.Engine ('정도어린이집', '임성호', '서울특별시 강서구 화곡로24길 55 ,서울특별시 강서구 화곡로24길55 (화곡제1동)', '02', '2603', '9553', 4)
2021-08-18 17:41:07,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,900 INFO sqlalchemy.engine.base.Engine ('또래또어린이집', '송준호', '서울특별시 도봉구 방학로7길 51 ,(쌍문동) (쌍문제2동)', '02', '902', '8295', 10)
2021-08-18 17:41:07,901 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,902 INFO sqlalchemy.engine.base.Engine ('구립낙성대어린이집', '박종수', '서울특별시 관악구 관악로12길 58-5 ,(봉천동) [낙성대동] (낙성대동)', '02', '872', '0726', 5)

2021-08-18 17:41:07,903 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,903 INFO sqlalchemy.engine.base.Engine ('둥이나라어린이집', '권준혁', '서울특별시 구로구 경인로8길 64 ,101동 104호(오류동 영풍마드레빌아파트) (오류제2동)', '02', '2681', '0705', 7)
2021-08-18 17:41:07,905 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,906 INFO sqlalchemy.engine.base.Engine ('꾸러기동산어린이집', '김현준', '서울특별시 구로구 디지털로27라길 32 ,(구로동) (구로제3동)', '02', '855', '3579', 7)
2021-08-18 17:41:07,907 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,908 INFO sqlalchemy.engine.base.Engine ('보혜어린이집', '장건우', '서울특별시 송파구 가락로28길 11 ,(송파동) (송파2동)', '02', '2202', '9170', 18)
2021-08-18 17:41:07,910 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,911 INFO sqlalchemy.engine.base.Engine ('경희의료원 어린이집', '이정운', '서울특별시 동대문구 경희대로1나길 56-1 (회기동)', '02', '958', '9850', 11)
2021-08-18 17:41:07,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,912 INFO sqlalchemy.engine.base.Engine ('한라어린이집', '윤도현', '서울특별시 광진구 뚝섬로33길 20 ,(자양동) (자양제3동)', '02', '2201', '1264', 6)
2021-08-18 17:41:07,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,914 INFO sqlalchemy.engine.base.Engine ('리틀영일우리어린이집', '윤성호', '서울특별시 영등포구 도신로29사길 22 (도림동)', '02', '835', '9488', 20)
2021-08-18 17:41:07,915 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,916 INFO sqlalchemy.engine.base.Engine ('신애어린이집', '강정남', '서울특별시 서초구 바우뫼로9길 9 ,(우면동) (양재1동)', '02', '576', '2759', 15)
2021-08-18 17:41:07,918 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,922 INFO sqlalchemy.engine.base.Engine ('은혜삐아제어린이집', '조준호', '서울특별시 중랑구 답십리로81길 130 ,(면목동) (면목제7동)', '02', '435', '5956', 25)
2021-08-18 17:41:07,923 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,923 INFO sqlalchemy.engine.base.Engine ('꼬마또래어린이집', '신지원', '서울특별시 마포구 성미산로 169 (연남동)', '070', '8824', '3756', 13)
2021-08-18 17:41:07,924 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,925 INFO sqlalchemy.engine.base.Engine ('엘지유플러스어린이집', '안영진', '서울특별시 용산구 한강로3가 한강대로 32 (한강로동)', '070', '8277', '4119', 21)
2021-08-18 17:41:07,926 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,926 INFO sqlalchemy.engine.base.Engine ('푸른꿈동산어린이집', '이지은', '서울특별시 서대문구 홍제내2다길 25 ,(홍제동) (홍제제1동)', '02', '391', '8049', 14)
2021-08-18 17:41:07,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,928 INFO sqlalchemy.engine.base.Engine ('무지개나라어린이집', '전민서', '서울특별시 은평구 가좌로7다길 13 ,(응암동) (응암제3동)', '02', '302', '5255', 22)
2021-08-18 17:41:07,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,930 INFO sqlalchemy.engine.base.Engine ('은빛어린이집', '송영숙', '서울특별시 서초구 효령로68길 13 ,21동 102호(서초동, 현대아파트) (서초1동)', '02', '3471', '1218', 15)
2021-08-18 17:41:07,932 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,932 INFO sqlalchemy.engine.base.Engine ('다솜어린이집', '오유진', '서울특별시 동대문구 천호대로45나길 48 ,(용두동) (용신동)', '02', '960', '1794', 11)
2021-08-18 17:41:07,934 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,936 INFO sqlalchemy.engine.base.Engine ('고운색동어린이집', '김혜진', '서울특별시 영등포구 영등포동7가 영중로27길 8 ,(영등포동) (영등포동)', '02', '2634', '8760', 20)
2021-08-18 17:41:07,937 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,937 INFO sqlalchemy.engine.base.Engine ('대림삐아제어린이집', '조은영', '서울특별시 동작구 여의대방로 250 ,102동 102호(대방동, 대림아파트) (대방동)', '02', '824', '7818', 12)
2021-08-18 17:41:07,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,938 INFO sqlalchemy.engine.base.Engine ('이루니키즈어린이집', '윤경숙', '서울특별시 강동구 명일로 230-15 ,(길동 101-2) (길동)', '02', '486', '6271', 2)
2021-08-18 17:41:07,940 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,940 INFO sqlalchemy.engine.base.Engine ('구립이수어린이집', '김준호', '서울특별시 동작구 동작대로35길 36 ,이수어린이집 (사당동) (사당제2동)', '02', '591', '7634', 12)
2021-08-18 17:41:07,942 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,942 INFO sqlalchemy.engine.base.Engine ('대치어린이집', '황정자', '서울특별시 강남구 영동대로65길 11 ,(대치동) (대치제2동)', '02', '561', '1730', 1)
2021-08-18 17:41:07,944 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,945 INFO sqlalchemy.engine.base.Engine ('바롬어린이집', '김정남', '서울특별시 강남구 언주로164길 36 ,(신사동) (압구정동)', '02', '516', '4665', 1)
2021-08-18 17:41:07,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,949 INFO sqlalchemy.engine.base.Engine ('아힘나어린이집', '송건우', '서울특별시 광진구 능동로3길 17 ,101동 106호(자양동, 한강성원아파트) (자양제4동)', '02', '447', '9335', 6)
2021-08-18 17:41:07,950 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,951 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '송준서', '서울특별시 강서구 화곡로35길 23-17 (우장산동)', '02', '2604', '5621', 4)
2021-08-18 17:41:07,951 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,952 INFO sqlalchemy.engine.base.Engine ('초동어린이집', '서준호', '서울특별시 종로구 돈화문로5가길 23 ,(돈의동) (종로1.2.3.4가동)', '02', '765', '6205', 23)
2021-08-18 17:41:07,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,954 INFO sqlalchemy.engine.base.Engine ('새서울어린이집', '장영자', '서울특별시 강북구 삼양로19길 164 ,순복음새서울교회 1353동 1층 4호(미아동) (삼각산동)', '02', '989', '7490', 3)
2021-08-18 17:41:07,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,955 INFO sqlalchemy.engine.base.Engine ('가락복지관어린이집', '강예준', '서울특별시 송파구 양재대로 897 ,(가락동) (가락1동)', '02', '449', '2356', 18)

2021-08-18 17:41:07,956 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,958 INFO sqlalchemy.engine.base.Engine ('석촌삐아제어린이집', '정은영', '서울특별시 송파구 송파대로39길 13 ,(석촌동) (석촌동)', '02', '2203', '6694', 18)
2021-08-18 17:41:07,959 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,960 INFO sqlalchemy.engine.base.Engine ('남산중앙어린이집', '윤민수', '서울특별시 용산구 두텁바위로60길 74 ,남산중앙교회내 (후암동) (후암동)', '02', '754', '9919', 21)
2021-08-18 17:41:07,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,964 INFO sqlalchemy.engine.base.Engine ('애일선교어린이집', '전민재', '서울특별시 동대문구 왕산로16길 28 ,(용두동) (용신동)', '02', '921', '3825', 11)
2021-08-18 17:41:07,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,966 INFO sqlalchemy.engine.base.Engine ('예본어린이집', '신준호', '서울특별시 은평구 연서로5길 40 ,(역촌동) (역촌동)', '02', '387', '3149', 22)
2021-08-18 17:41:07,967 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,968 INFO sqlalchemy.engine.base.Engine ('유정어린이집', '한영진', '서울특별시 도봉구 시루봉로27길 58 ,(도봉동) (도봉제1동)', '02', '955', '1377', 10)
2021-08-18 17:41:07,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,970 INFO sqlalchemy.engine.base.Engine ('삐아제어린이집', '오상훈', '서울특별시 강동구 고덕로61길 37 ,102동 104호(고덕동, 현대아파트) (고덕제1동)', '02', '442', '7349', 2)
2021-08-18 17:41:07,971 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,972 INFO sqlalchemy.engine.base.Engine ('예본i어린이집', '서미영', '서울특별시 노원구 한글비석로 396 ,104동 102호(상계동, 벽산) (상계5동)', '02', '6232', '1001', 9)
2021-08-18 17:41:07,972 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,973 INFO sqlalchemy.engine.base.Engine ('지성어린이집', '안정남', '서울특별시 노원구 섬밭로 52 ,101동108호(대주파크빌아파트) (공릉1동)', '02', '977', '5668', 9)
2021-08-18 17:41:07,974 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,975 INFO sqlalchemy.engine.base.Engine ('장미어린이집', '윤지은', '서울특별시 송파구 올림픽로35길 104 ,18동 103호(신천동, 장미아파트) (잠실6동)', '02', '3431', '1616', 18)
2021-08-18 17:41:07,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,977 INFO sqlalchemy.engine.base.Engine ('등촌어린이집', '박동현', '서울특별시 양천구 목동중앙북로8다길 13 ,(목동) (목3동)', '02', '2654', '1577', 19)
2021-08-18 17:41:07,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,978 INFO sqlalchemy.engine.base.Engine ('또래또어린이집', '김정수', '서울특별시 은평구 갈현로2길 29-15 (신사제1동)', '02', '386', '8593', 22)
2021-08-18 17:41:07,979 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,980 INFO sqlalchemy.engine.base.Engine ('사무엘 어린이집', '류서현', '서울특별시 용산구 이태원로15길 1 ,(이태원동) (이태원제1동)', '02', '796', '7470', 21)
2021-08-18 17:41:07,981 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,982 INFO sqlalchemy.engine.base.Engine ('돈암교회어린이집', '최영철', '서울특별시 성북구 아리랑로4길 45 ,(동선동5가) (동선동)', '02', '922', '6259', 17)
2021-08-18 17:41:07,983 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,984 INFO sqlalchemy.engine.base.Engine ('구립 녹번복지관 어린이집', '류순자', '서울특별시 은평구 은평로21길 14-26 (녹번동)', '02', '358', '4695', 22)
2021-08-18 17:41:07,985 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,986 INFO sqlalchemy.engine.base.Engine ('구립둥지어린이집', '안유진', '서울특별시 동작구 사당로14길 20 ,둥지어린이집 (사당동) (사당제4동)', '02', '597', '0912', 12)
2021-08-18 17:41:07,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,987 INFO sqlalchemy.engine.base.Engine ('구립원당어린이집', '최준혁', '서울특별시 관악구 행운1길 6-3 ,(봉천동) [행운동] (행운동)', '02', '879', '1798', 5)
2021-08-18 17:41:07,988 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,989 INFO sqlalchemy.engine.base.Engine ('신당중앙어린이집', '김지은', '서울특별시 중구 다산로 165 ,(신당동) (다산동)', '02', '2234', '7589', 24)
2021-08-18 17:41:07,990 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,991 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '전영철', '서울특별시 송파구 올림픽로47길 9 ,열매어린이집 (풍납동) (풍납2동)', '02', '473', '2311', 18)
2021-08-18 17:41:07,992 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,993 INFO sqlalchemy.engine.base.Engine ('용산교회어린이집', '서민지', '서울특별시 용산구 원효로1가 백범로77길 36 (원효로제1동)', '02', '3272', '9521', 21)
2021-08-18 17:41:07,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,994 INFO sqlalchemy.engine.base.Engine ('태화어린이집', '장예준', '서울특별시 강남구 광평로 185 ,태화기독교사회복지관 내 (수서동) (일원본동)', '02', '2040', '1680', 1)
2021-08-18 17:41:07,995 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,995 INFO sqlalchemy.engine.base.Engine ('서울YMCA방화어린이집', '오혜진', '서울특별시 강서구 개화동로21길 4 ,방화11단지아파트 내 서울YMCA방화어린이집 (방화동) (방화제2동)', '02', '2661', '0255', 4)
2021-08-18 17:41:07,997 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:07,998 INFO sqlalchemy.engine.base.Engine ('앨리스어린이집', '안지원', '서울특별시 강동구 고덕로20가길 21 ,(암사1동 457-43) (암사제1동)', '02', '3427', '3347', 2)
2021-08-18 17:41:08,001 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,001 INFO sqlalchemy.engine.base.Engine ('개나리어린이집', '전정운', '서울특별시 송파구 성내천로 189 ,(마천동) (마천2동)', '02', '403', '7365', 18)
2021-08-18 17:41:08,002 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,003 INFO sqlalchemy.engine.base.Engine ('새동원어린이집', '안상철', '서울특별시 관악구 남부순환로163가길 10 ,1-3층 (신림동) [신사동] (신사동)', '02', '857', '7777', 5)
2021-08-18 17:41:08,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,004 INFO sqlalchemy.engine.base.Engine ('선화어린이집', '권성호', '서울특별시 은평구 녹번로 66-6 (녹번동)', '02', '355', '7056', 22)

2021-08-18 17:41:08,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,005 INFO sqlalchemy.engine.base.Engine ('해오름어린이집', '임민재', '서울특별시 광진구 자양로50가길 41 ,(구의동) (구의제2동)', '02', '456', '4242', 6)
2021-08-18 17:41:08,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,007 INFO sqlalchemy.engine.base.Engine ('해솔어린이집', '이민지', '서울특별시 강서구 양천로57길 37 ,가양4단지아파트 가양4종합사회복지관 연세어린이집 (가양동) (가양제2동)', '02', '2659', '6097', 4)
2021-08-18 17:41:08,008 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,009 INFO sqlalchemy.engine.base.Engine ('서교어린이집', '최정호', '서울특별시 마포구 월드컵북로7길 43 ,(서교동) (서교동)', '02', '332', '9285', 13)
2021-08-18 17:41:08,010 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,011 INFO sqlalchemy.engine.base.Engine ('구립 신정어린이집', '한영일', '서울특별시 양천구 신정중앙로 36 ,(신정동) (신정4동)', '02', '2606', '0755', 19)
2021-08-18 17:41:08,012 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,013 INFO sqlalchemy.engine.base.Engine ('청진어린이집', '박성수', '서울특별시 관악구 신림로36길 23-11 ,(신림동) [서림동] (서림동)', '02', '872', '6677', 5)
2021-08-18 17:41:08,014 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,015 INFO sqlalchemy.engine.base.Engine ('함께하는어린이집', '오현준', '서울특별시 양천구 월정로 20 ,2층 (신월2동)', '02', '2699', '0438', 19)
2021-08-18 17:41:08,016 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,017 INFO sqlalchemy.engine.base.Engine ('봉화어린이집', '전민재', '서울특별시 중랑구 봉화산로 165 ,(상봉동,신내12단지아파트 내 신내종합사회복지관 1층) (상봉제1동)', '02', '3421', '2535', 25)
2021-08-18 17:41:08,021 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,022 INFO sqlalchemy.engine.base.Engine ('예아랑어린이집', '박병철', '서울특별시 광진구 동일로 456 ,성수교회 2층 1호(중곡동) (중곡제3동)', '02', '2207', '5292', 6)
2021-08-18 17:41:08,023 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,023 INFO sqlalchemy.engine.base.Engine ('은초롱어린이집', '권영철', '서울특별시 강북구 솔매로50가길 9 ,(미아동) (송중동)', '02', '982', '5300', 3)
2021-08-18 17:41:08,026 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,027 INFO sqlalchemy.engine.base.Engine ('우정어린이집', '안민지', '서울특별시 노원구 동일로214길 21 ,406동 101호(상계동, 주공아파트) (상계6.7동)', '02', '952', '9395', 9)
2021-08-18 17:41:08,027 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,028 INFO sqlalchemy.engine.base.Engine ('천사어린이집', '류지혜', '서울특별시 중랑구 사가정로64길 10-4 ,(면목동) (면목제7동)', '02', '2207', '8004', 25)
2021-08-18 17:41:08,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,030 INFO sqlalchemy.engine.base.Engine ('구립동산어린이집', '류지민', '서울특별시 금천구 탑골로 26 ,(시흥동) (시흥제5동)', '02', '896', '1004', 8)
2021-08-18 17:41:08,031 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,032 INFO sqlalchemy.engine.base.Engine ('리라키즈스쿨어린이집', '박상훈', '서울특별시 관악구 남부순환로163가길 37 ,(신림동) [신사동] (신사동)', '02', '869', '7770', 5)
2021-08-18 17:41:08,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,033 INFO sqlalchemy.engine.base.Engine ('신당삼성어린이집', '권순자', '서울특별시 중구 동호로15길 21-36 (다산동)', '02', '2233', '6925', 24)
2021-08-18 17:41:08,034 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,035 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '서경숙', '서울특별시 강서구 양천로 489 ,104동 101호(가양동, 가양우성아파트) (가양제2동)', '02', '3662', '8693', 4)
2021-08-18 17:41:08,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,037 INFO sqlalchemy.engine.base.Engine ('연꽃어린이집', '황민수', '서울특별시 구로구 디지털로31길 109 (구로제3동)', '02', '852', '5332', 7)
2021-08-18 17:41:08,039 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,039 INFO sqlalchemy.engine.base.Engine ('점프어린이집', '장영진', '서울특별시 중랑구 동일로112길 21 ,(상봉동) (상봉제2동)', '02', '495', '8787', 25)
2021-08-18 17:41:08,040 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,041 INFO sqlalchemy.engine.base.Engine ('양천삼성어린이집', '전지훈', '서울특별시 양천구 목동동로8길 36 ,(신정동) (신정6동)', '02', '2648', '3272', 19)
2021-08-18 17:41:08,042 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,042 INFO sqlalchemy.engine.base.Engine ('강일어린이집', '송광수', '서울특별시 강동구 풍산로 235 ,서울시 강동구 강일동669-1(강일동 348-1) (강일동)', '02', '430', '7079', 2)
2021-08-18 17:41:08,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,044 INFO sqlalchemy.engine.base.Engine ('새꼬예미어린이집', '정정호', '서울특별시 강동구 천중로35길 98 (천호제1동)', '02', '479', '3054', 2)
2021-08-18 17:41:08,045 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,045 INFO sqlalchemy.engine.base.Engine ('구립샛별어린이집', '서순자', '서울특별시 동작구 성대로27길 12 ,(상도동) (상도제4동)', '02', '823', '2482', 12)
2021-08-18 17:41:08,047 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,048 INFO sqlalchemy.engine.base.Engine ('숭일어린이집', '전준호', '서울특별시 종로구 종로 381-1 (숭인제2동)', '02', '742', '5706', 23)
2021-08-18 17:41:08,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,049 INFO sqlalchemy.engine.base.Engine ('참솔아이어린이집', '오상훈', '서울특별시 도봉구 시루봉로13가길 23-19 ,101호 (방학동) (방학제2동)', '02', '956', '5758', 10)
2021-08-18 17:41:08,053 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,054 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '서지혜', '서울특별시 관악구 법원단지5길 18 ,1층 (신림동) [미성동] (미성동)', '02', '851', '0539', 5)
2021-08-18 17:41:08,056 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,057 INFO sqlalchemy.engine.base.Engine ('어린별삐아제어린이집', '황민지', '서울특별시 노원구 마들로 31 ,118동 102호(월계동, 한진한화그랑빌) (월계3동)', '02', '949', '9100', 9)

2021-08-18 17:41:08,058 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,059 INFO sqlalchemy.engine.base.Engine ('상록어린이집', '황영식', '서울특별시 용산구 백범로45길 4 ,(효창동) (효창동)', '02', '715', '1009', 21)
2021-08-18 17:41:08,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,060 INFO sqlalchemy.engine.base.Engine ('아기나라어린이집', '안은영', '서울특별시 마포구 월드컵로31길 77 ,(망원동) 우림아파트 106호 (망원제2동)', '02', '324', '0966', 13)
2021-08-18 17:41:08,062 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,063 INFO sqlalchemy.engine.base.Engine ('구립 동교어린이집', '박정순', '서울특별시 마포구 와우산로37길 16 ,동교 어린이집 (동교동) (서교동)', '02', '338', '8907', 13)
2021-08-18 17:41:08,064 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,065 INFO sqlalchemy.engine.base.Engine ('별밭어린이집', '안지영', '서울특별시 강북구 도봉로29길 63-5 ,(미아동) (송천동)', '02', '987', '3372', 3)
2021-08-18 17:41:08,066 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,067 INFO sqlalchemy.engine.base.Engine ('믿음어린이집', '오혜진', '서울특별시 노원구 섬밭로 196 ,, 607동 102호(하계2동 장미아파트) (하계2동)', '02', '6061', '5075', 9)
2021-08-18 17:41:08,068 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,069 INFO sqlalchemy.engine.base.Engine ('선재어린이집', '정지혜', '서울특별시 강남구 삼성로71길 31 ,선재어린이집 (대치동) (대치제4동)', '02', '561', '3421', 1)
2021-08-18 17:41:08,070 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,071 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '조혜진', '서울특별시 은평구 갈현로23길 10-1 (갈현제2동)', '02', '357', '8283', 22)
2021-08-18 17:41:08,072 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,074 INFO sqlalchemy.engine.base.Engine ('기쁨어린이집', '박미영', '서울특별시 강북구 한천로105길 23 ,109동 106호(번동, 주공1단지아파트) (번3동)', '02', '987', '8437', 3)
2021-08-18 17:41:08,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,077 INFO sqlalchemy.engine.base.Engine ('에이비시어린이집', '황예은', '서울특별시 송파구 올림픽로 435 ,115동 103호(신천동, 파크리오아파트) (잠실4동)', '02', '489', '2840', 18)
2021-08-18 17:41:08,078 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,079 INFO sqlalchemy.engine.base.Engine ('세빛어린이집', '안혜진', '서울특별시 은평구 갈현로29길 33 (갈현제2동)', '02', '387', '5004', 22)
2021-08-18 17:41:08,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,080 INFO sqlalchemy.engine.base.Engine ('자연아이어린이집', '정영길', '서울특별시 은평구 진흥로1길 60-5 ,(역촌동) (역촌동)', '02', '308', '1004', 22)
2021-08-18 17:41:08,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,083 INFO sqlalchemy.engine.base.Engine ('기린어린이집', '오도현', '서울특별시 강동구 구천면로 278 ,동아하이빌아파트 관리동 (천호동 217-132 ) (천호제1동)', '02', '472', '7395', 2)
2021-08-18 17:41:08,085 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,085 INFO sqlalchemy.engine.base.Engine ('아이숲어린이집', '윤지은', '서울특별시 노원구 공릉로34길 38 ,1020동 102호(공릉동, 태강) (공릉2동)', '02', '975', '1535', 9)
2021-08-18 17:41:08,086 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,087 INFO sqlalchemy.engine.base.Engine ('구립 한빛어린이집', '강준호', '서울특별시 양천구 신월로11길 16 ,(신월동) (신월4동)', '02', '2690', '8543', 19)
2021-08-18 17:41:08,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,089 INFO sqlalchemy.engine.base.Engine ('신영광어린이집', '윤건우', '서울특별시 강서구 공항대로43길 104 ,주공아파트 8단지관리사무소2층 (등촌동) (등촌제3동)', '02', '2658', '2592', 4)
2021-08-18 17:41:08,090 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,091 INFO sqlalchemy.engine.base.Engine ('솔향기어린이집', '권지민', '서울특별시 관악구 난곡로15길 22-4 ,(신림동) [난곡동] (난곡동)', '02', '864', '9363', 5)
2021-08-18 17:41:08,092 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,093 INFO sqlalchemy.engine.base.Engine ('하나어린이집', '이영자', '서울특별시 관악구 신사로10길 30 ,지하1층, 지상4층 (신림동) [신사동] (신사동)', '02', '838', '6224', 5)
2021-08-18 17:41:08,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,095 INFO sqlalchemy.engine.base.Engine ('어린왕자어린이집', '이지훈', '서울특별시 강서구 강서로18가길 25 ,(화곡동) (화곡제8동)', '02', '2602', '7607', 4)
2021-08-18 17:41:08,095 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,096 INFO sqlalchemy.engine.base.Engine ('은초록어린이집', '황건우', '서울특별시 강서구 공항대로39길 59 ,은초록어린이집 (등촌동) (등촌제3동)', '02', '3662', '3339', 4)
2021-08-18 17:41:08,097 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,098 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '강민수', '서울특별시 금천구 독산로 279 ,1층 (독산동) (독산제3동)', '02', '864', '4105', 8)
2021-08-18 17:41:08,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,100 INFO sqlalchemy.engine.base.Engine ('예지원어린이집', '김준호', '서울특별시 은평구 응암로21가길 12 ,(응암동) (응암제3동)', '02', '359', '1288', 22)
2021-08-18 17:41:08,102 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,102 INFO sqlalchemy.engine.base.Engine ('구립 성수어린이집', '박정식', '서울특별시 성동구 광나루로2길 14 ,(성수동2가) (성수2가제3동)', '02', '498', '6715', 16)
2021-08-18 17:41:08,103 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,104 INFO sqlalchemy.engine.base.Engine ('구립하난곡어린이집', '최동현', '서울특별시 관악구 난우10가길 2 ,(신림동) [미성동] (미성동)', '02', '866', '5363', 5)
2021-08-18 17:41:08,105 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,105 INFO sqlalchemy.engine.base.Engine ('신나는어린이집', '최서연', '서울특별시 노원구 월계로 372 ,(월계동 사슴아파트 1단지) (월계3동)', '02', '975', '7888', 9)
2021-08-18 17:41:08,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,107 INFO sqlalchemy.engine.base.Engine ('KBS어린이집', '최민지', '서울특별시 영등포구 여의공원로 13 (여의동)', '02', '781', '2496', 20)

2021-08-18 17:41:08,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,109 INFO sqlalchemy.engine.base.Engine ('민주어린이집', '이수빈', '서울특별시 광진구 동일로26길 47 ,(화양동) (화양동)', '02', '469', '1956', 6)
2021-08-18 17:41:08,110 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,111 INFO sqlalchemy.engine.base.Engine ('장위어린이집', '안준서', '서울특별시 성북구 장월로6길 28 ,(장위동) (장위제2동)', '02', '918', '1184', 17)
2021-08-18 17:41:08,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,112 INFO sqlalchemy.engine.base.Engine ('향기어린이집', '안영숙', '서울특별시 노원구 한글비석로44길 42 ,(상계동) (상계5동)', '02', '951', '6246', 9)
2021-08-18 17:41:08,113 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,114 INFO sqlalchemy.engine.base.Engine ('구립신바람어린이집', '한준서', '서울특별시 강동구 성안로13길 56 ,(성내동 508-1) (성내제2동)', '02', '478', '2554', 2)
2021-08-18 17:41:08,115 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,116 INFO sqlalchemy.engine.base.Engine ('사랑나무어린이집', '임지훈', '서울특별시 중랑구 용마산로 616 ,101동 101호(신내동, 새한아파트) (신내1동)', '02', '3421', '7383', 25)
2021-08-18 17:41:08,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,118 INFO sqlalchemy.engine.base.Engine ('강북몬테소리어린이집', '이영일', '서울특별시 강북구 도봉로35길 16 ,318동 3호(미아동) (송천동)', '02', '989', '8761', 3)
2021-08-18 17:41:08,119 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,120 INFO sqlalchemy.engine.base.Engine ('양재2동어린이집', '정정수', '서울특별시 서초구 강남대로8길 66-15 (양재2동)', '02', '574', '1214', 15)
2021-08-18 17:41:08,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,122 INFO sqlalchemy.engine.base.Engine ('동화마을어린이집', '윤건우', '서울특별시 동대문구 망우로14길 18 ,2층 동화마을 어린이집 (휘경제2동)', '02', '2245', '5141', 11)
2021-08-18 17:41:08,125 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,125 INFO sqlalchemy.engine.base.Engine ('구립구의3동어린이집', '김경자', '서울특별시 광진구 광나루로54길 36 ,(구의동) (구의제3동)', '02', '457', '9230', 6)
2021-08-18 17:41:08,127 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,128 INFO sqlalchemy.engine.base.Engine ('구립동산어린이집', '윤은경', '서울특별시 관악구 대학14길 56 ,(신림동) [대학동] (대학동)', '02', '871', '6472', 5)
2021-08-18 17:41:08,130 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,130 INFO sqlalchemy.engine.base.Engine ('꼬망세어린이집', '정영환', '서울특별시 노원구 동일로227길 26 ,1616동 107호(상계동, 상계주공16차) (상계8동)', '070', '7530', '4161', 9)
2021-08-18 17:41:08,131 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,132 INFO sqlalchemy.engine.base.Engine ('가회어린이집', '정민석', '서울특별시 종로구 북촌로12길 12-2 ,가회어린이집 (가회동) (가회동)', '02', '3673', '2085', 23)
2021-08-18 17:41:08,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,134 INFO sqlalchemy.engine.base.Engine ('꿈나무키즈어린이집', '신민지', '서울특별시 강북구 덕릉로40길 14 ,(번동) (번2동)', '02', '981', '0116', 3)
2021-08-18 17:41:08,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,140 INFO sqlalchemy.engine.base.Engine ('예주어린이집', '서상훈', '서울특별시 강북구 삼양로 256 ,104동 104호(미아동, 미아래미안1차) (삼양동)', '02', '984', '0386', 3)
2021-08-18 17:41:08,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,141 INFO sqlalchemy.engine.base.Engine ('24시간연세어린이집', '한준혁', '서울특별시 관악구 관악로 246 ,(봉천동) [행운동] (행운동)', '02', '876', '0333', 5)
2021-08-18 17:41:08,142 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,144 INFO sqlalchemy.engine.base.Engine ('대신어린이집', '김병철', '서울특별시 서대문구 성산로 570 ,(신촌동) (신촌동)', '02', '393', '1357', 14)
2021-08-18 17:41:08,145 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,146 INFO sqlalchemy.engine.base.Engine ('구립청소년회관어린이집', '이은정', '서울특별시 강동구 양재대로138길 41 ,(명일동 327-6) (명일제1동)', '02', '3426', '6214', 2)
2021-08-18 17:41:08,147 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,147 INFO sqlalchemy.engine.base.Engine ('새빛어린이집', '박성민', '서울특별시 성북구 한천로72길 27 ,(석관동) (석관동)', '02', '969', '0578', 17)
2021-08-18 17:41:08,149 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,150 INFO sqlalchemy.engine.base.Engine ('구립 목동어린이집', '장영진', '서울특별시 양천구 목동서로8길 32 ,(목동) (목5동)', '02', '2651', '6005', 19)
2021-08-18 17:41:08,151 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,152 INFO sqlalchemy.engine.base.Engine ('둘리어린이집', '전미경', '서울특별시 노원구 동일로208길 20 ,211동 110호(중계동, 중계무지개아파트) (중계2.3동)', '02', '976', '0507', 9)
2021-08-18 17:41:08,153 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,154 INFO sqlalchemy.engine.base.Engine ('초롱별어린이집', '한민서', '서울특별시 노원구 섬밭로 190 ,608동 102호(하계동, 장미) (하계2동)', '02', '976', '3663', 9)
2021-08-18 17:41:08,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,155 INFO sqlalchemy.engine.base.Engine ('신대림어린이집', '전지영', '서울특별시 영등포구 디지털로 455-7 (대림제1동)', '02', '833', '9600', 20)
2021-08-18 17:41:08,156 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,157 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '조도현', '서울특별시 동대문구 휘경로 45 ,(휘경동) (휘경제1동)', '02', '965', '0471', 11)
2021-08-18 17:41:08,159 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,160 INFO sqlalchemy.engine.base.Engine ('삼육서울병원직장어린이집', '박예준', '서울특별시 동대문구 망우로 82 (휘경제2동)', '02', '2210', '3238', 11)
2021-08-18 17:41:08,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,163 INFO sqlalchemy.engine.base.Engine ('영화사어린이집', '정성진', '서울특별시 광진구 영화사로 105 ,(구의동) (구의제2동)', '02', '453', '5149', 6)

2021-08-18 17:41:08,164 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,165 INFO sqlalchemy.engine.base.Engine ('도원어린이집', '최서현', '서울특별시 용산구 효창원로37마길 8 ,도원어린이집 (용문동) (용문동)', '02', '701', '1284', 21)
2021-08-18 17:41:08,166 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,167 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '신영식', '서울특별시 성북구 오패산로 21 (월곡제1동)', '02', '916', '9132', 17)
2021-08-18 17:41:08,169 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,170 INFO sqlalchemy.engine.base.Engine ('성심어린이집', '이지원', '서울특별시 강동구 천호대로193길 23-3 ,(길동 401-2) (길동)', '02', '473', '5408', 2)
2021-08-18 17:41:08,171 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,171 INFO sqlalchemy.engine.base.Engine ('열린어린이집', '안민재', '서울특별시 성북구 보국문로 19 ,102동 102호(정릉동, 대우푸르지오아파트) (정릉제2동)', '02', '915', '4210', 17)
2021-08-18 17:41:08,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,173 INFO sqlalchemy.engine.base.Engine ('새한어린이집', '이성호', '서울특별시 송파구 도곡로62길 21 ,(잠실동) (잠실본동)', '02', '414', '9363', 18)
2021-08-18 17:41:08,174 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,175 INFO sqlalchemy.engine.base.Engine ('시흥삐아제어린이집', '박경자', '서울특별시 금천구 독산로27길 33 ,(시흥동) (시흥제1동)', '02', '804', '4590', 8)
2021-08-18 17:41:08,176 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,177 INFO sqlalchemy.engine.base.Engine ('삼성서울병원 어린이집', '최건우', '서울특별시 강남구 광평로31길 66 ,(수서동) (일원본동)', '02', '3411', '9141', 1)
2021-08-18 17:41:08,178 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,179 INFO sqlalchemy.engine.base.Engine ('후암어린이집', '안영식', '서울특별시 용산구 두텁바위로1길 86 ,(후암동) (후암동)', '02', '752', '7223', 21)
2021-08-18 17:41:08,180 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,181 INFO sqlalchemy.engine.base.Engine ('로마어린이집', '장예준', '서울특별시 양천구 오목로38길 16 ,101동 102호(신정동, 로마아파트) (신정4동)', '02', '2691', '7442', 19)
2021-08-18 17:41:08,182 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,183 INFO sqlalchemy.engine.base.Engine ('꾸러기동산어린이집', '장은영', '서울특별시 노원구 섬밭로 190 ,606동 102호(하계동, 장미) (하계2동)', '02', '972', '3372', 9)
2021-08-18 17:41:08,184 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,184 INFO sqlalchemy.engine.base.Engine ('구립 구일어린이집', '오영철', '서울특별시 구로구 구일로 62 ,(구로동) (구로제1동)', '02', '830', '4673', 7)
2021-08-18 17:41:08,185 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,186 INFO sqlalchemy.engine.base.Engine ('미리내어린이집', '정순자', '서울특별시 노원구 동일로 1127 ,1동(공릉동, 공릉) (공릉1동)', '02', '976', '2731', 9)
2021-08-18 17:41:08,187 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,188 INFO sqlalchemy.engine.base.Engine ('아이소리어린이집', '조영진', '서울특별시 구로구 고척로 85 ,101-102(개봉동, 거성푸르뫼아파트1차) (개봉제1동)', '02', '2688', '8897', 7)
2021-08-18 17:41:08,189 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,190 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '임정운', '서울특별시 서초구 서리풀6길 28-4 ,(서초동) (서초1동)', '02', '525', '5164', 15)
2021-08-18 17:41:08,191 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,192 INFO sqlalchemy.engine.base.Engine ('꿈동이어린이집', '윤영진', '서울특별시 은평구 증산로19길 8-8 ,(신사동) (신사제1동)', '02', '308', '4399', 22)
2021-08-18 17:41:08,193 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,194 INFO sqlalchemy.engine.base.Engine ('동화나라어린이집', '임정호', '서울특별시 중구 다산로38길 80 ,(신당동) (동화동)', '02', '2236', '5156', 24)
2021-08-18 17:41:08,195 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,196 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '이성수', '서울특별시 강서구 가로공원로76가길 53 ,2층 (화곡동) (화곡제1동)', '02', '2693', '6028', 4)
2021-08-18 17:41:08,197 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,198 INFO sqlalchemy.engine.base.Engine ('알콩달콩어린이집', '신경숙', '서울특별시 강동구 양재대로102길 35-1 ,(둔촌동 429-4) (둔촌제2동)', '02', '479', '0612', 2)
2021-08-18 17:41:08,200 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,201 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '서영길', '서울특별시 중랑구 봉우재로 94-3 (면목제2동)', '02', '495', '0670', 25)
2021-08-18 17:41:08,202 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,203 INFO sqlalchemy.engine.base.Engine ('다산어린이집', '박진호', '서울특별시 중구 동호로15길 50 ,(신당동) (다산동)', '02', '2232', '6905', 24)
2021-08-18 17:41:08,204 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,204 INFO sqlalchemy.engine.base.Engine ('구립노량진2동어린이집', '김예준', '서울특별시 동작구 장승배기로15길 21 ,(노량진동) (노량진제2동)', '02', '821', '4756', 12)
2021-08-18 17:41:08,205 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,206 INFO sqlalchemy.engine.base.Engine ('서울대학교병원어린이집', '한지혜', '서울특별시 종로구 동숭3길 40 (이화동)', '02', '2072', '2260', 23)
2021-08-18 17:41:08,207 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,207 INFO sqlalchemy.engine.base.Engine ('안델센어린이집', '강민수', '서울특별시 관악구 인헌6길 26 ,2층 (봉천동) [인헌동] (인헌동)', '02', '882', '7163', 5)
2021-08-18 17:41:08,208 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,209 INFO sqlalchemy.engine.base.Engine ('예슬어린이집', '류영진', '서울특별시 동작구 사당로16아길 46 ,(사당4동 291-5) (사당제4동)', '02', '588', '8777', 12)
2021-08-18 17:41:08,212 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,214 INFO sqlalchemy.engine.base.Engine ('곤지잼잼 어린이집', '최도현', '서울특별시 성동구 성수동2가 성수일로10길 33 ,1층 (성수동2가, 성락교회) (성수2가제3동)', '02', '468', '0140', 16)

2021-08-18 17:41:08,216 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,217 INFO sqlalchemy.engine.base.Engine ('성혜어린이집', '최준호', '서울특별시 관악구 난곡로16길 30-6 ,(신림동) [난곡동] (난곡동)', '02', '863', '3932', 5)
2021-08-18 17:41:08,218 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,219 INFO sqlalchemy.engine.base.Engine ('성모어린이집', '최경숙', '서울특별시 강서구 공항대로43길 104 ,주공아파트 7단지 등촌7복지관 성모어린이집 (등촌동) (등촌제3동)', '02', '2658', '6524', 4)
2021-08-18 17:41:08,221 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,221 INFO sqlalchemy.engine.base.Engine ('구립 금사어린이집', '오지혜', '서울특별시 성동구 독서당로46길 26 ,(금호동4가) (금호4가동)', '02', '2293', '4544', 16)
2021-08-18 17:41:08,223 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,224 INFO sqlalchemy.engine.base.Engine ('구립 불광어린이집', '류정수', '서울특별시 은평구 연서로34길 28 ,(불광동) (불광제2동)', '02', '389', '3122', 22)
2021-08-18 17:41:08,225 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,226 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '장지은', '서울특별시 금천구 독산로 251 ,1층 은혜어린이집 (독산제4동)', '02', '867', '0691', 8)
2021-08-18 17:41:08,228 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,229 INFO sqlalchemy.engine.base.Engine ('한나영아어린이집', '최경숙', '서울특별시 노원구 노원로19길 23 ,408동 108호(중계동, 목화4단지아파트) (중계2.3동)', '02', '971', '1519', 9)
2021-08-18 17:41:08,230 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,230 INFO sqlalchemy.engine.base.Engine ('국회제1어린이집', '이준혁', '서울특별시 영등포구 의사당대로 1 ,국회제1어린이집 (여의동)', '02', '6788', '3294', 20)
2021-08-18 17:41:08,232 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,232 INFO sqlalchemy.engine.base.Engine ('정릉1동어린이집', '정정호', '서울특별시 성북구 정릉로 300 ,(정릉동) (정릉제1동)', '02', '917', '3867', 17)
2021-08-18 17:41:08,234 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,234 INFO sqlalchemy.engine.base.Engine ('신나라어린이집', '장정남', '서울특별시 송파구 백제고분로22길 3-5 (삼전동)', '02', '2202', '4598', 18)
2021-08-18 17:41:08,235 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,236 INFO sqlalchemy.engine.base.Engine ('구립기쁨어린이집', '임정남', '서울특별시 금천구 범안로12길 63-3 ,(독산동) (독산제1동)', '02', '895', '8225', 8)
2021-08-18 17:41:08,237 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,238 INFO sqlalchemy.engine.base.Engine ('푸른어린이집', '류정수', '서울특별시 강서구 화곡로63가길 92 ,(등촌동) (등촌제3동)', '02', '2658', '5513', 4)
2021-08-18 17:41:08,239 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,239 INFO sqlalchemy.engine.base.Engine ('성미어린이집', '오상철', '서울특별시 마포구 월드컵로26길 9 ,(성산동) (성산제1동)', '02', '3141', '2833', 13)
2021-08-18 17:41:08,240 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,241 INFO sqlalchemy.engine.base.Engine ('회현어린이집', '한수빈', '서울특별시 중구 퇴계로12가길 23 ,(회현동1가) (회현동)', '02', '757', '0896', 24)
2021-08-18 17:41:08,243 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,244 INFO sqlalchemy.engine.base.Engine ('둥근마음어린이집', '임은영', '서울특별시 강서구 강서로68길 36 ,주공1단지내 둥근마음어린이집 (등촌동) (등촌제3동)', '02', '2658', '7077', 4)
2021-08-18 17:41:08,246 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,246 INFO sqlalchemy.engine.base.Engine ('우면어린이집', '서정남', '서울특별시 서초구 바우뫼로7길 11 ,주공아파트 (우면동) (양재1동)', '02', '573', '7347', 15)
2021-08-18 17:41:08,248 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,249 INFO sqlalchemy.engine.base.Engine ('또래또래어린이집', '박민재', '서울특별시 강동구 고덕로20마길 38 ,(암사동 470-7) (암사제1동)', '02', '441', '1148', 2)
2021-08-18 17:41:08,250 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,251 INFO sqlalchemy.engine.base.Engine ('구립볏고을어린이집', '서지영', '서울특별시 강서구 화곡로58길 100 ,(화곡동) (화곡제6동)', '02', '2605', '4098', 4)
2021-08-18 17:41:08,252 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,253 INFO sqlalchemy.engine.base.Engine ('예승아트스쿨어린이집', '송민석', '서울특별시 영등포구 신길로42길 10 (신길제4동)', '02', '846', '4422', 20)
2021-08-18 17:41:08,254 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,254 INFO sqlalchemy.engine.base.Engine ('요셉어린이집', '김정순', '서울특별시 구로구 디지털로27다길 20 ,요셉어린이집 (구로제3동)', '02', '857', '8546', 7)
2021-08-18 17:41:08,256 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,256 INFO sqlalchemy.engine.base.Engine ('방이하나어린이집', '황서현', '서울특별시 송파구 올림픽로32길 57-9 ,101호 (방이2동)', '02', '415', '1489', 18)
2021-08-18 17:41:08,257 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,258 INFO sqlalchemy.engine.base.Engine ('송중어린이집', '송정수', '서울특별시 서대문구 가좌로 56 ,(홍은동) (홍은제2동)', '02', '372', '0654', 14)
2021-08-18 17:41:08,260 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,261 INFO sqlalchemy.engine.base.Engine ('아이스타어린이집', '장상철', '서울특별시 강북구 삼양로114길 14 ,(수유동) (수유2동)', '02', '991', '4379', 3)
2021-08-18 17:41:08,263 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,264 INFO sqlalchemy.engine.base.Engine ('상록어린이집', '오예준', '서울특별시 강서구 금낭화로23길 25 ,(방화동) (방화제3동)', '02', '2661', '4700', 4)
2021-08-18 17:41:08,265 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,266 INFO sqlalchemy.engine.base.Engine ('구립 즐거운어린이집', '류민수', '서울특별시 양천구 신월로24길 19 ,신월종합사회복지관 1층 (신월2동)', '02', '2697', '8513', 19)
2021-08-18 17:41:08,268 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,268 INFO sqlalchemy.engine.base.Engine ('도화어린이집', '신성수', '서울특별시 마포구 새창로4다길 18 ,(도화동) (도화동)', '070', '4607', '4607', 13)

2021-08-18 17:41:08,270 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,270 INFO sqlalchemy.engine.base.Engine ('새날어린이집', '이성호', '서울특별시 구로구 구로중앙로3길 10 ,(구로동) (구로제4동)', '02', '851', '5932', 7)
2021-08-18 17:41:08,271 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,272 INFO sqlalchemy.engine.base.Engine ('구립상록어린이집', '송정남', '서울특별시 관악구 신원로2길 4-7 ,(신림동) [신원동] (신원동)', '02', '852', '3851', 5)
2021-08-18 17:41:08,273 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,274 INFO sqlalchemy.engine.base.Engine ('송파제일어린이집', '송성수', '서울특별시 송파구 가락로23길 9 (송파1동)', '02', '423', '6128', 18)
2021-08-18 17:41:08,275 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,276 INFO sqlalchemy.engine.base.Engine ('삼성아이마루어린이집', '서예은', '서울특별시 마포구 백범로25길 63 ,삼성래미안아파트 관리동 (염리동)', '02', '3275', '0667', 13)
2021-08-18 17:41:08,277 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,278 INFO sqlalchemy.engine.base.Engine ('사임당어린이집', '신민지', '서울특별시 광진구 아차산로46가길 23 ,(자양동) 101호 (자양제1동)', '02', '455', '0883', 6)
2021-08-18 17:41:08,280 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,280 INFO sqlalchemy.engine.base.Engine ('엄지어린이집', '황영환', '서울특별시 노원구 한글비석로 89 ,108동 101호(하계동, 하계청구1차아파트) (하계1동)', '02', '971', '5335', 9)
2021-08-18 17:41:08,282 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,283 INFO sqlalchemy.engine.base.Engine ('자람어린이집', '안정호', '서울특별시 강남구 일원로5길 29 ,(일원동) (일원제1동)', '02', '3411', '2555', 1)
2021-08-18 17:41:08,284 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,284 INFO sqlalchemy.engine.base.Engine ('무궁화어린이집', '윤예준', '서울특별시 송파구 백제고분로48길 20 ,(방이동) (방이2동)', '02', '413', '4018', 18)
2021-08-18 17:41:08,285 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,286 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '이영길', '서울특별시 동작구 성대로6길 27 ,(상도동) (상도제3동)', '02', '821', '4359', 12)
2021-08-18 17:41:08,286 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,287 INFO sqlalchemy.engine.base.Engine ('한신예쁜어린이집', '한지영', '서울특별시 도봉구 마들로 859-19 ,111동 110호(도봉동, 도봉한신아파트) (도봉제2동)', '02', '955', '3896', 10)
2021-08-18 17:41:08,288 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,289 INFO sqlalchemy.engine.base.Engine ('구립 망원어린이집', '강미숙', '서울특별시 마포구 동교로 47-9 (망원제1동)', '02', '338', '2232', 13)
2021-08-18 17:41:08,289 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,290 INFO sqlalchemy.engine.base.Engine ('어깨동무어린이집', '윤정수', '서울특별시 영등포구 영신로13길 8 ,(영등포동) (영등포본동)', '02', '833', '7326', 20)
2021-08-18 17:41:08,291 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,292 INFO sqlalchemy.engine.base.Engine ('구립 곰달래어린이집', '권은정', '서울특별시 양천구 남부순환로65길 2 ,(신월동) (신월1동)', '02', '2695', '9765', 19)
2021-08-18 17:41:08,293 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,294 INFO sqlalchemy.engine.base.Engine ('구립 청솔어린이집', '박영식', '서울특별시 양천구 등촌로 192 ,(목동) (목3동)', '02', '2652', '7293', 19)
2021-08-18 17:41:08,295 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,296 INFO sqlalchemy.engine.base.Engine ('구립번1동어린이집', '장경숙', '서울특별시 강북구 도봉로96길 5-6 (번1동)', '02', '992', '0331', 3)
2021-08-18 17:41:08,297 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,298 INFO sqlalchemy.engine.base.Engine ('구립시흥5동어린이집', '박순자', '서울특별시 금천구 독산로10길 24 ,(시흥동) (시흥제5동)', '02', '892', '2415', 8)
2021-08-18 17:41:08,300 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,301 INFO sqlalchemy.engine.base.Engine ('봉일어린이집', '박영자', '서울특별시 관악구 구암5길 14 ,봉일교회 [성현동] (봉천동) (성현동)', '02', '889', '3596', 5)
2021-08-18 17:41:08,302 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,303 INFO sqlalchemy.engine.base.Engine ('중곡샛별어린이집', '오영철', '서울특별시 광진구 동일로 458 ,(중곡동) (중곡제3동)', '02', '435', '4900', 6)
2021-08-18 17:41:08,305 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,305 INFO sqlalchemy.engine.base.Engine ('하나린어린이집', '조성진', '서울특별시 중랑구 겸재로24길 41 ,(면목동) (면목제5동)', '02', '492', '6440', 25)
2021-08-18 17:41:08,307 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,315 INFO sqlalchemy.engine.base.Engine ('구립 역촌어린이집', '한상철', '서울특별시 은평구 진흥로7길 8-9 (역촌동)', '02', '388', '5612', 22)
2021-08-18 17:41:08,316 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,317 INFO sqlalchemy.engine.base.Engine ('야호은물어린이집', '서서연', '서울특별시 송파구 올림픽로 525 ,103동 101호(풍납동, 현대아파트) (풍납2동)', '02', '484', '5955', 18)
2021-08-18 17:41:08,317 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,318 INFO sqlalchemy.engine.base.Engine ('상계삼성어린이집', '류건우', '서울특별시 노원구 노원로34길 54 ,(상계동) (상계2동)', '02', '933', '5147', 9)
2021-08-18 17:41:08,319 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,319 INFO sqlalchemy.engine.base.Engine ('화송어린이집', '최건우', '서울특별시 광진구 능동로13길 108 ,(화양동) (화양동)', '02', '468', '2336', 6)
2021-08-18 17:41:08,321 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,321 INFO sqlalchemy.engine.base.Engine ('슬기어린이집', '이준혁', '서울특별시 서대문구 북아현로24길 26 ,(북아현동) (충현동)', '02', '312', '8919', 14)
2021-08-18 17:41:08,324 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,325 INFO sqlalchemy.engine.base.Engine ('구립해맞이어린이집', '안정운', '서울특별시 강북구 도봉로30길 53 ,(미아동) (송중동)', '02', '986', '7533', 3)
2021-08-18 17:41:08,326 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,327 INFO sqlalchemy.engine.base.Engine ('상계어린이집', '전영철', '서울특별시 노원구 덕릉로115나길 25 ,(상계동) (상계3.4동)', '02', '936', '5010', 9)
2021-08-18 17:41:08,328 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,332 INFO sqlalchemy.engine.base.Engine ('아름어린이집', '한도현', '서울특별시 강남구 도곡로39길 6 ,(역삼동) (역삼제2동)', '02', '563', '5523', 1)
2021-08-18 17:41:08,333 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,334 INFO sqlalchemy.engine.base.Engine ('구립상도어린이집', '강영길', '서울특별시 동작구 양녕로36길 15 ,(상도동) (상도제1동)', '02', '825', '0505', 12)
2021-08-18 17:41:08,335 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,336 INFO sqlalchemy.engine.base.Engine ('사랑의어린이집', '김지훈', '서울특별시 광진구 아차산로66길 8 ,(광장동) (광장동)', '02', '2201', '1049', 6)
2021-08-18 17:41:08,337 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,339 INFO sqlalchemy.engine.base.Engine ('아기파랑새어린이집', '윤지영', '서울특별시 영등포구 선유서로21길 15 ,벽산상가 202동 203호 (양평제1동)', '02', '2634', '6264', 20)
2021-08-18 17:41:08,340 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,346 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '임순자', '서울특별시 강동구 천호대로182길 35 ,예지어린이집 (둔촌제2동)', '02', '485', '7602', 2)
2021-08-18 17:41:08,347 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,348 INFO sqlalchemy.engine.base.Engine ('은영어린이집', '신민지', '서울특별시 성북구 보문동3가 보문사길 18 ,1층 (보문동)', '02', '928', '9609', 17)
2021-08-18 17:41:08,349 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,350 INFO sqlalchemy.engine.base.Engine ('해피어린이집', '안광수', '서울특별시 강남구 광평로19길 10 ,까치마을아파트 관리동 (수서동) (일원본동)', '02', '451', '0515', 1)
2021-08-18 17:41:08,354 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,355 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '송정남', '서울특별시 송파구 송파대로 567 ,507동 104호(잠실동, 잠실주공5단지아파트) (잠실3동)', '02', '417', '2515', 18)
2021-08-18 17:41:08,356 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,357 INFO sqlalchemy.engine.base.Engine ('한솔어린이집', '오성호', '서울특별시 강남구 광평로10길 6 ,307동 101호(일원동, 한솔마을) (일원본동)', '02', '6677', '1585', 1)
2021-08-18 17:41:08,358 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,358 INFO sqlalchemy.engine.base.Engine ('영락어린이집', '김영길', '서울특별시 용산구 후암로4길 70 ,(후암동) (후암동)', '02', '775', '2157', 21)
2021-08-18 17:41:08,359 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,361 INFO sqlalchemy.engine.base.Engine ('배봉어린이집', '최영진', '서울특별시 동대문구 사가정로25길 51 ,(장안동) (장안제2동)', '02', '2217', '2070', 11)
2021-08-18 17:41:08,361 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,362 INFO sqlalchemy.engine.base.Engine ('평화어린이집', '김지은', '서울특별시 관악구 난곡로 333 ,(신림동) [조원동] (조원동)', '02', '857', '9834', 5)
2021-08-18 17:41:08,363 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,363 INFO sqlalchemy.engine.base.Engine ('구립 은하수어린이집', '류민수', '서울특별시 양천구 남부순환로33길 37 ,(신월동) (신월5동)', '02', '2603', '0286', 19)
2021-08-18 17:41:08,365 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,366 INFO sqlalchemy.engine.base.Engine ('즐거운어린이집', '김정식', '서울특별시 강서구 양천로57길 36 ,도시개발아파트 5단지 내 (가양동) (가양제2동)', '02', '2668', '7683', 4)
2021-08-18 17:41:08,367 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,368 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '이혜진', '서울특별시 광진구 광나루로15길 17 ,(군자동) (군자동)', '02', '467', '3333', 6)
2021-08-18 17:41:08,369 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,370 INFO sqlalchemy.engine.base.Engine ('구립 한별어린이집', '이영식', '서울특별시 양천구 목동동로10길 16-13 (신정2동)', '02', '2646', '2371', 19)
2021-08-18 17:41:08,370 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,371 INFO sqlalchemy.engine.base.Engine ('나나어린이집', '전성호', '서울특별시 은평구 통일로92길 36-1 (불광제2동)', '02', '352', '5033', 22)
2021-08-18 17:41:08,372 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,372 INFO sqlalchemy.engine.base.Engine ('삐아제어린이집', '황성호', '서울특별시 강남구 광평로47길 17 ,신동아아파트 관리동 (수서동)', '02', '451', '7370', 1)
2021-08-18 17:41:08,374 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,375 INFO sqlalchemy.engine.base.Engine ('세종어린이집', '이성민', '서울특별시 은평구 서오릉로17길 5 ,(구산동341-4) (구산동)', '02', '352', '6775', 22)
2021-08-18 17:41:08,376 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,376 INFO sqlalchemy.engine.base.Engine ('구로삼성어린이집', '류광수', '서울특별시 구로구 가마산로 174 ,구로삼성어린이집 (구로동) (구로제2동)', '02', '839', '0667', 7)
2021-08-18 17:41:08,378 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,378 INFO sqlalchemy.engine.base.Engine ('구립 파랑새어린이집', '조건우', '서울특별시 양천구 지양로5길 2 ,(신월동) (신월7동)', '02', '2690', '4011', 19)
2021-08-18 17:41:08,379 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,380 INFO sqlalchemy.engine.base.Engine ('도림어린이집', '이정식', '서울특별시 영등포구 도영로 37 ,(도림동) (도림동)', '02', '2181', '6090', 20)
2021-08-18 17:41:08,381 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,381 INFO sqlalchemy.engine.base.Engine ('귀염이어린이집', '강광수', '서울특별시 강서구 강서로 532 ,101동 102호(가양동, 동신아파트) (가양제1동)', '02', '2659', '7337', 4)
2021-08-18 17:41:08,382 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,383 INFO sqlalchemy.engine.base.Engine ('구립 성모어린이집', '안서연', '서울특별시 성동구 청계천로 506 ,(성동종합사회복지관3층) (마장동)', '02', '2290', '3182', 16)
2021-08-18 17:41:08,384 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,385 INFO sqlalchemy.engine.base.Engine ('애림어린이집', '오도현', '서울특별시 노원구 마들로 111 ,25동 101호(월계동, 삼호) (월계3동)', '02', '6223', '5808', 9)
2021-08-18 17:41:08,387 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,387 INFO sqlalchemy.engine.base.Engine ('문정동화나라어린이집', '권수빈', '서울특별시 송파구 동남로8길 18 ,(문정동) (문정1동)', '02', '448', '0507', 18)
2021-08-18 17:41:08,388 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,389 INFO sqlalchemy.engine.base.Engine ('보성어린이집', '정은경', '서울특별시 강서구 방화대로48길 40 ,(방화동) (방화제3동)', '02', '2662', '6665', 4)
2021-08-18 17:41:08,390 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,390 INFO sqlalchemy.engine.base.Engine ('예손어린이집', '김상훈', '서울특별시 강서구 양천로57길 26 ,예손어린이집 (가양동) (가양제2동)', '02', '2659', '3430', 4)
2021-08-18 17:41:08,391 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,392 INFO sqlalchemy.engine.base.Engine ('별밭어린이집', '송성호', '서울특별시 동대문구 답십리로66길 3 ,(장안동) (장안제1동)', '02', '2215', '0248', 11)
2021-08-18 17:41:08,393 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,393 INFO sqlalchemy.engine.base.Engine ('선릉삼성어린이집', '최건우', '서울특별시 강남구 선릉로100길 48 ,(삼성동) (삼성제2동)', '02', '539', '4068', 1)
2021-08-18 17:41:08,394 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,395 INFO sqlalchemy.engine.base.Engine ('꿈마루어린이집', '오지혜', '서울특별시 중랑구 겸재로50나길 71 ,(면목동) (면목본동)', '02', '433', '8734', 25)
2021-08-18 17:41:08,396 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,397 INFO sqlalchemy.engine.base.Engine ('파랑새어린이집', '권혜진', '서울특별시 도봉구 해등로 50 ,316동 106호(창동, 주공3단지아파트) (창제1동)', '02', '996', '1582', 10)
2021-08-18 17:41:08,398 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,399 INFO sqlalchemy.engine.base.Engine ('다향어린이집', '윤준호', '서울특별시 구로구 오리로 1167 ,(오류동) (오류제2동)', '02', '2684', '0535', 7)
2021-08-18 17:41:08,401 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,402 INFO sqlalchemy.engine.base.Engine ('자양4동어린이집', '황정순', '서울특별시 광진구 아차산로32길 17 ,(자양동) (자양제4동)', '02', '463', '4959', 6)
2021-08-18 17:41:08,403 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,403 INFO sqlalchemy.engine.base.Engine ('연남어린이집', '황경숙', '서울특별시 마포구 연남로7길 32-10 (연남동)', '02', '322', '6180', 13)
2021-08-18 17:41:08,405 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,405 INFO sqlalchemy.engine.base.Engine ('강성어린이스쿨어린이집', '최정자', '서울특별시 영등포구 대림로 128-2 ,(대림동) (대림제1동)', '02', '833', '5123', 20)
2021-08-18 17:41:08,406 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,407 INFO sqlalchemy.engine.base.Engine ('은가어린이집', '윤지민', '서울특별시 서대문구 증가로28길 18-48 (북가좌제2동)', '02', '307', '0283', 14)
2021-08-18 17:41:08,408 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,409 INFO sqlalchemy.engine.base.Engine ('예쁜어린이집', '정유진', '서울특별시 성북구 정릉로26길 18 ,(정릉동) (정릉제2동)', '02', '911', '5172', 17)
2021-08-18 17:41:08,410 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,410 INFO sqlalchemy.engine.base.Engine ('광진어린이집', '김은영', '서울특별시 광진구 아차산로40길 9 ,(자양동) (자양제1동)', '02', '2201', '0126', 6)
2021-08-18 17:41:08,411 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,412 INFO sqlalchemy.engine.base.Engine ('공덕어린이집', '조영일', '서울특별시 마포구 효창목5길 18 ,(공덕동) (공덕동)', '02', '716', '2234', 13)
2021-08-18 17:41:08,413 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,413 INFO sqlalchemy.engine.base.Engine ('베이비엔젤어린이집', '서혜진', '서울특별시 노원구 덕릉로 459-18 ,102동 112호(상계동, 미도) (상계6.7동)', '02', '931', '9370', 9)
2021-08-18 17:41:08,415 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,416 INFO sqlalchemy.engine.base.Engine ('아기차지어린이집', '박예준', '서울특별시 노원구 노원로 564 ,1006동 104호(상계동, 상계주공10차) (상계8동)', '02', '932', '0929', 9)
2021-08-18 17:41:08,417 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,418 INFO sqlalchemy.engine.base.Engine ('푸른어린이집', '오정운', '서울특별시 강남구 자곡로7길 8-1 ,(자곡동) (세곡동)', '02', '451', '3655', 1)
2021-08-18 17:41:08,419 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,420 INFO sqlalchemy.engine.base.Engine ('반포복지관어린이집', '전준영', '서울특별시 서초구 사평대로55길 90 ,(반포동) (반포1동)', '02', '512', '1825', 15)
2021-08-18 17:41:08,421 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,422 INFO sqlalchemy.engine.base.Engine ('예심어린이집', '권정호', '서울특별시 강서구 화곡로31길 18-3 (우장산동)', '02', '2699', '0698', 4)
2021-08-18 17:41:08,423 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,424 INFO sqlalchemy.engine.base.Engine ('나래어린이집', '서지훈', '서울특별시 강동구 올림픽로 932 ,나래어린이집 (암사동) (암사제3동)', '02', '441', '5742', 2)
2021-08-18 17:41:08,425 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,426 INFO sqlalchemy.engine.base.Engine ('보람어린이집', '전은경', '서울특별시 강남구 남부순환로397길 19 ,(대치동) (대치제1동)', '02', '563', '9511', 1)
2021-08-18 17:41:08,427 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,428 INFO sqlalchemy.engine.base.Engine ('하계어린이집', '정성민', '서울특별시 노원구 공릉로58마길 1 ,(하계동) (하계1동)', '02', '948', '0311', 9)
2021-08-18 17:41:08,429 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,429 INFO sqlalchemy.engine.base.Engine ('신나는어린이집', '임영철', '서울특별시 광진구 광나루로40길 78 ,(구의동) (구의제1동)', '02', '453', '2814', 6)
2021-08-18 17:41:08,430 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,431 INFO sqlalchemy.engine.base.Engine ('신수어린이집', '정현준', '서울특별시 마포구 토정로17길 16-5 (신수동)', '02', '703', '1686', 13)

2021-08-18 17:41:08,432 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,433 INFO sqlalchemy.engine.base.Engine ('파란나라어린이집', '신도현', '서울특별시 송파구 풍성로14길 9 ,(풍납동) (풍납2동)', '02', '487', '0100', 18)
2021-08-18 17:41:08,435 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,441 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '안지은', '서울특별시 구로구 디지털로32길 29 ,(구로동) (구로제3동)', '02', '853', '1180', 7)
2021-08-18 17:41:08,443 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,444 INFO sqlalchemy.engine.base.Engine ('엄지어린이집', '윤지훈', '서울특별시 양천구 신정로 293 ,102동 107호(신정동, 신트리아파트) (신정3동)', '02', '2607', '4177', 19)
2021-08-18 17:41:08,445 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,445 INFO sqlalchemy.engine.base.Engine ('미루나무어린이집', '류예준', '서울특별시 영등포구 도신로29가길 12 ,(도림동) (도림동)', '02', '849', '9570', 20)
2021-08-18 17:41:08,446 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,448 INFO sqlalchemy.engine.base.Engine ('창문어린이집', '장영길', '서울특별시 도봉구 도봉로118길 15 ,(창동) (창제1동)', '02', '999', '1236', 10)
2021-08-18 17:41:08,450 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,451 INFO sqlalchemy.engine.base.Engine ('리틀지니어스어린이집', '오도현', '서울특별시 광진구 자양로26길 50 ,(구의동) (구의제1동)', '02', '444', '0717', 6)
2021-08-18 17:41:08,452 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,453 INFO sqlalchemy.engine.base.Engine ('초롱몬테소리어린이집', '류은정', '서울특별시 노원구 노원로 532 ,909동 103호(상계동, 상계주공9차) (상계10동)', '02', '939', '5500', 9)
2021-08-18 17:41:08,454 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,455 INFO sqlalchemy.engine.base.Engine ('예진어린이집', '안유진', '서울특별시 송파구 올림픽로35길 104 ,장미1차아파트 7동 106호 (잠실6동)', '02', '413', '2418', 18)
2021-08-18 17:41:08,456 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,457 INFO sqlalchemy.engine.base.Engine ('쌍문3동어린이집', '한준혁', '서울특별시 도봉구 노해로 224 ,(쌍문동) (쌍문제3동)', '02', '990', '3261', 10)
2021-08-18 17:41:08,459 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,460 INFO sqlalchemy.engine.base.Engine ('샘터어린이집', '강건우', '서울특별시 노원구 동일로216길 47 ,505동 101호(상계동, 상계주공5차) (상계6.7동)', '02', '931', '5627', 9)
2021-08-18 17:41:08,462 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,463 INFO sqlalchemy.engine.base.Engine ('또래어린이집', '장정호', '서울특별시 강남구 언주로 107 ,현대아파트 단지내(개포동) (개포4동)', '02', '571', '3667', 1)
2021-08-18 17:41:08,464 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,465 INFO sqlalchemy.engine.base.Engine ('구립금빛어린이집', '오민재', '서울특별시 관악구 남부순환로246가길 17 ,(봉천동) [인헌동] (인헌동)', '02', '875', '8172', 5)
2021-08-18 17:41:08,467 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,467 INFO sqlalchemy.engine.base.Engine ('꿈빛어린이집', '권영자', '서울특별시 노원구 초안산로1길 51 ,(월계2동, 꿈빛어린이집) (월계2동)', '02', '996', '9375', 9)
2021-08-18 17:41:08,468 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,469 INFO sqlalchemy.engine.base.Engine ('경동어린이집', '권건우', '서울특별시 중구 장충단로 204 ,경동교회내 경동어린이집 (장충동1가) (장충동)', '02', '2272', '7158', 24)
2021-08-18 17:41:08,471 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,472 INFO sqlalchemy.engine.base.Engine ('보람어린이집', '류유진', '서울특별시 노원구 노원로16길 15 ,(하계1동, 보람어린이집) (하계1동)', '02', '948', '8715', 9)
2021-08-18 17:41:08,472 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,474 INFO sqlalchemy.engine.base.Engine ('아이꿈어린이집', '임은영', '서울특별시 강동구 구천면로42길 16 ,한신아파트 2동 105호 (천호제1동)', '02', '484', '9798', 2)
2021-08-18 17:41:08,475 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,476 INFO sqlalchemy.engine.base.Engine ('청마을어린이집', '한경숙', '서울특별시 강남구 양재대로55길 10 ,대청복지관 내 1층 청마을어린이집 (일원제1동)', '02', '459', '6335', 1)
2021-08-18 17:41:08,477 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,478 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '박성호', '서울특별시 광진구 자양로 134 ,(구의동) (구의제1동)', '02', '444', '5449', 6)
2021-08-18 17:41:08,479 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,480 INFO sqlalchemy.engine.base.Engine ('한빛어린이집', '장지원', '서울특별시 종로구 종로65길 10 ,(숭인동) (숭인제2동)', '02', '763', '6825', 23)
2021-08-18 17:41:08,482 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,483 INFO sqlalchemy.engine.base.Engine ('민들레어린이집', '이준서', '서울특별시 강남구 광평로56길 11 ,(수서동) (수서동)', '02', '3412', '7979', 1)
2021-08-18 17:41:08,484 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,485 INFO sqlalchemy.engine.base.Engine ('구민회관어린이집', '강민서', '서울특별시 영등포구 국회대로 596 (당산제1동)', '02', '2678', '5685', 20)
2021-08-18 17:41:08,486 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,486 INFO sqlalchemy.engine.base.Engine ('반포1동어린이집', '조준혁', '서울특별시 서초구 신반포로 318 ,(반포동) (반포1동)', '02', '518', '1630', 15)
2021-08-18 17:41:08,488 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,488 INFO sqlalchemy.engine.base.Engine ('송파어린이집', '황병철', '서울특별시 송파구 오금로51길 34 ,(거여동) (거여1동)', '02', '401', '1848', 18)
2021-08-18 17:41:08,490 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,490 INFO sqlalchemy.engine.base.Engine ('푸른몬테소리어린이집', '이준호', '서울특별시 금천구 시흥대로141길 47 ,(독산동) (독산제1동)', '02', '838', '3435', 8)
2021-08-18 17:41:08,493 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,494 INFO sqlalchemy.engine.base.Engine ('꿈이크는어린이집', '서현준', '서울특별시 송파구 가락로33길 21 ,(방이동) (방이2동)', '02', '421', '5311', 18)

2021-08-18 17:41:08,495 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,495 INFO sqlalchemy.engine.base.Engine ('명화어린이집', '이지훈', '서울특별시 강남구 광평로51길 49 ,(수서동) (수서동)', '02', '459', '0686', 1)
2021-08-18 17:41:08,497 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,497 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '정미경', '서울특별시 구로구 경인로19길 32 (오류제1동)', '02', '2683', '6700', 7)
2021-08-18 17:41:08,498 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,500 INFO sqlalchemy.engine.base.Engine ('내곡어린이집', '이순자', '서울특별시 서초구 홍씨마을길 25 ,(내곡동) (내곡동)', '02', '572', '9309', 15)
2021-08-18 17:41:08,501 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,502 INFO sqlalchemy.engine.base.Engine ('동신베베어린이집', '안건우', '서울특별시 노원구 광운로2나길 30 ,5동 101호(월계동, 동신아파트) (월계1동)', '02', '913', '5490', 9)
2021-08-18 17:41:08,503 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,503 INFO sqlalchemy.engine.base.Engine ('하얀돌어린이집', '류영길', '서울특별시 강서구 등촌로39가길 10 ,(등촌동) (등촌제2동)', '02', '2643', '5630', 4)
2021-08-18 17:41:08,504 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,507 INFO sqlalchemy.engine.base.Engine ('홍제어린이집', '황지은', '서울특별시 서대문구 통일로31길 3-4 ,(홍제동) (홍제제1동)', '02', '734', '6378', 14)
2021-08-18 17:41:08,508 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,509 INFO sqlalchemy.engine.base.Engine ('예뜰어린이집', '신유진', '서울특별시 양천구 신정중앙로16길 10 ,(신정동) (신정4동)', '02', '2607', '2560', 19)
2021-08-18 17:41:08,510 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,511 INFO sqlalchemy.engine.base.Engine ('구립원광어린이집', '최병철', '서울특별시 관악구 신림로64길 57 ,(신림동) [신림동] (신림동)', '02', '872', '9629', 5)
2021-08-18 17:41:08,513 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,514 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '오민지', '서울특별시 은평구 은평로 33-9 (신사제1동)', '02', '306', '7123', 22)
2021-08-18 17:41:08,515 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,516 INFO sqlalchemy.engine.base.Engine ('구립 성덕어린이집', '강성수', '서울특별시 성동구 성수이로3길 14-7 (성수2가제1동)', '02', '464', '9746', 16)
2021-08-18 17:41:08,516 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,517 INFO sqlalchemy.engine.base.Engine ('햇님어린이집', '전영길', '서울특별시 동대문구 사가정로 148 ,108동 104호(전농동, SK아파트) (전농제2동)', '02', '2213', '4322', 11)
2021-08-18 17:41:08,519 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,519 INFO sqlalchemy.engine.base.Engine ('상도복지관어린이집', '윤민재', '서울특별시 동작구 상도로39가길 7 ,상도복지관어린이집 (상도동) (상도제1동)', '02', '825', '4875', 12)
2021-08-18 17:41:08,520 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,521 INFO sqlalchemy.engine.base.Engine ('예닮어린이집', '한준영', '서울특별시 강북구 한천로120길 3 ,(번동) (번1동)', '02', '997', '5004', 3)
2021-08-18 17:41:08,522 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,523 INFO sqlalchemy.engine.base.Engine ('에덴어린이집', '송영철', '서울특별시 영등포구 여의대로6길 17 ,C동 106호(여의도동, 공작아파트) (여의동)', '02', '769', '1339', 20)
2021-08-18 17:41:08,524 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,525 INFO sqlalchemy.engine.base.Engine ('국공립 가양 7 어린이집', '조미영', '서울특별시 강서구 허준로 209 ,(가양동) (가양제3동)', '02', '2668', '8606', 4)
2021-08-18 17:41:08,526 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,526 INFO sqlalchemy.engine.base.Engine ('산성어린이집', '권준호', '서울특별시 송파구 마천로41길 12 (마천2동)', '02', '449', '5552', 18)
2021-08-18 17:41:08,527 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,528 INFO sqlalchemy.engine.base.Engine ('해방어린이집', '서경자', '서울특별시 용산구 소월로20길 43 ,해방어린이집 (용산동2가) (용산2가동)', '02', '795', '8450', 21)
2021-08-18 17:41:08,529 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,530 INFO sqlalchemy.engine.base.Engine ('동방어린이집', '장지훈', '서울특별시 서대문구 모래내로 177 ,(남가좌동) (남가좌제1동)', '02', '374', '7861', 14)
2021-08-18 17:41:08,530 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,531 INFO sqlalchemy.engine.base.Engine ('아현어린이집', '송준혁', '서울특별시 마포구 신촌로 210 ,(아현동) (아현동)', '02', '312', '5539', 13)
2021-08-18 17:41:08,534 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,535 INFO sqlalchemy.engine.base.Engine ('중구청직장어린이집', '임지훈', '서울특별시 중구 마른내로12길 17-19 (광희동)', '02', '3396', '4049', 24)
2021-08-18 17:41:08,536 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,537 INFO sqlalchemy.engine.base.Engine ('구립곡교어린이집', '조민재', '서울특별시 강동구 천중로12길 23-40 ,구립곡교어린이집 (천호동 362-60) (천호제2동)', '02', '472', '4200', 2)
2021-08-18 17:41:08,538 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,539 INFO sqlalchemy.engine.base.Engine ('구립보람나무어린이집', '박혜진', '서울특별시 강동구 암사길 57 ,(암사동474-8) (암사제1동)', '02', '442', '0057', 2)
2021-08-18 17:41:08,541 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,542 INFO sqlalchemy.engine.base.Engine ('청량리어린이집', '박예준', '서울특별시 동대문구 홍릉로17길 38 ,(제기동) (제기동)', '02', '6080', '6404', 11)
2021-08-18 17:41:08,543 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,545 INFO sqlalchemy.engine.base.Engine ('구립 구산어린이집', '강지은', '서울특별시 은평구 서오릉로21길 11-8 (구산동)', '02', '352', '9606', 22)
2021-08-18 17:41:08,546 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,547 INFO sqlalchemy.engine.base.Engine ('송은어린이집', '최정남', '서울특별시 송파구 송파대로16길 11 ,(문정동) (문정1동)', '02', '448', '3714', 18)
2021-08-18 17:41:08,547 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,548 INFO sqlalchemy.engine.base.Engine ('유아교실어린이집', '한정호', '서울특별시 마포구 마포대로 195 ,마포래미안푸르지오아파트 205동 104호 (아현동)', '02', '392', '6506', 13)
2021-08-18 17:41:08,550 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,550 INFO sqlalchemy.engine.base.Engine ('시온어린이집', '권민재', '서울특별시 송파구 오금로49길 33 ,(오금동) (오금동)', '02', '449', '7898', 18)
2021-08-18 17:41:08,551 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,552 INFO sqlalchemy.engine.base.Engine ('구립노량진어린이집', '정상철', '서울특별시 동작구 노량진로14길 44 ,노량진동 84-33 (노량진제1동)', '02', '822', '7373', 12)
2021-08-18 17:41:08,552 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,553 INFO sqlalchemy.engine.base.Engine ('마들어린이집', '윤예준', '서울특별시 노원구 동일로210길 22 ,(동일로 210길 22) (중계동) (중계2.3동)', '02', '978', '8389', 9)
2021-08-18 17:41:08,554 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,555 INFO sqlalchemy.engine.base.Engine ('늘사랑어린이집', '박상훈', '서울특별시 동대문구 제기로38길 50 ,동성빌딩 2층 (청량리동)', '02', '965', '6096', 11)
2021-08-18 17:41:08,556 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,556 INFO sqlalchemy.engine.base.Engine ('구립예지어린이집', '서상철', '서울특별시 관악구 난곡로30나길 19 ,(신림동) [난곡동] (난곡동)', '02', '837', '4745', 5)
2021-08-18 17:41:08,557 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,558 INFO sqlalchemy.engine.base.Engine ('구립 꿈나래어린이집', '한건우', '서울특별시 양천구 목동동로12길 7 ,(목동) (목1동)', '02', '2654', '4600', 19)
2021-08-18 17:41:08,558 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,559 INFO sqlalchemy.engine.base.Engine ('삼선뜰어린이집', '박예은', '서울특별시 성북구 보문로29길 86 ,(삼선동3가) (삼선동)', '02', '747', '6776', 17)
2021-08-18 17:41:08,560 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,561 INFO sqlalchemy.engine.base.Engine ('가원어린이집', '안영숙', '서울특별시 송파구 오금로57길 22 ,가원어린이집 (거여1동)', '02', '408', '1074', 18)
2021-08-18 17:41:08,562 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,563 INFO sqlalchemy.engine.base.Engine ('캥거루어린이집', '임지훈', '서울특별시 강서구 가로공원로76길 9 ,(화곡동) (화곡제1동)', '02', '2692', '1007', 4)
2021-08-18 17:41:08,565 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,566 INFO sqlalchemy.engine.base.Engine ('피노키오어린이집', '송정식', '서울특별시 성동구 용답중앙15길 10 ,(용답동) (용답동)', '02', '2215', '0526', 16)
2021-08-18 17:41:08,567 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,568 INFO sqlalchemy.engine.base.Engine ('충무어린이집', '오건우', '서울특별시 중구 동호로27길 21 ,(묵정동) (장충동)', '02', '2264', '3679', 24)
2021-08-18 17:41:08,570 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,571 INFO sqlalchemy.engine.base.Engine ('단우물 어린이집', '강상훈', '서울특별시 중구 다산로48길 33 ,단우물어린이집(황학동) (황학동)', '02', '2234', '9125', 24)
2021-08-18 17:41:08,572 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,573 INFO sqlalchemy.engine.base.Engine ('혜성어린이집', '신성진', '서울특별시 중랑구 동일로136나길 29-6 ,(중화동) (중화제1동)', '02', '439', '5431', 25)
2021-08-18 17:41:08,575 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,576 INFO sqlalchemy.engine.base.Engine ('강남어린이집', '오성진', '서울특별시 강남구 개포로109길 5 ,강남종합사회복지관 1층 강남어린이집(개포동 12번지) (일원제2동)', '02', '451', '0350', 1)
2021-08-18 17:41:08,577 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,577 INFO sqlalchemy.engine.base.Engine ('방배어린이집', '송준혁', '서울특별시 서초구 방배로19길 36-8 (방배1동)', '02', '523', '3735', 15)
2021-08-18 17:41:08,578 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,579 INFO sqlalchemy.engine.base.Engine ('상수어린이집', '조혜진', '서울특별시 마포구 독막로12길 38 ,(당인동) (서강동)', '02', '323', '5045', 13)
2021-08-18 17:41:08,580 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,581 INFO sqlalchemy.engine.base.Engine ('구립 파란들어린이집', '박서현', '서울특별시 양천구 가로공원로 85 ,(신월동) (신월3동)', '02', '2696', '9594', 19)
2021-08-18 17:41:08,582 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,583 INFO sqlalchemy.engine.base.Engine ('한내어린이집', '서은정', '서울특별시 노원구 공릉로55길 88 ,(하계동) (하계2동)', '02', '948', '0125', 9)
2021-08-18 17:41:08,583 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,584 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '황정수', '서울특별시 중랑구 동일로143길 12-12 ,(묵동) (묵제2동)', '02', '973', '2396', 25)
2021-08-18 17:41:08,585 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,585 INFO sqlalchemy.engine.base.Engine ('평화어린이집', '장지훈', '서울특별시 노원구 노원로 331 ,(중계동, 평화어린이집) (중계2.3동)', '02', '948', '0993', 9)
2021-08-18 17:41:08,587 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,587 INFO sqlalchemy.engine.base.Engine ('희망어린이집', '오동현', '서울특별시 구로구 새말로 93 ,태영타운내 갈릴리교회2층 (구로동) (구로제5동)', '02', '853', '8853', 7)
2021-08-18 17:41:08,589 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,590 INFO sqlalchemy.engine.base.Engine ('동선어린이집', '이지영', '서울특별시 성북구 아리랑로 27-24 (동선동)', '02', '923', '1745', 17)
2021-08-18 17:41:08,591 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,592 INFO sqlalchemy.engine.base.Engine ('서초어린이집', '안준호', '서울특별시 서초구 남부순환로 2271-1 (방배3동)', '02', '522', '9411', 15)
2021-08-18 17:41:08,593 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,594 INFO sqlalchemy.engine.base.Engine ('구립 송화어린이집', '권동현', '서울특별시 성동구 송정18가길 29 ,(송정동) (송정동)', '02', '499', '5292', 16)
2021-08-18 17:41:08,595 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,596 INFO sqlalchemy.engine.base.Engine ('성아어린이집', '김경회', '서울특별시 관악구 난곡로22길 23 ,(신림동) [난곡동] (난곡동)', '02', '857', '5335', 5)

2021-08-18 17:41:08,597 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,598 INFO sqlalchemy.engine.base.Engine ('엄마사랑어린이집', '황지은', '서울특별시 양천구 목동중앙본로18길 11 ,(목동) (목2동)', '02', '2653', '6262', 19)
2021-08-18 17:41:08,599 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,600 INFO sqlalchemy.engine.base.Engine ('구립 무궁화어린이집', '전지은', '서울특별시 양천구 목동중앙서로11길 48 ,(목동) (목4동)', '02', '2653', '6313', 19)
2021-08-18 17:41:08,601 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,602 INFO sqlalchemy.engine.base.Engine ('월계1동어린이집', '권준영', '서울특별시 노원구 석계로 69 ,(월계동) (월계1동)', '02', '913', '8045', 9)
2021-08-18 17:41:08,603 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,605 INFO sqlalchemy.engine.base.Engine ('성호 어린이집', '권병철', '서울특별시 성동구 금호산12길 10 ,(금호동3가) (금호2.3가동)', '02', '2232', '4215', 16)
2021-08-18 17:41:08,607 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,608 INFO sqlalchemy.engine.base.Engine ('성산누리어린이집', '오영진', '서울특별시 마포구 월드컵로 215 ,성산종합사회복지관 1층 (성산제2동)', '02', '307', '8453', 13)
2021-08-18 17:41:08,609 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,610 INFO sqlalchemy.engine.base.Engine ('사랑어린이집', '최정호', '서울특별시 송파구 토성로19길 35-1 (풍납2동)', '02', '488', '8819', 18)
2021-08-18 17:41:08,611 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,612 INFO sqlalchemy.engine.base.Engine ('회기어린이집', '서미영', '서울특별시 동대문구 회기로 165 ,(회기동 58-1) (회기동)', '02', '969', '6691', 11)
2021-08-18 17:41:08,613 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,614 INFO sqlalchemy.engine.base.Engine ('별빛어린이집', '정준혁', '서울특별시 송파구 가락로40길 9 ,2층 별빛어린이집 (방이1동)', '02', '420', '9920', 18)
2021-08-18 17:41:08,615 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,616 INFO sqlalchemy.engine.base.Engine ('안동어린이집', '오영진', '서울특별시 종로구 북촌로7길 3-10 (가회동)', '02', '743', '9307', 23)
2021-08-18 17:41:08,618 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,618 INFO sqlalchemy.engine.base.Engine ('다애어린이집', '서순자', '서울특별시 동작구 사당로20가길 36-4 (사당제4동)', '02', '583', '0384', 12)
2021-08-18 17:41:08,619 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,620 INFO sqlalchemy.engine.base.Engine ('거성어린이집', '권민서', '서울특별시 송파구 오금로 544-6 ,거성어린이집 (거여2동)', '02', '431', '5773', 18)
2021-08-18 17:41:08,621 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,622 INFO sqlalchemy.engine.base.Engine ('구립송중동어린이집', '한성민', '서울특별시 강북구 오패산로30길 18-5 (송중동)', '02', '985', '5880', 3)
2021-08-18 17:41:08,623 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,624 INFO sqlalchemy.engine.base.Engine ('새싹어린이집', '최정자', '서울특별시 강서구 양천로24가길 73 ,(방화동) (방화제1동)', '02', '2665', '4910', 4)
2021-08-18 17:41:08,625 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,625 INFO sqlalchemy.engine.base.Engine ('백상어린이집', '윤경회', '서울특별시 관악구 신림로28길 18 ,서림동] (신림동) (서림동)', '02', '883', '3803', 5)
2021-08-18 17:41:08,626 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,627 INFO sqlalchemy.engine.base.Engine ('중림어린이집', '장광수', '서울특별시 중구 만리재로35길 12 ,(만리동1가) (중림동)', '02', '364', '7534', 24)
2021-08-18 17:41:08,628 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,629 INFO sqlalchemy.engine.base.Engine ('구립 은평어린이집', '정성호', '서울특별시 은평구 증산로9길 44-12 (증산동)', '02', '376', '0540', 22)
2021-08-18 17:41:08,631 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,632 INFO sqlalchemy.engine.base.Engine ('절제어린이집', '최민서', '서울특별시 용산구 후암로57길 57 ,(동자동) (남영동)', '02', '771', '4937', 21)
2021-08-18 17:41:08,633 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,634 INFO sqlalchemy.engine.base.Engine ('남산어린이집', '송민재', '서울특별시 구로구 경인로47가길 35 ,(고척동) (고척제1동)', '02', '2612', '0289', 7)
2021-08-18 17:41:08,635 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,636 INFO sqlalchemy.engine.base.Engine ('덕성어린이집', '최민지', '서울특별시 구로구 고척로51길 46 ,(고척동) (고척제2동)', '02', '2612', '4788', 7)
2021-08-18 17:41:08,638 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,639 INFO sqlalchemy.engine.base.Engine ('구립 무지개어린이집', '전정순', '서울특별시 양천구 남부순환로83길 54 ,건강힐링문화관 1층 (신월6동)', '02', '2693', '1905', 19)
2021-08-18 17:41:08,640 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,641 INFO sqlalchemy.engine.base.Engine ('구립다원어린이집', '서지훈', '서울특별시 관악구 미성7길 20 ,다원어린이집 (미성동)', '02', '851', '7227', 5)
2021-08-18 17:41:08,642 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,643 INFO sqlalchemy.engine.base.Engine ('아람어린이집', '류상철', '서울특별시 강동구 올림픽로89길 27-20 ,(천호동 321-77) (천호제2동)', '02', '485', '2234', 2)
2021-08-18 17:41:08,644 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,645 INFO sqlalchemy.engine.base.Engine ('금륜어린이집', '황영일', '서울특별시 송파구 거마로24길 8-6 (마천2동)', '02', '401', '1774', 18)
2021-08-18 17:41:08,646 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,647 INFO sqlalchemy.engine.base.Engine ('상아어린이집', '전상훈', '서울특별시 도봉구 해등로16가길 32 ,(창동) (창제5동)', '02', '904', '0677', 10)
2021-08-18 17:41:08,649 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,649 INFO sqlalchemy.engine.base.Engine ('예쁜친구어린이집', '오정수', '서울특별시 도봉구 노해로63다길 62-11 ,(창동) (창제5동)', '02', '900', '9388', 10)
2021-08-18 17:41:08,651 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,651 INFO sqlalchemy.engine.base.Engine ('엄마랑아가랑어린이집', '송병철', '서울특별시 영등포구 영등포로86가길 21 ,(신길동) (신길제1동)', '02', '843', '6692', 20)
2021-08-18 17:41:08,652 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,653 INFO sqlalchemy.engine.base.Engine ('수호천사어린이집', '윤미경', '서울특별시 금천구 독산로 62 ,(시흥동) (시흥제5동)', '02', '805', '4448', 8)
2021-08-18 17:41:08,654 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,655 INFO sqlalchemy.engine.base.Engine ('조은어린이집', '전미영', '서울특별시 종로구 지봉로12가길 35 ,(숭인동) (숭인제1동)', '02', '763', '7800', 23)
2021-08-18 17:41:08,656 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,657 INFO sqlalchemy.engine.base.Engine ('아름어린이집', '오준호', '서울특별시 양천구 목동서로 38 ,125동 106호(목동, 목동신시가지1단지아파트) (목5동)', '02', '2648', '6327', 19)
2021-08-18 17:41:08,658 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,658 INFO sqlalchemy.engine.base.Engine ('구립당곡어린이집', '한은영', '서울특별시 관악구 봉천로23길 6 ,(봉천동) [보라매동] (보라매동)', '02', '884', '2267', 5)
2021-08-18 17:41:08,660 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,660 INFO sqlalchemy.engine.base.Engine ('풍성어린이집', '안성민', '서울특별시 송파구 풍성로25길 21-3 (풍납1동)', '02', '471', '6177', 18)
2021-08-18 17:41:08,661 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,662 INFO sqlalchemy.engine.base.Engine ('동명어린이집', '송영철', '서울특별시 강남구 개포로20길 34 ,서울특별시 강남구 개포로 20길34 (개포제4동)', '02', '529', '2383', 1)
2021-08-18 17:41:08,663 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,664 INFO sqlalchemy.engine.base.Engine ('현대어린이집', '이민지', '서울특별시 강서구 양천로75길 57 ,104동 109호(염창동, 현대) (염창동)', '02', '3664', '9184', 4)
2021-08-18 17:41:08,665 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,666 INFO sqlalchemy.engine.base.Engine ('영화어린이집', '조지혜', '서울특별시 광진구 자양로4길 26 ,(자양동) (자양제2동)', '02', '462', '9400', 6)
2021-08-18 17:41:08,667 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,668 INFO sqlalchemy.engine.base.Engine ('중동 어린이집', '안준호', '서울특별시 마포구 월드컵북로38가길 8-1 (성산제2동)', '02', '375', '6755', 13)
2021-08-18 17:41:08,670 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,670 INFO sqlalchemy.engine.base.Engine ('또래또어린이집', '서종수', '서울특별시 중랑구 공릉로2나길 46 ,201동 102호(묵동, 신안2차아파트) (묵제1동)', '02', '972', '8645', 25)
2021-08-18 17:41:08,672 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,672 INFO sqlalchemy.engine.base.Engine ('은강어린이집', '한지원', '서울특별시 마포구 대흥로2길 41 ,은강어린이집 (용강동)', '02', '702', '4002', 13)
2021-08-18 17:41:08,674 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,685 INFO sqlalchemy.engine.base.Engine ('우리보람어린이집', '황지영', '서울특별시 노원구 노해로 508 ,621동 105호(상계동, 상계주공6단지아파트) (상계6.7동)', '02', '952', '9797', 9)
2021-08-18 17:41:08,686 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,687 INFO sqlalchemy.engine.base.Engine ('염창어린이집', '조은정', '서울특별시 강서구 공항대로65길 43 ,염창어린이집 (염창동) (염창동)', '02', '3665', '1960', 4)
2021-08-18 17:41:08,688 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,689 INFO sqlalchemy.engine.base.Engine ('만나어린이집', '황예은', '서울특별시 구로구 고척로27길 74 ,(개봉동) (개봉제1동)', '02', '2612', '0284', 7)
2021-08-18 17:41:08,690 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,691 INFO sqlalchemy.engine.base.Engine ('해태어린이집', '송유진', '서울특별시 영등포구 가마산로 316 ,(대림동) (대림제3동)', '02', '832', '4071', 20)
2021-08-18 17:41:08,692 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,693 INFO sqlalchemy.engine.base.Engine ('구립 다솜어린이집', '전유진', '서울특별시 양천구 목동중앙로13길 22 ,(목동) (목2동)', '02', '2646', '8909', 19)
2021-08-18 17:41:08,694 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,694 INFO sqlalchemy.engine.base.Engine ('은행나무어린이집', '박예은', '서울특별시 종로구 낙산5길 33 ,(창신동) (창신제3동)', '02', '744', '5420', 23)
2021-08-18 17:41:08,696 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,696 INFO sqlalchemy.engine.base.Engine ('구립 신사어린이집', '이미영', '서울특별시 은평구 은평터널로13길 9-9 ,신사어린이집 (신사동) (신사제2동)', '02', '302', '1902', 22)
2021-08-18 17:41:08,698 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,699 INFO sqlalchemy.engine.base.Engine ('구립나래어린이집', '강영일', '서울특별시 동작구 상도로15라길 24 ,나래어린이집 (상도제2동)', '02', '823', '3412', 12)
2021-08-18 17:41:08,701 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,702 INFO sqlalchemy.engine.base.Engine ('강동복지관어린이집', '오영진', '서울특별시 강동구 양재대로122가길 31 ,지하~3층 (길동)', '02', '2041', '7890', 2)
2021-08-18 17:41:08,703 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,704 INFO sqlalchemy.engine.base.Engine ('예지어린이집', '권성민', '서울특별시 강남구 언주로7길 23 ,예지어린이집 (개포동) (개포4동)', '02', '573', '1840', 1)
2021-08-18 17:41:08,705 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,706 INFO sqlalchemy.engine.base.Engine ('YWCA또래또어린이집', '정수빈', '서울특별시 동작구 국사봉1길 100 ,(상도동) (상도제3동)', '02', '821', '0210', 12)
2021-08-18 17:41:08,706 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,707 INFO sqlalchemy.engine.base.Engine ('이문어린이집', '오종수', '서울특별시 동대문구 신이문로 9 ,(이문동) (이문제2동)', '02', '969', '2052', 11)
2021-08-18 17:41:08,709 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,710 INFO sqlalchemy.engine.base.Engine ('아현어린이집', '최수빈', '서울특별시 서대문구 신촌로 293 ,아현감리교회 부설 아현어린이집 (북아현동)', '02', '393', '7419', 14)
2021-08-18 17:41:08,711 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,714 INFO sqlalchemy.engine.base.Engine ('웅지어린이집', '전지은', '서울특별시 성북구 길음로9길 113 ,(길음동) (길음제1동)', '02', '917', '9400', 17)
2021-08-18 17:41:08,715 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,716 INFO sqlalchemy.engine.base.Engine ('구세군강북 어린이집', '강민수', '서울특별시 강북구 인수봉로20가길 24 ,구세군 강북 복지관내 구세군 강북 어린이집 (미아동) (삼양동)', '02', '987', '4103', 3)
2021-08-18 17:41:08,718 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,719 INFO sqlalchemy.engine.base.Engine ('아크로힐스논현어린이집', '장준혁', '서울특별시 강남구 언주로 604 ,아크로힐스논현 관리동 (논현제2동)', '02', '547', '1677', 1)
2021-08-18 17:41:08,720 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,720 INFO sqlalchemy.engine.base.Engine ('에벤에셀어린이집', '윤은경', '서울특별시 구로구 오리로22나길 16-31 ,102동 102호(수궁동, 다청림아파트) (수궁동)', '02', '2625', '0502', 7)
2021-08-18 17:41:08,721 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,722 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '강병철', '서울특별시 송파구 송파대로 567 ,526동 110호(잠실동, 잠실주공5단지아파트) (잠실3동)', '02', '423', '6385', 18)
2021-08-18 17:41:08,725 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,728 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '최준영', '서울특별시 송파구 마천로17길 8-1 ,1층(오금동) (오금동)', '02', '403', '1492', 18)
2021-08-18 17:41:08,730 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,731 INFO sqlalchemy.engine.base.Engine ('구립 가양 어린이집', '류진호', '서울특별시 강서구 양천로49길 26 ,(가양동) (가양제1동)', '02', '3662', '9691', 4)
2021-08-18 17:41:08,732 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,733 INFO sqlalchemy.engine.base.Engine ('인솔어린이집', '강성진', '서울특별시 강동구 풍성로52길 14 ,103호(성내동, 태천해오름A) (성내제3동)', '02', '483', '6154', 2)
2021-08-18 17:41:08,734 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,735 INFO sqlalchemy.engine.base.Engine ('대림2동어린이집', '황성수', '서울특별시 영등포구 대림로23길 27 ,구립대림2동어린이집 (대림제2동)', '02', '832', '9909', 20)
2021-08-18 17:41:08,737 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,738 INFO sqlalchemy.engine.base.Engine ('은나래어린이집', '조정호', '서울특별시 노원구 동일로250길 17 ,관리사무소 내 1층 은나래어린이집 (상계1동)', '02', '935', '9166', 9)
2021-08-18 17:41:08,739 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,740 INFO sqlalchemy.engine.base.Engine ('초롱어린이집', '강정호', '서울특별시 중랑구 중랑역로3길 28 ,(중화동) (중화제2동)', '02', '436', '9439', 25)
2021-08-18 17:41:08,741 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,741 INFO sqlalchemy.engine.base.Engine ('현대몬테소리어린이집', '장성호', '서울특별시 광진구 광나루로56길 32 ,207동 106호(구의동, 구의현대2단지아파트) (구의제3동)', '02', '452', '8348', 6)
2021-08-18 17:41:08,742 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,742 INFO sqlalchemy.engine.base.Engine ('보경어린이집', '서준호', '서울특별시 중랑구 망우로77길 12 ,(망우동) (망우본동)', '02', '438', '3365', 25)
2021-08-18 17:41:08,743 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,744 INFO sqlalchemy.engine.base.Engine ('즐거운숲어린이집', '박정수', '서울특별시 강북구 인수봉로67길 12-5 ,(수유동 524-44) (인수동)', '02', '907', '3040', 3)
2021-08-18 17:41:08,745 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,745 INFO sqlalchemy.engine.base.Engine ('본동어린이집', '전광수', '서울특별시 금천구 독산로 12 ,(시흥동) (시흥제5동)', '02', '802', '8646', 8)
2021-08-18 17:41:08,746 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,747 INFO sqlalchemy.engine.base.Engine ('은혜어린이집', '장준영', '서울특별시 노원구 동일로227길 26 ,1608동 104호(상계동, 주공아파트) (상계8동)', '02', '951', '9430', 9)
2021-08-18 17:41:08,748 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,749 INFO sqlalchemy.engine.base.Engine ('아이꿈터어린이집', '한지영', '서울특별시 양천구 목동서로2길 22 ,112동 110호 목동한신청구아파트 (목5동)', '02', '2647', '4112', 19)
2021-08-18 17:41:08,750 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,751 INFO sqlalchemy.engine.base.Engine ('충현어린이집', '김진호', '서울특별시 강남구 테헤란로27길 40 ,1층(역삼동) (역삼제1동)', '02', '554', '7055', 1)
2021-08-18 17:41:08,752 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,753 INFO sqlalchemy.engine.base.Engine ('이대복지어린이집', '정영식', '서울특별시 서대문구 북아현로19길 58-21 (충현동)', '02', '3277', '3287', 14)
2021-08-18 17:41:08,755 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,757 INFO sqlalchemy.engine.base.Engine ('한내들어린이집', '서영식', '서울특별시 중랑구 동일로139라길 24 ,(중화동) (중화제2동)', '02', '434', '2666', 25)
2021-08-18 17:41:08,758 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,759 INFO sqlalchemy.engine.base.Engine ('꿈나무어린이집', '장건우', '서울특별시 영등포구 대방천로 199 ,(신길동) (신길제6동)', '02', '848', '1001', 20)
2021-08-18 17:41:08,761 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,761 INFO sqlalchemy.engine.base.Engine ('명신어린이집', '윤경회', '서울특별시 영등포구 신길로41라길 13-9 ,명신어린이집 (신길제3동)', '02', '831', '5329', 20)
2021-08-18 17:41:08,765 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,766 INFO sqlalchemy.engine.base.Engine ('신길5동어린이집', '전유진', '서울특별시 영등포구 신길로13길 20 ,(신길동) (신길제5동)', '02', '842', '7398', 20)
2021-08-18 17:41:08,767 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,768 INFO sqlalchemy.engine.base.Engine ('구립샛별어린이집', '황민수', '서울특별시 강북구 삼양로19길 102 ,201호 샛별어린이집 (삼각산동)', '02', '986', '6925', 3)
2021-08-18 17:41:08,769 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,770 INFO sqlalchemy.engine.base.Engine ('삼성어린이집', '정진호', '서울특별시 강남구 영동대로122길 7-6 (삼성제1동)', '02', '514', '6752', 1)
2021-08-18 17:41:08,773 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,774 INFO sqlalchemy.engine.base.Engine ('구립난향어린이집', '임지훈', '서울특별시 관악구 난향5길 6 (난향동)', '02', '866', '4070', 5)
2021-08-18 17:41:08,775 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,776 INFO sqlalchemy.engine.base.Engine ('석관어린이집', '전성민', '서울특별시 성북구 화랑로40길 27 ,(석관동) (석관동)', '02', '965', '1633', 17)
2021-08-18 17:41:08,777 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,777 INFO sqlalchemy.engine.base.Engine ('천마어린이집', '강종수', '서울특별시 송파구 성내천로 315 ,(마천동) (마천1동)', '02', '448', '4218', 18)
2021-08-18 17:41:08,780 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,780 INFO sqlalchemy.engine.base.Engine ('구립아람어린이집', '조영자', '서울특별시 강북구 삼양로41길 60 ,(미아동 791-2119) (삼양동) (삼양동)', '02', '986', '2612', 3)
2021-08-18 17:41:08,781 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,782 INFO sqlalchemy.engine.base.Engine ('도봉2동어린이집', '한병철', '서울특별시 도봉구 도봉로160길 24-12 (도봉제2동)', '02', '954', '2364', 10)
2021-08-18 17:41:08,783 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,784 INFO sqlalchemy.engine.base.Engine ('구립 신나는어린이집', '최정식', '서울특별시 양천구 목동남로 94 (신정7동)', '02', '2642', '6914', 19)
2021-08-18 17:41:08,785 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,786 INFO sqlalchemy.engine.base.Engine ('원효어린이집', '최영자', '서울특별시 용산구 원효로41가길 14-19 (원효로제2동)', '02', '704', '2463', 21)
2021-08-18 17:41:08,786 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,787 INFO sqlalchemy.engine.base.Engine ('구립 성일어린이집', '서정남', '서울특별시 성동구 아차산로1길 30 ,(성수동1가) (성수1가제2동)', '02', '464', '5219', 16)
2021-08-18 17:41:08,788 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,789 INFO sqlalchemy.engine.base.Engine ('구민회관어린이집', '장도현', '서울특별시 강동구 상암로 168 ,구민회관1층 (천호동41) (천호제1동)', '02', '483', '2474', 2)
2021-08-18 17:41:08,789 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,790 INFO sqlalchemy.engine.base.Engine ('나리어린이집', '전지훈', '서울특별시 성북구 화랑로 242-5 (석관동)', '02', '960', '3385', 17)
2021-08-18 17:41:08,791 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,792 INFO sqlalchemy.engine.base.Engine ('솔샘어린이집', '신정운', '서울특별시 성북구 보국문로16가길 82 ,(정릉동) (정릉제4동)', '02', '943', '1177', 17)
2021-08-18 17:41:08,794 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,795 INFO sqlalchemy.engine.base.Engine ('구립 도선어린이집', '류준혁', '서울특별시 성동구 왕십리로30길 17-1 (왕십리도선동)', '02', '2297', '9178', 16)
2021-08-18 17:41:08,797 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,797 INFO sqlalchemy.engine.base.Engine ('염리어린이집', '황정수', '서울특별시 마포구 숭문6길 22 ,(염리동) (염리동)', '02', '719', '4845', 13)
2021-08-18 17:41:08,798 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,799 INFO sqlalchemy.engine.base.Engine ('중곡4동어린이집', '류은영', '서울특별시 광진구 긴고랑로 149-8 ,(중곡동) (중곡제4동)', '02', '2201', '2704', 6)
2021-08-18 17:41:08,800 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,801 INFO sqlalchemy.engine.base.Engine ('양평3가어린이집', '안진호', '서울특별시 영등포구 선유서로34길 10 ,(양평동3가) (양평제1동)', '02', '2678', '8336', 20)
2021-08-18 17:41:08,803 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,804 INFO sqlalchemy.engine.base.Engine ('둥지어린이집', '최종수', '서울특별시 중랑구 공릉로14길 19 ,(묵동) (묵제1동)', '02', '974', '6893', 25)
2021-08-18 17:41:08,805 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,805 INFO sqlalchemy.engine.base.Engine ('구민어린이집', '박종수', '서울특별시 구로구 가마산로26길 34 ,(구로동) (구로제4동)', '02', '853', '9260', 7)
2021-08-18 17:41:08,807 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,807 INFO sqlalchemy.engine.base.Engine ('푸른누리어린이집', '권미숙', '서울특별시 서대문구 연희로20길 27 ,(연희동) (연희동)', '02', '324', '4306', 14)
2021-08-18 17:41:08,808 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,809 INFO sqlalchemy.engine.base.Engine ('미래어린이집', '강정남', '서울특별시 구로구 구로동로20길 57 ,(구로동) (구로제4동)', '02', '853', '1474', 7)
2021-08-18 17:41:08,810 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,811 INFO sqlalchemy.engine.base.Engine ('요한어린이집', '오정순', '서울특별시 중랑구 면목로37길 37 ,(면목동) (면목제7동)', '02', '439', '8696', 25)
2021-08-18 17:41:08,812 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,812 INFO sqlalchemy.engine.base.Engine ('구립 둥지어린이집', '황미숙', '서울특별시 양천구 월정로 289 ,(신월동) (신월5동)', '02', '2607', '9224', 19)
2021-08-18 17:41:08,813 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,814 INFO sqlalchemy.engine.base.Engine ('아동회관어린이집', '한은정', '서울특별시 종로구 지봉로13길 14 ,아동회관어린이집 (창신제3동)', '02', '763', '6038', 23)
2021-08-18 17:41:08,815 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,816 INFO sqlalchemy.engine.base.Engine ('구립삼각산동어린이집', '전준호', '서울특별시 강북구 삼양로19길 102 ,101호(미아동) (삼각산동)', '02', '988', '6019', 3)
2021-08-18 17:41:08,818 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,819 INFO sqlalchemy.engine.base.Engine ('약수어린이집', '송건우', '서울특별시 중구 다산로6길 15 ,(신당동) (약수동)', '02', '2252', '7672', 24)
2021-08-18 17:41:08,820 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,820 INFO sqlalchemy.engine.base.Engine ('88상암어린이집', '박민지', '서울특별시 마포구 월드컵북로44길 6 ,(상암동) (상암동)', '02', '374', '0816', 13)
2021-08-18 17:41:08,821 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,822 INFO sqlalchemy.engine.base.Engine ('하정어린이집', '윤진호', '서울특별시 영등포구 여의대방로43나길 6 ,(신길동) (신길제7동)', '02', '841', '5959', 20)

2021-08-18 17:41:08,823 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,824 INFO sqlalchemy.engine.base.Engine ('방죽어린이집', '김민석', '서울특별시 강남구 밤고개로24길 75 ,(율현동) (세곡동)', '02', '451', '2374', 1)
2021-08-18 17:41:08,825 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,826 INFO sqlalchemy.engine.base.Engine ('해바라기어린이집', '이건우', '서울특별시 강서구 등촌로13자길 39-16 (화곡제4동)', '02', '2643', '7307', 4)
2021-08-18 17:41:08,826 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,828 INFO sqlalchemy.engine.base.Engine ('구립 은혜어린이집', '전정식', '서울특별시 양천구 목동로15길 24 ,(신정동) (신정4동)', '02', '2603', '1020', 19)
2021-08-18 17:41:08,829 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,829 INFO sqlalchemy.engine.base.Engine ('영삼어린이집', '황진호', '서울특별시 영등포구 영등포로35길 13 ,(영등포동6가) (영등포동)', '02', '2634', '7859', 20)
2021-08-18 17:41:08,830 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,831 INFO sqlalchemy.engine.base.Engine ('재능어린이집', '류예준', '서울특별시 관악구 서원6길 28 ,2층 (신림동) [서원동] (서원동)', '02', '885', '3014', 5)
2021-08-18 17:41:08,832 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,833 INFO sqlalchemy.engine.base.Engine ('남태령어린이집', '전성민', '서울특별시 서초구 전원말길 6 ,(방배동) (방배2동)', '02', '588', '0640', 15)
2021-08-18 17:41:08,833 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,834 INFO sqlalchemy.engine.base.Engine ('세종마을어린이집', '박순자', '서울특별시 종로구 옥인길 89 ,(옥인동) (청운효자동)', '02', '732', '3070', 23)
2021-08-18 17:41:08,835 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,835 INFO sqlalchemy.engine.base.Engine ('구립개미어린이집', '강지훈', '서울특별시 금천구 독산로54길 251 ,(독산동) (독산제3동)', '02', '855', '2627', 8)
2021-08-18 17:41:08,836 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,837 INFO sqlalchemy.engine.base.Engine ('공릉어린이집', '권상철', '서울특별시 노원구 동일로192나길 8 ,(동일로 192 나길 8) (공릉동) (공릉1동)', '02', '977', '0488', 9)
2021-08-18 17:41:08,838 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,838 INFO sqlalchemy.engine.base.Engine ('도봉1동어린이집', '조성진', '서울특별시 도봉구 도봉로175길 10 ,(도봉1동어린이집) (도봉동) (도봉제1동)', '02', '955', '8807', 10)
2021-08-18 17:41:08,839 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,839 INFO sqlalchemy.engine.base.Engine ('구립우리어린이집', '최병철', '서울특별시 동작구 솔밭로 74-1 ,구립우리어린이집 (사당동) (사당제5동)', '02', '584', '7684', 12)
2021-08-18 17:41:08,840 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,841 INFO sqlalchemy.engine.base.Engine ('구립 개나리어린이집', '황영진', '서울특별시 은평구 연서로37가길 8-25 ,구립 개나리어린이집 (불광동) (불광제2동)', '02', '385', '0331', 22)
2021-08-18 17:41:08,843 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,844 INFO sqlalchemy.engine.base.Engine ('양평동교회어린이집', '윤유진', '서울특별시 영등포구 양평로20길 11 ,(양평동4가) (양평제2동)', '02', '2631', '9610', 20)
2021-08-18 17:41:08,844 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,845 INFO sqlalchemy.engine.base.Engine ('구립흑석어린이집', '황준영', '서울특별시 동작구 서달로 61 (흑석동)', '02', '813', '9598', 12)
2021-08-18 17:41:08,846 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,847 INFO sqlalchemy.engine.base.Engine ('청구어린이집', '권지영', '서울특별시 중구 다산로24길 81 ,(신당동) (청구동)', '02', '2236', '1466', 24)
2021-08-18 17:41:08,848 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,849 INFO sqlalchemy.engine.base.Engine ('구립새길어린이집', '전지영', '서울특별시 금천구 시흥대로12길 82 ,(시흥동) (시흥제3동)', '02', '807', '2460', 8)
2021-08-18 17:41:08,849 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,850 INFO sqlalchemy.engine.base.Engine ('휘경어린이집', '강유진', '서울특별시 동대문구 망우로10가길 15 ,(휘경동 308-196) (휘경제2동)', '02', '2243', '2831', 11)
2021-08-18 17:41:08,851 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,852 INFO sqlalchemy.engine.base.Engine ('청파어린이집', '임성호', '서울특별시 용산구 청파로49길 19 ,(청파동2가) (청파동)', '02', '716', '7998', 21)
2021-08-18 17:41:08,853 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,854 INFO sqlalchemy.engine.base.Engine ('보광 어린이집', '조영식', '서울특별시 용산구 보광로12가길 48-4 ,보광 어린이집 (보광동) (보광동)', '02', '795', '2844', 21)
2021-08-18 17:41:08,856 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,858 INFO sqlalchemy.engine.base.Engine ('큰나무어린이집', '서건우', '서울특별시 성북구 화랑로18길 74 ,(상월곡동) (월곡제2동)', '02', '964', '2919', 17)
2021-08-18 17:41:08,859 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,859 INFO sqlalchemy.engine.base.Engine ('온수어린이집', '박건우', '서울특별시 구로구 부일로1길 72 ,온수어린이집 (수궁동)', '02', '2684', '4745', 7)
2021-08-18 17:41:08,860 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,861 INFO sqlalchemy.engine.base.Engine ('선화어린이집', '박영식', '서울특별시 서대문구 경기대로 26-26 ,(충현동) (충현동)', '02', '313', '0177', 14)
2021-08-18 17:41:08,862 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,862 INFO sqlalchemy.engine.base.Engine ('은도어린이집', '장수빈', '서울특별시 강서구 화곡로26길 33 ,(화곡동) (화곡제1동)', '02', '2693', '8840', 4)
2021-08-18 17:41:08,863 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,864 INFO sqlalchemy.engine.base.Engine ('구립연꽃어린이집', '류영자', '서울특별시 동작구 국사봉1길 235-1 (상도제3동)', '02', '823', '3203', 12)
2021-08-18 17:41:08,864 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,865 INFO sqlalchemy.engine.base.Engine ('구립 한아름어린이집', '최영자', '서울특별시 양천구 중앙로55길 6-1 (신월2동)', '02', '2690', '6837', 19)
2021-08-18 17:41:08,866 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,868 INFO sqlalchemy.engine.base.Engine ('구립꿈나무어린이집', '안수빈', '서울특별시 동작구 여의대방로36길 11 ,(대방동) (대방동)', '02', '821', '5615', 12)
2021-08-18 17:41:08,869 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,871 INFO sqlalchemy.engine.base.Engine ('좋은어린이집', '황민재', '서울특별시 광진구 구의강변로3길 31 ,(구의동) (구의제3동)', '02', '454', '8548', 6)
2021-08-18 17:41:08,872 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,873 INFO sqlalchemy.engine.base.Engine ('동빙고어린이집', '한현준', '서울특별시 용산구 녹사평대로14길 7 ,(동빙고동) (서빙고동)', '02', '795', '3935', 21)
2021-08-18 17:41:08,875 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,876 INFO sqlalchemy.engine.base.Engine ('신촌어린이집', '윤영철', '서울특별시 서대문구 연세로2나길 48 ,(창천동) (신촌동)', '02', '363', '0682', 14)
2021-08-18 17:41:08,877 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,877 INFO sqlalchemy.engine.base.Engine ('당산1동어린이집', '송정식', '서울특별시 영등포구 영등포로25길 24 ,(당산동1가) (당산제1동)', '02', '2675', '4295', 20)
2021-08-18 17:41:08,878 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,881 INFO sqlalchemy.engine.base.Engine ('면일어린이집', '안미경', '서울특별시 중랑구 상봉로19길 13 ,(면목동) (면목본동)', '02', '495', '4604', 25)
2021-08-18 17:41:08,882 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,883 INFO sqlalchemy.engine.base.Engine ('종암어린이집', '정미숙', '서울특별시 성북구 종암로23길 11 ,(종암동) (종암동)', '02', '923', '8465', 17)
2021-08-18 17:41:08,884 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,886 INFO sqlalchemy.engine.base.Engine ('구립 금호어린이집', '권지훈', '서울특별시 성동구 금호동2가 매봉18길 125 ,금호어린이집 (금호2.3가동)', '02', '2234', '1382', 16)
2021-08-18 17:41:08,888 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,888 INFO sqlalchemy.engine.base.Engine ('구립옥계어린이집', '권건우', '서울특별시 금천구 시흥대로86길 20 ,(독산동) (독산제2동)', '02', '805', '9539', 8)
2021-08-18 17:41:08,890 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,891 INFO sqlalchemy.engine.base.Engine ('구립양지어린이집', '권지훈', '서울특별시 관악구 양지12길 18-1 ,(신림동) (삼성동)', '02', '882', '4359', 5)
2021-08-18 17:41:08,892 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,893 INFO sqlalchemy.engine.base.Engine ('양평1동 어린이집', '장정식', '서울특별시 영등포구 양평동1가 선유서로24길 21 ,양평1동어린이집 (양평제1동)', '02', '2677', '7781', 20)
2021-08-18 17:41:08,894 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,895 INFO sqlalchemy.engine.base.Engine ('구립양지어린이집', '류미경', '서울특별시 동작구 사당로23바길 9 ,삼성래미안내 구립양지어린이집 (사당동) (사당제3동)', '02', '533', '9250', 12)
2021-08-18 17:41:08,896 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,896 INFO sqlalchemy.engine.base.Engine ('구립 해나라어린이집', '강준영', '서울특별시 양천구 오목로5길 34 ,(신월동) (신월4동)', '02', '2607', '0053', 19)
2021-08-18 17:41:08,897 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,898 INFO sqlalchemy.engine.base.Engine ('샛별어린이집', '오영철', '서울특별시 구로구 구로중앙로32가길 18 (구로제5동)', '02', '856', '3009', 7)
2021-08-18 17:41:08,899 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,899 INFO sqlalchemy.engine.base.Engine ('삼선어린이집', '황지훈', '서울특별시 성북구 삼선교로4길 147 ,(삼선동1가) (삼선동)', '02', '763', '3415', 17)
2021-08-18 17:41:08,900 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,901 INFO sqlalchemy.engine.base.Engine ('라온어린이집', '박예준', '서울특별시 강동구 천중로39길 43-1 ,(천호1동49-33) (천호제1동)', '02', '441', '9000', 2)
2021-08-18 17:41:08,902 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,902 INFO sqlalchemy.engine.base.Engine ('다솔어린이집', '황현준', '서울특별시 강남구 개포로 264 ,단지 내 다솔어린이집(개포동, 개포래미안포레스트) (개포제4동)', '02', '575', '2577', 1)
2021-08-18 17:41:08,903 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,904 INFO sqlalchemy.engine.base.Engine ('구립고덕어린이집', '황준호', '서울특별시 강동구 고덕로61길 34 ,상록아파트 단지내 (고덕동307) (고덕제1동)', '02', '426', '3218', 2)
2021-08-18 17:41:08,906 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,907 INFO sqlalchemy.engine.base.Engine ('신당동어린이집', '최민지', '서울특별시 중구 청구로8길 41 ,(신당동) (신당동)', '02', '2233', '9478', 24)
2021-08-18 17:41:08,909 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,909 INFO sqlalchemy.engine.base.Engine ('명륜어린이집', '신예은', '서울특별시 종로구 성균관로13길 66 ,(명륜1가) (혜화동)', '02', '742', '8436', 23)
2021-08-18 17:41:08,910 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,911 INFO sqlalchemy.engine.base.Engine ('월계2동어린이집', '강종수', '서울특별시 노원구 월계로45길 21 ,(월계동, 롯데캐슬루나아파트 내) (월계2동)', '02', '992', '6087', 9)
2021-08-18 17:41:08,912 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,913 INFO sqlalchemy.engine.base.Engine ('창3동어린이집', '조성호', '서울특별시 도봉구 덕릉로62길 57-7 (창제3동)', '02', '904', '8790', 10)
2021-08-18 17:41:08,914 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,915 INFO sqlalchemy.engine.base.Engine ('샘물어린이집', '박서연', '서울특별시 마포구 방울내로 21 ,구립샘물어린이집 (망원제2동)', '02', '336', '3424', 13)
2021-08-18 17:41:08,920 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,923 INFO sqlalchemy.engine.base.Engine ('세화어린이집', '임준서', '서울특별시 중랑구 동일로123길 125 ,(중화동) (중화제2동)', '02', '492', '4789', 25)
2021-08-18 17:41:08,924 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,925 INFO sqlalchemy.engine.base.Engine ('대림1동어린이집', '송광수', '서울특별시 영등포구 디지털로 441 ,(대림동) (대림제1동)', '02', '845', '0589', 20)
2021-08-18 17:41:08,926 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:08,927 INFO sqlalchemy.engine.base.Engine ('구립 신정3동어린이집', '신영자', '서울특별시 양천구 중앙로47길 30 ,(신정동) (신정3동)', '02', '2694', '7036', 19)
2021-08-18 17:41:08,928 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,929 INFO sqlalchemy.engine.base.Engine ('구립독산1동어린이집', '김정식', '서울특별시 금천구 벚꽃로18길 33 ,(독산동) (독산제1동)', '02', '804', '8049', 8)
2021-08-18 17:41:08,930 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,930 INFO sqlalchemy.engine.base.Engine ('은화어린이집', '황동현', '서울특별시 서대문구 간호대로 48 ,선강빌딩 2, 3층 (홍제제3동)', '02', '391', '3248', 14)
2021-08-18 17:41:08,933 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,934 INFO sqlalchemy.engine.base.Engine ('구립신일어린이집', '최미경', '서울특별시 관악구 문성로28길 51 ,(신림동) [신림동] (신원동)', '02', '854', '0140', 5)
2021-08-18 17:41:08,935 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,935 INFO sqlalchemy.engine.base.Engine ('방학2동어린이집', '신영철', '서울특별시 도봉구 방학로 180 ,(방학동) (방학제2동)', '02', '955', '8718', 10)
2021-08-18 17:41:08,936 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,937 INFO sqlalchemy.engine.base.Engine ('가좌제일어린이집', '권경자', '서울특별시 서대문구 수색로8길 46 ,(북가좌동) (북가좌제1동)', '02', '304', '6117', 14)
2021-08-18 17:41:08,938 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,938 INFO sqlalchemy.engine.base.Engine ('구립 녹번어린이집', '강광수', '서울특별시 은평구 통일로62길 17 ,(녹번동) (녹번동)', '02', '352', '7818', 22)
2021-08-18 17:41:08,939 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,940 INFO sqlalchemy.engine.base.Engine ('꿈마루어린이집', '한영환', '서울특별시 동대문구 전농로36길 29-3 ,꿈마루어린이집 (전농제1동)', '02', '2213', '7974', 11)
2021-08-18 17:41:08,943 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,944 INFO sqlalchemy.engine.base.Engine ('또또어린이집', '박서연', '서울특별시 중랑구 동일로 584 ,(면목동) (면목제5동)', '02', '434', '8998', 25)
2021-08-18 17:41:08,945 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,945 INFO sqlalchemy.engine.base.Engine ('구립 행응어린이집', '안순자', '서울특별시 성동구 독서당로63길 34 ,(행당동) (행당제2동)', '02', '2293', '4870', 16)
2021-08-18 17:41:08,946 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,947 INFO sqlalchemy.engine.base.Engine ('구립새싹어린이집', '장정호', '서울특별시 동작구 동작대로29길 119 ,극동아파트111동 뒤 새싹어린이집 (사당제2동)', '02', '537', '4216', 12)
2021-08-18 17:41:08,948 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,949 INFO sqlalchemy.engine.base.Engine ('목화어린이집', '김건우', '서울특별시 성북구 오패산로4길 39-1 (월곡제2동)', '02', '914', '0709', 17)
2021-08-18 17:41:08,949 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,950 INFO sqlalchemy.engine.base.Engine ('상계4동어린이집', '최민지', '서울특별시 노원구 덕릉로130길 6 ,(상계동) (상계3.4동)', '02', '936', '6545', 9)
2021-08-18 17:41:08,951 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,951 INFO sqlalchemy.engine.base.Engine ('금강어린이집', '이준호', '서울특별시 중랑구 용마산로100길 20 ,(망우동) (망우제3동)', '02', '434', '9669', 25)
2021-08-18 17:41:08,953 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,953 INFO sqlalchemy.engine.base.Engine ('북부어린이집', '안지영', '서울특별시 노원구 동일로245길 56 ,(상계동) (상계1동)', '02', '935', '5664', 9)
2021-08-18 17:41:08,954 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,955 INFO sqlalchemy.engine.base.Engine ('능곡어린이집', '박유진', '서울특별시 구로구 고척로52라길 28 ,(고척동) (고척제2동)', '02', '2685', '6787', 7)
2021-08-18 17:41:08,957 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,959 INFO sqlalchemy.engine.base.Engine ('구립새빛어린이집', '임서연', '서울특별시 관악구 신사로10길 29 ,(신림동) [신사동] (신사동)', '02', '862', '1255', 5)
2021-08-18 17:41:08,961 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,962 INFO sqlalchemy.engine.base.Engine ('구립정심어린이집', '송민재', '서울특별시 금천구 독산로54길 129 ,(독산동) (독산제4동)', '02', '853', '2557', 8)
2021-08-18 17:41:08,963 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,963 INFO sqlalchemy.engine.base.Engine ('청운어린이집', '김정수', '서울특별시 종로구 자하문로35길 21 (청운효자동)', '02', '730', '9261', 23)
2021-08-18 17:41:08,965 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,965 INFO sqlalchemy.engine.base.Engine ('세화어린이집', '이영철', '서울특별시 구로구 구로동로8길 27 ,(구로동) (구로제4동)', '02', '853', '2558', 7)
2021-08-18 17:41:08,967 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,968 INFO sqlalchemy.engine.base.Engine ('구립 아이솔 어린이집', '전성호', '서울특별시 강서구 개화동로27길 13 ,(방화동) (방화제2동)', '02', '2664', '9574', 4)
2021-08-18 17:41:08,969 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,970 INFO sqlalchemy.engine.base.Engine ('구립 금일어린이집', '정병철', '서울특별시 성동구 난계로 18 ,(금호동1가) (금호1가동)', '02', '2291', '8629', 16)
2021-08-18 17:41:08,972 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,972 INFO sqlalchemy.engine.base.Engine ('구립 대현어린이집', '김성민', '서울특별시 성동구 행당로 15 ,(금호동1가) (금호1가동)', '02', '2299', '5935', 16)
2021-08-18 17:41:08,973 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,974 INFO sqlalchemy.engine.base.Engine ('상록수어린이집', '임지훈', '서울특별시 종로구 송월1길 73-7 ,상록수어린이집 (교남동)', '02', '738', '1773', 23)
2021-08-18 17:41:08,976 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,976 INFO sqlalchemy.engine.base.Engine ('이촌어린이집', '전영숙', '서울특별시 용산구 이촌로14길 11-22 (이촌제2동)', '02', '713', '9920', 21)
2021-08-18 17:41:08,978 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,978 INFO sqlalchemy.engine.base.Engine ('구립선봉어린이집', '안민석', '서울특별시 관악구 봉천로27길 20 ,(봉천동) [은천동] (은천동)', '02', '877', '3121', 5)

2021-08-18 17:41:08,979 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,980 INFO sqlalchemy.engine.base.Engine ('구립문성어린이집', '조정호', '서울특별시 관악구 시흥대로164길 27 ,(신림동) [조원동] (조원동)', '02', '856', '5621', 5)
2021-08-18 17:41:08,980 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,981 INFO sqlalchemy.engine.base.Engine ('신덕어린이집', '권지원', '서울특별시 마포구 만리재로 34 (공덕동)', '02', '712', '9348', 13)
2021-08-18 17:41:08,982 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,983 INFO sqlalchemy.engine.base.Engine ('구립 용답어린이집', '서영길', '서울특별시 성동구 자동차시장길 22 ,용답어린이집 (용답동)', '02', '2245', '8538', 16)
2021-08-18 17:41:08,985 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,986 INFO sqlalchemy.engine.base.Engine ('구립 금봉어린이집', '류준영', '서울특별시 성동구 독서당로57가길 24 ,금봉어린이집 (금호1가동)', '02', '2291', '5803', 16)
2021-08-18 17:41:08,987 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,988 INFO sqlalchemy.engine.base.Engine ('도담어린이집', '전준호', '서울특별시 동대문구 사가정로17길 21 ,구립 도담 어린이집 (전농제2동)', '02', '2244', '8703', 11)
2021-08-18 17:41:08,989 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,990 INFO sqlalchemy.engine.base.Engine ('구립암사어린이집', '장미영', '서울특별시 강동구 상암로4가길 28 ,구립암사어린이집 (암사동) (암사제2동)', '02', '3426', '7543', 2)
2021-08-18 17:41:08,990 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,991 INFO sqlalchemy.engine.base.Engine ('강동어린이집', '강은정', '서울특별시 강동구 고덕로 131 ,(암사동 414-2) 롯데캐슬퍼스트아파트 관리동 (암사제3동)', '02', '428', '7875', 2)
2021-08-18 17:41:08,992 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,993 INFO sqlalchemy.engine.base.Engine ('궁동어린이집', '한경자', '서울특별시 구로구 오리로17길 48 ,(궁동) (수궁동)', '02', '2685', '4596', 7)
2021-08-18 17:41:08,993 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,994 INFO sqlalchemy.engine.base.Engine ('메꽃어린이집', '정정운', '서울특별시 동대문구 답십리로 320-1 (장안제1동)', '02', '2212', '6096', 11)
2021-08-18 17:41:08,997 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:08,998 INFO sqlalchemy.engine.base.Engine ('만리어린이집', '강준호', '서울특별시 중구 만리동2가 만리재로 175 ,(만리동2가) (중림동)', '02', '312', '8718', 24)
2021-08-18 17:41:08,999 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,000 INFO sqlalchemy.engine.base.Engine ('반포어린이집', '김영환', '서울특별시 서초구 사평대로20길 54 ,(반포동) (반포4동)', '02', '537', '6670', 15)
2021-08-18 17:41:09,001 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,002 INFO sqlalchemy.engine.base.Engine ('신내어린이집', '송혜진', '서울특별시 중랑구 용마산로125가길 39-26 ,(신내동) (신내1동)', '02', '432', '0880', 25)
2021-08-18 17:41:09,003 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,004 INFO sqlalchemy.engine.base.Engine ('열매어린이집', '황서현', '서울특별시 중랑구 동일로100길 26 ,(면목동) (면목제2동)', '02', '433', '9889', 25)
2021-08-18 17:41:09,005 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,005 INFO sqlalchemy.engine.base.Engine ('중계어린이집', '한정웅', '서울특별시 노원구 중계로 167 ,(중계동) (중계본동)', '02', '930', '0040', 9)
2021-08-18 17:41:09,006 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,007 INFO sqlalchemy.engine.base.Engine ('구립난우어린이집', '강영자', '서울특별시 관악구 난곡로61길 1 ,(신림동) [미성동] (미성동)', '02', '862', '4547', 5)
2021-08-18 17:41:09,007 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,008 INFO sqlalchemy.engine.base.Engine ('구립미림어린이집', '장종수', '서울특별시 관악구 태흥길 4 ,(신림동) [삼성동] (삼성동)', '02', '878', '6150', 5)
2021-08-18 17:41:09,011 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,012 INFO sqlalchemy.engine.base.Engine ('늘푸른어린이집', '윤도현', '서울특별시 노원구 노원로34길 9 ,늘푸른어린이집 (상계동) (상계10동)', '02', '936', '0050', 9)
2021-08-18 17:41:09,013 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,014 INFO sqlalchemy.engine.base.Engine ('구립 금옥어린이집', '정영철', '서울특별시 성동구 매봉18길 1 ,(옥수동) (옥수동)', '02', '2297', '6738', 16)
2021-08-18 17:41:09,015 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,016 INFO sqlalchemy.engine.base.Engine ('본심어린이집', '신진호', '서울특별시 성북구 장위로8길 20 ,(상월곡동) (장위제1동)', '02', '912', '2546', 17)
2021-08-18 17:41:09,017 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,018 INFO sqlalchemy.engine.base.Engine ('구립수유1동어린이집', '최영자', '서울특별시 강북구 인수봉로38가길 28 ,(수유동) (수유1동)', '02', '988', '9521', 3)
2021-08-18 17:41:09,020 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,021 INFO sqlalchemy.engine.base.Engine ('상암어린이집', '박현준', '서울특별시 마포구 월드컵북로47길 8 ,월드컵아파트 1단지 (상암동)', '02', '374', '0216', 13)
2021-08-18 17:41:09,022 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,023 INFO sqlalchemy.engine.base.Engine ('한울어린이집', '오정호', '서울특별시 강서구 우현로 34 (우장산동)', '02', '2602', '3886', 4)
2021-08-18 17:41:09,024 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,025 INFO sqlalchemy.engine.base.Engine ('혜화어린이집', '전도현', '서울특별시 종로구 대학로14길 34 (혜화동)', '02', '742', '2694', 23)
2021-08-18 17:41:09,025 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,026 INFO sqlalchemy.engine.base.Engine ('구립 동호어린이집', '전상철', '서울특별시 성동구 금호동3가 금호산9길 9 ,(금호동3가) (금호2.3가동)', '02', '2235', '0914', 16)
2021-08-18 17:41:09,027 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,028 INFO sqlalchemy.engine.base.Engine ('우리어린이집', '신정웅', '서울특별시 서대문구 간호대로4길 10 ,우리어린이집 (홍제제3동)', '02', '391', '8233', 14)
2021-08-18 17:41:09,029 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:09,030 INFO sqlalchemy.engine.base.Engine ('잠일어린이집', '이종수', '서울특별시 송파구 삼전로13길 44 ,(잠실동) (잠실본동)', '02', '412', '6681', 18)
2021-08-18 17:41:09,031 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,032 INFO sqlalchemy.engine.base.Engine ('수서어린이집', '김영환', '서울특별시 강남구 광평로 242 ,(수서동) (수서동)', '02', '3412', '4208', 1)
2021-08-18 17:41:09,033 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,034 INFO sqlalchemy.engine.base.Engine ('서연어린이집', '박성민', '서울특별시 서대문구 홍제천로4길 18 ,(연희동) (연희동)', '02', '334', '9669', 14)
2021-08-18 17:41:09,035 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,035 INFO sqlalchemy.engine.base.Engine ('성산어린이집', '김영철', '서울특별시 마포구 월드컵북로30길 14 ,(성산동) (성산제2동)', '02', '302', '3221', 13)
2021-08-18 17:41:09,036 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,037 INFO sqlalchemy.engine.base.Engine ('금파어린이집', '박상훈', '서울특별시 중랑구 용마산로 520-5 ,(망우동) (망우본동)', '02', '434', '0600', 25)
2021-08-18 17:41:09,038 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,039 INFO sqlalchemy.engine.base.Engine ('고일어린이집', '전민재', '서울특별시 강동구 양재대로156길 121 (고덕제1동)', '02', '429', '4829', 2)
2021-08-18 17:41:09,040 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,041 INFO sqlalchemy.engine.base.Engine ('구립은천어린이집', '안정운', '서울특별시 관악구 국회단지10길 22 ,(봉천동) [은천동] (은천동)', '02', '889', '3176', 5)
2021-08-18 17:41:09,042 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,042 INFO sqlalchemy.engine.base.Engine ('구립비안어린이집', '윤은영', '서울특별시 관악구 장군봉6길 8 ,(봉천동) [청룡동] (청룡동)', '02', '889', '0351', 5)
2021-08-18 17:41:09,043 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,044 INFO sqlalchemy.engine.base.Engine ('노고산어린이집', '조성호', '서울특별시 마포구 신촌로20길 15 ,(노고산동) (대흥동)', '02', '717', '0220', 13)
2021-08-18 17:41:09,044 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,045 INFO sqlalchemy.engine.base.Engine ('북악어린이집', '김예준', '서울특별시 성북구 솔샘로6마길 5 ,(정릉동) (정릉제3동)', '02', '912', '1644', 17)
2021-08-18 17:41:09,046 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,046 INFO sqlalchemy.engine.base.Engine ('필동어린이집', '김정남', '서울특별시 중구 퇴계로36가길 60 ,(필동2가) (필동)', '02', '2274', '2268', 24)
2021-08-18 17:41:09,048 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,048 INFO sqlalchemy.engine.base.Engine ('구립서원어린이집', '조경회', '서울특별시 관악구 서원3길 25 ,(신림동) [서원동] (서원동)', '02', '889', '5845', 5)
2021-08-18 17:41:09,049 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,050 INFO sqlalchemy.engine.base.Engine ('구립가산어린이집', '이영철', '서울특별시 금천구 벚꽃로38길 35 ,(가산동) (가산동)', '02', '854', '4370', 8)
2021-08-18 17:41:09,051 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,053 INFO sqlalchemy.engine.base.Engine ('신당5동어린이집', '정정수', '서울특별시 중구 퇴계로88가길 8-10 (신당제5동)', '02', '2234', '2745', 24)
2021-08-18 17:41:09,054 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,054 INFO sqlalchemy.engine.base.Engine ('구립 무학어린이집', '송준호', '서울특별시 성동구 난계로 114-31 ,금호베스트빌아파트 임대관리동 (하왕십리동) (왕십리제2동)', '02', '2293', '3067', 16)
2021-08-18 17:41:09,055 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,056 INFO sqlalchemy.engine.base.Engine ('구립사당어린이집', '임정호', '서울특별시 동작구 사당로27길 190 ,(사당동) (사당제3동)', '02', '533', '7155', 12)
2021-08-18 17:41:09,057 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,059 INFO sqlalchemy.engine.base.Engine ('구립청룡어린이집', '장정식', '서울특별시 관악구 참숯1길 7 ,(봉천동) [청룡동] (청룡동)', '02', '886', '1245', 5)
2021-08-18 17:41:09,060 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,060 INFO sqlalchemy.engine.base.Engine ('구립구암어린이집', '오준혁', '서울특별시 관악구 구암길 98 ,1층 구암어린이집 (봉천동) [성현동] (성현동)', '02', '883', '6647', 5)
2021-08-18 17:41:09,061 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,062 INFO sqlalchemy.engine.base.Engine ('고은어린이집', '송은경', '서울특별시 서대문구 모래내로 459-6 ,(홍제동 107-17) (홍제제1동)', '02', '391', '7466', 14)
2021-08-18 17:41:09,063 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,063 INFO sqlalchemy.engine.base.Engine ('구립 홍익어린이집', '서종수', '서울특별시 성동구 마장로 141 ,(홍익동) (왕십리도선동)', '02', '2293', '2596', 16)
2021-08-18 17:41:09,064 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,065 INFO sqlalchemy.engine.base.Engine ('쌍문2동어린이집', '강민재', '서울특별시 도봉구 방학로5길 34 ,(쌍문동) (쌍문제2동)', '02', '902', '6966', 10)
2021-08-18 17:41:09,066 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,066 INFO sqlalchemy.engine.base.Engine ('햇살어린이집', '김정수', '서울특별시 동대문구 청계천로 547 ,(용두동 696-9) (용신동)', '02', '962', '5519', 11)
2021-08-18 17:41:09,069 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,071 INFO sqlalchemy.engine.base.Engine ('자양어린이집', '정준혁', '서울특별시 광진구 자양번영로 35 ,(자양동) (자양제3동)', '02', '452', '0748', 6)
2021-08-18 17:41:09,072 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,073 INFO sqlalchemy.engine.base.Engine ('천호어린이집', '윤미영', '서울특별시 강동구 천중로35길 60 ,(천호동 48-2호) (천호제1동)', '02', '483', '1439', 2)
2021-08-18 17:41:09,074 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,075 INFO sqlalchemy.engine.base.Engine ('월계3동어린이집', '전정수', '서울특별시 노원구 마들로 31 ,3동(월계동, 한진한화그랑빌) (월계3동)', '02', '973', '8181', 9)
2021-08-18 17:41:09,076 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,077 INFO sqlalchemy.engine.base.Engine ('이태원어린이집', '박미숙', '서울특별시 용산구 녹사평대로40나길 38-3 (이태원제2동)', '02', '798', '2592', 21)

2021-08-18 17:41:09,078 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,079 INFO sqlalchemy.engine.base.Engine ('서강어린이집', '조준혁', '서울특별시 마포구 와우산로30길 79 ,(창전동) (서강동)', '02', '337', '1394', 13)
2021-08-18 17:41:09,080 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,081 INFO sqlalchemy.engine.base.Engine ('서계어린이집', '김예은', '서울특별시 용산구 청파로93길 25 ,서계어린이집 (청파동)', '02', '715', '6046', 21)
2021-08-18 17:41:09,082 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,082 INFO sqlalchemy.engine.base.Engine ('누상어린이집', '이영식', '서울특별시 종로구 옥인길 23-4 ,(누상동) (청운효자동)', '02', '738', '6711', 23)
2021-08-18 17:41:09,083 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,084 INFO sqlalchemy.engine.base.Engine ('창전어린이집', '류예준', '서울특별시 마포구 창전로 69 ,(창전동) (서강동)', '02', '324', '5131', 13)
2021-08-18 17:41:09,085 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,086 INFO sqlalchemy.engine.base.Engine ('인왕어린이집', '윤민지', '서울특별시 종로구 통일로18길 9 ,인왕산 아이파크단지내 (무악동)', '02', '738', '8577', 23)
2021-08-18 17:41:09,088 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,089 INFO sqlalchemy.engine.base.Engine ('구립탑골어린이집', '김예준', '서울특별시 금천구 금하로 764 ,(시흥동) (시흥제2동)', '02', '803', '2070', 8)
2021-08-18 17:41:09,091 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,092 INFO sqlalchemy.engine.base.Engine ('구립선재어린이집', '김정자', '서울특별시 동작구 노량진로32길 62 ,(본동) (노량진제1동)', '02', '815', '0274', 12)
2021-08-18 17:41:09,094 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,095 INFO sqlalchemy.engine.base.Engine ('양평2동어린이집', '조정수', '서울특별시 영등포구 선유로53길 20-7 ,(양평동4가) (양평제2동)', '02', '2634', '7383', 20)
2021-08-18 17:41:09,096 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,098 INFO sqlalchemy.engine.base.Engine ('구립율곡어린이집', '조정호', '서울특별시 관악구 신우길 1 ,(신림동) [삼성동] (삼성동)', '02', '889', '7682', 5)
2021-08-18 17:41:09,099 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,100 INFO sqlalchemy.engine.base.Engine ('남산숲어린이집', '이영일', '서울특별시 중구 동호로5길 193 ,남산숲어린이집 (신당동) (약수동)', '02', '2234', '2753', 24)
2021-08-18 17:41:09,101 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,102 INFO sqlalchemy.engine.base.Engine ('이화어린이집', '박영길', '서울특별시 중랑구 면목로27길 85 ,(면목동) (면목제4동)', '02', '432', '4425', 25)
2021-08-18 17:41:09,104 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,105 INFO sqlalchemy.engine.base.Engine ('구립 마장어린이집', '최준호', '서울특별시 성동구 마장로44길 10 ,(마장동) (마장동)', '02', '2293', '9394', 16)
2021-08-18 17:41:09,106 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,106 INFO sqlalchemy.engine.base.Engine ('노원어린이집', '오종수', '서울특별시 노원구 동일로239다길 23 ,(상계동) (상계1동)', '02', '936', '0649', 9)
2021-08-18 17:41:09,107 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,108 INFO sqlalchemy.engine.base.Engine ('장안어린이집', '박지영', '서울특별시 동대문구 천호대로89길 58 ,(장안동) (장안제1동)', '02', '2212', '5178', 11)
2021-08-18 17:41:09,108 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,109 INFO sqlalchemy.engine.base.Engine ('구립삼양어린이집', '임정호', '서울특별시 강북구 삼양로64길 32 -14 ,구립삼양어린이집 (삼양동)', '02', '989', '0259', 3)
2021-08-18 17:41:09,112 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,113 INFO sqlalchemy.engine.base.Engine ('낙산어린이집', '서준혁', '서울특별시 종로구 창신길 210-11 ,낙산어린이집 (창신동) (창신제2동)', '02', '765', '1268', 23)
2021-08-18 17:41:09,114 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,115 INFO sqlalchemy.engine.base.Engine ('무악어린이집', '조지원', '서울특별시 종로구 통일로18길 64 ,(무악동) (무악동)', '02', '736', '8003', 23)
2021-08-18 17:41:09,116 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,117 INFO sqlalchemy.engine.base.Engine ('구립합실어린이집', '송지훈', '서울특별시 관악구 광신길 113 ,(신림동) [삼성동] (삼성동)', '02', '878', '0254', 5)
2021-08-18 17:41:09,118 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,119 INFO sqlalchemy.engine.base.Engine ('구립 서마어린이집', '류정호', '서울특별시 성동구 청계천로 546 ,(마장동) (마장동)', '02', '2293', '5369', 16)
2021-08-18 17:41:09,121 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,122 INFO sqlalchemy.engine.base.Engine ('구립도담어린이집', '전정순', '서울특별시 관악구 청림3길 37 ,(봉천동) [청림동] (청림동)', '02', '886', '2240', 5)
2021-08-18 17:41:09,122 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,123 INFO sqlalchemy.engine.base.Engine ('마천어린이집', '오민수', '서울특별시 송파구 마천로61다길 28-7 (마천1동)', '02', '406', '2300', 18)
2021-08-18 17:41:09,124 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,125 INFO sqlalchemy.engine.base.Engine ('황학어린이집', '안지혜', '서울특별시 중구 난계로15길 23 ,(황학동) (황학동)', '02', '2234', '6840', 24)
2021-08-18 17:41:09,126 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,127 INFO sqlalchemy.engine.base.Engine ('상봉어린이집', '송정웅', '서울특별시 중랑구 상봉중앙로6길 57 ,(상봉동) (상봉제1동)', '02', '432', '3421', 25)
2021-08-18 17:41:09,128 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,128 INFO sqlalchemy.engine.base.Engine ('구립중앙어린이집', '류정식', '서울특별시 관악구 봉천로41길 35 ,(봉천동) [중앙동] (중앙동)', '02', '884', '5861', 5)
2021-08-18 17:41:09,129 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,130 INFO sqlalchemy.engine.base.Engine ('금화어린이집', '이미경', '서울특별시 서대문구 독립문로10길 15 ,(천연동) (천연동)', '02', '392', '0212', 14)
2021-08-18 17:41:09,131 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)

2021-08-18 17:41:09,132 INFO sqlalchemy.engine.base.Engine ('구립송천동어린이집', '강광수', '서울특별시 강북구 솔샘로60길 21 ,(미아동) (송천동)', '02', '981', '7391', 3)
2021-08-18 17:41:09,133 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,134 INFO sqlalchemy.engine.base.Engine ('구립문화어린이집', '안민석', '서울특별시 동작구 사당로13길 24 ,(사당동) (사당제3동)', '02', '534', '0175', 12)
2021-08-18 17:41:09,135 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,136 INFO sqlalchemy.engine.base.Engine ('구립신림어린이집', '안민서', '서울특별시 관악구 난곡로 67 ,(신림동) [난향동] (난향동)', '02', '853', '4487', 5)
2021-08-18 17:41:09,137 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,138 INFO sqlalchemy.engine.base.Engine ('동대문어린이집', '정정순', '서울특별시 동대문구 사가정로2길 13 ,(답십리동) (답십리제1동)', '02', '2213', '7994', 11)
2021-08-18 17:41:09,139 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,139 INFO sqlalchemy.engine.base.Engine ('안암어린이집', '안영일', '서울특별시 성북구 고려대로8길 5 ,(안암동2가) (안암동)', '02', '923', '5046', 17)
2021-08-18 17:41:09,140 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,141 INFO sqlalchemy.engine.base.Engine ('도봉도선어린이집', '서경회', '서울특별시 도봉구 마들로 756 ,(도봉동) (도봉제2동)', '02', '954', '4311', 10)
2021-08-18 17:41:09,141 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,142 INFO sqlalchemy.engine.base.Engine ('푸른하늘어린이집', '박영환', '서울특별시 동대문구 답십리로66길 75-4 ,(장안동 393-2) (장안제1동)', '02', '2212', '1036', 11)
2021-08-18 17:41:09,144 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,146 INFO sqlalchemy.engine.base.Engine ('진선미어린이집', '이준혁', '서울특별시 마포구 마포대로4나길 28 ,진선미어린이집 (도화동)', '02', '714', '1486', 13)
2021-08-18 17:41:09,149 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,150 INFO sqlalchemy.engine.base.Engine ('성북어린이집', '장정순', '서울특별시 성북구 동소문동1가 성북로4길 13-2 (성북동)', '02', '742', '1097', 17)
2021-08-18 17:41:09,151 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,152 INFO sqlalchemy.engine.base.Engine ('혜림어린이집', '류종수', '서울특별시 강동구 천중로39길 77 ,(천호동47-23) (천호제1동)', '02', '477', '1015', 2)
2021-08-18 17:41:09,154 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,154 INFO sqlalchemy.engine.base.Engine ('용산어린이집', '송종수', '서울특별시 용산구 한강로2가 한강대로38길 28 ,용산어린이집 (한강로동)', '02', '795', '0432', 21)
2021-08-18 17:41:09,155 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,156 INFO sqlalchemy.engine.base.Engine ('서대문어린이집', '윤정수', '서울특별시 서대문구 증가로29길 30-42 (북가좌제2동)', '02', '372', '0547', 14)
2021-08-18 17:41:09,157 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,158 INFO sqlalchemy.engine.base.Engine ('창신어린이집', '윤혜진', '서울특별시 종로구 창신5길 22 ,(창신동) (창신제1동)', '02', '743', '6302', 23)
2021-08-18 17:41:09,159 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,160 INFO sqlalchemy.engine.base.Engine ('구립 은아새 어린이집', '이영자', '서울특별시 은평구 불광천길 470-11 (응암제3동)', '02', '386', '4498', 22)
2021-08-18 17:41:09,161 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,162 INFO sqlalchemy.engine.base.Engine ('마포어린이집', '안진호', '서울특별시 마포구 양화로18안길 21 ,(동교동) (서교동)', '02', '334', '4743', 13)
2021-08-18 17:41:09,163 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,164 INFO sqlalchemy.engine.base.Engine ('명인어린이집', '이성호', '서울특별시 중랑구 면목로53길 70 ,(면목동) (면목제3.8동)', '02', '434', '4651', 25)
2021-08-18 17:41:09,165 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,169 INFO sqlalchemy.engine.base.Engine ('역삼가애어린이집', '서혜진', '서울특별시 강남구 도곡로37길 15 ,(역삼동) (역삼제2동)', '02', '568', '1623', 1)
2021-08-18 17:41:09,170 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,171 INFO sqlalchemy.engine.base.Engine ('성동어린이집', '황도현', '서울특별시 광진구 능동로3마길 1 ,(자양동, 자양) (자양제4동)', '02', '463', '0942', 6)
2021-08-18 17:41:09,172 INFO sqlalchemy.engine.base.Engine INSERT INTO daycare_center (name, chief_staff_name, address, ph_num1, ph_num2, ph_num3, loc_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2021-08-18 17:41:09,172 INFO sqlalchemy.engine.base.Engine ('항동어린이집', '전영자', '서울특별시 구로구 연동로 284 (항동)', '02', '2614', '4459', 7)
2021-08-18 17:41:09,269 INFO sqlalchemy.engine.base.Engine COMMIT

In [35]:
violence_vid_name = [
    '태양하나어린이집_2021-08-18_16:47:52 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:04 PM.mp4',
    '태양하나어린이집_2021-08-18_16:46:52 PM.mp4'
]
uncertain_vid_name =[
    '태양하나어린이집_2021-08-18_16:46:54 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:05 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:08 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:09 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:13 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:21 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:23 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:26 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:28 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:32 PM.mp4',
    '태양하나어린이집_2021-08-18_16:47:51 PM.mp4'
]

In [36]:
tmp = violence_vid_name[0]

In [39]:
temp = tmp.split('태양하나어린이집_')[-1].split('.mp4')[0]

In [40]:
temp

'2021-08-18_16:47:52 PM'

In [41]:
time.mktime(datetime.datetime.strptime(temp, "%Y-%m-%d_%H:%M:%S PM").timetuple())

1629272872.0

In [44]:
convert_datetime(1629272872)

'2021-08-18 16:47:52'

In [ ]:
np.r

In [56]:
np.random.randint(80,100) + np.random.randint(0,99) * 0.01

99.59

In [58]:
# 0 not check
# 1 checked
# 2 police reported

for vid in uncertain_vid_name[8:]:
    temp = vid.split('태양하나어린이집_')[-1].split('.mp4')[0]
    time_ = time.mktime(datetime.datetime.strptime(temp, "%Y-%m-%d_%H:%M:%S PM").timetuple())
    video = Video(
        detection_time = time_,
        name = vid,
        accuracy = np.random.randint(50,80) + np.random.randint(0,99) * 0.01,
        status = '1',
        loc_id = 11,
        dc_id = 50
    )
    session.add(video)

In [59]:
session.commit()

2021-08-18 18:00:18,416 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 18:00:18,419 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,420 INFO sqlalchemy.engine.base.Engine (1629272814.0, '태양하나어린이집_2021-08-18_16:46:54 PM.mp4', 97.0, '0', 11, 50)
2021-08-18 18:00:18,425 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,426 INFO sqlalchemy.engine.base.Engine (1629272825.0, '태양하나어린이집_2021-08-18_16:47:05 PM.mp4', 95.0, '0', 11, 50)
2021-08-18 18:00:18,428 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,428 INFO sqlalchemy.engine.base.Engine (1629272828.0, '태양하나어린이집_2021-08-18_16:47:08 PM.mp4', 87.0, '0', 11, 50)
2021-08-18 18:00:18,429 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,430 INFO sqlalchemy.engine.base.Engine (1629272829.0, '태양하나어린이집_2021-08-18_16:47:09 PM.mp4', 86.0, '0', 11, 50)
2021-08-18 18:00:18,432 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,432 INFO sqlalchemy.engine.base.Engine (1629272833.0, '태양하나어린이집_2021-08-18_16:47:13 PM.mp4', 93.5, '0', 11, 50)
2021-08-18 18:00:18,433 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,434 INFO sqlalchemy.engine.base.Engine (1629272841.0, '태양하나어린이집_2021-08-18_16:47:21 PM.mp4', 93.94, '0', 11, 50)
2021-08-18 18:00:18,434 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,436 INFO sqlalchemy.engine.base.Engine (1629272843.0, '태양하나어린이집_2021-08-18_16:47:23 PM.mp4', 99.03, '0', 11, 50)
2021-08-18 18:00:18,437 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,437 INFO sqlalchemy.engine.base.Engine (1629272848.0, '태양하나어린이집_2021-08-18_16:47:28 PM.mp4', 95.98, '1', 11, 50)
2021-08-18 18:00:18,438 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,439 INFO sqlalchemy.engine.base.Engine (1629272852.0, '태양하나어린이집_2021-08-18_16:47:32 PM.mp4', 80.93, '1', 11, 50)
2021-08-18 18:00:18,440 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:00:18,440 INFO sqlalchemy.engine.base.Engine (1629272871.0, '태양하나어린이집_2021-08-18_16:47:51 PM.mp4', 80.35, '1', 11, 50)
2021-08-18 18:00:18,441 INFO sqlalchemy.engine.base.Engine COMMIT

In [60]:
# 0 not check
# 1 checked
# 2 police reported

for vid in violence_vid_name:
    temp = vid.split('태양하나어린이집_')[-1].split('.mp4')[0]
    time_ = time.mktime(datetime.datetime.strptime(temp, "%Y-%m-%d_%H:%M:%S PM").timetuple())
    video = Video(
        detection_time = time_,
        name = vid,
        accuracy = np.random.randint(80,100) + np.random.randint(0,99) * 0.01,
        status = '2',
        loc_id = 11,
        dc_id = 50
    )
    session.add(video)

In [61]:
session.commit()

2021-08-18 18:01:27,878 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 18:01:27,879 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:01:27,880 INFO sqlalchemy.engine.base.Engine (1629272872.0, '태양하나어린이집_2021-08-18_16:47:52 PM.mp4', 97.43, '2', 11, 50)
2021-08-18 18:01:27,886 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:01:27,886 INFO sqlalchemy.engine.base.Engine (1629272824.0, '태양하나어린이집_2021-08-18_16:47:04 PM.mp4', 98.89, '2', 11, 50)
2021-08-18 18:01:27,888 INFO sqlalchemy.engine.base.Engine INSERT INTO video (detection_time, name, accuracy, status, loc_id, dc_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:01:27,889 INFO sqlalchemy.engine.base.Engine (1629272812.0, '태양하나어린이집_2021-08-18_16:46:52 PM.mp4', 83.0, '2', 11, 50)
2021-08-18 18:01:27,890 INFO sqlalchemy.engine.base.Engine COMMIT

In [66]:
video1 = ReportList(
    time = 1629272872+ 50,
    police_name = '청량리파출소',
    status = '출동',
    loc_id = 11,
    dc_id = 50,
    vid_id = 11
)
video2 = ReportList(
    time = 1629272824+ 23,
    police_name = '답십리지구대',
    status = '현장 종결',
    loc_id = 11,
    dc_id = 50,
    vid_id = 12
)
video3 = ReportList(
    time = 1629272812 +19,
    police_name = '휘경파출소',
    status = '현장 종결',
    loc_id = 11,
    dc_id = 50,
    vid_id = 13
)

In [72]:
session.add(video1)
session.add(video2)
session.add(video3)
session.commit()

2021-08-18 18:11:51,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-08-18 18:11:51,291 INFO sqlalchemy.engine.base.Engine INSERT INTO report_list (time, police_name, status, loc_id, dc_id, vid_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:11:51,292 INFO sqlalchemy.engine.base.Engine (1629272922, '청량리파출소', '출동', 11, 50, 11)
2021-08-18 18:11:51,297 INFO sqlalchemy.engine.base.Engine INSERT INTO report_list (time, police_name, status, loc_id, dc_id, vid_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:11:51,298 INFO sqlalchemy.engine.base.Engine (1629272847, '답십리지구대', '현장 종결', 11, 50, 12)
2021-08-18 18:11:51,299 INFO sqlalchemy.engine.base.Engine INSERT INTO report_list (time, police_name, status, loc_id, dc_id, vid_id) VALUES (?, ?, ?, ?, ?, ?)
2021-08-18 18:11:51,299 INFO sqlalchemy.engine.base.Engine (1629272831, '휘경파출소', '현장 종결', 11, 50, 13)
2021-08-18 18:11:51,300 INFO sqlalchemy.engine.base.Engine COMMIT

In [71]:
session.rollback()